### PR TITLE
ODC-5954-Clean up code for 4.8 release

### PR DESCRIPTION
**Pull request by makambalaji**
**Jira Id**: https://issues.redhat.com/browse/ODC-5954
**Description**:
Removed the odc related tags

### CODE REVIEW

**Comment by jerolimov** [comment]
This is not my main business. But discussed this changes in slack with @makambalaji and they look good to me.

/lgtm

**Comment by makambalaji** [comment]
> @makambalaji One more file needs removal of `@odc` tags
> https://github.com/openshift/console/blob/ded0de8063bec2e02a07defeb1a050f4c9bf0399/frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature#L260
> 
> 
> https://github.com/openshift/console/blob/ded0de8063bec2e02a07defeb1a050f4c9bf0399/frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature#L269
> 
> 
> https://github.com/openshift/console/blob/ded0de8063bec2e02a07defeb1a050f4c9bf0399/frontend/packages/pipelines-plugin/integration-tests/features/pipelines/pipelines-runs.feature#L281

Removed as part of another pr: https://github.com/openshift/console/pull/9109

**Pull request merged**
