### PR TITLE
ODC-7434: Knative test package update concerning pf5 update

### PR DESCRIPTION
**Pull request by sanketpathak**
**Fix**: [ODC-7434](https://issues.redhat.com/browse/ODC-7434)  [ODC-7528](https://issues.redhat.com/browse/ODC-7528)

**Description**: 
Remove PatternFly classname selectors from knative-plugin integration tests
Add flow improvements

**Test Setup**:

Check the TAGS in frontend/packages/knative-plugin/integration-tests/cypress.config.js file be: ""(@knative or @knative-admin or @knative-camelk or @knative-eventing or @knative-kafka or @knative-serverless) and (@pre-condition or @smoke or @regression) and not (@manual or @to-do or @un-verified or @broken-test)'"",

Command to execute:

    export NO_HEADLESS=true && export CHROME_VERSION=$(/usr/bin/google-chrome-stable --version)
    BRIDGE_KUBEADMIN_PASSWORD=YH3jN-PRFT2-Q429c-5KQDr
    BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.dev-svc-4.13-042801.devcluster.openshift.com/
    export BRIDGE_KUBEADMIN_PASSWORD
    export BRIDGE_BASE_ADDRESS
    oc login -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD
    oc apply -f ./frontend/integration-tests/data/htpasswd-secret.yaml
    oc patch oauths cluster --patch "$(cat ./frontend/integration-tests/data/patch-htpasswd.yaml)" --type=merge
    ./test-cypress.sh -p dev-console

**Browser**
Chrome 116

**Test Execution Screenshot:**
Screenshot 2024-03-04 at 10 26 18 PM

### CODE REVIEW

**Comment by The-Anton** [comment]
Test are passing

Screenshot 2024-03-20 at 4 55 56 PM
/lgtm
/approve

**Review by jerolimov — APPROVED** [review]
@The-Anton added lgtm for the integration-test changes. I just approve the ToastProvider data-test line and this lgtm.

/label acknowledge-critical-fixes-only
/approve

**Comment by jerolimov** [comment]
This only affects our integration tests and is written and reviewed by our QE team.

/label qe-approved
/label px-approved
/label docs-approved

**Comment by jerolimov** [comment]
One more time:

/approve

**Pull request merged**
