### PR TITLE
Fine tuned adjustments to transitions to be quicker and smoother

### PR DESCRIPTION
**Pull request by sg00dwin**
Requested changes for
- Adjust .pf-c-page__sidebar nav transition-duration and transition-timing-function
- Adjust .right-side-modal-pf transition-duration and transform origin position

### CODE REVIEW

**Comment by rhamilto** [comment]
So much better!  Nice job, @sg00dwin!

/lgtm

**Comment by spadgett** [comment]
Performance test flake

> StaleElementReferenceError: stale element reference: element is not attached to the page document

/retest

**Comment by spadgett** [comment]
olm flake

/retest

**Pull request merged**
