### PR TITLE
Pipeline Run Details Log Snippet

### PR DESCRIPTION
**Pull request by andrewballantyne**
**Fixes**: 
https://issues.redhat.com/browse/ODC-4196

**Analysis / Root cause**: 
As a user, I'd like to be able to see directly on the Pipeline Run details why it failed instead of having to look into the logs.

**Solution Description**: 
Implement a log snippet in combination with smart condition reading to showcase why a pipeline run has failed.

**Screen shots / Gifs for design review**: 
@openshift/team-devconsole-ux

Updated Build failure so the message is above the log snippet:
Screen Shot 2020-07-13 at 4 23 24 PM

Pipeline referencing a task that does not exist:
Screen Shot 2020-07-13 at 4 23 58 PM

Task that is incomplete:
Screen Shot 2020-07-13 at 4 24 07 PM

Cancelled Pipeline:
Screen Shot 2020-07-13 at 4 24 17 PM

Success Pipeline:
Screen Shot 2020-07-13 at 4 24 31 PM

Pipeline Run failure mid-execution:
Screen Shot 2020-07-13 at 4 23 48 PM

Animation of the above failure:
LogFailureAndPodLoad

**Unit test coverage report**: 

```
 PASS  packages/dev-console/src/components/pipelineruns/logs/__tests__/pipelineRunLogSnippet.spec.ts
  getLogSnippet successfully parses Pipeline Runs
    ✓ expect to return null if the PLR is malformed (2ms)
    ✓ expect to not try to parse a PLR that has yet to start (lacks status) (1ms)
    ✓ expect to not try to parse a running Pipeline
    ✓ expect to not try to parse a successfully completed Pipeline
    ✓ expect to not try to parse a cancelled Pipeline
    ✓ expect to handle invalid task reference Pipelines (1ms)
    ✓ expect to handle invalid task definition Pipelines (1ms)
    ✓ expect to handle internal errors of the task Pipelines

Test Suites: 1 passed, 1 total
Tests:       8 passed, 8 total

------------------------------------------------------------|----------|----------|----------|----------|-------------------|
File                                                        |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------------------------------------------------|----------|----------|----------|----------|-------------------|
 src/components/pipelineruns/logs/pipelineRunLogSnippet.ts  |    96.15 |    84.62 |      100 |       95 |                18 |
------------------------------------------------------------|----------|----------|----------|----------|-------------------|
```

**Test setup:**

- Pipeline Operator installed
- Scenario "Failure at PLR validation": Any Pipeline that references a task that does not exist
- Scenario "Failure at TR validation": Create the `git-clone` through the Pipeline Builder (it needs a workspace and we have a support gap here)
- Scenario "Failure during run": Use these [set of pipeline resources](https://github.com/andrewballantyne/pipeline-scratch-pad/tree/master/examples/broken-app)

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by jerolimov** [comment]
@andrewballantyne Nice PR! Maybe this in WIP, but I have already two questions:

Can you add some tests for this as well? Maybe for the state extraction?

And could we unify the UI of LogSnippet and LogSnippetFromPod a little bit?

LogSnippet:
logsnippet

LogSnippetFromPod:
logsnippetfrompod

**Comment by andrewballantyne** [comment]
> @andrewballantyne Nice PR! Maybe this in WIP, but I have already two questions:

@jerolimov Thanks for the review!

> 
> Can you add some tests for this as well? Maybe for the state extraction?

Yup, needs to be added - tests are not my concern, I got this in late last night and will write tests today. There is a note in the description for this.

> LogSnippetFromPod:
> logsnippetfrompod

How did you get this to happen? This is a fall back if somehow the container & podName do not align to a pod. Did you delete the pod?

**Comment by bgliwa01** [comment]
To keep consistent with how we display build failures, remove the vertical red line from the details page and add the message section that is shown on build failures

**Comment by andrewballantyne** [comment]
@bgliwa01 Updated the screenshots / code to remove the line. Let me know if the screenshots look good now.

**Comment by andrewballantyne** [comment]
@jerolimov Please re-review. I pulled the log component out... it'll show up in the next PR for the sidebar. Also added tests.

**Pull request merged**
