### PR TITLE
[release-4.9] OCPBUGS-2173: do not show NodesUpdateGroup if there are 0 nodes

### PR DESCRIPTION
**Pull request by rhamilto**
Manual back port of https://github.com/openshift/console/pull/12061

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by yapei** [comment]
Before:
Screen Shot 2022-10-26 at 09 53 15

After:
Screen Shot 2022-10-26 at 09 54 08
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
