### PR TITLE
CONSOLE-3081: Integrate dark theme - fix(background-color): updates to --pf-global--BackgroundColor—200

### PR DESCRIPTION
**Pull request by mattnolting**
For: https://issues.redhat.com/browse/CONSOLE-3081
fix(background-color): updates to --pf-global--BackgroundColor—200
This PR updates 

- --pf-global--palette--black-150
- --pf-global--palette--black-200
- --pf-global--BackgroundColor--light-300
- --pf-global--Color--light-200
- $pf-global--BorderColor--300
- $pf-color-black-150
- $pf-global--Color--light-200

=> --pf-global--BackgroundColor—200

Color shifts are described here: https://codepen.io/bobcatTaco/pen/NWwVYzq#bc200

Screen Shot 2022-03-09 at 1 20 48 PM

## OCS drawer header - can't locate
https://github.com/openshift/console/pull/11168/files#diff-695c09321efc7eacc249d65a619ef2c4ff717ba564e199d77a99f5113ea77226R24

## Namespaced page
https://github.com/openshift/console/pull/11168/files#diff-bfe7a299ef3e6faa4ef726d3418f4cbb7a30ed0aa3f4372b2affc9586255a84aR11

No change. `background-color` references text color variable `--pf-global--Color--light-200`:

Screen Shot 2022-03-10 at 12 08 41 PM

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/approve
/ok-to-test

**Comment by jcaianirh** [comment]
Propagate from epic:
/label docs-approved
/label px-approved

**Review by vikram-raj — COMMENTED** [review]
Verified the changes locally.

/lgtm

/label qe-approved

**Comment by spadgett** [comment]
This hasn't been tested by QE.

**Comment by mattnolting** [comment]
@jerolimov updated. I removed many of the updates until I have a better understanding where the styles are presented.

**Comment by yanpzhan** [comment]
Checked on admin console with dark theme, no issue is found.
/label qe-approved

**Review by jerolimov — APPROVED** [review]
Tested it locally and don't see any changes, as expected.

/lgtm
/retest

**Pull request merged**
