### PR TITLE
CONSOLE-4291: Consolidate shared Type definitions for CreateSecret in "createsecret/type.ts" file

### PR DESCRIPTION
**Pull request by cyril-ui-developer**

### CODE REVIEW

**Comment by Mylanos** [comment]
/LGTM
/approved 
Good job  @cyril-ui-developer

**Comment by cyril-ui-developer** [comment]
QA Approver:
/assign @yapei

**Review by yapei — COMMENTED** [review]
did some regression testings about secret creations, edits. no regression issues found
/label qe-approved

**Comment by cyril-ui-developer** [comment]
Docs Approver:
/assign @opayne1 
PX Approver:
/assign @reestr

**Pull request merged**
