### PR TITLE
CONSOLE-4117: replace deprecated components in MastheadToolbar

### PR DESCRIPTION
**Pull request by rhamilto**
After

https://github.com/user-attachments/assets/cab25a62-8517-4b85-9de1-cbb9744a0957

https://github.com/user-attachments/assets/764279bd-4adf-46e3-b1ae-95bbba444e04

https://github.com/user-attachments/assets/61f8efd9-e1ca-4128-b8d5-b6a7e6746548

### CODE REVIEW

**Comment by rhamilto** [comment]
Tech debt so manually adding labels:
/label px-approved
/label docs-approved

/assign @yapei
/assign @sg00dwin

**Review by sg00dwin — APPROVED** [review]
Nice work!

/lgtm

**Pull request merged**
