### PR TITLE
Bug 1978425: Consolidate namespaces in plugins

### PR DESCRIPTION
**Pull request by rebeccaalpert**
Consolidated namespaces in console-app and console-shared plugins.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1978425.

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by rebeccaalpert** [comment]
A few front end tests were still using the old namespaces. I just updated those.

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
