### PR TITLE
Bug 2000391: review kubevirt skipped tests

### PR DESCRIPTION
**Pull request by gouyang**

### CODE REVIEW

**Comment by gouyang** [comment]
@pcbailey @yaacov PTAL, I went through the skipped tests, either enable them or move them downstream only.

**Comment by yaacov** [comment]
did you have to move any test downstream ?

**Comment by gouyang** [comment]
> did you have to move any test downstream ?

yes, `ID(CNV-771): create VM from PXE` and  the `quick starts` are marking downstream only now. 
BTW:  A bug was found by moving `quick starts` downstream.

**Pull request merged**
