### PR TITLE
CONSOLE-3244: Make status.HostIP for Pods visible in the OCP Web Console

### PR DESCRIPTION
**Pull request by tvu20**
Addresses https://issues.redhat.com/browse/CONSOLE-3244

Adds Host IP field to Pods details page.

### CODE REVIEW

**Review by jcaianirh — CHANGES_REQUESTED** [review]
I think you need to add the string to the localization file here...jsut run:
yarn run i18n

**Review by jcaianirh — APPROVED** [review]
/lgtm

**Comment by jcaianirh** [comment]
QE Approver:
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

Console Approver:
/assign @rhamilto

**Review by jhadvig — APPROVED** [review]
/approve

**Review by RickJWagner — APPROVED** [review]
Looks good.  Adding 'px-approved'.

**Comment by yapei** [comment]
@XiyunZhao will test the PR

**Comment by XiyunZhao** [comment]
This PR has been tested on the private build without any issue, test case is ready for review
/label qe-approved

**Pull request merged**
