### PR TITLE
Bug 1798288: fixes sbr to work with knative service

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes**: 
https://issues.redhat.com/browse/ODC-2791

**Analysis / Root cause**: 
Currently, on hover on Revisions, we show connector which can be dropped to an Operator backed service which in turn creates Service Binding Request which is incorrect sbr should be created via knative service and in turn revisions should be rolled out

**Solution Description**: 
Service Binding Request would be from knative Service i.e on hover for knative service show connector which can be dropped to an Operator backed service which in turn creates Service Binding Request and inject required info in service.

**Screen shots / Gifs for design review**: 
On expand state: 

ezgif com-video-to-gif (20)

On Collapse state:

ezgif com-video-to-gif (21)

**Browser conformance**: 
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

cc @openshift/team-devconsole-ux @serenamarie125

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
Verified locally with **kubeadmin** and **non-admin (view only)** users. Services are now having connectors and revisions does not.

/lgtm

**Comment by jeff-phillips-18** [comment]
@Veethika @serenamarie125 Should we provide the ability to add a connector when the knative service is collapsed?

**Comment by christianvogt** [comment]
@jeff-phillips-18 yes we should.

**Comment by invincibleJai** [comment]
@jeff-phillips-18 @christianvogt pls take a look have handled collapse state as well for the creation of connector and updated gif as well.

**Pull request merged**
