### PR TITLE
ODC-7315: Change help texts in initialize Terminal page

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
**Story**: https://issues.redhat.com/browse/ODC-7315 

**Description**:

Updated the help texts in initiualize terminal page as below

1. "This Project will be used to initialize your command line terminal" to "Project used to initialize your command line terminal"
 
2. "Set timeout for the terminal." to "Pod timeout for your command line terminal"
3. "Set custom image for the terminal." to "Custom image used for your command line terminal
 
 **Screenshots**:
 
 -----Before----
 
 
image

----After----

image

### CODE REVIEW

**Review by vikram-raj — APPROVED** [review]
image

/lgtm

**Comment by sanketpathak** [comment]
Verified on cluster-bot
Screenshot from 2023-05-23 15-33-12
/label qe-approved

**Comment by lokanandaprabhu** [comment]
Propage labels from the epic:

/label docs-approved
/label px-approved

**Pull request merged**
