### PR TITLE
Bug 1907972: Update OCM UI link to open Insights tab

### PR DESCRIPTION
**Pull request by gkarat**
**Related to:**
https://issues.redhat.com/browse/CCXDEV-3520

+ edited OWNERS

### CODE REVIEW

**Comment by gkarat** [comment]
@bond95 @tisnik could you please add me to contributors?

**Review by tisnik — APPROVED** [review]
LGTM

**Review by bond95 — APPROVED** [review]

**Comment by bond95** [comment]
@spadgett could you, please, take a look as well?

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by gkarat** [comment]
@spadgett could you please merge this patch if everything seems fine? I have become an OS collaborator, but don't have write permissions. So I suppose I need to ping you every time I would like to merge patches... :-)

**Comment by gkarat** [comment]
@alecmerdler @jhadvig @rhamilto @bparees could you also please take a look and merge it whether it's possible? (Sam Padgett is on PTO, so trying to ping people who is still available)

**Comment by bparees** [comment]
@gkarat can you open a BZ and associate it w/ this PR?

**Comment by gkarat** [comment]
@bparees done :-)

**Comment by bparees** [comment]
awesome, thank you.

I don't think you should be an approver however, can you separate the OWNERS file update to a separate PR and we can discuss if that's appropriate or not there?

otherwise the change lgtm.

**Comment by gkarat** [comment]
@bparees sure, removed my username for now. If everything is alright, let's merge it :) I will push OWNERS related MR soon and ping you too. Thanks.

**Comment by bparees** [comment]
please squash your commits and then it lgtm.

**Pull request merged**
