### PR TITLE
CONSOLE-2391: Monitoring: Add i18n for Metrics and Dashboards pages

### PR DESCRIPTION
**Pull request by kyoto**

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm
/hold for approvals
/assign @yapei @ahardin-rh @sferich888

**Review by dtaylor113 — APPROVED** [review]
/lgtm

**Comment by schituku** [comment]
hi, the test failed. both pages are not getting translated.  
steps:
  launch a cluster bot for the pr -- launch openshift/console#7266 aws
  change language preferences to other than english
  check Monitoring>Dashboards or Metrics. No translation.
attached screenshot.
Screenshot from 2020-11-20 08-39-05
/cc @yapei

**Comment by kyoto** [comment]
@schituku That is expected because the actual string translations have not been added yet. This PR just makes the strings available for translating, but doesn't include the actual translations.

**Comment by yanpzhan** [comment]
@kyoto  Won't those chart titles be marked for translation on dashboards page?

**Comment by spadgett** [comment]
@yanpzhan No, the dashboard content itself will not be translated at this time. Those are defined in config maps contributed by the monitoring operator and are out of scope for the initial i18n work. What you have in the screenshot is what I would expect.

**Comment by sferich888** [comment]
> @yanpzhan No, the dashboard content itself will not be translated at this time. Those are defined in config maps contributed by the monitoring operator and are out of scope for the initial i18n work. What you have in the screenshot is what I would expect.

If this is the case we need to make sure the release notes for i18n denotes this. @codyhoag can you make sure that we capture this in some way? 

/label px-approved
/unassign @sferich888

**Comment by spadgett** [comment]
> @yanpzhan No, the dashboard content itself will not be translated at this time. Those are defined in config maps contributed by the monitoring operator and are out of scope for the initial i18n work. What you have in the screenshot is what I would expect.

@ahardin-rh -- @sferich888 suggested we should release note this. There are a few other places where things won't be translated as well such as content coming from operators in OperatorHub.

**Comment by codyhoag** [comment]
I have added this to the release notes tracker so we don't miss this https://github.com/openshift/openshift-docs/issues/26801#issuecomment-737266056. @ahardin-rh feel free to mark it as done in the tracker if you take care of the release note. Thanks!

**Comment by kyoto** [comment]
Rebased

**Review by spadgett — APPROVED** [review]
/lgtm

We'll need to wait until our bugs are under our SLO before we can merge.

**Comment by spadgett** [comment]
Removing the hold since we're below our SLO.

/hold cancel

**Pull request merged**
