### PR TITLE
Add workspaces to Pipeline Details Pages

### PR DESCRIPTION
**Pull request by abhinandan13jan**
# Yet to add unit testsTest
# Addresses
https://issues.redhat.com/browse/ODC-4444
# Screenshot
Screenshot from 2021-02-22 19-58-42
Screenshot from 2021-02-22 19-59-06
Screenshot from 2021-02-22 19-58-51
Screenshot from 2021-02-22 19-58-22
Screenshot from 2021-02-22 19-58-34

# PR Test
Add following YAMLs and check the details pages

```
apiVersion: v1
kind: Secret
metadata:
  name: secret-password
type: Opaque
data:
  password: aHVudGVyMg==
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-task-storage
spec:
  resources:
    requests:
      storage: 16Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: fetch-secure-data
spec:
  workspaces:
  - name: super-secret-password
  - name: secure-store
  - name: filedrop
  steps:
  - name: fetch-and-write
    image: ubuntu
    script: |
      if [ "hunter2" = "$(cat $(workspaces.super-secret-password.path)/password)" ]; then
        cp $(workspaces.secure-store.path)/recipe.txt $(workspaces.filedrop.path)
      else
        echo "wrong password!"
        exit 1
      fi
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: print-data
spec:
  workspaces:
  - name: storage
    readOnly: true
  params:
  - name: filename
  steps:
  - name: print-secrets
    image: ubuntu
    script: cat $(workspaces.storage.path)/$(params.filename)
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: fetch-and-print-recipe
spec:
  workspaces:
  - name: password-vault
  - name: recipe-store
  - name: shared-data
  tasks:
  - name: fetch-the-recipe
    taskRef:
      name: fetch-secure-data
    workspaces:
    - name: super-secret-password
      workspace: password-vault
    - name: secure-store
      workspace: recipe-store
    - name: filedrop
      workspace: shared-data
  - name: print-the-recipe
    taskRef:
      name: print-data
    # Note: this is currently required to ensure order of write / read on PVC is correct.
    runAfter:
      - fetch-the-recipe
    params:
    - name: filename
      value: recipe.txt
    workspaces:
    - name: storage
      workspace: shared-data
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: recipe-time-
spec:
  pipelineRef:
    name: fetch-and-print-recipe
  workspaces:
  - name: password-vault
    secret:
      secretName: secret-password
  - name: recipe-store
    configMap:
      name: sensitive-recipe-storage
      items:
      - key: brownies
        path: recipe.txt
  - name: shared-data
    persistentVolumeClaim:
      claimName: shared-task-storage
```

# Tests
yet to add

# Browser conformance
Chrome 88

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
The pipeline run created with `VolumeClaimTemplate` will in-turn create a `PVC` , we should show that created PVC link in the workspace section below, right now it shows the workspace name.

To reproduce this, go through the GIT import flow and check the pipeline option and then visit the pipelineRun details page. 
image

**Comment by karthikjeeyar** [comment]
Resource links should take us to resource details page. 

links-not-working

**Comment by karthikjeeyar** [comment]
@bgliwa01 is working on showing the workspace that uses `Empty Directory`, I think we should align with that for this usecase. I ll let her chime in for more input.

Empty Directory workspace list: 
image

**Comment by bgliwa01** [comment]
> @bgliwa01 is working on showing the workspace that uses `Empty Directory`, I think we should align with that for this usecase. Brigid can chime in here for more input.
> Empty Directory workspace list:
> image

@karthikjeeyar correct me if I am wrong, but I thought that the workspaces in the PLR page were the specific resources (Secret, pvc, config, map- so badge and resource link) or empty directory. On the Pipeline page it should just be the name of the workspace.

**Comment by bgliwa01** [comment]
> @bgliwa01 is working on showing the workspace that uses `Empty Directory`, I think we should align with that for this usecase. Brigid can chime in here for more input.
> Empty Directory workspace list:
> image

working on that design right now...hopefully will have it ready by EOD.

**Comment by abhinandan13jan** [comment]
Apologies getting issue in my local branch and am not able to restore the PR, please look into https://github.com/openshift/console/pull/8238 instead. I will link both

**Pull request closed without merging**
