### PR TITLE
Fix bug where role rule with no resources outputs empty <ResourceIcon>

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://jira.coreos.com/browse/CONSOLE-1216?filter=16409

After:
screen shot 2019-01-17 at 2 35 59 pm

### CODE REVIEW

**Comment by rhamilto** [comment]
jenkins rebuild

**Comment by jhadvig** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
Last failure was flake https://jira.coreos.com/browse/CONSOLE-1214

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
