### PR TITLE
OCPBUGS-14463: Web Terminal e2e tests are failing

### PR DESCRIPTION
**Pull request by musienko-maxim**
After investigating the flakiness of the web terminal after the first run test, I supposed that WTO could not finish the full installation. This PR add check up this on UI part

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
/retitle OCPBUGS-14463: Web Terminal e2e tests are failing

**Review by jerolimov — APPROVED** [review]
@sanketpathak is this fine for you? can you add lgtm then?

/approve

**Comment by sanketpathak** [comment]
The PR needs updation concerning the new pf5 [upgrade](https://github.com/openshift/console/pull/12983)

**Comment by ibuziuk** [comment]
@jerolimov @sanketpathak @The-Anton could you clarify why the PR is not merged?
also, could you prioritize the recent 4.15 issue related to changes in OpenShift console - https://github.com/openshift/console/issues/13696

**Comment by jerolimov** [comment]
Retry this because #13749 is merged.

/retest

**Comment by sanketpathak** [comment]
@musienko-maxim The logout function has been removed so the tests need to be updated
Screenshot 2024-06-05 at 3 28 48 PM

**Comment by sanketpathak** [comment]
@musienko-maxim the CI is failing on web-terminal tests, you can check more in these [screenshots](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_console/12922/pull-ci-openshift-console-master-e2e-gcp-console/1800839131144654848/artifacts/e2e-gcp-console/test/artifacts/gui_test_screenshots/cypress/screenshots/web-terminal-adminuser.feature/)

**Comment by vikram-raj** [comment]
@musienko-maxim PR has conflicts. It needs to rebase the PR. Can you PTAL? Thanks

**Pull request closed without merging**
