### PR TITLE
Bug 1966487: Update IP address on pods list to show podIP other than …

### PR DESCRIPTION
**Pull request by yapei**
…hostIP

Screen Shot 2021-06-01 at 8 28 13 PM

### CODE REVIEW

**Comment by yapei** [comment]
@spadgett  Could you help review?

**Review by dtaylor113 — APPROVED** [review]
Looks good to me.  Wondering if we want to change the title on the list page from "IP Address" to "Pod IP" to match what is shown on the pod details page: 
image

`<DetailsItem label={t('public~Pod IP')} obj={pod} path="status.podIP" />`

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
> Looks good to me. Wondering if we want to change the title on the list page from "IP Address" to "Pod IP" to match what is shown on the pod details page:
> image
> 
> `<DetailsItem label={t('public~Pod IP')} obj={pod} path="status.podIP" />`

Yes, we should update the details page as well if it's using hostIP. Good catch @dtaylor113 👍 

/lgtm cancel
/hold cancel

**Comment by yapei** [comment]
@spadgett  `Pod IP` on Pod details page is already using podIP not hostIP. It looks like @dtaylor113 requested changing the column title `IP address` to `Pod IP` on pods list page
|Name|IP address| Pod IP|
| ------------- | ------------- | ------------- |
|test-pod| 10.x.x.x| 10.x.x.x |

**Comment by yapei** [comment]
@spadgett could you PTAL?

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
