### PR TITLE
CONSOLE-4140: display URI decoded configuration files on MachineConfi…

### PR DESCRIPTION
**Pull request by rhamilto**
…g details page

https://github.com/openshift/console/assets/895728/bd01f69b-acbd-4c34-843b-975fb25a718c

### CODE REVIEW

**Comment by rhamilto** [comment]
Code Approver:
@sg00dwin 
UXD Approver:
@nirfarkas 
QA Approver:
/assign @yapei
Docs Approver:
/assign @opayne1
PX Approver:
/assign @RickJWagner

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

Thanks @rhamilto 🚀

**Review by RickJWagner — COMMENTED** [review]
Looks good.  Thanks for the nice functionality.  (Thanks also for the screencast to help with the review.)

**Comment by yapei** [comment]
@rhamilto Shall we display the configuration files content with a scroll bar? Large configuration files make the page really large

**Comment by rhamilto** [comment]
@jhadvig, please re-tag.

**Review by sg00dwin — APPROVED** [review]

**Comment by yapei** [comment]
@rhamilto Shall we also remove `data:,` prefix when displaying so that the content will be in valid format?

**Comment by jhadvig** [comment]
> @rhamilto Shall we display the configuration files content with a scroll bar? Large configuration files make the page really large
I would leave that as is it, to have the same exp. as from ConfigMaps

> Shall we also remove data:, prefix from all content so that the content will be in valid and more user friendly format?

Yes, lets trim that prefix

**Comment by rhamilto** [comment]
> > @rhamilto Shall we display the configuration files content with a scroll bar? Large configuration files make the page really large
> > I would leave that as is it, to have the same exp. as from ConfigMaps
> 
> > Shall we also remove data:, prefix from all content so that the content will be in valid and more user friendly format?
> 
> Yes, lets trim that prefix

Done.  And updated the video in the PR description to show the latest changes.

**Comment by yapei** [comment]
@rhamilto  Thanks for your continuous updates, now everything looks good enough
/label qe-approved

**Review by jhadvig — APPROVED** [review]
/lgtm

**Pull request merged**
