### PR TITLE
CONSOLE-3812: remove packages/ceph-storage-plugin/integration-tests

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by rhamilto** [comment]
Work is tech debt and has no customer-facing impact.

/label docs-approved
/label px-approved
/label qe-approved

**Review by bipuladh — APPROVED** [review]
/lgtm

**Review by bipuladh — APPROVED** [review]

**Comment by rhamilto** [comment]
@bipuladh, mind re-tagging?  I overlooked [a file that was using const.ts](https://github.com/openshift/console/compare/045f6a597fe18325e70c34ddaab40d3e2dd2c8db..9e0adab8bceb937fe3ff6d0b748e0ff47579661f).

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
