### PR TITLE
[Dark Theme]: fix dark theme issues in pipeline task visualization

### PR DESCRIPTION
**Pull request by vikram-raj**
**Story:** https://issues.redhat.com/browse/ODC-6677

**Descriptions:**
- Fixes dark theme issues in pipeline task visualization.

**Before:**
image

**After:**
image

**Before:**
image

**After:**
image

**Before:**
image

**After:**
image

### CODE REVIEW

**Review by sg00dwin — APPROVED** [review]

**Comment by karthikjeeyar** [comment]
Thanks @vikram-raj looks good!

We need to fix the when expression node as well.

image

**Review by karthikjeeyar — APPROVED** [review]
Thanks @vikram-raj .I have verified on the clusterbot and this looks great. 


image
/lgtm
/label qe-approved

**Comment by vikram-raj** [comment]
Propagating docs and px acks from the Epic
/label docs-approved
/label px-approved

**Pull request merged**
