### PR TITLE
Remove noButton option from dropdown to fix accessibility issue

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes bug where dropdowns without buttons (e.g., namespace picker) do not open on press of Enter key.

### CODE REVIEW

**Comment by rhamilto** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
Is there a way we can get rid of the `noButton` prop instead and always use a button (styled however we like)? Is `noButton` only for styling?

**Comment by rhamilto** [comment]
> Is there a way we can get rid of the noButton prop instead and always use a button (styled however we like)? 

I will investigate.  I took this approach because it was the most risk averse.

> Is noButton only for styling?

Appears so.

**Comment by rhamilto** [comment]
Take 2 with the elimination of noButton.

**Comment by rhamilto** [comment]
jenkins rebuild

**Comment by rhamilto** [comment]
jenkins rebuild

**Comment by rhamilto** [comment]
Fixed filter integration test failure.  PTAnotherLook, @spadgett.

**Pull request merged**
