### PR TITLE
Bug 1906877: Update name filter placeholder for vulnerability list

### PR DESCRIPTION
**Pull request by vikram-raj**
**Fixes**: 
https://issues.redhat.com/browse/ODC-5185

**Analysis / Root cause**: 
Placeholder's value in search filter does not match column' headings in Vulnerability tab and ImageManifestVuln details page

**Solution Description**: 
Update name filter placeholder for vulnerability list

**Screen shots / Gifs for design review**: 
image
image

### CODE REVIEW

**Comment by vikram-raj** [comment]
/retitle Bug 1906877: Update name filter placeholder for vulnerability list

**Comment by invincibleJai** [comment]
/lgtm

verified the changes

**Comment by itsptk** [comment]
> image

Ideally the search field text would read **Search by image name...**

> image

From [this comment](https://issues.redhat.com/browse/ODC-5185?focusedCommentId=15527390&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-15527390), I was expecting the **Vulnerabilities** column on the Vulnerabilities table to become **Name**, and the search field to read **Search by name...**

Thanks.

**Comment by vikram-raj** [comment]
image
image

@itsptk Updated it. PTAL again.

**Review by jerolimov — APPROVED** [review]
Tested it on cluster 4.7.0-0.nightly-2020-12-15-223602 with Quay Container Security 3.3.1 and a local console.

Works fine :+1:

/lgtm

**Comment by itsptk** [comment]
> @itsptk Updated it. PTAL again.

LGTM thanks!

**Review by itsptk — APPROVED** [review]

**Pull request merged**
