### PR TITLE
kubevirt: move and refactor v2v requests from kubevirt-web-ui-components 

### PR DESCRIPTION
**Pull request by suomiy**
```
- remove kubevirtInterOP function
- make PersistentVolumeClaimWrapper use init
- add hook onVMCreate to createVM function
- add wrappers for used K8s objects
- use Wrappers and PatchBuilder
- introduce DeploymentWrapper
- move and refactor createV2VvmwareObject

- fix parseNumber
- add vm owner references to the storage
+ few other bug fixes
```

### CODE REVIEW

**Comment by suomiy** [comment]
component/core label not relevant - committed by mistake

/remove-label component/core

**Comment by mareklibra** [comment]
Thank you for moving this last bit from `kubevirt-web-ui-components` here.

I have bunch of comments/concerns regarding readability and maintainability of the code after refactoring but they are relevant to other parts of recent plugin's codebase so I will not block  review on this here.

I prefer using less wrappers and abstraction while keeping the code both clean and simple, so future maintainers and contributors can step into it easily.

**Comment by mareklibra** [comment]
/lgtm  
per my previous comment

**Comment by suomiy** [comment]
> I have bunch of comments/concerns regarding readability and maintainability of the code after refactoring but they are relevant to other parts of recent plugin's codebase so I will not block review on this here.
> 
> I prefer using less wrappers and abstraction while keeping the code both clean and simple, so future maintainers and contributors can step into it easily.

The recent refatoring (https://github.com/openshift/console/pull/4321, https://github.com/openshift/console/pull/4696 and partially here) and the current solution of wrappers (and abstraction) were discussed by the team and this was decided to be the best approach.

Please start a discussion if you have such concerns , to fix the things we might have missed.

**Pull request merged**
