### PR TITLE
Bug 1993148: Monitoring: Memoize some components and other optimizations

### PR DESCRIPTION
**Pull request by kyoto**
- Move some constants outside of their components.
- Memoize `rows` when generating the dashboards page
- Prevent unnecessary update of the variable's URL GET param when the
  value has not actually changed.

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
/lgtm cancel

Need to run `yarn i18n`

**Comment by kyoto** [comment]
Thanks @spadgett, I ran `yarn i18n`

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
