### PR TITLE
Add yaacov to kubevirt approvers

### PR DESCRIPTION
**Pull request by rawagner**
@mareklibra @suomiy @yaacov

### CODE REVIEW

**Comment by suomiy** [comment]
congrats!

/lgtm

**Comment by yaacov** [comment]
/hold

Trying to stop the bot from triggering, until tests fixed,

**Comment by spadgett** [comment]
/hold
e2e-gcp-console is currently broken

**Comment by spadgett** [comment]
/override ci/prow/e2e-gcp-console 
OWNERS change only and the test is currently broken

**Pull request merged**
