### PR TITLE
Update icon tooltip text from "Topology View" to "Graph View" 

### PR DESCRIPTION
**Pull request by divyanshiGupta**
**Fixes:** https://issues.redhat.com/browse/ODC-5355

Screenshot from 2021-01-21 21-26-31

/kind bug

cc: @openshift/team-devconsole-ux

### CODE REVIEW

**Review by andrewballantyne — APPROVED** [review]

**Review by jeff-phillips-18 — APPROVED** [review]

**Comment by andrewballantyne** [comment]
cc @rishumehra

**Review by bgliwa01 — APPROVED** [review]
lgtm

**Pull request merged**
