### PR TITLE
fix: build image selector overflows text

### PR DESCRIPTION
**Pull request by vikram-raj**
Bug fix - https://jira.coreos.com/browse/ODC-1184

Before:
Screenshot from 2019-07-02 17-35-01

After:
Screenshot from 2019-07-03 11-26-06

### CODE REVIEW

**Comment by vikram-raj** [comment]
cc: @serenamarie125 @openshift/team-devconsole-ux

**Comment by rohitkrai03** [comment]
@vikram-raj Removing the height makes all the cards have different height and it looks very inconsistent. cc: @serenamarie125

**Comment by rhamilto** [comment]
> @vikram-raj Removing the height makes all the cards have different height and it looks very inconsistent. cc: @serenamarie125

And the problem will return if there are three lines of text.  We solved for this in the service catalog with the following:
https://github.com/openshift/origin-web-catalog/blob/master/src/styles/services-view.less#L27-L36
https://github.com/openshift/origin-web-catalog/blob/master/src/styles/services-view.less#L108-L129

**Comment by christianvogt** [comment]
@vikram-raj use a min-height along with `line-clamp`. https://caniuse.com/#search=line-clamp

Ensure that the bottom padding is always consistent no matter how many lines of text there are though.

**Comment by vikram-raj** [comment]
@christianvogt @rhamilto I uses the ```line-clamp``` property to truncate the title on the 2nd line and set the ```min-height``` of the card to ```118px```.

**Pull request merged**
