### PR TITLE
handle issue while fetching labels for revisions

### PR DESCRIPTION
**Pull request by invincibleJai**
- handle the issue while fetching labels for revisions

Tracks: https://jira.coreos.com/browse/ODC-1420

### CODE REVIEW

**Comment by christianvogt** [comment]
So if the label isn't there, what's shown in the column?

Maybe omit rendering the `ResourceLink` if the service label isn't available?

**Comment by invincibleJai** [comment]
@christianvogt if label isn't there it shows as below

Screenshot 2019-07-23 at 10 06 30 PM

**Comment by invincibleJai** [comment]
It looks as below post omiting rendering of `ResourceLink` if the service label isn't available and have updated PR

Screenshot 2019-07-23 at 10 11 15 PM

**Pull request merged**
