### PR TITLE
Add Azure Red Hat OpenShift branding option

### PR DESCRIPTION
**Pull request by rhamilto**
cc: @jim-minter, @y-cote 

localhost_9000_status_ns_default
localhost_9000_status_ns_default 1
localhost_9000_status_ns_default iphone x

### CODE REVIEW

**Comment by spadgett** [comment]
We'll need to update openshift/api too. cc @benjaminapetersen 

https://github.com/openshift/api/blob/master/operator/v1/types_console.go#L41-L55

**Comment by spadgett** [comment]
Also https://github.com/openshift/console-operator/pull/152

cc @zherman0

**Comment by zherman0** [comment]
@spadgett - azure has been added to console-operator

**Comment by rhamilto** [comment]
Rebased.  @spadgett, PTAL.

**Comment by jim-minter** [comment]
thanks @rhamilto @spadgett !

**Pull request merged**
