### PR TITLE
[release-4.17]OCPBUGS-44183: Remove ClusterTask dependency in console from Pipelines 1.17

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
Manual cherrypick of PR - https://github.com/openshift/console/pull/14349

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Working fine. Tested locally by updating the version to 1.16 since Pipelines 1.17 build is not available yet. 

`const IS_PIPELINE_OPERATOR_VERSION_1_17_OR_NEWER =
    operatorVersion?.major === 1 && operatorVersion?.minor >= 16;`
    

https://github.com/user-attachments/assets/1c9a6cf7-fcdc-47a0-abca-719e746009cd

**Review by vikram-raj — COMMENTED** [review]
/label backport-risk-assessed

/lgtm
/approve

**Pull request merged**
