### PR TITLE
ODC-7283: Add Terminal tab in cluster configuration page

### PR DESCRIPTION
**Pull request by jerolimov**
**Fixes:** https://issues.redhat.com/browse/ODC-7283

It incl. the extraction of the web terminal-related stuff into a static plugin.

This is a rebase of @lokanandaprabhu PR #12718 and fixes two simple import conflicts:

### Merge conflict in `public/components/masthead-toolbar.jsx`:

merge conflict 1

### Merge conflict in `packages/webterminal-plugin/src/components/cloud-shell/CloudShellMastheadButton.tsx`:

merge conflict 2

The rebase kept the original author. We have a follow-up story ([ODC-7308](https://issues.redhat.com/browse/ODC-7308)) to add additional e2e tests.

/cc @lokanandaprabhu @vikram-raj

### CODE REVIEW

**Comment by jerolimov** [comment]
Propage labels from the epic:

/label docs-approved
/label px-approved

**Review by vikram-raj — COMMENTED** [review]
Verified it on the cluster bot and as a user I can successfully update the timeout and image value in the `DevWorkspaceTemplate` `web-terminal-exec` and `web-terminal-tooling`

/lgtm

**Comment by invincibleJai** [comment]
closed this https://github.com/openshift/console/pull/12807 in favour of https://github.com/openshift/console/pull/12718

feel free to reopen it if required

**Pull request closed without merging**
