### PR TITLE
ODC-7381: deps: update @patternfly/quickstarts to 5.3.0

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

Resolves tech debt https://issues.redhat.com/browse/ODC-7381

**Analysis / Root cause**: 

The @patternfly/quickstarts dep was updated without removing the duplicated file.

**Solution Description**: 

I updated @patternfly/quickstarts to the latest version and then removed the duplicated file

**Screen shots / Gifs for design review**: 

Here is the quick start catalog page still working after my changes

https://github.com/openshift/console/assets/18614559/4e83ad2b-b1ef-4539-a416-dd60ec316093

**Unit test coverage report**: 

Unchanged

**Test setup:**

None required

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
This looks exactly what we wanted to do with the tech debt issue. Thanks :+1:

I didn't tested it yet myself, so no lgtm right now, but I like to apply the other labels since this doesn't change anything related to docs or the product itself.

/approve
/label docs-approved
/label px-approved
/cc @sanketpathak

**Review by vikram-raj — APPROVED** [review]
Verified it on the cluster bot


https://github.com/openshift/console/assets/2561818/655c9678-9fbe-49dd-8dc3-6affdefbee48

/lgtm

**Comment by sanketpathak** [comment]
Verified on a cluster with admin and non-admin users
Screenshot 2024-06-21 at 6 47 08 PM

/label qe-approved

**Pull request merged**
