### PR TITLE
visualisation of KameletBiding in topology

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes**: 
https://issues.redhat.com/browse/ODC-5126

**Analysis / Root cause**: 
KameletBinding are not shown in topology

**Solution Description**: 
- Visualise `KameletBinding` in topology as other sources
- Show custom icons as provided 
- Show associated sidebar details and resources tab
- In subscriber sidebar (KSVC/Channel etc) show kameletBinding in sidebar if sinking
- Show default kebab action with option to `MoveSink`
- support all gestures as supported by eventSources

**Screen shots / Gifs for design review**: 

- Visualise KameletBinding
image

- Kebab options

image

**Unit test coverage report**: 

image

**Test setup:**
- Install Serverless operator and create CR for KnativeServing, KnativeEventing
- Install Red Hat Integration - Camel K 1.2.0 provided by Red Hat, If installed globally create CR for IntegrationPlatform 
- Create KSVC and  KameletBinding via yaml
```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: example-telegram-source
  namespace: jai-test
spec:
  source:
    ref:
      apiVersion: camel.apache.org/v1alpha1
      kind: Kamelet
      name: telegram-source
    properties:
      authorizationToken: 'token'
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
```

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by christianvogt** [comment]
The event sources list for a URI node does not show the KBs:
image

**Comment by invincibleJai** [comment]
Tanks, have updated it 

image

**Pull request merged**
