### PR TITLE
Correctly continue lines in run-bridge.sh

### PR DESCRIPTION
**Pull request by spadgett**
/assign @jhadvig

### CODE REVIEW

**Comment by spadgett** [comment]
@jhadvig I think this will fix the problem you were seeing with login

**Comment by xiaocwan** [comment]
Do we need `--k8s-mode-off-cluster-skip-verify-tls=true \` for a 502 issue?

**Comment by spadgett** [comment]
> Do we need --k8s-mode-off-cluster-skip-verify-tls=true \ for a 502 issue?

I don't think we should generally since we're passing `--ca-file=examples/ca.crt` and the correct CA file is required for OAuth to work anyway. I'd rather not enable it by default so we can test that the CA file param is working.

Is your master public URL different than your OAuth token URL? Does this request work?

```
$ curl --cacert examples/ca.crt $OPENSHIFT_API
```

You could set `BRDIGE_K8S_MODE_OFF_CLUSTER_SKIP_VERIFY_TLS=true` env var if needed

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
@alecmerdler FYI

```
Failed Specs:

1) Interacting with the etcd OCS : displays etcd OCS in "Available Applications" view for the namespace
   TimeoutError: Wait timed out after 10002ms
```

**Comment by spadgett** [comment]
OK I dug into this more, and I realize --ca-file is not used to validate the k8s API certificate when running off-cluster. That's unfortunate :(

We can add it back to the run script. Will open a follow on PR

**Comment by spadgett** [comment]
Adding it back in #216

We might want a flag for passing the ca file in off-cluster mode

**Pull request merged**
