### PR TITLE
ODC-5922-pipeline workspaces script fixes

### PR DESCRIPTION
**Pull request by makambalaji**
Jira Id : https://issues.redhat.com/browse/ODC-5922

**Dependencies**: https://github.com/openshift/console/pull/9195

Browser & its version : Chrome 89

**Setup**:
Update the [script](https://github.com/openshift/console/blob/master/frontend/packages/pipelines-plugin/integration-tests/package.json#L11) in package.json  as  `"test-cypress-headless": "node --max-old-space-size=4096 ../../../node_modules/.bin/cypress run --env openshift=true --browser ${BRIDGE_E2E_BROWSER_NAME:=chrome} --headless cypress:cli,cypress:server:specs --spec \"features/*/pipelines-workspaces.feature\";"` in 

Execution Commands:
In below commands, please update url and password based on the cluster

```
export NO_HEADLESS=true && export CHROME_VERSION=$(/usr/bin/google-chrome-stable --version)
BRIDGE_KUBEADMIN_PASSWORD=YH3jN-PRFT2-Q429c-5KQDr
BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.dev-svc-4.8-042801.devcluster.openshift.com
export BRIDGE_KUBEADMIN_PASSWORD
export BRIDGE_BASE_ADDRESS
oc login -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD
oc apply -f ./frontend/integration-tests/data/htpasswd-secret.yaml
oc patch oauths cluster --patch "$(cat ./frontend/integration-tests/data/patch-htpasswd.yaml)" --type=merge
./test-cypress.sh -p pipelines -h true
```
**Screenshots**
image

### CODE REVIEW

**Comment by makambalaji** [comment]
/hold
Addressing https://issues.redhat.com/browse/ODC-5822 is required in this pr

**Review by gajanan-more — APPROVED** [review]
Screenshot from 2021-06-03 12-38-24


Worked as expected

/lgtm

**Comment by gajanan-more** [comment]
Screenshot from 2021-06-11 16-00-55

Working as expected

/lgtm

**Pull request merged**
