### PR TITLE
Bug 1872092:  Make 'Volume Snapshot *' labels consistent

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1872092

Note I did not add `Volume` to `Snapshot Class` and `Snapshot Content` on the Volume Content and Volume Snapshot Content table headers in order to keep them shorter.

### CODE REVIEW

**Comment by yapei** [comment]
@rhamilto  Hi, trying to verify the fix before PR is merged

**Comment by yapei** [comment]
1. on Create VolumeSnapshot form page, 'Volume Snapshot Class' dropdown shows 'Select volume snapshot class'
2. on Volume Snapshots Details page, it shows  a field 'Volume Snapshot Class' and links with a 'vsc' icon
3. on Volume Snapshot Class Details page, the heading is shown as 'Volume Snapshot Class Details' , it shows a field 'Volume Snapshot Class' and links with a 'vsc' icon
4. on Volume Snapshot Content Details page, the heading is shown as 'Volume Snapshot Content Details' it shows a field 'Volume Snapshot Class' and links with a 'vsc' icon

But on `Volume Snapshots` lists page, the table heading is still showing `Snapshot Class` while it should be `Volume Snapshot Class`

**Comment by yapei** [comment]
Screen Shot 2020-08-26 at 7 53 46 PM

**Comment by rhamilto** [comment]
> But on `Volume Snapshots` lists page, the table heading is still showing `Snapshot Class` while it should be `Volume Snapshot Class`

@yapei, [as noted above](https://github.com/openshift/console/pull/6429#issue-473171341), I intentionally left the table header instances unchanged due to the length of the labels.  Adding `Volume` makes those column headers significantly longer, making the table columns narrower.  If you feel strongly, I'm happy to change it, but we may need to drop a right-most column or two at various viewport sizes.

**Comment by yapei** [comment]
yeah you are right, I just forgot about that sentence.  Sorry

**Pull request merged**
