### PR TITLE
OCPBUGS-5773: Delete secret on async run error

### PR DESCRIPTION
**Pull request by Kartikey-star**
In order to return error s occured during async isntall/upgrade a secret is created to log the error. This secret is then returned in the timeout duration of the api. If an error occurs later then this secret is not being deleted. This PR deletes that secret created after 15 seconds.
Signed-off-by: Kartikey Mamgain <mamgainkartikey@gmail.com>

### CODE REVIEW

**Review by dperaza4dustbit — APPROVED** [review]
/lgtm

**Comment by sanketpathak** [comment]
UI works fine, tested on cluster created on pr
/qe-approved

**Pull request merged**
