### PR TITLE
kubevirt: refactor/fix VMStatus and add standalone VirtualMachineImports to VM list

### PR DESCRIPTION
**Pull request by suomiy**
- refactor VMStatus and introduce VMStatus enum and abstract StatusEnum - (see commit msgs for more details)
- enhance VirtualMachineImport Status (add Pending, etc.)

- fix bugs
  - fix closing popover on status change
  - fix missing VMs on table filter reset 
  - fix actions visibility

- enhance CDI import status
- fix ovirt provider bugs and allign with new API
- customize success result page for import
- make VM/Template list sorted according to Created when going there from Wizard on creation
- pass VMStatus bundle everywhere instead of the resources to get them

### CODE REVIEW

**Comment by suomiy** [comment]
Btw what should be the VMImport shortcut? OVMI does not probably cut it and we are already using VMI. @jelkosz @matthewcarleton 

VM list lists VirtualMachineImports. 

yyy

importing

import

error

error

**Comment by suomiy** [comment]
success result tab in VM Wizard. We can't send them to the VM as it is not created yet and VirtualMachineImport page is not implemeted/not telling much and would have to show notification that the VM is ready and user should go there

uu

CDI import status supports multiple imports with progress at once

aa

@matthewcarleton can you check if the design seems ok to you?

**Comment by pcbailey** [comment]
I'm loving the enums!
/lgtm

**Comment by matthewcarleton** [comment]
> Btw what should be the VMImport shortcut? OVMI does not probably cut it and we are already using VMI. @jelkosz @matthewcarleton
> 
> VM list lists VirtualMachineImports.
> 
> yyy
> 
> importing
> 
> import
> 
> error
> 
> error

It would be nice if we could drop the (red Hat Virtualization) from the list view and only have it on the details popover. If it's required maybe we can use RHV? That's not ideal though.

**Comment by suomiy** [comment]
> It would be nice if we could drop the (red Hat Virtualization) from the list view and only have it on the details popover. If it's required maybe we can use RHV? That's not ideal though.

I changed it to RHV now. Details popover has the short version as well as there are some shared components that need to be changed to implement this. Better to do in followup

**Pull request merged**
