### PR TITLE
OCPBUGS-34595: Clicking Size control in PVC form throws a warning error

### PR DESCRIPTION
**Pull request by cyril-ui-developer**
### Before:

Screenshot 2024-09-25 at 10 13 25 AM

### After:

Screenshot 2024-09-25 at 10 43 21 AM

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
Nice catch 👍 
/lgtm

**Comment by cyril-ui-developer** [comment]
> Nice catch 👍 /lgtm

Thank you. :)

**Pull request merged**
