### PR TITLE
OCPBUGS-6770: Pipeline doesn't render correctly when displayed but looks fine in edit mode

### PR DESCRIPTION
**Pull request by aneeshmbhat**
**Fixes**: 

https://issues.redhat.com/browse/OCPBUGS-6770

**Analysis / Root cause**: 

This issue was caused by an unhandled edge case in the function that generates nodes for the graph, causing it to create unwanted edges for the same

**Solution Description**: 

fixed the issue by making sure the dependencies present in the current node are the only ones that are being used as nearest dependencies

**Screen shots / Gifs for design review**: 

--Before--
render-bad

--After--
Screenshot from 2023-04-13 16-51-24

**Unit test coverage report**: 

NA

**Test setup:**

For the setup, just make sure pipelines operator is installed
Then create a pipeline using the following YAML file, https://github.com/gnunn-gitops/product-catalog/blob/main/components/tekton/pipelines/server/base/server-pipeline.yaml

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Tested in local

/lgtm

**Review by vikram-raj — APPROVED** [review]
/approve

**Pull request merged**
