### PR TITLE
Update CTA and description based on design

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes**: 
https://issues.redhat.com/browse/ODC-5764

**Solution Description**: 
Update CTA and description based on design

**Screen shots / Gifs for design review**: 
@openshift/team-devconsole-ux

image

image

image

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by bmignano** [comment]
@invincibleJai I think the form description we decided on was: "This feature will create a new serverless deployment next to your existing deployment. Other configurations, including the traffic pattern, can be modified in the form." Otherwise looks good!

**Review by bmignano — APPROVED** [review]
LGTM! Thanks, @invincibleJai

**Review by serenamarie125 — APPROVED** [review]
This looks great @invincibleJai

**Comment by debsmita1** [comment]
verified the changes
/lgtm

**Pull request merged**
