### PR TITLE
container section alignment issue in demon-sets workload

### PR DESCRIPTION
**Pull request by cloudbehl**
Signed-off-by: Ankush Behl <cloudbehl@gmail.com>

### CODE REVIEW

**Comment by coreos-ui** [comment]
Can one of the admins verify this patch?

**Comment by coreos-ui** [comment]
Can one of the admins verify this patch?

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by cloudbehl** [comment]
Older
screenshot from 2018-11-14 22-13-28
Fixed
screenshot from 2018-11-14 22-14-01

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
