### PR TITLE
Bug 1741773 - fix Insecure Traffic set when creating a app

### PR DESCRIPTION
**Pull request by vikram-raj**
Bug fix - https://jira.coreos.com/browse/ODC-1658

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
@vikram-raj please capitalize the first letter of other `InsecureTrafficTypes` and `PassthroughInsecureTrafficTypes` as well. Those values have also changed and are now incorrect.

**Comment by vikram-raj** [comment]
> @vikram-raj please capitalize the first letter of other `InsecureTrafficTypes` and `PassthroughInsecureTrafficTypes` as well. Those values have also changed and are now incorrect.

@divyanshiGupta Done.

**Pull request merged**
