### PR TITLE
bump codemirror and promql editor to the last version

### PR DESCRIPTION
**Pull request by Nexucis**
Hi,

Codemirror has been released in a final stable version. 
Following this new release, we also made some changes in Prometheus to be able to publish the package `codemirror-promql` under the npm org `prometheus-io`.

This PR is updating the packages around codemirror. Hopefully next time there is an update on `@prometheus-io/codemirror-promql`, dependabot or similar will be able to handle the update.

### CODE REVIEW

**Comment by kyoto** [comment]
/approve

Appears to just slightly increase the bundle size

**Comment by Nexucis** [comment]
mmm I don't get why this job is failing. It doesn't seem related to the PR.

**Comment by jgbernalp** [comment]
/label px-approved
/label docs-approved
As is a dependency update

**Comment by Tai-RedHat** [comment]
Test the PR with Cluster-Bot, monitoring autocomplete for promQL expression work as expected.

**Pull request merged**
