### PR TITLE
[release-4.7]Bug 1958873: Fix disk replacement during second replacement

### PR DESCRIPTION
**Pull request by afreen23**
This is the manual [cherry-picked](https://github.com/openshift/console/pull/9083/commits) PR to incorporate the fix merged in the following PRs:
https://github.com/openshift/console/pull/8864 ---> [cherry-pick commit](https://github.com/openshift/console/pull/9083/commits/943340920daca6ef1e62c06df2a54fcc98e45f3f)
https://github.com/openshift/console/pull/8880 ---> [cherry-pick commit](https://github.com/openshift/console/pull/9083/commits/601b383870325c108bddaaa10266df9b19227120)
https://github.com/openshift/console/pull/9025 ---> [cherry-pick commit](https://github.com/openshift/console/pull/9083/commits/b4da6c8bf2991f632abd471bed30a5b794ce5924)
4.8 verified BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1957756

### CODE REVIEW

**Comment by afreen23** [comment]
Tested on 4.7 OCS and it is working fine.

**Comment by afreen23** [comment]
/test e2e-gcp-console
ceph tests failing due to https://github.com/openshift/console/pull/9073

**Comment by derekwaynecarr** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 1.00

approved

**Pull request merged**
