### PR TITLE
CONSOLE-2428: i18n for search section of home nav

### PR DESCRIPTION
**Pull request by jcaianirh**
For: https://issues.redhat.com/browse/CONSOLE-2428

Search section only

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
lgtm, we'll need QE review.

Note that I think there is still some work to do to properly lazy load the translations, but we need to investigate. That can be handled separately.

**Comment by spadgett** [comment]
@yapei This is ready for QE review. This PR only covers basic elements of the Home -> Search page like the title and toolbar. It does not cover the list contents itself, which will be handled separately for each resource type.

/assign @yapei @ahardin-rh @sferich888 
for QE/docs/CEE approval

**Comment by ahardin-rh** [comment]
LGTM from the docs side

**Comment by spadgett** [comment]
> LGTM from the docs side

/label docs-approved

**Comment by jcaianirh** [comment]
> /label px-approved
/label px-approved

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
