### PR TITLE
Add messages to node's status card

### PR DESCRIPTION
**Pull request by rawagner**
Screenshot from 2020-04-15 11-15-03
Screenshot from 2020-04-15 10-50-04
Screenshot from 2020-04-15 10-49-37

### CODE REVIEW

**Comment by rawagner** [comment]
> Looking good!
> 
> 1. Could we add unit labels to the top area of the breakdown popover? There could be a mix of `m` (millicores) and `cores` there, so writing those units out would be clearer.

Would be good to have this implemented console-wide. But we still havent done it. I could take a look but until then I think we should just stick with what console uses now (no units for cores, m for milicores)
> 2. The second screenshot shows "total requested" being `5.5` (cores), but the node's "total capacity" is  only `4` (cores). Reading the [docs](https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#how-pods-with-resource-requests-are-scheduled), it seems like the pod scheduler wouldn't/shouldn't allow the total requested to go over the total capacity. Is this just dummy data, a UI bug, or maybe I'm misunderstanding?

@andrewballantyne 
After reading the docs, I would expect the same. These are real data. I'm using query
```
sum(kube_pod_container_resource_requests{node='<node-name>', resource='cpu'})
```
I see all masters having higher requests than capacity. Not happening on workers though.


> 3. The second screenshot also has a red state in the Utilization card but a yellow state in the Status card. I think the two should match, and assuming the `5.5` requested is just dummy data or a bug, that would mean the Utilization card would be yellow as well (for the total limit being `3.9`). The third screenshot seems correct though.

No dummy data, will fix that - if requests are over 100% we will show red state in status card too

**Comment by rawagner** [comment]
/hold
lets wait for https://github.com/openshift/console/pull/4971 to merge first

**Comment by brancz** [comment]
> sum(kube_pod_container_resource_requests{node='<node-name>', resource='cpu'})

Is for sure the wrong query as it includes completed, pending, failed, Pods. This precisely proves my point on the other PR of not reusing queries that have been hardened over the year, but instead re-inventing.

**Comment by rawagner** [comment]
After reading https://github.com/kubernetes/kube-state-metrics/issues/1051 I've updated the requests/limits queries based on https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/8e370046348970ac68bd0fcfd5a15184a6cbdf51/rules/apps.libsonnet#L64-L75 and hopefully didnt mess up.

@brancz 
I agree that we should do a better job at reusing queries. Would it be feasible to request the queries which we need to be included into `kubernetes-mixin` ? Similar to what we have already for namespace `record: 'namespace:kube_pod_container_resource_requests_memory_bytes:sum',` we would request another one for node etc ?

**Comment by spadgett** [comment]
/hold
for #5100

**Pull request merged**
