### PR TITLE
OCPBUGS-5435, OCPBUGS-7111: Don't block console pod startup when managed cluster authenticator can't be initialized

### PR DESCRIPTION
**Pull request by TheRealJon**
Use cluster proxy to initialize managed cluster authenticators, and do it concurrently with goroutines.

### CODE REVIEW

**Comment by jhadvig** [comment]
> (We might need the public endpoints for copy login command and kubeadmin logout, although we could delay those requests until they're needed.)

@spadgett the PR for the Copy login command is [here](https://github.com/openshift/console/pull/12553)

**Comment by TheRealJon** [comment]
> Hey, @TheRealJon. I think this is a good change, but if we want to be able to pierce firewalls, we also need to talk to the OAuth server itself using the service proxy instead of the public URL in the well-known document. Otherwise a firewall between the console pod on the hub cluster and the public OAuth server host will block requests. If we're able to use the service instead of the public endpoints, we can skip discovery entirely on startup since we don't need the public URLs. The service name and namespace are known. I realize this is a larger change, however.
> 
> (We might need the public endpoints for copy login command and kubeadmin logout, although we could delay those requests until they're needed.)

Is this something we want as part of this PR?

**Comment by jhadvig** [comment]
@TheRealJon needs rebase. PTAL

**Comment by TheRealJon** [comment]
Multicluster feature has been deferred. Closing this.

**Pull request closed without merging**
