### PR TITLE
Add new separate suite for release prow job

### PR DESCRIPTION
**Pull request by SSshahan**
@spadgett I removed only annotation tests out of full e2e test suite since I am not very sure which kind of test else is more flaky. Please let me know if any other test you think it should  be remove as well. PTAL, thanks.

### CODE REVIEW

**Comment by spadgett** [comment]
cc @jwforres

**Comment by spadgett** [comment]
Funny enough, the annotation tests flaked on this PR... :)

We need to fix that.

**Comment by SSshahan** [comment]
@spadgett  is it can be merged now?

**Comment by SSshahan** [comment]
@spadgett is it can be merged now?  We can move forward on that release repo pr once this has been merged. Thanks

**Comment by SSshahan** [comment]
@spadgett  could you help to merge it?

**Pull request merged**
