### PR TITLE
 Add 'co-require' class to create forms labels

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @spadgett

### CODE REVIEW

**Comment by spadgett** [comment]
Annotations test flake:

```
1) Modal Annotations : Add numeric Annotation from grid
   StaleElementReferenceError: stale element reference: element is not attached to the page document
```

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
Merge queue is busted. #670 is open to fix

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by jhadvig** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
