### PR TITLE
OCPBUGS-7232: Fixes resource status alignment issue

### PR DESCRIPTION
**Pull request by ciiay**
Fixes [gitops-2450: [UI] Issue with alignment of health status, occurrence, and resource text](https://issues.redhat.com/browse/GITOPS-2450).

signed by: yicai@redhat.com

Screenshot after fix:
Screenshot 2023-01-11 at 3 21 04 PM
Screenshot 2023-01-11 at 3 21 27 PM

### CODE REVIEW

**Comment by ciiay** [comment]
Hi @abhinandan13jan @sahil143 , could you please take a look at this PR?

**Review by jerolimov — APPROVED** [review]
Code looks good but I will test it myself (or someone else do) locally or on a cluster bot.

I cloned your ticket as https://issues.redhat.com/browse/OCPBUGS-7232 to follow our bug tracking and merge process.

/retitle OCPBUGS-7232: Fixes resource status alignment issue
/approve

**Comment by lokanandaprabhu** [comment]
Tested locally.

Screenshot 2023-03-13 at 7 09 22 PM

/lgtm

**Pull request merged**
