### PR TITLE
convert topology SBR sidepanel to use dynamic extensions

### PR DESCRIPTION
**Pull request by sahil143**
fixes: https://issues.redhat.com/browse/ODC-5846, task: https://issues.redhat.com/browse/ODC-6111

ScreenShots:
image
image

### CODE REVIEW

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Comment by sahil143** [comment]
Propagate from epic:
/label docs-approved
/label px-approved

**Comment by invincibleJai** [comment]
/lgtm

verified the changes

**Pull request merged**
