### PR TITLE
VM Detail: add Events tab 

### PR DESCRIPTION
**Pull request by suomiy**

### CODE REVIEW

**Comment by suomiy** [comment]
fyi:

Followup PR for overview tab: #1682 

screenshots:
 
a

b

**Comment by mareklibra** [comment]
If #1682 lands first, this PR will not be needed.
Based on last review comments there, there is difference between filenames here and in #1682 , which will potentially cause merge conflicts.

**Comment by suomiy** [comment]
> If #1682 lands first, this PR will not be needed.
Based on last review comments there, there is difference between filenames here and in #1682 , which will potentially cause merge conflicts.

I don't mind, which ever comes first. But this PR will be still needed due to adding the events tab.

**Comment by spadgett** [comment]
events commit lgtm

/approve
/hold
for #1682

**Comment by suomiy** [comment]
rebased & ready to land

**Pull request merged**
