### PR TITLE
Bug 1896529: Updates to the serverless quicks starts content to fix errors and update areas that have changed based on the new operator release.

### PR DESCRIPTION
**Pull request by jcaianirh**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1896529

Design: https://issues.redhat.com/browse/ODC-5059

Updates to the serverless quicks starts content to fix errors and update areas that have changed based on the new operator release.

### CODE REVIEW

**Comment by beaumorley** [comment]
Thank you @jcaianirh! Sj and I have reviewed. Looks good.

**Comment by jcaianirh** [comment]
@spadgett this is ready for review/merge

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
This will need a Bugzilla bug to be able to cherry-pick back.

**Pull request merged**
