### PR TITLE
NO-JIRA: docs: update dead links in `docs/helm`

### PR DESCRIPTION
**Pull request by logonoff**
Some of the links in the `docs/helm` folder now 404, this PR updates them to their working counterparts. Some other links were outdated (helm repo renamed their `master` branch to `main`), so this PR also updates those links

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Thanks for fixing all these links! Good catch.

I think this is not an official doc, or @opayne1? lgtm, happy to merge it if no one is against it.

/approve

**Comment by jerolimov** [comment]
/retitle NO-JIRA docs: update dead links in `docs/helm`

**Comment by jerolimov** [comment]
/retitle NO-JIRA: docs: update dead links in `docs/helm`

**Comment by opayne1** [comment]
This looks good to me!

/label docs-approved

**Comment by jerolimov** [comment]
Adding lgtm based on Olivias ack on that and px and qe approval because this doesn't touch our product.

/lgtm
/label px-approved
/label qe-approved

**Pull request merged**
