### PR TITLE
CONSOLE-2361: Conversion of Bootstrap text alignment class to PF utility classes

### PR DESCRIPTION
**Pull request by sg00dwin**

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm
/hold for QE approval
/assign @yapei 

@yapei We simply need a regression test to make sure the text alignment still looks correct on these pages.

This PR has no user visible changes, and we have general docs and px approval for this epic. @ahardin-rh @sferich888 FYI

/label docs-approved
/label px-approved

**Comment by XiyunZhao** [comment]
This PR has been verified on private build, no issue found, Recorder some snapshot as below shown
image
image
image
image

**Pull request merged**
