### PR TITLE
More i18n for vm details page

### PR DESCRIPTION
**Pull request by yaacov**
More i18n for virtualization -> virtual machines -> details page

screenshot-localhost_9000-2020 11 18-10_46_00

### CODE REVIEW

**Comment by yaacov** [comment]
@pcbailey @glekner @metalice please review

**Comment by yaacov** [comment]
translation file is created in public directory instead of in our local plugin, set to WIP until this is cleared out.

**Review by pcbailey — COMMENTED** [review]
There are strings in a few files that I think should to be translated, but were in sections that didn't allow me to make per-line comments. I've included the files and lines below.

kubevirt-plugin/src/components/modals/scheduling-modals/dedicated-resources-modal/dedicated-resources-modal.tsx  
Line numbers: 75, 85, 98, 102, 105

frontend/packages/kubevirt-plugin/src/components/modals/scheduling-modals/tolerations-modal/tolerations-modal.tsx
Line numbers: 111, 115, 118, 128, 129

frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-resource.tsx
Line numbers: 48, 52, 61, 66, 74, 94,

**Comment by yaacov** [comment]
@pcbailey +1 thanks

**Comment by yaacov** [comment]
removed WIP, the json file is back in the plugin dir,
I translated by mistake a string in common namesapce that moved the .json file to the common directory.

**Comment by yaacov** [comment]
@pcbailey added the missing translations +1, please re-review

**Pull request merged**
