### PR TITLE
[release-12] OCPBUGS-17530: fix bug where binary secret values are corrupted on edit and add test coverage

### PR DESCRIPTION
**Pull request by jcaianirh**
https://issues.redhat.com/browse/OCPBUGS-17530

### CODE REVIEW

**Comment by jcaianirh** [comment]
Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  e2e/knative-ci.feature                   10:32       15       14        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     10:32       15       14        1        -        -

**Comment by jcaianirh** [comment]
* could not run steps: execution cancelled
  * could not run steps: step e2e-gcp-console failed: "e2e-gcp-console" test steps failed: ["e2e-gcp-console" pod "e2e-gcp-console-test" failed: could not watch pod: context canceled

**Comment by jcaianirh** [comment]
✖  crud/roles-rolebindings.spec.ts          00:50        8        -        1        -        7
1 test failure

**Comment by jcaianirh** [comment]
CRD extensions ConsoleExternalLogLink CRD : deletes the ConsoleExternalLogLink instance
   Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       at listOnTimeout internal/timers.js:554:17
       at processTimers internal/timers.js:497:7
   
   Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       at listOnTimeout internal/timers.js:554:17
       at processTimers internal/timers.js:497:7
   
   Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       at listOnTimeout internal/timers.js:554:17
       at processTimers internal/timers.js:497:7

**Review by jhadvig — APPROVED** [review]
/approve

**Review by jhadvig — APPROVED** [review]
/lgtm

**Pull request merged**
