### PR TITLE
CONSOLE-3614: Remove multicluster code from Bridge

### PR DESCRIPTION
**Pull request by TheRealJon**

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by yanpzhan** [comment]
@TheRealJon I launched a cluster against the pr, and do some regression test from console page, including install acm operators. If there are special checkpoints I need to pay attention to?

**Comment by TheRealJon** [comment]
@yanpzhan This was mostly just removing dead code, so overall regression testing should be sufficient. Consider looking at authentication a little more closely since a lot of the removed code was in that area.

**Comment by TheRealJon** [comment]
px and docs review not needed:
/label px-approved
/label docs-approved

**Pull request merged**
