### PR TITLE
CONSOLE-3776: Add GCP token auth to Infrastructure features filter section in OpertorHub

### PR DESCRIPTION
**Pull request by sg00dwin**
https://issues.redhat.com/browse/CONSOLE-3776

Screenshot 2024-01-30 at 4 36 19 PM

### CODE REVIEW

**Comment by jhadvig** [comment]
QE Approver: 
/assign @XiyunZhao
Docs Approver: 
/assign @opayne1
PX Approver:
/assign @RickJWagner

**Comment by XiyunZhao** [comment]
This PR has been tested via cluster-bot, the checkpoint on the case is pass
/label qe-approved

**Pull request merged**
