### PR TITLE
Remove Mode from Topology view

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes**: 
https://issues.redhat.com/browse/ODC-6485

**Analysis / Root cause**: 
Remove consumption mode from topology, thus MODE itself is not needed

**Solution Description**: 
Remove Mode from Topology view

**Screen shots / Gifs for design review**: 

image

image

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by serenamarie125 — APPROVED** [review]
LGTM!  Thank you

**Comment by invincibleJai** [comment]
@jeff-phillips-18 / @karthikjeeyar PTAL, when you get time. Thanks!!

**Review by vikram-raj — APPROVED** [review]
Verified it locally. And it works as expected.

/lgtm

**Comment by karthikjeeyar** [comment]
Verified on cluster, works as expected 👍

**Comment by invincibleJai** [comment]
/label docs-approved
/label px-approved

Propagating from epic based on ACKs

**Pull request merged**
