### PR TITLE
CONSOLE-3090: [Dark Theme] Convert custom row-filter to use PatternFly ToggleGroup component for styling that is dark theme enabled.

### PR DESCRIPTION
**Pull request by sg00dwin**
Since row-filter uses a toggle for filtering, I've converted it to use https://www.patternfly.org/v4/components/toggle-group/ styling.
cc @vikram-raj @mattnolting

**before**
Screen Shot 2022-04-22 at 10 11 58 AM
Screen Shot 2022-04-22 at 10 12 13 AM

**after**
filter-light
filter-dark

### CODE REVIEW

**Comment by sg00dwin** [comment]
/label docs-approved
/label px-approved

We have docs- and px-approval for the epic.

**Comment by sg00dwin** [comment]
QE Approver:
/assign @yanpzhan

**Comment by mattnolting** [comment]
@sg00dwin This looks awesome!!! Great update. I noticed `toggle group` could potentially break some things when viewport width is limited or there are many items in the `group`, so I opened https://github.com/sg00dwin/console/pull/5 to prevent unwanted layout adjustments.

**Comment by mattnolting** [comment]
Fantastic! 

/LGTM

**Comment by sg00dwin** [comment]
@rhamilto mind retagging. Had to push some changes.

**Comment by rhamilto** [comment]
Changes look good.  Mind squashing?

**Comment by yanpzhan** [comment]
@sg00dwin launched a cluster against the pr, check on the binding api page, the "User" and "Group" box color is white, is it an issue?
Screenshot from 2022-04-26 16-48-47

**Comment by sg00dwin** [comment]
> @sg00dwin launched a cluster against the pr, check on the binding api page, the "User" and "Group" box color is white, is it an issue? Screenshot from 2022-04-26 16-48-47

@yanpzhan that issue will be fixed when https://github.com/openshift/console/pull/11370 merges. So I'll put a hold on this for now and re tag you once it's merged, so you can retest.

**Comment by sg00dwin** [comment]
Hi @yanpzhan https://github.com/openshift/console/pull/11370 has merged so this is ready for qe approval.

**Comment by sg00dwin** [comment]
QE Approver:
/assign @yanpzhan

**Pull request merged**
