### PR TITLE
Replace cluster variable in queries for multi-cluster environments

### PR DESCRIPTION
**Pull request by jgbernalp**
Fixes: https://issues.redhat.com/browse/OU-116

### CODE REVIEW

**Review by spadgett — CHANGES_REQUESTED** [review]
/hold

This value should come from `$cluster` query as set in the Grafana JSON from the dashboard config map:

```
label_values(up{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\"}, cluster)
```

We'll have to debug why the value isn't getting resolved in the code here:

https://github.com/openshift/console/blob/master/frontend/public/components/monitoring/dashboards/index.tsx#L221-L252

@kyoto knows this code the best.

**Comment by jgbernalp** [comment]
@spadgett thnx for checking this. Indeed the value should be derived from the `label_values` expression, but In the dev console the soft-tenancy for prometheus labels is enforced. This adds a `namespace` label to queries which results in an empty list. I changed the solution doing 2 things:

1. For admins, use the `labels/<label_name>/values` endpoint to fill the dropdown
2. For dev users, use the previous `count($1) by ($2)` query. In the case of loading a list of clusters when the console is running in a multi-cluster environment, fallback to the current cluster id if there's no data returned.

cc @kyoto, @vikram-raj, @jerolimov

**Comment by jgbernalp** [comment]
I realized this solution is incomplete as the `useActiveCluster` hook returns only the name. An additional change will be required so we can get the id of the current cluster for the fallback to work

**Comment by kyoto** [comment]
> 1. For admins, use the `labels/<label_name>/values` endpoint to fill the dropdown
> 2. For dev users, use the previous `count($1) by ($2)` query. In the case of loading a list of clusters when the console is running in a multi-cluster environment, fallback to the current cluster id if there's no data returned.

Ideally we would use the `/labels/<label_name>/values` approach for both the admin and dev users. However, I guess this will mean we need to update the backend proxy too.

The code currently uses the `count($1) by ($2)` approach because `/labels` did not support `matchers` at the time.
(Confusingly, the TODO comment says it should use the `/series` API instead once that is available, but in the end the `/labels` API got full support for `matchers`. I think the `/labels` API will now give us what we want and be more performant and less hacky too.)

**Comment by jgbernalp** [comment]
@kyoto But using the `/labels/<label_name>/values` will give admin and dev users access to all the label names regardless of the namespaces they have access to. Do you consider this a security issue by letting all the users know about label values? or you suggest to update backend proxy to add tenancy to the label values endpoint?

**Comment by kyoto** [comment]
> @kyoto But using the `/labels/<label_name>/values` will give admin and dev users access to all the label names regardless of the namespaces they have access to. Do you consider this a security issue by letting all the users know about label values? or you suggest to update backend proxy to add tenancy to the label values endpoint?

Yes, I'm suggesting we update the backend proxy to add tenancy for `/labels` too. That will obviously make it a bigger change, so I don't mean as part of this PR, but probably a better long-term solution.

**Comment by berenss** [comment]
@spadgett @bjoydeep is there any need from ACM Observability on this review?
The original Jira Bug mentioned interaction with ACM but I'm not quite sure how ACM needs to respond.

**Comment by spadgett** [comment]
I'll defer to @kyoto's expertise here.

We'll need to fix this for multi-cluster in 4.13, but is there a way to fallback to the current cluster for now? A smaller fix we can backport? And if there are backend changes needed for multi-cluster, we can add that as a story to the epic.

**Comment by jgbernalp** [comment]
As discussed with the ACM team:
In ACM 2.6.3 and ACM 2.7 stream, the reserved `cluster` label is not used anymore, it was replaced by `managed_cluster`. This feature can be disabled adding an [annotation](https://access.redhat.com/documentation/en-us/red_hat_advanced_cluster_management_for_kubernetes/2.7/html/observability/observing-environments-intro#disabling-forward-alerts) to the MultiClusterObservability CR. Clusters with newer versions don't have the issue, clusters upgraded to newer versions might have the issue as metrics were created with the reserved `cluster` label. In this case, the label should be cleaned manually.

**Pull request closed without merging**
