### PR TITLE
Update yarn.lock

### PR DESCRIPTION
**Pull request by spadgett**
yarn >= 1.10.0 adds integrity hashes to yarn.lock. Commit these changes.

/cc @alecmerdler

### CODE REVIEW

**Comment by spadgett** [comment]
I'd like to commit this separately from #384

**Comment by spadgett** [comment]
@sosiouxme I don't think this impacts downstream product builds. Let me know if I'm mistaken...

**Comment by spadgett** [comment]
/hold
until @sosiouxme weighs in

**Comment by sosiouxme** [comment]
@spadgett As long as yarn 1.9.4 won't choke on the new entries, should be fine, right?

We could update yarn downstream too if needed.

**Comment by spadgett** [comment]
I don't think yarn 1.9 chokes on them, but it seems to *remove* them, however. I wonder if that will add `-dirty` to the version string if it's modifying yarn.lock, which is committed.

We probably need to get everyone on the same yarn version, otherwise we'll constantly be fighting noise in the diffs.

**Comment by spadgett** [comment]
/close

Close for now until we can update our yarn version to 1.10 everywhere

**Pull request closed without merging**
