### PR TITLE
Bug 2063897: Change the tekton hub api endpoint to use v1 api

### PR DESCRIPTION
**Pull request by karthikjeeyar**
**Fixes**: 

[Bug 2063897](https://bugzilla.redhat.com/show_bug.cgi?id=2063897)

**Analysis / Root cause**: 

New versioned API endpoint is released as part of Hub 1.7
**Solution Description**: 

Update the API to use v1 endpoint.

**Screen shots / Gifs for design review**: 

image

**Unit test coverage report**: 

Not changed

**Test setup:**

Visit pipeline builder and add Tasks

### CODE REVIEW

**Comment by invincibleJai** [comment]
/lgtm

verified the change with cluster-bot and could see community tasks.

image

**Comment by jerolimov** [comment]
> verified the change with cluster-bot and could see community tasks.

/label qe-approved

**Pull request merged**
