### PR TITLE
Localize Virtualization nav name

### PR DESCRIPTION
**Pull request by pcbailey**
This PR localizes the Virtualization side navigation tab name.

Screenshot:
Selection_688

### CODE REVIEW

**Comment by pcbailey** [comment]
@yaacov Please review.

**Comment by christianvogt** [comment]
@pcbailey I suggest holding off on this for another day. I will be posting a pr tomorrow to address the dev console nav localization. It uses the `%...%` pattern for extension localization. These keys get localized with a call to `useExtension`. However I didn't implement support for localizing nested extension props which is required by nav which I have fixed on my branch.

**Comment by christianvogt** [comment]
see https://github.com/openshift/console/pull/7341

**Comment by pcbailey** [comment]
@christianvogt Thanks for the heads up. I have updated this PR to use the `%...%` pattern.

**Pull request merged**
