### PR TITLE
Make up missing attributes from example config.

### PR DESCRIPTION
**Pull request by xiaocwan**
@spadgett  Please review, thanks!

### CODE REVIEW

**Comment by coreos-ui** [comment]
Can one of the admins verify this patch?

**Comment by coreos-ui** [comment]
Can one of the admins verify this patch?

**Comment by wjiangjay** [comment]
Will got `502 bad gateway` when no `--k8s-mode-off-cluster-skip-verify-tls=true` for OpenShift with self-sgined tls, since have no `--k8s-mode-off-cluster-ca-file` flags.

**Comment by xiaocwan** [comment]
Oops, found [existed PR](https://github.com/openshift/console/pull/214/files) 
Closing this one.

**Pull request closed without merging**
