### PR TITLE
Bug 1961878: Add Sprint 199 translations

### PR DESCRIPTION
**Pull request by rebeccaalpert**
Uploading ko, zh-cn, and ja translations from Globalization team.

Issues and regressions:
* https://bugzilla.redhat.com/show_bug.cgi?id=1961356
* https://bugzilla.redhat.com/show_bug.cgi?id=1961363
* https://bugzilla.redhat.com/show_bug.cgi?id=1961224
* https://bugzilla.redhat.com/show_bug.cgi?id=1961391

### CODE REVIEW

**Comment by rebeccaalpert** [comment]
Rebased after Sprint 198 translations merged.

**Comment by spadgett** [comment]
@rebeccaalpert Let's start tracking updated translations using Bugzilla bugs as suggested by @sferich888. These should have no px or doc impact. @yapei Let me know if you have concerns with that.

**Comment by yapei** [comment]
> @rebeccaalpert Let's start tracking updated translations using Bugzilla bugs as suggested by @sferich888. These should have no px or doc impact. @yapei Let me know if you have concerns with that.

Sounds good to me

**Comment by rebeccaalpert** [comment]
All set!

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
