### PR TITLE
GITOPS-1438 display resources health and sync status

### PR DESCRIPTION
**Pull request by ciiay**
This PR is for [Epic GITOPS-1307](https://issues.redhat.com/browse/GITOPS-1307), to add sync status to Resources on Environment Details page.

Jira Ticket:
[GITOPS-1438](https://issues.redhat.com/browse/GITOPS-1438) 

Background:
We show several resources in the lower half of the card.   Not all of these resources have healthy status but all of them have sync status.

Now that Routes has a health state, we need to capture this.  We also want to use this epic as well to 'fix' up the original design we had originally - We only showed one status icon for the resource, which is a broken heart. to represent the resource health and sync status. eg. if the user sees this icon, he/she can then go to Argo CD to check what is specifically wrong with the resource(s).

What we should do now is to show both the broken heart for Degraded resources (excluding Progressing, Missing, and Unknown), and a new yellow warning sign for out of sync resources.

So for those resources that do not have a health status, then the broken heart will never be shown.

It should behave as shown below:

- For healthy and sync'ed resources, no icons will be displayed
- For any resources not in "Healthy" status, the broken heart will be displayed
- For out of sync resources, the yellow warning icon will be displayed
- Tool tip for the out of sync resource can say "x of y OutOfSync"
- Tool tip for the not healthy resource can say "x of y Unhealthy"

Preview:
Unhealthy tooltip
OutOfSync tooltip

### CODE REVIEW

**Comment by serenamarie125** [comment]
@beaumorley tagging you here as well. Brigid provided initial designs for this work.

**Comment by serenamarie125** [comment]
@ciiay what's the tooltip for degraded?  I think we agreed on "Unhealthy", can you confirm please? 
FYI @reginapizza

**Comment by andrewballantyne** [comment]
/unassign @invincibleJai 
/assign @andrewballantyne 

I'll take over the review for the approval state.

**Comment by andrewballantyne** [comment]
I tested it as proxy to QE

/label qe-approved
/lgtm

Docs agreed to the PR in slack

/label docs-approved

**Pull request merged**
