### PR TITLE
Bug 1853352: update CDI version to v1beta1

### PR DESCRIPTION
**Pull request by suomiy**

### CODE REVIEW

**Comment by yaacov** [comment]
/hold

kubevirt-plugin test is failing, holding until we know what is the reason

@irosenzw @omril-redhat is the test failing because of a problem in the code ?

cc/ @metalice @rawagner

**Comment by irosenzw** [comment]
@yaacov it looks like a problem in the test infra, I'll dig into this.

**Comment by yaacov** [comment]
/close
will continue in #7640

**Pull request closed without merging**
