### PR TITLE
Delete HPA In-Context

### PR DESCRIPTION
**Pull request by andrewballantyne**
## Built on #6022 - See the 2nd Commit

**Fixes**: 
https://issues.redhat.com/browse/ODC-4270

**Analysis / Root cause**: 
As a user, I want a way to delete an in-context HPA.

**Solution Description**: 
Add a Kebab action and modal to support deleting the associated HPA on a workload.

**Screen shots / Gifs for design review**: 

Screen Shot 2020-07-22 at 7 32 11 AM
Screen Shot 2020-07-22 at 7 32 19 AM

**Unit test coverage report**: 

```
  doesHpaMatch checks if it aligns to a workload
    ✓ expect not to match when hpa does not target workload
    ✓ expect to match when hpa does target workload

------------------------------------------------------------|----------|----------|----------|----------|-------------------|
File                                                        |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
------------------------------------------------------------|----------|----------|----------|----------|-------------------|
  src/components/hpa/hpa-utils.ts                           |    97.26 |    90.63 |      100 |    96.83 |            92,100 |
------------------------------------------------------------|----------|----------|----------|----------|-------------------|
```

**Test setup:**

- Add an HPA to a D/DC Workload that is in Topology
- Use the Kebab action to delete

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by andrewballantyne** [comment]
/hold

Waiting on dependant PR #6022.

**Comment by christianvogt** [comment]
@andrewballantyne the remove action seems to only be available in topology. But not from the resource list or details pages.

**Comment by andrewballantyne** [comment]
> @andrewballantyne the remove action seems to only be available in topology. But not from the resource list or details pages.

🤔  I suppose it probably shows the Add HPA action because it's in with the generics. I'll have to look into that. It was in context, but I guess that means more than Topology.

**Comment by andrewballantyne** [comment]
See https://github.com/openshift/console/pull/6150

**Pull request closed without merging**
