### PR TITLE
Rename CA file router-ca to default-ingress-cert

### PR DESCRIPTION
**Pull request by jhadvig**
After https://github.com/openshift/console-operator/pull/361 is merged this update needs to be merged as well.

/assign @spadgett 

fyi @benjaminapetersen

### CODE REVIEW

**Comment by spadgett** [comment]
hold for https://github.com/openshift/console-operator/pull/361
/hold

**Comment by spadgett** [comment]
Actually, we might be able to merge this now, correct?

**Comment by jhadvig** [comment]
yes, it should be ok, since its a revert of a revert.
@benjaminapetersen thoughts ?

**Comment by benjaminapetersen** [comment]
/retest

```failed to initialize the cluster: Cluster operator machine-config is reporting a failure: Failed to resync 0.0.1-2019-12-10-155846 because: timed out waiting for the condition```

**Comment by benjaminapetersen** [comment]
/lgtm

Yes this should be good now.

**Comment by spadgett** [comment]
/hold cancel
/retest
#3847 has fixed the e2e tests

**Pull request merged**
