### PR TITLE
Added Donut chart inside for ocs installation on attached devices

### PR DESCRIPTION
**Pull request by gnehapk**
Screenshot from 2020-07-24 12-17-13

### CODE REVIEW

**Comment by gnehapk** [comment]
Depends on #6018

**Comment by cloudbehl** [comment]
Selected capacity is confusion as a user I will understand that my cluster will be of the size that is selected but out of those disk on 3 disks will be selected & made available to OCS cluster use.

**Comment by gnehapk** [comment]
v

**Pull request merged**
