### PR TITLE
Bug 1953728: Fix issues related to loading dynamic plugins

### PR DESCRIPTION
**Pull request by vojtechszocs**
This PR includes the following changes:
- #8076 (1st commit): applied as-is (no merge conflicts)
- #8705 (2nd commit): only the fix in `findWebpackModules` function

cc @spadgett @christianvogt  @DaoDaoNoCode

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
@vojtechszocs Backport telemetry dynamic extension to release-4.7 and apply the changes in the PR, it works perfect, thanks @vojtechszocs ! 👏

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
