### PR TITLE
Migrate workload resource actions to new extension based actions

### PR DESCRIPTION
**Pull request by rohitkrai03**
**Fixes**: https://issues.redhat.com/browse/ODC-6230

**Analysis / Root cause**: All workload resource actions need to use new extension based actions in order to update the resource side panel on topology.

**Solution Description**: 
This PR migrate actions for list page and details page of following workload resources - 
- `DeploymentConfig`
- `StatefulSet`
- `DaemonSet`
- `Job`
- `CronJob`
- `Pod`

**Screen shots / Gifs for design review**: No UI changes.

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge

### CODE REVIEW

**Review by sahil143 — COMMENTED** [review]
@rohitkrai03 fro StatefulSets the order of actions seems to be changed
Screenshot 2021-08-05 at 5 29 51 PM
Screenshot 2021-08-05 at 5 29 56 PM

**Comment by rohitkrai03** [comment]
> @rohitkrai03 fro StatefulSets the order of actions seems to be changed
> Screenshot 2021-08-05 at 5 29 51 PM
> Screenshot 2021-08-05 at 5 29 56 PM

@sahil143 Yeah, I am trying to make it consistent in terms of where we place `Edit pod count` for all resources. It's at the top for `Deployment` so I've placed it at the top for all the others as well.

**Review by sahil143 — APPROVED** [review]
/lgtm

verified and tested locally

**Comment by sahil143** [comment]
/lgtm cancel

@rohit I'm seeing this type error with `yarn dev`

```
ERROR in /Users/sahil/workspace/github/openshift/console/frontend/packages/console-shared/src/components/actions/loader/ActionsLoader.tsx(43,65):
TS2345: Argument of type 'ExtensionK8sKindVersionModel' is not assignable to parameter of type 'ExtensionK8sGroupModel'.
  Property 'group' is optional in type 'ExtensionK8sKindVersionModel' but required in type 'ExtensionK8sGroupModel'.
Version: typescript 3.8.3
```

**Comment by invincibleJai** [comment]
> /lgtm cancel
> 
> @rohit I'm seeing this type error with `yarn dev`
> 
> ```
> ERROR in /Users/sahil/workspace/github/openshift/console/frontend/packages/console-shared/src/components/actions/loader/ActionsLoader.tsx(43,65):
> TS2345: Argument of type 'ExtensionK8sKindVersionModel' is not assignable to parameter of type 'ExtensionK8sGroupModel'.
>   Property 'group' is optional in type 'ExtensionK8sKindVersionModel' but required in type 'ExtensionK8sGroupModel'.
> Version: typescript 3.8.3
> ```

verified the changes looks good

@sahil143 am not seeing this on `yarn dev`

**Comment by rohitkrai03** [comment]
> /lgtm cancel
> 
> @rohit I'm seeing this type error with `yarn dev`
> 
> ```
> ERROR in /Users/sahil/workspace/github/openshift/console/frontend/packages/console-shared/src/components/actions/loader/ActionsLoader.tsx(43,65):
> TS2345: Argument of type 'ExtensionK8sKindVersionModel' is not assignable to parameter of type 'ExtensionK8sGroupModel'.
>   Property 'group' is optional in type 'ExtensionK8sKindVersionModel' but required in type 'ExtensionK8sGroupModel'.
> Version: typescript 3.8.3
> ```

@sahil143 I think you might need to pull my latest changes. The PR initially had that issue but i pushed a fix for it this morning.

**Comment by invincibleJai** [comment]
/label qe-approved
/label docs-approved
/label px-approved

added docs-approved on behalf of the docs team as the epic has a doc-ack label.
added px-approved on behalf of the px team as the epic has a px-ack label.
Epic link: https://issues.redhat.com/browse/ODC-5712

**Pull request merged**
