### PR TITLE
OCPBUGS-13204: Fix that customNodeDeployment pipeline YAML script wasn't working

### PR DESCRIPTION
**Pull request by The-Anton**
**Fixes:**

https://issues.redhat.com/browse/OCPBUGS-13204

**Solution Description:**
Removed last applied configuration and other configuration which were causing the YAML script to fail.

**Screen shots / Gifs :**
Before:

https://github.com/openshift/console/assets/51144829/cb929d36-01e5-4a10-b930-2fc2dd5e93c5

 
After the fix: 

https://github.com/openshift/console/assets/51144829/603f30cd-a15b-4cac-b254-fefc352335c9

### CODE REVIEW

**Review by Lucifergene — COMMENTED** [review]
/lgtm

**Comment by jerolimov** [comment]
/retitle OCPBUGS-13204: Fix that customNodeDeployment pipeline YAML script wasn't working

**Review by jerolimov — APPROVED** [review]
I've tested the old and new YAMLs and could confirm the old couldn't be created, while the new one is working fine

/approve

**Comment by jerolimov** [comment]
@The-Anton, anyway, I have one question for that test: Can't we remove the namespace as well so that you install that new resource in the current namespace???

**Pull request merged**
