### PR TITLE
Added dropdown to overview dashboard

### PR DESCRIPTION
**Pull request by cloudbehl**
**Overview Dashboard**
Screenshot from 2019-10-16 16-45-13
Screenshot from 2019-10-16 16-45-05

**Project Dashboard**
Screenshot from 2019-10-21 17-09-24
Screenshot from 2019-10-21 17-09-16

Signed-off-by: cloudbehl <cloudbehl@gmail.com>

### CODE REVIEW

**Comment by rawagner** [comment]
@cloudbehl please update project dashboard utilization card too

**Comment by kyoto** [comment]
/hold
Let's merge https://github.com/openshift/console/pull/2988 first

**Comment by cloudbehl** [comment]
@rawagner  Added dropdown for project dashboard.

**Comment by kyoto** [comment]
@cloudbehl, @rawagner I think this change broke the Cluster Capacity card.

**Comment by rawagner** [comment]
@kyoto @s-urbaniak the card (together with Top Consumers) is going to be removed for 4.3 as all the functionality is included in Utilization

**Pull request merged**
