### PR TITLE
Bug 1996159: Show 404 page only after all dynamic plugins are processed

### PR DESCRIPTION
**Pull request by vojtechszocs**
This PR fixes a race condition in a scenario where a user navigates directly to a plugin-contributed route and Console shows 404 error page until the relevant plugin finishes loading, then re-renders the plugin-contributed page content as expected.

The expected behavior is to wait until all dynamic plugins are processed (i.e. either loaded or failed) before falling back to the 404 error page.

### CODE REVIEW

**Comment by vojtechszocs** [comment]
/label px-approved
/label docs-approved

There are no user visible changes, and we have approval for dynamic plugin APIs.

**Comment by christianvogt** [comment]
looks good

**Review by spadgett — APPROVED** [review]
/lgtm

Let's go with this PR in favor of #9559 since it contains both commits. Since this is a bug fix, we don't need qe approval prior to merging.

**Pull request merged**
