### PR TITLE
ODC-7710: Remove `@console/rhoas-plugin`

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7710

**Analysis / Root cause**: 

`@console/rhoas-plugin` is unmaintained

**Solution Description**: 

Remove it

**Screen shots / Gifs for design review**: 

Before:
image (1)

After:
image

**Unit test coverage report**: 

n/a

**Test setup:**

n/a

**Browser conformance**: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari

### CODE REVIEW

**Comment by logonoff** [comment]
Code review:
/assign @vikram-raj 

Docs Approver:
/assign @opayne1

PX Approver:
/assign @reestr

QA Approver:
/assign @yapei
or 
/assign @sanketpathak 

whoever has the time

**Comment by yapei** [comment]
based on our discussion, @sanketpathak will work on this PR verification

**Review by vikram-raj — COMMENTED** [review]
/lgtm

**Comment by sanketpathak** [comment]
Verified on a cluster with admin and non-admin users
Screenshot from 2024-12-09 15-15-40

/label qe-approved

**Comment by logonoff** [comment]
PR is a blocker for PF6 migration
/label acknowledge-critical-fixes-only

**Review by spadgett — APPROVED** [review]
/approve

**Comment by logonoff** [comment]
Console PM gave approval internally

/label px-approved

**Pull request merged**
