### PR TITLE
Bug  2000689: Expandable section in mirroring card is empty when no image found under a pool

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Issue: https://issues.redhat.com/browse/RHSTOR-2081

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
image

**Comment by GowthamShanmugam** [comment]
Before fix:
image



After fix: 

image

**Review by bipuladh — APPROVED** [review]
/lgtm

**Comment by bipuladh** [comment]
Screenshot from 2021-08-18 10-21-38
Could we decrease the spacing between the two?

**Comment by GowthamShanmugam** [comment]
> Screenshot from 2021-08-18 10-21-38
> Could we decrease the spacing between the two?

Both are hidden when no image is found. When an image is found both are displayed with proper spaceing

**Pull request merged**
