### PR TITLE
Bug 1871767: Add quick start link in dashboard page

### PR DESCRIPTION
**Pull request by rohitkrai03**
**Fixes**: https://issues.redhat.com/browse/ODC-4454

**Analysis / Root cause**: There's no link to quick starts catalog from admin perspective.

**Solution Description**: Add a quick start link in dashboard page of admin perspective.

**Screen shots / Gifs for design review**: 
@openshift/team-devconsole-ux @bmignano 
image

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by christianvogt** [comment]
@rohitkrai03 the user's pref for the visibility of this badge needs to be stored in local storage according to @bmignano

**Comment by rohitkrai03** [comment]
> @rohitkrai03 the user's pref for the visibility of this badge needs to be stored in local storage according to @bmignano

@christianvogt Updated PR to save user preference in local storage.

**Pull request merged**
