### PR TITLE
[release-4.2] Bug 1760044: Console workload show restricted acccess if knative serverless TP1 operator is installed and logged in as non admin

### PR DESCRIPTION
**Pull request by invincibleJai**
This is a cherry-pick of #2905

This pull request references Bugzilla bug 1758628

### CODE REVIEW

**Comment by eparis** [comment]
make sure to reach out to one of the 'approvers' listed above as they will need to help move this forward.
/retest

**Comment by invincibleJai** [comment]
@gijohn pls review this cc @christianvogt

**Pull request merged**
