### PR TITLE
OCPBUGS-7893: show all the legends for Pipeline metrics in PipelineRun TaskRun Duration chart

### PR DESCRIPTION
**Pull request by vikram-raj**
Fixes: https://issues.redhat.com/browse/OCPBUGS-7893

Before: 

https://github.com/openshift/console/assets/2561818/5ecd75f5-778b-4790-aae6-6dcc6f4eb62c

After:

https://github.com/openshift/console/assets/2561818/fe5c1d86-3ec2-4e54-a6d6-03f401004c55

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
I observed page crash couple of times but I am not able to reproduce it always. Once I rerun the pipelinerun and I was present in Metrics page and suddenly page got crashed. 

Screenshot 2023-08-17 at 2 00 52 PM

**Comment by Lucifergene** [comment]
@vikram-raj Do you need to push any more changes? Or shall I verify again?

**Comment by vikram-raj** [comment]
@Lucifergene You can verify it again. Thanks.

**Review by jerolimov — APPROVED** [review]
Tested this locally and it works as expected :+1: 

/lgtm

**Pull request merged**
