### PR TITLE
OCPBUGS-11285: Dynamic plugin translation support for plurals broken

### PR DESCRIPTION
**Pull request by tvu20**
Fixes https://issues.redhat.com/browse/OCPBUGS-11285.

Updates compatibility layer to provide translation for plurals in dynamic plugins.

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
The fix looks good 👍 
@tvu20 could you please add comment that will explain why to translations are needed. Just for future reference.
Thank you

**Comment by tvu20** [comment]
i18next v4 converter functions differently for plurals in 'en' compared to other languages. Therefore, two conversions are needed: one in the correct language, then a second one in English to catch the missing plural cases.

**Comment by jhadvig** [comment]
@tvu20 could you please add it to the code 😄 ?
Sorry for my poor wording.

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
