### PR TITLE
Render icon as a svg instead of img tag to support dark theme

### PR DESCRIPTION
**Pull request by vikram-raj**
**Story:** https://issues.redhat.com/browse/ODC-6676

**Descriptions:**
- Render the icon as a SVG instead of img tag on Add page to support the dark theme

**Screenshots:**
image

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
image

image

Hi @vikram-raj , I noticed one thing from above screenshots, there is styling of vertical-align: -0.125em; for all other menu options except Broker, Channel and Helm Charts. 

This is existing from before not due to your changes but can we corret it here? It looked odd for me so pointing it out.

**Comment by vikram-raj** [comment]
@lokanandaprabhu added `vertical-align`. PTAL again. Thanks

**Comment by lokanandaprabhu** [comment]
> @lokanandaprabhu added `vertical-align`. PTAL again. Thanks

Verified. Thanks.

**Comment by vikram-raj** [comment]
Propagating docs and px acks from the Epic
/label docs-approved
/label px-approved

**Review by jerolimov — APPROVED** [review]
Thanks @vikram-raj :+1: :+1: :+1: 

/approve

**Pull request merged**
