### PR TITLE
CONSOLE-2395: Add language switcher

### PR DESCRIPTION
**Pull request by rhamilto**
Resolves https://issues.redhat.com/browse/CONSOLE-2395

Screen Shot 2020-11-04 at 8 32 34 AM
Screen Shot 2020-11-04 at 8 34 09 AM

Demo to show reactive change (but missing all Japanese translation files except for cluster-settings, so empty strings load for the site chrome when language is changed to Japanese)
UUzthuJBie

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm
/hold for approvals
/assign @yapei @ahardin-rh @sferich888 

👍

**Review by dtaylor113 — APPROVED** [review]

**Comment by yanpzhan** [comment]
@rhamilto I checked on cluster against the pr, on the language switcher dropdown list, only "English" language is listed, no "Japanese" or other language. Is it expected?
Screenshot from 2020-11-05 17-22-43

**Comment by rhamilto** [comment]
> @rhamilto I checked on cluster against the pr, on the language switcher dropdown list, only "English" language is listed, no "Japanese" or other language. Is it expected?
> Screenshot from 2020-11-05 17-22-43

Yeah.  That is expected at this point since no additional language files exist in the repo.  I pulled https://github.com/openshift/console/pull/7092/files#diff-652b3d8dea573a584a93ac961168b94ebf24456cae758da8175e5aa2cf40038c in to my local environment and updated https://github.com/openshift/console/blob/master/frontend/public/i18next-parser.config.js#L3 with `ja: 'Japanese'` (which will ultimately be `ja: '日本語'` I believe) for testing.

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
