### PR TITLE
Fix broken Couchbase CSV link

### PR DESCRIPTION
**Pull request by PiotrWodecki**

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm
/label px-approved
/label docs-approved
/label qe-approved

README change only.

**Comment by PiotrWodecki** [comment]
Closing as no one seems to care

**Comment by spadgett** [comment]
> Closing as no one seems to care

Apologies, this was missing the `ok-to-test` label that prevented merge. Can you reopen?

**Comment by spadgett** [comment]
Please reach out if you feel like a PR isn't getting attention. The missing label was an oversight.

/ok-to-test

**Comment by PiotrWodecki** [comment]
@spadgett, I've exapanded the PR and reopened at https://github.com/openshift/console/pull/11342.

**Pull request closed without merging**
