### PR TITLE
ODC-7437: Remove pf classes in topology package

### PR DESCRIPTION
**Pull request by sanketpathak**
**Fix**:[ODC-7437](https://issues.redhat.com/browse/ODC-7437) 

**Description**: 
Remove PatternFly classname selectors from topology integration tests

Command to execute:
Run a cluster locally and execute the command `yarn run dev` and then `yarn run test-cypress-topology` simultaneously

**Browser**
Chrome 120

**Test Execution Screenshot:**
Screenshot 2024-03-31 at 2 44 54 AM

### CODE REVIEW

**Comment by The-Anton** [comment]
Tests are passing.
/lgtm

Screenshot 2024-04-09 at 3 46 10 PM

**Comment by sanketpathak** [comment]
Pr edits only e2e tests
/label qe-approved
/label docs-approved
/label px-approved

**Review by jerolimov — APPROVED** [review]
/unhold
/lgtm

**Pull request merged**
