### PR TITLE
Bug 1884402: Fix to draw aggregate edges to Event Brokers correctly in topology

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**Fixes**
https://issues.redhat.com/browse/ODC-4946

**Description**
Fix the end points for aggregate edges to Event Broker nodes

**Screenshots**
Before:
image

After:
image

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

/kind bug

/cc @bgliwa01 @beaumorley @serenamarie125

### CODE REVIEW

**Review by andrewballantyne — APPROVED** [review]
Seems to work well for me.

cc @invincibleJai 

/hold 

Waiting on UX's approval of the change in design (or closing of a gap in the design that is). Connectors were always fixed to either side (and they still are) but when application groups are collapsed, they can be of mixed items and that's *this* issue. Once we get an approval this is good to go imo.

**Review by bgliwa01 — APPROVED** [review]
lgtm

**Pull request merged**
