### PR TITLE
[release-4.13] OCPBUGS-41594: Redirects to new PipelineRun logs URL from old PipelineRun logs URL

### PR DESCRIPTION
**Pull request by vikram-raj**
Manually cherry-pick of PR https://github.com/openshift/console/pull/14234

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
Verified on the cluster bot

https://github.com/user-attachments/assets/3e3ad800-3332-4265-8afb-071381fda349

**Review by lokanandaprabhu — APPROVED** [review]

**Comment by vikram-raj** [comment]
Verified it on 4.13.0-0.nightly-2024-09-12-165259

https://github.com/user-attachments/assets/b0f536e2-f55d-401e-9ce5-8cea9b2a2c32

**Pull request merged**
