### PR TITLE
Take extra screenshots to troubleshoot overview test flakes

### PR DESCRIPTION
**Pull request by TheRealJon**
Add some extra screenshots into the failing overview spec so that we can see exactly what's happening step by step.

/cc @spadgett

### CODE REVIEW

**Comment by alecmerdler** [comment]
Looks like you accidentally committed `.DS_Store`.

**Comment by TheRealJon** [comment]
Ha, yeah, I noticed that but didn't really think it was worth fixing and restarting the tests since this is not going to be merged. We just wanted to get a better idea of what was happening during the tests since we can't duplicate the failures locally.

**Comment by TheRealJon** [comment]
@spadgett I added a catch to the assertion that keeps failing and dumped the page content to a file so we can look at the actual dom at the point of failure.

**Comment by spadgett** [comment]
Unfortunately the lint error prevents the integration tests from running

```
[4m/go/src/github.com/openshift/console/frontend/integration-tests/views/overview.view.ts[24m
  [2m20:1[22m  [31merror[39m  Expected indentation of 2 spaces but found 4  [2mindent[22m
```

**Comment by TheRealJon** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
/close

We're no longer seeing this flake. (Thanks @TheRealJon)

**Pull request closed without merging**
