### PR TITLE
ODC-7681: fix flaking k-native e2e test cases

### PR DESCRIPTION
**Pull request by The-Anton**
**Story**:
[ODC-7681](https://issues.redhat.com/browse/ODC-7681)

**Description**

- Replace `KN-05-TC05` knative test to use Git flow to create knative workload 
- [OCPBUGS-42104](https://issues.redhat.com/browse/OCPBUGS-42104) Disabling `KN-01-TC10` `KN-02-TC12` `KN-06-TC02` due to flaking nature

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
/approve

**Comment by vikram-raj** [comment]
e2e tests PR.

/label docs-approved
/label px-approved

**Review by vikram-raj — APPROVED** [review]

**Comment by sanketpathak** [comment]
CI is green
/label qe-approved

**Pull request merged**
