### PR TITLE
[release-4.16] OCPBUGS-38093: correct link for Lightspeed operator

### PR DESCRIPTION
**Pull request by rhamilto**
After

https://github.com/user-attachments/assets/f28cb6e0-4039-45f3-82ac-1b877b1ea134

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm

**Comment by yanpzhan** [comment]
Checked on cluster launched against the pr, Lightspeed url in getting started resources card is updated to use Lightspeed operator from "redhat-operators" catalogsource, clicking the url link could jump to Lightspeed operator's detail page.
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
