### PR TITLE
[release-4.3] Bug 1792847: Kubevirt vm real node name

### PR DESCRIPTION
**Pull request by yaacov**
This is a cherry-pick of #4460

### CODE REVIEW

**Comment by yaacov** [comment]
@suomiy please review.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1792847

**Comment by yaacov** [comment]
@spadgett hi, how do I get a cherry-pick-approved label ?

**Comment by spadgett** [comment]
> @spadgett hi, how do I get a cherry-pick-approved label ?

@yaacov This will get added by the patch manager. There's nothing you should need to do.

**Pull request merged**
