### PR TITLE
Bug 2020483: Monitoring dashboards: Improve display text for interval variables

### PR DESCRIPTION
**Pull request by kyoto**
Some variables are treated specially for setting an appropriate interval
value. If a dropdown contains one of these variables, display readable
text instead of just the variable name.

Before | After
-|-
before | after

### CODE REVIEW

**Comment by juzhao** [comment]
tested with PR, "API Performance" dashboard, Period field "$__auto_interval_period" is changed to "Auto interval ($__auto_interval_period)", auto interval period is 5m.
/lgtm

**Comment by kyoto** [comment]
Changed this to use a popup tooltip on the "Auto interval" entry.

**Review by jgbernalp — APPROVED** [review]

**Pull request merged**
