### PR TITLE
Allow all-projects to create Start Modal inline Pipeline Resources

### PR DESCRIPTION
**Pull request by andrewballantyne**
Targeted only for 4.4 at the moment. Still being decided if it's to be ported for 4.3.

https://jira.coreos.com/browse/ODC-2392

### CODE REVIEW

**Comment by abhinandan13jan** [comment]
@andrewballantyne Looking into this. First look, everything seems to be working fine. Would just do some sanity test and get back.

**Comment by abhinandan13jan** [comment]
/test e2e-gcp-console
/lgtm
P.S: The PR works well and is able to start a pipeline from all-project namespace. However, something to note here is that the active/current namespace of the user changes to that of the namespace the Pipeline is scoped to. Is this ideal? @andrewballantyne @christianvogt

**Comment by andrewballantyne** [comment]
> P.S: The PR works well and is able to start a pipeline from all-project namespace. However, something to note here is that the active/current namespace of the user changes to that of the namespace the Pipeline is scoped to. Is this ideal? @andrewballantyne @christianvogt

As discussed in Slack, we do the same thing for other resources and when you manipulate or select a resource from `all-projects` you end up in that namespace.

**Pull request merged**
