### PR TITLE
Updates to Troubleshooting nav section

### PR DESCRIPTION
**Pull request by spadgett**
Request from @sichvoge

* Rename Prometheus to Metrics
* Rename Prometheus Alerts to Alerts
* Add Dashboards item, which links to Grafana

secrets openshift origin 2018-07-24 09-05-49

/assign @rhamilto 
cc @openshift/team-ux-review @robszumski @brancz @kyoto

### CODE REVIEW

**Comment by sichvoge** [comment]
Can we change "Troubleshooting" to "Monitoring" please?

**Comment by spadgett** [comment]
> Can we change "Troubleshooting" to "Monitoring" please?

Then where does Search go?

**Comment by spadgett** [comment]
I guess Search could go to Administration?

**Comment by sichvoge** [comment]
Yea, I thought about that as well.

**Comment by sichvoge** [comment]
Let's wait for other to join the conversation on "Search" and if we can't get to a decision for this release, it's ok with me to leave it where it is and stick with "Troubleshooting" for now.

**Comment by spadgett** [comment]
Should we add the external link icon? Then it's less surprising that these items open a new window.

projects openshift origin 2018-07-24 09-21-00

**Comment by sichvoge** [comment]
If that's the case, trying to have a new icon would probably take a while. Let's keep "Troubleshooting" for the 3.11 release in that case. Don't want to add additional burden on the team if its not too important. 

It's enough for us to have a proper naming for the sub sections already. :)

**Comment by spadgett** [comment]
> If that's the case, trying to have a new icon would probably take a while

It's not too hard. We have one we use in the existing OpenShift console. (Screenshot below.)

Having said that, I think we should make the non-controversial change to the items themselves in one PR and look at any changes to the categories in another since those might have some debate.

We might want to move some things like config maps and secrets out of workloads into a more general resource nav section. Search could go there. We already have #254 we wanted to look at as well. 

openshift web console 2018-07-24 09-53-10

**Comment by spadgett** [comment]
> Hence, do you want to leave where it is right now?

I think so. I was looking at fading the external link icon in the nav with @rhamilto... Let me make that change, and I can take off WIP unless anyone objects.

**Comment by sichvoge** [comment]
Sounds good to me. Looking forward to the changes. :) And thanks for the quick turn around.

**Comment by spadgett** [comment]
@rhamilto PTAL

**Comment by sichvoge** [comment]
@spadgett @robszumski said we can throw "Search" under "Administration" as we suggested as well.

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by robszumski** [comment]
There aren't a lot of good options, so admin is fine with me. Open to other ideas though.

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by serenamarie125** [comment]
Troubleshooting -> Monitoring & the associated icon looks good to me.

Search in Administration is questionable to me though.  I'd suggest we leave that where it was for 3.11, and be sure to cover it in the effort that @beanh66 is looking at regarding overall navigation sections & items.

**Comment by rhamilto** [comment]
> There aren't a lot of good options, so admin is fine with me. Open to other ideas though.

Opinions on making "Search" a standalone, top-level item like "Overview"?

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by robszumski** [comment]
> Search in Administration is questionable to me though. I'd suggest we leave that where it was for 3.11, and be sure to cover it in the effort that @beanh66 is looking at regarding overall navigation sections & items.

Agree, lets do with that. This what we came to on Slack too.

**Comment by spadgett** [comment]
OK moved search back under monitoring

search openshift origin 2018-07-24 15-09-06

@rhamilto PTAL

**Pull request merged**
