### PR TITLE
CONSOLE-2361: Remove orphaned patternfly-react 3 styles and patternfly-react 3 depe…

### PR DESCRIPTION
**Pull request by rhamilto**
…ndency

I assume these packages updated to the patternfly-react 4 equivalents, but left behind the patternfly-react 3 css, orphaning the css and maintaining the dependency on patternfly-react 3.  This fixes that oversight.

cc: @sg00dwin @jcaianirh @glekner

### CODE REVIEW

**Review by jcaianirh — APPROVED** [review]
lgtm

**Review by spadgett — APPROVED** [review]
/lgtm
/hold for approvals
/assign @yapei 

@yapei We just need a regression test to make sure there are no visual problems removing this dependency.

**Comment by jcaianirh** [comment]
@rhamilto @spadgett I think these color changes are ok, but wanted to make note that mcoker found some minor color differences post merge (when he was able to install the extension package in his openshift dev env):
https://github.com/patternfly/patternfly-react/pull/5987#pullrequestreview-702483800

**Comment by rhamilto** [comment]
I realized there were additional unnecessary imports in https://github.com/openshift/console/pull/9452/files#diff-e4dab90fda631807abb5c876d5926e380851139a8ea5ca96b04638e32e03aafcL1-L12 and https://github.com/openshift/console/pull/9452/files#diff-ff6bbd646f75df45d59a89f387ce5622a78d264af33f7e117388fd8ab4a86d92L3-L10.  Please retag, @spadgett

**Comment by XiyunZhao** [comment]
This changes is verified, it's not impacted the relgular function and page on private build.

**Comment by spadgett** [comment]
There are no user visible changes. Adding the docs-approved label.

/label docs-approved

@ahardin-rh FYI

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
