### PR TITLE
[WIP] Bug 2027959: Grace Period on delete VM request

### PR DESCRIPTION
**Pull request by upalatucci**
**Fix:** 
https://bugzilla.redhat.com/show_bug.cgi?id=2027959

**Analysis / Root cause:**
It seems we have a very high terminationGracePeriodSeconds on Windows VMs templates.
This is annoying if the Virtual Machine fails to shutdown gracefully. The user needs to interneve manually or wait 1h.

**Solution Description:**
Allow the user to specify a different Grace Period in the delete VM modal.

**Screen shots / Gifs for design review:**

Before:
Screenshot from 2022-01-18 11-59-03

After:
Screenshot from 2022-01-18 11-17-11

### CODE REVIEW

**Comment by yaacov** [comment]
```
-}
11278
+}
11279
\ No newline at end of file
```

you need to run `yarn i18n` in the frontend directory

**Comment by yfrimanm** [comment]
Delete confirmation modal 1
Delete confirmation modal 2
Text in the popover should be reviewed by the docs team.

**Comment by yaacov** [comment]
@yfrimanm thank you for the design !
a - grace period is always in sec, it does not make sense to me to let a machine more then a few seconds to shout down.
     - the backend name is `gracePeriodSeconds`
b - I like the help popups, it makes a lot of sense to me here
     - for the text we can use the official description from - https://kubevirt.io/api-reference/master/definitions.html#_k8s_io_apimachinery_pkg_apis_meta_v1_deleteoptions 
     - I think the pattern now is to use dotted line under the text instead of question mark, am i missing somethin ?

**Comment by yfrimanm** [comment]
Thank you @yaacov I just checked the PF guidelines and it seems that in **modals** we use the "?" icon for help text.
Please see here https://www.patternfly.org/v4/components/modal/design-guidelines#modals-with-help
The Grace period popover text is updated.
Delete confirmation modal 1
Delete confirmation modal 2

**Comment by yaacov** [comment]
/approve
need a re-run of 'yarn i18n'

**Comment by upalatucci** [comment]
The only idea I had to test the grace period effectively was to spy on the request and ensure that the gracePeriodSeconds parameter is in the body. What do you think about guys? f9ee61bc660d44b01d01884dfc663dd658a5113a

**Comment by yaacov** [comment]
> The only idea I had to test the grace period effectively was to spy on the request and ensure that the gracePeriodSeconds  parameter is in the body. What do you think about

I'm happy with it, @gouyang PTAL

**Comment by fabiand** [comment]
ANy update on why this got closed?

@tnisan ?

**Comment by upalatucci** [comment]
This pr was idle for quite some time so I decided to close it.

**Pull request closed without merging**
