### PR TITLE
Bug 1879054: UI should display password in cloud-init

### PR DESCRIPTION
**Pull request by glekner**
Added label with the password to the right of the new window button.
The label will only be present if a password is found in the YAML.
thoughts @jelkosz @matthewcarleton ?

image

### CODE REVIEW

**Comment by jelkosz** [comment]
2 things: 
1: we need to provide both username and password. If the "user" is not set, the username and the password is the same. But if it looks e.g. like this:
              #cloud-config
              user: admin
              password: q1w2e3
              chpasswd: {expire: False}
              ssh_pwauth: True
than the user is admin

2: you have to show the password only after the user chooses to. @matthewcarleton @yfrimanm WDYT?

**Comment by glekner** [comment]
Added user, and to show the password you now have to click Show Password

image

**Comment by glekner** [comment]
image

@jelkosz @matthewcarleton

**Comment by jelkosz** [comment]
@glekner 
1: the "if it is not successful" needs to have a capital "I"
2: once you hit "show password", you need to have also a "hide password" to hide it again

other than that work very nice!

**Comment by matthewcarleton** [comment]
> image
> 
> @jelkosz @matthewcarleton

sorry small text tweak:


`The following credentials for this operating system were created via Cloud-init. If unsuccessful the cloud-init could be improperly configured. Please contact the image provider for more information. `

**Comment by glekner** [comment]
fixed text and added `Hide password` button

**Pull request merged**
