### PR TITLE
fix: Dragging the rows to re-order creates multiple duplicate items.

### PR DESCRIPTION
**Pull request by gijohn**
Fixes: https://jira.coreos.com/browse/ODC-1525

### CODE REVIEW

**Comment by joshuawilson** [comment]
@gijohn this is outside of dev console, only Christian can approve it or someone on the admin/core team can.

**Comment by joshuawilson** [comment]
Can you please add to the description what you did and why.

**Comment by spadgett** [comment]
We should open a Bugzilla to track this as this should be a release blocking bug. We also need to evaluate whether it's present in 4.1 to check if we need to backport.

> Can you please add to the description what you did and why.

+1, it's unclear to me looking at the diff what the cause of the problem was. Can you describe what was wrong?

Thanks for your patience on the review.

**Comment by gijohn** [comment]
@spadgett, @joshuawilson I don't see any problem with the data or the call to move method. 

image
image

In the above example, the index of the first element is undefined and second is 1. It fails even if the indices are identical. i.e. 1 and 1.

image
image

It works fine when the index is populated correctly which acts as key. I believe it is a limitation from react-dnd.

**Pull request merged**
