### PR TITLE
Bug 1953937: Fixing PVC creation page issue in 4.7(Reverting wrong commit)

### LINKED ISSUE #8452: [OKD4.7] Web-UI broken on "Create PersistentVolumeClaim"
Hi,

we experienced an error on the Web-UI in 4.7.0-0.okd-2021-03-21-094146 Release (bare-metal UPI).
When we click in Administrator View on "PersistentVolumeClaims" -> "Create PersistentVolumeClaim" (URL: https://console-openshift-console.apps.clustername.basedomain/k8s/ns/default/persistentvolumeclaims/~new/form") 
grafik

the page gets loaded and after a  short flickering showing the Forms content for a millisecond it stays completely empty - like being overlayed with a white page or the page content blended out:
grafik

In 4.6 it would look like this:
grafik

When looking at the pages source code it seems to be loaded having the following JavaScript-error:
grafik

> **TypeError: can't convert undefined to object**
>     d create-pvc-chunk-e6298432dd020e2cd449.min.js:1
>     k create-pvc-chunk-e6298432dd020e2cd449.min.js:1
>     Ia vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     Ws vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     unstable_runWithPriority vendors~main-chunk-3652a4e54bce917198bc.min.js:166497
>     li vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     Ws vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     Fs vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     Ps vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     hi vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     unstable_runWithPriority vendors~main-chunk-3652a4e54bce917198bc.min.js:166497
>     li vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     hi vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     di vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     Is vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
>     notify vendors~main-chunk-3652a4e54bce917198bc.min.js:39200
>     notifyNestedSubs vendors~main-chunk-3652a4e54bce917198bc.min.js:39200
>     notifySubscribers vendors~main-chunk-3652a4e54bce917198bc.min.js:109462
>     handleChangeWrapper vendors~main-chunk-3652a4e54bce917198bc.min.js:39200
>     v vendors~main-chunk-3652a4e54bce917198bc.min.js:24762
>     b main-chunk-0e0280b47986f6ccc022.min.js:1
>     dispatch vendors~main-chunk-3652a4e54bce917198bc.min.js:24762
>     s main-chunk-0e0280b47986f6ccc022.min.js:1
>     s main-chunk-0e0280b47986f6ccc022.min.js:1
>     i main-chunk-0e0280b47986f6ccc022.min.js:1
> vendors~main-chunk-3652a4e54bce917198bc.min.js:166203
> **stopped watching storage.k8s.io~v1~StorageClass before finishing incremental loading with error TypeError: can't convert undefined to object! main-chunk-0e0280b47986f6ccc022.min.js:1**

It is reproduceable in 4.7, but not in 4.6 and seems like it could be related to the templating/branding issue on the first 4.7 Release...

Can you confirm that?

Best regards

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
PR: https://github.com/openshift/console/pull/8234 have the wrong commit, reverted the irrelevant commit 

Fixes #8452

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
pvc_page_blank

**Comment by GowthamShanmugam** [comment]
Just to double-check i verified my arbiter fix also:
image

**Comment by GowthamShanmugam** [comment]
@spadgett Please approve this fix

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by GowthamShanmugam** [comment]
I have tested this PR with storage class YAML from: https://github.com/openshift/console/issues/8452, it works fine

image

**Pull request merged**
