### PR TITLE
[release-4.5.z] Bug 1852530: kubevirt - fix importing VMs with same vnicIDs for ovirt provider

### PR DESCRIPTION
**Pull request by suomiy**
- don't allow Pod networks for such nics
- allow only same network values for nics with same vnicID

### CODE REVIEW

**Comment by suomiy** [comment]
backport of https://github.com/openshift/console/pull/5871

**Comment by suomiy** [comment]
@spadgett 
Can you please add this to v4.5.z milestone?

**Comment by suomiy** [comment]
can you please cherry-pick-approved ?
@sdodson @eparis @markmc @crawford

**Comment by sdodson** [comment]
Please see the patch manager documentation in the topic of #forum-release. A patch manager will review according to the merge windows and there should be no need to ping someone directly for PRs that only need cherry-pick-approved label.

**Comment by bparees** [comment]
cherry pick of https://github.com/openshift/console/pull/5871

**Pull request merged**
