### PR TITLE
Always show OpenShift templates in developer catalog

### PR DESCRIPTION
**Pull request by spadgett**
Remove the check for service catalog and always show templates if OpenShift.

/assign @dtaylor113 
@jwforres @bparees fyi

### CODE REVIEW

**Comment by jwforres** [comment]
/hold

until we are 100% sure about timeline for TSB removal

**Comment by spadgett** [comment]
I've finally been able to verify this fix. @rhamilto can you take a look since @dtaylor113 is out?

/assign @rhamilto

**Comment by spadgett** [comment]
The current code always shows templates and never show template service broker items in catalog. (Other service classes will be visible.)

**Pull request merged**
