### PR TITLE
ODC-7671: Migrate FilterDropdown to PF5

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7671

**Screen shots / Gifs for design review**: 

demo:

https://github.com/user-attachments/assets/91e155d3-8321-487c-ae8f-c86e01d55204

**Unit test coverage report**: 

n/a

**Test setup:**

n/a

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

This pr is 2/3 of [ODC-7671](https://issues.redhat.com//browse/ODC-7671) story as each file is being split into a separate PR.

### CODE REVIEW

**Comment by logonoff** [comment]
Tech debt that is not customer facing, so manually adding labels
/label px-approved
/label docs-approved

**Review by vikram-raj — APPROVED** [review]
/lgtm

**Review by vikram-raj — CHANGES_REQUESTED** [review]
Clicking anywhere in the window does not close the dropdown option. It should close the dropdown.

https://github.com/user-attachments/assets/bd1d3827-8592-4781-89b1-9ab519aec5d5


/lgtm cancel

**Comment by logonoff** [comment]
> Clicking anywhere in the window does not close the dropdown option. It should close the dropdown.
> Screen.Recording.2024-08-30.at.3.24.19.PM.mov
> 
> /lgtm 

amended, thanks for catching :)

**Review by vikram-raj — APPROVED** [review]
/lgtm

**Comment by The-Anton** [comment]
Tested on Cluster, working as expected
/label qe-approved

Screenshot 2024-09-03 at 12 49 57 PM

**Pull request merged**
