### PR TITLE
Integration Tests: Avoid StaleElementReferenceErrors in OLM descriptor scenario

### PR DESCRIPTION
**Pull request by spadgett**
🤞

https://jira.coreos.com/browse/CONSOLE-1214

/assign @alecmerdler

### CODE REVIEW

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
Previous error was a different stale element error on another page :/

https://jira.coreos.com/browse/CONSOLE-1219

**Comment by alecmerdler** [comment]
Closing in favor of #1104

**Pull request closed without merging**
