### PR TITLE
[release-4.11] OCPBUGS-19359: Remove PipelineResource CRD check because it's not installed with PO 1.11 anymore

### PR DESCRIPTION
**Pull request by jerolimov**
This is an manual cherry-pick of #12948

### CODE REVIEW

**Comment by Lucifergene** [comment]
Looks good to me as PirpelineResource has been deprecated.

@sanketpathak PTAL.

**Review by Lucifergene — COMMENTED** [review]
Looks good to me as PirpelineResource has been deprecated.
/lgtm

@sanketpathak PTAL.

**Comment by jerolimov** [comment]
/retitle [release-4.11] OCPBUGS-19359: Remove PipelineResource CRD check because it's not installed with PO 1.11 anymore

**Pull request merged**
