### PR TITLE
Update Chromedriver to 77.x

### PR DESCRIPTION
**Pull request by ldimaggi**
https://jira.coreos.com/browse/CONSOLE-1859

### CODE REVIEW

**Comment by spadgett** [comment]
I'm surprised this is passing CI without also updating the Chrome version we download as in #2327.

cc @yaacov

**Comment by yaacov** [comment]
@spadgett just tried with chromium 77.0.3865.0:
```
export FORCE_CHROME_BRANCH_BASE="681090"
export FORCE_CHROME_BRANCH_SHA256SUM="2f0c6b091d626310cf5bef7c2a897f53aee40d01d341b4ad2cfbabe83711d85f"
```
and it works with the chromedriver 76 ... will need to ask in some bigger forum ?

**Comment by spadgett** [comment]
Looks like this worked because we aren't really using Chromedriver 77.

https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_console/3113/pull-ci-openshift-console-master-e2e-gcp-console/920/artifacts/e2e-gcp-console/container-logs/test.log

```
[16:42:29] I/downloader - curl -o/go/src/github.com/openshift/console/frontend/node_modules/webdriver-manager/selenium/chromedriver_76.0.3809.12.zip https://chromedriver.storage.googleapis.com/76.0.3809.68/chromedriver_linux64.zip
```

I suspect we need to update webdriver, but then our chrome versions won't match unless we update chrome as well.

**Comment by spadgett** [comment]
The good news is you can install a different Chromedriver locally for dev with

```
 yarn run webdriver-update --versions.chrome=77.0.3865.120
```

**Pull request merged**
