### PR TITLE
[release-4.12] OCPBUGS-18563: OLM Pages work when copied CSVs are disabled

### PR DESCRIPTION
**Pull request by TheRealJon**
Backport disable copied CSV fix to 4.12

### CODE REVIEW

**Comment by TheRealJon** [comment]
/hold

Depends on operator changes.

**Comment by TheRealJon** [comment]
I launched a 4.12 cluster with the changes from this PR and the operator changes in https://github.com/openshift/console-operator/pull/780 and did some high-level testing and it is working as expected as far as I can tell.

**Review by rhamilto — APPROVED** [review]
/lgtm

**Pull request merged**
