### PR TITLE
Bug 2014238: increase yaml load wait to reduce test flake on yaml import

### PR DESCRIPTION
**Pull request by jcaianirh**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2014238

### CODE REVIEW

**Comment by jcaianirh** [comment]
@spadgett @dtaylor113 After debugging https://github.com/openshift/console/pull/10320 some more, I saw that even disabling the button and or yaml editor I'm still seeing the problem. I remember our initial issue when writing the tests was because the yaml editor just didn't load on time, and we put a wait statement in the test. I decreased the wait statement, and immediately saw the same test failure in cypress as we have in ci. Therefore, I'm going to up the wait from 3500 -> 4000 to allow for loading of the yaml editor component.

**Review by dtaylor113 — APPROVED** [review]
Long standing issue with the Monaco editor, we tried several workarounds including adding cypress code directly into concole code to indicate when the editor is fully loaded...nothing has worked yet for this component, so ok to increase time wait if neccesary

**Comment by rhamilto** [comment]
> @spadgett @dtaylor113 After debugging #10320 some more, I saw that even disabling the button and or yaml editor I'm still seeing the problem. I remember our initial issue when writing the tests was because the yaml editor just didn't load on time, and we put a wait statement in the test. I decreased the wait statement, and immediately saw the same test failure in cypress as we have in ci. Therefore, I'm going to up the wait from 3500 -> 4000 to allow for loading of the yaml editor component.

If the 500ms increase in this PR seems to have made a difference, should we try bumping it even further and seeing if that makes a difference in CI in order to resolve https://bugzilla.redhat.com/show_bug.cgi?id=2039065?  Or do y'all have other suggestions we haven't tried yet?

**Pull request merged**
