### PR TITLE
ODC-7671: Migrate NameLabelFilterDropdown to PF5

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7671

**Screen shots / Gifs for design review**: 

demo:

https://github.com/user-attachments/assets/b90e8aa3-c8e4-4445-bb91-c9887796e1ad

**Unit test coverage report**: 

n/a

**Test setup:**

n/a

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

This pr is 1/3 of [ODC-7671](https://issues.redhat.com//browse/ODC-7671) story as each file is being split into a separate PR.

### CODE REVIEW

**Comment by logonoff** [comment]
Tech debt that is not customer facing, so manually adding labels
/label px-approved
/label docs-approved

**Review by vikram-raj — APPROVED** [review]
/lgtm

**Review by vikram-raj — CHANGES_REQUESTED** [review]
Clicking anywhere in the window does not close the dropdown option. It should close the dropdown.

https://github.com/user-attachments/assets/42eee1da-4767-4b52-8943-28e130e64bd3

/lgtm cancel

**Comment by logonoff** [comment]
> Clicking anywhere in the window does not close the dropdown option. It should close the dropdown.
> Screen.Recording.2024-08-30.at.3.19.52.PM.mov
> 
> /lgtm cancel

amended, thanks for catching :)

**Review by vikram-raj — APPROVED** [review]
/lgtm

**Comment by sanketpathak** [comment]
Tested on a cluster, works fine 
Screenshot 2024-08-31 at 3 40 48 AM
/label qe-approved

**Pull request merged**
