### PR TITLE
dynamic-plugin-sdk: set useActiveColumns props as optional

### PR DESCRIPTION
**Pull request by mareklibra**
In consistence with the implementation.

### CODE REVIEW

**Comment by rawagner** [comment]
@mareklibra can you use `UseActiveColumns` type in  `active-columns-hook.ts` ?

```js
export const useActiveColumns: UseActiveColumns = ({
  columns,
  showNamespaceOverride,
  columnManagementID,
}) => {
```

**Comment by rawagner** [comment]
/label docs-approved
/label px-approved

This change is scoped only for dynamic plugin SDK. There is no change to Console itself.

@yapei Can you please take a look ? Though I do not think there is anything to test :)

**Comment by yapei** [comment]
I run a `yarn run build` in `dynamic-demo-plugin` dir and see following error
```
38 assets
Entrypoint console-demo-plugin = plugin-entry.js (plugin-entry.js.map)
container entry 42 bytes [built]
./utils/example-navs.tsx + 1 modules 2.12 KiB [built]
./utils/bar.ts 138 bytes [built]
./utils/perspective.ts + 1 modules 1.03 KiB [built]
./utils/telemetry.ts 4.23 KiB [built]
./components/ExtensionConsumer.tsx 1.88 KiB [built]
./components/UtilityConsumer.tsx 1.26 KiB [built]
./components/Nav.tsx 684 bytes [built]
./components/ListPage.tsx 2.77 KiB [built]
overridable react -> react 42 bytes [built]
overridable react-i18next -> react-i18next 42 bytes [built]
overridable @patternfly/react-core -> @patternfly/react-core 42 bytes [built]
overridable react -> react 42 bytes [built]
overridable react-i18next -> react-i18next 42 bytes [built]
overridable @openshift-console/dynamic-plugin-sdk -> @openshift-console/dynamic-plugin-sdk 42 bytes [built]
    + 408 hidden modules

ERROR in container entry K8sAPIConsumer[6]
Module not found: Error: Can't resolve './components/K8sConsumer/K8sAPIConsumer.tsx' in '/root/odev/src/github.com/openshift/mareklibra-console/dynamic-demo-plugin/src'
```
This issue should be fixed so I guess we need rebase the PR?  @rawagner  @mareklibra

**Pull request closed without merging**
