### PR TITLE
CONSOLE-2361: Convert Bootstrap utility class show to PF equivalent

### PR DESCRIPTION
**Pull request by sg00dwin**

### CODE REVIEW

**Review by rhamilto — COMMENTED** [review]
Four of these could be markup changes of `<span>` to `<div>` and then there is no utility class needed?

**Comment by XiyunZhao** [comment]
This PR has been verified on private build, and do not find any issue, share some snapshot for the scenario that has been checked,
image
image
image

**Comment by rhamilto** [comment]
This PR has no user visible changes, and we have general docs and px approval for this epic. @ahardin-rh @sferich888 FYI

/label docs-approved
/label px-approved

**Pull request merged**
