### PR TITLE
Removed references to Protractor tests which no longer exist

### PR DESCRIPTION
**Pull request by dtaylor113**
Removed references to `devconsole` and `service-catalog` tests as they no longer exist.

### CODE REVIEW

**Comment by spadgett** [comment]
/assign @christianvogt @andrewballantyne 

It looks like these tests moved into the dev-console page. Adding @christianvogt and @andrewballantyne to confirm that we should remove the old references.

**Comment by andrewballantyne** [comment]
Yeah that appears to be the case. 👍 

I think @makambalaji needs to be the one with the final DevConsole say as he is the current owner of our Automated Test Suite.

**Comment by dtaylor113** [comment]
> It looks like these tests moved into the dev-console page. Adding @christianvogt and @andrewballantyne to confirm that we should remove the old references.

IM'ed @andrewballantyne about these the other day:

Andrew Ballantyne
As far as I know, we don’t have Protractor tests anymore :thinking: 
QE has been full-time at doing Cypress for the past year or so. I think their first steps were to convert them or toss them
:thinking: as far as I am aware, we don’t run anything part of the CI anymore
It’s [`frontend/packages/dev-console/integration-tests/tests/dev-perspective.scenario.ts`] run manually by the QE team while they figure out what they are going to do to automated I guess

**Comment by makambalaji** [comment]
> Yeah that appears to be the case. 
> 
> I think @makambalaji needs to be the one with the final DevConsole say as he is the current owner of our Automated Test Suite.

We are not using protractor files, we can remove them

**Review by makambalaji — APPROVED** [review]
We are not using protractor related code in dev-console, So I am good with these changes

**Comment by spadgett** [comment]
> We are not using protractor related code in dev-console, So I am good with these changes

OK, are the tests here dead code? Should we remove them?

https://github.com/openshift/console/tree/master/frontend/packages/dev-console/integration-tests/tests

**Comment by dtaylor113** [comment]
> > We are not using protractor related code in dev-console, So I am good with these changes
> 
> OK, are the tests here dead code? Should we remove them?
> 
> https://github.com/openshift/console/tree/master/frontend/packages/dev-console/integration-tests/tests

That is a question for @makambalaji or @andrewballantyne

**Review by andrewballantyne — APPROVED** [review]
I think we can merge this as-is... we are polluting the global space and not providing tests for it. So this is good for you guys to help us clean that up. 👍 

I'll log a technical debt ticket with the QE board to have something logged that they follow through on at a future date (for posterity - https://issues.redhat.com/browse/ODC-5888).

Recommend we merge this as-is.

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by makambalaji** [comment]
> > We are not using protractor related code in dev-console, So I am good with these changes
> 
> OK, are the tests here dead code? Should we remove them?
> 
> https://github.com/openshift/console/tree/master/frontend/packages/dev-console/integration-tests/tests

Yes, we can remove them

**Comment by andrewballantyne** [comment]
@makambalaji please see https://issues.redhat.com/browse/ODC-5888 -- this will take care of the extra tests. Please remove them if you have the covered in other areas. This will be a Dev Console task.

**Pull request merged**
