### PR TITLE
auth: use proxy from environment when connecting to OAuth server

### LINKED ISSUE #1248: Support http_proxy env variable
Authentication fails if the openshift cluster's public endpoint is reachable only through an http proxy.

Error message on my environment:

2019/03/3 07:21:03 auth: unable to verify auth code with issuer: Post https://console.rh.hml.lab-nxtit.com:443/oauth/token:  net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

I tried configuring uppercase and lowercase environment variables http_proxy & https_proxy but it doesn't help. I looked at the cmd/bridge/main.go file and proxy isn't configured in the custom http.Transport.

### PR DESCRIPTION
**Pull request by patlachance**
Fixes #1248 

https://jira.coreos.com/browse/CONSOLE-1440

### CODE REVIEW

**Comment by spadgett** [comment]
Hi @patlachance. How does the environment variable get set? Is this a manual edit to the deployment?

Note that in 4.0 we have an operator that would overwrite changes to env vars.

cc @enj

**Comment by jhadvig** [comment]
@patlachance could you please rebase this PR, so we can merge it ?

**Comment by spadgett** [comment]
Hi, @patlachance. I rebased your PR for you. Hope you don't mind. Thanks for your contribution.

Now that https://github.com/openshift/console-operator/pull/254 is complete, we should be able to go ahead with this change.

**Pull request merged**
