### PR TITLE
[release-4.14] OCPBUGS-25274: Add support for Azure Workload Identity / Federated Identity based in…

### PR DESCRIPTION
**Pull request by rhamilto**
…stalls in OperatorHub

### CODE REVIEW

**Comment by rhamilto** [comment]
Replaces https://github.com/openshift/console/pull/13442

**Comment by rhamilto** [comment]
@jcaianirh, mind tagging this?

**Review by jcaianirh — APPROVED** [review]
/lgtm

**Comment by yapei** [comment]
verified that the warning info is shown on operator installation page
Screenshot 2024-03-04 at 10 07 32 AM
Screenshot 2024-03-04 at 10 08 02 AM
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
