### PR TITLE
Bug 2014245: i18n several aria-labels, external links, and labels

### PR DESCRIPTION
**Pull request by rebeccaalpert**
Several aria-labels, external links, and labels appear to have been missed. I internationalized them.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2014245

### CODE REVIEW

**Review by TheRealJon — APPROVED** [review]
/approve
/lgtm

**Comment by rebeccaalpert** [comment]
Looks like the linter is unhappy with one of the i18n files. I will resolve it tomorrow.

**Review by sg00dwin — APPROVED** [review]
/lgtm

**Review by kdoberst — APPROVED** [review]
Looks good.  Thanks for picking up the aria-labels :-)

**Pull request merged**
