### PR TITLE
CONSOLE-3774: Enable OperatorHub filter by TLSProfiles annotation 

### PR DESCRIPTION
**Pull request by sg00dwin**
https://issues.redhat.com/browse/CONSOLE-3774

Screenshot 2024-01-30 at 3 12 46 PM

### CODE REVIEW

**Comment by jhadvig** [comment]
QE Approver: 
/assign @XiyunZhao
Docs Approver: 
/assign @opayne1
PX Approver:
/assign @RickJWagner

**Comment by XiyunZhao** [comment]
Wait for a usable build, currently failed to launch the cluster with the code change by using cluster bot

**Comment by XiyunZhao** [comment]
This PR has been tested via cluster-bot, the checkpoint on the case is pass
/label qe-approved

**Pull request merged**
