### PR TITLE
CONSOLE-3136: add conditional updates to Cluster Settings

### PR DESCRIPTION
**Pull request by rhamilto**
Note this includes dependent changes from https://github.com/openshift/console/pull/11424

### Demo

https://user-images.githubusercontent.com/895728/166937616-5ee40301-17fb-4e39-931f-25256693fa6d.mov

### To test

I've been using a `v4.10.7` cluster with channel `candidate-4.10`.

### To mock `conditionalUpdates` and no `availableUpdates`:

Turn off the CVO, so it doesn't fight with us over ClusterVersion ownership:
  ```
oc scale --replicas 0 -n openshift-cluster-version deployments/cluster-version-operator
```
Patch the CVO:

```
oc proxy &
```
Add `conditionalUpdates`:
```
curl -k -XPATCH -H "Accept: application/json" -H "Content-Type: application/json-patch+json" 'http://127.0.0.1:8001/apis/config.openshift.io/v1/clusterversions/version/status' -d '[{"op":"add","path":"/status/conditionalUpdates","value":[{"release":{"version":"4.10.97","image":"quay.io/openshift-release-dev/ocp-release@sha256:7082f01282a07f4033308ccadb1ca0c6acacadd83812d7cc1135a022f5382391","channels":["candidate-4.10"]},"risks":[{"url":"https://bugzilla.redhat.com/show_bug.cgi?id=2047190","name":"AlibabaStorageDriverDemo","message":"The Alibaba storage driver was updated from a patched 1.1.4 to a patched 1.1.6 in 4.10.0-rc.0.  That is unlikely to fix anything that regressed in this provider from fc.3 to fc.4, but this conditional update is pretending it does, as a demonstration of the conditional update system.","matchingRules":[{"type":"PromQL","promql":{"promql":"cluster_infrastructure_provider{type=\"AlibabaCloud\"} or 0 * cluster_infrastructure_provider"}}]}],"conditions":[{"type":"Recommended","status":"False","lastTransitionTime":"2022-02-03T22:53:33Z","reason":"AlibabaStorageDriverDemo","message":"The Alibaba storage driver was updated from a patched 1.1.4 to a patched 1.1.6 in 4.10.0-rc.0.  That is unlikely to fix anything that regressed in this provider from fc.3 to fc.4, but this conditional update is pretending it does, as a demonstration of the conditional update system.  https://bugzilla.redhat.com/show_bug.cgi?id=2047190"}]},{"release":{"version":"4.10.98","image":"quay.io/openshift-release-dev/ocp-release@sha256:7082f01282a07f4033308ccadb1ca0c6acacadd83812d7cc1135a022f5382391","channels":["candidate-4.10"]},"risks":[{"url":"https://bugzilla.redhat.com/show_bug.cgi?id=2047190","name":"AlibabaStorageDriverDemo","message":"The Alibaba storage driver was updated from a patched 1.1.4 to a patched 1.1.6 in 4.10.0-rc.0.  That is unlikely to fix anything that regressed in this provider from fc.3 to fc.4, but this conditional update is pretending it does, as a demonstration of the conditional update system.","matchingRules":[{"type":"PromQL","promql":{"promql":"cluster_infrastructure_provider{type=\"AlibabaCloud\"} or 0 * cluster_infrastructure_provider"}}]}],"conditions":[{"type":"Recommended","status":"True","lastTransitionTime":"2022-02-03T22:53:33Z","reason":"AsExpected","message":"The update is recommended, because none of the conditional update risks apply to this cluster."}]},{"release":{"version":"4.10.99","image":"quay.io/openshift-release-dev/ocp-release@sha256:7082f01282a07f4033308ccadb1ca0c6acacadd83812d7cc1135a022f5382391","channels":["candidate-4.10"]},"risks":[{"url":"https://bugzilla.redhat.com/show_bug.cgi?id=1941840#c33","name":"AuthOAuthProxyLeakedConnections","message":"On clusters with a Proxy configured, the authentication operator may keep many oauth-server connections open, resulting in high memory consumption by the authentication operator and router pods.","matchingRules":[{"type":"PromQL","promql":{"promql":"max(cluster_proxy_enabled{type=~\"https?\"})"}}]},{"url":"https://bugzilla.redhat.com/show_bug.cgi?id=1942207#c3","name":"VSphereNodeNameChanges","message":"vSphere clusters leveraging the vSphere cloud provider may lose node names which can have serious impacts on the stability of the control plane and workloads.","matchingRules":[{"type":"PromQL","promql":{"promql":"cluster_infrastructure_provider{type=~\"VSphere|None\"}\nor\n0 * cluster_infrastructure_provider\n"}}]},{"url":"https://access.redhat.com/solutions/5896081\",","name":"VSphereHW14CrossNodeNetworkingError\",","message":"Clusters on vSphere Virtual Hardware Version 14 and later may experience cross-node networking issues.","matchingRules":[{"type":"PromQL","promql":{"promql":"cluster_infrastructure_provider{type=~\"VSphere|None\"}\nor\n0 * cluster_infrastructure_provider\n"}}]}],"conditions":[{"type":"Recommended","status":"False","lastTransitionTime":"2022-02-03T22:53:33Z","reason":"Other","message":"Clusters on vSphere Virtual Hardware Version 14 and later may experience cross-node networking issues. https://access.redhat.com/solutions/5896081\n\nvSphere clusters leveraging the vSphere cloud provider may lose node names which can have serious impacts on the stability of the control plane and workloads. https://bugzilla.redhat.com/show_bug.cgi?id=1942207#c3\n\nOn clusters with a Proxy configured, the authentication operator may keep many oauth-server connections open, resulting in high memory consumption by the authentication operator and router pods. https://bugzilla.redhat.com/show_bug.cgi?id=1941840#c33"}]}]}]'
```
Set `availableUpdates` to empty:
```
curl -k -XPATCH -H "Accept: application/json" -H "Content-Type: application/json-patch+json" 'http://127.0.0.1:8001/apis/config.openshift.io/v1/clusterversions/version/status' -d '[{"op": "add", "path": "/status/availableUpdates", "value": []}]'
```

### When you're done, kill the `oc proxy`:

```
$ fg
oc proxy
^C
```

And turn the CVO back on:
```
oc scale --replicas 1 -n openshift-cluster-version deployments/cluster-version-operator
```

### CODE REVIEW

**Comment by rhamilto** [comment]
/assign @andrewballantyne
/assign @opayne1
/assign @RickJWagner
/assign @yapei

for review and approvals

**Comment by yapei** [comment]
tested the changes locally, everything works well, detailed testing steps are in test case
Screen Shot 2022-05-06 at 15 59 08
Screen Shot 2022-05-06 at 15 59 58
Screen Shot 2022-05-06 at 16 02 00

**Review by andrewballantyne — APPROVED** [review]
/hold

Waiting on dependant PR to merge.

**Comment by rhamilto** [comment]
@andrewballantyne, please retag as I had to rebase due to changes in https://github.com/openshift/console/pull/11424.

**Review by jhadvig — APPROVED** [review]
/lgtm

**Pull request merged**
