### PR TITLE
Expose useResolvedExtensions as part of the stable API

### PR DESCRIPTION
**Pull request by bipuladh**
Jira Link: https://issues.redhat.com/browse/CONSOLE-2922
To test this PR: 
- Build and run the dynamic demo plugin
- Check route `/test-consumer`. The Page should render a bunch of Flags and associated Models.
/assign @spadgett @christianvogt 

Example Screenshot: 
Screenshot from 2021-07-26 13-17-03

### CODE REVIEW

**Comment by christianvogt** [comment]
What API can we use from the SDK today?

`src/index.ts` already does this: `export * from './api/useResolvedExtensions';`

But it doesn't look like this is exported in the final built lib. 
Should it have been?
What about `common-types` as well?

**Comment by bipuladh** [comment]
> What API can we use from the SDK today?
> 
> `src/index.ts` already does this: `export * from './api/useResolvedExtensions';`
> 
> But it doesn't look like this is exported in the final built lib.
> Should it have been?
We can't export because it pulls code from `console-plugin-sdk` which would cause compilation errors.

> What about `common-types` as well?
`common-types` are used internally we are only exposing types which make up the API. While working with the SDK I haven't actually have had need for `common-types`(yet).

**Comment by vojtechszocs** [comment]
> `src/index.ts` already does this: `export * from './api/useResolvedExtensions';`
> 
> But it doesn't look like this is exported in the final built lib.
> Should it have been?

@christianvogt The `main` field of dynamic SDK package today points to `src/index.ts` which is used to export stuff for use in other Console monorepo packages. This is different from transpiled & exported stuff for use in actual dynamic plugins outside the monorepo.

> What about `common-types` as well?

We need to decide which parts of that should be exposed to actual dynamic plugins.

**Comment by christianvogt** [comment]
api lgtm

**Comment by bipuladh** [comment]
/assign @yapei 
Could you please test it out?

**Comment by yapei** [comment]
tested locally, confirmed that the feature Flags and Models are returned when visiting `http://localhost:9000/test-consumer`

**Comment by spadgett** [comment]
/label px-approved docs-approved
/hold cancel

This PR has no user visible changes. @sferich888 @ahardin-rh FYI

**Pull request merged**
