### PR TITLE
Monitoring: Use the text "Expire Silence" instead of "Cancel Silence"

### PR DESCRIPTION
**Pull request by kyoto**
FYI @cshinn 

### Before
before-1
before-2

### After
screenshot-1
screenshot-2

### CODE REVIEW

**Comment by kyoto** [comment]
jenkins rebuild

**Comment by kyoto** [comment]
jenkins rebuild

**Comment by kyoto** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
