### PR TITLE
Rename "Search" to "All Resources" and "Explore" to "All Types"

### PR DESCRIPTION
**Pull request by spadgett**
Revisiting the nav item names.

@bmignano @alimobrem @serenamarie125 @christianvogt @smarterclayton 

Screenshot_2020-02-24 All Resources · OKD

Screenshot_2020-02-24 All Types · OKD

Screenshot_2020-02-24 Config Map · OKD

Screenshot_2020-02-24 Topology · OKD

### CODE REVIEW

**Comment by spadgett** [comment]
Added a separator based on feedback from @bmignano 

Screenshot_2020-02-24 Overview · OKD(1)

**Comment by serenamarie125** [comment]
@spadgett I'm not sure this is a change we want on the Dev side.  
@sspeiche Is this intended for 4.4 or 4.5?

**Comment by Ranelim** [comment]
Do the "All Types" menu item serve as a generic "Help", to help the user understand basic concepts/components in the cluster (like: "what is ConfigMap")?

If it is, it might (more?) useful to place that info on the resource pages themselves first?
If we want to keep it as a menu item, it might worth considering collaboration with the documentation team to create a softer landing on this page for users who just want to get a big picture of what's going on.
A "Help" menu item, either in the side nav or horizontal nav sounds a bit more self-explanatory than "Types" cause I'm not sure what Types mean in this side menu context.

**Comment by spadgett** [comment]
@Ranelim It's not just help. It allows you to drill into all the specific types for this cluster (including custom resources), list instances, check who has access, etc.

https://blog.openshift.com/openshift-4-2-the-api-explorer/

@serenamarie125 If we don't change the name on the dev side, the page header won't match the nav. Wouldn't it be confusing to call the same page different things in different perspectives? I suspect in practice users don't stay in only one perspective.

Search and Explore don't convey what either page does. There must be a better names. Surely we can find something that makes everyone equally unhappy :)

**Comment by bmignano** [comment]
@spadgett @serenamarie125 Agree that the page title should be the same in both perspectives. Otherwise we introduce so much more potential confusion 😄
I'm also curious about the timeline. I think it'd be really helpful to do some quick user testing to make sure that whatever combination of page titles we move forward with are backed by data. What's the latest date this could get in for 4.4?

**Comment by bmignano** [comment]
It seems unlikely we'll be able to validate in time for 4.4. I'd recommend closing this out for now in favor of testing the titles with users and aiming for a 4.5 release. We'll be much more confident in the change after testing and will hopefully make this a one-time change. Thoughts? @spadgett @benjaminapetersen @alimobrem @beanh66 @serenamarie125

**Comment by serenamarie125** [comment]
Personally don't think a name change at this late time makes sense for 4.4.  Agreed that if functionality matches we should have the same name.  Going forward, we may deviate on the dev side.

**Pull request closed without merging**
