### PR TITLE
Bug 1878835: Make whole quick start badge clickable

### PR DESCRIPTION
**Pull request by rohitkrai03**
**Fixes**: https://issues.redhat.com/browse/ODC-4812

**Analysis / Root cause**: The quick start badge is not fully clickable.

**Solution Description**: Update the badge to make it all clickable.

**Screen shots / Gifs for design review**: 

@openshift/team-devconsole-ux @gdoyle1 

Peek 2020-09-14 22-08

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by gdoyle1** [comment]
@rohitkrai03 sorry to be _more_ of a pain, but even on hover, the text color should be green:
Here's [the link to the page](I left something simple. Basically they just need to include the FAR icon(s) themselves but could do that a lot of ways. Maybe that's hosting it themselves (https://fontawesome.com/how-to-use/on-the-web/setup/hosting-font-awesome-yourself), including via a package manager (https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers), linking to a CDN (https://cdnjs.com/libraries/font-awesome), etc... you can even get the SVG source from fontawesome.com and include that manually though I think that requires attribution.) where you can hover over `green link removeable` example 
quickstart-label-update-hover

**Comment by rohitkrai03** [comment]
> @rohitkrai03 sorry to be _more_ of a pain, but even on hover, the text color should be green:
> Here's [the link to the page](https://www.patternfly.org/v4/documentation/react/components/label#filled) where you can hover over `green link removeable` example
> quickstart-label-update-hover

@gdoyle1 Fixed. The styles from bootstrap were overriding PF styles here. That what happens when we use two different PF versions together in one app.

**Comment by gdoyle1** [comment]
@rohitkrai03 thank you!! looks good to me

**Pull request merged**
