### PR TITLE
Bug 2028170: Remove whitespaces around mirroring card popover

### PR DESCRIPTION
**Pull request by rexagod**
Removes whitespaces around mirroring card popover under BlockPools. The text inside the popover was unchanged before and after the modification in the code.
***
#### Before (and after)
Screenshot from 2021-12-02 15-31-37

### CODE REVIEW

**Review by afreen23 — APPROVED** [review]
cc @GowthamShanmugam please check once and approve

**Comment by cloudbehl** [comment]
Why do we have space between image and (PV) `image (PV)`?

**Comment by GowthamShanmugam** [comment]
> Why do we have space between image and (PV) `image (PV)`?

you mean ```image(PV)``` instead of ```image (PV)```

**Comment by cloudbehl** [comment]
> you mean `image(PV)` instead of `image (PV)` ?

Yes

**Comment by GowthamShanmugam** [comment]
> > you mean `image(PV)` instead of `image (PV)` ?
> 
> Yes

@rexagod Please check this

**Comment by rexagod** [comment]
> 
> 
>         you mean image(PV) instead of image (PV) ?
> 
>     Yes
> 
> @rexagod Please check this

[This](https://www.btb.termiumplus.gc.ca/tpv2guides/guides/wrtps/index-eng.html?lang=eng&lettr=indx_catlog_p&page=9zTwhStstj28.html) suggests that we should keep this change, thoughts?

```
Parentheses and brackets

One space before and none after an opening parenthesis or bracket within a sentence; no space before or after a closing parenthesis or bracket that is followed by a punctuation mark:

    Please read the enclosed booklet (Using Your Modem); it will help you take full advantage of your new communication tool.

No space before or between parentheses enclosing subsections, paragraphs, subparagraphs, etc., in citations from legislation:

    subparagraph 123(4)(b)(ii)
```

**Pull request merged**
