### PR TITLE
Improve display of Pods table columns

### PR DESCRIPTION
**Pull request by rhamilto**
@bmignano PTAL.

Note the position of the kebab will be tweaked by changes in #3368

After:
localhost_9000_k8s_cluster_projects (5)
localhost_9000_k8s_cluster_projects (7)
localhost_9000_k8s_cluster_projects (8)
localhost_9000_k8s_all-namespaces_pods
localhost_9000_k8s_all-namespaces_pods (1)

### CODE REVIEW

**Comment by bmignano** [comment]
@rhamilto I'm wondering about the order in which we add columns. I tend to think that the columns should be ordered by importance and thus reflect that order when adding columns on the right in larger views. If the order in which they are added in the above examples demonstrates relative importance, I think the columns should be ordered: Name, Namespace, Status, Owner, Node, Readiness. Thoughts?

**Comment by rhamilto** [comment]
> @rhamilto I'm wondering about the order in which we add columns. I tend to think that the columns should be ordered by importance and thus reflect that order when adding columns on the right in larger views. If the order in which they are added in the above examples demonstrates relative importance, I think the columns should be ordered: Name, Namespace, Status, Owner, Node, Readiness. Thoughts?

I don't have a strong opinion one way or another.  I maintained the existing order (where Status is beside Readiness since they're related), but made Status appear earlier since its an important column.

**Comment by spadgett** [comment]
Status and readiness are closely related, so I think it makes sense to keep those together here.

I suspect we're going to remove node to make space for memory and CPU usage. I wouldn't be against pulling owner and node to the right, although I do think visually there's a nice balance with all the resource links together in adjacent columns.

It might be good to try to keep the status column in roughly the same place across pages (nodes, routes, projects, replication controllers, etc.)

**Comment by bmignano** [comment]
I like the idea of the status column being in generally the same spot across pages. It looks like today status is typically one of the last columns on most pages – does it make sense to move it left so that the order is generally Name, Namespace, Status, ...etc.? It seems like it'd be fairly important for a lot of the resources. In that case I'd say we should move owner and node over.
Also, is it possible to potentially combine Status and Readiness into a single column? Could help us make way for additional columns too. @beanh66 @alimobrem Curious what you think!

**Comment by rhamilto** [comment]
>  does it make sense to move it left so that the order is generally Name, Namespace, Status, ...etc.? It seems like it'd be fairly important for a lot of the resources. In that case I'd say we should move owner and node over.

localhost_9000_k8s_all-namespaces_pods
localhost_9000_k8s_all-namespaces_pods (1)

> Also, is it possible to potentially combine Status and Readiness into a single column?

Yes, but that significantly impacts the filtering and column sorting functionality.  I think we want to avoid this in order to maintain the existing functionality.

**Comment by spadgett** [comment]
I dislike combining columns in most cases because I think it makes the data harder to understand and breaks sorting.

We should consider showing a count for readiness like the CLI. Here are the CLI columns for reference:

```
$ oc get pods -n openshift-console
NAME                         READY   STATUS    RESTARTS   AGE
console-699c5bf8ff-26ndk     1/1     Running   1          23h
console-699c5bf8ff-sg9ss     1/1     Running   0          23h
downloads-79667dc568-4nx95   1/1     Running   0          23h
downloads-79667dc568-q62bv   1/1     Running   0          23h

~/work/console master
$ oc get pods -n openshift-console -o wide
NAME                         READY   STATUS    RESTARTS   AGE   IP            NODE                                         NOMINATED NODE   READINESS GATES
console-699c5bf8ff-26ndk     1/1     Running   1          23h   10.128.0.31   ip-10-0-150-74.us-east-2.compute.internal    <none>           <none>
console-699c5bf8ff-sg9ss     1/1     Running   0          23h   10.129.0.46   ip-10-0-137-70.us-east-2.compute.internal    <none>           <none>
downloads-79667dc568-4nx95   1/1     Running   0          23h   10.131.0.3    ip-10-0-134-26.us-east-2.compute.internal    <none>           <none>
downloads-79667dc568-q62bv   1/1     Running   0          23h   10.129.2.3    ip-10-0-170-137.us-east-2.compute.internal   <none>           <none>
```

**Pull request merged**
