### PR TITLE
[release-3.11] Downstream build updates

### PR DESCRIPTION
**Pull request by spadgett**
/assign @sosiouxme

### CODE REVIEW

**Comment by sosiouxme** [comment]
/lgtm
ship it :ship:

**Comment by sosiouxme** [comment]
no luck w https://s3.amazonaws.com/teamui-jenkins/jenkins-console-build-10225/GUI-Tests-OLM.log
/retest

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by sosiouxme** [comment]
not looking good today :)

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
