### PR TITLE
Add infotip and remove not bindable filter

### PR DESCRIPTION
**Pull request by divyanshiGupta**
**Fixes:** https://issues.redhat.com/browse/ODC-6607

This PR removes "not bindable" filter from `Service binding` filters and adds a infotip. It also updates `Service Binding` filter label to `Service binding`.

https://user-images.githubusercontent.com/20724543/162733516-5bdc10cd-ff32-4fba-9d21-317500dda778.mov

Screenshot 2022-04-12 at 6 35 26 PM

/kind feature

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
@serenamarie125 PTAL. Also can you confirm if the infotip text looks good to you?

**Comment by serenamarie125** [comment]
Meet with Stevan to confirm this in a bit, will get back to you later today @divyanshiGupta!

**Comment by serenamarie125** [comment]
Please update the popover text with the following:
Bindable services are easily consumed by applications because they expose their binding data (credentials, connection details, volume mounts, secrets, etc.) in a standard way.

**Comment by debsmita1** [comment]
PR works fine
/lgtm

**Comment by debsmita1** [comment]
verified on a dev cluster
/label qe-approved

**Comment by invincibleJai** [comment]
/label docs-approved
/label px-approved

propagating above labels based on ACKs on epic

**Pull request merged**
