### PR TITLE
[release-4.13] OCPBUGS-22986: Correct logout process

### PR DESCRIPTION
**Pull request by TheRealJon**
Manual cherry-pick of https://github.com/openshift/console/pull/13173

### CODE REVIEW

**Comment by TheRealJon** [comment]
/hold

This does remove some multicluster logout code from 4.13. I think this is okay since this was still a tech preview feature at that point and has since been deprecated, but wanted to make sure it's okay.

@jhadvig @spadgett, wdyt?

**Comment by TheRealJon** [comment]
> /hold
> 
> This does remove some multicluster logout code from 4.13. I think this is okay since this was still a tech preview feature at that point and has since been deprecated, but wanted to make sure it's okay.
> 
> @jhadvig @spadgett, wdyt?

I can refactor a bit to keep the multicluster logout code intact if needed, but it'll require kind of a novel fix, different from the original 4.14 one.

**Comment by TheRealJon** [comment]
/hold cancel

I refactored this to keep the multicluster logout functionality intact since removing it is out of scope for this bug and it seemed to be causing issues.

**Review by jhadvig — APPROVED** [review]
/lgtm
/label backport-risk-assessed

**Comment by yanpzhan** [comment]
Tried on cluster launched against the pr, sent a post to a page by a script in tab A when user logged out from another tab B, the post page redirected to login page, without inputting user/passwd, console page did not show up.
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
