### PR TITLE
Bug 1804447: Monitoring Dashboards: Fix graph legends

### PR DESCRIPTION
**Pull request by kyoto**
We need to add back some space for graphs that have legends.

### CODE REVIEW

**Comment by kyoto** [comment]
The disadvantage of this approach is that there is a blank space below graphs with no legend.

However, adding a consistent padding like this means all graph panels stay the same height.

Also, we are close to code freeze, so I prefer a simple solution.

**Comment by spadgett** [comment]
I put a hold on #4553 for now. @sg00dwin can you help investigate?

**Comment by kyoto** [comment]
With legend
legend

No legend
no-legend

**Comment by sg00dwin** [comment]
@kyoto Adding the extra spacing to `graph-wrapper--query-browser` instead of `query-browser__wrapper` also works and it doesn't effect the single-state panels. So I opened this pr instead. https://github.com/openshift/console/pull/4562

**Comment by spadgett** [comment]
> @kyoto Adding the extra spacing to `graph-wrapper--query-browser` instead of `query-browser__wrapper` also works and it doesn't effect the single-state panels. So I opened this pr instead. #4562

Closing in favor of #4562 since it doesn't affect single stat panels.

/close

**Pull request closed without merging**
