### PR TITLE
ODC-5917-Fix the scripts for create-from-add-options feature

### PR DESCRIPTION
**Pull request by makambalaji**
**Jira Id**: https://issues.redhat.com/browse/ODC-5917

**Description**:
P-01-TC03 | On Second run, script worked fine
P-01-TC06 | created seperate functions for docker file page
P-01-TC07 | On Second run, script worked fine
P-01-TC09 | Removing this test scenario 
P-04-TC04 Updating pipelines section title in side bar

**Browser & its version** : Chrome 91

**Setup**:
Update the [script](https://github.com/openshift/console/blob/master/frontend/packages/pipelines-plugin/integration-tests/package.json#L11) in package.json as `"test-cypress-headless": "node --max-old-space-size=4096 ../../../node_modules/.bin/cypress run --env openshift=true --browser ${BRIDGE_E2E_BROWSER_NAME:=chrome} --headless cypress:cli,cypress:server:specs --spec \"features/*/create-from-add-options.feature\";"` 

**Execution Commands**:
In below commands, please update url and password based on the cluster

```
export NO_HEADLESS=true && export CHROME_VERSION=$(/usr/bin/google-chrome-stable --version)
BRIDGE_KUBEADMIN_PASSWORD=YH3jN-PRFT2-Q429c-5KQDr
BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.dev-svc-4.8-042801.devcluster.openshift.com
export BRIDGE_KUBEADMIN_PASSWORD
export BRIDGE_BASE_ADDRESS
oc login -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD https://api.gamore48installer7thjune001.devcluster.openshift.com:6443  --insecure-skip-tls-verify
oc apply -f ./frontend/integration-tests/data/htpasswd-secret.yaml
oc patch oauths cluster --patch "$(cat ./frontend/integration-tests/data/patch-htpasswd.yaml)" --type=merge
./test-cypress.sh -p pipelines
```
Select the "create-from-add-options.feature"

**Screenshots**
image

### CODE REVIEW

**Comment by sanketpathak** [comment]
Some of the tests are failing for `create from add options` and `pipelines-runs`
Screenshot from 2021-06-08 01-52-48
Screenshot from 2021-06-08 02-13-17

**Comment by karthikjeeyar** [comment]
8 Passed - 10 Skipped out of 18 tests.

image

In Headless mode, I ran a couple of times and I get the following error
image

image

**Comment by makambalaji** [comment]
Its updated, Please review it now

**Comment by gajanan-more** [comment]
Screenshot from 2021-06-09 15-08-15
Screenshot from 2021-06-09 15-01-43

Working as expected in both the modes. 
/lgtm

**Pull request merged**
