### PR TITLE
Add quick search to add page

### PR DESCRIPTION
**Pull request by vikram-raj**
**Story:** https://issues.redhat.com/browse/ODC-6402

**Descriptions:** 
Add quick search to dev console add page

**Screenshots / GIFs:**
image

Kapture 2021-10-29 at 20 30 08

### CODE REVIEW

**Review by sahil143 — CHANGES_REQUESTED** [review]
Quick search modal is not draggable vertically

https://user-images.githubusercontent.com/9278015/140747106-0a0ad2eb-3fd0-4523-bea0-5edae459fc2e.mp4

**Comment by beaumorley** [comment]
@vikram-raj 
This looks great. One question. Can you show in this PR how it would look if the user was on the Topology screen and clicked on the +Add. So we can see the icon in both places? Either take a screen cap of each screen to compare or another gif so we can see the transition? Thank you.

**Comment by vikram-raj** [comment]
@beaumorley 

Kapture 2021-11-16 at 20 06 39

**Comment by beaumorley** [comment]
@vikram-raj Thank you for adding the last gif. It looks really nice. UX is good with this.

**Comment by vikram-raj** [comment]
> Quick search modal is not draggable vertically
> 

@sahil143 I fixed the vertical drag issue. PTAL.
Kapture 2021-11-17 at 12 31 46

**Comment by debsmita1** [comment]
2 scrollbar appears when the modal is dragged to the bottom of the page

scroll

**Comment by vikram-raj** [comment]
> 2 scrollbar appears when the modal is dragged to the bottom of the page
> 

@debsmita1 It is the existing issue with the quick search modal. The issue has been logged here https://bugzilla.redhat.com/show_bug.cgi?id=2008486

**Review by jerolimov — COMMENTED** [review]
@vikram-raj Works fine, but can we add some unit or e2e (cypress) for this?

**Comment by vikram-raj** [comment]
> @vikram-raj Works fine, but can we add some unit or e2e (cypress) for this?

We have a separate [ticket](https://issues.redhat.com/browse/ODC-6423) for adding the e2e test and Sanket is working on it.

**Review by jerolimov — APPROVED** [review]
Okay, thanks for that info. I think we should add more tests in the future as part of any story directly. But I approve this for the moment.

/approve

**Comment by vikram-raj** [comment]
Propagate from epic:
/label docs-approved
/label px-approved

**Comment by jerolimov** [comment]
Tested this on a cluster with cluster bot and works there fine as well.

/label qe-approved

**Pull request merged**
