### PR TITLE
Bug 1999614: Add name field in edit deployment form

### PR DESCRIPTION
**Pull request by divyanshiGupta**
**Fixes:** https://issues.redhat.com/browse/ODC-6228

**Screenshot:**
Screenshot 2021-08-27 at 10 05 21 PM

/kind bug

### CODE REVIEW

**Review by sahil143 — APPROVED** [review]
/lgtm

verified locally. Can see the disabled input field on Edit Deployment and DC form

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
