### PR TITLE
Bug 1958811: KubeVirt v1 GA api

### PR DESCRIPTION
**Pull request by yaacov**
The UI is using deprecated kubevirt API version, this PR update to current version.

Signed-off-by: yaacov <kobi.zamir@gmail.com>

### CODE REVIEW

**Comment by yaacov** [comment]
@glekner @metalice @pcbailey  please review

**Comment by yaacov** [comment]
/hold

test failing, hold until tests fixed

**Comment by gouyang** [comment]
verified that the VM can be created on latest CNV 4.8 with this patch.

**Pull request merged**
