### PR TITLE
Bug 1933666: [release-4.6] Create ImageStream and other resources for samples step by step

### PR DESCRIPTION
**Pull request by jerolimov**
This is a manual cherry-pick of #8222 because DevFile changes are not available in 4.6

BZ for 4.6 https://bugzilla.redhat.com/show_bug.cgi?id=1933666 depends on 4.7 https://bugzilla.redhat.com/show_bug.cgi?id=1933665 which depends on 4.8 issue https://bugzilla.redhat.com/show_bug.cgi?id=1933664

edit: This also fixes https://bugzilla.redhat.com/show_bug.cgi?id=1921717 (Deployment creates a huge number of ReplicaSets)

/assign jerolimov

### CODE REVIEW

**Comment by jerolimov** [comment]
Tested it on a 4.6 cluster, happy to have another lgtm

/approve

**Comment by jerolimov** [comment]
Tested this branch locally with a 4.6 cluster, works for me.

/lgtm

**Comment by jerolimov** [comment]
Checked this now on a cluster-bot cluster for this PR as well. With this PR the resources are created sequential instead of parallel. Here is the recorded network tab in Chrome:

https://user-images.githubusercontent.com/139310/113839381-ebf8ca00-978f-11eb-9486-21c5b5faac00.mp4

/lgtm

**Comment by mfojtik** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.


* Score: *0.10*
* Reason: *maximum total for this z-stream is 10*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Pull request merged**
