### PR TITLE
Bug 2052986: fix console crashing in the edit deployment form

### PR DESCRIPTION
**Pull request by debsmita1**
**Fixes:**
https://issues.redhat.com/browse/OCPBUGSM-40566

**Root analysis:**
When the initial values of strategy data (which is `deploymentStrategy` here ) contains only pre & post lifecycle hooks then on spreading, it overwrites the default strategy values (which contains all the 3 lifecycle hooks data) and removes the mid lifecycle hook from the final data

**Solution description:**
using lodash's merge

**GIF:**
edit-dc

/kind bug

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
@debsmita1 it looks like this PR https://github.com/openshift/console/pull/9766 introduced this bug. Also what was the reason behind removing this - https://github.com/openshift/console/pull/9766/files#diff-1c30be5b175823bf10dac87c91792ad79efba4c889a4777321454b572d98efedL59-L64 ?

**Comment by debsmita1** [comment]
> @debsmita1 it looks like this PR #9766 introduced this bug. Also what was the reason behind removing this - https://github.com/openshift/console/pull/9766/files#diff-1c30be5b175823bf10dac87c91792ad79efba4c889a4777321454b572d98efedL59-L64 ?

@divyanshiGupta  When the initial values of strategy data (which is `deploymentStrategy` here ) contains only pre & post-lifecycle hooks, then on spreading, it overwrites the default strategy values (which contains all the 3 lifecycle hooks data) and removes the mid lifecycle hook from the final data. So I am using merge here so that I can retain the values entered by the user and also show default values for the fields that are not touched.

**Comment by divyanshiGupta** [comment]
> > @debsmita1 it looks like this PR #9766 introduced this bug. Also what was the reason behind removing this - https://github.com/openshift/console/pull/9766/files#diff-1c30be5b175823bf10dac87c91792ad79efba4c889a4777321454b572d98efedL59-L64 ?
> 
> @divyanshiGupta When the initial values of strategy data (which is `deploymentStrategy` here ) contains only pre & post-lifecycle hooks, then on spreading, it overwrites the default strategy values (which contains all the 3 lifecycle hooks' default data) and removes the mid lifecycle hook from the final data. So I am using merge here so that I can retain the values entered by the user and also show default values for the fields that are not touched.

@debsmita1 on spreading it might override values of same properties but it will not remove any property. Also I see another issue that is when initial values of all the three hooks and the default has 2 then it will add the hook that is not present. I will run this locally and test these edge cases.

**Review by divyanshiGupta — CHANGES_REQUESTED** [review]
@debsmita1 I ran it locally and it works fine but just to make sure we don't face any such issues in future can you add some more unit tests in `DeploymentStrategySection.spec.tsx`? Maybe some tests covering these edge cases will be good.

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
