### PR TITLE
Bug 2090895: Support startsWith Nav Extension property

### PR DESCRIPTION
**Pull request by andrewballantyne**
Supporting `startsWith` from the navigation extensions.

I'm a bit unsure if it was ever supported. Quick searching of the history appears it was not supported in this manner.

To test this, you simply need to add a snippet like this one to any `console.navigation/href`, `console.navigation/resource-ns` or `console.navigation/resource-cluster` extension in the `dynamic-demo-plugin`.
```
      "startsWith": ["test"],
```
Then navigate to any of the Dynamic Plugin routes that start with `test` and the navs whom you modified will highlight.

/assign @TheRealJon

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
> /cc @jeff-phillips-18
> 
> Jeff, do you ever recall this working when you were reworking our nav to support pinned items back a couple years ago?

I don't recall it working like this before

**Review by TheRealJon — CHANGES_REQUESTED** [review]
Sections also need to be marked as active when a child is active. Check out the static `startsWith` function that's already implemented on the `NavLink` class. I'm not sure why this was never used, but we could use it in all of the inheriting classes so that [this](https://github.com/openshift/console/blob/master/frontend/public/components/nav/utils.ts#L163-L173) function will just work.

**Comment by andrewballantyne** [comment]
> Sections also need to be marked as active when a child is active. Check out the static `startsWith` function that's already implemented on the `NavLink` class. I'm not sure why this was never used, but we could use it in all of the inheriting classes so that [this](https://github.com/openshift/console/blob/master/frontend/public/components/nav/utils.ts#L163-L173) function will just work.

Yup, the test scenario was not part of what I was testing. Good catch.

To test this you'll need to add an extension that uses `startsWith` that aligns to another section's item. So when you select one nav item, it can highlight a hidden nav item under another section.

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Pull request merged**
