### PR TITLE
Add alert in subscription details with failure info

### PR DESCRIPTION
**Pull request by jcaianirh**
Add alert with failure message only when the install has failed, and populate the a message about the failure. 

Address the rich subscription status in design here: https://docs.google.com/document/d/1hQR4QFYa05YHIFBFfZoVFB46ubtFjr-KE48fXuENjJY/edit#

### CODE REVIEW

**Comment by spadgett** [comment]
Actually, we should squash. I'll retag when you push again.

/lgtm cancel

**Comment by jcaianirh** [comment]
@spadgett squashed

**Comment by spadgett** [comment]
Needs rebase

**Comment by jcaianirh** [comment]
@spadgett rebased

**Pull request merged**
