### PR TITLE
OCPBUGS-30457: Bump github.com/prometheus/common to latest

### PR DESCRIPTION
**Pull request by TheRealJon**
- Update to golang v1.22
- Updates some inderect deps, including google.golang.org/protobuf to v1.33.0

### CODE REVIEW

**Comment by TheRealJon** [comment]
/hold

/assign @yapei 

Needs regression testing. Golang has been bumped two major versions, and other indirect deps were also bumped.

**Comment by TheRealJon** [comment]
@jhadvig Can you use these changes to build and push a v27 builder image with golang 1.21? I don't have permission.

**Comment by spadgett** [comment]
@TheRealJon I built and pushed an image:

https://quay.io/repository/coreos/tectonic-console-builder?tab=tags

**Comment by TheRealJon** [comment]
@spadgett Is there another step that needs to happen? Tests are still failing to pull the new image:

```
WARN[2024-04-09T18:12:26Z] Waiting for imagestreamtag ci/tectonic-console-builder:v27 failed  error=timed out waiting for the condition
```

**Comment by TheRealJon** [comment]
/hold

Wait for #13830

**Comment by TheRealJon** [comment]
https://issues.redhat.com//browse/OCPBUGS-29499 addresses this issue.

**Pull request closed without merging**
