### PR TITLE
[release-4.2] Bug 1787585: Fix off by one bug in metrics rows count

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by rhamilto** [comment]
/hold

OLM integration tests appear to be broken

**Comment by rhamilto** [comment]
/hold cancel

/retest

https://github.com/openshift/console/pull/3885 should resolve integration test issues.

**Comment by ashcrow** [comment]
Looks like this is a backport of https://github.com/openshift/console/pull/3858.

**Pull request merged**
