### PR TITLE
[release 4.9] Bug 2042683: Check rbac before polling for rules silences

### PR DESCRIPTION
**Pull request by jcaianirh**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2042683

### CODE REVIEW

**Comment by florkbr** [comment]
Original master PR: https://github.com/openshift/console/pull/10725

**Review by florkbr — APPROVED** [review]

**Comment by jcaianirh** [comment]
Console Approver:
/assign @jhadvig 

Backport Risk Assessed:
/assign @kdoberst

**Comment by yanpzhan** [comment]
Tested against the pr, login console with normal user, check in dev console, there is no error about "/api/prometheus/api/v1/rules
/api/alertmanager/api/v2/silences"

**Pull request merged**
