### PR TITLE
[release-4.8] Bug 2036045: fix resource limit form validation

### PR DESCRIPTION
**Pull request by debsmita1**
This is a manual cherry-pick of #9489

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Thanks for the manual cherry-pick. Code is now similar to the change in 4.9.

Tested this locally and it works fine.

/approve
/lgtm
/label backport-risk-assessed

**Comment by sanketpathak** [comment]
Verified pr in cluster created using cluster-bot
Screenshot from 2022-01-21 17-27-29
/label cherry-pick-approved

**Pull request merged**
