### PR TITLE
Bug 2017050: CONSOLE-2963: Update dynamic plugin SDK to latest webpack

### PR DESCRIPTION
**Pull request by rawagner**
released as 0.0.2-wp5 https://www.npmjs.com/package/@openshift-console/dynamic-plugin-sdk so it can be easily tested

used in action in https://github.com/rawagner/console-dynamic-foo

This should unblock teams that need latest webpack

There are plenty of additional stuff in latest webpack module federation which we can take advantage of, but this PR is just a minimal set of changes needed to make it work.

### CODE REVIEW

**Review by spadgett — COMMENTED** [review]
Excellent work. @rawagner Were you able to test if this breaks runtime compatiblity of plugins? (Will 4.9 plugins run on 4.10 with this change and vice versa?) Either way, we have to move off the beta version of webpack, but it would be good to understand the impact to existing plugins.

**Comment by rawagner** [comment]
@spadgett I added a new commit which falls back to callng `override` (the webpack5beta16 function) if `init` (latest webpack) does not exist. That should make us compatible with 4.9 plugins.
I tried with https://github.com/rawagner/console-dynamic-foo built against `0.0.2` SDK version (wp5beta16). The console was running webpack latest SDK build and the `foo` plugin was correctly loaded

**Comment by rawagner** [comment]
If we also want to be able to load 4.10 plugins in 4.9 console, I think thats doable. We have to backport subset of changes from this PR. 
However 4.10 has more APIs exposed so the plugin that wants to backwards compatible cannot use those new APIs.

**Comment by spadgett** [comment]
I think 4.9 plugin compatibility with 4.10 clusters is what's important 👍 

Any chance this indirectly fixes https://bugzilla.redhat.com/show_bug.cgi?id=2017050 ?

**Comment by rawagner** [comment]
> Any chance this indirectly fixes https://bugzilla.redhat.com/show_bug.cgi?id=2017050 ?

There is a chance :) I tried your plugin with https://github.com/spadgett/console-customization-plugin/pull/1 and didnt see PF being loaded twice

**Comment by spadgett** [comment]
Unfortunately, I was able to reproduce bug 2017050 with these changes.

**Comment by spadgett** [comment]
Disregard the above comment. I didn't notice that I had a build error when building the plugin. The PR fixes the bug!

**Review by spadgett — APPROVED** [review]
/lgtm

👍

**Review by zherman0 — APPROVED** [review]

**Pull request merged**
