### PR TITLE
dashboard: Allow multi-line charts in UtilizationItem

### PR DESCRIPTION
**Pull request by rawagner**
replaces https://github.com/openshift/console/pull/3089

@mareklibra @andybraren please take a look

Screenshot from 2020-01-20 14-09-38
Screenshot from 2020-01-20 14-09-17

note that the cursor is always in the middle of tooltip - the behavior is from VictoryVoronoiContainer which I was not able to alter
Screenshot from 2020-01-20 14-27-36

### CODE REVIEW

**Comment by andybraren** [comment]
image

> note that the cursor is always in the middle of tooltip - the behavior is from VictoryVoronoiContainer which I was not able to alter

Looks a little odd 😄

@dlabrecq would you happen to know why this is happening? The [Victory example](https://formidable.com/open-source/victory/docs/victory-voronoi-container/) and [PatternFly examples](https://www.patternfly.org/v4/documentation/react/charts/chartarea) don't seem to have this issue. Is the triangle being missing related maybe?

**Comment by rawagner** [comment]
> image
> 
> > note that the cursor is always in the middle of tooltip - the behavior is from VictoryVoronoiContainer which I was not able to alter
> 
> Looks a little odd 
> 
> @dlabrecq would you happen to know why this is happening? The [Victory example](https://formidable.com/open-source/victory/docs/victory-voronoi-container/) and [PatternFly examples](https://www.patternfly.org/v4/documentation/react/charts/chartarea) don't seem to have this issue. Is the triangle being missing related maybe?

it is actually the same as Victory example where you have two lines and one tooltip for both - see https://formidable.com/open-source/victory/docs/victory-voronoi-container/#mousefollowtooltips

**Comment by andybraren** [comment]
Ah I see. Would we be able to use either the behavior of `voronoiBlacklist` (appearing over the top-most data points) or `voronoiDimension`'s behavior as a backup option? The `mouseFollowTooltips` behavior is very odd. 🙂

**Comment by rawagner** [comment]
`mouseFollowTooltips` is not set, but the points are so close together that it looks like it is.
`voronoiDimension` is already set to `x`
`voronoiBlacklist` could work but I need to choose a line which to block and that line can on top and then a few minutes later below the other one.

I used `centerOffset` to not have cursor in middle of tooltip. WDYT ?

Screenshot from 2020-01-21 13-06-57

**Comment by dlabrecq** [comment]
It could be that the `constrainToVisibleArea` prop is positioning the tooltip within its container?

**Comment by rawagner** [comment]
> constrainToVisibleArea

that is not set. The tooltip is actually able to go outside the chart.

**Comment by mareklibra** [comment]
Nitpicks only, otherwise lgtm

**Comment by rawagner** [comment]
@mareklibra fixed

**Pull request merged**
