### PR TITLE
CONSOLE-4234,CONSOLE-4298,CONSOLE-4299: Remove PF deprecated table from public/components/factory/table.tsx and public/components/factory/Table/VirtualizedTable.tsx

### PR DESCRIPTION
**Pull request by TheRealJon**
public/components/factory/table.tsx
- Refactor Table component to remove PatternFly deprecated Table component 
- Separate virtualized/non-virtualized tables into local sub-components
- Remove unused generic types
- Address some nits and tech debt

public/components/factory/Table/VirtualizedTable.tsx
- Refactor VirtualizedTable component to remove PatternFly deprecated Table component
- Address a few nits and tech debt

### CODE REVIEW

**Comment by TheRealJon** [comment]
QE Approver
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @reestr

**Comment by yanpzhan** [comment]
Regression test about table against the pr code passed.
/label qe-approved

**Review by rhamilto — APPROVED** [review]
/lgtm

**Pull request merged**
