### PR TITLE
Bug 1734601 - The statefulset created with default yaml will get error in page after add storage to it

### PR DESCRIPTION
**Pull request by jhadvig**
Don't show any `VolumeType` reference if the  container has `volumeMount` defined, but it's not part of the spec's `volumes`
eg:
```
kind: StatefulSet
...
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
    spec:
      volumes:
        - name: www-example-0
          persistentVolumeClaim:
            claimName: www-example-0
      containers:
        - name: nginx
          image: 'gcr.io/google_containers/nginx-slim:0.8'
          ports:
            - name: web
              containerPort: 80
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
            - name: www-example-0
              mountPath: /data1
...
```

Screen:
Screen Shot 2019-07-31 at 17 04 45

/assign @zherman0 

ccíng @rhamilto

### CODE REVIEW

**Comment by zherman0** [comment]
@jhadvig - This needs a little more discussion.  While this does fix the issue of the page loading, there are other issues that are not visible.  Specifically, the "Remove Volume" will cause a lot of damage if someone tries to delete the VolumeMount that has no volume to go along with it.  
I think the question becomes should we be showing a VolumeMount in the Volumes table that does not have a Volume entry?
```
volumeMounts:
            - name: www
              mountPath: /usr/share/nginx/html
```
This uses a `volumeClaimTemplates` instead of a typical Volumes entry in the yaml. I am not sure what we should do for this type of configuration so I will need to do some further research.

**Comment by jhadvig** [comment]
@zherman0 PR is ready for another review, per our discussion

**Comment by zherman0** [comment]
After reviewing the code, we decided to show the `volumeMounts` that do not have a standard `Volume` entry as that is how the code worked prior to our last round of changes.  We can revisit how we show stateful sets volume mounts in the future if it is an issue.

**Pull request merged**
