### PR TITLE
Bug 1905066: Monitoring smoke test cases

### PR DESCRIPTION
**Pull request by makambalaji**
Jira Id : https://issues.redhat.com/browse/ODC-4157
Bugzilla Id; https://bugzilla.redhat.com/show_bug.cgi?id=1905066

Renamed the feature files and added the scripts related to monitoring

Please Note: This scripts are not integrated with CI
If need to verify, execute the below command "npm run test-cypress-devconsole" on fronted
On cypress UI, please select the appropriate file 

Test Results:
No. of smoke test cases in this pr : 13 [Execution Time: ]
No. of regression test cases in this pr: 1 [Execution Time: ]

Defect Raised :

Note: a couple of test cases are not executed due to unavailability of locators will fix it once this or is merged

### CODE REVIEW

**Comment by andrewballantyne** [comment]
@makambalaji we should close this off if we have no intentions of getting it merged. The BZ is on our backlog and thus needs to be triaged a few more times before the end of this sprint. Please either rebase and seek appropriate reviews or close this PR and the BZ. Thanks!

**Comment by makambalaji** [comment]
closed this pr and created new pr : https://github.com/openshift/console/pull/7984

**Pull request closed without merging**
