### PR TITLE
ODC-7664: Add subscribe form for Knative EventType

### PR DESCRIPTION
**Pull request by vikram-raj**
Story: https://issues.redhat.com/browse/ODC-7664

Descriptions: This PR adds a subscribe form for Knative EventType.

Screenshots:

https://github.com/user-attachments/assets/c747f167-f29d-46c6-8ffb-e11f80f31582

image

Test setup:

- Install Serverless operator and create Knative Serving and Eventing CR
- Enable eventtype-auto-create: enabled in ConfigMap config-features present in knative-eventing namespace
- Create a broker in your namespace kn broker create my-broker
- Send an event to broker kn event send \ --to Broker:eventing.knative.dev/v1:my-broker\ --type com.corp.integration.warning \ -f message="Hey there my Broker"
- Navigate to Events catalog from the Event action on the Add page

### CODE REVIEW

**Review by lokanandaprabhu — COMMENTED** [review]
1. When I first enter the Subscribe form, neither Form view nor YAML view was selected. After selecting once I am not able to see the issue

Screenshot 2024-10-07 at 11 35 11 AM

------

2. If service is not created then we are showing alert message as "To create a Subscriber, first create a Knative Service from the Add page." but we don't have the direct CTA in add page for service? can we add link or else to string "Knative Service" so that it will redirect the user to proper link

Screenshot 2024-10-07 at 11 37 02 AM

-----

3. Schema for spec is not there. Is this fine?

Screenshot 2024-10-07 at 11 39 15 AM

-----

4. Download button is not there in YAML view, is this ok?

Screenshot 2024-10-07 at 11 48 08 AM

------

5. I can see more spacing on top and bottom of Configure via, can we remove that? so that it will align to other forms. 


https://github.com/user-attachments/assets/b4559686-7e48-4356-8982-c998f8c55b3f

**Review by lokanandaprabhu — APPROVED** [review]

**Comment by The-Anton** [comment]
Tested using cluster bot, working fine 

/label qe-approved

image

**Pull request merged**
