### PR TITLE
Switch product Dockerfile to multistage build

### PR DESCRIPTION
**Pull request by spadgett**
@sosiouxme This should work now, correct?
/assign @sosiouxme 

Fixes https://jira.coreos.com/browse/CONSOLE-686

### CODE REVIEW

**Comment by spadgett** [comment]
ping @sosiouxme

**Comment by spadgett** [comment]
> However I'd like to have the golang and nodejs builds happen in their own builders, so please hold off on this.

I don't think that's too hard. What benefit do you see to doing it that way?

**Comment by spadgett** [comment]
ping @sosiouxme 

It would be good to get this in 3.11 since it impacts the image size. Do you mind if we add additional builders in a follow on?

**Comment by spadgett** [comment]
Closing in favor of #473

/close

**Comment by sosiouxme** [comment]
> However I'd like to have the golang and nodejs builds happen in their own
> builders, so please hold off on this.
>
> I don't think that's too hard. What benefit do you see to doing it that
> way?
>

The golang builder should be reusable for other builds. The nodejs builder
I'd like to capture exactly what tools were used in each build. They don't
strictly need to be separate but it seemed cleanest.

**Pull request closed without merging**
