### PR TITLE
[release-4.10]Update bucket-class.ts

### PR DESCRIPTION
**Pull request by orangeji11**
Single NamespaceStore description i18n

### CODE REVIEW

**Comment by orangeji11** [comment]
当前分支下我看到的内容，单命名空间桶描述部分未进行国际化工作：
截图_选择区域_20220914103249

**Comment by orangeji11** [comment]
cc @spadgett

**Comment by jerolimov** [comment]
Thanks for this PR, we can not merge this back into 4.10 without merging this to the latest version. I opened #12380 because it was required to also run `yarn i18n`. This change will be part of 4.13.

/close

**Pull request closed without merging**
