### PR TITLE
CONSOLE-3816: Goodbye!

### PR DESCRIPTION
**Pull request by bipuladh**
Removes Ceph static plugin from OCP console repository
Screenshot:
Screenshot from 2023-10-17 14-07-38

### CODE REVIEW

**Review by SanjalKatiyar — APPROVED** [review]

**Review by jhadvig — APPROVED** [review]
Thanks @bipuladh 🙌 
/lgtm
/approve

**Comment by rhamilto** [comment]
https://github.com/openshift/console/pull/13249 merged first, resulting in conflicts.  Rebase will be required.  Sorry, @bipuladh.

**Pull request merged**
