### PR TITLE
[release-4.14] OCPBUGS-32697: Routes created by devfiles do not always use HTTPS

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
This is manual cherry pick for PR - https://github.com/openshift/console/pull/13771

Video:

https://github.com/openshift/console/assets/102503482/a50543c8-d655-42b3-9f13-2177a4f14b96

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
/label backport-risk-assessed
/approve
/retest

**Comment by lokanandaprabhu** [comment]
@sanketpathak / @The-Anton ,

Need cherry-pick-approved label for this. PTAL.

**Pull request merged**
