### PR TITLE
Add Thanos tenancy proxy for rules

### PR DESCRIPTION
**Pull request by simonpasquier**
The Thanos querier deployment exposes a tenancy-aware service for
recording and alerting rules. It is exposed via a different port than
the existing tenancy-aware service for queries because it requires
different permissions to be granted.

This change modifies the console bridge to make this service available
to the console users.

cc @kyoto @vikram-raj

### CODE REVIEW

**Comment by vikram-raj** [comment]
We need this service for Monitoring work for 4.6.

/cc @christianvogt @abhi-kn

**Comment by simonpasquier** [comment]
cc @paulfantom for a review from the monitoring team.

**Comment by paulfantom** [comment]
LGTM, leaving final `/lgtm` to the console team.

**Comment by invincibleJai** [comment]
Thanks @paulfantom , @spadgett needed your help with review 

cc @vikram-raj

**Pull request merged**
