### PR TITLE
Fixed alignment of container and pod Volumes in pods page

### PR DESCRIPTION
**Pull request by cloudbehl**
**Before**
screenshot from 2018-11-14 23-52-18

**After**
screenshot from 2018-11-14 23-50-01

Signed-off-by: Ankush Behl <cloudbehl@gmail.com>

### CODE REVIEW

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
@cloudbehl please use `git rebase` instead of `git merge` to avoid the merge commit

**Comment by cloudbehl** [comment]
@spadgett Ahh ok! I actually used the git tool to resolve the conflict this PR was having. 

I can see what I did, will not repeat.

**Pull request merged**
