### PR TITLE
[release-4.9] OCPBUGS-695: Input values in Instantiate Template are disappeared randomly in the developer console

### PR DESCRIPTION
**Pull request by Lucifergene**
This is a manual cherry-pick of https://github.com/openshift/console/pull/11967

/cc @invincibleJai @rottencandy

### CODE REVIEW

**Comment by Lucifergene** [comment]
Tested this on a cluster bot:


https://user-images.githubusercontent.com/47265560/187416663-5a0e5d9e-2ad4-488d-82fc-26932736f2a1.mp4

**Comment by Lucifergene** [comment]
Waiting for [OCPBUGS-550](https://issues.redhat.com/browse/OCPBUGS-550) to be verified.
Once verified, this PR will get the `ValidBug` label from Jira.

**Comment by invincibleJai** [comment]
/lgtm
/label backport-risk-assessed

Have verified the changes and works as expected

wto-4 9

**Comment by invincibleJai** [comment]
/lgtm
/approve
/label backport-risk-assessed

Verified the changes and works as expected

template-4 9

**Comment by invincibleJai** [comment]
we would need https://issues.redhat.com//browse/OCPBUGS-550 to be verified 

cc @Lucifergene

**Pull request merged**
