### PR TITLE
Interop UI install multiple helm

### PR DESCRIPTION
**Pull request by shvasude**
Jira Id: https://issues.redhat.com/browse/HELM-15, https://issues.redhat.com/browse/HELM-70

Problem:
Add scenarios implementation for feature - on install helm chart
* Developer Catalog Page when Helm Charts checkbox is selected: HR-01-TC02, HR-02-TC02

Solution: Is to automate manual step converted to automated

Test Setup:
Add @Regression under env.tags in cypress.json
Run yarn run test-cypress-devconsole in frontend
Execute feature file: frontend/packages/dev-console/integration-tests/features/helm/install-HelmChart.feature

### CODE REVIEW

**Comment by spadgett** [comment]
/override ci/prow/ceph-storage-plugin

The ceph-storage-plugin job should only have run on PRs with changes to `frontend/packages/ceph-storage-plugin`. It failed due to an unrelated CI config change. Overriding status on this PR.

**Comment by makambalaji** [comment]
@shvasude - Please fix the conflicts and let us know
/assign @sanketpathak - Please review this pr

**Pull request closed without merging**
