### PR TITLE
Bug 1869783:  Fix column management help text

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1869783

After:
Screen Shot 2020-08-25 at 1 56 51 PM
Screen Shot 2020-08-25 at 12 57 15 PM

### CODE REVIEW

**Comment by gdoyle1** [comment]
@rhamilto Thanks for you work on this! The tooltip on the column icon should say "Manage columns".
Screen Shot 2020-08-25 at 1 25 05 PM

Otherwise, looks good to me!

**Comment by rhamilto** [comment]
Thanks, @gdoyle1.  I misread the bug.

**Comment by gdoyle1** [comment]
LGTM @rhamilto thanks!

**Pull request merged**
