### PR TITLE
Bug 1770808: Link to dev perspective metrics if admin monitoring is not available

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by lizsurette** [comment]
@rawagner - Does this mean we will show the Dashboards page to a dev user after all? Today, we hide this tab for certain roles.

**Comment by rawagner** [comment]
@lizsurette it's for other dashboards we show to user such as Project and VM. Dashboards page can still be seen only by admins and they can also see monitoring section so there wont be any difference

**Comment by lizsurette** [comment]
> @lizsurette it's for other dashboards we show to user such as Project and VM. Dashboards page can still be seen only by admins and they can also see monitoring section so there wont be any difference

@rawagner - Makes sense. Thanks for clarifying!

**Pull request merged**
