### PR TITLE
Bug 2029369: Mock github API requests when importing projects in cypress tests

### PR DESCRIPTION
**Pull request by jrichter1**
There have been intermittent cypress test failures due to github rate limits when importing projects for workloads. This is a workaround for the issue by mocking the github API requests for the example repositories, with the possibility to add more.

### CODE REVIEW

**Review by dtaylor113 — APPROVED** [review]
/lgtm

**Comment by dtaylor113** [comment]
@jrichter1 , nice use of `cy.intercept`'s :-)  lgtm.  Let me know if you want me to merge this or prefer to wait for other to review this PR.  -thanks

**Comment by jrichter1** [comment]
@dtaylor113 if you could merge this, that would be really nice

**Comment by dtaylor113** [comment]
Hmm..sorry @jrichter1 , the merge button is disabled for me.  I was able to merge the other pr though :confused:

**Pull request merged**
