### PR TITLE
adds topology actions to upload a jar file

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes**: 
https://issues.redhat.com/browse/ODC-5465

**Analysis / Root cause**: 

**Solution Description**: 
context menu: add to project/application/connector action for `upload JAR file` is added to the topology

**Screen shots / Gifs for design review**: 

Add to connector:

image

Add to project:

image

Add to application group

image

**Unit test coverage report**: 

**Test setup:**
- Updated existing specs 
- Added

image

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

**Note:** Position of the sub-context menu is off being handled as part of https://github.com/openshift/console/pull/8417

### CODE REVIEW

**Comment by jerolimov** [comment]
@invincibleJai for me the action menu with the arrow-drag-function works, but when I right click outside of my app and select the option nothing happen:

Peek 2021-03-24 23-43

**Comment by invincibleJai** [comment]
> @invincibleJai for me the action menu with the arrow-drag-function works, but when I right click outside of my app and select the option nothing happen:
> 
> Peek 2021-03-24 23-43

@jerolimov yes there is an issue for it even in master, as I mentioned in the description 

> Note: Position of the sub-context menu is off being handled as part of #8417

**Comment by jeff-phillips-18** [comment]
https://github.com/openshift/console/pull/8417 addresses the context menu positioning. However, there is a problem with the side bar when upgrading PF react so its is on hold for a fix https://github.com/patternfly/patternfly-react/pull/5572

**Comment by debsmita1** [comment]
tried out the changes along with https://github.com/openshift/console/pull/8470 , it works fine

**Comment by lwrigh** [comment]
This looks good to me, when the user clicks on the Upload JAR file action an empty upload form opens right?

**Comment by invincibleJai** [comment]
> This looks good to me, when the user clicks on the Upload JAR file action an empty upload form opens right?

Yes it will open empty upload form

**Review by lwrigh — APPROVED** [review]
It looks good to me!

**Review by jerolimov — APPROVED** [review]
Tested this again with node_modules installed from the master, works fine now after https://github.com/patternfly/patternfly-react/pull/5572 and https://github.com/openshift/console/pull/8470/files got merged.

/lgtm

**Pull request merged**
