### PR TITLE
OCPBUGS-7399: fix pipeline selection in Edit flow in devconsole

### PR DESCRIPTION
**Pull request by vikram-raj**
Fixes: https://issues.redhat.com/browse/OCPBUGS-7399

GIF:
Peek 2023-02-14 20-18

### CODE REVIEW

**Review by Lucifergene — COMMENTED** [review]
Looks good to me :+1:

**Comment by lokanandaprabhu** [comment]
At the time of creating, in Add pipeline, I have selected s2i-go-deployment in the dropdown,
.
.
.

Screenshot 2023-02-16 at 1 09 57 PM

.
.
.

When I went to edit, the value in dropdown is golang-ex-1 which is same as name. Is this behaviour correct? 
.
.
.


Screenshot 2023-02-16 at 1 13 09 PM

**Comment by vikram-raj** [comment]
> At the time of creating, in Add pipeline, I have selected s2i-go-deployment in the dropdown, . . .
> 
> Screenshot 2023-02-16 at 1 09 57 PM
> 
> . . .
> 
> When I went to edit, the value in dropdown is golang-ex-1 which is same as name. Is this behaviour correct? . . .
> 
> Screenshot 2023-02-16 at 1 13 09 PM

@lokanandaprabhu It is expected. As while creating the Pipeline name is s2i-<runtime>-<resource type> in Openshift ns. and after creating the same Pipeline we copy it to active ns and update the name to the Pipeline because of that in the edit flow Pipeline name is same as the application name.

**Pull request merged**
