### PR TITLE
OCPBUGS-7806: Add NFS-export details for PersistentVolume details

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Shows the NFS-export details if exists. 
The details fetched from spec.csi.volumeAttributes.share of a pv

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
Shows no NFS-export details when not found
Screenshot from 2023-02-16 16-50-53


Shows NFS-export when a persistentvolume has the details
Screenshot from 2023-02-16 16-39-59

**Comment by TimothyAsirJeyasing** [comment]
@SanjalKatiyar Please review

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by SanjalKatiyar** [comment]
/retitle OCPBUGS-7806: Add NFS-export details for PersistentVolume details

**Pull request merged**
