### PR TITLE
CONSOLE-3081: Adjust darkest purple resource color to one PF shade lighter for better contrast on dark theme.

### PR DESCRIPTION
**Pull request by sg00dwin**
**Before and After**

Screen Shot 2022-06-09 at 4 30 26 PM
Screen Shot 2022-06-09 at 4 15 13 PM

---

Screen Shot 2022-06-09 at 4 28 24 PM
Screen Shot 2022-06-09 at 4 13 54 PM

### CODE REVIEW

**Comment by sg00dwin** [comment]
/label docs-approved
/label px-approved

We have docs- and px-approval for the epic.

**Comment by sg00dwin** [comment]
QE Approver:
/assign @yanpzhan

**Review by jcaianirh — APPROVED** [review]
/lgtm

pulled down code, looks good to me
Screen Shot 2022-06-13 at 6 13 51 AM

**Pull request merged**
