### PR TITLE
ODC-7682: Update icons

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7682

**Analysis / Root cause**: 

Icons weren't updated 

**Solution Description**: 

Icons were taken from the [official Red Hat source](https://redhat.brand-portal.adobe.com/mediaportal.html/content/dam/mac/redhat/brand/icons) when possible, otherwise they were downloaded/modified from brand guidelines when possible, otherwise they were taken from Wikimedia Commons

**Screen shots / Gifs for design review**: 

See [diff](https://github.com/openshift/console/pull/14146/files) for icons changed

**Unit test coverage report**: 

unchanged

**Test setup:**

need to double check if icons conform to respective brand guidelines and check if I missed any

**Browser conformance**: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari

### CODE REVIEW

**Comment by spadgett** [comment]
Have we tested to make sure the icons that aren't square render OK?

@rhamilto FYI

**Comment by logonoff** [comment]
image

Icons with a dark background look weird, I've opened a ticket for it: see [OCPBUGS-38480](https://issues.redhat.com/projects/OCPBUGS/issues/OCPBUGS-38480)

MongoDB looks weird as well which I will fix

**Comment by vikram-raj** [comment]
3Scale
image

AMQ
image

EAP
image

Fedora
image

Kubevirt
image

Jboss
image

Laravel
image

MariaDB
image

MediaWiki
image

MongoDB
image

Scala
image

StackOverflow
image

Suse
image

Ubuntu
image

Window
image

Openshift
image

**Comment by Misjohns** [comment]
The Suse icon looks small and Windows looks large compared to the rest. Please adjust these so the padding is consistent with the other icons.

**Comment by logonoff** [comment]
> The Suse icon looks small and Windows looks large compared to the rest. Please adjust these so the padding is consistent with the other icons.

Thanks for the feedback! I've updated the SUSE and Windows logos; I also found a bunch of icons that were unused in the icons folder and added them into the list of deployment icons:

image

**Comment by vikram-raj** [comment]
Suse icon looks fine now
image

Intellij
image

**Review by vikram-raj — APPROVED** [review]
Verified all the icons.

/lgtm

**Review by vikram-raj — COMMENTED** [review]
/label tide/merge-method-squash

/lgtm

**Pull request merged**
