### PR TITLE
ODC-7391: Add a new allowInsecure option to the internet proxy API

### PR DESCRIPTION
**Pull request by jerolimov**
**Fixes:**
Epic: [ODC-7347 Support to load PipelineRuns and Logs also from Tekton Results](https://issues.redhat.com/browse/ODC-7347)
Story: [ODC-7391 Workaround to bypass CORS and TLS issues to fetch data from the Tekton Results API](https://issues.redhat.com/browse/ODC-7391)

Adds a new option to allow insecure (disables the TLS cert validation) when fetching data with the "internet proxy".

This must not be used in the final implementation! It's a workaround to start the UI developing.

### CODE REVIEW

**Comment by jerolimov** [comment]
No UI change, and mostly a workaround to continue with the UI work.

/label docs-approved
/label px-approved
/label qe-approved

**Review by vikram-raj — COMMENTED** [review]
/lgtm

**Pull request merged**
