### PR TITLE
CONSOLE-3681: Convert storage-class-form.tsx from class component to …

### PR DESCRIPTION
**Pull request by tvu20**
…functional component

storage-class-form.tsx converted from a class component to a functional component in order to use react-router v6 hooks.

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
Love it 👍 
/lgtm
/approve

/assign @yanpzhan for QE approval.
/label docs-approved
/label px-approved

**Comment by yanpzhan** [comment]
@XiyunZhao pls help to test the pr, thanks!

**Comment by XiyunZhao** [comment]
Do manual and regression testing for the storage and StorageClasses related page, no issue was found
/label qe-approved

**Pull request merged**
