### PR TITLE
Add namespace choice to obc creation function

### PR DESCRIPTION
**Pull request by ebondare**

### CODE REVIEW

**Comment by afreen23** [comment]
@ebondare can you specify in commit the way you made it stable.
It will help track. We can have many patches go by `Make obc tests more stable` , which will make us lose track of things.

Thanks for PR :)

**Comment by afreen23** [comment]
/retitle Add namespace choice to obc creation function
/lgtm

**Comment by spadgett** [comment]
/hold
Queue is broken. Hold for #6225

**Pull request merged**
