### PR TITLE
[release-4.9] Bug 2027804: use namespace instead of useActivePerspective hooks to get the variables in Observe dashboard

### PR DESCRIPTION
**Pull request by vikram-raj**
Cherry-pick: https://github.com/openshift/console/pull/10526

### CODE REVIEW

**Comment by jerolimov** [comment]
/assign @kyoto @karthikjeeyar 
/cc @kyoto @karthikjeeyar 

Hey Andrew and Karthik, can you review/approve this backport? I asked because you also reviewed #10526

**Comment by jrichter1** [comment]
Tested and verified with cluster-bot
/label cherry-pick-approved

**Pull request merged**
