### PR TITLE
Bug 2097026: Administration - Cluster Settings - Cluster Operators : …

### PR DESCRIPTION
**Pull request by tvu20**
…Filter menu values are in English

Makes sure filter menu dropdown values in Cluster Settings are in the selected language.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2097026

### CODE REVIEW

**Review by sg00dwin — APPROVED** [review]
/lgtm

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
