### PR TITLE
Add CJK translation of Inspect link in monitoring

### PR DESCRIPTION
**Pull request by utccp**
The modified solution result is shown in the figure below:
image

### CODE REVIEW

**Comment by utccp** [comment]
@vikram-raj @karthikjeeyar Please check this submission, thank you.

**Comment by utccp** [comment]
This is not a proper term. I think the translation engineer missed it.

**Comment by rebeccaalpert** [comment]
Hey @utccp - We get files translated in-house by @rh-tchuang's team on a rolling basis. It looks like we have the "Inspect" text captured correctly in the English files, so we're on track to get that translated correctly during our next file exchange with the translators. I want to make it clear here that any updates we merge in manually like this without Terry's team's input are essentially temporary fixes because they just get overwritten during the next file exchange.

@rh-tchuang, would your team be able to take a look at these to make sure they're ok? Or would you rather wait and handle these as part of the next file drop?

It looks like a test is also failing here @utccp; that would also need to be updated.

**Comment by utccp** [comment]
I seem to have mistakenly combined other problems into my main branch. Now I'll mention it again

**Comment by utccp** [comment]
I have submitted in another pull requests,you can now close this submission.

**Pull request closed without merging**
