### PR TITLE
ODC-7655: Migrate TimespanDropdown to PF5

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7655

**Solution Description**: 

Migrate file to PF5

**Screen shots / Gifs for design review**: 

Demo:

https://github.com/user-attachments/assets/dbd646f8-d6bc-4794-9c57-402927bb26c4

**Unit test coverage report**: 

unchanged

**Test setup:**

to see the observe dashboard in local development, use the mock data linked here https://github.com/openshift/monitoring-plugin/compare/main...zhuje:monitoring-plugin:mock_monitoring_dashboard_config

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

This pr is 2/4 of [ODC-7655](https://issues.redhat.com//browse/ODC-7655) story as each file is being split into a separate PR.

### CODE REVIEW

**Comment by logonoff** [comment]
Tech debt that is not customer facing, so manually adding labels
/label px-approved
/label docs-approved

**Review by vikram-raj — APPROVED** [review]
/lgtm

**Comment by kyoto** [comment]
FYI @jgbernalp @zhuje @PeterYurkovich

I assume this change should be copied to the monitoring plugin

**Pull request merged**
