### PR TITLE
Bug 1964902 improve display of network policies

### PR DESCRIPTION
**Pull request by jotak**
- Show ipblock exceptions
- Show all ipblocks in the same row within a rule
- Specific text when podSelector is missing
- JS->TS: create NetworkPolicyKind, more typing in network-policy.tsx

### CODE REVIEW

**Comment by jotak** [comment]
cc @yapei 

- Multiple IPBlocks in a row:

Capture d’écran de 2021-06-07 13-51-44

- IPBlock exceptions in tooltip:

Capture d’écran de 2021-06-07 13-51-48

**Comment by yapei** [comment]
tested the changes in cluster-bot cluster, now everything looks good

**Comment by jotak** [comment]
@jhadvig @jeff-phillips-18 this was tested, now waiting for code review

**Review by jhadvig — APPROVED** [review]
nicely done 👍 
/approve
/lgtm

**Pull request merged**
