### PR TITLE
Bug 2069577: Update dynamic-demo-plugin readme

### PR DESCRIPTION
**Pull request by jhadvig**
I've missed this one in https://github.com/openshift/console/pull/11247 but luckily https://github.com/openshift/console/pull/11267 contains this change.

/assign @spadgett

### CODE REVIEW

**Comment by andrewballantyne** [comment]
@jhadvig I noticed another PR to come through my email... are you colliding with anything that @yapei is doing?

Her PR for 4.10 is here but it links back to other PRs done in `master`: https://github.com/openshift/console/pull/11267

**Review by spadgett — APPROVED** [review]
/lgtm

If we have backported the previous change, we should check that those are correct as well.

**Comment by jhadvig** [comment]
@andrewballantyne so @yapei backported https://github.com/openshift/console/pull/11247 which did contain this change. For that reason I've moved the 4.11 BZ back to ASSIGNED state, since the [4.10 backport](https://github.com/openshift/console/pull/11267), which contains this change, is still waiting to get merged.

**Pull request merged**
