### PR TITLE
CONSOLE-3998: Update 'Explore new admin features' section

### PR DESCRIPTION
**Pull request by rhamilto**
Updated so that the LightSpeed link is only displayed if the LightSpeed PackageManifest is present on the cluster.  Thanks for that suggestion, @jhadvig!

In order to fully test, apply https://github.com/openshift/lightspeed-operator/blob/main/hack/example_catalogsource.yaml to the cluster so LightSpeed operator is available.

https://github.com/openshift/console/assets/895728/643dce8a-00c1-4b4c-950d-a6f6af735ff8

### CODE REVIEW

**Comment by rhamilto** [comment]
UX Approver:
@yuvalgalanti
QE Approver:
/assign @yapei
Docs Approver:
/assign @opayne1
PX Approver:
/assign @RickJWagner
Code Approver:
/assign @sg00dwin

**Comment by yanpzhan** [comment]
Tested on cluster launched against the pr. The feature works as expected.
@rhamilto  I see there is WIP label for the pr. Not sure if the pr is completely ready and will have no new code. I would add qe-approved label if there won't be new update.

**Comment by rhamilto** [comment]
> Tested on cluster launched against the pr. The feature works as expected.
@rhamilto I see there is WIP label for the pr. Not sure if the pr is completely ready and will have no new code. I would add qe-approved label if there won't be new update.

Thanks, @yanpzhan.  The WIP label is present since the URL for the LightSpeed operator needs to be updated.  There will be no functional changes though, so feel free to tag.

**Comment by yanpzhan** [comment]
Got it. Thanks Robb.
/label qe-approved

**Comment by rhamilto** [comment]
@gauravsingh85, any insight as to when the LightSpeed operator is likely to get added to the Red Hat operators CatalogSource?

**Review by jhadvig — APPROVED** [review]
/lgtm
 🙌

**Pull request merged**
