### PR TITLE
CONSOLE-2964: Update ts-node to v10.2.1

### PR DESCRIPTION
**Pull request by spadgett**

### CODE REVIEW

**Comment by spadgett** [comment]
/assign @kdoberst 
@jamestalton FYI

/label px-approved
/label docs-approved

There is only a dev dependency update with no user-visible changes. @opayne1 @RickJWagner FYI

@yapei Did you want to test? I don't believe this has any impact to the built console image.

**Comment by spadgett** [comment]
Seems to have caused protractor build errors. I'll investigate.

```
[20:06:29] E/configParser - Error code: 105
[20:06:29] E/configParser - Error message: failed loading configuration file integration-tests/protractor.conf.ts
[20:06:29] E/configParser - TSError: ⨯ Unable to compile TypeScript:
integration-tests/protractor.conf.ts(3,41): error TS7016: Could not find a declaration file for module 'protractor-jasmine2-screenshot-reporter'. '/go/src/github.com/openshift/console/frontend/node_modules/protractor-jasmine2-screenshot-reporter/index.js' implicitly has an 'any' type.
  Try `npm install @types/protractor-jasmine2-screenshot-reporter` if it exists or add a new declaration (.d.ts) file containing `declare module 'protractor-jasmine2-screenshot-reporter';`
integration-tests/protractor.conf.ts(5,47): error TS7016: Could not find a declaration file for module 'jasmine-reporters'. '/go/src/github.com/openshift/console/frontend/node_modules/jasmine-reporters/index.js' implicitly has an 'any' type.
  Try `npm install @types/jasmine-reporters` if it exists or add a new declaration (.d.ts) file containing `declare module 'jasmine-reporters';`
integration-tests/protractor.conf.ts(6,34): error TS7016: Could not find a declaration file for module 'jasmine-console-reporter'. '/go/src/github.com/openshift/console/frontend/node_modules/jasmine-console-reporter/index.js' implicitly has an 'any' type.
  Try `npm install @types/jasmine-console-reporter` if it exists or add a new declaration (.d.ts) file containing `declare module 'jasmine-console-reporter';`
integration-tests/protractor.conf.ts(7,27): error TS7016: Could not find a declaration file for module 'protractor-fail-fast'. '/go/src/github.com/openshift/console/frontend/node_modules/protractor-fail-fast/dist/protractor-fail-fast.js' implicitly has an 'any' type.
  Try `npm install @types/protractor-fail-fast` if it exists or add a new declaration (.d.ts) file containing `declare module 'protractor-fail-fast';`
integration-tests/protractor.conf.ts(43,7): error TS7034: Variable 'browserLogs' implicitly has type 'any[]' in some locations where its type cannot be determined.
integration-tests/protractor.conf.ts(110,12): error TS7011: Function expression, which lacks return-type annotation, implicitly has an 'any' return type.
integration-tests/protractor.conf.ts(169,5): error TS7005: Variable 'browserLogs' implicitly has an 'any[]' type.
integration-tests/protractor.conf.ts(187,17): error TS7006: Parameter 'exitCode' implicitly has an 'any' type.
integration-tests/protractor.conf.ts(221,17): error TS2339: Property 'windowError' does not exist on type 'Window & typeof globalThis'.
integration-tests/protractor.conf.ts(232,30): error TS7006: Parameter 'elementArrayFinder' implicitly has an 'any' type.
integration-tests/protractor.conf.ts(232,50): error TS7006: Parameter 'expectedCount' implicitly has an 'any' type.
integration-tests/protractor.conf.ts(239,29): error TS7006: Parameter 'elementArrayFinder' implicitly has an 'any' type.
integration-tests/protractor.conf.ts(246,24): error TS7006: Parameter 'obj' implicitly has an 'any' type.
```

**Comment by spadgett** [comment]
I believe what's happening is that ts-node isn't finding out tsconfig.json file and defaulting to `strict: true`. I don't see these errors running locally however.

**Comment by spadgett** [comment]
It seems to be picking up the `tsconfig.json` from `node_modules/protractor`, which has `noImplicitAny: "true"`.

```
$ ts-node -O '{"module":"commonjs"}' --show-config ./node_modules/.bin/protractor integration-tests/protractor.conf.ts --suite all
{
  "ts-node": {
    "cwd": "/Users/sam/work/console/frontend",
    "projectSearchDir": "/Users/sam/work/console/frontend/node_modules/protractor/bin",
    "require": [],
    "project": "/Users/sam/work/console/frontend/node_modules/protractor/tsconfig.json"
  },
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "declaration": false,
    "removeComments": false,
    "noImplicitAny": true,
    "outDir": "./.ts-node",
    "inlineSourceMap": false,
    "inlineSources": true,
    "noEmit": false
  },
  "exclude": [
    "built",
    "node_modules",
    "testapp",
    "website",
    "scripts",
    "exampleTypescript",
    "spec/**/*"
  ]
}
```

**Comment by kdoberst** [comment]
@spadgett There is now a Jira card for this - https://issues.redhat.com/browse/CONSOLE-2964

**Comment by spadgett** [comment]
/assign @yapei 
for QE review

@yapei I don't think this affects the built console image, but assigning you in case you want to test.

**Comment by spadgett** [comment]
@kdoberst Rebased

**Comment by spadgett** [comment]
Adding qe-approved since this is only a dev dependency.

/label qe-approved

**Pull request merged**
