### PR TITLE
Bump webpack-bundle-analyzer

### PR DESCRIPTION
**Pull request by spadgett**
The latest version lets us see the final, parsed and gzipped sizes of each bundle.

/assign @alecmerdler 

screen shot 2018-12-18 at 12 06 37 pm

### CODE REVIEW

**Comment by spadgett** [comment]
Rebased

**Comment by spadgett** [comment]
Fixed the yarn.lock error

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by alecmerdler** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
