### PR TITLE
CONSOLE-3764: Update husky to v8.0.3

### PR DESCRIPTION
**Pull request by TheRealJon**

### CODE REVIEW

**Comment by TheRealJon** [comment]
QE Approver
/assign @yanpzhan

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

**Review by jcaianirh — APPROVED** [review]
/lgtm

**Comment by TheRealJon** [comment]
Hi @XiyunZhao, you should only need to run `yarn` in order for it to work. This PR adds a post-install step which should set up husky on your system.

**Review by jhadvig — APPROVED** [review]

**Comment by XiyunZhao** [comment]
/label qe-approved
test details have been updated in Ticket

**Pull request merged**
