### PR TITLE
ODC-7669: Migrate PipelineMetricsTimeRangeDropdown to PF5

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7669

**Screen shots / Gifs for design review**: 

demo:

https://github.com/user-attachments/assets/46bc7231-6d4c-4d0c-92cf-78732610b02c

**Unit test coverage report**: 

n/a

**Test setup:**

install pipelines plugin and set up a pipeline

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

This pr is 1/2 of [ODC-7669](https://issues.redhat.com//browse/ODC-7669) story as each file is being split into a separate PR.

### CODE REVIEW

**Comment by logonoff** [comment]
Tech debt that is not customer facing, so manually adding labels
/label px-approved
/label docs-approved

**Review by vikram-raj — APPROVED** [review]
/lgtm

**Comment by The-Anton** [comment]
Tested using cluster bot, working as expected.
/label qe-approved

Screenshot 2024-09-12 at 3 01 29 PM

**Pull request merged**
