### PR TITLE
Bug 1962569: Show NetworkPolicy egress rules

### PR DESCRIPTION
**Pull request by jotak**
A text is displayed to inform about differences between openshift-sdn and
ovn-k wrt. egress.

Also fix wrong text "allow all" => "deny all", cf https://bugzilla.redhat.com/show_bug.cgi?id=1964319

### CODE REVIEW

**Comment by jotak** [comment]
Capture d’écran de 2021-05-25 11-23-48

**Review by spadgett — APPROVED** [review]
/lgtm

Thank you!

**Comment by jotak** [comment]
> Looks like you need to run `yarn i18n`

I'll remember it eventually, I promise!
done :)

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
