### PR TITLE
e2e automation add wait for RDP data

### PR DESCRIPTION
**Pull request by yaacov**
e2e automation add wait for RDP data

### CODE REVIEW

**Comment by yaacov** [comment]
@gouyang please review

**Comment by yaacov** [comment]
passed on jenkins env:
https://cnv-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/test-kubevirt-console-4.7-cnv-2.6-gouyang/24/console

**Comment by gouyang** [comment]
Verified in https://cnv-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/test-kubevirt-console-4.7-cnv-2.6-gouyang/24/console

**Pull request merged**
