### PR TITLE
HELM-522:bump helm version to 3.13.2 for OCP 4.15

### PR DESCRIPTION
**Pull request by Kartikey-star**
This PR is meant to Bump Helm version to 3.13.2, latest Helm version released upstream for OCP 4.15

### CODE REVIEW

**Comment by Kartikey-star** [comment]
Requesting review from 
@dperaza4dustbit

**Review by dperaza4dustbit — APPROVED** [review]
/lgtm

**Comment by Kartikey-star** [comment]
/retitle [release-4.15] OCPBUGS-26517:bump helm version to 3.13.2 for OCP 4.15

**Pull request merged**
