### PR TITLE
ODC-7277: added v1 support for Pipeline

### PR DESCRIPTION
**Pull request by vikram-raj**
Story: https://issues.redhat.com/browse/ODC-7277

Descriptions: Add support to the Pipeline v1 API as the Pipeline API version is upgrading to v1 with the Red Hat Pipeline operator 1.11.0 release.

GIF: No UI changes all the Pipeline features should work as before.

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
while editing `v1beta1`pipeline, on submit it auto upgrades to `v1` api and the request fails.

Screenshot 2023-05-05 at 3 04 14 PM

**Comment by karthikjeeyar** [comment]
Resource tab in pipelinerun and resources section in pipeline builder form is not required anymore with v1 APIs. see this thread for more details - https://redhat-internal.slack.com/archives/CHG0KRB7G/p1683280697729089

**Comment by vikram-raj** [comment]
@karthikjeeyar updated the PR PTAL again. Thanks

**Comment by jerolimov** [comment]
Hi @vikram-raj, some small finding we should please check/improve/fix in a follow up PR:

1. Search: Select Pipeline/PipelineRun resource doesn't render the P/PR rows with their status.
2. Pipeline Builder: When switching to YAML, the samples and snippet sidebar aren't shown.
3. Pipeline Builder: I think we can drop the Workspace :information_source: that explains "Resources aren't in beta, so it is recommended to use workspaces instead."
4. When I import an app via "Import from Git", select "Add Pipeline" and then Rerun the automatically started PipelineRun, the new PipelineRun doesn't run successfully while the first one was fine. (Tested with OpenShift 4.13, OpenShift Pipelines operator 1.10.3) It looks like the annotation `tekton.dev/v1beta1TaskRuns` is copied and includes an old status. So we need to remove it when rerun a PR.

**Review by jerolimov — CHANGES_REQUESTED** [review]
Hi @vikram-raj, existing change looks well, but I found some issues anyway:

Tested with OpenShift 4.13, OpenShift Pipelines operator 1.10.3 and a local bridge with this PR:

1. Search: Select Pipeline/PipelineRun resource doesn't render the P/PR rows with their status.
2. Pipeline Builder: When switching to YAML, the samples and snippet sidebar aren't shown.
3. Pipeline Builder: I think we can drop the Workspace :information_source: that explains "Resources aren't in beta, so it is recommended to use workspaces instead."
4. When I import an app via "Import from Git", select "Add Pipeline" and then Rerun the automatically started PipelineRun, the new PipelineRun doesn't run successfully while the first one was fine. It looks like the annotation `tekton.dev/v1beta1TaskRuns` is copied and includes an old status. So we need to remove it when rerun a PR.

Tested this also on a cluster bot (`launch openshift/console#12729,4.14 gcp`) with PO 1.11 preview (1.11.0/507983-4.14):

1-3. Exists here as well.
4. Rerun works fine because the annotation mentioned above isn't used.

**Comment by jerolimov** [comment]
Tested this again (in progress...):

Local build (frontend) with 4.13 cluster and PO 1.10.3:

0. Import from Git and overall Pipeline pages works fine (creates Pipeline v1) :heavy_check_mark: 
1. Search shows the P/PR status again (shows Pipeline v1) :heavy_check_mark: 
2. Pipeline Builder: When switching to YAML, the samples and snippet sidebar are still not shown (create Pipeline v1). :x:
3. Pipeline Builder: Workspace :information_source: was removed :heavy_check_mark: 
4. Pipeline Rerun works fine, but the issue exists only on 4.13, so I will check that as well...

Cluster bot (`launch openshift/console#12729,4.14 aws`) with PO 1.11 preview (1.11.0/514451-4.14):

0. Import from Git and overall Pipeline pages works fine (creates Pipeline v1) :heavy_check_mark: 
1. Search shows the P/PR status again (shows Pipeline v1) :heavy_check_mark: 
2. Pipeline Builder: When switching to YAML, the samples and snippet sidebar are still not shown (create Pipeline v1). :x:
3. Pipeline Builder: Workspace :information_source: was removed :heavy_check_mark: 
4. Pipeline Rerun works fine, but the issue exists only on 4.13, so I will check that as well...

**Review by jerolimov — APPROVED** [review]
For mode details see comment above. Code looks good to me. For the missing YAML samples we can have follow-up bug+PR.

/lgtm

Propage labels from the epic:

/label docs-approved
/label px-approved
/label qe-approved

**Comment by jerolimov** [comment]
This backport is only to check this on 4.13 as well. I will close the backport soon again.

/cherry-pick release-4.13

**Comment by jerolimov** [comment]
Nevermind :smile:

**Pull request merged**
