### PR TITLE
[release-4.12] OCPBUGS-6758: Add RBAC check on Create a Project link in all-namespaces pages

### PR DESCRIPTION
**Pull request by vikram-raj**
Manual cherry-pick of https://github.com/openshift/console/pull/12279

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Tested this on a cluster bot and it works fine for me :+1: 

https://user-images.githubusercontent.com/139310/215353646-998cddf5-481b-44f4-9582-88fd96aecb96.mp4

/label backport-risk-assessed
/lgtm
/approve

**Comment by vikram-raj** [comment]
Created a manual cherry-pick PR https://github.com/openshift/console/pull/12514

**Pull request merged**
