### PR TITLE
OCPBUGS-36678: Add useQuickStartContext hook and expose it via dynamic plugin API

### PR DESCRIPTION
**Pull request by vojtechszocs**
## Problem

When working with [React contexts](https://react.dev/learn/passing-data-deeply-with-context) in Console frontend and its dynamic plugins, the context object passed to `React.useContext` hook _must be identical_ (i.e. `===` referentially equal) in order for the context value (hook result) to work properly across all plugins.

The exact use case here is importing `QuickStartContext` from `@patternfly/quickstarts` package.

From a plugin's perspective, unless `@patternfly/quickstarts` is marked as a shared module, that plugin will always use its own "copy" of `@patternfly/quickstarts` module(s) during its webpack build. This behavior is normal and expected; code not shared between the host application and its plugins can be loaded multiple times in possibly different versions.

The problem arises when some objects, like `QuickStartContext` mentioned above, must be referentially equal in order for plugin to properly interoperate with the host application.

:exclamation: If a plugin uses `@openshift-console/dynamic-plugin-sdk-webpack` version that includes #13992 and that plugin also uses PatternFly 5 or higher, **`@patternfly/quickstarts` will not be treated as a shared module.** This is because Console provided PatternFly shared modules are limited to PF 4 implementation for backwards compatibility reasons. Plugins using PatternFly 5 or higher will share PF modules between themselves via dynamic modules #13521.

## Solution

Add new React hook `useQuickStartContext` and expose it via `@openshift-console/dynamic-plugin-sdk` package.

```ts
// Plugin code, before:
import { QuickStartContext, QuickStartContextValues } from '@patternfly/quickstarts';
// ..
const { setActiveQuickStart } = useContext<QuickStartContextValues>(QuickStartContext);

// Plugin code, updated (*):
import { useQuickStartContext } from '@openshift-console/dynamic-plugin-sdk';
// ..
const { setActiveQuickStart } = useQuickStartContext();
```

(*) Requires that we publish a new version of `@openshift-console/dynamic-plugin-sdk` package with this change included.

## Notes

Console already has [`withQuickStartContext`](https://github.com/openshift/console/blob/master/frontend/packages/console-shared/src/hoc/withQuickStartContext.tsx) React utility that injects `quickStartContext` prop into the wrapped component. The value of `quickStartContext` prop is the context value retrieved via `React.useContext(QuickStartContext)` which means the prop name is misleading and we should improve it at some point.

@rhamilto @TheRealJon The above mentioned `withQuickStartContext` utility seems to be unused in Console frontend and not exposed via dynamic plugin API. I'd suggest removing it, do you have any thoughts or objections?

### CODE REVIEW

**Comment by rhamilto** [comment]
> @rhamilto @TheRealJon The above mentioned withQuickStartContext utility seems to be unused in Console frontend and not exposed via dynamic plugin API. I'd suggest removing it, do you have any thoughts or objections?

No objections if it unused, but we probably need to deprecate first.

**Review by rhamilto — APPROVED** [review]
/lgtm

**Comment by vojtechszocs** [comment]
Forgot to add API docs change, I'll update the PR.

**Pull request merged**
