### PR TITLE
CONSOLE-3997: Bump Yarn to v1 latest & add script to check PatternFly modules

### PR DESCRIPTION
**Pull request by vojtechszocs**
Follow-up to #13693

The aim of this PR is to avoid webpack build or performance issues due to multiple version resolutions of PatternFly packages.

- Upgrade Yarn from version `1.22.15` (2021-09-30) to `1.22.22` (2024-03-09)
- Check PatternFly package version resolutions as part of Console `postinstall` hook

#### Example - check resolutions on current Console code base

x1

#### Example - add `@patternfly/patternfly` :exclamation: and another dummy package to the list

x2

:exclamation: `PKGS_TO_CHECK` lists all PatternFly v5 packages, except for `@patternfly/patternfly`.

`@patternfly/patternfly` is excluded because a v4 package gets pulled in via `@patternfly-4/react-console`.
```sh
$ yarn why @patternfly/patternfly
..
=> Found "@patternfly/patternfly@5.2.1"
..
=> Found "@patternfly-4/react-console#@patternfly/patternfly@4.139.2"
..
```
Having multiple `@patternfly/patternfly` resolutions should be OK since this package only contains style related assets.

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by jhadvig** [comment]
QE Approver:
/assign @yapei 
Docs Approver:
/assign @opayne1
PX Approver:
/assign @RickJWagner

**Comment by XiyunZhao** [comment]
This PR has been tested and no issue was found
/qe-approved

**Comment by rhamilto** [comment]
@vojtechszocs, `./scripts/check-patternfly-modules.sh` fails on MacOS.  Probably ought to revert this in the interim as it blocks builds for Mac users (which is the majority of developers).

**Comment by vojtechszocs** [comment]
@rhamilto Good catch, that issue should be fixed by https://github.com/openshift/console/pull/13757

**Pull request merged**
