### PR TITLE
[release-4.10] Bug 2080389: Link to documentation from the overview page goes to a missing link

### PR DESCRIPTION
**Pull request by jhadvig**
manual backport of https://github.com/openshift/console/pull/11668/files

/assign @rhamilto

### CODE REVIEW

**Comment by yanpzhan** [comment]
@jhadvig  currently the variable "moreLinkURL" has been reset in https://github.com/openshift/console/pull/11768/files as below:

  const moreLinkURL = getDocumentationURL(
    documentationURLs.postInstallationMachineConfigurationTasks,
  );
Does this pr need update accordingly? or just leave it and test as it is and wait for another backport from pr11768?

**Comment by jhadvig** [comment]
@yanpzhan no, we wont be backporting https://github.com/openshift/console/pull/11768, since its introducing more changes then we need. Just this PR should go in.

**Comment by yanpzhan** [comment]
Thanks Jakub. Since the fix in the pr works as expected, the test passed.
/label qe-approved

**Pull request merged**
