### PR TITLE
Add plugin extension tests

### PR DESCRIPTION
**Pull request by vojtechszocs**
This PR aims to improve the overall quality of Console plugins by detecting common problems at build time, using Jest as the test platform.

fail-ModelFeatureFlag

In the above screenshot, `metal3-plugin` was modified to add `VirtualMachineModel` which is already contributed by `kubevirt-plugin`. The object diff reflects the expectation of `duplicateModels` being `[]`.

Tests under `packages/console-app/src/__tests__/extension-checks` work with the same set of active plugins as the webpack build. This ensures consistency between plugins getting tested vs. plugins getting bundled in the Console build output.

### Summary of changes

- Jest `testRegex` now matches files with `spec.(ts|tsx|js|jsx)` suffix, allowing developers to put test utility modules under `__tests__` directories
- added `@types/jest` dev dependency along with corresponding `tsconfig.json` update
- :star: code under `packages` now uses `lodash` instead of `lodash-es`
- :star: using [`webpack.NormalModuleReplacementPlugin`](https://webpack.js.org/plugins/normal-module-replacement-plugin/) to replace `lodash` with `lodash-es`
- plugin SDK codegen improved to support dynamic loading of plugins along with proper test coverage
- extension properties docs improved (`NavItem`, `YAMLTemplate`)

Consequently, production code that interprets Console extensions is simplified, i.e. no need to report on conflicting models or similar problems.

The demo plugin was updated so that extension tests pass when this plugin is enabled.

### :star: What's the deal with `lodash` vs. `lodash-es` anyway?

[`lodash-es`](https://www.npmjs.com/package/lodash-es) is a variation of the [`lodash`](https://github.com/lodash/lodash) library which uses ECMAScript module syntax.

Most tools, including `ts-node` and Jest, expect code under the `node_modules` directory to be transpiled and ready for use. Using libraries like `lodash-es` in environments like Node.js LTS results in syntax errors. _Console `integration-tests`, for example, use `lodash` exactly because of this (Protractor not configured to transpile `node_modules/lodash-es`, as opposed to Jest)._

To be able to dynamically load Console plugin entry points in context of Node.js env. (Jest), we have to use `lodash` instead of `lodash-es`. To retain current approach of using `lodash-es` in the webpack build, we use `NormalModuleReplacementPlugin`. This allows us to remove the `lodash` vs. `lodash-es` duality.

---

/cc @spadgett @alecmerdler @christianvogt @jelkosz

### CODE REVIEW

**Comment by vojtechszocs** [comment]
As a follow-up, I'd like to replace all `lodash-es` imports with `lodash`, but I'm curious what @spadgett thinks.

Alternatively, we can retain the existing `lodash` vs. `lodash-es` duality and require all Console plugins to have their entry points (i.e. `src/plugin.ts`) not reference `lodash-es` (directly or indirectly).

**Comment by spadgett** [comment]
> As a follow-up, I'd like to replace all `lodash-es` imports with `lodash`, but I'm curious what @spadgett thinks.

Just to be clear, we'd be able to use `NormalModuleReplacementPlugin` and retain tree shaking?

**Comment by spadgett** [comment]
Great to see these additional tests 👍 

/approve

**Comment by vojtechszocs** [comment]
> > As a follow-up, I'd like to replace all `lodash-es` imports with `lodash`, but I'm curious what @spadgett thinks.
> 
> Just to be clear, we'd be able to use `NormalModuleReplacementPlugin` and retain tree shaking?

Yes :smiley: AFAIK we still need to use `lodash-es` with webpack to do proper tree shaking, since `lodash-es` uses the native ES module syntax which webpack can easily look into & optimize.

The `NormalModuleReplacementPlugin` is used to replace modules which share the same exports. With this PR, during webpack build, `import * as _ from 'lodash';` becomes `import * as _ from 'lodash-es';`. If we had code like `import { uniq } from 'lodash';` it would become `import { uniq } from 'lodash-es';`.

Also, if you can think of any additional extension tests that we should perform, let me know and I'll add them. The more issues with plugins we can check during test/build time (instead of runtime), the better.

**Comment by vojtechszocs** [comment]
@spadgett To ensure this doesn't have unexpected impact on build outputs, I'll run `yarn analyze` (webpack-bundle-analyzer) before and after the PR and compare the bundle reports.

**Comment by vojtechszocs** [comment]
> @spadgett To ensure this doesn't have unexpected impact on build outputs, I'll run `yarn analyze` (webpack-bundle-analyzer) before and after the PR and compare the bundle reports.

Hmm, it seems like `public/dist/stats.json` gets malformed when generated via `yarn analyze` command:

```
Using ^[[1m1 worker^[[22m with ^[[1m2048MB^[[22m memory limit
{
// usual JSON output goes here
}
```

So I've compared `yarn build` outputs between
- current `master`
- this PR and its follow-up #1724 

Generated chunk sizes were equivalent. The `main` entry point has the same combined asset size of 2.14 MiB. This means the build outputs are still the same as before.

**Comment by vojtechszocs** [comment]
Please note, this PR isn't complete without its follow-up #1724 which removes `lodash-es` imports from the codebase.

**Comment by spadgett** [comment]
> Please note, this PR isn't complete without its follow-up #1724 which removes `lodash-es` imports from the codebase.

Can it merge without #1724? I see you updated eslintrc for lodash

**Comment by spadgett** [comment]
@christianvogt It might be better for you to review if you have bandwidth

**Comment by vojtechszocs** [comment]
> > Please note, this PR isn't complete without its follow-up #1724 which removes `lodash-es` imports from the codebase.
> 
> Can it merge without #1724? I see you updated eslintrc for lodash

Yes, this PR alone should pass tests and the webpack build output should be the same as before, effectively using `lodash-es` for the compilation.

#1724 completes this PR in terms of Lodash imports used within the code & ESLint configuration, but this has no impact on webpack output.

**Comment by vojtechszocs** [comment]
Rebased & included config tweaks from #1724 

`frontend/packages/.eslintrc.js`
```diff
 'no-restricted-imports': [
   'error',
   {
     name: 'lodash-es',
-    message: 'Use lodash instead.',
+    message: 'Use lodash instead. webpack is configured to use lodash-es automatically.',
   },
 ],
```

`frontend/webpack.config.ts`
```diff
-    new webpack.NormalModuleReplacementPlugin(/^lodash$/, 'lodash-es'),
+    // replace 'lodash' and 'lodash/*' imports with a lodash-es equivalent
+    new webpack.NormalModuleReplacementPlugin(/^lodash($|\/.*$)/, (resource) => {
+      resource.request = resource.request.replace(/^lodash/, 'lodash-es');
+    }),
```

**Comment by vojtechszocs** [comment]
Need to rebase on top of #1743, one more update incoming.

**Comment by vojtechszocs** [comment]
> Need to rebase on top of #1743, one more update incoming.

Done, please review the second commit titled `Add plugin integration tests`.

**Comment by vojtechszocs** [comment]
#1724 rebased & updated, please review if you have some spare time :smiley:

**Comment by mareklibra** [comment]
@vojtechszocs , With #1708 merged, recent master fails to open vms list from `kubevirt-plugin`.
The issue is within import of `kubevirt-web-ui-components`, investigating ...

**Comment by vojtechszocs** [comment]
> @vojtechszocs , With #1708 merged, recent master fails to open vms list from `kubevirt-plugin`.
> The issue is within import of `kubevirt-web-ui-components`, investigating ...
> 
> Edit: `import './style.scss';` seized to work as well.

I'm looking into this.

**Comment by vojtechszocs** [comment]
@mareklibra #1766 should fix the problem you've encountered.

**Pull request merged**
