### PR TITLE
Bug 1912434: update the guided tour modal heading

### PR DESCRIPTION
**Pull request by nemesis09**
**Fixes:**
https://issues.redhat.com/browse/ODC-5122

**Analysis / Root cause:**
Title for the initial modal screen of guided tour needs to be updated

**Solution Description:**
updated the title of the initial modal screen to "Welcome to the Developer Perspective"

**Screens:**
Screenshot from 2021-01-04 18-54-57

**Test Coverage:**
NA

**Browser Conformance:**
- [x] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by lwrigh** [comment]
LGTM!

**Review by sahil143 — APPROVED** [review]
/lgtm

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Comment by rohitkrai03** [comment]
Maybe not part of this PR but shouldn't guided tour text have translations? @sahil143 @nemesis09

**Comment by sahil143** [comment]
> Maybe not part of this PR but shouldn't guided tour text have translations? @sahil143 @nemesis09

Yes, Text should be translated everywhere in the guided tour. There are two files for guided tour text and it's translated in one but not in another. I will raise an issue to handle this.

**Comment by sahil143** [comment]
Raised this issue https://issues.redhat.com/browse/ODC-5318

**Pull request merged**
