### PR TITLE
Bug 1997187: Increase analyze script to 3.5 MiB

### PR DESCRIPTION
**Pull request by jcaianirh**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1997187 
cc: @kdoberst, @spadgett

### CODE REVIEW

**Comment by jcaianirh** [comment]
@spadgett is this an adequate vendor size?

**Review by spadgett — APPROVED** [review]
/lgtm

We should open a BZ so the bot lets the PR merge.

@jcaianirh Can you also open a JIRA issue to investigate improving the vendor bundle size? There are some packages showing up there that I wouldn't expect.

**Comment by jcaianirh** [comment]
@spadgett do we need the bz? I added this pr during 4.7 but maybe the release process changed since then: https://github.com/openshift/release/pull/14476

**Comment by jcaianirh** [comment]
> /lgtm
> 
> 
> @jcaianirh Can you also open a JIRA issue to investigate improving the vendor bundle size? There are some packages showing up there that I wouldn't expect.

@spadgett: https://issues.redhat.com/browse/CONSOLE-2953

**Pull request merged**
