### PR TITLE
OCPBUGS-1445: Notification count in the top nav bar does not take Recommendation notifications into account, only Critical Alerts and Other Alerts

### PR DESCRIPTION
**Pull request by cyril-ui-developer**

### CODE REVIEW

**Review by spadgett — COMMENTED** [review]
Hm, I thought this was intentional. We should get UX input here.

**Comment by cyril-ui-developer** [comment]
> Hm, I thought this was intentional. We should get UX input here.

@spadgett I have reached out to UX on this, and they think it is a bug. 

https://coreos.slack.com/archives/CC4C1BLP7/p1669136991770949

**Comment by jcaianirh** [comment]
@spadgett @yuvalgalanti @matthewcarleton @cyril-ui-developer 
Originally this behavior was intentional. I believe we were only bubbling up the higher severity notifications so admins would know that if there were notifications by the bell icon they were always important. Lower priority notifications may dilute the importance of the trigger to open the drawer for those users. 

Making sure the team took the original intent into consideration.

**Comment by yuvalgalanti** [comment]
let me check that and I will update as soon as possible

**Comment by matthewcarleton** [comment]
The concern here is when there are none critical notifications there's no way for a user to see that without checking the drawer.

**Comment by jcaianirh** [comment]
@matthewcarleton do you remember if the redesign of the notification icon was completed where we would show some sort of popup with more info than just a single number. ie counts with sevs. It looks like there is a blue/red notification badge (also with non-color indicator) that shows high / low sev counts or indications...

**Comment by matthewcarleton** [comment]
@jcaianirh there is this design which I believe shows what you're asking for.
http://openshift.github.io/openshift-origin-design/designs/administrator/4.4/notification-drawer/

**Comment by jcaianirh** [comment]
> @jcaianirh there is this design which I believe shows what you're asking for. http://openshift.github.io/openshift-origin-design/designs/administrator/4.4/notification-drawer/

yes thats it, and although i do see the design, when I look at the react components, I don't see the implementation of that design...is this something the pf-react team could prioritize? Actually there's a similar implementation in the react component library here: https://www.patternfly.org/v4/components/notification-badge

Which is the preferred version of the notification badge in your opinion @matthewcarleton ?

**Comment by matthewcarleton** [comment]
@jcaianirh that design is old, IMO we'd go with what the PatternFly team delivers rather than create a unique version of it.

**Comment by jcaianirh** [comment]
> @jcaianirh that design is old, IMO we'd go with what the PatternFly team delivers rather than create a unique version of it.

@matthewcarleton not suggesting we create anything unique on our end. Just wondering if we use the currently implemented pf-react component or have the pf team update the component to reflect the latest pf designs

**Comment by jcaianirh** [comment]
@matthewcarleton thanks for the update. How do you think we should proceed with the pf react component for the notifications in the drawer. There are 3 ways to shade the bell: none (read), blue (unread), red (attention), and then the numeric tally next to it.  In the console we don't have read/unread state. We use read/none with a critical notification count for notifications status in the icon. How do you propose we use the new icon/count combo. Would we just provide a total count rather than the critical count and then toggle the attention/read state when critical alerts are present?

**Comment by yuvalgalanti** [comment]
@Joseph Caiani ***@***.***> @Matt Carleton ***@***.***> I
think that the situation we have now when we are showing the count just for
critical is a bit misleading and I would go with showing the total count of
notifications that the user hasn't read yet. WDYT?

**Comment by cyril-ui-developer** [comment]
Closing this PR since the behavior was intentional to only show the total count for higher severity notifications.

**Pull request closed without merging**
