### PR TITLE
[release-4.13] OCPBUGS-16040: fix bug where binary secret values are corrupted on edit and add test coverage

### PR DESCRIPTION
**Pull request by jcaianirh**
Fixes: https://issues.redhat.com/browse/OCPBUGS-16040

Backport from 4.14: https://github.com/openshift/console/pull/12986

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]

**Comment by yanpzhan** [comment]
Tested on cluster launched against the pr. 
Prepared keystore secret according to steps in https://issues.redhat.com/browse/OCPBUGS-16040, created a pod with volume from the secret.  After change cert.pem value in secree, check md5sum of the keystore file from local host and running pod individually. Their md5sum output are the same.
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
