### PR TITLE
CONSOLE-4256: (deps) update PatternFly to 5.3.0

### PR DESCRIPTION
**Pull request by logonoff**
<h2 id="feature-fix">CONSOLE Features and Fixes:</h2>

https://issues.redhat.com/browse/CONSOLE-4256

<h2 id="solution-description">Solution description</h2> 

Updated the following dependencies, then used dedupe on the patternfly scope:

```diff
--- a/frontend/package.json
+++ b/frontend/package.json
@@ -147,19 +147,19 @@
     "@patternfly-4/react-styles": "npm:@patternfly/react-styles@4.92.8",
     "@patternfly-4/react-table": "npm:@patternfly/react-table@4.113.6",
     "@patternfly-4/react-tokens": "npm:@patternfly/react-tokens@4.94.7",
-    "@patternfly/patternfly": "5.2.1",
+    "@patternfly/patternfly": "5.3.0",
     "@patternfly/quickstarts": "5.3.0",
     "@patternfly/react-catalog-view-extension": "5.0.0",
     "@patternfly/react-charts": "7.2.2",
-    "@patternfly/react-component-groups": "^5.1.0",
-    "@patternfly/react-console": "5.0.0",
-    "@patternfly/react-core": "^5.2.2",
-    "@patternfly/react-icons": "^5.2.1",
-    "@patternfly/react-log-viewer": "5.1.0",
-    "@patternfly/react-styles": "^5.2.1",
-    "@patternfly/react-table": "^5.2.2",
-    "@patternfly/react-tokens": "^5.2.1",
-    "@patternfly/react-topology": "5.2.0",
+    "@patternfly/react-component-groups": "^5.2.0",
+    "@patternfly/react-console": "5.1.0",
+    "@patternfly/react-core": "^5.3.0",
+    "@patternfly/react-icons": "^5.3.0",
+    "@patternfly/react-log-viewer": "5.3.0",
+    "@patternfly/react-styles": "^5.3.0",
+    "@patternfly/react-table": "^5.3.0",
+    "@patternfly/react-tokens": "^5.3.0",
+    "@patternfly/react-topology": "5.3.0",
     "@patternfly/react-user-feedback": "5.0.0",
     "@patternfly/react-virtualized-extension": "5.1.0",
     "@prometheus-io/codemirror-promql": "^0.37.0",
```

<h2 id="reviewers-and-assignees">Reviewers and assignees:</h2>

<h2 id="test-cases">Test cases:</h2>

n/a

<h2 id="additional-info">Additional info:</h2>

Did not update @patternfly/react-charts due to build issue (a dependency in the package now uses optional chaining syntax which webpack 4 does not recognize)

<h2 id="screenshots">Screen shots / gifs / design review:</h2>

n/a

### CODE REVIEW

**Comment by logonoff** [comment]
Tech debt that is not customer facing, so manually adding labels
/label docs-approved
/label px-approved

**Review by vikram-raj — COMMENTED** [review]
/lgtm

**Comment by sanketpathak** [comment]
I've tested the following in the cluster as part of the pr with admin and non-admin wherever needed:

- Add flows including serverless flows 
- Pipeline and associated pages
- Helm charts and associated page
- Build config page
- Observe page
- Topology page- chart and list view
- Search page

I found two issues:

1. Observe doesn't have the dashboard tab in the developer perspective
Screenshot from 2024-10-09 15-12-55
This is present in the latest nightly as can be seen in the following screenshot:
Screenshot from 2024-10-09 16-05-41

2. In the Search page when you click on the Resource search bar, the cursor is removed so you can not search it directly you will have to click on it again.

https://github.com/user-attachments/assets/191d5256-5de4-4ff2-933c-74ee5af83e88

This is not seen in the available nightly build:

https://github.com/user-attachments/assets/40f84ffa-8ad4-4fcb-a138-721eb5948da4

**Comment by sanketpathak** [comment]
The Observe tab issue might be due to https://github.com/openshift/monitoring-plugin/pull/167 and https://github.com/openshift/console/pull/14192 so it is not related to this pr

**Comment by sanketpathak** [comment]
Verified the pr on the cluster with admin and non-admin users
The search bar works too, thanks @logonoff 

https://github.com/user-attachments/assets/5d3b18b1-246a-4a42-9e47-28dc87379e49

/label qe-approved

**Pull request merged**
