### PR TITLE
[release-4.15] OCPBUGS-30208: Fix asynccache bugs 

### PR DESCRIPTION
**Pull request by TheRealJon**
Manual cherry-pick of https://github.com/openshift/console/pull/13703 and https://github.com/openshift/console/pull/13647

### CODE REVIEW

**Comment by TheRealJon** [comment]
@stlaz @jhadvig PTAL

**Comment by stlaz** [comment]
Please don't use the merge commits but the actual commits of the PRs

**Comment by TheRealJon** [comment]
@stlaz I've updated. I cherry-picked the commits from #13703 and some from #13647. Some of the commits from #13647 were already covered by #13793

**Pull request merged**
