### PR TITLE
OCPBUGS-11620: Fix stop PLR option

### PR DESCRIPTION
**Pull request by vikram-raj**
Fixes: https://issues.redhat.com/browse/OCPBUGS-11620

https://github.com/openshift/console/assets/2561818/b2f6637b-fdc6-4908-b53c-656363bcbd8d

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Tested using cluster bot.

/lgtm

**Comment by vikram-raj** [comment]
Manual cherry-pick PR https://github.com/openshift/console/pull/13031

**Pull request merged**
