### PR TITLE
ODC-7409: Use @kubernetes-models/shipwright types in shipwright-plugin

### PR DESCRIPTION
**Pull request by jerolimov**
Use CRD-generated types instead of manual written types in the shipwright-plugin.

See:

* https://github.com/tommy351/kubernetes-models-ts
* https://github.com/tommy351/kubernetes-models-ts/tree/master/third-party/shipwright
* https://www.npmjs.com/package/@kubernetes-models/shipwright

`@kubernetes-models/shipwright` 0.2.0 types are generated based on the shipwright 0.12.0 CRDs:

* https://github.com/tommy351/kubernetes-models-ts/pull/140
* https://github.com/tommy351/kubernetes-models-ts/pull/145

/cc @Lucifergene @lokanandaprabhu @vikram-raj @spadgett @jhadvig

### CODE REVIEW

**Comment by jerolimov** [comment]
Just type updates. This doesn't touch the project or tests.

 /label px-approved
 /label px-approved

**Comment by jerolimov** [comment]
Just type updates. This doesn't touch the project or tests.

/label px-approved
/label qe-approved
/label docs-approved

**Review by vikram-raj — APPROVED** [review]
Thanks @jerolimov it is a nice improvement it would be nice to do the same for other packages/resources.  

/lgtm

**Pull request merged**
