### PR TITLE
Bug 1786419: StatefulSet should use openshift/hello-openshift image and not attach volume in example yaml

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @spadgett

### CODE REVIEW

**Comment by spadgett** [comment]
The goal is to give the user a template to create their own resources. It's not expected to be used exactly as-is. Removing the `volumeClaimTemplates` from the example makes it harder for users to take this as a starting point for their own stateful set since they'll probably need to set that.

If we can find a real example that works out-of-the-box, great. But I think it's  more important to provide realistic YAML.

**Comment by jhadvig** [comment]
I dont think we will be able to provide a working example in this case, since the YAML editor 
 is expecting a single document in the stream, not more. Due to that we can not create needed PersistantVolume and we can not guarantee its already created.
I recalled that in the past we had issues with some templates that could not be created, so we fix those, since template thats not working its kinda useless. On the other hand I also see the value to have a descriptive template where user could get a sense of its purpose.
Im fine with both approaches.

**Comment by spadgett** [comment]
> Due to that we can not create needed PersistantVolume and we can not guarantee its already created.

I'd think you can remove `storageClassName` and it would work with the default

**Comment by jhadvig** [comment]
> I'd think you can remove storageClassName and it would work with the default

Tried it but the `volumeClaimTemplates` status gets stuck `Pending` phase.

**Comment by jhadvig** [comment]
Closing since we agreed with @benjaminapetersen and @spadgett that its more important to provide a realistic example then a working one

**Pull request closed without merging**
