### PR TITLE
OCPBUGS-10562: disable operator-uninstall.ts as the uninstall test is…

### PR DESCRIPTION
**Pull request by rhamilto**
… still flaking

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by jerolimov** [comment]
4.13 is super flaky aka doesn't work at all....

/cherry-pick release-4.13

**Comment by jerolimov** [comment]
/title OCPBUGS-7632: disable operator-uninstall.ts as the uninstall test

**Comment by jerolimov** [comment]
/retitle OCPBUGS-7632: disable operator-uninstall.ts as the uninstall test is still flaking

**Pull request merged**
