### PR TITLE
[release-4.9] Bug 2066771: Enhance Insights widget empty states

### PR DESCRIPTION
**Pull request by gkarat**
This is a manual cherry-pick of #10826.

Description:

Make sure the Insights Advisor widget in the main dashboard requests for the Insights Operator status Prometheus metric to decide whether the Insights Operator is disabled. As a side-work, the patch improves empty states handling (disabled, waiting for results, error).

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2066771.

/assign @spadgett 
/cc: @tremes

### CODE REVIEW

**Comment by gkarat** [comment]
@spadgett, hello Sam, here is a patch backporting (4.9.z) one of the features introduced 1-2 months ago (Insights Advisor widget on the main console dashboard). Could you please take a look? 👋🏼

**Comment by gkarat** [comment]
@spadgett, ping 👀

**Review by spadgett — APPROVED** [review]
/lgtm
/label backport-risk-assessed

**Pull request merged**
