### PR TITLE
OCPBUGS-43360: Start last run do not work in buildConfig details page

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-43360

**Analysis / Root cause**: 
The check was present to see `buildConfig.latestBuild` is present or not, if not this option should be hidden but by mistake double negation was added

**Solution Description**: 
Replaced double negation with single so that if `buildConfig.latestBuild` is not present then Start last run option will be disabled
  
**Screen shots / Gifs for design review**: 

----BEFORE---

https://github.com/user-attachments/assets/d5ac2a86-1d7a-4407-89e0-70feee9c966b

---AFTER----

Screenshot 2024-10-17 at 12 35 00 PM

**Unit test coverage report**: 
NA

**Test setup:**

    1. Create workloads with with builds 
    2. Goto the builds page from navigation 
    3. Select the build config 
    4. Select the` Start last run` option from the Action menu
    

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by logonoff — APPROVED** [review]
I can replicate the before/after locally

/lgtm

**Review by vikram-raj — COMMENTED** [review]
Builds are present for BuildConfig but still Start last run option is not present.

image

**Comment by lokanandaprabhu** [comment]
Updated the PR and handled start last run in both BC list and details page.


https://github.com/user-attachments/assets/f92437ae-c9be-4334-aec4-63cfa646096a

**Review by Lucifergene — APPROVED** [review]
Verified the fix works as expected

https://github.com/user-attachments/assets/a24c8d7a-8e33-4458-8262-8966cb202a6d

/lgtm

**Review by vikram-raj — COMMENTED** [review]
/approve

**Pull request merged**
