### PR TITLE
CONSOLE-3084: frontend/packages/console-shared/src/hooks/useCanClusterUpgrade: Not ROSA

### PR DESCRIPTION
**Pull request by wking**
ROSA cluster updates are [via OCM][1]:

> There are three methods to upgrade Red Hat OpenShift Service on AWS (ROSA) clusters:
>
> * Individual upgrades through the ROSA CLI (`rosa`)
> * Individual upgrades through the OpenShift Cluster Manager Hybrid Cloud Console console
> * Recurring upgrades through the OpenShift Cluster Manager Hybrid Cloud Console console

This is similar to [OpenShift Dedicated (OSD)][2], although there is no OSD command-line client analogous to `rosa`.  This catches this one function up with f783d87981 (#12889), CC @rhamilto, although I have not audited to see if there are other branding consumers that might want similar updates.

[1]: https://docs.openshift.com/rosa/upgrading/rosa-upgrading.html#rosa-sts-upgrading-a-cluster
[2]: https://docs.openshift.com/dedicated/upgrading/osd-upgrades.html

### CODE REVIEW

**Comment by rhamilto** [comment]
Thanks, @wking.  Note the `rosa` branding option is new-ish. Will want to work with the packaging team to make sure they are using it, otherwise this fix won't work.

**Comment by wking** [comment]
[Neither][1] [failure][2] seems relevant, and [`pull-ci-openshift-console-master-e2e-gcp-console
` seems pretty dead][3], but:

/retest-required

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/13184/pull-ci-openshift-console-master-e2e-gcp-console/1704937757698166784
[2]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/13184/pull-ci-openshift-console-master-frontend/1704937757731721216
[3]: https://prow.ci.openshift.org/job-history/gs/origin-ci-test/pr-logs/directory/pull-ci-openshift-console-master-e2e-gcp-console

**Review by jhadvig — COMMENTED** [review]
@wking you need to run `yarn prettier-all` to properly format the changes

**Comment by wking** [comment]
I don't have `yarn` installed  locally, and [CI][1]:

```
/go/src/github.com/openshift/console/frontend/packages/console-shared/src/hooks/useCanClusterUpgrade.ts
  16:33  error  Insert `⏎···`  prettier/prettier
  17:28  error  Insert `⏎···`  prettier/prettier
```

suggests line wrapping, but doesn't print a convenient diff for me to apply as a patch.  But I've taken a guess and pushed 9d11ec65 -> b7261e96.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/13184/pull-ci-openshift-console-master-frontend/1705011285176881152#1:build-log.txt%3A6232-6234

**Review by rhamilto — APPROVED** [review]
/lgtm

**Comment by rhamilto** [comment]
QE Approver: 
/assign @yanpzhan
PX Approver:
/assign @RickJWagner
Docs Approver:
/assign @opayne1

**Pull request merged**
