### PR TITLE
Kubevirt VMTemplate create YAML

### PR DESCRIPTION
**Pull request by yaacov**
Add route and page for creating vm templates from YAML.

OKD(3)

OKD(4)

### CODE REVIEW

**Comment by yaacov** [comment]
@mareklibra @vojtechszocs @suomiy @rawagner please review.

**Comment by suomiy** [comment]
ignore my comment about the redirection - I see that this is being resolved by #1843

**Comment by yaacov** [comment]
@suomiy  :+1:

Didn't see the `.../cluster/...` route before :-) , played with other resources and it looks like it behaves like `all-namespaces` ? so I added it in the same way, am I missing something here ?

**Comment by suomiy** [comment]
After looking at it the second time, I would remove the cluster route altogether for vmtemplates. It seems to me that it is meant for cluster wide resources like storageclasses.

**Comment by yaacov** [comment]
> After looking at it the second time, I would remove the cluster route altogether for vmtemplates. It seems to me that it is meant for cluster wide resources like storageclasses.

@suomiy makes sense :+1: 

I copied the `cluster` route from here:
https://github.com/openshift/console/blob/master/frontend/public/components/factory/list-page.jsx#L321

It looks like we do not need to support the `cluster` option for vms and vmtemplates .

**Pull request merged**
