### PR TITLE
Remove custom namespace and CRD list APIs

### PR DESCRIPTION
**Pull request by spadgett**
Remove the special namespace and CRD console endpoints, which can be
escalating if the console service account has greater privileges than
the logged in user.

For namespaces, use the Kubernetes API instead, passing the user's
API token (like other resources).

For CRDs, we already use API discovery, so the custom endpoint
isn't needed.

### CODE REVIEW

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by jhadvig** [comment]
The PR looks good since its just removing the extra endpoints. Just a question, not sure how we get list of resources (of a particular kind) that a particular user can view, since we don't get `SelfSubjectRulesReview` rules. Or we just check the RC ?

**Comment by jhadvig** [comment]
Also, was testing the PR, so I've rebuilt the binary and run the `./examples/run-bridge.sh` but I could not login into the console, got stucked ina login loop:
```
2018/07/9 13:44:06 cmd/main: cookies are not secure because base-address is not https!
2018/07/9 13:44:06 cmd/main: Binding to 127.0.0.1:9000...
2018/07/9 13:44:06 cmd/main: not using TLS
2018/07/9 13:59:12 auth: unable to verify auth code with issuer: Post https://127.0.0.1:8443/oauth/token: x509: certificate signed by unknown authority
2018/07/9 13:59:13 server: authentication failed: unauthenticated
2018/07/9 13:59:13 server: authentication failed: unauthenticated
2018/07/9 13:59:13 server: authentication failed: unauthenticated
```

**Comment by spadgett** [comment]
@jhadvig Yeah, the login problem is unrelated. You don't have the right CA cert:

> auth: unable to verify auth code with issuer: Post https://127.0.0.1:8443/oauth/token: x509: certificate signed by unknown authority

The instructions have changed a bit. Make sure you're following what's documented here:

https://github.com/openshift/console#openshift

The CA cert file is set here:

https://github.com/openshift/console/blob/master/examples/run-bridge.sh#L14

**Comment by spadgett** [comment]
> Just a question, not sure how we get list of resources (of a particular kind) that a particular user can view, since we don't get SelfSubjectRulesReview rules.

@benjaminapetersen has started working on that. We've SSAR checks for cluster-scoped resources in #99

**Comment by spadgett** [comment]
cc @alecmerdler

**Comment by spadgett** [comment]
@jwforres FYI, this removes the two escalating endpoints. (The console service account isn't granted special permission during install, but I still want to remove these.)

**Pull request merged**
