### PR TITLE
Update PF packages to 2021-10

### PR DESCRIPTION
**Pull request by jcaianirh**
Remove some previously needed translate="no" props due to react/types version mismatch as they are no longer needed for the menu components.

### CODE REVIEW

**Comment by spadgett** [comment]
@jcaianirh This bump makes our vendor bundle almost 50% larger:

```
Main vendor bundle size: 4.73 MiB
FAILURE: Main vendor bundle is larger than the 3.25 MiB limit.
```

**Comment by jcaianirh** [comment]
> @jcaianirh This bump makes our vendor bundle almost 50% larger:
> 
> ```
> Main vendor bundle size: 4.73 MiB
> FAILURE: Main vendor bundle is larger than the 3.25 MiB limit.
> ```

yes, there is a victory-core mismatch (between pf and console) causing duplication. checking with the pf folks, we can remove our entry as this dependecy is already present with the pf-charts dependency.

**Review by sg00dwin — APPROVED** [review]

**Review by spadgett — APPROVED** [review]
/lgtm

/label px-approved
/label docs-approved

No user visible changs, so adding px- and docs-approved labels.

/assign @yapei 
for QE review

**Comment by yapei** [comment]
Did a regression tests about action menu item and lists, no issues found
/label qe-approved

**Pull request merged**
