### PR TITLE
OCPBUGS-4008: Make sure console refresh toast notification pops up wh…

### PR DESCRIPTION
**Pull request by TheRealJon**
…en managed cluster list changes.

### CODE REVIEW

**Comment by spadgett** [comment]
Thanks, @TheRealJon. Let's go ahead with this change, but it might be good to also explore how hard it is to simply update  the cluster list on the client. Since no JavaScript has changed, we shouldn't strictly need a browser refresh. The problem is that in places we're accessing `window.SERVER_FLAGS.clusters` directly (e.g. to disable features like cloud shell), and we'd need to store the list in Redux or React context.

I worry in a large fleet the user might see this popup often.

**Comment by spadgett** [comment]
Current direct references to `clusters`, mostly in tests. `isMultiClusterEnabled` would need to become a hook to react client side to cluster changes.

```
❯ rg -F 'SERVER_FLAGS.clusters'
frontend/packages/integration-tests-cypress/tests/app/multi-cluster.spec.ts
19:      win.SERVER_FLAGS.clusters = MULTI_CLUSTER_ARRAY;

frontend/packages/console-app/src/components/nav/NavHeader.tsx
137:  const clusterItems = (window.SERVER_FLAGS.clusters ?? []).map((managedCluster: string) => (

frontend/packages/console-app/src/components/cloud-shell/__tests__/CloudShellTab.spec.tsx
11:    window.SERVER_FLAGS.clusters = ['clustera'];
18:    window.SERVER_FLAGS.clusters = ['clustera'];
25:    window.SERVER_FLAGS.clusters = ['clustera', 'clusterb'];
32:    window.SERVER_FLAGS.clusters = ['clustera'];

frontend/packages/console-app/src/utils/isMultiClusterEnabled.ts
1:const isMultiClusterEnabled = (): boolean => window.SERVER_FLAGS.clusters?.length > 1;

frontend/packages/console-app/src/utils/__tests__/isMultiClusterEnabled.spec.ts
5:    window.SERVER_FLAGS.clusters = undefined;
10:    window.SERVER_FLAGS.clusters = ['clustera'];
15:    window.SERVER_FLAGS.clusters = ['clustera', 'clusterb'];

frontend/packages/knative-plugin/src/utils/__tests__/fetch-dynamic-eventsources-utils.spec.ts
39:    window.SERVER_FLAGS.clusters = ['clustera', 'clusterb'];
45:    window.SERVER_FLAGS.clusters = null;
149:    window.SERVER_FLAGS.clusters = ['clustera', 'clusterb'];
155:    window.SERVER_FLAGS.clusters = null;
```

**Review by jhadvig — APPROVED** [review]
/lgtm

**Comment by rhamilto** [comment]
I added integration tests to console updates.  We should add a test for managed clusters list.

**Pull request merged**
