### PR TITLE
Bug 1877822: The OS which already has a golden image can not be selected

### PR DESCRIPTION
**Pull request by glekner**
Os with a golden image selected from a URL param or from the dropdown will have the following alert:

image

### CODE REVIEW

**Comment by glekner** [comment]
@yaacov can you review

**Comment by jelkosz** [comment]
@glekner you need to disable the controls on the screen when you pick an os which already has an image. Now I do see the error message but I can ignore it and attempt to do an upload and get 
image

**Comment by matthewcarleton** [comment]
> Os with a golden image selected from a URL param or from the dropdown will have the following alert:
> 
> image

So does that text within the dropdown change to default data image already exists when they select it? I don't think we need to change it if we are showing the alert.

**Comment by glekner** [comment]
@matthewcarleton @jelkosz 
Tomas wrote in the BZ to keep the `default data image already exists` inside the dropdown. can we settle?

**Comment by matthewcarleton** [comment]
My opinion hasn’t changed :) Tomas WDYT?

**Comment by jelkosz** [comment]
@matthewcarleton it does not change - it is there the whole time so I would keep it there. The "source available" feels like "everything is fine, source is available, feel free to pick me" while the "default data image already exists" feels like "dont touch this, it has already been configured" :)

**Comment by glekner** [comment]
Upload button is now disabled when the alert is shown @jelkosz 
image

**Comment by matthewcarleton** [comment]
> @matthewcarleton it does not change - it is there the whole time so I would keep it there. The "source available" feels like "everything is fine, source is available, feel free to pick me" while the "default data image already exists" feels like "dont touch this, it has already been configured" :)

ok I see your point. LGTM :)

**Pull request merged**
