### PR TITLE
Bug 1944602: fixing-project-creation-and-updated-packageJson

### PR DESCRIPTION
**Pull request by makambalaji**
**Problem**: project creation feature execution issue on CI issue and updated package json
**solution**: This pr is created to update package.json under devconsole, where specs are selected instead of selecting specs from frontend/package.json
Included one more change, i.e, merging runtime-icon.feature to create from container image

Need to backport this pr to 4.7 as well, to avoid the CI issues

Executed on Chrome Browser

**Screenshot**
image

### CODE REVIEW

**Review by gajanan-more — APPROVED** [review]
Screenshot from 2021-03-31 15-26-37


Working as expected

/lgtm

**Review by dtaylor113 — APPROVED** [review]
/approved

**Pull request merged**
