### PR TITLE
[release-4.2] Bug 1796634: Fix bug where booleanSwitch does not default to false

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1796634

Partial back port of #3390

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
/retest

```
level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply using Terraform"
```

**Comment by bparees** [comment]
@rhamilto i'm unclear on why this was only a partial backport of the 4.3 fix, can you explain?

**Comment by rhamilto** [comment]
> @rhamilto i'm unclear on why this was only a partial backport of the 4.3 fix, can you explain?

Sure.  There are additional changes in #3390 that are specific to other 4.3 changes that are not part of 4.2.

**Comment by bparees** [comment]
thanks, approved

**Pull request merged**
