### PR TITLE
Fast-forward the multicluster feature branch

### PR DESCRIPTION
**Pull request by TheRealJon**

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by TheRealJon** [comment]
This opened to try and get a PR to pass CI, but it has since passed all checks. Closing.

**Review by jcaianirh — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
/override kubevirt-plugin

Overriding the kubevirt plugin test to unblock work since this is only the feature branch. We'll have to address any test failures when we merge into master.

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
