### PR TITLE
convert topology application group side panel to use dynamic extensions

### PR DESCRIPTION
**Pull request by sahil143**
fixes: https://issues.redhat.com/browse/ODC-5846, task: https://issues.redhat.com/browse/ODC-6112

Screenshot:
image

### CODE REVIEW

**Review by rottencandy — COMMENTED** [review]
Page crashes with this error when I try to open application sidebar:

**Comment by sahil143** [comment]
> Page crashes with this error when I try to open application sidebar: 

@rottencandy fixed

**Review by rottencandy — APPROVED** [review]
Tested the changes
/lgtm

**Comment by invincibleJai** [comment]
/approve
/label qe-approved

verified the changes and works as expected.

**Comment by sahil143** [comment]
Propagate from epic:

/label px-approved
/label doc-approved

**Pull request merged**
