### PR TITLE
Include ActionServiceProvider in dynamic-plugin-sdk

### PR DESCRIPTION
**Pull request by jgbernalp**
Exposes ActionServiceProvider to ease the consumption of action extensions. Using the ActionsServiceProvider includes an extension points to alerts toolbar.

https://user-images.githubusercontent.com/5461414/185861110-7acaf8ae-0ec3-4cb2-9ec6-fa09ab314d03.mov

### CODE REVIEW

**Comment by jgbernalp** [comment]
cc @christianvogt

**Comment by christianvogt** [comment]
/approve

cc @vojtechszocs @spadgett

**Comment by christianvogt** [comment]
/lgtm

cc @spadgett

**Comment by jgbernalp** [comment]
/assign @yapei @opayne1 @RickJWagner
for approvals

**Comment by yapei** [comment]
Screen Shot 2022-08-22 at 15 48 46
/label qe-approved

**Comment by jgbernalp** [comment]
cc @opayne1

**Pull request merged**
