### PR TITLE
Upgrade patternfly-react-extensions and adjust catalog sidebar width

### PR DESCRIPTION
**Pull request by rhamilto**
This resolves the outstanding issues with spacing between catalog tiles and the width of the catalog sidebar.

attn: @tlwu2013

localhost_9000_catalog_ns_robb
localhost_9000_catalog_ns_robb 1
localhost_9000_catalog_ns_robb 2

### CODE REVIEW

**Comment by tlwu2013** [comment]
Hey @rhamilto, thanks for your great efforts on this! Super appreciated! :)

Just one small thing, I feel the spacing of the `<li>` from your screenshots seems to be smaller in comparison with the current setting in the shared cluster. 

*screenshot from this PR:*
pr

*mocked screenshot with shared cluster's spacing:*
pr__mocked

Could you kindly help check the spacing between `vertical-tabs-pf-tab`?  Thanks again!  👍 👍

**Comment by rhamilto** [comment]
I've opened https://github.com/patternfly/patternfly-react/issues/687 upstream to address the spacing issue.

**Comment by sosiouxme** [comment]
@spadgett naturally :( I'll put a little work toward scripting this today, maybe I can at least get it to where it's trivial to run by hand. Eventually it should just happen as part of downstream builds.

**Comment by rhamilto** [comment]
Upstream PR to fix VerticalTabs spacing issue: https://github.com/patternfly/patternfly-react/pull/688

Will update this PR with a new patternfly-react-extensions release once the aformentioned PR merges.

**Comment by rhamilto** [comment]
Updated with upstream fixes.  @tlwu2013, PTAL.

**Comment by sosiouxme** [comment]
Apologies for the delay. I got back to this and I've scripted it now so should be easier in the future. Not included in automation yet though.

@rhamilto Please update the sources as part of this PR:

```
diff --git a/sources b/sources
index 7d156de..34c7d87 100644
--- a/sources
+++ b/sources
@@ -1,2 +1,2 @@
 401aa1438604b8e32306fa2bd4f8e211  node-v8.9.4-headers.tar.gz
-6eb618b42413ed28fb9ce0ca4130722e  yarn-offline.tar
+60d04378ee7fe27c3ac97b6a6bd3d65b  yarn-offline.tar
```

(to be clear, it should look like:)

```
401aa1438604b8e32306fa2bd4f8e211  node-v8.9.4-headers.tar.gz
60d04378ee7fe27c3ac97b6a6bd3d65b  yarn-offline.tar
```

**Comment by rhamilto** [comment]
sources updated.  Ready for merge.

**Pull request merged**
