### PR TITLE
Reenable secrets integration tests

### PR DESCRIPTION
**Pull request by spadgett**
/cc @jhadvig

### CODE REVIEW

**Comment by spadgett** [comment]
Install failed

/retest

**Comment by jhadvig** [comment]
```
2019/04/12 16:30:36 auth: error contacting auth provider (retrying in 10s): discovery through endpoint https://172.30.0.1:443/.well-known/oauth-authorization-server failed: 404 Not Found
```

/retest

**Comment by jhadvig** [comment]
```
NoSuchElementError: No element found using locator: By(css selector, [data-test=etcd-openshift-marketplace])
    at elementArrayFinder.getWebElements.then (/go/src/github.com/openshift/console/frontend/node_modules/protractor/built/element.js:814:27)
    at ManagedPromise.invokeCallback_ (/go/src/github.com/openshift/console/frontend/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/go/src/github.com/openshift/console/frontend/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/go/src/github.com/openshift/console/frontend/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/go/src/github.com/openshift/console/frontend/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /go/src/github.com/openshift/console/frontend/node_modules/selenium-webdriver/lib/promise.js:668:7
    at process._tickCallback (internal/process/next_tick.js:68:7)Error
    at ElementArrayFinder.applyAction_ (/go/src/github.com/openshift/console/frontend/node_modules/protractor/built/element.js:459:27)
    at ElementArrayFinder.(anonymous function).args [as getText] (/go/src/github.com/openshift/console/frontend/node_modules/protractor/built/element.js:91:29)
    at ElementFinder.(anonymous function).args [as getText] (/go/src/github.com/openshift/console/frontend/node_modules/protractor/built/element.js:831:22)
    at Object.<anonymous> (/go/src/github.com/openshift/console/frontend/integration-tests/tests/operator-hub/operator-hub.scenario.ts:152:103)
    at step (/go/src/github.com/openshift/console/frontend/integration-tests/tests/operator-hub/operator-hub.scenario.ts:33:23)
    at Object.next (/go/src/github.com/openshift/console/frontend/integration-tests/tests/operator-hub/operator-hub.scenario.ts:14:53)
    at fulfilled (/go/src/github.com/openshift/console/frontend/integration-tests/tests/operator-hub/operator-hub.scenario.ts:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

/retest

**Comment by spadgett** [comment]
Let's see if it passes a second time...

/test e2e-aws-console

**Comment by jhadvig** [comment]
@spadgett everything is green :)

**Comment by spadgett** [comment]
/hold cancel

@jhadvig please lgtm if this looks good, thanks!

**Pull request merged**
