### PR TITLE
i18n common components: YAML

### PR DESCRIPTION
**Pull request by rebeccaalpert**
Addressed components related to the YAML tab on the details page.

This is a part of https://issues.redhat.com/projects/CONSOLE/issues/CONSOLE-2416.

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
LGTM, will need QE review

**Comment by spadgett** [comment]
/assign @yapei @ahardin-rh @sferich888 
for QE / docs / CEE review

This localizes the YAML editor.

**Comment by ahardin-rh** [comment]
Ack from the docs side :+1:

**Comment by yanpzhan** [comment]
/label qe-approved
Launch cluster with cluster-bot against the pr, the yaml related items are marked for translation, no issue is found for now.

**Comment by spadgett** [comment]
> Ack from the docs side 👍

/label docs-approved

**Comment by rebeccaalpert** [comment]
Rebased.

**Comment by spadgett** [comment]
@rebeccaalpert You need to run prettier, thanks!

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
