### PR TITLE
[WIP] Monitoring: Remove page descriptions

### PR DESCRIPTION
**Pull request by kyoto**
A separate PR will also remove the "Alerts" / "Silences" tabs.

FYI @cshinn 

screenshot-1

### CODE REVIEW

**Comment by sichvoge** [comment]
@kyoto @cshinn are we just removing it or add a least description and a link to some documentation?

**Comment by kyoto** [comment]
@sichvoge @cshinn The suggestion is to just remove it for now since it is probably not very helpful, but maybe add back a more helpful description later, possibly with different styling.

**Comment by sichvoge** [comment]
I'd love to have that for the release though. If you want, I can add it back when the time comes.

**Comment by sichvoge** [comment]
Later meaning before the release? :)

**Comment by cshinn** [comment]
@sichvoge yes that's definitely what I intend! I would like to discuss with you what would be useful information to include here as well as figure out a pattern for including these kinds of descriptions that we can use consistently in other parts of the application. I think it's better to remove non-useful descriptions in the (very) short term so that we have a clean slate. That said, if you feel strongly, we can wait until there's a good replacement.

**Comment by sichvoge** [comment]
Agree, I couldn't find anything helpful as well. We should leave it out until we have something more appropriate. The docs team will need to create some description on how to use all this. I think as soon as this is finished, we can add a link to that.

WDYT?

**Comment by cshinn** [comment]
@sichvoge currently working with a content strategist to come up with some good text here. If we come up with anything, I'll run it by you.

**Comment by kyoto** [comment]
Closing this PR and will open a new one for changing the description text once we have decided what it should be.

**Pull request closed without merging**
