### PR TITLE
Add help texts for Serverless Advanced Scaling

### PR DESCRIPTION
**Pull request by debsmita1**
This PR fixes the bug: https://jira.coreos.com/browse/ODC-1442

Screenshot from 2019-07-25 15-37-46

### CODE REVIEW

**Comment by invincibleJai** [comment]
@debsmita1 did you confirmed on wordings from UXD?

**Comment by debsmita1** [comment]
> @debsmita1 did you confirmed on wordings from UXD?

@invincibleJai yes, spoke to @parvathyvr . She said that the help text wordings are final

**Pull request merged**
