### PR TITLE
OCPBUGS-18542: Fixed topology package e2e tests

### PR DESCRIPTION
**Pull request by sanketpathak**
Issue: https://issues.redhat.com/browse/OCPBUGS-18542
Description: Fixed tests in the topology package

### CODE REVIEW

**Comment by The-Anton** [comment]
All test are passing.
/lgtm

**Comment by sanketpathak** [comment]
It only updates the integration tests

/label acknowledge-critical-fixes-only
/label px-approved
/label qe-approved
/label docs-approved

**Pull request merged**
