### PR TITLE
Bug: fix network/storage row kebab focus in createVMWizard

### PR DESCRIPTION
**Pull request by suomiy**
depends on:
- [ ] #3411

### CODE REVIEW

**Comment by christianvogt** [comment]
@suomiy could you share some screenshots and describe the problem. Was this a result of the recent kebab changes?

**Comment by suomiy** [comment]
> @suomiy could you share some screenshots and describe the problem. 

it is not possible to focus or select kebab options. This has to do with the wizard z-indexes

> Was this a result of the recent kebab changes?

yes

aa

**Comment by christianvogt** [comment]
@suomiy We're better to apply a default `z-index` value to the Popper itself.
I created a PR: https://github.com/openshift/console/pull/3431
Let me know if this solves your issue.

**Comment by christianvogt** [comment]
A default z index is now applied to the kebab which should solve your problem.

**Comment by suomiy** [comment]
@christianvogt works great, thanks!

**Pull request closed without merging**
