### PR TITLE
[release-4.12] OCPBUGS-13580: Regression: OpenShift Console no-longer filters SecretList when displaying ServiceAccount

### PR DESCRIPTION
**Pull request by cyril-ui-developer**

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/approve
/label backport-risk-assessed

**Review by rhamilto — APPROVED** [review]
/lgtm

**Comment by cyril-ui-developer** [comment]
> Hi @cyril-ui-developer, I tested the PR by using cluster bot (launch 4.12,#12747), but the Secret list is still shown in the ServiceAccount details page, could you help to check?

@XiyunZhao This is expected for release-4.12 since the change to remove autogenerated secrets was introduced in 4.12. 
cc: @rhamilto

**Comment by XiyunZhao** [comment]
> > Hi @cyril-ui-developer, I tested the PR by using cluster bot (launch 4.12,#12747), but the Secret list is still shown in the ServiceAccount details page, could you help to check?
> 
> @XiyunZhao This is expected for release-4.12 since the change to remove autogenerated secrets was introduced in 4.12. cc: @rhamilto

Sorry @cyril-ui-developer, I have some misunderstanding here, based on the changes on 4.13-4.15, the secret list is removed from the SA details page, which means list will be no longer shown on the page.
Based on your reply, did you mean that the list will be kept on 4.12 only, and only SA related secret would be shown, is that correct?

**Comment by cyril-ui-developer** [comment]
> > > Hi @cyril-ui-developer, I tested the PR by using cluster bot (launch 4.12,#12747), but the Secret list is still shown in the ServiceAccount details page, could you help to check?
> > 
> > 
> > @XiyunZhao This is expected for release-4.12 since the change to remove autogenerated secrets was introduced in 4.12. cc: @rhamilto
> 
> Sorry @cyril-ui-developer, I have some misunderstanding here, based on the changes on 4.13-4.15, the secret list is removed from the SA details page, which means list will be no longer shown on the page. Based on your reply, did you mean that the list will be kept on 4.12 only, and only SA related secret would be shown, is that correct?

@XiyunZhao Yes. Sorry for late reply.

**Pull request merged**
