### PR TITLE
Bug 1957756: Fix key value in replacement object 

### PR DESCRIPTION
**Pull request by afreen23**
- key is `node` but we are fetching `nodeName`.
- removed the check for metrics map since it's redundant.
- updated check for the replaced device based on  path and deviceID to differentiate similar paths on same node

Signed-off-by: Afreen Rahman <afrahman@redhat.com>

### CODE REVIEW

**Review by bipuladh — APPROVED** [review]
/lgtm

**Comment by afreen23** [comment]
/hold cancel
tested with actual disks based environment. Working fine

**Pull request merged**
