### PR TITLE
CONSOLE-2453: Hpa i18n

### PR DESCRIPTION
**Pull request by zherman0**
[CONSOLE-2453](https://issues.redhat.com/browse/CONSOLE-2453): i18n for Hpa

### CODE REVIEW

**Comment by zherman0** [comment]
Updates to conditions.tsx is causing several unit test to fail.  Under Investigation now:
```
it('renders a conditions status', () => {
    descriptor['x-descriptors'] = [StatusCapability.conditions];
    descriptor.path = 'conditions';
    wrapper.setProps({ descriptor });

    expect(wrapper.find(Conditions).exists()).toBe(true);
  });
```

**Review by spadgett — APPROVED** [review]
/lgtm
/hold for approvals
/assign @yapei @ahardin-rh @sferich888

**Review by spadgett — APPROVED** [review]
/lgtm

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
