### PR TITLE
[release-4.9] Bug 2065549: Change the tekton hub api endpoint to use v1 api

### PR DESCRIPTION
**Pull request by karthikjeeyar**
This is an manual cherry-pick of https://github.com/openshift/console/pull/11186

Description:

Change the tekton hub endpoints to use the latest `v1` Apis

/assign @jerolimov 
/cc @sanketpathak

### CODE REVIEW

**Comment by jerolimov** [comment]
/retitle [release-4.9] Bug 2065549: Change the tekton hub api endpoint to use v1 api
/label backport-risk-assessed

**Review by jerolimov — APPROVED** [review]
/lgtm
/approve

**Comment by sanketpathak** [comment]
Verified using cluster-bot
Screenshot from 2022-03-18 21-18-03
/label cherry-pick-approved

**Pull request merged**
