### PR TITLE
Bug 1921258: use sessionStorage for user-settings when impersonating

### PR DESCRIPTION
**Pull request by christianvogt**
**Analysis / Root cause**: 
When logged in as kubeadmin and impersonating a user, the access to the user-settings configmap for kubeadmin returns a 403 which puts the user settings hook in a bad state and will update whenever another tab is opened for the kubeadmin user and their settings are updated.

**Solution Description**: 
When impersonating a user, use session storage as the backing store instead of configmap or local storage.

**Screen shots / Gifs for design review**: 
No UI change.

**Unit test coverage report**: 
Added unit test which checks for session storage usage when impersonating.

**Browser conformance**: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [x] Edge

### CODE REVIEW

**Comment by invincibleJai** [comment]
@christianvogt  Verified it i no longer observed Switch in perspective when tried on one window with impersonate and another with kubeadmin. 

Storing in session works as expected in chrome however in safari it doesn't seems to work as expected. That looks like a separate issue LMK if needed will log one


Jan-29-2021 17-17-32

**Comment by christianvogt** [comment]
@invincibleJai thanks. I cannot test safari until i update my OS since my safari is too old and doesn't support `ResizeObserver` and the console errors out ;/

**Comment by invincibleJai** [comment]
> @invincibleJai thanks. I cannot test safari until i update my OS since my safari is too old and doesn't support `ResizeObserver` and the console errors out ;/

i verified again and it works fine in Safari as well earlier i was trying to look in storage and din't seem to get it reflect there then but seems fine now

image

**Comment by christianvogt** [comment]
@invincibleJai that's for the review and test.
I did just notice from your screenshot that you are using the dev setup where you choose to store settings in local storage instead of configmaps. When we enable this setting, the user-settings key in the local storage is always set to `console-user-settings` as oppose to `console-user-settings-<userid>`. I fixed the key when impersonating.

**Pull request merged**
