### PR TITLE
[release-4.16] OCPBUGS-35571: Update Go prereq in README.md 

### PR DESCRIPTION
**Pull request by logonoff**
Per [issues.redhat.com/browse/OCPBUGS-35497](https://issues.redhat.com/browse/OCPBUGS-35497) and #13979, correct the go prereq README for release v4.16

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Review by vikram-raj — COMMENTED** [review]
/label backport-risk-assessed

**Pull request merged**
