### PR TITLE
CONSOLE-2985: Replace all instances of old variables controlling global grid widths and breakpoints with Patternfly variables for more consistency of spacing between elements and behaviors

### PR DESCRIPTION
**Pull request by sg00dwin**
Replaces `$grid-gutter-width` instances with Patternfly equivalent `$pf-global-gutter--md` and `$pf-global-gutter`
Replaces instances of `$grid-float-breakpoint` variables with Patternfly `$pf-global--breakpoint--(size)`

Minor markup changes and associated css to various pages for consistency of markup and spacing/positioning. (PipelineBuilder and MonitoringPage)

The primary spacing changes are the left and right margins of the main page elements (page-body, project selector, breadcrumbs, title, actions button)

Notes:

```
// Old
$grid-gutter-width = 30px 
($grid-gutter-width / 2) = 15px
```

```
// New
// PF uses $pf-global--gutter for it's mobile size to 1200px and $pf-global--gutter--md for >1200px
$pf-global--gutter--md: $pf-global--spacer--lg !default; // 24px
$pf-global--gutter: $pf-global--spacer--md !default; // 16px
```

**Switching from `$grid-float-breakpoint` to `$pf-global--breakpoint--{size}`**
```
@screen-sm-min == $pf-global--breakpoint--md // 768
@screen-md-min == $pf-global--breakpoint--lg // 992
@screen-lg-min == $pf-global--breakpoint--xl // 1200
```

PF doesn't have `..-max` values. I created ones to use with for our ` @media (max-width: ...` use cases.
```
$pf-global--breakpoint--xs-max: ($pf-global--breakpoint--xs - 1);
$pf-global--breakpoint--sm-max: ($pf-global--breakpoint--sm - 1);
$pf-global--breakpoint--md-max: ($pf-global--breakpoint--md - 1);
$pf-global--breakpoint--lg-max: ($pf-global--breakpoint--lg - 1);
```

observe-dashboard-b4
observe-dashboard-after

----

pipeline-metrics-b4

pipeline-metrics-after
 
----

List-events-b4
List-events-after

----

yaml-side-b4
yaml-side-after

----

dev-console-dashboard-b4

dev-console-dashboard-after

----

pipeline-builder-b4

pipeline-builder-after

----

yaml-edit-b4
yaml-edit-after

### CODE REVIEW

**Comment by rhamilto** [comment]
/lgtm

Don't forget to request your other approvals.

**Comment by sg00dwin** [comment]
/assign @yapei @opayne1 @RickJWagner
for approvals

**Comment by XiyunZhao** [comment]
@sg00dwin Hi, I have two questions about the changes:
1. The pops up textbox of 'Add task' is out of the canvas of tasks, is that correct behavior?
2. There is a new option '$__auto_interval_period' on the dropdown list of the Period, please help to take a look
image
image

**Comment by sg00dwin** [comment]
> * The pops up textbox of 'Add task' is out of the canvas of tasks, is that correct behavior?

Yes, it is draggable.

> * There is a new option '$__auto_interval_period' on the dropdown list of the Period, please help to take a look

This looks like an unrelated bug with Grafana variables.  @kyoto do you know?

**Comment by XiyunZhao** [comment]
@sg00dwin I will track the second one on BZ, this PR has been verified on a private build, no other issue found

**Comment by kyoto** [comment]
@XiyunZhao @sg00dwin The `$__auto_interval_period` issue will be addressed by https://github.com/openshift/console/pull/10472

**Pull request merged**
