### PR TITLE
Integrate NotificationDrawer component from PatternFly

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
This PR uses the NotificationDrawer component in PatternFly to replace the previous one that was implemented in OpenShift. Thus, I delete the folder /frontend/packages/patternfly/. What's more, I create some mock alert data and add some test cases to do unit test on Notification Drawer.

### CODE REVIEW

**Comment by DaoDaoNoCode** [comment]
@jcaianirh All tests have been past, please take a look.

**Comment by jcaianirh** [comment]
Note: this needs the x close button update here: https://github.com/patternfly/patternfly-react/pull/4739

**Comment by jcaianirh** [comment]
/remove-lifecycle stale and freshen up this pr

**Pull request closed without merging**
