### PR TITLE
add labels to OWNERS files

### PR DESCRIPTION
**Pull request by christianvogt**
Adds `labels` to owners files for prow `owners-labels` plugin to automatically apply labels.

Requires: https://github.com/openshift/release/pull/4526

cc @spadgett

### CODE REVIEW

**Comment by christianvogt** [comment]
@spadgett I didn't update the owners in the files that are being tagged an issue. Should i just remove their names or can we override? How'd they get added in the first place.

**Comment by christianvogt** [comment]
rebased

**Comment by spadgett** [comment]
> @spadgett I didn't update the owners in the files that are being tagged an issue. Should i just remove their names or can we override? How'd they get added in the first place.

@cloudbehl @gnehapk @flofuchs can you submit requests to join the OpenShift org?

I'd suggest we remove them from OWNERS for now to unblock the PR and add them back when they're in the org.

**Comment by christianvogt** [comment]
Removed the non members.

**Comment by christianvogt** [comment]
Prow complained again and had to remove @afreen23 and @dantrainor

**Comment by cloudbehl** [comment]
@christianvogt Got added back to openshift org can you add my name back, sorry for the inconvenience.

Got removed from org it yesterday because I forgot to add the GitHub id to the rover.

@spadgett ^^

Thanks

**Pull request merged**
