### PR TITLE
[release-4.9] Bug 2073999: avoid pre-fetching tekton hub task versions

### PR DESCRIPTION
**Pull request by karthikjeeyar**
This is a manual cherry pick of https://github.com/openshift/console/pull/11290

Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=2073999

**Analysis / Root cause:**

Prefetching all the task versions upfront might cause issues in slower network and this tasks catalog can grow in future.

**Solution Description:**

Avoided prefetching of task versions and now fetching lazily when a task is selected.
Switching back and forth between previously selected tasks will not make API call again.

---
**Screenshots**:

image

---

pipelineQuickSearchDetails:
    CTA button tests
      ✓ Add button should be disabled if the versions is not available (119ms)
      ✓ Add button should be enabled if the versions is not available (158ms)
      
 pipelineQuickSearchVersionDropdown:
    ✓ should not show version dropdown if an invalid value is passed as versions (18ms)
    ✓ should call the onchange handler with the version key (22ms)
    
---

**Test setup:**

1. Install OpenShift Pipelines operator
2. Navigate to pipeline list page
3. Open the browser network inspector and filter for "api.hub.tekton.dev"
4. Click on Create Pipeline to navigate to pipeline builder page
5. Observe the network calls.

### CODE REVIEW

**Review by jerolimov — CHANGES_REQUESTED** [review]
Hey @karthikjeeyar

you don't backported `tektonHub.spec.ts`, any reason for that?

You also don't removed `pipelines-plugin/src/components/catalog/const.ts` and `packages/pipelines-plugin/src/types/tektonHub.ts`, both are not needed anymore, or?

**Comment by karthikjeeyar** [comment]
@jerolimov Ah, I missed to remove unused files and now added the test as well. Thanks for pointing out

**Review by jerolimov — APPROVED** [review]
Similar code as in 4.10, tested it locally and it works fine. There is an issue that I can now also reproduce in 4.11 that the version API call was triggered multiple when typing fast. Maybe because the response is not saved at that moment... I wrote you on slack if we want create a follow-up bug for that.

https://user-images.githubusercontent.com/139310/163418124-8fd52455-72ec-4317-aafe-b732f636f503.mp4

For now this backport looks fine for me.

/lgtm
/approve

**Comment by jerolimov** [comment]
Jan, I've tested this already on a cluster, see https://github.com/openshift/console/pull/11312#pullrequestreview-942415806

/label backport-risk-assessed
/cc @jrichter1

**Pull request merged**
