### PR TITLE
Bug 1749397:Removed edit yaml link from ocs install flow

### PR DESCRIPTION
**Pull request by gnehapk**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1749397

OCS install flow looks like this now -
ocs-install

### CODE REVIEW

**Comment by gnehapk** [comment]
@spadgett @afreen23 @cloudbehl Please review.

**Comment by spadgett** [comment]
@gnehapk needs rebase

Is this required for 4.2? This is a rather large change, and the guidance is to limit fixes to critical bugs. If we must fix this in 4.2, we should consider a smaller fix like leaving the existing code in place and just removing the link.

**Comment by gnehapk** [comment]
@spadgett Make sense. I will amend the PR which will only remove the link and can target refactoring in 4.3.

**Comment by gnehapk** [comment]
@spadgett Amended the PR. Please review.

**Comment by cloudbehl** [comment]
@spadgett As @gnehapk mentioned, removing one component led to another. I think for now we can do a `display: none` on button[1] and we should be good. Thoughts?

https://github.com/openshift/console/pull/2752/files#diff-d0946bdb0e314e7aa9773ce5be8b2db8L59

**Pull request merged**
