### PR TITLE
OCPBUGS-1678: Use local test data to mock a devfile registry

### PR DESCRIPTION
**Pull request by jerolimov**
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-1678

**Analysis / Root cause**: 
pkg/devfile/sample_test.go fails after devfile registry was updated (https://github.com/devfile/registry/pull/126)

**Solution Description**: 
Follow up on #12085 that just updated the assertion.

This PR adds a test server that mock a devfile registry and return json data from a testdata folder.

### CODE REVIEW

**Comment by jerolimov** [comment]
Thanks, but i would like that @jhadvig take a look as well because we wanna backport this.

If this takes too much time we can backport #12085

/hold

**Review by jhadvig — APPROVED** [review]
@jerolimov the change looks good 👍 
One thing that could be update is the name of the datatest folder. Instead of `registry.stage.devfile.io` it should be `registrystagedevfileio` to align to the naming convention. But see your point of the registry domain.
/lgtm
/approve

**Comment by jerolimov** [comment]
Updated based on your feedback @jhadvig. Thanks. :)

/unhold

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
