### PR TITLE
Update PF packages to release 2021-16

### PR DESCRIPTION
**Pull request by jcaianirh**
cc: @sg00dwin

### CODE REVIEW

**Comment by jcaianirh** [comment]
/retest

Other routes failed test in ci succeeded locally

**Comment by jcaianirh** [comment]
QE Approver:
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

Console Approver:
/assign @kdoberst

**Comment by gruselhaus** [comment]
@jcaianirh a rebase could do the trick. I think there were some commits that fixed the e2e issues.

**Comment by gruselhaus** [comment]
@jcaianirh this can't be the flaky tests 😂

**Pull request closed without merging**
