### PR TITLE
Bug 1803611: show hint for the typed metrics in Metrics PromQL editor

### PR DESCRIPTION
**Pull request by vikram-raj**
**Fixes**: 
https://issues.redhat.com/browse/ODC-3809

**Analysis / Root cause**: 
The hint was not showing up when the user start typing in the metrics PromQL.

**Solution Description**: 
Set metrics in the redux store so that when the user starts typing then the hint shows up.

**Screen shots / Gifs for design review**: 
promql-hint

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by vikram-raj** [comment]
/retitle Bug 1803611: show hint for the typed metrics in Metrics PromQL editor

**Comment by invincibleJai** [comment]
Metrics are not same like as we have in Admin i.e 

from Admin :

Screenshot 2020-05-15 at 4 38 39 PM

for DevCnsole

Screenshot 2020-05-15 at 4 39 27 PM

is this right behaviour ?

**Comment by vikram-raj** [comment]
@invincibleJai Yes, it is expected behavior, as it calls the different API calls based on ```namespace``` is available or not.

**Comment by invincibleJai** [comment]
> @invincibleJai Yes, it is expected behavior, as it calls the different API calls based on `namespace` is available or not.

Thanks , otherwise it looks good, i can see same metrics in both places

**Comment by karthikjeeyar** [comment]
verified locally, works as expected, fetches the metrics as we type
/lgtm

**Pull request merged**
