### PR TITLE
OCPBUGS-23924: Render TaskRun results even when failed

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

[OCPBUGS-23924](https://issues.redhat.com/browse/OCPBUGS-23924)

**Analysis / Root cause**: 

Render of `TaskRun` results was blocked if failed

**Solution Description**: 

Render results regardless of failure

**Screen shots / Gifs for design review**: 

After:

image

**Unit test coverage report**: 

n/a

**Test setup:**

install pipeline operator and use the pipeline provided in the jira

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

### CODE REVIEW

**Comment by logonoff** [comment]
code review:
/assign @lokanandaprabhu

**Review by vikram-raj — COMMENTED** [review]
/lgtm

**Pull request merged**
