### PR TITLE
Bug 1929243: override normal namespace hiding for pods view in node details

### PR DESCRIPTION
**Pull request by jcaianirh**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1929243

override-namespace

### CODE REVIEW

**Comment by rhamilto** [comment]
/hold

probably want to hide `The namespace column is only shown when in "All projects"` in the columns modal for this context.

**Comment by jcaianirh** [comment]
@rhamilto hid the alert text in the col management modal for the override use case

**Pull request merged**
