### PR TITLE
Bug 1874241: Change git to Git capitalization

### PR DESCRIPTION
**Pull request by jerolimov**
**Fixes**: 
https://issues.redhat.com/browse/ODC-4723
https://bugzilla.redhat.com/show_bug.cgi?id=1874241

**Analysis / Root cause**: 
Typo

**Solution Description**: 
Change capitalization

**Screen shots / Gifs for design review**:
image
image
image

**Unit test coverage report**: 
Unchanged

**Test setup:**
Open the developer perspective and verifies labels on the Add+ page and the Import from Git page.

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by sahil143 — COMMENTED** [review]
@jerolimov Can you please change the `git` -> `Git` in the pipelines as well.
I found a few in PipelineGitOptions.tsx, TriggerBindingSection.tsx, PipelineSecretSection.tsx there might be some more instances where we use git.
you missed one in GitSection.tsx for Alert.

**Comment by jerolimov** [comment]
Good catch @sahil143, updated this strings also

**Review by sahil143 — APPROVED** [review]
/lgtm

**Pull request merged**
