### PR TITLE
CONSOLE-3526: Use MCE cluster proxy for managed cluster alertmanager requests

### PR DESCRIPTION
**Pull request by TheRealJon**
Dependent on [openshift/console-operator#736](https://github.com/openshift/console-operator/pull/736)

### CODE REVIEW

**Comment by TheRealJon** [comment]
Depends on #12360

**Comment by TheRealJon** [comment]
QE Approver
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

**Review by RickJWagner — APPROVED** [review]
lgtm

**Review by opayne1 — COMMENTED** [review]
/label docs-approved

**Comment by TheRealJon** [comment]
/retest

Unrelated flake

**Comment by yapei** [comment]
tested the PR and no issues found following case steps
/label qe-approved

**Comment by TheRealJon** [comment]
Closing this PR. The multicluster feature has been deferred.

**Pull request closed without merging**
