### PR TITLE
[release-4.3] Bug 1829046: removes techpreview badge from serverless

### PR DESCRIPTION
**Pull request by invincibleJai**
This is a cherry-pick of #5164

### CODE REVIEW

**Comment by andrewballantyne** [comment]
@invincibleJai Title needs `Bug <number>:` in order to find the bugzilla.

/lgtm

/assign @rohitkrai03 seems you have approvals in 4.3. I do not, please toss one on here when you get a chance.

**Comment by rohitkrai03** [comment]
@invincibleJai The tests are failing in frontend.

**Comment by andrewballantyne** [comment]
@invincibleJai Would appear you have failures in tests:

> ERROR in /go/src/github.com/openshift/console/frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx
> (5,10): Duplicate identifier 'RadioButtonField'.
> ERROR in /go/src/github.com/openshift/console/frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx
> (5,10): Module '"../../../../../../node_modules/@console/shared/src"' has no exported member 'RadioButtonField'.
> ERROR in /go/src/github.com/openshift/console/frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx
> (5,28): Duplicate identifier 'RadioOption'.
> ERROR in /go/src/github.com/openshift/console/frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx
> (5,28): Module '"../../../../../../node_modules/@console/shared/src"' has no exported member 'RadioOption'.
> ERROR in /go/src/github.com/openshift/console/frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx
> (10,10): Duplicate identifier 'RadioOption'.
> ERROR in /go/src/github.com/openshift/console/frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx
> (11,10): Duplicate identifier 'RadioButtonField'.

**Comment by invincibleJai** [comment]
@rohitkrai03 @andrewballantyne thanks, have updated PTAL

**Pull request merged**
