### PR TITLE
OCPBUGS-33383: Fix Admission webhook warning for Route and BuildConfig creation via import flow

### PR DESCRIPTION
**Pull request by vikram-raj**
Fix: https://issues.redhat.com/browse/OCPBUGS-33383

Descriptions: The unknown field gets added to Route and BuildConfig while creating using the import from git flow. This PR fixes and removes the unknown field from the Route and BuidConfig.

Before: 

https://github.com/openshift/console/assets/2561818/6b8ed418-dc20-4776-9b75-19ea80121c22

After:

https://github.com/openshift/console/assets/2561818/d0e5854f-a7d9-4a49-aaf5-0a843e860419

### CODE REVIEW

**Review by Lucifergene — COMMENTED** [review]
@vikram-raj Found out that creating serverless functions from the create serverless form is also throwing this error. I think you also need to update the Knative stuffs.

image

**Comment by vikram-raj** [comment]
@Lucifergene Updated the PR PTAL. Thanks

**Review by Lucifergene — APPROVED** [review]
/lgtm

**Pull request merged**
