### PR TITLE
OCPBUGS-5346: Change vSphere connection health status icon

### PR DESCRIPTION
**Pull request by mareklibra**

### CODE REVIEW

**Comment by nirfarkas** [comment]
Screenshot? (:

**Comment by mareklibra** [comment]
Screenshots:

**Before:**
Screenshot from 2023-01-05 10-35-50

---

**After:**
Screenshot from 2023-01-05 11-15-34

**Comment by yapei** [comment]
tested the PR, 
- If `vShpere connection configuration` has correct settings and `vShpere Problem Detector` doesn't return any error/warning, then OK icon and message `No error is reported, open for detailed status.` will be shown in Status card
- otherwise, we will show WARN icon with message `vShpere Problem Detector` has returned

/label qe-approved

**Pull request merged**
