### PR TITLE
[release-4.10] OCPBUGS-23310: add support for new features annotations while preserv…

### PR DESCRIPTION
**Pull request by rhamilto**
…ing support for existing infrastructure-features annotation

### CODE REVIEW

**Comment by jhadvig** [comment]
/retest

```
Running:  crud/resource-crud.spec.ts                                                    (12 of 19)
  Kubernetes resource CRUD operations
  Logging in as kubeadmin
    1) "before all" hook for "creates the resource instance"
      delete project
    2) "after all" hook for "creates the resource instance"
  0 passing (39s)
  2 failing
  1) Kubernetes resource CRUD operations
       Pod
         "before all" hook for "creates the resource instance":
     AssertionError: Timed out retrying after 30000ms: Expected to find element: `[data-test="user-dropdown"]`, but never found it.
Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Kubernetes resource CRUD op...`
Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail
      at Object.shouldBeVisible (https://console-openshift-console.apps.ci-op-swrybm58-0887c.xxxxxxxxxxxxxxxxxxxxxx/__cypress/tests?p=tests/crud/resource-crud.spec.ts:49318:14)
      at Context.eval (https://console-openshift-console.apps.ci-op-swrybm58-0887c.xxxxxxxxxxxxxxxxxxxxxx/__cypress/tests?p=tests/crud/resource-crud.spec.ts:48692:75)
  2) Kubernetes resource CRUD operations
       Pod
         "after all" hook for "creates the resource instance":
     CypressError: `cy.click()` failed because it requires a DOM element.
```

**Review by jhadvig — APPROVED** [review]
/lgtm
label backport-risk-assessed

**Comment by rhamilto** [comment]
@yanpzhan, I manually added @XiyunZhao to the assignees since the bot couldn't.

**Pull request merged**
