### PR TITLE
CONSOLE-3568: expose DeleteModal via useDeleteModal hook in @console/shared

### PR DESCRIPTION
**Pull request by rhamilto**
https://github.com/openshift/console/assets/895728/b67a072d-798d-44f9-835a-c8834ecc8fe5

### CODE REVIEW

**Comment by rhamilto** [comment]
This is internal Console code cleanup and has no user-facing impact.

/assign @TheRealJon for code approval
/assign @yanpzhan for QE approval
/label docs-approved
/label px-approved

**Comment by yanpzhan** [comment]
@rhamilto could you pls rebase the pr so that cluster-bot can launch cluster against it?

**Comment by rhamilto** [comment]
> @rhamilto could you pls rebase the pr so that cluster-bot can launch cluster against it?

Done.

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Comment by yanpzhan** [comment]
Did a regression test on the cluster launched against the pr, especially tested about resource deletion, there is no regression issue.
/label qe-approved

**Pull request merged**
