### PR TITLE
[release-4.8] OCPBUGS-4120: Show already loaded catalog items after a timeout (3sec)

### PR DESCRIPTION
**Pull request by jerolimov**
Manual backport of #12136

4.12: https://issues.redhat.com/browse/OCPBUGS-270
4.11: https://issues.redhat.com/browse/OCPBUGS-1523
4.10: https://issues.redhat.com/browse/OCPBUGS-1759
4.9: https://issues.redhat.com/browse/OCPBUGS-2008
4.8: https://issues.redhat.com/browse/OCPBUGS-4120

/kind bug
/cc @invincibleJai @sanketpathak

### CODE REVIEW

**Comment by invincibleJai** [comment]
Verified on bot catalg loads fine, need to validate in dev setup as well once with increasing setTimeout for one of the network calls

image

**Comment by sanketpathak** [comment]
Verified on complete disconnected cluster 
[Screencast from 01-21-2023 10:44:32 AM.webm](https://user-images.githubusercontent.com/10252230/213970565-b8d45fc1-f1ff-4f02-ab2d-7a9ecbaaeef1.webm)
/label cherry-pick-approved

**Pull request merged**
