### PR TITLE
Move Alertmanager link from sidebar to top of monitoring pages

### PR DESCRIPTION
**Pull request by kyoto**
### Before
screenshot-2

### After
screenshot-1

### CODE REVIEW

**Comment by spadgett** [comment]
Should the "Alerts Firing" gauge on the cluster status page go to the in-console Alerts page or still link out to the Alertmanager UI?

https://github.com/openshift/console/blob/master/frontend/public/components/cluster-overview.jsx#L67

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by kyoto** [comment]
@spadgett Yes, I'm planning to change that gauge link to point to the new UI too. That will be a separate PR.

**Comment by spadgett** [comment]
@jhadvig fyi, we've seen this flake a few times:

```
1) Interacting with the create secret forms SSH source secrets : check for edited SSH source secret values
   NoSuchElementError: No element found using locator: by.partialButtonText("Reveal Values")
```

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by kyoto** [comment]
PR #702 changes the Cluster Status page's gauge link to also go to the new UI. @spadgett

**Pull request merged**
