### PR TITLE
OCPBUGS-17913: Typo in the OCP console menu

### PR DESCRIPTION
**Pull request by anilabhabaral**
JIRA: https://issues.redhat.com/browse/OCPBUGS-17913

### CODE REVIEW

**Review by jhadvig — CHANGES_REQUESTED** [review]
please run `make i18n` on the changes

**Comment by anilabhabaral** [comment]
@jhadvig i tried to run `make 18n` on the files but seems like it is not working:

~~~
make i18n devconsole.json        
make: *** No rule to make target `i18n'.  Stop.
~~~

I am getting above output when i run the command  `make 18n`.

Am i missing anything in the above command ?

**Comment by anilabhabaral** [comment]
@jhadvig i made the suggested changes. Also i see all the ci tests passed. Could you please review it ?

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by anilabhabaral** [comment]
Thank you @jhadvig for your help!

**Pull request merged**
