### PR TITLE
OCPBUGS-33487: Fix tsconfig so that VSCode can autocomplete imports correctly

### PR DESCRIPTION
**Pull request by TheRealJon**
This is a nit that has bothered me for a while. Hopefully it improves the developer experience in our repo.

### CODE REVIEW

**Comment by rhamilto** [comment]
Huzzah!

/lgtm

**Comment by jhadvig** [comment]
Looks like the change is is surfacing quite a lot of es-lint errors

**Comment by TheRealJon** [comment]
I'm closing this as it introduces webpack issues that would need to be addressed separately. This change surfaces many import cycle issues that are currently ignored.

**Pull request closed without merging**
