### PR TITLE
Update helm side panel info in developer catalog

### PR DESCRIPTION
**Pull request by rohitkrai03**
**Fixes**: https://issues.redhat.com/browse/ODC-6254

**Analysis / Root cause**: Side panel for helm charts needed to show more information.

**Solution Description**: Updated side panel for helm chart to show information about provider, provider type, repository and update labels for a few of the descriptions.

**Screen shots / Gifs for design review**: @openshift/team-devconsole-ux

https://user-images.githubusercontent.com/6041994/129885917-41677cac-e41d-4e80-ba44-1735ce1d039d.mov

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge

### CODE REVIEW

**Review by serenamarie125 — APPROVED** [review]
@rohitkrai03 this looks great, thanks for these changes!

**Comment by invincibleJai** [comment]
/lgtm
/label qe-approved

verified the changes , works as expected

**Comment by rohitkrai03** [comment]
Propagate from epic:
/label docs-approved
/label px-approved

**Comment by rohitkrai03** [comment]
/hold

E2E tests are failing. Looking into it.

**Pull request merged**
