### PR TITLE
Bug 1966401: Revamp Ceph Table in Install Wizard flow

### PR DESCRIPTION
**Pull request by rexagod**
Changed column CSS to better respond to tablet resolutions.

**Before:**

ss

**After:**

https://user-images.githubusercontent.com/33557095/120274704-d99d9700-c2cd-11eb-9665-f6e2920fdeae.mp4

### CODE REVIEW

**Comment by afreen23** [comment]
@rexagod please update the after and before visuals.

**Comment by rexagod** [comment]
[Done, PTAL.](https://github.com/openshift/console/pull/9087#issue-658643622)

**Comment by rexagod** [comment]
@afreen23 [Done, PTAL.](https://github.com/openshift/console/pull/9087#issue-658643622)

**Pull request merged**
