### PR TITLE
CONSOLE-2361:  remove and replace Bootstrap close styles and consolidate close button code

### PR DESCRIPTION
**Pull request by rhamilto**
I went down a bit of a rabbit hole with this one, but I think it's good code cleanup/consolidation.

Two commits as the first is the removal and replacement and the second is to update the remaining close buttons to use a single component.

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm
/hold
/assign @yapei 
for QE approval

**Comment by spadgett** [comment]
/lgtm cancel
Some unit test failures, but QE should be able to test the change.

**Comment by spadgett** [comment]
This PR has no user visible changes, and we have general docs and px approval for this epic. @ahardin-rh @sferich888 FYI

/label docs-approved
/label px-approved

**Comment by rhamilto** [comment]
Unit tests fixed.  Please retag, @spadgett

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
