### PR TITLE
Allow catalog providers their own types and remove custom from Operator Hub

### PR DESCRIPTION
**Pull request by jcaianirh**
For Story: https://issues.redhat.com/browse/CONSOLE-2159

Haven't installed a custom operator, but tested by removing the Community type to give an example of how it will look using default value (name) without the new annotation.

There is also a sort for the filter that sorts the provider types. As of now, this just sorts the first three types in the order: Red Hat, Certified, Community, Marketplace...after those, the custom names will be listed in alpha sort as shown in the sample image.

sample image:
Screen Shot 2020-03-30 at 1 09 43 PM

### CODE REVIEW

**Comment by andybraren** [comment]
Nice, looking great!

> do we want to sort the dynamically provided types here?

I believe so yes, from @itsptk’s [PR here](https://github.com/openshift/openshift-origin-design/pull/368):

> Ideally **Red Hat**, **Certified**, **Community** and **Marketplace** facets would appear first, with the rest alphabetized after

**Comment by jcaianirh** [comment]
@benjaminapetersen this is ready for review.

**Pull request merged**
