### PR TITLE
migrate perspective extension from static to dynamic

### PR DESCRIPTION
**Pull request by christianvogt**
fixes: https://issues.redhat.com/browse/CONSOLE-2570 https://issues.redhat.com/browse/ODC-6237

Migration of perspective extension from static to dynamic.

No UI changes.

Note that there are 2 test cases disabled in `console-app/src/__tests__/extension-checks/perspectives.spec.ts` because these test cases relied on loading static extensions only.

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [x] Safari
- [x] Edge

cc @rohitkrai03 @spadgett @jamestalton

### CODE REVIEW

**Comment by christianvogt** [comment]
Propagate from epic:
/label docs-approved
/label px-approved

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Comment by rohitkrai03** [comment]
/lgtm cancel

While doing QE testing on a cluster found some issues with `usePerspectiveDetection`.

**Comment by christianvogt** [comment]
Looking into issue right now. 
Reproducible when user settings are initially empty.

**Comment by christianvogt** [comment]
@rohitkrai03 fixed the loading issue. Try deleting the user settings to get back to what it's like to load the console for the first time.

**Pull request merged**
