### PR TITLE
Replace `<DashboardCardHelp>` with `<FieldLevelHelp>`

### PR DESCRIPTION
**Pull request by rhamilto**
Follow on to https://github.com/openshift/console/pull/2714

Important!  
  * These changes are untested as I don't have an easy way to test (although they should be fine given `<FieldLevelHelp>` is a near clone of `<DashboardCardHelp>`).  **Can someone either provide instructions on enabling the affected dashboard and plugins or test for me?**
  * There is a functional difference from `<DashboardCardHelp>` in that `<FieldLevelHelp>`'s `<Popover>` does not include `appendTo={() => document.getElementById('content-scrollable')}`.  The result is the popover can overlay the masthead; however, `enableFlip` now works correctly so the popover positions correctly when the popover is near the top of the viewport.

Mock example:
Screen Shot 2019-09-26 at 3 38 01 PM
Screen Shot 2019-09-26 at 3 38 05 PM

cc: @matthewcarleton, @mceledonia

### CODE REVIEW

**Comment by matthewcarleton** [comment]
Thanks @rhamilto

**Comment by rawagner** [comment]
tested and it works but overlap with masthead is still ugly even with `enableFlip`

help_popup

Could we update `FieldLevelHelp` with `appendTo={() => document.getElementById('content-scrollable')}` and maybe make the `elementId` configurable ?

**Comment by spadgett** [comment]
/assign @cloudbehl 
Can you help us test since we don't have an environment?

**Comment by spadgett** [comment]
> Could we update FieldLevelHelp with appendTo={() => document.getElementById('content-scrollable')} and maybe make the elementId configurable ?

Won't this mean the popover doesn't scroll with the content? Is that really better? (Neither seems great.)

**Comment by rawagner** [comment]
> > Could we update FieldLevelHelp with appendTo={() => document.getElementById('content-scrollable')} and maybe make the elementId configurable ?
> 
> Won't this mean the popover doesn't scroll with the content? Is that really better? (Neither seems great.)

it scrolls with the element that is defined by `appendTo`. Which in our case it usually is `'content-scrollable` and if it's something else, we could allow overriding it via props.

**Comment by rhamilto** [comment]
The popover scrolls with and without `appendTo`.  The difference lies in whether the popover overlays the masthead.  IMO, it is better for the popover to overlay the masthead in order to avoid the situation where popover contents can be clipped by the masthead when the popover is close to the the masthead.  

Popover contents clipped by masthead
Screen Shot 2019-09-27 at 9 21 38 AM
Popover contents overlay masthead
Screen Shot 2019-09-27 at 9 22 05 AM

Using `appendTo` here recreates the clipping problem that plagues our current dropdown component (and we've battled numerous bugs about in the various console implementations).

**Pull request merged**
