### PR TITLE
ClusterServiceVersion Views Cleanup

### PR DESCRIPTION
**Pull request by alecmerdler**
### Description

General updates and fixes for the views for `ClusterServiceVersion`.

### Changes

- Fixed flash on `ClusterServiceVersion` detail view nav title
- Replaced old "apps" icon with new "operator" icon
- Remove unused dropdown filters
- Add "Deployment" column with link to Operator's deployment

### Screenshots

**List view:**
screenshot_20180830_140933

Fixes https://jira.coreos.com/browse/ALM-682
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1617161
Fixes https://jira.coreos.com/browse/ALM-697

### CODE REVIEW

**Comment by alecmerdler** [comment]
jenkins rebuild

**Comment by alecmerdler** [comment]
jenkins push

**Comment by coreos-ui** [comment]
The PR image failed.

**Comment by alecmerdler** [comment]
jenkins push

**Comment by coreos-ui** [comment]
The PR image has been pushed to Quay with tag `pr_478_build_419`

**Comment by spadgett** [comment]
@alecmerdler Is this going to conflict with the refactoring in master-next?

**Comment by dtaylor113** [comment]
Might have some merge conflicts with #468

**Pull request merged**
