### PR TITLE
fix source image test

### PR DESCRIPTION
**Pull request by avivtur**
Signed-off-by: Aviv Turgeman <aturgema@redhat.com>

### CODE REVIEW

**Comment by yaacov** [comment]
cc:// @gouyang

**Comment by gouyang** [comment]
One failure I noticed in other PR about source-image test maybe caused by timeout issue in view/virtualization.ts:
```
    testSource: (templateName: string, sourceStatus: string, timeout = 600000) =>
      getRow(templateName, () =>
        cy.byTestID('template-source', { timeout }).should('have.text', sourceStatus),
```
It doesn't specify the value of the timeout in the last line, so it gets default value which is defaultCommandTimeout(60000ms) not the one from the parameter `600,000ms`.

**Pull request merged**
