### PR TITLE
Update topology to Patternfly topology package containing updates and styles.

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Jira: https://issues.redhat.com/browse/ODC-6626

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
Requires https://github.com/openshift/console/pull/11261

**Comment by jeff-phillips-18** [comment]
@invincibleJai @jerolimov Patternfly updated. Ready for review.

**Review by jerolimov — APPROVED** [review]
From what I have seen this works and looks fine. I would like to get also the input from Vikram and Karthik as they found bugs before

And Sanket, can you run more automation tests against this PR?

/cc @vikram-raj @karthikjeeyar @sanketpathak

**Comment by karthikjeeyar** [comment]
Topology crashes when I use filter by resource on serverless workloads. I have used two ping sources and connected it to a KSVC, and used the filter by resource dropdown it crashes with NPE.

**Comment by karthikjeeyar** [comment]
By clicking on reset, two KVSC's get stacked upon one another

https://user-images.githubusercontent.com/9964343/165523237-237d20f8-217a-462e-9177-6c3bbf7deb71.mov

**Comment by karthikjeeyar** [comment]
Cursor pointer style flickering between `pointer` and `not-allowed` values.

https://user-images.githubusercontent.com/9964343/165533969-58c0d304-9806-4afb-a610-02ffda0d891f.mov

**Comment by jeff-phillips-18** [comment]
> Cursor pointer style flickering between `pointer` and `not-allowed` values.

This will be fixed in an upcoming PF release. Can we log a separate issue?

**Comment by jeff-phillips-18** [comment]
@karthikjeeyar fixed the crash and the flickering

**Comment by karthikjeeyar** [comment]
I have verified with various workloads, its is not crashing or flickering anymore.

Few other observations:
@jeff-phillips-18 The boundary of the application group with two different shapes (circle + polygon) is different from what we currently have, is it expected?

before:
image
After:
Screenshot 2022-04-28 at 6 39 49 PM

image

**Comment by karthikjeeyar** [comment]
Not able to drag an Edge connected between channel and KSVC, on dragging it moves the entire visualisation.

https://user-images.githubusercontent.com/9964343/165773732-3556ea74-8a8b-403d-a87e-be4988e55bac.mov

**Comment by jeff-phillips-18** [comment]
> The boundary of the application group with two different shapes (circle + polygon) is different from what we currently have, is it expected?

Unexpected. Kinda cool, but wrong and unexpected 😄

**Comment by jeff-phillips-18** [comment]
@karthikjeeyar Addressed those issues.

**Comment by karthikjeeyar** [comment]
/label qe-approved

propagating other labels based on the acks from epic https://issues.redhat.com/browse/ODC-6626
/label docs-approved
/label px-approved

**Pull request merged**
