### PR TITLE
ODC-7310: Bump openshift/api to latest, k8s api to 0.27.3 and go to 1.20

### PR DESCRIPTION
**Pull request by jerolimov**
Updates:

* github.com/openshift/api from **2022-08-03** to **2023-07-13**, incl.:
  * https://github.com/openshift/api/pull/1424, see [STOR-1263](https://issues.redhat.com//browse/STOR-1263)

Executed

```
go get -u -t k8s.io/api@v0.27.3 && \
go get -u -t k8s.io/apiextensions-apiserver@v0.27.3 && \
go get -u -t k8s.io/apimachinery@v0.27.3 && \
go get -u -t k8s.io/client-go@v0.27.3 && \
go get -u -t k8s.io/component-base@v0.27.3 && \
go mod tidy && \
go mod vendor
```

Required as well:

```
go get -u -t github.com/openshift/library-go/pkg/serviceability@v0.0.0-20230622115850-9596e367bcb4 && \
go get -u -t k8s.io/kube-openapi@v0.0.0-20230501164219-8b0f38b5fd1f && \
go get k8s.io/kube-openapi/pkg/validation/strfmt@v0.0.0-20230501164219-8b0f38b5fd1f && \
go mod tidy && \
go mod vendor
```

### CODE REVIEW

**Review by jhadvig — COMMENTED** [review]
Lets also update golang the Dockerfile and Dockerfile.product PR looks good.

**Comment by jerolimov** [comment]
(chore) it's just a dependency update.

/label docs-approved
/abel px-approved

@sanketpathak, can you start a cluster and verify that the major features like operator installation, helm, and devfiles still work? for qe-approved

/cc @sanketpathak

**Pull request closed without merging**
