### PR TITLE
[release-4.13] OCPBUGS-15890: Use proxy with web socket connection and monitoring dashboard

### PR DESCRIPTION
**Pull request by TheRealJon**
Manual cherry-pick of #12877

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by TheRealJon** [comment]
@yanpzhan Could you take a look at this and approve?

/assign @yanpzhan

**Comment by cblecker** [comment]
looks like network timeouts? trying again
/retest-required

**Pull request merged**
