### PR TITLE
Bug 1760497: Update available channels for 4.2

### PR DESCRIPTION
**Pull request by spadgett**
Cluster Settings · OKD 2019-10-10 12-54-08

/assign @smarterclayton 
cc @bparees @cuppett

### CODE REVIEW

**Comment by wking** [comment]
I manually linked this PR from https://bugzilla.redhat.com/show_bug.cgi?id=1760497 , because I doubt we are going to wait until the master/4.3 bug gets VERIFIED to make the Bugzilla bot happy.

**Comment by smarterclayton** [comment]
This is approved for 4.2.0 to provide the proper experience at GA.

**Comment by spadgett** [comment]
> StaleElementReferenceError: stale element reference: element is not attached to the page document

known olm test flake

/retest

**Pull request merged**
