### PR TITLE
Switch to multi stage builds in the Dockerfile

### PR DESCRIPTION
**Pull request by spadgett**
Use multi stage builds for origin releases.

### CODE REVIEW

**Comment by spadgett** [comment]
jenkins push

**Comment by coreos-ui** [comment]
The PR image has been pushed to Quay with tag `pr_153_build_389`

**Comment by spadgett** [comment]
@smarterclayton @stevekuznetsov This adds back the multi stage build to our repo. Let me know what I need to do to add an image push job

**Pull request merged**
