### PR TITLE
OU-59: Query browser: Remove the metrics list dropdown

### PR DESCRIPTION
**Pull request by kyoto**
The metrics dropdown list provided a useful way to search for available
metrics. However, the query input field now has autocompletion of
metrics names, which allows for discovering metrics. The dropdown list
is therefore basically redundant and is being removed.

Also removed the now unused `queryBrowserInsertText` Redux action.

| Before | After |
| - | - |
| screenshot | after |

### CODE REVIEW

**Comment by kyoto** [comment]
/cc @RickJWagner 
For PX approval

**Review by RickJWagner — APPROVED** [review]
Less code is better, nice change.
Thanks also for the pictures describing the change in the comments section of this PR.  That gives reviewers like me a huge headstart.
Approved.

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by Tai-RedHat** [comment]
test PR with cluster-bot, check on metrics page: the drop-down list is removed, no other regression issues.
/label qe-approved

**Comment by lihongyan1** [comment]
metrics dropdown is useful and keep it from the following historical discussion, not sure why remove it again? 
https://github.com/openshift/console/pull/11143#issuecomment-1096381845
https://github.com/openshift/console/pull/11143#issuecomment-1103024433
CC: @Nexucis @thile01
The metrics dropdown is improved not long ago.
https://github.com/openshift/console/pull/11555
cc:@jgbernalp

No special reason, suppose we'd better keep it.

**Comment by kyoto** [comment]
For reference, here's what the autocompletion looks like.
screenshot

I believe the one advantage of the Metrics dropdown was that you could list all available metrics at once. With the query input you need to start typing before you see suggestions.

However, I think the Metrics dropdown has some problems
- Inferior UX compared to the query input
- Causes an additional PromQL query every time the page is loaded
- Uses components that are not available in the dynamic plugin SDK, so will require extra work to migrate

So, despite the fact that we lose the ability to see all metrics in a single list, I still see removing this as a step towards better overall UX.

FYI @jgbernalp, @vmartini01, @andrew-ronaldson

**Pull request merged**
