### PR TITLE
[CONSOLE-2494] Update Dockerfile.product for nodejs v14.15.0

### PR DESCRIPTION
**Pull request by yselkowitz**
**Fixes**: 
https://issues.redhat.com/browse/CONSOLE-2494

### CODE REVIEW

**Review by zherman0 — APPROVED** [review]

**Comment by zherman0** [comment]
Should we bump the yarn version as well once https://github.com/openshift/console/pull/7280 merges (updates yarn to 1.22.10).  It would not need to be in this PR, we could open another one.

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
Thank you @yselkowitz 👍

**Pull request merged**
