### PR TITLE
CONSOLE-2527: Add translations from Sprint 197

### PR DESCRIPTION
**Pull request by rebeccaalpert**
This includes Japanese, Simplified Chinese, and Korean.

I went through the files looking for English strings with bad grammar and inconsistencies in the translation files.

All changes related to English file issues are in commit #2. I haven't made any changes to reflect the inconsistencies in the translation files (see below).

### Chinese: 
1. frontend/public/locales/zh/details-page.json
  * "Edit annotations": "编辑注解" was changed to “Edit annotations": "Pod 注解", (this is not correct and we’ve brought this up before with translation. We've manually edited it before, but it will be overwritten until it's changed in Memsource.)
  * Many plurals were not changed at all - was this intentional?
      - "ServiceClasses": "ServiceClasses",
      - "ServicePlans": "ServicePlans",
      - "ServiceBindings": "ServiceBindings",
      - "MachineConfigs": "MachineConfigs",

2. frontend/packages/knative-plugin/locales/zh/knative-plugin.json 
  * Sink is capitalized inconsistently in translations - should it be consistent?
3. frontend/packages/dev-console/locales/zh/devconsole.json
  * “Dockerfile” was changed to “Docker” in the translation. It should be “Dockerfile;" It’s “Dockerfile elsewhere in the translation file.
4. frontend/packages/console-app/locales/zh/nodes.json
  * "Mark as unschedulable": "将节点标记为不可调度。", - Period needs removal in Memsource (we've discussed this before and removed the period on our end before. This will keep getting overwritten unless it's changed in Memsource.)
5. frontend/public/locales/zh/modal.json 
  * "Edit annotations": "编辑注解" was changed to “Edit annotations": "Pod 注解", (this is not correct and we’ve brought this up before with translation. We've manually edited it before, but it will be overwritten until it's changed in Memsource.)
6. frontend/public/locales/zh/public.json
  * "Home": "主页" was changed to "Home": "家", - Translation had said to use the former and we'd manually updated our files; this needs to be changed in Memsource or it will continue to get overwritten.
  * Pod is inconsistently capitalized (could be an "us" issue): "No Pods found for this resource.": "没有找到此资源的 Pod。", vs  "Hide waiting pods with errors": "隐藏有错误的等待的 pod",
  * Plural ResourceKinds have not been changed at all - was this intentional?
      - "DaemonSets": "DaemonSets",
      - "ResourceQuotas": "ResourceQuotas",
      - "StatefulSets": "StatefulSets",
      - "ConfigMaps": "ConfigMaps",
      -  "CronJobs": "CronJobs",
      - "HorizontalPodAutoscalers": "HorizontalPodAutoscalers",
      - "NetworkPolicies": "NetworkPolicies",
      -  "PersistentVolumes": "PersistentVolumes",
      - "PersistentVolumeClaims": "PersistentVolumeClaims",
      - "StorageClasses": "StorageClasses",
      - "VolumeSnapshots": "VolumeSnapshots",
      - "VolumeSnapshotClasses": "VolumeSnapshotClasses”,
      - “ImageStreams": "ImageStreams",
      - "MachineAutoscalers": "MachineAutoscalers",
      - "MachineHealthChecks": "MachineHealthChecks",
      - "MachineConfigs": "MachineConfigs",
      - "MachineConfigPools": "MachineConfigPools",
      - "LimitRanges": "LimitRanges",
      - "CustomResourceDefinitions": "CustomResourceDefinitions",
      - "Prometheuses": "Prometheuses",
      - "ServiceMonitors": "ServiceMonitors",
      - "Alertmanagers": "Alertmanagers",
      - "Reports": "Reports",
      - "ReportQueries": "ReportQueries",
      - "ImageStreamTags": "ImageStreamTags",
      - "ImageStreamImports": "ImageStreamImports",
      - "CertificateSigningRequests": "CertificateSigningRequests”,
      - “ComponentStatuses": "ComponentStatuses",
      - "ProjectRequests": "ProjectRequests",
      -  "ClusterRoleBindings": "ClusterRoleBindings",
      - "ClusterRoles": "ClusterRoles",
      - "SelfSubjectAccessReviews": "SelfSubjectAccessReviews",
      - "ResourceAccessReviews": "ResourceAccessReviews",
      - "LocalResourceAccessReviews": "LocalResourceAccessReviews",
      - "Petsets": "Petsets",
      - "ClusterResourceQuotas": "ClusterResourceQuotas",
      - "ClusterServiceBrokers": "ClusterServiceBrokers",
      -  "ClusterServiceClasses": "ClusterServiceClasses",
      -  "ClusterServicePlans": "ClusterServicePlans",
      - "ServiceInstances": "ServiceInstances",
      - "ServiceBindings": "ServiceBindings",
      - "APIServices": "APIServices",
      - "MachineDeployments": "MachineDeployments",
      - "ClusterOperators": "ClusterOperators",
      -  "ClusterVersions": "ClusterVersions",
      - "CSIDrivers": "CSIDrivers",
      - "ClusterAutoscalers": "ClusterAutoscalers",
      - "OAuths": "OAuths",
      - "ConsoleLinks": "ConsoleLinks",
      - "ConsoleCLIDownloads": "ConsoleCLIDownloads",
      - "ConsoleNotifications": "ConsoleNotifications",
      - "ConsoleExternalLogLinks": "ConsoleExternalLogLinks",
      - "ConsoleYAMLSamples": "ConsoleYAMLSamples",
      - "VolumeSnapshotContents": "VolumeSnapshotContents",

### Korean:
1. frontend/packages/console-app/locales/ko/nodes.json 
   * "External ID": "외부 IP", - ID was changed to IP; this seems like it may be a typo?
2. frontend/packages/dev-console/locales/ko/devconsole.json
  * "Developer": "개발자" was changed to "Developer": "Developer", - we had discussed this and the translator for Korean had told us to change it to 개발자; it seems like this was not updated in Memsource.
3. frontend/packages/pipelines-plugin/locales/ko/pipelines-plugin.json 
  * "Select a Project to view the list of Pipelines or <2>create a Project</2>.": "파이프 라인 목록을 보려면 프로젝트를 선택하십시오.", - the translation is missing the brackets used to generate the "create a Project" link.
4. frontend/public/locales/ko/search.json
  * "Add to navigation": "검색에 추가합니다.", - shouldn’t have period in translation (net new)
5. frontend/public/locales/ko/public.json
* Pod is capitalized inconsistently, but this could be an "us" issue: (No Pods found for this resource.": "이 리소스에 대한 Pod가 없습니다." vs. "Hide waiting pods with errors": "오류가 있는 pod 대기 창 숨기기"
*   Many plurals were not changed at all - was this intentional? Examples:

   - "DaemonSets": "DaemonSets",
   - "ResourceQuotas": "ResourceQuotas",
   - "DeploymentConfigs": "DeploymentConfigs",
   - "StatefulSets": "StatefulSets",
   - "ConfigMaps": "ConfigMaps",
   - "CronJobs": "CronJobs",
   - "ReplicaSets": "ReplicaSets",
   - "ReplicationControllers": "ReplicationControllers",
   - "HorizontalPodAutoscalers": "HorizontalPodAutoscalers",
   - "NetworkPolicies": "NetworkPolicies",
   - "PersistentVolumes": "PersistentVolumes",
   - "PersistentVolumeClaims": "PersistentVolumeClaims",
   - "StorageClasses": "StorageClasses",
   - "VolumeSnapshots": "VolumeSnapshots",
   - "VolumeSnapshotClasses": "VolumeSnapshotClasses",
   - "BuildConfigs": "BuildConfigs",
   - "ImageStreams": "ImageStreams",
   - "MachineSets": "MachineSets",
   - "MachineAutoscalers": "MachineAutoscalers",
   - "MachineHealthChecks": "MachineHealthChecks",
   - "MachineConfigs": "MachineConfigs",
   - "MachineConfigPools": "MachineConfigPools",
   - "ServiceAccounts": "ServiceAccounts",
   - "LimitRanges": "LimitRanges",
   - "CustomResourceDefinitions": "CustomResourceDefinitions",
   - "Prometheuses": "Prometheuses",
   - "ServiceMonitors": "ServiceMonitors",
   - "Alertmanagers": "Alertmanagers",
   - "Reports": "Reports",
   - "ReportQueries": "ReportQueries",
   - "ImageStreamTags": "ImageStreamTags",
   - "ImageStreamImports": "ImageStreamImports",
   - "CertificateSigningRequests": "CertificateSigningRequests",
   - "ComponentStatuses": "ComponentStatuses",
   - "ProjectRequests": "ProjectRequests",
   - "ClusterRoleBindings": "ClusterRoleBindings",
   - "ClusterRoles": "ClusterRoles",
   - "SelfSubjectAccessReviews": "SelfSubjectAccessReviews",
   - "ResourceAccessReviews": "ResourceAccessReviews",
   - "LocalResourceAccessReviews": "LocalResourceAccessReviews",
   - "Petsets": "Petsets",
   - "ClusterResourceQuotas": "ClusterResourceQuotas",
   - "ClusterServiceBrokers": "ClusterServiceBrokers",
   - "ClusterServiceClasses": "ClusterServiceClasses",
   - "ClusterServicePlans": "ClusterServicePlans",
   - "ServiceInstances": "ServiceInstances",
   - "ServiceBindings": "ServiceBindings",
   - "APIServices": "APIServices",
   - "MachineDeployments": "MachineDeployments",
   - "ClusterOperators": "ClusterOperators",
   - "ClusterVersions": "ClusterVersions",
   - "CSIDrivers": "CSIDrivers",
   - "ClusterAutoscalers": "ClusterAutoscalers",
   - "OAuths": "OAuths",
   - "ConsoleLinks": "ConsoleLinks",
   - "ConsoleNotifications": "ConsoleNotifications",
   - "ConsoleExternalLogLinks": "ConsoleExternalLogLinks",
   - "ConsoleYAMLSamples": "ConsoleYAMLSamples",
   - "VolumeSnapshotContents": "VolumeSnapshotContents",

### Japanese:
1. frontend/packages/console-app/locales/ja/tour.json
  * “Okay, got it!” Is in English now - changed from Japanese; not sure if that's intentional
2. frontend/packages/console-shared/locales/ja/console-shared.json 
  * Pod is inconsistently uppercase vs. lowercase (could be an "us" issue): “Pod": "Pod", while “Pods”: “pod” and "to {{count}} Pod_0": "対象: {{count}} Pod"
3. frontend/public/locales/ja/ingress.json
  * "Ingresses": "Ingress" was changed to  "Ingresses": "Ingresses" - was this intentional?
4. frontend/public/locales/ja/machine-autoscalers.json
  * "MachineAutoscaler details": "Machine Autoscaler の詳細" was changed to "MachineAutoscaler details": "MachineAutoscaler details." This is inconsistent with other translations; was this intentional?
5. frontend/public/locales/ja/public.json
 * A couple of singular items are translated while the plural is not:

    - "ResourceAccessReview": "リソースアクセスのレビュー",
     - "ResourceAccessReviews": "ResourceAccessReviews",
     - "ReportQuery": "レポートクエリー",
     - "ReportQueries": "ReportQuery",

* Pod capitalization is inconsistent and many plurals were not updated; not sure if that was intentional.
    - "ResourceQuotas": "ResourceQuotas",
     - “CronJobs": "CronJobs",
     - "HorizontalPodAutoscalers": "HorizontalPodAutoscalers",
     - Ingresses": "Ingresses",
     - "PersistentVolumeClaims": "PersistentVolumeClaims",
     - "VolumeSnapshotClasses": "VolumeSnapshotClasses",
     - "BuildConfigs": "BuildConfigs",
     - "ImageStreams": "ImageStreams",
     - "MachineAutoscalers": "MachineAutoscalers",
     - "CustomResourceDefinitions": "CustomResourceDefinitions",
     - "Prometheuses": "Prometheuses",
     - "Alertmanager": "Alertmanager 0.14.0",
     - "ImageStreamTags": "ImageStreamTags",
     - "ImageStreamImports": "ImageStreamImports",
     - "CertificateSigningRequests": "CertificateSigningRequests",
     - "ComponentStatuses": "ComponentStatuses",
     - "ClusterRoleBindings": "ClusterRoleBindings",
     - "ClusterRoles": "ClusterRoles",
     - "ClusterResourceQuotas": "ClusterResourceQuotas",
     - "ClusterServiceBrokers": "ClusterServiceBrokers",
     - “ClusterServiceClasses": "ClusterServiceClasses",
     - "ClusterServicePlans": "ClusterServicePlans",
     - "MachineDeployments": "MachineDeployments",
     - "ClusterAutoscalers": "ClusterAutoscalers",
     - "ConsoleLinks": "ConsoleLinks",
     - "ConsoleExternalLogLinks": "ConsoleExternalLogLinks",
     - "VolumeSnapshotContents": "VolumeSnapshotContents",

### CODE REVIEW

**Comment by rebeccaalpert** [comment]
CC @spadgett @rh-tchuang @kyoto

**Comment by rebeccaalpert** [comment]
I manually updated many of the translation inconsistencies in commit #3. I didn't address plurals, the missing tag issue in the Korean translation of pipelines-plugin, the "Okay, got it!" change, or inconsistent capitalization (not sure if capitalization stuff is worth approaching). Will reach out to Terry's team on remaining non-capitalization related items.

**Review by spadgett — APPROVED** [review]
/lgtm
/hold for approvals
/assign @yapei @ahardin-rh @sferich888

**Comment by spadgett** [comment]
@rebeccaalpert You'll need to rebase.

@sferich888 PTAL, thanks!

**Comment by spadgett** [comment]
@jelkosz Do you know who can help us troubleshoot the kubevirt tests? It looks like the failure is unrelated to the PR:

> error: timed out waiting for the condition on kubevirts/kubevirt

**Pull request merged**
