### PR TITLE
[release-4.15] OCPBUGS-32399: Update devfile library to v2.2.2

### PR DESCRIPTION
**Pull request by maysunfaisal**
Backport of https://github.com/openshift/console/pull/13045

### CODE REVIEW

**Review by Lucifergene — COMMENTED** [review]
/lgtm

**Comment by sanketpathak** [comment]
Tested on cluster bot, devfile creation is working fine
Screenshot 2024-04-17 at 7 33 21 PM


/label qe-approved
/label cherry-pick-approved

**Comment by jerolimov** [comment]
/retitle [release-4.15] OCPBUGS-32399: Update devfile library to v2.2.2

**Review by jerolimov — APPROVED** [review]
/approve

**Pull request merged**
