### PR TITLE
Bug 1769395:  Add additional ConsoleLink examples

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1769395

localhost_9000_k8s_cluster_console openshift io_v1_ConsoleLink_example-application-menu

### CODE REVIEW

**Comment by rhamilto** [comment]
Words are hard.  `description`s could use some wordsmithing.

**Comment by spadgett** [comment]
@ahardin-rh FYI, we're adding more link samples directly to the console YAML editor

**Pull request merged**
