### PR TITLE
Bug 1796664: Change link to external link

### PR DESCRIPTION
**Pull request by rebeccaalpert**
Changed Marketplace link in Operator details modal to external link.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1796664.

### CODE REVIEW

**Comment by rhamilto** [comment]
Please add a screenshot.  I'm pretty sure this is going to result in two external link icons.

**Comment by rebeccaalpert** [comment]
Nah, looks ok to me.

Screen Shot 2020-02-05 at 1 41 13 PM

**Comment by rhamilto** [comment]
So it looks like the `.pf-c-button::after` styles are overriding the `.co-external-link:after` styles preventing a double icon.

Screen Shot 2020-02-05 at 1 43 17 PM  

We should probably look at fixing this in a follow on so they are compatible.

/approve
/lgtm

**Comment by rhamilto** [comment]
/lgtm cancel

please squash.

**Comment by rebeccaalpert** [comment]
Squashed.

**Pull request merged**
