### PR TITLE
OU-175: Monitoring: Add "Silences" tab to Developer console

### PR DESCRIPTION
**Pull request by kyoto**
Adds the ability to view, create, edit and expire silences to the Developer console. These pages have the same behaviour as in the Administrator console, except they have the Project selector. Silences are filtered to those from the current namespace and when creating a silence, a `namespace` label matching the current project is automatically added.

Also fixes the props types for `SilencesPage` and `AlertsPage`.

Also removes the unused `Rules` type.

To use the Silences tab in the Developer console, you must have both the `cluster-monitoring-view` and `monitoring-rules-edit` roles for the current namespace. This is the same requirement as for the existing "Alerts" tab (see https://docs.openshift.com/container-platform/4.13/monitoring/managing-alerts.html#silencing-alerts_managing-alerts).

## Silences List
list

## Silence Details
details

## Edit Silence
edit

### CODE REVIEW

**Comment by kyoto** [comment]
/cc @RickJWagner
For PX approval

/cc @opayne1
For docs approval

**Comment by kyoto** [comment]
/cc @juzhao
For QE

**Comment by kyoto** [comment]
Added a second commit for adding the ability to bulk expire silences. The functionality already exists in the Admin console, so this commit copies the relevant code from https://github.com/openshift/monitoring-plugin.

**Comment by juzhao** [comment]
tested with kubeadmin user on dev console, no issue, user with admin role(not cluster-admin) can not show "Observe -> Alerts" tab on dev console, https://issues.redhat.com/browse/OCPBUGS-16740, not related to this PR, 
add /label qe-approved

**Review by RickJWagner — COMMENTED** [review]
Looks good.

**Pull request merged**
