### PR TITLE
Add max values (quota limits) to project utilization card

### PR DESCRIPTION
**Pull request by rawagner**
util_quotas

with https://github.com/openshift/console/pull/3166 applied you also get `<number> available` under resource

util_quota_avail

### CODE REVIEW

**Comment by spadgett** [comment]
@rawagner do you have a screenshot?

**Comment by rawagner** [comment]
@spadgett sure, screenshots added

**Comment by rawagner** [comment]
What Im not sure about is what happens when you have multiple quotas defined for namespace ? Which is actually considered ?

**Comment by spadgett** [comment]
This is really confusing because the usage number is *not* the value that counts against quota. We're conflating two different things.

This also ignores quota scopes, multiple quotas, and requests. I don't think it can be boiled down to one number like this.

**Comment by rawagner** [comment]
/hold

yea, you're right. Usage number is from prometheus and resource quota has its own in `status` and the rest of course too.

@andybraren

**Comment by spadgett** [comment]
> What Im not sure about is what happens when you have multiple quotas defined for namespace ? Which is actually considered ?

They're all considered. Quotas can have scopes that cover certain kinds of workloads. The way to know how much of the quota is in use if by looking at the `status` for that quota.

**Comment by andybraren** [comment]
Agreed, I talked with @cshinn about this a bit more and it sounds like only the Pod limit shown here is an accurate representation - the limits shown in the other rows should be dropped.

**Comment by spadgett** [comment]
It's odd we're calling out pod quota counts specifically since many other resources can be quoted.

Would it make more sense to show object count quotas on the inventory card?

**Pull request closed without merging**
