### PR TITLE
Bug 1641976 - Correctly set destination CA certificate in create route form

### PR DESCRIPTION
**Pull request by spadgett**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1641976

/assign @rhamilto

### CODE REVIEW

**Comment by rhamilto** [comment]
Typing is hard.  Thanks for the fix, @spadgett.

/lgtm

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
