### PR TITLE
OU-218: Monitoring: Use `useResolvedExtensions` instead of `useExtensions`

### PR DESCRIPTION
**Pull request by kyoto**
Prefer `useResolvedExtensions` because it is available in the dynamic plugin SDK.

### CODE REVIEW

**Comment by kyoto** [comment]
This is a refactoring change. There should be no user visible changes.

/label px-approved
/label docs-approved

**Comment by Tai-RedHat** [comment]
test PR with cluster-bot, monitoring console function is working fine,  no other regression problems.
/label qe-approved

**Pull request merged**
