### PR TITLE
Remove declaration for DashboardOverviewUtilizationItem from all sdks

### PR DESCRIPTION
**Pull request by bipuladh**
/assign @rhamilto @spadgett

### CODE REVIEW

**Comment by bipuladh** [comment]
/hold
Waiting for new master to open up.

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by rhamilto** [comment]
/hold cancel

now that master is open for 4.9

**Comment by rhamilto** [comment]
@bipuladh please rebase.

**Comment by bipuladh** [comment]
@rhamilto PTAL

**Pull request merged**
