### PR TITLE
CRUD tests: wait for rows before typing in search input

### PR DESCRIPTION
**Pull request by spadgett**

### CODE REVIEW

**Comment by spadgett** [comment]
:(

```
could not wait for build: the build console failed with reason DockerBuildFailed: Docker build strategy has failed.

info There appears to be trouble with your network connection. Retrying...
error An unexpected error occurred: "https://registry.yarn...nfly/react-icons/-/react-icons-2.9.5.tgz: ESOCKETTIMEDOUT".
info If you think this is a bug, please open a bug report .../src/github.com/openshift/console/frontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error: build error: running './build.sh' failed with exit code 1
```

**Comment by ingvagabund** [comment]
Do you need approve label as well? Or, is lgtm sufficient?

**Comment by spadgett** [comment]
lgtm is sufficient

**Pull request merged**
