### PR TITLE
Bug 2071904: Translate Extensions On Each Language Change

### PR DESCRIPTION
**Pull request by andrewballantyne**
Cherrypick combination of #11278 & #11305.

/cc @jerolimov @vojtechszocs

### CODE REVIEW

**Comment by andrewballantyne** [comment]
/cherry-pick release-4.9

The bug was exposed in 4.9... we'll want to backport this one more time

**Comment by andrewballantyne** [comment]
/hold

Holding to investigate some performance issues that @yanpzhan has found during testing the 4.11 fix.

**Comment by andrewballantyne** [comment]
/unhold

Turns out it was a network slowness... hard to reproduce with a more stable connection. Unholding.

**Review by jerolimov — APPROVED** [review]
Change looks fine to me, it merges both mentioned PR fine.

Tested it locally and it works fine. Don't see any issue not-translated issues.

/lgtm

**Comment by jerolimov** [comment]
> /hold
> 
> Holding to investigate some performance issues that @yanpzhan has found during testing the 4.11 fix.

Looks a little bit strange if you change the translation in one tab and check another tab. Sometimes the 2nd tab get translated, but not always. But it looks like an old issue.

**Comment by andrewballantyne** [comment]
> Looks a little bit strange if you change the translation in one tab and check another tab. Sometimes the 2nd tab get translated, but not always. But it looks like an old issue.

@jerolimov Did you test with ConfigMap saving or with localStorage saving of the language value?

**Comment by jerolimov** [comment]
> > Looks a little bit strange if you change the translation in one tab and check another tab. Sometimes the 2nd tab get translated, but not always. But it looks like an old issue.
> 
> @jerolimov Did you test with ConfigMap saving or with localStorage saving of the language value?

Always ConfigMap

**Comment by andrewballantyne** [comment]
Hmmm, I'm not seeing the slowness... and it's possible it has to do with the watch on the ConfigMap and how it kicks through the websocket. As long as it doesn't require a refresh, I think we are fine.

**Comment by spadgett** [comment]
> /label qe-approved

/label cherry-pick-approved

Adding cherry-pick-approved as QE has already tested the fix, see https://bugzilla.redhat.com/show_bug.cgi?id=2071904#c6

**Pull request merged**
