### PR TITLE
[release-4.8]Bug 2004086: Add name field in edit deployment form

### PR DESCRIPTION
**Pull request by divyanshiGupta**
This PR is a manual cherry-pick of https://github.com/openshift/console/pull/9911

### CODE REVIEW

**Review by rohitkrai03 — APPROVED** [review]
/lgtm
/approve

**Comment by sanketpathak** [comment]
Verified on a cluster using cluster-bot
Screenshot from 2022-01-21 15-14-23

/label cherry-pick-approved

**Pull request merged**
