### PR TITLE
CONSOLE-3188: Add alert with message for Console plugins page when console operator spec.managementState is Unmanaged

### PR DESCRIPTION
**Pull request by sg00dwin**

### CODE REVIEW

**Comment by sg00dwin** [comment]
QE Approver:
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

LGTM Approver:
/assign @zherman0

**Comment by yapei** [comment]
Screen Shot 2022-07-29 at 11 39 52
/label qe-approved

**Review by zherman0 — APPROVED** [review]
/lgtm

**Comment by sg00dwin** [comment]
assign @ahardin-rh for docs approval

**Review by rhamilto — APPROVED** [review]
/approve

/lgtm

**Pull request merged**
