### PR TITLE
add Event Sink  option to broker and channel connector and context menu

### PR DESCRIPTION
**Pull request by sahil143**
**Fixes**: https://issues.redhat.com/browse/ODC-6523

**Analysis / Root cause**: Mising `Add Event Sink` action on context and connector menu for channel and brokers

**Solution Description**: added `Add Event Sink` action on context and connector menu for channel and brokers

**Screen shots / Gifs for design review**: 

Screenshot 2022-03-30 at 6 33 40 PM
Screenshot 2022-03-30 at 6 33 55 PM
Screenshot 2022-03-30 at 6 34 01 PM
Screenshot 2022-03-30 at 6 34 09 PM

**Unit test coverage report**: 

**Test setup:**

**Browser conformance**: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by rhamilto** [comment]
> @sahil143, rebasing on master to pick up the changes in https://github.com/openshift/console/pull/11235 should help this get through the tests.

It turns out that's not correct.  CI will apply your changes to latest automatically.

**Comment by invincibleJai** [comment]
@sahil overall looks good, I see one edge case if I provide an invalid name for channel in URL then the dropdown field for source keeps on loading forever. Can we handle this like show existing resources?

image

**Comment by invincibleJai** [comment]
@sahil143 it does not work as expected for app group flow

- if no app in context then still it creates the resource in an app group
- if an app is in context and in URL I change the app name then no effect still creates the resource in an old app group

contextEventSink

**Comment by sahil143** [comment]
> @sahil143 it does not work as expected for app group flow
> 
> * if no app in context then still it creates the resource in an app group
> 
> contextEventSink

@invincibleJai fixed

**Review by vikram-raj — COMMENTED** [review]
Verified it. and it works as expected.

/lgtm
/label qe-approved

**Pull request merged**
