### PR TITLE
NO-JIRA: Disable "Helm release status verification: HR-01-TC04" test due to CI outage

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
Test PR

/hold

### CODE REVIEW

**Review by vikram-raj — APPROVED** [review]
/lgtm

**Comment by logonoff** [comment]
do i have perms for this?

/label docs-approved 
/label px-approved
/label qe-approved

**Comment by logonoff** [comment]
/retitle NO-JIRA: Disable "Helm release status verification: HR-01-TC04" test due to CI outage

**Comment by logonoff** [comment]
/retitle OCPBUGS-38225: Disable "Helm release status verification: HR-01-TC04" test due to CI outage

**Pull request merged**
