### PR TITLE
Bug 1900020: Remove &apos from internationalized keys

### PR DESCRIPTION
**Pull request by rebeccaalpert**
The other string mentioned in the bug looks like it was already fixed.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1900020.

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by rebeccaalpert** [comment]
Updated the i18n key and lost the lgtm.

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
