### PR TITLE
Bug 1871927: update resource section text for knative

### PR DESCRIPTION
**Pull request by sahil143**
**Fixes**: https://issues.redhat.com/browse/ODC-2438

**Analysis / Root cause**: misleading text for Knative in resource section

**Solution Description**: update the text in resource section

**Screen shots / Gifs for design review**: 
Screenshot 2020-08-24 at 9 18 57 PM

**Unit test coverage report**: None

**Test setup:**

**Browser conformance**: 

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by invincibleJai** [comment]
@sahil143  thanks for the fix , as per design D/DC description has `.` at end so we may need to add that for DC and @rachael-phillips shouldn't description for knative service as well end with `.`

image

**Comment by rachael-phillips** [comment]
I know how we should solve your comment Jai - I agree it should be consistent, so the text could read "A Knative Service is a type of deployment that enables Serverless scaling to 0 when idle."
That way we can stay in a consistent format to the others.

**Comment by invincibleJai** [comment]
/lgtm

Thanks @sahil143  for making the changes

**Pull request merged**
