### PR TITLE
ODC-7271: add duration for PipelineRun and TaskRun on details page

### PR DESCRIPTION
**Pull request by vikram-raj**
Story: https://issues.redhat.com/browse/ODC-7271

Descriptions: 
- Add Duration on the PipelineRun details page
- Add Duration on the TaskRun details page

Screenshots:
PipelineRun details page
image

TaskRun details page
image

### CODE REVIEW

**Review by jerolimov — CHANGES_REQUESTED** [review]
@vikram-raj also if the ask was just for the duration, can we add the "Started" from the list view as well? We should also not show the duration before the status.

I think the order should be also:

For a PipelineRun:

1. Status
2. Pipeline
3. Started (new)
4. Duration

For TaskRun

1. Status
2. Started (new)
3. Duration

btw 1: Why we don't link the PipelineRun (and Pipeline) from the TaskRun? There are labels that reference these resource. This would make the navigation much easier. :man_shrugging: 

btw 2: We should also think about using the `DetailsItem` component instead of a simple definition (with dl, dt, dd). This would automatically lookup the CRD documentation. See BuildConfig details page for an example:

image

https://github.com/openshift/console/blob/95bcd76a0c88ba5d251384dc4e307939f1dfc9c3/frontend/public/components/utils/build-strategy.tsx#L31-L37

Both btw are not necessary but I personally would like to address both in the complete pipelines module. But the order and started should be addressed at least.

**Comment by vikram-raj** [comment]
@jerolimov Add Started and changed the order.

And here we are not using the `DetailsItem` component as we calculate it is not present in the obj directly.

**Comment by lokanandaprabhu** [comment]
Tested locally. Working fine for me.

/lgtm


https://user-images.githubusercontent.com/102503482/228739854-9d1f06ee-1c24-48e5-aafe-daaf2cc8e4ea.mov

**Pull request merged**
