### PR TITLE
Monitoring: Move monitoring Redux data to a separate store 

### PR DESCRIPTION
**Pull request by kyoto**
Move the monitoring related reducers and actions into separate files.

Rename some actions.

### CODE REVIEW

**Comment by spadgett** [comment]
Looks like a good change. I can review after #10154 merges. Thanks @kyoto

**Review by spadgett — APPROVED** [review]
/lgtm

👍

**Comment by kyoto** [comment]
PR updates:
- Rebased
- Fixed bug https://bugzilla.redhat.com/show_bug.cgi?id=2020496
- Realized there were many cases of `.getIn(['...'])` that could be converted to just `.get('...')`

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by lihongyan1** [comment]
/label qe-approved
except the bug, no other issue found
https://bugzilla.redhat.com/show_bug.cgi?id=2022612

**Comment by kyoto** [comment]
Needed to rebase again

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by kyoto** [comment]
Rebased again

**Comment by kyoto** [comment]
Rebased again. @spadgett Could you please tag again?

**Comment by kyoto** [comment]
Sorry @spadgett, I had to rebase again. Could you please tag this again?

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
