### PR TITLE
CONSOLE-3081: Integrate dark theme - fix(background-color): updated to --pf-global--BackgroundColor—100

### PR DESCRIPTION
**Pull request by mattnolting**
For: https://issues.redhat.com/browse/CONSOLE-3081
fix(background-color): updated to --pf-global--BackgroundColor—100
This PR updates `#fff`, `--pf-global--palette--white`, `--pf-chart-global--Fill--Color--white`, `--pf-global--BackgroundColor--light-100`, `--pf-global--palette--black-100`, `$pf-global--Color--light-100` to `--pf-global--BackgroundColor—100`

Color shifts are described here: https://codepen.io/bobcatTaco/pen/NWwVYzq#bc100

Screen Shot 2022-03-09 at 12 27 56 PM

## Form footer
https://github.com/openshift/console/pull/11167/files#diff-16710e5fc890e84eea5dd816cfb4bfd9101d6628f02a36b030a92e966bd60464R10

Before: 

Screen Shot 2022-03-10 at 8 58 22 AM

After:

Screen Shot 2022-03-10 at 8 58 27 AM

## OCS page layout
https://github.com/openshift/console/pull/11167/files#diff-4bfdc5c98535519693267670c0c08b782f2468bc773266d13126396eb4e074a5R15

Before: 

Screen Shot 2022-03-10 at 11 04 31 AM

After:

Screen Shot 2022-03-10 at 11 08 35 AM

## Quick search
https://github.com/openshift/console/pull/11167/files#diff-1a71e6b25655f2dc3a97578bd64168e83907342d364fe81204e55824d41089f2R10

Before:

Screen Shot 2022-03-10 at 9 20 16 AM

After:

Screen Shot 2022-03-10 at 9 20 20 AM

## Topology view 
https://github.com/openshift/console/pull/11167/files#diff-a21946284a52659070b948521c25560ecd685d71a52f32e00fd92d9d2d77ee74R25

Before: 

Screen Shot 2022-03-10 at 9 09 21 AM

After: 

Screen Shot 2022-03-10 at 9 09 26 AM

## Topology filter bar 
https://github.com/openshift/console/pull/11167/files#diff-a21946284a52659070b948521c25560ecd685d71a52f32e00fd92d9d2d77ee74R25 

Before: 

Screen Shot 2022-03-10 at 9 29 01 AM

After:

Screen Shot 2022-03-10 at 9 29 10 AM

## Yaml editor buttons
https://github.com/openshift/console/pull/11167/files#diff-72bd68349b3c1f0cce8ca7e7a4de4d7b69c4d1ddce6f9f7a9e5ab86c129f69aaR19

Before: 

Screen Shot 2022-03-10 at 9 35 29 AM

After:

Screen Shot 2022-03-10 at 9 35 34 AM

## System event icon
https://github.com/openshift/console/pull/11167/files#diff-699a30078a0e11512407321fa7e3f847bf89fdf35a6913b456325124d2a87beaR2

Before:

Screen Shot 2022-03-10 at 9 47 16 AM

After:

Screen Shot 2022-03-10 at 9 47 22 AM

## System even box
https://github.com/openshift/console/pull/11167/files#diff-6f56b5deeda9f877f09587f16d68911a1e4e17fb4764a8e405e19b3a375067e7R77

Before:

Screen Shot 2022-03-10 at 9 49 03 AM

After:

Screen Shot 2022-03-10 at 9 49 10 AM

## Toggle play - remove overridden background color
https://github.com/openshift/console/pull/11167/files#diff-0276e7554d23f547642b7e6f4d1b149731eeb30adb145e61b8d4e4695a6c1101R2

Before:

Screen Shot 2022-03-10 at 9 50 39 AM

After (no change):

Screen Shot 2022-03-10 at 9 51 56 AM

## Tags
https://github.com/openshift/console/pull/11167/files#diff-677d4d52acabea778abcb00b2b9db61974f9cd2261845d18abc3a06ed97cb127R137

Before: 

Screen Shot 2022-03-10 at 10 02 14 AM

After:

Screen Shot 2022-03-10 at 10 01 51 AM

## Resource log
https://github.com/openshift/console/pull/11167/files#diff-1fb6662a9d723188ad53db62330ff369bf37c33d83ea8bea8ce733cebeb1a6bcR10

Before:

Screen Shot 2022-03-10 at 10 08 52 AM

After:

Screen Shot 2022-03-10 at 10 08 59 AM

## List group item - _bootstrap-residual

Before:

Screen Shot 2022-03-10 at 9 40 45 AM

After: 

Screen Shot 2022-03-10 at 9 40 39 AM

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/approve
/ok-to-test

**Comment by jcaianirh** [comment]
Propagate from epic:
/label docs-approved
/label px-approved

**Comment by jcaianirh** [comment]
Propagate from epic:
/label docs-approved
/label px-approved

**Review by vikram-raj — COMMENTED** [review]
Verified the changes. and it works fine.

/lgtm

/qe-approved

**Comment by yanpzhan** [comment]
Launch cluster with the pr, in dark theme, the description on edit label modal is not clear, looks like blank:
Screenshot from 2022-03-14 17-58-22
@mattnolting could you help to confirm if it needs update?

**Comment by mattnolting** [comment]
> Launch cluster with the pr, in dark theme, the description on edit label modal is not clear, looks like blank

@yanpzhan I've opened a separate PR to addresses the modals [11148](https://github.com/openshift/console/pull/11148)

**Comment by jerolimov** [comment]
Code and results look good to me. :+1: Let's improve other areas with follow-up issues / PRss.

/lgtm

**Review by jerolimov — APPROVED** [review]

**Pull request merged**
