### PR TITLE
Nav updates

### PR DESCRIPTION
**Pull request by spadgett**
cluster status openshift origin 2018-08-08 17-28-33

pods openshift origin 2018-08-08 17-30-56

@openshift/team-ux-review @robszumski @sspeiche

### CODE REVIEW

**Comment by serenamarie125** [comment]
FYI @beanh66 this is the first set of changes to match Option 4 in the Navigation design document

**Comment by spadgett** [comment]
Unfortunately this will conflict with #358 :(

@alecmerdler fyi

**Comment by spadgett** [comment]
Note that this changes the URL from `/overview` to `/status` for the existing cluster overview. Confirming this is what we want.

**Comment by beanh66** [comment]
@spadgett @serenamarie125 great, thanks for following up on these changes so fast!

**Comment by spadgett** [comment]
jenkins pushed

**Comment by spadgett** [comment]
jenkins push

**Comment by coreos-ui** [comment]
The PR image has been pushed to Quay with tag `pr_382_build_414`

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

```
Failed Specs:

1) Performance test : downloads new bundle for persistent-volume-claim
   Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       at ontimeout timers.js:427:11
       at tryOnTimeout timers.js:289:5
       at listOnTimeout timers.js:252:5
       at Timer.processTimers timers.js:212:10
   Error: Timeout - Async callback was not invoked within timeout specified by 
```

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by robszumski** [comment]
LGTM! It was good to see this live this week as we talked in the F2F.

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by rhamilto** [comment]
Changes LGTM, but I'm not sure what's going on with the build, performance, and gui-test errors.

**Comment by rhamilto** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
All green now, @rhamilto can you tag?

**Pull request merged**
