### PR TITLE
ODC-6064: Update PatternFly to fix unexpected spacing below topology toolbar

### PR DESCRIPTION
**Pull request by jerolimov**
**Fixes**: 
https://issues.redhat.com/browse/ODC-6064

**Analysis / Root cause**: 
With one of the latest `@patternfly/react-core` the `Toolbar` component renders an unexpceted spacing. See before screenshots below.

**Solution Description**: 
Update `@patternfly/patternfly` and `@patternfly/react-core` to the latest version which includes the bugfix 

See also
* https://github.com/patternfly/patternfly-react/issues/5962
* https://github.com/patternfly/patternfly/pull/4197
* https://github.com/patternfly/patternfly-react/pull/5971

**Screen shots / Gifs for design review**: 

Broken topology toolbar before:

image

Topology toolbar now (again without spacing):

image

Search for other UI changes.

~~The only differences I noticed yet is that the perspective dropdown shows now a gray bottom-border line which changes to blue if the user hovers it.~~

~~Before:~~

Peek 2021-07-09 00-25

~~After (without the change in `_nav_header.scss`, with the change there is no visual change to the old version):~~

Peek 2021-07-09 00-38

With the latest `@patternfly/patternfly` update this issue is fixed again. I don't find any other layout issues yet.

**Unit test coverage report**: 
Untouched

**Test setup:**
Just open the developer perspective > topology.

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

/kind bug

### CODE REVIEW

**Comment by jerolimov** [comment]
I think we should wait for UX feedback if the perspective switch change is an issue.
/hold

**Comment by rhamilto** [comment]
> Search for other UI changes. The only differences I noticed yet is that the perspective dropdown shows now a gray bottom-border line which changes to blue if the user hovers it.

I noticed this as well and reported it at https://github.com/patternfly/patternfly/issues/4155#issuecomment-876741760 (which I now realize wasn't the offending PR, but the issue links to the offending PR).  I worked around the issue with https://github.com/openshift/console/pull/9419/files#diff-8f2141c9b030221e65e6a3c024604a13181de9046fdc1f54c60e23b6a10c045eR14-R18

**Comment by rhamilto** [comment]
Fix for the breaking PatternFly change coming.  See https://github.com/patternfly/patternfly/issues/4155#issuecomment-877420752

**Comment by jerolimov** [comment]
@rhamilto thanks for these links.

For this PR I removed the border also from for the `:after` element. So that there is no visual difference anymore to the old version. From my side this PR is fine with this change, but let me know what you think. :)

I remove the hold as I don't know any visual blocker at the moment. I also updated PF again and rebased this PR.
/unhold

**Comment by rhamilto** [comment]
> @rhamilto thanks for these links.
> 
> For this PR I removed the border also from for the `:after` element (see `_nav-header.scss` change). So that there is no visual difference anymore to the old version. From my side this PR is fine with this change, but let me know what you think. :)
> 
> I remove the hold as I don't know any visual blocker at the moment. I also updated PF again and rebased this PR.
> /unhold

[PatternFly is to revert the changes](https://github.com/patternfly/patternfly/issues/4155#issuecomment-877412085) requiring you to add `:after` to the existing rule.  I think it would be best to wait until those changes land so there is no need to add to the existing override as once the reversion is released, the `:after` addition will be unnecessary.

**Comment by jerolimov** [comment]
OK. Waiting for

* https://github.com/patternfly/patternfly/pull/4213 **+ release**
* maybe @patternfly/react-core release as well

/hold

**Comment by jerolimov** [comment]
@rhamilto https://github.com/patternfly/patternfly/pull/4213 is merged and released. I updated this PR again to the latest PF releases.

The topology toolbar is still fine with this PR, the perspective switch looks good and I could not find any other UI glitch at the moment. From my side we could update PF now. Look good to you as well?

/hold cancel

**Comment by rhamilto** [comment]
> From my side we could update PF now. Look good to you as well?

Yep!

> Are you fine with adding such a update-patternfly.sh script so that everyone knows how to update it (use prerelease instead latest, -W, --exact) 😄 ?

I'll defer to the @spadgett and @christianvogt on that one.

**Comment by christianvogt** [comment]
If you want to deliver a script because it makes the task easier. go for it.

**Review by rhamilto — APPROVED** [review]
/lgtm

**Review by rhamilto — APPROVED** [review]
/lgtm

**Comment by rhamilto** [comment]
Sorry, @jerolimov.  It looks like my PR landed before yours did, and now you need to rebase.

**Comment by jerolimov** [comment]
> Sorry, @jerolimov. It looks like my PR landed before yours did, and now you need to rebase.

No problem. Rebased, re-run the script and done. ;)

**Review by rhamilto — APPROVED** [review]
/lgtm

**Pull request merged**
