### PR TITLE
Bug 1791346: Error occurs while removing the second CD-ROM (4.3)

### PR DESCRIPTION
**Pull request by glekner**
Target 4.3

### CODE REVIEW

**Comment by glekner** [comment]
@suomiy can you review? this code has already been reviewed, its a cherry pick

**Comment by suomiy** [comment]
@yaacov can you lgtm as you reviewed the original one?

**Comment by glekner** [comment]
@suomiy can you approve aswell? kobe has no permissions for .3

**Comment by suomiy** [comment]
not working here either (-:

**Comment by bparees** [comment]
skipping this one for approval this week anyway due to the number of other changes already accepted.

**Pull request merged**
