### PR TITLE
Add OpenShift Dedicated logo option

### PR DESCRIPTION
**Pull request by rhamilto**
screen shot 2018-09-27 at 11 41 18 am

### CODE REVIEW

**Comment by spadgett** [comment]
We should update `index.html` and `tokener.html`

Also there is validation in main.go that needs to be updated.

**Comment by spadgett** [comment]
We should update the command line help here, too:

https://github.com/openshift/console/blob/master/cmd/bridge/main.go#L88

**Comment by rhamilto** [comment]
Fixed.  Sure am glad someone is paying attention.  ;-)

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
