### PR TITLE
OCPBUGS-1105: OCPBUGS-1106: Update dependencies to the registry library and devfile parser

### PR DESCRIPTION
**Pull request by kim-tsao**
This PR fixes two issues:

- When a devfile is imported with a parent reference pointing to a registry server,   the devfile parser will download the parent devfile in order to fully parse out the contents but the http client it uses does not support proxying and will result in a failure for console users
- In failed networking scenarios, it takes about 30s to retrieve a response from the devfile server/parser.  This is the default timeout devfile sets but it's too lengthy of a wait for end users.   The library and parser interfaces were modified to accept custom timeout values that clients can set.  In the case of console, the timeout value has been reduced to 10s.

### CODE REVIEW

**Comment by kim-tsao** [comment]
Devfile tracking issue: https://github.com/devfile/api/issues/934

**Review by jerolimov — APPROVED** [review]
Verified this locally and it works fine. :+1: 

I have done some manual changes

1. Changed `httpTimeout := 10` to 5 seconds
2. Added this code to `vendor/github.com/devfile/registry-support/registry-library/library/library.go` before `req, err := http.NewRequest("GET", url, nil)`

```go
fmt.Printf("url: %v\n", url)
url = "https://httpbin.org/delay/10"
```

3. `./build-backend.sh`
4. Loaded the samples in the console with opened network inspector. The network call should stop (failing is okay) after 5 seconds.

/lgtm
/approve

**Comment by jerolimov** [comment]
/retitle OCPBUGS-1105: OCPBUGS-1106: Update dependencies to the registry library and devfile parser

**Comment by jerolimov** [comment]
Retested this as described in this https://github.com/openshift/console/pull/12043#pullrequestreview-1129518578 comment, works fine :+1: 

/lgtm
/retest

**Comment by jerolimov** [comment]
/retitle OCPBUGS-1106: Update dependencies to the registry library and devfile parser

**Pull request merged**
