### PR TITLE
Bug 1957499: OperatorHub - console accepts any value for infraFeatures

### PR DESCRIPTION
**Pull request by florkbr**
This PR includes changes from (failed cherry-pick from bot):
  * https://github.com/openshift/console/pull/8844 
  
  https://bugzilla.redhat.com/show_bug.cgi?id=1957499

### CODE REVIEW

**Comment by florkbr** [comment]
@spadgett mind giving any pointers here? This is my first manual cherry-pick.

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by florkbr** [comment]
New bugzilla (duplicated from original) https://bugzilla.redhat.com/show_bug.cgi?id=1957499.

Cannot modify the target until it's assigned to me :(

**Comment by florkbr** [comment]
@spadgett is there anything else needed here? Wondering why this hasn't been merged yet...

**Comment by yapei** [comment]
@florkbr Maybe awaiting for QE's verification before PR is merged, let me test and give feedback

**Comment by yapei** [comment]
1. Build an operator image who has `operators.openshift.io/infrastructure-features` annotation with multiple values(valid and invalid)
```
    operators.openshift.io/infrastructure-features: >-
      ["disconnected", "cni", "cnf", "csi", "fips", "proxy-aware",
      "Disconnected", "FipsMode", "Proxy", "Unknown", "TestBacon"]
```
and deploy it within catalogsource
2. Check `Infrastructure features` filter on OperatorHub page, no unknown types shown and all types are mapped correctly
Screen Shot 2021-05-12 at 11 16 39 AM

**Comment by yapei** [comment]
Sorry, the values shown in operator modal is wrong, see 
Screen Shot 2021-05-12 at 11 46 56 AM

Removing qe-approved labels

**Comment by spadgett** [comment]
> @spadgett is there anything else needed here? Wondering why this hasn't been merged yet...

@florkbr For backports, it requires a patch manager to add a cherry-pick-approved label. We limit the number of PRs each week in the z-streams so that QE has bandwidth to test.

**Comment by spadgett** [comment]
> Sorry, the values shown in operator modal is wrong

@yapei Do you know if this is an issue in master as well?

/hold

**Comment by yapei** [comment]
@spadgett I confirmed that the issue is also found on master branch

**Comment by yapei** [comment]
also when operator doesn't have `` annotation defined, we still show `Infrastructure features` with empty value on operator modal(same issue in master as well)
Screen Shot 2021-05-13 at 1 38 17 PM

**Comment by florkbr** [comment]
@yapei I have opened another PR against master with a fix for both issues you pointed out above. I've pushed the change to this PR as well for release-4.7.

@spadgett do I need to cherry-pick the merge commit after my master PR merges, or is it ok that I cherry-picked the commit from my private branch?

**Comment by yapei** [comment]
@florkbr  Sorry for late response, @XiyunZhao will test this PR and report test results back

**Comment by spadgett** [comment]
> @spadgett do I need to cherry-pick the merge commit after my master PR merges, or is it ok that I cherry-picked the commit from my private branch?

I think what you've done is good. We can have QE test before merging. Thanks!

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by florkbr** [comment]
@XiyunZhao let me know if you need any information for your testing! Thanks in advance.

**Comment by XiyunZhao** [comment]
@florkbr this PR has been verified and the result is as expected, we can move to next stage. more details can be check on [Bugzilla bug 1957499](https://bugzilla.redhat.com/show_bug.cgi?id=1957499)

**Comment by derekwaynecarr** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

approved

**Pull request merged**
