### PR TITLE
Bug 1916524: Removed template rootdisk

### PR DESCRIPTION
**Pull request by metalice**
Signed-off-by: Matan Schatzman <mschatzm@redhat.com>

**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=1916524

**Analysis / Root cause**: 
Using old template without dataVolumeTemplate 

**Solution Description**: 
Removing template root disk in case there isn't dataVolumeTemplate

**Screen shots / Gifs for design review**: 
Before:
screencapture-0-0-0-0-9000-k8s-ns-default-virtualization-new-wizard-1610673105712 (1)

After:
image

### CODE REVIEW

**Comment by metalice** [comment]
@yaacov @rawagner when u have time :)

**Comment by rawagner** [comment]
/hold
I need some time to review

**Pull request merged**
