### PR TITLE
MGMT-14527: Add vSphere cluster field.

### PR DESCRIPTION
**Pull request by rawagner**
Fix some additional minor issues & simplify code

Screenshot from 2023-05-10 15-48-17

### CODE REVIEW

**Review by mareklibra — APPROVED** [review]

**Comment by rawagner** [comment]
@opayne1 @RickJWagner @yanpzhan for the approvals.

**Comment by RickJWagner** [comment]
Looks good.

/label px-approved

**Comment by yapei** [comment]
verified following
1. `vCenter cluster` field value is correctly populated 
2. After updating `vCenter cluster`, new values can be successfully saved to `failureDomains.topology.networks` of `infrastructure.config.openshift.io/cluster`
3. pesudo translation is done for new added `vCenter cluster` filed and all other fields in the form

**Pull request merged**
