### PR TITLE
CONSOLE-4014: Consume the telemetry parameter ORGANIZATION_ID and pass it as organizationId parameter to segment

### PR DESCRIPTION
**Pull request by jerolimov**
Update `useTelemetry` so that it automatically pass `SERVER_FLAGS.telemetry.ORGANIZATION_ID` as `organizationId` parameter to segment.

Tested with a console `config.yaml`:

```yaml
apiVersion: console.openshift.io/v1
kind: ConsoleConfig
telemetry:
  SEGMENT_API_KEY: F24PIOXaJhcshtmPGucjkZi8mGR9IhNa # staging
  SEGMENT_API_HOST: console.redhat.com/connections/api/v1
  SEGMENT_JS_HOST: console.redhat.com/connections/cdn
  ORGANIZATION_ID: cjerolim-test
  STATE: OPT-IN
```

image

/cc @lokanandaprabhu @jhadvig

### CODE REVIEW

**Comment by jerolimov** [comment]
Doesn't affect any user-facing code.

/label docs-approved
/label px-approved

**Comment by lokanandaprabhu** [comment]
Hope the screenshot you added is of old tag as orgId since it will send now as organizationId

Tested locally. Working fine.

/lgtm

Screenshot 2024-04-04 at 9 31 31 PM

**Review by lokanandaprabhu — APPROVED** [review]

**Comment by sanketpathak** [comment]
Verified on cluster-bot
Screenshot 2024-04-08 at 1 34 11 AM

/label qe-approved

**Pull request merged**
