### PR TITLE
OCPBUGS-38907: Increase login flow state paramater length/entropy

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @TheRealJon

### CODE REVIEW

**Comment by jhadvig** [comment]
-retest

**Comment by jhadvig** [comment]
/retest

```
  Running:  cluster-settings/update-modal.cy.ts                                           (18 of 57)
[1674:0909/094855.234431:ERROR:zygote_host_impl_linux.cc(273)] Failed to adjust OOM score of renderer with pid 4400: Permission denied (13)


  Cluster Settings cluster update modal
      redirect to home
      ensure perspective switcher is set to Administrator
      with a paused Worker MCP
      with available and conditional updates
      with a paused Worker MCP
      with available and conditional updates
    1) changes based on the cluster


  0 passing (3m)
  1 failing

  1) Cluster Settings cluster update modal
       changes based on the cluster:
     CypressError: Timed out retrying after 30050ms: `cy.click()` failed because this element is `disabled`:

`<input id="pf-1725875511519o6k8csggb0a" class="pf-v5-c-switch__input" type="checkbox" disabled="" aria-labelledby="pf-1725875511519o6k8csggb0a-off" data-test="dropdown-with-switch-switch" aria-label="">`

Fix this problem, or use `{force: true}` to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with
      at Object.isNotDisabled (https://console-openshift-console.apps.ci-op-km0fflvx-75d12.XXXXXXXXXXXXXXXXXXXXXX/__cypress/runner/cypress_runner.js:144844:58)
      at runAllChecks (https://console-openshift-console.apps.ci-op-km0fflvx-75d12.XXXXXXXXXXXXXXXXXXXXXX/__cypress/runner/cypress_runner.js:112761:26)
      at retryActionability (https://console-openshift-console.apps.ci-op-km0fflvx-75d12.XXXXXXXXXXXXXXXXXXXXXX/__cypress/runner/cypress_runner.js:112850:16)
      at tryCatcher (https://console-openshift-console.apps.ci-op-km0fflvx-75d12.XXXXXXXXXXXXXXXXXXXXXX/__cypress/runner/cypress_runner.js:1807:23)
      at Promise.attempt.Promise.try (https://console-openshift-console.apps.ci-op-km0fflvx-75d12.XXXXXXXXXXXXXXXXXXXXXX/__cypress/runner/cypress_runner.js:4315:29)
      at whenStable (https://console-openshift-console.apps.ci-op-km0fflvx-75d12.XXXXXXXXXXXXXXXXXXXXXX/__cypress/runner/cypress_runner.js:143666:68)
      at <unknown> (https://console-openshift-console.apps.ci-op-km0fflvx-75d12.XXXXXXXXXXXXXXXXXXXXXX/__cypress/runner/cypress_runner.js:143607:14)
      at tryCatcher (https://console-openshift-console.apps.ci-op-km0fflvx-75d12.XXXXXXXXXXXXXXXXXXXXXX/__cypress/runner/cypress_runner.js:1807:23)
      at Promise._settlePromiseFromHandler (https://console-openshift-console.apps.ci-op-km0fflvx-75d12.XXXXXXXXXXXXXXXXXXXXXX/__cypress/runner/cypress_runner.js:1519:31)
      at Promise._settlePromise (https://console-openshift-console.apps.ci-op-km0fflvx-75d12.XXXXXXXXXXXXXXXXXXXXXX/__cypress/runner/cypress_runner.js:1576:18)
      at Promise._settlePromise0 (https://console-openshift-console.apps.ci-op-km0fflvx-75d12.XXXXXXXXXXXXXXXXXXXXXX/__cypress/runner/cypress_runner.js:1621:10)
      at Promise._settlePromises (https://console-openshift-console.apps.ci-op-km0fflvx-75d12.XXXXXXXXXXXXXXXXXXXXXX/__cypress/runner/cypress_runner.js:1701:18)
      at Promise._fulfill (https://console-openshift-console.apps.ci-op-km0fflvx-75d12.XXXXXXXXXXXXXXXXXXXXXX/__cypress/runner/cypress_runner.js:1645:18)
      at <unknown> (https://console-openshift-console.apps.ci-op-km0fflvx-75d12.XXXXXXXXXXXXXXXXXXXXXX/__cypress/runner/cypress_runner.js:5450:46)
  From Your Spec Code:
      at Context.eval (webpack:///./tests/cluster-settings/update-modal.cy.ts:59:7)

```

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Pull request merged**
