### PR TITLE
Filter out global configs when cluster is externally managed

### PR DESCRIPTION
**Pull request by andrewballantyne**
https://issues.redhat.com/browse/CONSOLE-3073

Filters out the Cluster Settings => Configuration tab of resources (ticket has the list, but if you want the full qualified list see [this code link](https://github.com/openshift/console/pull/11383/files#diff-7c47f35e3e3c03d9ee57e6e7cc8c2761391134973e0b0e7be363faa8ef0e7760R4)) that cannot be modified if the cluster is externally managed.

image

### Setup / Testing
It's based on the SERVER_FLAG controlPlaneTopology being set to External is really the driving factor here; this can be done in one of two ways:

- Locally via a Bridge Variable, `export BRIDGE_CONTROL_PLANE_TOPOLOGY_MODE="External"`
- Locally / OnCluster via modifying the `window.SERVER_FLAGS.controlPlaneTopology` to External in the dev tools

### CODE REVIEW

**Review by rhamilto — COMMENTED** [review]
Nicely done, @andrewballantyne.

/lgtm

**Comment by andrewballantyne** [comment]
QE Approver:
 /assign @yanpzhan
Docs Approver:
 /assign @opayne1
PX Approver:
 /assign @RickJWagner

**Comment by yanpzhan** [comment]
@andrewballantyne  Checked in the code and cluster launched with the pr, the "OAuth“ config is not listed in code, so it still shows up on the page. And if "Console" config need to be hidden?

**Comment by yanpzhan** [comment]
@andrewballantyne Check on a normal cluster(non-hypershift provisioned), under Configuration tab of cluster settings page, there are not these 3 resources:  MachineConfig, KubeletConfig and ContainerRuntimeConfig.  If they only exist on special cluster?

**Comment by andrewballantyne** [comment]
> @andrewballantyne Checked in the code and cluster launched with the pr, the "OAuth“ config is not listed in code, so it still shows up on the page. And if "Console" config need to be hidden?

Not sure how I missed `OAuth` heh... fixed that now. Good catch, thanks!

As for the `Console` config, I don't believe it should be filtered as it states the details of the console as a whole -- like the URL it is on. So I don't believe this is one that needs to be filtered. cc @jhadvig

**Comment by andrewballantyne** [comment]
> @andrewballantyne Check on a normal cluster(non-hypershift provisioned), under Configuration tab of cluster settings page, there are not these 3 resources: MachineConfig, KubeletConfig and ContainerRuntimeConfig. If they only exist on special cluster?

Need to talk to @jhadvig about this.

**Comment by jhadvig** [comment]
@andrewballantyne those resources (MachineConfig, KubeletConfig, ContainerRuntimeConfig) are not in the `config.openshift.io` or `operator.openshift.io` apiGroup, so yes it's expected they wouldn't be in the Cluster Settings -> Configuration page.
Which means that we dont have to add them to the filter.

**Review by jhadvig — APPROVED** [review]
/lgtm

**Pull request merged**
