### PR TITLE
ODC-7635: Add alert for SW Builds when waiting

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7635 

**Solution Description**: 

When the `getBuildRunStatus` for all buildRuns in a build are not either `Succeeded` or `Failed`, show the alert

**Screen shots / Gifs for design review**: 

image

**Unit test coverage report**: 

unchanged

**Test setup:**

- Install Shipright Operator and set up a Shipwright Build

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

### CODE REVIEW

**Review by Lucifergene — CHANGES_REQUESTED** [review]
We have the alert under the Pod Section in case of BuildConfigs. 
But in this PR, it is displayed over the Build Section.

Please move the alert to the Pod Section to align with the present UX.

_**Refer to the Screenshots for more clarity:**_

Alert Message shown in case of BuildConfig:
Screenshot from 2024-07-12 20-54-23

Alert Message shown in case of Shipwright currently:
Screenshot from 2024-07-12 20-52-25

**Comment by Lucifergene** [comment]
Thanks for this!

/label docs-approved
/label px-approved

**Review by Lucifergene — APPROVED** [review]
All looks good :)

Screenshot from 2024-07-30 16-06-08

/lgtm
/approve

**Comment by Lucifergene** [comment]
Tagging
@vikram-raj  for approval
@sanketpathak for qe-approval

**Comment by The-Anton** [comment]
ShipwrightBuilds Tab is throwing UI issues for normal user in admin perspective. Addition info - Shipwright build is installed.

image

**Review by vikram-raj — COMMENTED** [review]
/approve

**Comment by The-Anton** [comment]
Affected tests are running green
/label qe-approved

Screenshot 2024-08-01 at 3 22 53 PM
Screenshot 2024-07-31 at 1 06 52 PM

**Pull request merged**
