### PR TITLE
Fix bug where success icon lacks enough contrast

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://jira.coreos.com/browse/CONSOLE-1694

Screen Shot 2019-08-20 at 2 26 28 PM
Screen Shot 2019-08-20 at 2 28 28 PM
Screen Shot 2019-08-20 at 2 29 14 PM
Screen Shot 2019-08-21 at 10 40 47 AM

### CODE REVIEW

**Comment by rhamilto** [comment]
Rebased.  @spadgett, please tag.

**Comment by rhamilto** [comment]
Updated to include topology screenshot previously unavailable.

**Comment by serenamarie125** [comment]
FYI @beanh66

**Pull request merged**
