### PR TITLE
[release-4.6]  Bug 1925037: fix delete app modal error when resource not found

### PR DESCRIPTION
**Pull request by debsmita1**
This is manual cherry-pick of https://github.com/openshift/console/pull/7948

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Tested this locally. works fine

/lgtm

**Comment by jerolimov** [comment]
Backend crash depends maybe also on #8025.

**Comment by jerolimov** [comment]
/assign @invincibleJai 

as you approved the origin PR

**Comment by invincibleJai** [comment]
/approve

Validated on PR build, works as expected

**Pull request merged**
