### PR TITLE
Bug 1883414: Update BMH utilization queries

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by kyoto** [comment]
FYI @openshift/openshift-team-monitoring

**Comment by rawagner** [comment]
FIY these are the same queries as used in Node utilization chart. The Node queries were updated recently but BMH were left unchanged.
https://github.com/openshift/console/pull/6571
https://github.com/openshift/console/pull/6652

**Review by jtomasek — APPROVED** [review]

**Pull request merged**
