### PR TITLE
[CONSOLE-2782] Update Dockerfile.product for nodejs v14.16.0

### PR DESCRIPTION
**Pull request by yselkowitz**
Fixes: https://issues.redhat.com/browse/CONSOLE-2782
Simultaneously requires: https://github.com/openshift/aos-cd-jobs/pull/2550

### CODE REVIEW

**Comment by yselkowitz** [comment]
4.7 also is FROM ubi8.nodejs.14, therefore: 
/cherry-pick release-4.7

**Comment by sosiouxme** [comment]
downstream is ready for this update.
/lgtm

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
