### PR TITLE
cnv-8975: Enable online VM snapshots in the UI

### PR DESCRIPTION
**Pull request by avivtur**
**Fixes**: 
https://issues.redhat.com/browse/CNV-8975

**Analysis / Root cause**: 
Restrictions for creating snapshot while VM is running

**Solution Description**: 
Removing restrictions for snapshot while VM is running, adjusting the 'snapshot' modal and list of snapshot in snapshot page UI components accordingly to indicate about snapshot creation while VM is running

**Screen shots / Gifs for design review**: 
before:
cnv8975-before

after:
snapshot creation while VM is still on running status:
cnv8975-after-create-while-vm-running

created snapshot yaml file:
cnv8975-after-snapshot-yaml-example

snapshot restore demo:
cnv8975-after-restore-demo

Signed-off-by: Aviv Turgeman <aturgema@redhat.com>

### CODE REVIEW

**Comment by avivtur** [comment]
@yaacov @glekner please review

**Comment by avivtur** [comment]
@matthewcarleton please review

**Comment by matthewcarleton** [comment]
we have some follow ups to this @avivtur / @yaacov

**Pull request merged**
