### PR TITLE
BZ1610595: ActionMenu for searched resources should only contain common actions

### PR DESCRIPTION
**Pull request by jhadvig**
We should leave only common actions for all the searched resources. Those are Edit and Delete.

@spadgett PTAL

### CODE REVIEW

**Comment by spadgett** [comment]
/hold

These actions apply to almost all resources and are useful. I'm not sure we want to disable them for everything because of restrictions on only a few kinds.

**Comment by spadgett** [comment]
I'd prefer to allow registering actions for a kind, similar to what we do for YAML templates. Then the same actions will appear everywhere (overview, list view, details page, search view). We can fallback to these four actions for resources we don't know about.

We might want to punt on this until after 3.11, though.

**Comment by jhadvig** [comment]
@spadgett makes sense to register them similar to the templates. Will take a look on it and leave this opened, but lets wait for 3.11 to go out. Ok ?

**Comment by alecmerdler** [comment]
@spadgett Registering UI actions as part of the model is actually something we were talking about for extending the console with Operators!

**Comment by spadgett** [comment]
Closing for now since we probably want a different approach.

**Pull request closed without merging**
