### PR TITLE
[WIP] Add memory and CPU usage to pods list

### PR DESCRIPTION
**Pull request by spadgett**
@kyoto @cshinn opinions on this change?

localhost_9000_k8s_all-namespaces_pods_orderBy=desc sortBy=Memory

### CODE REVIEW

**Comment by spadgett** [comment]
#1531 should fix the OLM test failure.

/retest

**Comment by kyoto** [comment]
@spadgett, @cshinn This looks like a nice change to me and it solves the problem of how to handle lots of labels.

**Comment by alimobrem** [comment]
+100

**Comment by cshinn** [comment]
@spadgett I think that makes sense. Being able to sort by usage should bring great benefits. I wonder if the ability to filter by label would give us most of the utility without taking up the space

**Comment by spadgett** [comment]
Closing for now. We can reconsider for 4.3

**Comment by spadgett** [comment]
Replaced by #3703

**Pull request closed without merging**
