### PR TITLE
OLS-944: Allow operators to enable monitoring by default

### PR DESCRIPTION
**Pull request by kyoto**
default-monitoring

Related OpenShfit Lightspeed PR: https://github.com/openshift/lightspeed-operator/pull/366

### CODE REVIEW

**Comment by kyoto** [comment]
/assign @spadgett 

Could you please review @spadgett?

**Comment by kyoto** [comment]
Docs approver:
/assign @opayne1

PX approver:
/assign @reestr

**Review by spadgett — APPROVED** [review]
/approve
/lgtm

Code looks good to me. @jan--f can you take a quick look and confirm the label/annotation values? Feel free the remove the hold when ready.

/hold

**Comment by kyoto** [comment]
QE approver:
/assign @yapei

**Comment by yapei** [comment]
@yanpzhan will start working on PR verification

**Comment by yanpzhan** [comment]
Tested on cluster launched against the pr, now the "Enable Operator recommended cluster monitoring on this Namespace" is checked by default when the operator has annotation "console.openshift.io/operator-monitoring-default: true" and label "provider" includes "Red Hat".
/label qe-approved

**Pull request merged**
