### PR TITLE
[release-4.13] OCPBUGS-16434: Fix stop PLR option

### PR DESCRIPTION
**Pull request by vikram-raj**
Manual cherry-pick of https://github.com/openshift/console/pull/13020

### CODE REVIEW

**Comment by vikram-raj** [comment]
Verified it on the cluster bot. 

https://github.com/openshift/console/assets/2561818/ff8f8e31-8c8c-4e72-beea-e5e324307a1b

**Comment by lokanandaprabhu** [comment]
Tested using cluster bot. Working fine.

/retest

**Pull request merged**
