### PR TITLE
[Dark Theme]: fix quick search bar and  project selector in User Preferences page

### PR DESCRIPTION
**Pull request by vikram-raj**
**fixes:** https://issues.redhat.com/browse/ODC-6634

**Screnshots:**
### Project selector
**Before:**
image

**After:**
image

### Quick Search
**Before:**
image

image

**After:**
image

image

### CODE REVIEW

**Comment by vikram-raj** [comment]
cc: @sg00dwin @mattnolting

**Review by jerolimov — APPROVED** [review]
Lgtm! :+1: 

/lgtm
/approve

**Comment by jerolimov** [comment]
Propagating docs and px acks from the Epic
/label docs-approved
/label px-approved
/label qe-approved

**Pull request merged**
