### PR TITLE
Bug 1924968: Monitoring: Add some missing translations

### PR DESCRIPTION
**Pull request by kyoto**
Mostly for the list row filtering options.

### CODE REVIEW

**Comment by kyoto** [comment]
FYI @rebeccaalpert

**Review by rebeccaalpert — APPROVED** [review]
Looks good to me. I have one comment about translating the filter values - we should probably internationalize the row values to match since they may differ significantly where they're translated into a different language. I've used switch statements to return translations for this kind of stuff elsewhere.

Screen Shot 2021-02-04 at 10 30 35 AM

**Comment by kyoto** [comment]
This was mostly implemented by https://github.com/openshift/console/pull/8571, so I changed this PR to just add a couple of missing translations and rebased.

**Comment by andrewballantyne** [comment]
/lgtm

Looks like a tiny PR, let's get it merged.

**Pull request merged**
