### PR TITLE
CONSOLE-3618: Remove frontend multicluster code

### PR DESCRIPTION
**Pull request by TheRealJon**

### CODE REVIEW

**Review by rhamilto — APPROVED** [review]
/lgtm

**Review by jhadvig — APPROVED** [review]
QE Approver:
/assign @yanpzhan 
Docs Approver:
/assign @opayne1 
PX Approver:
/assign @RickJWagner

**Comment by yanpzhan** [comment]
Regression test passed.
/label qe-approved
/label cherry-pick-approved

**Comment by yanpzhan** [comment]
@TheRealJon I added cherry-pick-approved label by mistake, do you know how to remove it?

**Comment by TheRealJon** [comment]
px review not needed:
/label px-approved

**Comment by TheRealJon** [comment]
/retest

Cluster didn't start

**Pull request merged**
