### PR TITLE
Bug 1906356: Unify Clone PVC boot source flow

### PR DESCRIPTION
**Pull request by glekner**
When clicking customize on the VM Wizard and choosing the Clone provision source, the user can now select the PVC from the General Tab.

Screen Shot 2020-12-14 at 15 07 23

### CODE REVIEW

**Comment by glekner** [comment]
@matthewcarleton @rawagner

**Comment by matthewcarleton** [comment]
awesome! My only question is "project" vs "namespace" I think I've seen PVC namespace in other places. @rawagner WDYT?

**Comment by glekner** [comment]
@matthewcarleton in the simple wizard (before clicking customize) its `Persistent Volume Claim project`

**Pull request merged**
