### PR TITLE
OCPBUGS-38051: improve Lightspeed popup contents and navigation

### PR DESCRIPTION
**Pull request by rhamilto**
localhost_9000_dashboards(iPhone 12 Pro)
localhost_9000_dashboards(iPad Mini)
localhost_9000_dashboards(iPad Pro)
localhost_9000_dashboards
localhost_9000_dashboards (1)

### CODE REVIEW

**Comment by yanpzhan** [comment]
Checked on cluster launched against the pr, on Lightseed popup modal, the contents and navigation works as expected.
/label qe-approved

**Comment by cyril-ui-developer** [comment]
Awesome work! 👍 
Screenshot 2024-08-16 at 11 12 54 AM

/lgtm

**Pull request merged**
