### PR TITLE
[release-4.10] Bug 2076777:  add update mode to Update cluster

### PR DESCRIPTION
**Pull request by rhamilto**
Manual back port of https://github.com/openshift/console/pull/11053

### CODE REVIEW

**Comment by rhamilto** [comment]
/hold 

Need to determine if any 4.10 doc updates are needed.  @opayne1, do you know?

**Comment by opayne1** [comment]
Spoke with @rhamilto doc updates are needed to these topics: 

- https://docs.openshift.com/container-platform/4.10/updating/preparing-eus-eus-upgrade.html
- https://docs.openshift.com/container-platform/4.10/updating/updating-cluster-within-minor.html
- Possibly https://docs.openshift.com/container-platform/4.10/updating/updating-cluster-cli.html

**Comment by rhamilto** [comment]
Hold until @opayne1 has had a chance to update the docs mentioned in https://github.com/openshift/console/pull/11364#issuecomment-1103131876.

**Comment by XiyunZhao** [comment]
Hi @rhamilto, could you help to check if the changes from [Bug 2073023 ](https://bugzilla.redhat.com/show_bug.cgi?id=2073023) are included in this branch? No reaction after clicking the button of the update on OCP 4.10 that will block the testing

**Comment by rhamilto** [comment]
> Hi @rhamilto, could you help to check if the changes from [Bug 2073023 ](https://bugzilla.redhat.com/show_bug.cgi?id=2073023) are included in this branch? No reaction after clicking the button of the update on OCP 4.10 that will block the testing

You can browse the branch at https://github.com/rhamilto/console/commits/control-plane-4.10.  Yes, the changes from https://github.com/openshift/console/pull/11302 are included there.  Those changes should not affect the ability to start an update of a cluster, however.  Some time it can take up to 30 seconds before the ClusterVersionOperator starts updating after a new update has been requested.  How long did you wait?  How did you spin up a cluster to test?

**Comment by XiyunZhao** [comment]
@rhamilto I use the private build and open the console via ./bridge, nothing happens after hitting the update button for more than 2 minutes, so I'm wondering if it's possible to do this test  by using a private build

**Comment by rhamilto** [comment]
@XiyunZhao, a private build should work fine.  I was able to successfully build using this branch against a 4.10.4 cluster-bot cluster and see the update start (see attached).

https://user-images.githubusercontent.com/895728/165109796-e274aaf1-16e5-4c21-92e8-e2644c03bdbd.mov

My build steps:

1.  `gh pr checkout 11364`
2. `./build.sh`
3. `./bin/bridge --branding=ocp`

**Comment by XiyunZhao** [comment]
This PR has been tested with Test case [OCP-49458](https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-49458) , no issue found, al new added function is working correctly

**Comment by rhamilto** [comment]
@opayne1, note this PR has merged and will release with 4.10.14.

**Pull request merged**
