### PR TITLE
Bug 1910024: fallback to localstorage for 404 on create ConfigMap

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes**: 
https://issues.redhat.com/browse/ODC-5302

**Analysis / Root cause**: 
Running latest UI on 4.6 cluster locally i observe the reloads and console had warning with 404 for create userSettings

**Solution Description**: 

Added fallback to localstorage in case of 404 from create userSettings

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
verified it and I can not see auto-reload now locally.

/lgtm

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
