### PR TITLE
CONSOLE-4330: Remove Developer perspective > Observe > Silences tab

### PR DESCRIPTION
**Pull request by zhuje**
### OU JIRA issue 
https://issues.redhat.com/browse/OU-257

### CONSOLE JIRA issue 
This duplicate issue was created because openshift/console github bots require a valid CONSOLE Jira to be associated with all PRs. 
https://issues.redhat.com/browse/CONSOLE-4330

### Corresponding PR to migrate Dev > Observe > Silences Tab to `openshift/monitoring-plugin`
https://github.com/openshift/monitoring-plugin/pull/252

## Description
To consolidate the code between the Developer and Administrative perspectives, the Developer View > Observe > Silences Tab is being moved from openshift/console to openshift/monitoring-plugin.

- This PR removes the 'Silences' tab in the openshift/console.
- The corresponding PR renders the 'Silences' tab in the openshift/monitoring-plugin: https://github.com/openshift/monitoring-plugin/pull/252

## Testing Notes
- The `Developer View > Observe > Silences Tab` should not appear if you run the console without the monitoring-plugin. 
- The `Developer View > Observe > Silences Tab` should appear once you run the monitoring-plugin that includes this PR: https://github.com/openshift/monitoring-plugin/pull/252

### CODE REVIEW

**Comment by zhuje** [comment]
/hold

HOLD until openshift/monitoring-plugin is ready to serve this tab.

**Comment by logonoff** [comment]
/retitle CONSOLE-4330: Remove Developer perspective > Observe > Silences tab

**Comment by juzhao** [comment]
tested again
`launch 4.18,openshift/monitoring-plugin#252,openshift/console#14480 aws`
[OCPBUGS-44594](https://issues.redhat.com/browse/OCPBUGS-44594) is fixed

**Review by vikram-raj — COMMENTED** [review]
/lgtm

**Comment by zhuje** [comment]
/label docs-approved 
/label px-approved 

No Docs of Product approval needed because this PR just refactors code. No new features were added.

**Comment by zhuje** [comment]
/unhold 

https://github.com/openshift/monitoring-plugin/pull/252 has merged and has been reviewed by QE.

**Pull request merged**
