### PR TITLE
internal kubevirt 3

### PR DESCRIPTION
**Pull request by glekner**
- internal-kubevirt npm pkg patches
- internal-kubevirt npm pkg patches

### CODE REVIEW

**Comment by andrewballantyne** [comment]
I'm not sure exposing the store whole-hog is the best approach. I wonder what use-cases you need it for? I'd think the SDK probably should manage those specifically, but as your kubevirt internal package is to get you unblocked, I think this is fine for your work now. 👍 

I just don't think we'll do it from the SDK in the future. So that's where we need to understand use-cases and address those from the core SDK. cc @vojtechszocs @spadgett @christianvogt

**Comment by rawagner** [comment]
/label docs-approved
/label px-approved
/label qe-approved
/lgtm

This change only impacts internal Kubevirt specific SDK package. This has no impact on Console itself or existing plugin APIs.

**Pull request merged**
