### PR TITLE
Bug 2077138: fix {{execute}} regex for multiline executables in QuickStart

### PR DESCRIPTION
**Pull request by abhinandan13jan**
# Addresses
https://bugzilla.redhat.com/show_bug.cgi?id=2077138

# Issue
ConsoleQuickStart YAML does not support the {{copy}} or {{execute}} modifiers for multi-line code blocks if the blocks are indented as part of a list.

# Solution
Regex problem in {{execute}} quickstart block.
converts regex from `/```[\n]((.*?\n)+)```{{execute}}/g` to `/```[\n]\s*((((?!```).)*?\n)+)\s*```{{execute}}/g` 

# Screenshots
Screenshot 2022-05-31 at 10 11 56 PM
Screenshot 2022-05-31 at 10 12 02 PM

#Browser conformance
Chrome

### CODE REVIEW

**Comment by christianvogt** [comment]
Can you eliminate the leading white space and the trailing new line as shown in the screenshots.

**Comment by abhinandan13jan** [comment]
@christianvogt Aligning the pfext class with PF

**Review by sahil143 — APPROVED** [review]
/lgtm

verified on cluster bot

**Pull request merged**
