### PR TITLE
OCPBUGS-4047: further improve secrets integration test to mitigate fl…

### PR DESCRIPTION
**Pull request by rhamilto**
…akes

### CODE REVIEW

**Comment by jhadvig** [comment]
So I know we recently updated the Console centric CRDs towards using Cypress.
But I see following error in the CI:
```
ConsoleLink CRD
  Logging in as kubeadmin
    1) creates, displays, and deletes a new ConsoleLink help menu instance
    2) creates, displays, and deletes a new ConsoleLink user menu instance
  Logging out
  0 passing (3m)
  2 failing
  1) ConsoleLink CRD
       creates, displays, and deletes a new ConsoleLink help menu instance:
     AssertionError: Timed out retrying after 30000ms: Expected to find content: 'test-njlzg-cl help menu link' within the element: [ <a.pf-m-external.pf-c-app-launcher__menu-item>, 4 more... ] but never did.
      at Context.eval (https://console-openshift-console.apps.ci-op-vh5whdsh-75d12.xxxxxxxxxxxxxxxxxxxxxx/__cypress/tests?p=tests/crd-extensions/console-link.spec.ts:43960:18)
  2) ConsoleLink CRD
       creates, displays, and deletes a new ConsoleLink user menu instance:
     AssertionError: Timed out retrying after 30000ms: Expected to find content: 'test-njlzg-cl user menu link' within the element: <a.pf-m-external.pf-c-app-launcher__menu-item> but never did.
      at Context.eval (https://console-openshift-console.apps.ci-op-vh5whdsh-75d12.xxxxxxxxxxxxxxxxxxxxxx/__cypress/tests?p=tests/crd-extensions/console-link.spec.ts:43960:18)
```

Just FYI @rhamilto

**Comment by rhamilto** [comment]
> So I know we recently updated the Console centric CRDs towards using Cypress. But I see following error in the CI:
> 
> ```
> ConsoleLink CRD
>   Logging in as kubeadmin
>     1) creates, displays, and deletes a new ConsoleLink help menu instance
>     2) creates, displays, and deletes a new ConsoleLink user menu instance
>   Logging out
>   0 passing (3m)
>   2 failing
>   1) ConsoleLink CRD
>        creates, displays, and deletes a new ConsoleLink help menu instance:
>      AssertionError: Timed out retrying after 30000ms: Expected to find content: 'test-njlzg-cl help menu link' within the element: [ <a.pf-m-external.pf-c-app-launcher__menu-item>, 4 more... ] but never did.
>       at Context.eval (https://console-openshift-console.apps.ci-op-vh5whdsh-75d12.xxxxxxxxxxxxxxxxxxxxxx/__cypress/tests?p=tests/crd-extensions/console-link.spec.ts:43960:18)
>   2) ConsoleLink CRD
>        creates, displays, and deletes a new ConsoleLink user menu instance:
>      AssertionError: Timed out retrying after 30000ms: Expected to find content: 'test-njlzg-cl user menu link' within the element: <a.pf-m-external.pf-c-app-launcher__menu-item> but never did.
>       at Context.eval (https://console-openshift-console.apps.ci-op-vh5whdsh-75d12.xxxxxxxxxxxxxxxxxxxxxx/__cypress/tests?p=tests/crd-extensions/console-link.spec.ts:43960:18)
> ```
> 
> Just FYI @rhamilto

Noticed that, too.  Will investigate.

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
