### PR TITLE
[release-4.12] OCPBUGS-2182: re-enable operator-install-single-namespace.spec.ts test

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by rhamilto** [comment]
@TheRealJon, mind tagging this backport?

**Comment by jhadvig** [comment]
Its still failing `Installs Red Hat Integration - 3scale operator in test namespace and creates 3scale Backend operand instance` :(

**Comment by rhamilto** [comment]
> Its still failing `Installs Red Hat Integration - 3scale operator in test namespace and creates 3scale Backend operand instance` :(

This ran numerous times locally, so I'm going to assume this is a flake.  🤞

**Comment by rhamilto** [comment]
I've run both `operator-install-global.spec.ts` and `operator-install-global.spec.ts` locally against a 4.12.0-0.nightly-2023-07-15-021657 cluster and they passed numerous times.  Not sure what's going on in CI, but I am going to assume they are flakes and retest.

**Comment by yanpzhan** [comment]
Checked in log https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/13013/pull-ci-openshift-console-release-4.12-e2e-gcp-console/1682122663989874688, the test for install 3scale operator passed.
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
