### PR TITLE
Bug 2039065:  re-enable Bulk Import e2e test and increase wait

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by rhamilto** [comment]
Testing to see if this reduces failures in CI.

**Comment by rhamilto** [comment]
@dtaylor113, @jcaianirh with the increase in the wait included in this PR, I've yet to see the test flake despite repeated retests.  Thoughts on merging to see if it still flakes with this fix?

**Review by jcaianirh — APPROVED** [review]
/lgtm

**Pull request merged**
