### PR TITLE
[release-4.8] Bug 2008141: Allow web terminal to be installed in any namespace

### PR DESCRIPTION
**Pull request by JPinkney**
This is a backport of https://github.com/openshift/console/pull/10045 to OpenShift 4.8.

Testing instructions (if neccessary):
1. Deploy the console changes to your cluster following https://github.com/openshift/console#steps with the image set as: `quay.io/jpinkney/console:4.8-namespaces`
2. Install web terminal catalogsource with the web terminal changes:
```bash
cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: custom-web-terminal-catalog
  namespace: openshift-marketplace
spec:
  displayName: Web Terminal Operator Catalog
  image: quay.io/jpinkney/web-terminal-operator-index@sha256:70e4f05ef522f1fd197db6a2cc364c36b1facf0af41d0303af6e7fbdc0bff0ba
  publisher: Red Hat
  sourceType: grpc
EOF
``` 
3. Create a subscription and operator group in a non openshift-operators namespace
```bash
# Create the test namespace
oc new-project web-terminal-test

# Create the operator group
cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: web-terminal-test
  namespace: web-terminal-test
EOF

# Create the subscription
cat <<EOF | oc apply -f -
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: web-terminal
  namespace: web-terminal-test
spec:
  channel: fast
  installPlanApproval: Automatic
  name: web-terminal
  source: custom-web-terminal-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: web-terminal.v1.3.1
EOF
```
4. Make sure that the console operator has the correct permissions. It can be done easily by checking out [this pr](https://github.com/openshift/console-operator/pull/588) and then using:
```bash
watch -n 1 oc apply -f manifests/03-rbac-role-cluster.yaml
```

To actually verify that everything is working:
1. Login as normal user or admin and create a web terminal. Verify that everything is working as expected
2. Create a new subscription in a different namespace. Verify that the console will fail to open the next time with an error saying: `found multiple subscriptions for web-terminal when only one should be found`
3. Remove the subscription and verify that opening the terminal will work again

### CODE REVIEW

**Comment by jerolimov** [comment]
@christianvogt @sahil143 Happy new year. :smile: You approved / lgtm'ed the PRs #10045 and #10135, can you check this backport here as well?

**Comment by jerolimov** [comment]
/retitle [release-4.8] Bug 2008141: Allow web terminal to be installed in any namespace
/remove-lifecycle stale
/cc @sahil143

**Review by jhadvig — APPROVED** [review]
/lgtm

**Comment by sanketpathak** [comment]
Verified in cluster using cluster-bot
Screenshot from 2022-01-28 14-26-43
/qe-approved

**Pull request merged**
