### PR TITLE
Bug 1891419: Wrong detail head on network policy detail page

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @spadgett

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Review by dtaylor113 — APPROVED** [review]
I was going to just update this in my i18n networking pages open PR, but this is already in place and approved.

**Comment by spadgett** [comment]
> I was going to just update this in my i18n networking pages open PR, but this is already in place and approved.

We probably want to backport, so I'd keep it as a separate PR.

**Pull request merged**
