### PR TITLE
updates icon for serverless functions

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes**: 
https://issues.redhat.com/browse/ODC-5718

**Solution Description**: 
Update icon for Serverless function as provided from UXD.

**Screen shots / Gifs for design review**: 

image

cc @openshift/team-devconsole-ux

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by wtrocki** [comment]
FYI - I have launched prow job to build cluster on this PR:
`launch openshift/console#8525`

**Comment by nemesis09** [comment]
tested locally
icon update is reflected in topology
/lgtm

**Review by serenamarie125 — APPROVED** [review]
looks great!

**Review by bgliwa01 — APPROVED** [review]
lgtm!

**Pull request merged**
