### PR TITLE
OCPBUGS-38651: i18n misses for some provisioner on Create storageclass page

### PR DESCRIPTION
**Pull request by cyril-ui-developer**

### CODE REVIEW

**Review by sg00dwin — APPROVED** [review]
/lgtm

**Comment by cyril-ui-developer** [comment]
@jhadvig Updated due to the missing "Select Provisioner" string in the duplicate bug-OCPBUGS-41595.

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
