### PR TITLE
Type-Check Test Files

### PR DESCRIPTION
**Pull request by alecmerdler**
### Description

Reverts https://github.com/openshift/console/pull/1708/files#diff-64282092d7b77f064e3f06a569429a99

### CODE REVIEW

**Comment by christianvogt** [comment]
@vojtechszocs by excluding these dirs, we are missing type checks entirely on those files. webpack dev was the only tool in our process performing type checking.

/lgtm

**Comment by alecmerdler** [comment]
@christianvogt Had to fix an issue in `protractor.conf.ts`, ready for review again.

**Comment by vojtechszocs** [comment]
> @vojtechszocs by excluding these dirs, we are missing type checks entirely on those files. webpack dev was the only tool in our process performing type checking.

Yes, it seems that `yarn dev` is currently the only tool to cover that.

**Pull request merged**
