### PR TITLE
CONSOLE-3902: External login command modal

### PR DESCRIPTION
**Pull request by TheRealJon**
Add external OIDC copy login command modal to masthead toolbar and "Command Line Tools" page.

### CODE REVIEW

**Comment by TheRealJon** [comment]
@jhadvig This PR is ready for review!

**Comment by TheRealJon** [comment]
/retest

Flake

**Comment by TheRealJon** [comment]
/retest

cluster install failed

**Review by jhadvig — APPROVED** [review]
One small nit, otherwise its good to go 👍 
Nice work @TheRealJon 🙌

**Comment by yanpzhan** [comment]
After several rounds test against the pr, the copy login feature works as expected. If there is not further code update, I will add qe-approve label.

**Comment by yanpzhan** [comment]
The feature works against current code. 
/label qe-approved

**Pull request merged**
