### PR TITLE
Bug 1813902: [UI][Operator] Position of "Update Channel" should be prior to "Installation Mode" when Create Operator Subscription from UI

### PR DESCRIPTION
**Pull request by cyril-ui-developer**
/assign @TheRealJon
/cc @benjaminapetersen @spadgett

Backport to 4.4

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
/assign @rhamilto 

bug reporter.

**Comment by sdodson** [comment]
/bugzilla refresh
(to pick up bug retargetting to 4.4.z)

**Comment by sdodson** [comment]
Is this a dupe of https://github.com/openshift/console/pull/4680 or vice versa?

**Comment by cyril-ui-developer** [comment]
The Bot created a backport for this PR - https://github.com/openshift/console/pull/4680.

**Pull request closed without merging**
