### PR TITLE
[release-4.10] OCPBUGS-2717: Update dependencies to the registry library and devfile parser

### PR DESCRIPTION
**Pull request by kim-tsao**
Backport changes from 4.12 PR: https://github.com/openshift/console/pull/12043

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Tested this as described here https://github.com/openshift/console/pull/12043#pullrequestreview-1129518578 on my local machine and the timeout works fine.

/label backport-risk-assessed
/lgtm
/approve

**Comment by jerolimov** [comment]
/retitle [release-4.10] OCPBUGS-2717: Update dependencies to the registry library and devfile parser

**Comment by jerolimov** [comment]
@kim-tsao gofmt fails:

```
Checking gofmt...
gofmt checking failed:
pkg/devfile/sample.go
```

**Comment by kim-tsao** [comment]
> @kim-tsao gofmt fails:
> 
> ```
> Checking gofmt...
> gofmt checking failed:
> pkg/devfile/sample.go
> ```

@jerolimov can I get a retest?

**Comment by jerolimov** [comment]
Re-tested as described here https://github.com/openshift/console/pull/12043#pullrequestreview-1129518578 

1. With a network call that takes 10 seconds, the samples are shown after 3 seconds (not part of this PR) and the `/api/devfile` API call fails after 5 seconds. :heavy_check_mark:

https://user-images.githubusercontent.com/139310/200821107-316e6b26-e8b4-4420-90a8-d631d9c237d4.mp4

2. Working example without timeout URL :heavy_check_mark:

https://user-images.githubusercontent.com/139310/200821462-b99ab5ef-8aa0-40bf-bad5-3b3c1e22d3ac.mp4

/lgtm
@jhadvig, can you please add approval for this.
@sanketpathak, can you test this on a cluster and add cherry-pick-approved as well.

**Pull request merged**
