### PR TITLE
[release-4.8] Bug 2019301: Check for resource in ServiceBinding spec's service reference

### PR DESCRIPTION
**Pull request by rottencandy**
Manual cherry pick of #10327 

Conflict occurred due to changed imports.

### CODE REVIEW

**Review by rohitkrai03 — APPROVED** [review]
/lgtm
/approve

**Comment by jrichter1** [comment]
Tested and verified with cluster-bot
/label cherry-pick-approved

**Comment by jerolimov** [comment]
Wait for #10918
/hold

**Pull request merged**
