### PR TITLE
Add ability to delete connectors in topology

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Closes https://jira.coreos.com/browse/ODC-878

delete-connectors

@serenamarie125 @Veethika @beanh66 @sspeiche

### CODE REVIEW

**Comment by andrewballantyne** [comment]
It's looking good @jeff-phillips-18 - I'd give a `lgtm` right now but I am wondering if there is a better way we can handle overlapping labels and action items (like the delete).

Eg:
image

I'm not a fan of the overlap, so I am just going to poke around for a bit to see if I can find a fix to this.

**Comment by andrewballantyne** [comment]
> It's looking good @jeff-phillips-18 - I'd give a `lgtm` right now but I am wondering if there is a better way we can handle overlapping labels and action items (like the delete).
> 
> Eg:
> ...
> 
> I'm not a fan of the overlap, so I am just going to poke around for a bit to see if I can find a fix to this.

The suggestion I have actually is similar to how you render the _create connection arrow_.

The main rendering would be something like this: 

```
<g transform={zoomTransform}>
  <g>
    // groups
  </g>
  <g>
    // edges
  </g>
  <g>
    // nodes
  </g>
  <g>
    // actions (interactables that need to be on top of everything)
    // eg:
    //  - this.renderCreateConnection()   <-- move out of the nodes group
    //  - this.renderMoveConnection()     <-- move out of the nodes group
    //  - this.renderConnectionActions()  <-- this is the new addition
  </g>
</g>
```

If we just put the action itself on top, it will go from this:
Screen Shot 2019-09-06 at 12 32 03 PM

To something like this:
Screen Shot 2019-09-06 at 12 33 41 PM

Obviously that still needs some work, but I think this has more promise for giving the user easier access to the actions (which may expand upon a delete / have other use-cases).

Thoughts? We definitely should question if this is worth the effort today (given the upcoming release), but I think it's something we should look into as an action item for the QoL using the Topology view.

**Comment by jeff-phillips-18** [comment]
Thanks @andrewballantyne, I can look into implementing that. I can do it as a follow on or as part of this PR. If you're ok with a follow on, please add a bug to fix the overlap issue.

**Comment by andrewballantyne** [comment]
> Thanks @andrewballantyne, I can look into implementing that. I can do it as a follow on or as part of this PR. If you're ok with a follow on, please add a bug to fix the overlap issue.

JIRA Bug: https://jira.coreos.com/browse/ODC-1792

**Pull request merged**
