### PR TITLE
Bug 1887380: Add additional provisioners to their AccessMode mapping

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @spadgett 

cc'ing @jsafrane

### CODE REVIEW

**Comment by spadgett** [comment]
Hi @jhadvig. I'm a little unclear on the fix here since the Bugzilla is asking about `volumeMode` and not `accessModes`.

**Comment by jhadvig** [comment]
@spadgett sorry I've pasted wrong BZ number.

**Review by spadgett — APPROVED** [review]
/lgtm

**Review by zherman0 — APPROVED** [review]

**Pull request merged**
