### PR TITLE
Gherkin  and Automation for dev console usability improvements

### PR DESCRIPTION
**Pull request by sanketpathak**
Epic: https://issues.redhat.com/browse/ODC-6303
Story: https://issues.redhat.com/browse/ODC-6421

Acceptance criteria:

-  The Add page should provide access to the same Quick Add/Search feature that we have available in the topology
-  The "Logs" tab of a failed PipelineRun should include the "Log snippet"

**Checks required for approving Epic gherkin scripts PR:**

- [x] Add @epic-number to the scenarios or feature file [e.g: @odc-xxx]
- [x] Add @to-do for automation possible scenarios
- [x] Add @regression or @smoke based on the importance of the scenario
- [x] Update the test scenarios count in [Automation status confluence Report](https://docs.jboss.org/display/ODC/Automation+Status+Report)
- [x] Check for the linter issues by executing `yarn run gherkin-lint` on frontend folder [Skip epic number tags related linter issues]

**Fix**: https://issues.redhat.com/browse/ODC-6423

**Test Setup**:

Check the TAGS in frontend/packages/dev-console/integration-tests/cypress.json file be: ""(@pre-condition or @smoke or @regression) and not (@manual or @to-do or @un-verified or @broken-test)"",

Command to execute:

Run a cluster locally and execute the command `yarn run dev` and then `npm run test-cypress-dev-console` simultaneously

Execute the quick-search-add.feature file

**Browser**
Chrome 90

**Test Execution Screenshot:**
Screenshot from 2021-11-25 00-55-30

### CODE REVIEW

**Comment by vikram-raj** [comment]
I ran the test locally and one of the test is falling.

image

**Comment by jrichter1** [comment]
Getting some nice green runs now
quickadd

/lgtm

**Comment by vikram-raj** [comment]
image

one test is still failing for me.

**Review by vikram-raj — COMMENTED** [review]
image

All tests passed.

/lgtm

**Review by jerolimov — APPROVED** [review]
UI changes only adds additional `data-test` attributes.

/approve

**Comment by jerolimov** [comment]
This PR only affects our e2e tests.

/label qe-approved
/label px-approved
/label docs-approved

**Pull request merged**
