### PR TITLE
OCPBUGS-18604: [knative] Don't rely on openshift/hello-openshift as a sample image

### PR DESCRIPTION
**Pull request by cardil**
Fixes https://issues.redhat.com//browse/OCPBUGS-18604

The docs have been migrated already: https://github.com/openshift/openshift-docs/pull/60772. This is for the samples in the OCP Web console.

### CODE REVIEW

**Comment by sanketpathak** [comment]
Edited knative tests run green
/label qe-approved

**Comment by cardil** [comment]
Can we merge this? It should be effective in Serverless 1.30

**Review by Lucifergene — COMMENTED** [review]
Verified Unit tests and E2E tests.

/lgtm

**Comment by Lucifergene** [comment]
@vikram-raj PTAL for Approval

**Comment by Lucifergene** [comment]
/retitle OCPBUGS-18604: [knative] Don't rely on openshift/hello-openshift as a sample image

**Comment by Lucifergene** [comment]
Moved the ticket from ODC to OCPBUGS to be able to backport to the previous releases

**Comment by Lucifergene** [comment]
Setting this label as the Priority of this ticket is set to Major in Jira.
/acknowledge-critical-fixes-only

**Comment by Lucifergene** [comment]
Setting this label as the Priority of this ticket is set to Major in Jira.
/label acknowledge-critical-fixes-only

**Comment by cardil** [comment]
> _@vikram-raj: /approve_

Seems to be ineffective?!?

**Pull request merged**
