### PR TITLE
Bug 2060583: Remove internal-kubevirt Console plugin SDK package

### PR DESCRIPTION
**Pull request by vojtechszocs**
Removed code and configuration associated with `@openshift-console/dynamic-plugin-sdk-internal-kubevirt` package.

### CODE REVIEW

**Comment by spadgett** [comment]
```
TSError: ⨯ Unable to compile TypeScript:
scripts/generate-pkg-assets.ts(8,3): error TS2305: Module '"./package-definitions"' has no exported member 'getInternalKubevirtPackage'.
```

**Review by bipuladh — APPROVED** [review]

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
