### PR TITLE
Bug 1961391: Textual updates follow-up

### PR DESCRIPTION
**Pull request by rexagod**
This PR:
* Covers the corner case where there are a lot of storage classes.
* Removes the un-used `commaSeparatedString` method.

### CODE REVIEW

**Comment by rexagod** [comment]
Follows up on https://github.com/openshift/console/pull/9333

**Review by afreen23 — APPROVED** [review]
/lgtm

**Comment by rexagod** [comment]
/hold
Need to fix a test case.

**Pull request merged**
