### PR TITLE
OCPBUGS-2344:Change annotation to be used for fake helm repositories

### PR DESCRIPTION
**Pull request by Kartikey-star**
This PR realigns the annotations to be used for a fake helm repository as per  https://issues.redhat.com/browse/OCPBUGS-1959.
Signed-off-by: Kartikey Mamgain <mamgainkartikey@gmail.com>

### CODE REVIEW

**Comment by Kartikey-star** [comment]
Hi @debsmita1 @jerolimov the following annotation is getting returned in the index. When the user corrects the url or removes the repository the annotation is getting removed too.
Screenshot 2022-10-14 at 12 39 38 PM


Screenshot 2022-10-14 at 12 34 18 PM

**Review by jerolimov — APPROVED** [review]
The message and code look fine, thanks for this change! For lgtm label someone need to run this locally.

/cc @debsmita1 @jerolimov 
/approve

**Review by jerolimov — APPROVED** [review]
Tested it locally, works fine.

/lgtm

**Pull request merged**
