### PR TITLE
CCXDEV-7039: make severity links clickable in Insights Advisor widget

### PR DESCRIPTION
**Pull request by gkarat**
The patch enables the links in the dashboard's Insights Advisor widget and points them to the Insights Advisor application with respective pre-filled filter parameters. Besides that, the overall look of the widget is improved according to the latest mockups.

- [x] Enable severity links and point them to Insights Advisor
- [x] Edit "View all" description link and point it to Insights Advisor instead of OCM
- [x] Reverse order of the legend items
- [x] Adjust widget styles to meet the mockup requirements

Links list:
```
Critical: https://console.redhat.com/openshift/insights/advisor/clusters/\{clusterId}?total_risk=4
Important: https://console.redhat.com/openshift/insights/advisor/clusters/\{clusterId}?total_risk=3
Moderate: https://console.redhat.com/openshift/insights/advisor/clusters/\{clusterId}?total_risk=2
Low: https://console.redhat.com/openshift/insights/advisor/clusters/\{clusterId}?total_risk=1
View all: https://console.redhat.com/openshift/insights/advisor/clusters/\{clusterId}
```

Screenshot from 2022-01-18 21-42-57

### CODE REVIEW

**Comment by gkarat** [comment]
Blocked by https://github.com/openshift/console/pull/10826.

**Review by spadgett — APPROVED** [review]
/approve

LGTM, we'll wait for #10826 to merge

**Comment by jcaianirh** [comment]
QE Approver:
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

**Comment by yapei** [comment]
@yanpzhan Could you help test the PR?

**Comment by yanpzhan** [comment]
@gkarat I tested on a cluster launched against the pr, found that the "View all" url is "https://console.redhat.com/openshift/insights/advisor/fa402bd0-9e23-4765-9fad-f032f623875c". Checked in the pr code, it's " href={`https://console.redhat.com/openshift/insights/advisor/${clusterID}`}". Missed the "clusters".
they are not consistent with design "View all: https://console.redhat.com/openshift/insights/advisor/clusters/\{clusterId}"

**Comment by gkarat** [comment]
> @gkarat I tested on a cluster launched against the pr, found that the "View all" url is "https://console.redhat.com/openshift/insights/advisor/fa402bd0-9e23-4765-9fad-f032f623875c". Checked in the pr code, it's " href={`https://console.redhat.com/openshift/insights/advisor/${clusterID}`}". Missed the "clusters". they are not consistent with design "View all: [https://console.redhat.com/openshift/insights/advisor/clusters/\{clusterId}](https://console.redhat.com/openshift/insights/advisor/clusters/%5C%7BclusterId%7D)"

@yanpzhan, thank you, and yes, this is indeed incorrect. I have just modified the commit and updated the wrong lings. Could you please take a look once more?

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
