### PR TITLE
Bug 1863402: Developer console tables show extra columns due to projects table columns change

### PR DESCRIPTION
**Pull request by DaoDaoNoCode**
Add `isColumnManagementEnabled` props to `ProjectTableRow` so it will not render the two additional columns even if they are chosen in the page under admin view.

### CODE REVIEW

**Comment by spadgett** [comment]
@DaoDaoNoCode Is it possible to enable custom columns for the Developer perspective as well? As a user, I'd want my columns to be used in both perspectives.

I'm not familiar with how the Developer perspective is changing the Project list. cc @christianvogt

**Comment by DaoDaoNoCode** [comment]
@spadgett Yes I think it's possible to enable custom columns for the Developer perspective. However, this is likely adding new features that is not included in version 4.6. What's more, if it is added, all the pages with a table under Developer perspective can use column management modal when "all projects" is selected. Do we still need to implement it now?

**Comment by spadgett** [comment]
Closing in favor of #6601

/close

**Pull request closed without merging**
