### PR TITLE
Bug 2065513: Fix ResourceQuota dashboard card and ACRQ donut label

### PR DESCRIPTION
**Pull request by TheRealJon**
- Add separate sections on resource quota dashboard card for ResourceQuota and AppliedClusterResourceQuotas
- Use humanizePercentage on ACRQ donut label

**Before**
image

**After**
image

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by nima-rx** [comment]
is it possible to cherry-pick it to 4.10 as well.
@TheRealJon

**Pull request merged**
