### PR TITLE
[release-4.8] Bug 1987167: Add inspect url to devconsole monitoring chart

### PR DESCRIPTION
**Pull request by rottencandy**
Manual cherry pick of #9641 

https://issues.redhat.com/browse/ODC-6094

/kind bug

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Tested this backport with Firefox and Chrome. Code looks similar to the origin PR. Manually cherry-pick was only needed because of the import reorder.

/lgtm
/approve

**Comment by ecordell** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped*

* Score: *0.20*
* Reason: *skipping for now, may still be tagged today*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by ecordell** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped*

* Score: *0.20*
* Reason: *missed cutoff this week*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by rottencandy** [comment]
Rebased.

**Review by jerolimov — APPROVED** [review]
Tested the new version again with cluster-bot and Firefox

**Pull request merged**
