### PR TITLE
[release-4.7] Bug 1942864: Warning Alert for Encrypted PVs in Create StorageClass

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
image

**Comment by GowthamShanmugam** [comment]
@cloudbehl Please review

**Comment by GowthamShanmugam** [comment]
@spadgett we are not making any changes to kubevirt. Could you please override the test? Thank you.

**Comment by russellb** [comment]
This is blocked because the kubevirt-plugin is broken. #8619 is needed to resolve it

**Comment by mfojtik** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.


* Score: *0.20*
* Reason: *maximum total for this z-stream is 10*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by bipuladh** [comment]
/retitle [release-4.7] Bug 1942864: Warning Alert for Encrypted PVs in Create StorageClass

**Comment by GowthamShanmugam** [comment]
@spadgett Please merge this

**Comment by sdodson** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*We've hit capacity of 50 for this week.*

* Score: *0.20*
* Reason: *maximum QE capacity for all z-stream is 50*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

approved

**Pull request merged**
