### PR TITLE
OCPBUGS-28917: Optimize federation of shared PF5 code for dynamic plugins

### PR DESCRIPTION
**Pull request by vojtechszocs**
This is a single PR backport of the following changes:
- #13388
- #13521

This was a clean backport, no merge conflicts detected.

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/approve
/label backport-risk-assessed

**Comment by XiyunZhao** [comment]
This PR has been tested by following the step on PR#13388 and the step in case OCP-71228, no issue was found
/label qe-approved

**Pull request merged**
