### PR TITLE
Bug 2055702: e2e tests: enable serverless tests

### PR DESCRIPTION
**Pull request by vikram-raj**
Enable Serverless tests as Serverless operator is now available in Operator hub

### CODE REVIEW

**Comment by jrichter1** [comment]
I think I accidentally committed the interim operator label, it needs to be reverted 
https://github.com/openshift/console/blob/master/frontend/packages/dev-console/integration-tests/support/pages/operators-page.ts#L100

@vikram-raj can you uncomment the mentioned line and remove the get below it?

**Comment by vikram-raj** [comment]
> I think I accidentally committed the interim operator label, it needs to be reverted https://github.com/openshift/console/blob/master/frontend/packages/dev-console/integration-tests/support/pages/operators-page.ts#L100
> 
> @vikram-raj can you uncomment the mentioned line and remove the get below it?

Sure, I will do it.

**Comment by jrichter1** [comment]
@vikram-raj I've opened https://github.com/openshift/console/pull/11124 to work around the test issue. If it succeeds, I think we can close this PR.

**Comment by vikram-raj** [comment]
closing it as we have PR https://github.com/openshift/console/pull/11124 opened to enable serverless e2e tests.

/close

**Pull request closed without merging**
