### PR TITLE
Bug 1802525: update Go and .NET logos

### PR DESCRIPTION
**Pull request by karthikjeeyar**
Fixes: https://issues.redhat.com/browse/ODC-3049

Analysis / Root cause:
Icons for dotnet and go has changed

Solution Description:
Updated the dotnet and go logos in the console. Changes will reflect in throughout the devconsole as well.

Screen shots / Gifs for design review:

image

Dev catalog Sidepanel: 
image

cc: @serenamarie125

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
/retitle Bug 1802525: update Go and .NET logos

**Comment by christianvogt** [comment]
@karthikjeeyar I suggest you keep the `go-gopher.svg` file and add a new icon named `golang.svg`. There are separate icons in the catalog and probably best to just add the new icon for `icon-golang`.

```
  .set('icon-go-gopher', goGopherImg)
  .set('icon-golang', goGopherImg)
```

**Comment by sahil143** [comment]
@karthikjeeyar Icons are correct on the topology page but on builder images,  I am seeing the old go icon.
Screenshot from 2020-02-14 13-01-42

**Comment by karthikjeeyar** [comment]
> @karthikjeeyar Icons are correct on the topology page but on builder images, I am seeing the old go icon.
> Screenshot from 2020-02-14 13-01-42

@sahil143  @christianvogt  This happens because still we are getting the old icon class (`icon-go-gopher`) in the builder Image api response, 
If we change this icon class to point new golang icon then it will be changed in catalog as well.

image

**Comment by christianvogt** [comment]
argh so sorry @karthikjeeyar 
I didn't realize that our imagestream for golang was using `icon-go-gopher` :(

Ok please make the change back so that even `icon-go-gopher` uses the new go logo.

Confirmed with UX.

**Pull request merged**
