### PR TITLE
[release-4.8] Bug 2060616: Add error boundary in edit-flows

### PR DESCRIPTION
**Pull request by jerolimov**
This is a manual backport of #9253, originally done by @divyanshiGupta 

/cc @divyanshiGupta

### CODE REVIEW

**Comment by jerolimov** [comment]
Stop wasting cpu cycles, need to check the tests
/hold

**Comment by jerolimov** [comment]
Root cause of the failing tests:

image

Argh.

**Comment by jerolimov** [comment]
Verified this on a cluster:

https://user-images.githubusercontent.com/139310/157036231-e1ae04e8-80a7-4bbf-9693-f40ff1b8d91c.mp4

**Comment by sanketpathak** [comment]
Works for the change in parameter value
/label cherry-pick-approved

**Comment by jerolimov** [comment]
#11141 merged to fix e2e
/unhold

**Pull request merged**
