### PR TITLE
CONSOLE-3181: Deprecate useAccessReviewAllowed and useSafetyFirst

### PR DESCRIPTION
**Pull request by tvu20**
Deprecates useAccessReviewAllowed and useSafetyFirst.
Allows 'api.md' doc to generate deprecated tags and sorts deprecated items to bottom.

### CODE REVIEW

**Review by andrewballantyne — APPROVED** [review]
/lgtm

It's interesting that the solution differed from our extensions api -- but this is cleaner. Might need to relook at your extensions generator at some to align the two on the same principles.

**Comment by tvu20** [comment]
QE Approver:
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

**Comment by yapei** [comment]
in `docs/api.md`, `[DEPRECATED]` sections can be generated and sorted to bottom
```
55.  [`usePrometheusPoll`](#useprometheuspoll)
56.  [`Timestamp`](#timestamp)
57. [DEPRECATED] [`PerspectiveContext`](#perspectivecontext)
58. [DEPRECATED] [`useAccessReviewAllowed`](#useaccessreviewallowed)
59. [DEPRECATED] [`useSafetyFirst`](#usesafetyfirst)
......
## `useSafetyFirst`

### Summary [DEPRECATED]

@deprecated - This hook is not related to console functionality.<br/>Hook that ensures a safe asynchronnous setting of React state in case a given component could be unmounted.<br/>(https://github.com/facebook/react/issues/14113)
### Parameters
| Parameter Name | Description |
| -------------- | ----------- |
| `initialState` | initial state value |
### Returns
An array with a pair of state value and it's set function.
```
/label qe-approved

**Pull request merged**
