### PR TITLE
CONSOLE-3126: Remove paused state since its no longer relevant due to 4.14 changes …

### PR DESCRIPTION
**Pull request by sg00dwin**
…on paused certificates

https://issues.redhat.com/browse/CONSOLE-3126

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

QE Approver: 
/assign @yanpzhan
PX Approver:
/assign @RickJWagner
Docs Approver:
/assign @opayne1

**Comment by yanpzhan** [comment]
Update a cluster to an image which was built from the pr code. Choose "Pause update" for worker node, on the progress part, there is not "Update is paused. Resume update as soon as possible." now.
Screenshot from 2023-08-09 18-01-43
@sg00dwin What else needs to be checked for paused upgrade on the page?

**Comment by yanpzhan** [comment]
Saw Steve's comment in jira CONSOLE-3126.  I think the test is acceptable for now. Accept the pr.
/label qe-approved

**Pull request merged**
