### PR TITLE
Bug 1922015:  prevent catalog modal header from collapsing

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1922015

After:
Screen Shot 2021-02-01 at 9 19 33 AM

### CODE REVIEW

**Comment by rhamilto** [comment]
Temp fix for [upstream issue](https://github.com/patternfly/patternfly/issues/3825).

**Review by sg00dwin — APPROVED** [review]
/lgtm

**Pull request merged**
