### PR TITLE
Bug 2022253: fix web terminal resize layout issue

### PR DESCRIPTION
**Pull request by sahil143**
**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-37085

**Screen shots / Gifs for design review**: 

Kapture 2022-01-27 at 14 41 38

**Unit test coverage report**: None

**Test setup:**

- Install WebTerminal operator
- Click on Web terminal icon in masthead to open terminal
- Resize web terminal window

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Edge

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
2 scrolls bar is present in the terminal window. See the GIF.

Kapture 2022-01-27 at 18 00 23

**Comment by rhamilto** [comment]
@sg00dwin, mind taking this one?  At this point, you're much more familiar with the layout CSS than I am.

**Comment by christianvogt** [comment]
The double scroll bar issue can be dealt with separately as I believe it was a previous outstanding issue and it seems unrelated to the main app layout.
But if we can address it in a timely manner here we may as well. Otherwise post a separate pr.

**Comment by invincibleJai** [comment]
Looks good!!

Double scroll bar as well got fixed, thanks @sahil143 

I verified in-cluster on chrome/firefox

webTermSp


cc @christianvogt @vikram-raj

**Comment by invincibleJai** [comment]
@sg00dwin PTAL if you get time, it'll be nice to get this fix in 4.10. Thanks :)

**Comment by christianvogt** [comment]
Putting on hold to wait for @sg00dwin if there's any concerns.
/hold

@sahil143 Please make sure this gets tested on all conformance browsers.

**Comment by sahil143** [comment]
@christianvogt I tested the changes on all four browsers(Chrome, Firefox, Safari, Edge) and it works as expected.

**Review by vikram-raj — COMMENTED** [review]
Tested it on Chrome 97.0.4692.99, Firefox 96.0.2 and Safari 15.1. And its works as expected

**Review by sg00dwin — APPROVED** [review]
Tested changes in Chrome, Firefox, Edge, Safari and works good, no issue found.

Note: https://github.com/openshift/console/pull/10856 involves changes to page scroll, so will want to confirm things function properly with both sets of changes.

**Pull request merged**
