### PR TITLE
Bug 1835814: Auto fill application group name in event source flows

### PR DESCRIPTION
**Pull request by divyanshiGupta**
**Fixes:** https://issues.redhat.com/browse/ODC-3522

**Solution:**
Auto fill application group name on event source selection

/kind bug

### CODE REVIEW

**Comment by invincibleJai** [comment]
@divyanshiGupta thanks,  i tried verifying it works on form Changes however on load i see an issue , PTAL gif 

evSrcAppname

**Comment by divyanshiGupta** [comment]
@invincibleJai yes I am working on fixing that. It happens since after the form values are set onLoad of `application-selector` is called again and there it sets the `application.name` as `' '`.

**Comment by andrewballantyne** [comment]
> @invincibleJai yes I am working on fixing that. It happens since after the form values are set onLoad of `application-selector` is called again and there it sets the `application.name` as `' '`.

@divyanshiGupta Any progress? (you also need to rebase)

**Comment by divyanshiGupta** [comment]
> > @invincibleJai yes I am working on fixing that. It happens since after the form values are set onLoad of `application-selector` is called again and there it sets the `application.name` as `' '`.
> 
> @divyanshiGupta Any progress? (you also need to rebase)

@andrewballantyne still trying to fix this but it seems difficult without having to refactor a lot of code in `ResourceDropdown`. And refactoring `ResourceDropdown` is going to take time as it is being used at other places also and have different usecases. Will try one more thing to avoid refactoring in this PR.

**Comment by andrewballantyne** [comment]
> @andrewballantyne still trying to fix this but it seems difficult without having to refactor a lot of code in `ResourceDropdown`. And refactoring `ResourceDropdown` is going to take time as it is being used at other places also and have different usecases. Will try one more thing to avoid refactoring in this PR.

If you cannot find a solution and this is a hinderance in getting a clean solution (haven't stopped to understand what the nuance of the problem is), perhaps we back out. The ticket is Medium on Priority and may be just easier than a risky solution this close to Code Freeze.

cc @invincibleJai

**Comment by divyanshiGupta** [comment]
@andrewballantyne @invincibleJai since application group name is not auto filled only in case of page load because of issues in `ResourceDropdown` and how `ApplicationSelector` uses it maybe we can have a separate bug to handle this scenario. It get auto filled in all other cases like after page load if an event source is selected and if create application item is selected from the dropdown. WDYT?

**Comment by andrewballantyne** [comment]
/assign @invincibleJai 

I defer to Jai, if needed I can catch up and answer.

**Comment by invincibleJai** [comment]
> @andrewballantyne @invincibleJai since application group name is not auto filled only in case of page load because of issues in `ResourceDropdown` and how `ApplicationSelector` uses it maybe we can have a separate bug to handle this scenario. With this PR it gets auto filled in all other cases like after page load if an event source is selected and if create application item is selected from the dropdown. WDYT?

Considering  `application group` is not a required field and will be auto populated in case create application is selected, and current solution also works in scenario where no app group exists it populates application group except on load. I don't see any harm with taking this PR in if the fix will take more effort and have an issue with scenario. As the fix may need to refactor application selector to support on load.

cc @andrewballantyne  let us know if it's fine.

**Comment by invincibleJai** [comment]
@divyanshiGupta pls create an issue to track this as we discussed

**Comment by divyanshiGupta** [comment]
@invincibleJai https://issues.redhat.com/browse/ODC-3960 bug for the on load issue.

**Pull request merged**
