### PR TITLE
Bug 1981399: Fix failing KubeVirt Protractor e2e tests

### PR DESCRIPTION
**Pull request by vojtechszocs**
KubeVirt Protractor end-to-end tests were failing due to test code `integration-tests/tests/*.scenario.ts` transitively importing Console internal code which directly references browser env. specifics, e.g. presence of `window` global.

- remove index file `packages/kubevirt-plugin/src/selectors/vm/index.ts` and adapt imports
- move relevant parts from `public/module/k8s/k8s.ts` to `public/module/k8s/k8s-ref.ts`
- for modules in `public/module/k8s` directory, avoid importing from `./index`

### CODE REVIEW

**Comment by vojtechszocs** [comment]
/hold

Needs verification.

**Comment by vojtechszocs** [comment]
cc @pcbailey @yaacov

**Comment by gouyang** [comment]
still not able to run kubevirt protractor test
```
./test-protractor.sh kubevirt                                                              
+ cd frontend
+ yarn install
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
warning Resolution field "jquery@3.5.1" is incompatible with requested version "jquery@~3.4.1"
warning Resolution field "minimist@1.2.5" is incompatible with requested version "minimist@0.0.8"
warning Resolution field "minimist@1.2.5" is incompatible with requested version "minimist@0.0.8"
warning Resolution field "minimist@1.2.5" is incompatible with requested version "minimist@~0.0.1"
success Already up-to-date.
$ yarn generate
yarn run v1.22.10
$ yarn generate-graphql && yarn build-plugin-sdk
$ graphql-codegen --config graphql-codegen.yml
  ✔ Parse configuration
  ✔ Generate outputs
$ yarn --cwd packages/console-dynamic-plugin-sdk build
$ yarn clean && yarn validate && yarn generate && yarn tsc
$ rm -rf ./dist
$ yarn ts-node ./scripts/validate-extensions.ts
$ ts-node -O '{"module":"commonjs"}' ./scripts/validate-extensions.ts
Validating Console extension types
Warnings (31)
    Extension type 'PVCCreateProp' has no JSDoc comments
    Extension type 'PVCStatus' has no JSDoc comments
    Extension type 'PVCAlert' has no JSDoc comments
    Extension type 'PVCDelete' has no JSDoc comments
    Extension type 'AddAction' has no JSDoc comments
    Extension type 'AddActionGroup' has no JSDoc comments
    Extension type 'ClusterGlobalConfig' has no JSDoc comments
    Extension type 'HrefNavItem' has no JSDoc comments
    Extension type 'ResourceNSNavItem' has no JSDoc comments
    Extension type 'ResourceClusterNavItem' has no JSDoc comments
    Extension type 'Separator' has no JSDoc comments
    Extension type 'NavSection' has no JSDoc comments
    Extension type 'FileUpload' has no JSDoc comments
    Extension type 'AlertAction' has no JSDoc comments
    Extension type 'AlertAction' property 'alert' has no JSDoc comments
    Extension type 'AlertAction' property 'text' has no JSDoc comments
    Extension type 'AlertAction' property 'action' has no JSDoc comments
    Extension type 'StorageProvider' has no JSDoc comments
    Extension type 'StorageProvider' property 'name' has no JSDoc comments
    Extension type 'StorageProvider' property 'Component' has no JSDoc comments
    Extension type 'TelemetryListener' has no JSDoc comments
    Extension type 'CatalogItemType' has no JSDoc comments
    Extension type 'CatalogItemProvider' has no JSDoc comments
    Extension type 'CatalogItemFilter' has no JSDoc comments
    Extension type 'TopologyDisplayFilters' property 'getTopologyFilters' has no JSDoc comments
    Extension type 'TopologyDisplayFilters' property 'applyDisplayOptions' has no JSDoc comments
    Extension type 'TopologyDecoratorProvider' property 'id' has no JSDoc comments
    Extension type 'TopologyDecoratorProvider' property 'priority' has no JSDoc comments
    Extension type 'TopologyDecoratorProvider' property 'quadrant' has no JSDoc comments
    Extension type 'TopologyDecoratorProvider' property 'decorator' has no JSDoc comments
    Extension type 'CreateResource' has no JSDoc comments
$ yarn generate-schema && yarn generate-doc && yarn generate-pkg-assets
$ yarn ts-node ./scripts/generate-schema.ts
$ ts-node -O '{"module":"commonjs"}' ./scripts/generate-schema.ts
Generating Console plugin JSON schemas
schema/plugin-package.json
schema/plugin-package.js
schema/console-extensions.json
schema/console-extensions.js
schema/plugin-manifest.json
schema/plugin-manifest.js
$ yarn ts-node ./scripts/generate-doc.ts
$ ts-node -O '{"module":"commonjs"}' ./scripts/generate-doc.ts
Generating Console plugin documentation
dist/doc/console-extensions.md
$ yarn ts-node ./scripts/generate-pkg-assets.ts
$ ts-node -O '{"module":"commonjs"}' ./scripts/generate-pkg-assets.ts
Generating Console plugin package.json
dist/package.json
Copying schema, license, and readme files
$ /home/gouyang/console/frontend/node_modules/.bin/tsc
Done in 31.03s.
Done in 32.61s.
+ '[' '' == firefox ']'
+ '[' -n '' ']'
+ yarn run webdriver-update --gecko=false
yarn run v1.22.10
$ webdriver-manager update --gecko=false
[14:41:58] I/file_manager - creating folder /home/gouyang/console/frontend/node_modules/webdriver-manager/selenium
[14:41:58] I/config_source - curl -o/home/gouyang/console/frontend/node_modules/webdriver-manager/selenium/standalone-response.xml https://selenium-release.storage.googleapis.com/
[14:41:58] I/config_source - curl -o/home/gouyang/console/frontend/node_modules/webdriver-manager/selenium/chrome-response.xml https://chromedriver.storage.googleapis.com/
[14:42:00] I/downloader - curl -o/home/gouyang/console/frontend/node_modules/webdriver-manager/selenium/selenium-server-standalone-3.141.59.jar https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
[14:42:00] I/downloader - curl -o/home/gouyang/console/frontend/node_modules/webdriver-manager/selenium/chromedriver_91.0.4472.101.zip https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_linux64.zip
[14:42:02] I/update - chromedriver: unzipping chromedriver_91.0.4472.101.zip
[14:42:02] I/update - chromedriver: setting permissions to 0755 for /home/gouyang/console/frontend/node_modules/webdriver-manager/selenium/chromedriver_91.0.4472.101
Done in 4.66s.
+ '[' 1 -gt 0 ']'
+ '[' -n kubevirt ']'
+ yarn run test-protractor-suite --suite kubevirt --params.openshift true
yarn run v1.22.10
$ yarn ts-node ./node_modules/.bin/protractor integration-tests/protractor.conf.ts --suite kubevirt --params.openshift true
$ ts-node -O '{"module":"commonjs"}' ./node_modules/.bin/protractor integration-tests/protractor.conf.ts --suite kubevirt --params.openshift true
Report destination:   gui_test_screenshots/protractor-report.html
[14:42:04] I/launcher - Running 1 instances of WebDriver
[14:42:04] I/direct - Using ChromeDriver directly...
I0728 14:42:07.934626    9942 request.go:621] Throttling request took 1.171331421s, request: GET:https://api.uit-02.cnv-qe.rhcloud.com:6443/apis/operator.openshift.io/v1alpha1?timeout=32s
[14:42:10] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
public/graphql/client.gql (1,7): ';' expected. (1005)
public/graphql/client.gql (1,20): ',' expected. (1005)
public/graphql/client.gql (1,31): ';' expected. (1005)
public/graphql/client.gql (2,15): ',' expected. (1005)
    at getOutput (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:141:19)
    at Object.compile (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:293:18)
    at Module.m._compile (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:234:49)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .js] (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:236:16)
    at Module.load (/home/gouyang/console/frontend/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gouyang/console/frontend/public/graphql/client.ts:19:22)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:234:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:236:16)
    at Module.load (/home/gouyang/console/frontend/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gouyang/console/frontend/public/module/k8s/get-resources.ts:6:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:234:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:236:16)
    at Module.load (/home/gouyang/console/frontend/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gouyang/console/frontend/public/actions/k8s.ts:14:25)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:234:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:236:16)
    at Module.load (/home/gouyang/console/frontend/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gouyang/console/frontend/public/reducers/features.ts:11:15)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:234:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:236:16)
    at Module.load (/home/gouyang/console/frontend/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gouyang/console/frontend/public/redux.ts:5:20)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:234:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:236:16)
    at Module.load (/home/gouyang/console/frontend/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gouyang/console/frontend/public/co-fetch.js:15:17)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:234:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .js] (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:236:16)
    at Module.load (/home/gouyang/console/frontend/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gouyang/console/frontend/public/module/k8s/resource.ts:4:20)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:234:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:236:16)
    at Module.load (/home/gouyang/console/frontend/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gouyang/console/frontend/public/module/k8s/index.ts:9:10)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:234:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:236:16)
    at Module.load (/home/gouyang/console/frontend/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gouyang/console/frontend/packages/kubevirt-plugin/src/models/kubevirtReferenceForModel.ts:3:15)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:234:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:236:16)
    at Module.load (/home/gouyang/console/frontend/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gouyang/console/frontend/packages/kubevirt-plugin/src/selectors/vm/vmlike.ts:5:37)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:234:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:236:16)
    at Module.load (/home/gouyang/console/frontend/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gouyang/console/frontend/packages/kubevirt-plugin/src/selectors/vm/devices.ts:7:18)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:234:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:236:16)
    at Module.load (/home/gouyang/console/frontend/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/gouyang/console/frontend/packages/kubevirt-plugin/integration-tests/tests/vm.detail.boot-order.scenario.ts:16:19)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Module.m._compile (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:234:29)
    at Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Object.require.extensions.<computed> [as .ts] (/home/gouyang/console/frontend/node_modules/ts-node/dist/index.js:236:16)
    at Module.load (/home/gouyang/console/frontend/node_modules/coffeescript/lib/coffee-script/register.js:45:36)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /home/gouyang/console/frontend/node_modules/jasmine/lib/jasmine.js:93:5
    at Array.forEach (<anonymous>:null:null)
    at Jasmine.loadSpecs (/home/gouyang/console/frontend/node_modules/jasmine/lib/jasmine.js:92:18)
    at Jasmine.execute (/home/gouyang/console/frontend/node_modules/jasmine/lib/jasmine.js:197:8)
    at /home/gouyang/console/frontend/node_modules/protractor/built/frameworks/jasmine.js:132:15
    at Function.promise (/home/gouyang/console/frontend/node_modules/protractor/node_modules/q/q.js:682:9)
    at /home/gouyang/console/frontend/node_modules/protractor/built/frameworks/jasmine.js:104:14
    at _fulfilled (/home/gouyang/console/frontend/node_modules/protractor/node_modules/q/q.js:834:54)
    at /home/gouyang/console/frontend/node_modules/protractor/node_modules/q/q.js:863:30
    at Promise.promise.promiseDispatch (/home/gouyang/console/frontend/node_modules/protractor/node_modules/q/q.js:796:13)
    at /home/gouyang/console/frontend/node_modules/protractor/node_modules/q/q.js:556:49
    at runSingle (/home/gouyang/console/frontend/node_modules/protractor/node_modules/q/q.js:137:13)
    at flush (/home/gouyang/console/frontend/node_modules/protractor/node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:77:11)

Closing report
```

**Comment by vojtechszocs** [comment]
@yaacov @gouyang PR updated, when running the following command locally

```
(cd frontend ; yarn test-protractor-suite --suite kubevirt --params.openshift true)
```

I've got to the point where Protractor starts executing test suites
```
>> Executing 136 defined specs...
```

Please check if this fixes the issue :smiley:

**Comment by vojtechszocs** [comment]
Seems like there are webpack build issues, will fix them.

**Comment by pcbailey** [comment]
I have been able to confirm that this PR allows me to reach the point where tests are being executed.

**Comment by yaacov** [comment]
/hold cancel

@vojtechszocs hi, i'm removing the hold because it waiting for verification that we now have.

**Pull request merged**
