### PR TITLE
[release-4.8] Bug 1984102: Switch Cypress OLM tests to use supported Red Hat operators

### PR DESCRIPTION
**Pull request by dtaylor113**
Backports of #9420 & #9681

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by dtaylor113** [comment]
Hi @yapei, not sure why this PR is requesting your review after you have added a `/lgtm` label?  Maybe it needs some sort of `approval` tag from you?

**Review by yapei — APPROVED** [review]
/lgtm

**Comment by yapei** [comment]
a new review comment is added, let's see if it works :  )

**Comment by dtaylor113** [comment]
Hi @spadgett, do we need to do something else to get this PR to merge?  -thanks

**Review by jhadvig — APPROVED** [review]
/lgtm

**Pull request merged**
