### PR TITLE
Clean up of CronJobSource code references

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes**: 
https://issues.redhat.com/browse/ODC-6486

**Analysis / Root cause**: 
CronJobSource is no longer supported with Serverless operator

**Solution Description**: 
Clean up of CronJobSource code references/update tests

**Screen shots / Gifs for design review**: 
No Visual changes

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by vikram-raj — APPROVED** [review]
Verified. works as expected.

**Comment by invincibleJai** [comment]
/label docs-approved
/label px-approved

Propagating from epic based on ACKs

**Pull request merged**
