### PR TITLE
[release-4.13] OCPBUGS-14267: Add Pipeline metrics unsupported empty page

### PR DESCRIPTION
**Pull request by vikram-raj**
Manual cherry-pick of PR https://github.com/openshift/console/pull/12435

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Tested this on a cluster bot instance:

image

/label backport-risk-assessed
/lgtm
/approve

**Comment by jerolimov** [comment]
Tested the update on a cluster bot.

/lgtm

**Comment by jerolimov** [comment]
Tested the update on a cluster bot.

/lgtm

**Comment by vikram-raj** [comment]
Manual cherry-pick PR https://github.com/openshift/console/pull/12977

**Pull request merged**
