### PR TITLE
[release-4.12] OCPBUGS-15474: Project admin can update and view subscription from operator details page

### PR DESCRIPTION
**Pull request by TheRealJon**
Manual backport of #12780
Depends on #13055

### CODE REVIEW

**Comment by TheRealJon** [comment]
/hold

Wait for #13055

**Review by jcaianirh — APPROVED** [review]

**Comment by XiyunZhao** [comment]
@TheRealJon since https://github.com/openshift/console/pull/12717 is tracking as a separate bug, I approve this one first, Please make sure the 4.12 backport PR for #12717 is in progress, otherwise catalog source info is invisible on Subscription page
/label qe-approved

**Comment by TheRealJon** [comment]
/retest
timed out

**Pull request merged**
