### PR TITLE
[release-4.14] OCPBUGS-33064: Fix PipelineRun Logs tab navigation

### PR DESCRIPTION
**Pull request by vikram-raj**
Manual cherry-pick of PR https://github.com/openshift/console/pull/13484

### CODE REVIEW

**Review by Lucifergene — COMMENTED** [review]
/lgtm

**Comment by Lucifergene** [comment]
/retitle [release-4.14] OCPBUGS-33064: Fix PipelineRun Logs tab navigation

**Comment by vikram-raj** [comment]
manual cherry-pick PR https://github.com/openshift/console/pull/13890

**Pull request merged**
