### PR TITLE
Bug 1889348: Remove Project link from Application Details page

### PR DESCRIPTION
**Pull request by divyanshiGupta**
**Jira:** https://issues.redhat.com/browse/ODC-5032

When going to the Application Stages view, and drilling into an Application, a Project link is shown for each environment that takes the user to the topology view with that project selected. This link is now inaccurate and should be removed, until we can get the appropriate information from the backend service.

image

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
cc: @serenamarie125

**Review by rohitkrai03 — APPROVED** [review]
/approve

Changes looks good to me. Will wait for @serenamarie125's approval before adding lgtm.

**Review by serenamarie125 — APPROVED** [review]
Looks good to me!  Thanks for taking care of this

**Pull request merged**
