### PR TITLE
add translation capabilities to extensions

### PR DESCRIPTION
**Pull request by christianvogt**
fixes: https://issues.redhat.com/browse/ODC-5103

Updates `useExtensions` to translate all strings which match the pattern `%...%`.

Supports translation strings within the `properties` object of an extension.

eg:
```
properties: {
  // t('namespace~My Label')
  label: '%My Label%'
}
```

Translated all `AddAction` extensions.
image

image

cc @vojtechszocs @spadgett

### CODE REVIEW

**Review by jeff-phillips-18 — APPROVED** [review]

**Comment by christianvogt** [comment]
added `useTranslation` mock to `catalog.spec.tsx`

**Review by vikram-raj — COMMENTED** [review]
Missed the `AddAction` translation in `pipelines-plugin` plugin.

**Pull request merged**
