### PR TITLE
Bug 1916860: Filter out helm charts based on kubernetes version

### PR DESCRIPTION
**Pull request by pedjak**
This is the manual cherry-pick of https://github.com/openshift/console/pull/7012 (could not applied automatically) and https://github.com/openshift/console/pull/7548

cc @spadgett and @akashshinde

### CODE REVIEW

**Comment by akashshinde** [comment]
Thanks @pedjak.

/lgtm

**Comment by jerolimov** [comment]
@pedjak This PR has unfortunately a merge conflict after many other PRs are merged today. Just FYI :)

**Comment by pedjak** [comment]
> This PR has unfortunately a merge conflict after many other PRs are merged today. Just FYI :)

Thanks @jerolimov - just got rebased.

**Review by akashshinde — APPROVED** [review]

**Comment by derekwaynecarr** [comment]
(Patch-Manager) approve as this meets criteria.

**Pull request merged**
