### PR TITLE
CONSOLE-2501: Update nodebuilder image

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @spadgett @jerolimov 

🤞

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Build (local) master and #12821 successfully with this builder image :+1:

/lgtm

**Comment by jerolimov** [comment]
:crossed_fingers: 

/lgtm

**Comment by spadgett** [comment]
/hold

This will still get replaced again with a Node 14 image during builds... I've opened a ticket with ART to find out what to do.

**Comment by locriandev** [comment]
This looks good to me. ART has already updated its downstream config, so new console builds should start using nodejs16.

**Comment by jhadvig** [comment]
Based on the conversation with @locriandev the 4.14 image should be containing the node-16 from today. So we either wait or we use the `registry.ci.openshift.org/ocp/builder:rhel-8-openshift-nodejs16-base-4.14.art` image as `nodebuilder`

**Comment by jerolimov** [comment]
Based on the ART feedback this pr is fine and will hopefully unblock our TS upgrade PR.

We can switch later again and have other follow up to improve this, so I hope it's fine to merge this @jhadvig @spadgett

/unhold

**Pull request closed without merging**
