### PR TITLE
Fixed popover issues

### PR DESCRIPTION
**Pull request by bipuladh**
- Fixed max-width issues
- Fixed overflow issues
Before:
Screenshot from 2019-11-15 16-31-12
Screenshot from 2019-11-15 16-42-28
After:
Screenshot from 2019-11-15 16-33-51
Screenshot from 2019-11-15 16-41-56

### CODE REVIEW

**Comment by rawagner** [comment]
@andybraren are you ok with this change ?

**Comment by andybraren** [comment]
The new `max-width` looks good to me for the Disk Usage (soon to be "Filesystem" in #3440) popover. Will this apply to every Utilization card popover? The new width will probably be fine for those too, just curious.

Is the idea of top-aligning popovers to be able to see the chart at the same time as the top consumers? That makes sense to @yuvalgalanti and I so 👍 good call!

Are there any potential downsides of this change we're not seeing? 🙂

Side note: In the Used Capacity breakdown popover, should "By Projects" be the first option selected?

**Comment by bipuladh** [comment]
@rawagner I found the auto flipping of popover faulty hence I send this PR. Could you please verify it? If it's not working as expected I will raise an issue on Patternfly.

**Comment by rawagner** [comment]
flipping is not working as expected for me too

/lgtm

**Pull request merged**
