### PR TITLE
Bug 1872080: Define RHEL_ALLOW_PYTHON2_FOR_BUILD in Dockerfile.product

### PR DESCRIPTION
**Pull request by yselkowitz**
This is required for building with python2 for RHEL 8.

### CODE REVIEW

**Comment by yselkowitz** [comment]
This is required for RHEL 8.
/assign @bparees

**Comment by yselkowitz** [comment]
Something seems stuck
/retest

**Comment by spadgett** [comment]
> Something seems stuck

It's not stuck. It's part of a batch merge being tested now: https://prow.ci.openshift.org/tide

**Pull request merged**
