### PR TITLE
Switch overview tooltips to PF4 to prevent overflow clipping

### PR DESCRIPTION
**Pull request by rhamilto**
Partially fixes https://jira.coreos.com/browse/CONSOLE-1011

Screen Shot 2019-08-16 at 9 02 00 AM
Screen Shot 2019-08-16 at 9 02 06 AM
Screen Shot 2019-08-16 at 9 02 19 AM
Screen Shot 2019-08-16 at 9 02 29 AM
Screen Shot 2019-08-16 at 9 02 35 AM

### CODE REVIEW

**Comment by jschuler** [comment]
@rhamilto can you try adding `enableFlip={false}` to the Tooltip? I believe with `enableFlip` set to true, it checks where its boundary is. Therefore, it is getting pushed to the right because its (boundary)[https://atomiks.github.io/tippyjs/all-options/] that it adheres to is defaulting to the `scrollParent`. I'll take a look and see if we can make this modifiable so that we can set the boundary to the window or viewport instead.

**Comment by rhamilto** [comment]
> @rhamilto can you try adding enableFlip={false} to the Tooltip? I believe with enableFlip set to true, it checks where its boundary is. Therefore, it is getting pushed to the right because its boundary that it adheres to is defaulting to the scrollParent. I'll take a look and see if we can make this modifiable so that we can set the boundary to the window or viewport instead.

Thanks, @jschuler.  Disabling `enableFlip` aligns the arrow with the correct content but results in the tooltip being clipped by the viewport.

Screen Shot 2019-08-14 at 3 03 52 PM

Seems like what we need is to keep `flip` enabled and add the ability to specify `flipBehavior` as `['right']`?

**Comment by jschuler** [comment]
> Seems like what we need is to keep `flip` enabled and add the ability to specify `flipBehavior` as `['right']`?

@rhamilto yes having the `flipBehavior` functionality would be great, but unfortunately in my testing so far the `flipBehavior` prop is not working as expected. This may be a bug in the now outdated third party dependency that we're using. I'll keep investigating this.

**Comment by rhamilto** [comment]
> This may be a bug in the now outdated third party dependency that we're using. 

@jschuler, something other than [Tippy v3.x](https://github.com/patternfly/patternfly-react/blob/master/packages/patternfly-4/react-core/package.json#L50 )?  It appears Tippy v3.2.0 has the correct, desired behavior.  https://codepen.io/_MYN/pen/KLgvKr

**Comment by rhamilto** [comment]
Oops.  Wrong codpen above.  I meant https://codepen.io/rhamilto/pen/yLBOpQb

**Comment by jschuler** [comment]
Thanks @rhamilto , I was able to make a couple improvements to the tooltip in PR https://github.com/patternfly/patternfly-react/pull/2711. Now, if the tooltip gets pushed by its boundary, the arrow should still point at the correct node. Also, by default the boundary is not the scrolling container, but the window. With these improvements, it should be able to keep your tooltip in view with the arrow shifted to still point at the correct node.
Unfortunately i did not have success with implementing the `flipBehavior` functionality. I recreated the issue here:
https://codesandbox.io/s/tippy-1-flipbehavior-bug-hbq6b
We use `@tippyjs/react` version 1.1.1 which is a wrapper for tippy. There is a newer version that we should upgrade to that may work better, but that won't happen in the current release cycle.

**Comment by rhamilto** [comment]
Note:  will conflict with https://github.com/openshift/console/pull/2363

**Comment by rhamilto** [comment]
Rebased.  @spadgett, PTAL

**Pull request merged**
