### PR TITLE
CONSOLE-3763: Update null-loader dev dependency in console

### PR DESCRIPTION
**Pull request by jcaianirh**
Fixes: https://issues.redhat.com/browse/CONSOLE-3763

### CODE REVIEW

**Comment by jcaianirh** [comment]
QE Approver:
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

**Comment by XiyunZhao** [comment]
This PR has been tested with automation regression test, the job is trigger in job #236009, no issue was found
/label qe-approved

**Pull request merged**
