### PR TITLE
[release-4.7] Bug 1975469: Handle array to string conversion for HTTPS checkbox value

### PR DESCRIPTION
**Pull request by debsmita1**
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=1975469

Manual cherry pick of fb0a5764ae9e3eedd370701325140e76a454c3cb
PR : https://github.com/openshift/console/pull/9277

### CODE REVIEW

**Comment by jerolimov** [comment]
Tested this PR on a 4.7 cluster and the HTTPS checkbox it works as expected.

Port, success / failure threshold number fields doesn't have a problem on 4.7 / with this PR.

PR is identical to the original PR so add both labels here.

/lgtm
/approve
/retest

**Comment by invincibleJai** [comment]
@debsmita1 it'll nice to put the corresponding PR link as well in the description for 4.8 with which manual cherry-pick has been done

**Pull request merged**
