### PR TITLE
Change namespace bar Add actions to only Import YAML

### PR DESCRIPTION
**Pull request by rhamilto**
I made the link the text color as having it link color was a bit too prominent IMO.  I maintained the link hover color, however.

Screen Shot 2019-06-12 at 1 24 13 PM
hover
Screen Shot 2019-06-12 at 1 24 24 PM

### CODE REVIEW

**Comment by spadgett** [comment]
cc @beanh66

**Comment by rhamilto** [comment]
Linter errors fixed.  @spadgett, PTAL.

**Comment by beanh66** [comment]
@rhamilto Thanks, make sense! Minor question, on hover can we add the underline as well?

**Comment by rhamilto** [comment]
> @rhamilto Thanks, make sense! Minor question, on hover can we add the underline as well?

Done in https://github.com/openshift/console/pull/1715

**Pull request merged**
