### PR TITLE
Bug 1773646: Extend dashboard grey background to full height of viewport

### PR DESCRIPTION
**Pull request by sg00dwin**
Note: The markup structure was slightly different for each dashboard view.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1773646

Tested with `.pf-l-grid__item {display:none;}`

**before**
Screen Shot 2019-12-02 at 6 29 15 PM
Screen Shot 2019-12-02 at 6 29 36 PM
Screen Shot 2019-12-02 at 6 29 49 PM

---

**after**
(Edge, Chrome, Firefox, Safari)

Screen Shot 2019-12-02 at 5 54 37 PM
Screen Shot 2019-12-02 at 5 55 20 PM
Screen Shot 2019-12-02 at 5 56 06 PM
Screen Shot 2019-12-02 at 5 57 35 PM
Screen Shot 2019-12-02 at 5 57 48 PM
Screen Shot 2019-12-02 at 5 58 00 PM
Screen Shot 2019-12-02 at 5 58 58 PM
Screen Shot 2019-12-02 at 5 59 07 PM
Screen Shot 2019-12-02 at 5 59 20 PM
Screen Shot 2019-12-02 at 5 59 51 PM
Screen Shot 2019-12-02 at 6 23 22 PM
Screen Shot 2019-12-02 at 6 24 58 PM

### CODE REVIEW

**Comment by rhamilto** [comment]
A couple of issues on catalog pages:

Gray background doesn't extend.
Screen Shot 2019-12-03 at 9 53 46 AM

Bottom of page not visible, no gutter below.
Screen Shot 2019-12-03 at 9 54 36 AM

**Comment by sg00dwin** [comment]
> A couple of issues on catalog pages:
> 
> Gray background doesn't extend.
> Bottom of page not visible, no gutter below.

Screen Shot 2019-12-03 at 2 27 20 PM

**Comment by sg00dwin** [comment]
@rhamilto pushed updates

**Comment by rhamilto** [comment]
/lgtm

cc @smarterclayton

**Comment by rhamilto** [comment]
@sg00dwin looks like you broke an integration test.
```
displays the Silences list page expand_less | 2s
-- | --
WebDriverError: element click intercepted: Element <li class="co-m-horizontal-nav__menu-item">...</li> is not clickable at point (437, 199). Other element would receive the click: <ul class="co-m-horizontal-nav__menu">...</ul>
```

**Comment by sg00dwin** [comment]
@rhamilto please add another lgtm

**Pull request merged**
