### PR TITLE
Update add pipeline flow based on new UX designs

### PR DESCRIPTION
**Pull request by rohitkrai03**
Related Bug - https://jira.coreos.com/browse/ODC-2241 and https://jira.coreos.com/browse/ODC-2246.

Based on the new user flow and designs for add pipeline section, this PR -
- Updates the label of checkbox from `Enable Pipelines` -> `Add pipeline`.
- Updates the component to always show `Pipelines` section with an alert if no builder image is selected.
- Fetches the `pipeline` template when user selects a builder image and renders the checkbox and visualization in an expand collapse component.
- Shows an alert if no pipeline template is found for that builder image.
- Renders the `PipelineVisualization` component only when user expands the section to defer the fetching of all related `Task` resources.

Gif - 
ezgif com-video-to-gif (3)

- This PR also adds support for pipelines in dockerfile flow. We fetch pipeline template based on `pipeline.openshift.io/strategy=docker` label. 

Screenshot - 
Screenshot from 2019-11-13 04-16-11

### CODE REVIEW

**Comment by andrewballantyne** [comment]
> @rohitkrai03 overall looks great! One nit ... your animated gif shows an inline notification mentioning strategy which is a term we don't expose to the user. Looking at the code it looks like you have modified that to mention builder image & runtime, which is great, just verifying that's the case!

I don't see `strategy` anywhere in the content Rohit added. Where abouts are you seeing this in the gif? @serenamarie125

**Comment by rohitkrai03** [comment]
@andrewballantyne Its there in the alert message that we show in case of dockerfile flow. @serenamarie125 Can you suggest an alternate text for it? I can update it in a new PR.

**Comment by andrewballantyne** [comment]
@rohitkrai03 I think it's fine. I think @serenamarie125 was just making sure you didn't use the word `strategy` as it's not a term we are exposing to the end user. I did a quick search through your code and you don't use the word `strategy` anywhere, so I think all is good.

**Comment by rohitkrai03** [comment]
@andrewballantyne This is the line I use `dockerfile strategy` - https://github.com/openshift/console/pull/3364/files#diff-d46e40626f43a2fe25c845e59214ab8dR61

**Comment by andrewballantyne** [comment]
Glad one of us is paying attention haha. I must have missed that.

**Comment by beaumorley** [comment]
For the Info alert message, can we say:

"There are no pipeline templates available for this Dockerfile."

I suggest capitalizing Dockerfile since it is capitalized in the form.

**Comment by beaumorley** [comment]
Based on this clarification on how this works - For Import from Dockerfile flow we'll have one template for all types of dockerfiles. No user input needed.The recommended alert message: 

"The pipeline template for Dockerfiles is not available at this time."

**Pull request merged**
