### PR TITLE
CONSOLE-2972: Upgrade webpack 4.x dependencies

### PR DESCRIPTION
**Pull request by spadgett**
Update webpack to the latest 4.x and update webpack loaders. This will help prepare us to move to webpack 5 and gets us off some very old versions of dependencies in our build toolchain.

* react-refresh-webpack-plugin `^0.4.3` -> `^0.5.0`
* babel-loader `^8.1.0` -> `^8.2.1`
* cache-loader `1.x` -> `^4.1.0`
* css-loader `0.28.x` -> `^5.2.7` (!)
* glslify-loader `1.x` -> `^2.0.0`
* mini-css-extract-plugin `0.4.x` -> `^1.6.2`
* sass-loader `6.x` -> `^10.1.1` (!)
* style-loader `^0.23.1` -> `^2.0.0`
* thread-loader `1.x` -> `^3.0.4`
* umd-compat-loader `2.1.1` -> `^2.1.2`
* webpack `4.44.0` -> `^4.46.0`
* webpack-cli `4.5.x` -> `^4.8.0`
* webpack-dev-server `3.11.1` -> `^4.2.1`
* webpack-virtual-modules `0.3.x` -> `^0.4.3`

### CODE REVIEW

**Comment by spadgett** [comment]
Still working on this. @vojtechszocs FYI

**Comment by spadgett** [comment]
@rhamilto FYI, this gets rid of the postcss warnings we were seeing.

**Comment by spadgett** [comment]
/assign @kdoberst 
for code review

/assign @yapei 
for QE review

@yapei I think we simply need a regression test to make sure things generally look and work OK.

/label px-approved
/label docs-approved

This PR only updates development dependencies and has no user-visible changes. cc @opayne1 @RickJWagner

**Comment by spadgett** [comment]
kubevirt tests will likely fail until #10121 merges.

**Comment by kdoberst** [comment]
> kubevirt tests will likely fail until #10121 merges.

Looks good, but I'll add my approval once the tests pass.

**Comment by spadgett** [comment]
Looks like the kubevrit tests launched successfully, but they're failing with the known error.

**Pull request merged**
