### PR TITLE
Use standard resource summary on project overview tab

### PR DESCRIPTION
**Pull request by spadgett**
This restores the standard `Overview` tab to the project page since we have a first-class dashboard now. The problem is that the dashboard doesn't yet have the project links extension, so I'm not sure we can merge this yet.

cc @rawagner @rhamilto @andybraren @beanh66 @serenamarie125 

Screen Shot 2019-10-21 at 1 10 39 PM

### CODE REVIEW

**Comment by andybraren** [comment]
As discussed earlier, we should also move the ResourceQuota cards that sometimes appear in the Overview tab below the new Utilization card of the Project Dashboard so that this functionality isn't lost. This would be a quick & hopefully temporary solution until we design a better-integrated ResourceQuota visualization for 4.4.

I don't have a great screenshot of what they look like today, but see below (they should already be converted to PatternFly donuts). I think the header content can stay the same, just switched to our new dashboard card component instead.

FYI @rawagner @jelkosz, I'll send you a recording for context when it's available.

image

**Comment by spadgett** [comment]
/assign @rhamilto 
/skip

@jhadvig fyi

#3063 adds the quota card to the new dashboard.

**Comment by spadgett** [comment]
Rebased

**Comment by spadgett** [comment]
Rebase only (#3075 which changed the fragments in the deleted file)

**Pull request merged**
