### PR TITLE
Overriding default kabab actions

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@bipuladh @cloudbehl, please review(the idea here is to override the default action Edit/Delete), For pool management, i am overriding default actions using my own component modal.  But still, i am blocking actions for external cluster and default pool inside code only, i am displaying a message in the modal.

**Comment by cloudbehl** [comment]
@rawagner Can you review this and see if the idea fits in well enough?

**Review by bipuladh — CHANGES_REQUESTED** [review]
The CSV Extension itself is going to get removed. 
/hold

**Comment by GowthamShanmugam** [comment]
> The CSV Extension itself is going to get removed.
> /hold

Is it happening for 4.8? if yes can you please add this future in a new extention

**Comment by GowthamShanmugam** [comment]
as per comment: https://github.com/openshift/console/pull/8354#pullrequestreview-621798130 closing this PR

**Pull request closed without merging**
