### PR TITLE
Bug 1999292: Use "default projects" instead of "system projects"

### PR DESCRIPTION
**Pull request by spadgett**
This aligns with the terminology in https://docs.openshift.com/container-platform/4.8/applications/projects/working-with-projects.html

/assign @rhamilto

### CODE REVIEW

**Comment by spadgett** [comment]
cc @megan-hall

**Comment by spadgett** [comment]
Screen Shot 2021-08-30 at 3 53 23 PM

**Comment by spadgett** [comment]
@megan-hall We might want to update the terminology in the projects page filter dropdown as well, but changing to "Default" there doesn't really work since the filter group is "Requester." Technically default or not should be a different filter from "Requester."

**Review by rhamilto — APPROVED** [review]
/lgtm

**Pull request merged**
