### PR TITLE
OCPBUGS-38636: improve layout and findability of Hide Lightspeed pref…

### PR DESCRIPTION
**Pull request by rhamilto**
…erence

This changes are the result of feedback from @eliranmal and @jcaianirh during demo.  Thanks for the suggestions!

After:

https://github.com/user-attachments/assets/26fedf12-da4f-478d-b335-b233bd8b018d

### CODE REVIEW

**Comment by spadgett** [comment]
> +43 −189

Love to see PRs that add features and still remove lines of code 👍

**Comment by cyril-ui-developer** [comment]
lgtm

**Comment by wking** [comment]
[build09 capacity exhaustion][1]:

/retest-required

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_console/14171/pull-ci-openshift-console-master-images/1831821505982369792#1:build-log.txt%3A21-23

**Comment by wking** [comment]
/hold cancel

build09 struggled today, but is maybe happy again now

**Pull request merged**
