### PR TITLE
OU-38: Monitoring: Refactor silence duration dropdown to use PatternFly

### PR DESCRIPTION
**Pull request by kyoto**

### CODE REVIEW

**Comment by kyoto** [comment]
This is a refactoring change. There should be no user visible changes.

/label px-approved
/label docs-approved

**Comment by kyoto** [comment]
@jgbernalp I had to rebase. Could you tag again?

**Comment by Tai-RedHat** [comment]
Test PR with cluster bot, check on alerting page: no other regression issues.
/label qe-approved

**Pull request merged**
