### PR TITLE
Bug 1999076: Page Not Found error when clicking on Storage link provided in Overview page

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Fix 401 error while clicking ODF storage link in Overview page

Fix BZ#1999076

Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@bipuladh, @GowthamShanmugam, @SanjalKatiyar  Please review

**Comment by SanjalKatiyar** [comment]
/retitle Bug 1999076: Page Not Found error when clicking on Storage link provided in Overview page

**Comment by TimothyAsirJeyasing** [comment]
@cloudbehl , @afreen23 Please review

**Review by GowthamShanmugam — APPROVED** [review]

**Pull request merged**
