### PR TITLE
[release-4.9] Bug 2050271: show latest pipelinerun on the top of the list

### PR DESCRIPTION
**Pull request by debsmita1**
**Fixes:**
https://bugzilla.redhat.com/show_bug.cgi?id=2050271

**GIF:**
Peek 2022-02-09 23-44

Note: This is fixed in 4.10

/kind bug

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
Verified on cluster.

https://user-images.githubusercontent.com/9964343/154017932-113e0790-1d38-4e79-94f1-bb844f3668a0.mov

/lgtm

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
