### PR TITLE
[release-4.5.z] Bug 1874373: RHV URL validation is missing https://

### PR DESCRIPTION
**Pull request by suomiy**
@glekner @yaacov please review

### CODE REVIEW

**Comment by suomiy** [comment]
can you please cherry-pick-approved ?
@sdodson @eparis @markmc @crawford

**Review by glekner — CHANGES_REQUESTED** [review]
There was a following PR to this, please change accordingly 
https://github.com/openshift/console/pull/6721/files

**Comment by sdodson** [comment]
Please see the patch manager documentation in the topic of #forum-release. A patch manager will review according to the merge windows and there should be no need to ping someone directly for PRs that only need cherry-pick-approved label.

**Comment by suomiy** [comment]
@glekner done, can you please relgtm?

**Comment by bparees** [comment]
@suomiy why isn't https://github.com/openshift/console/pull/6721 part of this backport?

**Comment by suomiy** [comment]
@bparees it is, please see the commits

**Comment by bparees** [comment]
sorry, it was a more substantial delta than the PR so i missed it.

**Pull request merged**
