### PR TITLE
Bug 1986676: Fix Unique key warning issue in P/PLR details page

### PR DESCRIPTION
**Pull request by karthikjeeyar**
**Fixes**: 

https://issues.redhat.com/browse/ODC-6162

**Analysis / Root cause**: 

Browser log should not show any react warnings. Depending of the pipeline and pipeline run visualization shows a warning:

**Solution Description**: 

Use linkname instead of name so the list item gets unique key for embeddedTasks as well. 

**Screen shots / Gifs for design review**: 

No React warnings on the browser log.

**Test setup:**

Use this yaml https://gist.github.com/karthikjeeyar/17be9d82ad999b0dea3de1c00483415b

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by nemesis09** [comment]
verified locally
/lgtm

**Review by jerolimov — APPROVED** [review]
Warnings are gone :+1: 

/approve

**Pull request merged**
