### PR TITLE
[release-4.12] OCPBUGS-36561: Increase login flow state paramater lenth/entropy

### PR DESCRIPTION
**Pull request by jhadvig**
Manual backport of https://github.com/openshift/console/pull/14483

### CODE REVIEW

**Comment by yanpzhan** [comment]
Checked on cluster launched against the pr, accessed console url, checked "state" parameter in login redirect url, it's 16 bytes.
/label qe-approved
/label cherry-pick-approved

**Review by jhadvig — COMMENTED** [review]
/label backport-risk-assessed
/jira refresh

**Comment by jhadvig** [comment]
/

**Pull request closed without merging**
