### PR TITLE
Add support for param of array type when starting a Pipeline

### PR DESCRIPTION
**Pull request by vikram-raj**
**Story:** https://issues.redhat.com/browse/ODC-6773

**Descriptions:**
- Add support param of array type when starting a Pipeline
- user can add array type param in the start modal

**Screenshots:**
image

Kapture 2022-08-11 at 17 03 15

### CODE REVIEW

**Comment by vikram-raj** [comment]
cc: @serenamarie125

**Comment by karthikjeeyar** [comment]
Verified in cluster bot
/lgtm

**Comment by invincibleJai** [comment]
Propagating docs and px acks from the Epic https://issues.redhat.com/browse/ODC-6696
/label docs-approved
/label px-approved

**Comment by hemantsaini-7** [comment]
/lgtm
/label qe-approved

image

**Pull request merged**
