### PR TITLE
RHSTOR-5836: add info for ODF use-case (LSO LocalVolumeSet "Create" page)

### PR DESCRIPTION
**Pull request by SanjalKatiyar**
Screenshot 2024-06-17 at 4 47 13 PM
Screenshot 2024-06-17 at 4 47 36 PM

### CODE REVIEW

**Comment by SanjalKatiyar** [comment]
> Screenshot 2024-06-17 at 4 47 13 PM Screenshot 2024-06-17 at 4 47 36 PM

/qe-approved

**Comment by jhadvig** [comment]
@RickJWagner PTAL

**Pull request merged**
