### PR TITLE
[release-4.7] Bug 1963025: Fix documentation link to network policies

### PR DESCRIPTION
**Pull request by jotak**
Also fix missing space in english text

i18n network-policy with link: use Trans

4.7 backport for https://github.com/openshift/console/pull/8869

### CODE REVIEW

**Comment by jotak** [comment]
cc @jhadvig

**Comment by yapei** [comment]
launched cluster and tested, working as expected, the doc link is pointing to https://docs.openshift.com/container-platform/4.7/networking/network_policy/about-network-policy.html and strings are translated

Screen Shot 2021-05-26 at 3 08 33 PM

**Review by yapei — APPROVED** [review]
/lgtm

**Review by spadgett — APPROVED** [review]
/approve

**Pull request merged**
