### PR TITLE
Bug 1831071: Remove View Image Vulnerabilities action

### PR DESCRIPTION
**Pull request by spadgett**
There is a `Vulnerabilities` tab on the pod page now, so the action is not needed. This is consistent with removing other actions like `View Environment` that just link to a tab.

/assign @itsptk @rhamilto

### CODE REVIEW

**Comment by spadgett** [comment]
Screenshot_2020-05-04 nodejs-rest-http-cpk3vr-deploy-j59tk-pod-q4mrp · Details · OKD

**Comment by itsptk** [comment]
Of note is that this "Vulnerabilities" tab is showing the list of affected containers (which I forgot in my bugzilla comment) whereas the action was taking you to the list of ImageManifestVulns filtered to the ones related to this pod. We'd need to determine if this is sufficient to show the user or if there is another way to show the ImageManifestVulns, or if the action should stay. 

cc @alecmerdler

**Comment by alecmerdler** [comment]
> Of note is that this "Vulnerabilities" tab is showing the list of affected containers (which I forgot in my bugzilla comment) whereas the action was taking you to the list of ImageManifestVulns filtered to the ones related to this pod. We'd need to determine if this is sufficient to show the user or if there is another way to show the ImageManifestVulns, or if the action should stay.

The *Vulnerabilities* tab is more intuitive than the filtered list of `ImageManifestVulns` (which we only used because we didn't have that tab yet).

**Pull request merged**
