### PR TITLE
[WIP ODC-2945] refactor and clean up PodRing.tsx 

### PR DESCRIPTION
**Pull request by yozaam**
**Fixes**: 

https://issues.redhat.com/browse/ODC-2945

**Analysis / Root cause**: 

Handleclick function was defined inside the React Component
Lodash was being used 

**Solution Description**: 

convert `_.debounce` to `useDebounceCallback` which results in memoized (handled by the hook?)
also we not re creating the function on each render

**Screen shots / Gifs for design review**: 

**Unit test coverage report**: 

**Test setup:**

- make a sample app
- go in admin ->workload ->deployment ->config
- test out the buttons and 'actions-> edit pod count' 

**Browser conformance**: 

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by yozaam** [comment]
is this the delay/responsiveness we need to eliminate ?

delaypodring

(left is the PR with hook code & right is original lodash code)

Is this because

**Comment by christianvogt** [comment]
@yozaam click to scale multiple times. eg from 1-> 10 pods and you'll notice the difference in behavior. The new change actually sometimes gets stuck.

**Comment by yozaam** [comment]
undestood
Is there some design/pattern you suggest because I am not sure how to refactor it 😅

**Comment by christianvogt** [comment]
In order for the UI to feel responsive, there needs to be an internal state which is used to capture the user's desired pod count. This state will be updated each time the user clicks the scale up / down buttons. The debouncing is in place to ensure we don't send continuously send update requests if the user is quickly clicking to scale.

The catch here is when do we transition between displaying the internal state and displaying the real value captured in the pod resource. The least error prone impl I can think of is to start reading the desired pod count from state as soon as the user clicks one of the buttons and then to stop reading from internal state as soon as the pod date `obj` gets updated.

**Comment by yozaam** [comment]
Alright, if we pass the local state `clickCount` as the `subtitle` it feels a little more responsive, like this:  

Left side current PR ( we click 3 times then we see the subtitle change from 1->2->3->4
Right side we directly see 'scaling to 4' after 1 second of clicking

podringClickcountSubtitle

**Comment by christianvogt** [comment]
@yozaam I'm assuming that this won't work if you have 2 browser windows open on the same deployment and then scale up in one browser. The other browser won't correctly show where it's scaling to.

**Comment by yozaam** [comment]
Just tested same deployment
As soon as one browser updates the backend value, the other browser will show the message like this
podringdoublebrowser

**Comment by christianvogt** [comment]
@yozaam Weird behavior when scaling in both browsers one after the other. One ring can get stuck with the wrong value. In this case I scaled to 9 but one browser is still showing the old click count:
image

**Comment by yozaam** [comment]
the resource object is out of date in the sidebar, causing some trouble when we check `obj.spec.replicas`

Here is where we get the object, after this, I don't think it is getting updated https://github.com/openshift/console/blob/0f7f78f298cc108d0f538604fb2f008afe34c825/frontend/packages/topology/src/components/workload/DeploymentSideBarDetails.tsx#L52-L57

We see both the deployment `obj` are same on first load
image
(left = topology)

Now doing a +1 to either page, the object remains the out of date and so we see unexpected behaviour 
image
I also noticed that `ownerKind` becomes `ReplicaSet` in topology for latest render 

there is some place where topology is not refreshing the `deployment` resource and our main deployment page is fetching it

**Pull request closed without merging**
