### PR TITLE
Bug 1874832: Fix test for ocp 4.4 4.5

### PR DESCRIPTION
**Pull request by shyRozen**
Removed "see all" status icon section which don't exist and xit red status icon till https://bugzilla.redhat.com/show_bug.cgi?id=1859047 will be fixed (probably in ocs 4.6)

### CODE REVIEW

**Comment by bipuladh** [comment]
/lgtm cancel
oops I missed @afreen23 comment.

**Comment by shyRozen** [comment]
Added commit comments. Please review and approve @bipuladh @afreen23

**Review by bipuladh — APPROVED** [review]

**Pull request merged**
