### PR TITLE
dashboard: Make StatusCard height flexible

### PR DESCRIPTION
**Pull request by mareklibra**
For the case when there is not enough status messages to show, the large white card looks distracting.
By making it smaller, the focus is attracted to other cards instead.

---

### CODE REVIEW

**Comment by matthewcarleton** [comment]
@mareklibra I'm not sure if those screenshots are showing before/after but I'm seeing some issues with the icon sizing and spacing. I agree that the large check with text when there are no messages seems a bit odd and distracting. There is a lot of whitespace in that card.  I'm not the dashboard expert so I'll leave that up to @andybraren and @mceledonia.

**Comment by andybraren** [comment]
@matthewcarleton I think this is after, but the empty state being so much taller is definitely weird.

Here are two small small tweaks that aren't perfect (the empty state will still be a little taller than the min-height) but would be quick to implement. What do you think @matthewcarleton @mceledonia? I'm not sure about removing the empty state entirely at this point.

image

Changes:
- Change the height of the empty state's SVG icon to `<svg height="2rem">` (not exactly sure where this is set)
- Remove the `margin-bottom` from `.pf-c-empty-state__icon`

**Comment by andybraren** [comment]
Another tweak to prevent the first alert/message from shrinking the card:

```
.co-status-card__alerts-body {
    min-height: 9rem;
}
```

**Comment by mareklibra** [comment]
> @matthewcarleton I think this is after, but the empty state being so much taller is definitely weird.

Right, the screenshots are **after**. Just to show effect on other components.

**Comment by mareklibra** [comment]
@andybraren , maybe I am doing something wrong, but I do not see effect of the second tweak (`min-height: 9rem`).
But removing `margin-bottom` in `.pf-c-empty-state__icon` helped, please have a look:

alertsBody

**Comment by andybraren** [comment]
> @andybraren , maybe I am doing something wrong, but I do not see effect of the second tweak (min-height: 9rem).

image

@mareklibra This isn't a perfect way of doing this, but changing from `6rem` (as you have it now) to `9rem` ensures that when `.pf-c-empty-state` disappears as soon as the first alert comes in, the card doesn't shrink.

My React knowledge is very limited, but [it looks like](https://www.patternfly.org/v4/documentation/react/components/emptystate/) there's a `size` prop that can be `sm/md` - could that be used to make the empty state icon smaller like the screenshot above?

And rather than using `!important`, the margin below the empty state's icon can be removed using the CSS variable:

```
.pf-c-empty-state__icon {
    --pf-c-empty-state__icon--MarginBottom: initial;
}
```

**Pull request merged**
