### PR TITLE
update dnd icon

### PR DESCRIPTION
**Pull request by abhinandan13jan**
# Issue
https://issues.redhat.com/browse/ODC-5703

# Screenshot
# Before
Screenshot from 2021-05-03 18-57-32

# After
Screenshot from 2021-05-03 18-55-00

# tests
none changes

# Browser conformance
Chrome

### CODE REVIEW

**Comment by invincibleJai** [comment]
/lgtm

verified the change

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
