### PR TITLE
Bug 1827042: removes techpreview badge from serverless

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes**: 
https://issues.redhat.com/browse/ODC-3659

**Analysis / Root cause**: 
As serverless is going GA so needed to remove TP badge across console for Serverless

**Solution Description**: 
Removed TechPreview badge

**Screen shots / Gifs for design review**: 
Screenshot 2020-04-23 at 11 59 30 AM

Screenshot 2020-04-23 at 11 57 33 AM

Screenshot 2020-04-23 at 11 57 50 AM

Screenshot 2020-04-23 at 11 58 19 AM

@openshift/team-devconsole-ux 

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by invincibleJai** [comment]
@andrewballantyne sorry have missed it, updated PTAL

**Comment by andrewballantyne** [comment]
@invincibleJai Perhaps I was a bit vague lol... please remove the overrides. We have default pages for the details / list pages. Unless you need custom functionality, we can just remove the plugin hooks to these pages and delete the files.

**Comment by andrewballantyne** [comment]
@invincibleJai Looks like a manual cherry-pick is needed.

**Comment by invincibleJai** [comment]
@andrewballantyne here is PR for same https://github.com/openshift/console/pull/5210

**Pull request merged**
