### PR TITLE
Bug 1875794: Feature guards for Minimal Deployment and Cluster Encryption

### PR DESCRIPTION
**Pull request by bipuladh**

### CODE REVIEW

**Comment by cloudbehl** [comment]
Is there parallel OCS-op PR for this? can you tag it

**Comment by bipuladh** [comment]
> Is there parallel OCS-op PR for this? can you tag it

https://github.com/openshift/ocs-operator/pull/754

**Comment by cloudbehl** [comment]
We need to handle `getOCSRequestData` as well as this flag is not there in 4.5
 https://github.com/openshift/console/blob/21472765fd769cec49194cee13f198611e9d5566/frontend/packages/ceph-storage-plugin/src/components/ocs-install/create-form.tsx#L77

**Comment by cloudbehl** [comment]
This needs to be conditional based on flag enabled.
https://github.com/openshift/console/blob/master/frontend/packages/ceph-storage-plugin/src/components/ocs-install/ocs-request-data.ts#L47..L49

**Pull request merged**
