### PR TITLE
Monitoring: Hide SEVERITY column if there's no severity labels

### PR DESCRIPTION
**Pull request by kyoto**
We normally expect alerts to have `severity` labels, but this is not
guaranteed, so better handle the case where those labels don't exist.

### CODE REVIEW

**Comment by spadgett** [comment]
Does this mean the table columns can change when alerts are added / removed?

cc @cshinn

**Comment by cshinn** [comment]
I agree with @spadgett that it'd be weird to change the table format as items are added. I believe we use a dash (-) in most other places where a piece of information is missing.

**Comment by kyoto** [comment]
@spadgett @cshinn Yes, it does mean that the columns could change, but only if an alert is added to / removed from Prometheus, which should be rare. Still, I'm happy to just close this PR if you prefer?

**Comment by kyoto** [comment]
Closing for now. May reopen later.

**Pull request closed without merging**
