### PR TITLE
Fix bug where pod donut was not showing terminating status on scaling down

### PR DESCRIPTION
**Pull request by divyanshiGupta**
Jira Issue - https://jira.coreos.com/browse/ODC-1457

Screenshot from 2019-08-01 17-30-53

### CODE REVIEW

**Comment by christianvogt** [comment]
@divyanshiGupta please also fix line 68. `if (_.has(pod, ['metadata.deletionTimestamp'])) {`

**Comment by divyanshiGupta** [comment]
@christianvogt done.

**Pull request merged**
