### PR TITLE
CONSOLE-2446: statefulset i18n

### PR DESCRIPTION
**Pull request by zherman0**
[CONSOLE-2446](https://issues.redhat.com/browse/CONSOLE-2446): statefulset i18n

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm
/hold
/assign @yapei @ahardin-rh @sferich888 

This is ready for QE review.

**Comment by zherman0** [comment]
@spadgett - Had to rebase, can you redo the lgtm label.

**Review by spadgett — APPROVED** [review]
/lgtm
/hold cancel

**Pull request merged**
