### PR TITLE
Set default font-size to 14px instead of pf4 default of 16px

### PR DESCRIPTION
**Pull request by sg00dwin**
Some individual elements need specified size to maintain current sizing

### CODE REVIEW

**Comment by spadgett** [comment]
/assign @rhamilto 
cc @christianvogt

**Comment by rhamilto** [comment]
@sg00dwin, is this ready for merge?  Title still contains `WIP`.

**Comment by sg00dwin** [comment]
> @sg00dwin, is this ready for merge? Title still contains `WIP`.

Can you pull it down and browse through it first just to make sure I didn't catch something?

**Comment by rhamilto** [comment]
`<th>` and `<td>` font size is 13px instead of 14px.
Screen Shot 2019-07-03 at 9 51 42 AM

**Comment by spadgett** [comment]
I believe we can remove this rule that just merged after the general font change (but will need to be tested)

https://github.com/openshift/console/pull/1870/files#diff-307e5a43a73c45e1f3983abc14bcb686R162

Do we have other font overrides for the dropdown we can remove?

**Comment by sg00dwin** [comment]
> I believe we can remove this rule that just merged after the general font change (but will need to be tested)
> 
> https://github.com/openshift/console/pull/1870/files#diff-307e5a43a73c45e1f3983abc14bcb686R162
> 
> Do we have other font overrides for the dropdown we can remove?

@spadgett There may be others. We'll need to circle back and do a sweep of those that can be removed.

**Comment by sg00dwin** [comment]
@rhamilto updated pr ready

**Comment by kyoto** [comment]
Setting `--pf-global--FontSize--md: $font-size-base` broke the display of PatterFly `Switch` components (currently only used on `/monitoring/query-browser`).

**Pull request merged**
