### PR TITLE
Truncate long image names within table. 

### PR DESCRIPTION
**Pull request by sg00dwin**
Which tightens up the container table rows for better presentation.

https://jira.coreos.com/browse/CONSOLE-1290

### CODE REVIEW

**Comment by yapei** [comment]
@sg00dwin  do you know why did we remove the fast `copy`(I remember it's a sign of +) from container table?

**Comment by sg00dwin** [comment]
@yapei A PR was merged that better communicates that the image truncated string can be selected and copied. Thanks for the feedback!

**Pull request merged**
