### PR TITLE
Bug 1831305:  fix bug where page contents are not scrollable using ke…

### PR DESCRIPTION
**Pull request by rhamilto**
…yboard

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1831305

cc:  @smarterclayton

### CODE REVIEW

**Comment by spadgett** [comment]
I have a feeling this will fail the prettier check

**Comment by rhamilto** [comment]
/hold

need to apply same fix for sidebar

**Comment by rhamilto** [comment]
/hold cancel

Updated to add fix for sidebar.  Note there are other instances where keyboard scrolling will be broken, but it seems a bit excessive to add the fix everywhere?  Ultimately, we need to be able to remove `tabIndex={-1}` from `<Page>` in order to stop the bug everywhere.

**Pull request merged**
