### PR TITLE
CONSOLE-2501: Update builder image

### PR DESCRIPTION
**Pull request by spadgett**
* go 1.18 -> 1.20
* node 4.16.0 -> 4.21.3
* kubectl 1.20.4 -> 1.27.1

Requires https://github.com/openshift/release/pull/39443
Blocks https://github.com/openshift/console/pull/12821

### CODE REVIEW

**Comment by spadgett** [comment]
/label dependency-update/major

Blocks https://github.com/openshift/console/pull/12821

**Review by jerolimov — APPROVED** [review]
Great, also if I expected first an update to node 16. 😅

/lgtm

**Comment by spadgett** [comment]
> Great, also if I expected first an update to node 16. 😅

Yeah, I wanted to keep our node at the same major version as used for production builds to avoid surprises. We should update both to 16 in a follow up...

**Comment by spadgett** [comment]
/label qe-approved
/label px-approved
/label docs-approved

This PR contains changes to builder image only. No changes to the console itself.

**Comment by jhadvig** [comment]
Looks like the is an issue with folder permissions 
```
fatal: detected dubious ownership in repository at '/go/src/github.com/openshift/console'
To add an exception for this directory, call:
	git config --global --add safe.directory /go/src/github.com/openshift/console
```

**Comment by spadgett** [comment]
Some background on this error: https://github.com/git/git/commit/8959555cee7ec045958f9b6dd62e541affb7e7d9

**Review by jhadvig — APPROVED** [review]
/lgtm

**Comment by vojtechszocs** [comment]
> Looks like the is an issue with folder permissions
> 
> ```
> fatal: detected dubious ownership in repository at '/go/src/github.com/openshift/console'
> To add an exception for this directory, call:
> 	git config --global --add safe.directory /go/src/github.com/openshift/console
> ```

@jhadvig FYI, in [CI operator buildroot](https://github.com/openshift/dynamic-plugin-sdk/blob/main/docker/Dockerfile.ci-operator-buildroot) of OpenShift dynamic plugin SDK project, we solved a similar issue via git config
```
git config --system --add safe.directory '*'
```

**Pull request merged**
