### PR TITLE
Bug 1972060: Fix typo in olm message

### PR DESCRIPTION
**Pull request by rebeccaalpert**
Fixed spelling of available.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1972060.

### CODE REVIEW

**Review by jhadvig — CHANGES_REQUESTED** [review]
The change looks good. when searching through the repo I've found other occurrences of this misspelled string. 
Screenshot 2021-06-22 at 16 20 06

Please could you fix those as well? Thanks

**Comment by rebeccaalpert** [comment]
@jhadvig - Those are the cases I fixed. The other ones are in translation files; those would be updated after this PR merges.

**Pull request merged**
