### PR TITLE
Kubernetes Marketplace - disable marketplace nav and route

### PR DESCRIPTION
**Pull request by galletti94**
### Description

As a side effect of certain packagemanifests (specifically those in the openshift-operator-lifecycle-manager namespace) being "global", these operators will be present in the marketplace UI. The subscribe functionality is still in progress and we don't want users being able to see operators that are already on cluster as this would be confusing to the purpose of marketplace. Until these two issues are resolved, we need to temporarily disable the marketplace nav item and route.

### CODE REVIEW

**Comment by galletti94** [comment]
@alecmerdler had some trailing spaces issues and the lgtm got removed - could you take another look?

**Comment by galletti94** [comment]
jenkins push

**Comment by coreos-ui** [comment]
The PR image failed.

**Comment by galletti94** [comment]
jenkins push

**Comment by galletti94** [comment]
jenkins build

**Comment by coreos-ui** [comment]
The PR image failed.

**Comment by galletti94** [comment]
jenkins rebuild

**Comment by alecmerdler** [comment]
@galletti94 You will need to disable the [performance test here](https://github.com/openshift/console/blob/master/frontend/integration-tests/tests/performance.scenario.ts#L35) as well since the route was removed.

**Comment by galletti94** [comment]
@alecmerdler can you take a last look?

**Pull request merged**
