### PR TITLE
Bug 1991439: i18n overlooked string

### PR DESCRIPTION
**Pull request by rhamilto**
Note
* https://bugzilla.redhat.com/show_bug.cgi?id=1993999
* https://bugzilla.redhat.com/show_bug.cgi?id=1994094
* https://bugzilla.redhat.com/show_bug.cgi?id=1991439

were opened to cover the other relevant files contained in https://bugzilla.redhat.com/show_bug.cgi?id=1991439

### CODE REVIEW

**Review by rebeccaalpert — APPROVED** [review]
Looks good to me!

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
