### PR TITLE
Kubevirt - Add Scheduling section to VM Details

### PR DESCRIPTION
**Pull request by glekner**
- Created a new section in VM Details called Scheduling and resources requirements.
- Moved suitable existing details/modals to the new section

Screen Shot 2020-03-03 at 13 10 57

### CODE REVIEW

**Comment by glekner** [comment]
@yaacov @suomiy can you review?

**Comment by yaacov** [comment]
@glekner hi, can you also take care of the template view:
https://github.com/openshift/console/blob/master/frontend/packages/kubevirt-plugin/src/components/vm-templates/vm-template-resource.tsx#L138

**Comment by glekner** [comment]
- Added section to Template view @yaacov

**Pull request merged**
