### PR TITLE
chore(i18n): update translations: : Completed-7034-OCP 4.12/Master Branch UI Localization- Sprint 225 & 228

### PR DESCRIPTION
**Pull request by cyril-ui-developer**
Adding latest translations from Memsource project https://cloud.memsource.com/web/project2/show/8Y0nh60n044R5ErTcRT2Ec

### CODE REVIEW

**Comment by cyril-ui-developer** [comment]
@jhadvig

**Comment by cyril-ui-developer** [comment]
@jhadvig This needs the labels to merge. Thanks

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by jhadvig** [comment]
```
  -  /go/src/github.com/openshift/console/frontend/gui_test_screenshots/cypress/scree     (1280x720)
     nshots/crud/resource-crud.spec.ts/Kubernetes resource CRUD operations -- deletes               
      the resource instance -- after all hook (failed).png                                          
```
/retest

**Comment by cyril-ui-developer** [comment]
@jhadvig I merged the latest downloaded translations to this PR since this has not merged. Could you please tag this PR again?

**Comment by jhadvig** [comment]
```
1) Using OLM descriptor components
       deletes operand:
     AssertionError: Timed out retrying after 30000ms: Expected to find element: `[data-test-action="Delete App"]:not(.pf-m-disabled)`, but never found it.
      at Context.eval (https://console-openshift-console.apps.ci-op-bxr180kl-75d12.xxxxxxxxxxxxxxxxxxxxxx/__cypress/tests?p=tests/descriptors.spec.ts:31664:14)
[mochawesome] Report JSON saved to /go/src/github.com/openshift/console/frontend/gui_test_screenshots/cypress_report_olm_002.json
  (Results)
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        40                                                                               │
  │ Passing:      39                                                                               │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  2                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     2 minutes, 11 seconds                                                            │
  │ Spec Ran:     descriptors.spec.ts                                                              │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
  (Screenshots)
  -  /go/src/github.com/openshift/console/frontend/gui_test_screenshots/cypress/scree     (1280x720)
     nshots/descriptors.spec.ts/Using OLM descriptor components -- deletes operand (f               
     ailed).png                                                                                     
  -  /go/src/github.com/openshift/console/frontend/gui_test_screenshots/cypress/scree     (1280x720)
     nshots/descriptors.spec.ts/Using OLM descriptor components -- deletes operand (f               
     ailed) (attempt 2).png
```
/retest

**Pull request merged**
