### PR TITLE
frontend: use Memory instead of RAM

### PR DESCRIPTION
**Pull request by sjenning**
@spadgett 

The resource is named "Memory" in the pod resources and add "Usage" to align with "CPU Usage"

### CODE REVIEW

**Comment by coreos-ui** [comment]
Can one of the admins verify this patch?

**Comment by coreos-ui** [comment]
Can one of the admins verify this patch?

**Comment by spadgett** [comment]
We should update node.tsx as well

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
Hm, `yarn install` failed. Looks like a network issue.

```
(node:554) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
error An unexpected error occurred: "https://registry.yarnpkg.com/@patternfly/patternfly-next/-/patternfly-next-1.0.109.tgz: ETIMEDOUT".
info If you think this is a bug, please open a bug report with the information provided in "/go/src/github.com/openshift/console/frontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
Last failure was flake https://jira.coreos.com/browse/CONSOLE-1228

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
Last failure was flake https://jira.coreos.com/browse/CONSOLE-1224

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
