### PR TITLE
Improve display of Pipeline Runs cols

### PR DESCRIPTION
**Pull request by rhamilto**
cc: @bmignano 

localhost_9000_k8s_ns_pipelines-tutorial_tekton dev_v1alpha1_PipelineRun(1  PFXS)
localhost_9000_k8s_ns_pipelines-tutorial_tekton dev_v1alpha1_PipelineRun(2  PFSM)
localhost_9000_k8s_ns_pipelines-tutorial_tekton dev_v1alpha1_PipelineRun(3  PFMD)
localhost_9000_k8s_ns_pipelines-tutorial_tekton dev_v1alpha1_PipelineRun(4  PFLG)
localhost_9000_k8s_ns_pipelines-tutorial_tekton dev_v1alpha1_PipelineRun(5  PFXL)

### CODE REVIEW

**Comment by bmignano** [comment]
LGTM!

**Comment by spadgett** [comment]
@christianvogt @serenamarie125 We're trying to better align the table columns across types in console. @rhamilto is updating tables to show status in a consistent place after name/namespace. Any concerns with this change?

**Comment by christianvogt** [comment]
I'm ok with the change.
I think we'd want to do the same then w/ the pipelines list?
image

**Comment by christianvogt** [comment]
@serenamarie125 what's more important to show the overall status? or the task status bar chart? Note that the task status bar chart is clickable and links out to the logs.

**Comment by serenamarie125** [comment]
@christianvogt the task status bar chart is more important to show, although we would still want to be able to filter on the overall status.

**Comment by serenamarie125** [comment]
@andrewballantyne you did a considerable amount of work on this as well, any concerns here?

**Comment by abhinandan13jan** [comment]
status filter doesn't work

**Comment by andrewballantyne** [comment]
Yup, this was my bad... I didn't circle back and test after I put in the namespace column after the fact. Thanks for fixing this @rhamilto 

Need to remember to test layouts in all device sizes.

**Comment by andrewballantyne** [comment]
> Not something that was done in this PR, just wanted to mention that the row sort doesn't work
> @rhamilto @andrewballantyne Do we have some JIRA/bug around this story for tracking purpose.

I don't see any sorting issue looking at this on master.

**Comment by andrewballantyne** [comment]
FWIW, there is a sorting issue... I logged https://issues.redhat.com/browse/ODC-2565

**Pull request merged**
