### PR TITLE
Gherkin and automation for project vulnerability

### PR DESCRIPTION
**Pull request by sanketpathak**
Epic: https://issues.redhat.com/browse/ODC-5131
Story: https://issues.redhat.com/browse/ODC-5407
Acceptance criteria:

- I should be able to see a list of vulnerabilities in the Vulnerabilities tab of the Project page
  - I should be able to differentiate between different vulnerability severities
- I should be able to drill in and see the details of one of the vulnerabilities
   - I should be able to filter between All vulnerabilities, App dependency or Base Image vulnerabilities on the IMV Details page
   - I should be able to access Snyk data when available

**Checks required for approving Epic gherkin scripts PR:**

- [x] Add @epic-number to the scenarios or feature file [e.g: @odc-xxx]
- [x] Add @to-do for automation possible scenarios
- [x] Add @regression or @smoke based on the importance of the scenario
- [x] Update the test scenarios count in [Automation status confluence Report](https://docs.jboss.org/display/ODC/Automation+Status+Report)
- [x] Check for the linter issues by executing `yarn run gherkin-lint` on frontend folder [Skip epic number tags related linter issues]

**Fix**: https://issues.redhat.com/browse/ODC-5408

**Test Setup**:

Cluster should be running on local

Check the TAGS in frontend/packages/dev-console/integration-tests/cypress.json file be: ""(@pre-condition or @smoke or @regression) and not (@manual or @to-do or @un-verified or @broken-test)"",

Command to execute:
Run the command `yarn run dev`
Run a cluster locally and execute the command `npm run test-cypress-dev-console` simultaneously

Execute the vulnerability/project-vulnerability.feature file

**Browser**
Chrome 99

**Test Execution Screenshot:**
Screenshot from 2022-04-13 02-33-34

### CODE REVIEW

**Comment by vikram-raj** [comment]
I tried to run it locally and 2 tests keep failing 
image

**Comment by vikram-raj** [comment]
@sanketpathak There is a type error. PTAL into it. This is the reason for tests failing on this PR.

image

**Comment by vikram-raj** [comment]
@sanketpathak another type error
image

**Review by vikram-raj — COMMENTED** [review]
Thanks @sanketpathak. All scenarios look good to me. and I tried it locally and tests are passing now.

/lgtm

**Comment by jrichter1** [comment]
Screenshot from 2022-04-26 13-57-17

/lgtm

**Review by jerolimov — APPROVED** [review]

**Comment by sanketpathak** [comment]
The pr only affects our E2E tests
/label qe-approved
/label docs-approved
/label px-approved

**Pull request merged**
