### PR TITLE
Bug 1999075: Pan the selected workload into the full view

### PR DESCRIPTION
**Pull request by karthikjeeyar**
**Fixes**: 

https://issues.redhat.com/browse/ODC-6054

**Analysis / Root cause**: 

When the component is selected, its not completely moved to the full view in the canvas

**Solution Description**: 

Change the minimumVisible prop to 100, so the selected component moves in the the full view. 

**Screen shots / Gifs for design review**: 

**Before**:

half-visible

**After:**
into-the-full-view

**Test setup:**

1. Click on that Deployment & the side panel will show
2. Close the side panel, drag that Deployment all the way to the right side of the canvas
3. Click on that Deployment again & you'll see that the deployment is moved in full view
4. Now with that side panel open carefully move that deployment so that it's partially hidden by the side panel
5. Close the side panel by clicking X on it
6. Select the deployment

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

cc: @serenamarie125 @jeff-phillips-18

### CODE REVIEW

**Review by andrewballantyne — APPROVED** [review]

**Comment by christianvogt** [comment]
/lgtm

We could probably look at adding a feature to topology that would instead bring the full item into view instead of defining a fixed pixel size.

**Comment by invincibleJai** [comment]
/lgtm

added again as label didn't got added earlier

**Pull request merged**
