### PR TITLE
[release-4.7] Bug 2055411: Filter superseded helm secrets and fix firehose to support partial metadata

### PR DESCRIPTION
**Pull request by jerolimov**
This is a manually cherry-pick/backport of #10936, this PR depends on #11077 (first commit) that should be reviewed/merged first.

4.10: https://bugzilla.redhat.com/show_bug.cgi?id=2039315
4.9: https://bugzilla.redhat.com/show_bug.cgi?id=2044292
4.8: https://bugzilla.redhat.com/show_bug.cgi?id=2046215
4.7: https://bugzilla.redhat.com/show_bug.cgi?id=2055411

**Merge notes**
Just need to add one extra type definition to support operator "NotEquals".

On release-4.7 branch:
image

With this PR:
image

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
Verified on cluster
image

/lgtm
/label backport-risk-assessed

**Comment by jerolimov** [comment]
> Verified on cluster image

/cc @sanketpathak @jrichter1

**Pull request merged**
