### PR TITLE
[release-4.7] Bug 1970485: Add pipeline annotation to secrets for private git repo import with pipeline

### PR DESCRIPTION
**Pull request by rottencandy**
This is a manual cherry pick of #9058 
Jira: https://issues.redhat.com/browse/ODC-4927

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
Verified locally, works as expected
/lgtm

**Review by andrewballantyne — APPROVED** [review]
Conflict was in the imports (things have moved around in 4.8). Content the same.

**Pull request merged**
