### PR TITLE
CONSOLE-2361: Remove Bootstrap 3/PatternFly 3 button, button-group styles

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by rhamilto** [comment]
/hold for approval

/assign @yapei 

@yapei We just need a regression test to make sure there are no visual problems with these changes.

**Review by sg00dwin — APPROVED** [review]
/lgtm

**Comment by XiyunZhao** [comment]
This PR has been verified on private build, the verification is focus on the component of dropdown list, like the dropdown list of groups, versions, scopes on API Explorer page, dropdown list of 'All Types' on Event page and so on. The changes on this PR is not impact the display or layout for the componet of dropdown list on the page.

**Comment by spadgett** [comment]
This PR has no user visible changes, and we have general docs and px approval for this epic. @ahardin-rh @sferich888 FYI

/label docs-approved
/label px-approved
/hold cancel

**Comment by rhamilto** [comment]
Rebased.  Please retag, @spadgett.

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by rhamilto** [comment]
Rebased.  Please retag, @spadgett

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
