### PR TITLE
[release-4.15] OCPBUGS-29781: Fix operands list endpoint.

### PR DESCRIPTION
**Pull request by TheRealJon**
The operands list endpoint was proxying to the public API server URL instead of the proxy endpoint configured at startup. This can cause mismatched TLS configuration when the console is running on-cluster.

Manual cherry-pick of https://github.com/openshift/console/pull/13632 since I've already cloned the original Jira ticket.

### CODE REVIEW

**Comment by yanpzhan** [comment]
Tested on cluster launched against the pr. After config a custom apiserver certificate on the cluster, try to uninstall an operator, the operator could be uninstalled without error on modal.
/label qe-approved
/label cherry-pick-approved

**Review by rhamilto — APPROVED** [review]
/lgtm

**Comment by TheRealJon** [comment]
/hold cancel
tests passed

**Pull request merged**
