### PR TITLE
CONSOLE-3759: Update file-loader pkg to latest version

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @rhamilto

### CODE REVIEW

**Comment by jhadvig** [comment]
QE Approver:
/assign @yanpzhan 
Docs Approver:
/assign @opayne1 
PX Approver:
/assign @RickJWagner

**Comment by XiyunZhao** [comment]
This UserStory has been verified by using regression testing, no issue was found

**Comment by jhadvig** [comment]
Closing in favour of https://github.com/openshift/console/pull/13743

**Pull request closed without merging**
