### PR TITLE
Bug 2058282: Fix WebSockets not reconnecting during upgrade

### PR DESCRIPTION
**Pull request by andrewballantyne**
### Problem

During upgrade the web socket would disconnect and not reconnect, thus breaking the live watching of the resource upgrade progress.

During the WSFactory migration from JS to TS we were cleaning up code and I made the mistake to ask for this chunk of code to be removed ([#10528 (comment)](https://github.com/openshift/console/pull/10528#discussion_r755219548)).

### Fix

- Reimplement the pass-thru param
- Clean up some types
- Don't delete options, a required property of the WSFactory object that was deleted during the destroy method; it is needed to recreate the web socket connection if desired (configured by options)

### Steps to reproduce

1. bring up a 4.10.3 cluster
2. visit http://localhost:9000/settings/cluster
3. set Channel to candidate-4.10
4. click Update and set version to update to 4.10.4
5. continue watching the Cluster Settings page **without refreshing or navigating elsewhere**
6. note the ClusterOperators count doesn’t update (before the bug fix, should auto update with this bug fix)

### CODE REVIEW

**Comment by rhamilto** [comment]
Tested against https://github.com/openshift/console/pull/11053 and the bug appears to be fixed.

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
