### PR TITLE
CONSOLE-2487: Combine i18n namesapces into public json file

### PR DESCRIPTION
**Pull request by zherman0**
[CONSOLE-2487](https://issues.redhat.com/browse/CONSOLE-2487)
Combine i18n namesapces into public json file
This is just a handful of files consolidated into one public.json file but it still creates a fairly large change.

As a note of which files I changed, I started with i18n files I was familiar with and then I switch to alphabetical for simplicity of tracking.

### CODE REVIEW

**Comment by zherman0** [comment]
@spadgett - Can you take a look, this ended up fairly big even with just 12 files consolidated.

**Review by spadgett — APPROVED** [review]
LGTM
/hold for approvals
/assign @yapei @ahardin-rh @reestr 

@zherman0 Needs rebase :/

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
