### PR TITLE
Bug 1791182: Add 4.3 channels to UI in 4.2.z

### PR DESCRIPTION
**Pull request by jhadvig**
Not fully sure about the `candidate-4.3`, @wking could you please confirm? Thanks.

/assign @spadgett

### CODE REVIEW

**Comment by jwforres** [comment]
Looking at what we did in 4.1 when we added 4.2, yes we included candidate https://github.com/openshift/console/blob/release-4.1/frontend/public/module/k8s/cluster-settings.ts

**Comment by jwforres** [comment]
I'm overriding BZ bot in this particular case, because channels are unique to every release until we have an API that we can call.

**Comment by spadgett** [comment]
@jhadvig `candidate-4.3` looks valid

**Comment by jhadvig** [comment]
Looks like a flake:
```
Container setup exited with code 1, reason Error
---
Installing from release registry.svc.ci.openshift.org/ci-op-2chm16zy/release@sha256:3d5c813e569a9269646a4ed3d10ecbad2417845981f453482aba4c55ffcc102c
level=warning msg="Found override for release image. Please be warned, this is not advised"
level=info msg="Consuming \"Install Config\" from target directory"
level=info msg="Creating infrastructure resources..."
level=error
level=error msg="Error: Error creating service account: googleapi: Error 429: Maximum number of service accounts on project reached., rateLimitExceeded"
level=error
level=error msg="  on ../tmp/openshift-install-682008443/iam/main.tf line 1, in resource \"google_service_account\" \"worker-node-sa\":"
level=error msg="   1: resource \"google_service_account\" \"worker-node-sa\" {"
````

/retest

**Pull request merged**
