### PR TITLE
Bug 1883302: Add dev-preview badge to application stages and details page

### PR DESCRIPTION
**Pull request by divyanshiGupta**
**Jira:** https://issues.redhat.com/browse/ODC-4921

**Screenshots:**
image
image

/kind bug

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
cc: @serenamarie125

**Comment by andrewballantyne** [comment]
/bugzilla refresh
/lgtm

Should get @rohitkrai03 Approval

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
