### PR TITLE
CONSOLE-3677: Convert edit-yaml.jsx from class component to functiona…

### PR DESCRIPTION
**Pull request by tvu20**
…l component

edit-yaml.jsx converted from a class component to a functional component in order to use react-router v6 hooks

### CODE REVIEW

**Comment by vojtechszocs** [comment]
The changes look good to me.

This is a relatively complex React component so please make sure to test it locally as well.

**Comment by yanpzhan** [comment]
@XiyunZhao will test the pr.

**Comment by XiyunZhao** [comment]
This PR has been tested on private build, with manual and regression testing, and no issue was found
/label qe-approved

**Review by jhadvig — APPROVED** [review]
/approve

**Pull request merged**
