### PR TITLE
Bug 1919379: Update dotnet logo for '.NET 5'.

### PR DESCRIPTION
**Pull request by tmds**
The open-source .NET platform '.NET Core' has been
rebranded '.NET' for the '.NET 5' release.

This updates the logo used by OpenShift to match that change.

The new logo is downloaded from https://raw.githubusercontent.com/dotnet/brand/master/logo/dotnet-logo.svg.
It is licensed under CC0 1.0 Universal.

cc @yselkowitz @omajid @aslicerh

### CODE REVIEW

**Comment by tmds** [comment]
@kyoto @yselkowitz is this good to merge?

**Comment by tmds** [comment]
ping @kyoto @yselkowitz

**Comment by omajid** [comment]
Hey folks, any ETA on when this PR can be merged? We have been trying to get this merged for 1.5 months now....

**Comment by yselkowitz** [comment]
Sorry, not much more I can do here.  Let's try finding another assignee.
/assign @bparees

**Comment by spadgett** [comment]
/override ci/prow/kubevirt-plugin

We had a bug where the kubevirt-plugin test ran on PRs where they shouldn't have. Overriding the status.

**Review by spadgett — APPROVED** [review]
/lgtm

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
