### PR TITLE
Update machine API group and version

### PR DESCRIPTION
**Pull request by spadgett**
cluster.k8s.io/v1alpha1 -> machine.openshift.io/v1beta1

See https://github.com/openshift/installer/pull/1175

cc @jwforres @derekwaynecarr

### CODE REVIEW

**Comment by enxebre** [comment]
looks good to me

**Comment by spadgett** [comment]
The installer changes have merged. This should be ready.

**Comment by spadgett** [comment]
flake https://jira.coreos.com/browse/CONSOLE-1266

/retest

**Pull request merged**
