### PR TITLE
[release-4.15] OCPBUGS-45248: Remove ClusterTask dependency in console from Pipelines 1.17

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
Manual cherrypick PR - https://github.com/openshift/console/pull/14537

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Tested using cluster bot. Working fine.

----With Pipelines 1.17---

https://github.com/user-attachments/assets/65c7af03-5b27-47bb-96db-349b1a7fa119

----

---With Pipelines 1.16---

https://github.com/user-attachments/assets/6a09e0c9-0e9d-458a-abd4-f0db83132bf1

/cc @vikram-raj @sanketpathak @The-Anton

**Comment by lokanandaprabhu** [comment]
Hi @vikram-raj ,

Need lgtm and approved label for this PR. Can you please review?

**Review by vikram-raj — COMMENTED** [review]
/lgtm

/approve

**Pull request merged**
