### PR TITLE
OCPBUGS-42418: Solved the knative test issue when instances are not present

### PR DESCRIPTION
**Pull request by sanketpathak**
Issue: https://issues.redhat.com/browse/OCPBUGS-42418

Before:
Screenshot from 2024-09-25 14-02-29

Now:
Screenshot from 2024-09-25 14-47-35

### CODE REVIEW

**Comment by logonoff** [comment]
/jira refresh

Tests don't seem to be working when I run them locally

image

**Review by logonoff — COMMENTED** [review]
Tests don't seem to be working when I run them locally

image

/jira refresh

**Comment by sanketpathak** [comment]
> Tests don't seem to be working when I run them locally
> 
> image
> 
> /jira refresh

The bug only fixes the issue with knative installation script when any CR instance is missing in a cluster with knative operator already installed. But I'll push the change for the issue you are facing.

**Review by logonoff — APPROVED** [review]
/lgtm

Tests are passing locally

image

**Review by vikram-raj — APPROVED** [review]
/approve

**Pull request merged**
