### PR TITLE
[release-4.11] OCPBUGS-2716: Update dependencies to the registry library and devfile parser

### PR DESCRIPTION
**Pull request by kim-tsao**
Backport changes from 4.12 PR: https://github.com/openshift/console/pull/12043

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Tested this as described here https://github.com/openshift/console/pull/12043#pullrequestreview-1129518578 on my local machine and the timeout works fine.

/label backport-risk-assessed
/lgtm
/approve

**Comment by jerolimov** [comment]
/retitle [release-4.11] OCPBUGS-2716: Update dependencies to the registry library and devfile parser

**Comment by jhadvig** [comment]
@kim-tsao there is a conflict in `pkg/devfile/sample.go`

**Comment by jerolimov** [comment]
@kim-tsao same here:

```
Checking gofmt...
gofmt checking failed:
pkg/devfile/sample.go
```

**Comment by kim-tsao** [comment]
> @kim-tsao same here:
> 
> ```
> Checking gofmt...
> gofmt checking failed:
> pkg/devfile/sample.go
> ```

@jerolimov can I get a retest?

**Comment by jerolimov** [comment]
Re-tested as described here https://github.com/openshift/console/pull/12043#pullrequestreview-1129518578 

1. With a network call that takes 10 seconds, the samples are shown after 3 seconds (not part of this PR) and the `/api/devfile` API call fails after 5 seconds. :heavy_check_mark: 

https://user-images.githubusercontent.com/139310/200819014-d6f22115-5e54-430d-a21a-51b9afde6071.mp4

2. Working example without timeout URL:

https://user-images.githubusercontent.com/139310/200819849-60eae683-a07d-46b0-b07b-028135dae182.mp4

/lgtm
@jhadvig, can you please add approval for this.
@sanketpathak, can you test this on a cluster and add cherry-pick-approved as well.

**Review by jhadvig — APPROVED** [review]
/approve

**Comment by sanketpathak** [comment]
Verified on a disconnected cluster with a proxy with console image of pr
[Screencast from 11-09-2022 01:08:23 PM.webm](https://user-images.githubusercontent.com/10252230/201086672-e392e098-b15d-4b5f-b8f6-1057272be3b9.webm)

**Pull request merged**
