### PR TITLE
Bug 1878375: Show different operator instances from same CSV separately in topology

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**Fixes**
https://issues.redhat.com/browse/ODC-4730

**Screen Shot**
image

**Description**
Fix to show separate operator instances from the same operator separately in Topology.

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

/kind bug

/cc @bgliwa01 @beaumorley @serenamarie125

### CODE REVIEW

**Comment by invincibleJai** [comment]
/approve 

verified the changes, works as expected

**Comment by karthikjeeyar** [comment]
Tested locally, works great!
/lgtm

**Pull request merged**
