### PR TITLE
Bug 2002896: Dispatch name filter value to redux

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
/lgtm cancel

This is causing a runtime error on the catalog sources tab:

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_console/10392/pull-ci-openshift-console-master-e2e-gcp-console/1456493577424080896/artifacts/e2e-gcp-console/test/artifacts/gui_test_screenshots/cypress/screenshots/catalog-source-details.spec.ts/1_Interacting%20with%20CatalogSource%20page%20--%20renders%20details%20about%20the%20redhat-operators%20catalog%20source%20(failed).png

**Comment by rawagner** [comment]
@spadgett fixed

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
