### PR TITLE
ODC-7671: Migrate KindFilterDropdown to PF5

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7671

**Screen shots / Gifs for design review**: 

demo:

https://github.com/user-attachments/assets/b5628d20-30d5-4484-a701-09d686c400a8

**Unit test coverage report**: 

n/a

**Test setup:**

n/a

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

This pr is 3/3 of [ODC-7671](https://issues.redhat.com//browse/ODC-7671) story as each file is being split into a separate PR.

### CODE REVIEW

**Comment by logonoff** [comment]
Tech debt that is not customer facing, so manually adding labels
/label px-approved
/label docs-approved

**Comment by The-Anton** [comment]
Tested using cluster bot, working as expected.
/label qe-approved

**Pull request merged**
