### PR TITLE
CONSOLE-2467: i18n localization for project dashboard

### PR DESCRIPTION
**Pull request by jcaianirh**
Addresses: https://issues.redhat.com/browse/CONSOLE-2467

Externalize strings for project dashboards.

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm
/hold for approvals
/assign @yapei @ahardin-rh @sferich888

**Comment by yapei** [comment]
tested locally and no issues found

**Comment by pweil-** [comment]
manually adding `valid-bug` until we work out https://github.com/openshift/release/pull/14440 since the console team is piloting the no feature freeze effort and this PR has all acks, approvals, and lgtms

**Pull request merged**
