### PR TITLE
dashboards: Fix padding in OCS buckets card

### PR DESCRIPTION
**Pull request by spadgett**
/cc @rhamilto @cloudbehl @rawagner 

Fixes this bug:

Dashboards · OKD 2019-10-28 10-34-38

### CODE REVIEW

**Comment by spadgett** [comment]
/lgtm cancel
needs rebase

**Comment by afreen23** [comment]
@spadgett  the change needs to be in resource providers too.
https://github.com/openshift/console/blob/742758136b20806991df47b44eb6c92cf98e53c6/frontend/packages/noobaa-storage-plugin/src/components/resource-providers-card/resource-providers-card-body.tsx#L19

`  return <>{body || children}</>;
`

Thanks for the fix!

**Comment by spadgett** [comment]
rebased and fixed the resource providers card

**Pull request merged**
