### PR TITLE
ODC-7396: Add Pipeline metrics tab using plugin

### PR DESCRIPTION
**Pull request by vikram-raj**
Story: https://issues.redhat.com/browse/ODC-7396

Descriptions: 
- Contribute Pipeline metrics tab using the plugin
- Add flags to the Metrics tab so that it can be overridden if the Pipeline metrics tab is contributed using the dynamic plugin,

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Tested locally, working fine.

/lgtm

https://github.com/openshift/console/assets/102503482/c06af828-1f14-4ad2-b0be-6e8e6608b397

**Comment by vikram-raj** [comment]
Propagate from the epic

/label docs-approved
/label px-approved

**Pull request merged**
