### PR TITLE
Bug 1871919: Add id to submit button in vm wizard

### PR DESCRIPTION
**Pull request by yaacov**
Add id to submit button in vm wizard

### CODE REVIEW

**Comment by yaacov** [comment]
@ibragins hi, can you check if this new ID help automation ?

**Comment by ibragins** [comment]
This should be helpful, thanks!

**Comment by yaacov** [comment]
@suomiy @pcbailey @irosenzw @glekner please review

**Comment by suomiy** [comment]
@yaacov maybe we could add ids to other buttons in this component as well for consistency?

**Comment by irosenzw** [comment]
I didn't see Filip added a comment

**Comment by yaacov** [comment]
> maybe we could add ids to other buttons in this component as well for consistency?

@suomiy added id's for all the buttons :+1:

**Comment by suomiy** [comment]
thanks!
/lgtm

**Pull request merged**
