### PR TITLE
removes references of deprecated selfLink

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes**: 
https://issues.redhat.com/browse/ODC-5591

**Solution Description**: 
`selfLink` is used in the codebase as the type and in mock test data, snapshots, as part of this ticket did clean up of this usage

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by jeff-phillips-18 — APPROVED** [review]

**Review by sahil143 — APPROVED** [review]
/lgtm

**Pull request merged**
