### PR TITLE
Bug 1907877: Added cypress automation scripts for pipleline builder 

### PR DESCRIPTION
**Pull request by makambalaji**
Jira Id: https://issues.redhat.com/browse/ODC-5191
Bugzilla Id; https://bugzilla.redhat.com/show_bug.cgi?id=1907877

Renamed the feature files and added the scripts related to pipeline builder

Please Note: These scripts are not integrated with CI
If need to verify, execute the below command "npm run test-cypress-devconsole" on fronted
On cypress UI, please select the create-from-builder-page.feature file from pipelines folder

Test Results:
No. of smoke test cases in this pr: 1 [Execution Time: 12 sec]
No. of regression test cases in this pr: 4 [Execution Time: 25 sec] 
image

No. of test cases in this pr: 10

Defect Raised :

### CODE REVIEW

**Comment by jerolimov** [comment]
@makambalaji can you please recheck this tests. Looks like `project-creation.feature` fails in this PR.

**Comment by makambalaji** [comment]
/hold 
Until the resolution of the afterAll hook, marking this or as hold

**Comment by spadgett** [comment]
/override ci/prow/ceph-storage-plugin

The ceph-storage-plugin job should only have run on PRs with changes to `frontend/packages/ceph-storage-plugin`. It failed due to an unrelated CI config change. Overriding status on this PR.

**Comment by andrewballantyne** [comment]
@makambalaji You have conflicts, you need to rebase.

/hold

Holding to try to stop CI from wasting cycles... remove once we have rebased

**Comment by andrewballantyne** [comment]
@makambalaji Would appear you have type errors.

**Comment by makambalaji** [comment]
Fixed the type issues @sanketpathak - Can you look at it now
@andrewballantyne - Removing the /hold as rebase is done
/hold cancel

**Comment by andrewballantyne** [comment]
/cc @karthikjeeyar 

Karthik can provide a review of the tests. I was just passing through and noticed the rapid failure notifications and investigated why.

**Comment by sanketpathak** [comment]
Builder smoke test ran clean 
/lgtm

**Pull request merged**
