### PR TITLE
Bug 2065840: Fix CronJob resource version to batch/v1

### PR DESCRIPTION
**Pull request by jhadvig**
Bumping last pieces of the old apiVersion of the CronJob resource, from `batch/v1beta1` to `batch/v1
/assign @rhamilto

### CODE REVIEW

**Comment by spadgett** [comment]
Looks like the API did not change between v1beta1 and v1: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125

**Review by spadgett — CHANGES_REQUESTED** [review]
Please update the `apiVersion` in `CronJobModel`

**Comment by spadgett** [comment]
/hold
(See my comment above.)

**Comment by jhadvig** [comment]
@spadgett comment addressed. Thank you :)

**Comment by rhamilto** [comment]
@jhadvig, you broke the CRUD test?  Hard to tell..

**Comment by rhamilto** [comment]
/hold

Confirmed with local testing the Search page kebab is busted by these changes.

**Comment by jhadvig** [comment]
@rhamilto issue fixed. 
I've forgot to update https://github.com/openshift/console/blob/master/frontend/packages/console-app/console-extensions.json#L184

**Pull request merged**
