### PR TITLE
ODC-7672: Migrate TelemetryConfiguration to PF5

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7672

**Screen shots / Gifs for design review**: 

before:

https://github.com/user-attachments/assets/915c1720-1e84-40d4-8941-6bb00584867b

after:

https://github.com/user-attachments/assets/d0502520-e174-43ab-b36d-6cb8baeaa83d

**Unit test coverage report**: 

n/a

**Test setup:**

run the bridge with `./bin/bridge --telemetry 'STATE=OPT-IN'` to enable telemetry, then remove the required flags `TELEMETRY_CLUSTER_CONFIGURATION` and `TELEMETRY_ENABLED` in [console-extensions.json](https://github.com/openshift/console/tree/master/frontend/packages/console-telemetry-plugin/console-extensions.json)

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

This pr is 1/2 of [ODC-7672](https://issues.redhat.com//browse/ODC-7672) story as each file is being split into a separate PR.

### CODE REVIEW

**Comment by vikram-raj** [comment]
Clicking anywhere in the window does not close the dropdown option. It should close the dropdown.

https://github.com/user-attachments/assets/31a8ba76-a7af-469a-986f-bb6355f34e1a

**Comment by logonoff** [comment]
> Clicking anywhere in the window does not close the dropdown option. It should close the dropdown.
> Screen.Recording.2024-08-30.at.3.47.42.PM.mov

amended, thanks for catching :)

**Comment by logonoff** [comment]
Tech debt that is not customer facing, so manually adding labels
/label px-approved
/label docs-approved

**Comment by The-Anton** [comment]
Working fine
/label qe-approved

image

**Pull request merged**
