### PR TITLE
ODC-7334: Show ConsoleSamples resources in the samples catalog

### PR DESCRIPTION
**Pull request by jerolimov**
**Fixes:**
Epic: [ODC-7241: Include Serverless Function Samples in our Sample Catalog](https://issues.redhat.com/browse/ODC-7241) 
Story: [ODC-7334: Show all ConsoleSample resources in the samples catalog](https://issues.redhat.com/browse/ODC-7334)

**Related issues:**
* https://github.com/openshift/enhancements/pull/1429
  * Rendered preview: https://github.com/jerolimov/openshift-enhancements/blob/console-samples/enhancements/console/samples.md
* https://github.com/openshift/api/pull/1503
  * https://github.com/jerolimov/api/blob/console-samples/console/v1/0000_10_consolesample.crd.yaml
* https://github.com/openshift/console-operator/pull/771
* https://github.com/openshift/console-operator/pull/776

To test the CRD you can apply it with this command to your cluster:

```
# delete just to ensure that you have the latest version installed
oc delete -f https://raw.githubusercontent.com/openshift/api/master/console/v1/0000_10_consolesample.crd.yaml
oc apply -f https://raw.githubusercontent.com/openshift/api/master/console/v1/0000_10_consolesample.crd.yaml
```

Some ConsoleSamples could be found here: https://gist.github.com/jerolimov/2e557df4ea95961dd64a5c32268daadf

```
oc apply -f https://gist.github.com/jerolimov/2e557df4ea95961dd64a5c32268daadf/raw/a23b1d54f3535f329afd79c858aea6b5cbe76e4c/nodeinfo-console-samples.yaml
oc apply -f https://gist.github.com/jerolimov/2e557df4ea95961dd64a5c32268daadf/raw/a23b1d54f3535f329afd79c858aea6b5cbe76e4c/knative-console-samples.yaml
oc apply -f https://gist.github.com/jerolimov/2e557df4ea95961dd64a5c32268daadf/raw/a23b1d54f3535f329afd79c858aea6b5cbe76e4c/localized-console-samples.yaml
```

### CODE REVIEW

**Comment by jerolimov** [comment]
Propagate from the epic

/label docs-approved
/label px-approved

**Comment by sanketpathak** [comment]
Verified on cluster bot with admin and non-admin users

https://github.com/openshift/console/assets/10252230/45f9f63e-1875-40b9-9d1c-5969134607b4

Screenshot 2023-07-19 at 3 41 46 AM

/label qe-approved

**Pull request merged**
