### PR TITLE
OCPBUGS-6272: Start the pipeline with workspace

### PR DESCRIPTION
**Pull request by hemantsaini-7**
Bug: https://issues.redhat.com/browse/OCPBUGS-6272

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Hi @hemantsaini-7 ,

I am getting one failed test case when I run e2e in local,

Screenshot 2023-01-24 at 1 38 32 PM

Screenshot 2023-01-24 at 1 38 52 PM

PTAL. Thanks.

**Review by jerolimov — APPROVED** [review]
It's a bit unfortunate that we have to remove the e2e for `VolumeClaimTemplate` here, but as this is flaky on our CI and sometimes cluster bot instances this is a good step into less flaky tests. Thanks for that.

/lgtm
/approve

**Review by jerolimov — APPROVED** [review]
/lgtm
/retest

**Pull request merged**
