### PR TITLE
migrate static extension to dynamic for knative plugin

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes**: 
https://issues.redhat.com/browse/ODC-6199

**Analysis / Root cause**: 

**Solution Description**: 
- migrate static extension to dynamic for knative plugin package

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Comment by invincibleJai** [comment]
label docs-approved
/label px-approved

added docs-approved on behalf of the docs team as the epic has a doc-ack label.
added px-approved on behalf of the px team as the epic has a px-ack label.
Epic link: https://issues.redhat.com/browse/ODC-5712

**Comment by invincibleJai** [comment]
/label docs-approved
/label px-approved

added docs-approved on behalf of the docs team as the epic has a doc-ack label.
added px-approved on behalf of the px team as the epic has a px-ack label.
Epic link: https://issues.redhat.com/browse/ODC-5712

**Comment by karthikjeeyar** [comment]
verified locally, works fine
/lgtm
/label qe-approved

**Pull request merged**
