### PR TITLE
CONSOLE-3675: Dynamic Demo Plugin: Add dashboard card with chart using QueryBrowser component

### PR DESCRIPTION
**Pull request by Mylanos**
Links to: https://issues.redhat.com/browse/CONSOLE-3675 

This PR adds the following:

1. New tab "Demo dashboard" in the overview page that showcases a new dashboard added by the demo plugin
2. Card "DashboardCard" containing QueryBrowser graph with a simple demo query integrated into the newly added dashboard.
3. The integration test for the added card.

image

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
Both chart and additional details are present on the dashboard.
Screenshot 2023-09-26 at 14 41 24


Really nice job @Mylanos 👍 
/lgtm
/approve

**Comment by jhadvig** [comment]
QE Approver:
/assign @yapei
Docs Approver:
/assign @opayne1
PX Approver:
/assign @RickJWagner

**Comment by RickJWagner** [comment]
Looks good, and useful for users that need it.  Thanks for providing this one.

**Pull request merged**
