### PR TITLE
Change PodRingSet to fetch pods, remove PodRingController

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**Fixes**
https://issues.redhat.com/browse/ODC-4966 (portions of it)

**Description**
Update PodRingSet to use the usePodsWatcher hook to retrieve pods based on the object being displayed. Remove PodRingController.
Also, remove extraneous type `DonutStatusData` (duplicate of `PodRCData`) from topology types.

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

/kind cleanup

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Topology and deployment screen works fine.
/lgtm

**Comment by sahil143** [comment]
/retitle Bug 1970274: Change PodRingSet to fetch pods, remove PodRingController

**Pull request merged**
