### PR TITLE
Bug 2016925: Monitoring dashboards: Fix switching from "All" option to other option

### PR DESCRIPTION
**Pull request by kyoto**
The handling of the GET parameter for the "All" option was incorrect.

Also shortened the GET parameter value string for the "All" option since
it is now visible in the URL.

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by juzhao** [comment]
tested with PR, checked "Prometheus / Overview" and "Kubernetes / Networking / Namespace (Pods)" dashboards, dashboards with All filter, change to a specific value and change back, all data display well now
/lgtm

**Comment by lihongyan1** [comment]
Tested with PR
/label qe-approved

**Pull request merged**
