### PR TITLE
Remove unused cluster-health component

### PR DESCRIPTION
**Pull request by spadgett**
/cc @rhamilto

### CODE REVIEW

**Comment by spadgett** [comment]
@TheRealJon fyi

**Comment by TheRealJon** [comment]
Definitely not `humanizeNumber`, I'm using it in #1448

**Comment by TheRealJon** [comment]
I think the `Scalar` component could be refactored to be a chart title.

**Comment by spadgett** [comment]
Thanks, updated to remove `Scalar` for now. I left `humanizeNumber`.

**Pull request merged**
