### PR TITLE
Add create vm dropdown action

### PR DESCRIPTION
**Pull request by yaacov**
Add a drop down action to create a VM from a template.

a. add a "create vm" action in vm templates list.
b. add a "create vm" action in vm template details page.

Screenshots:
Screenshot from 2020-04-07 09-10-59
Screenshot from 2020-04-07 09-11-12_01

Design: openshift/openshift-origin-design#350
Ref: https://github.com/openshift/console/pull/4811#issuecomment-609792010

### CODE REVIEW

**Comment by yaacov** [comment]
@suomiy @matthewcarleton @yfrimanm please review.

**Comment by yfrimanm** [comment]
lgtm

**Pull request merged**
