### PR TITLE
CONSOLE-3186: Add shared-plugin to the SDK Packages tables docs

### PR DESCRIPTION
**Pull request by tvu20**
Addresses: https://issues.redhat.com/browse/CONSOLE-3186

Documents the purpose of the '@openshift-console/plugin-shared' package in the SDK packages docs.

### CODE REVIEW

**Comment by jcaianirh** [comment]
QE Approver:
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

Console Approver:
/assign @rhamilto

LGTM Approver:
/assign @zherman0

**Review by zherman0 — APPROVED** [review]

**Pull request merged**
