### PR TITLE
Bug 1752845: Modified the text to remove tainting of nodes text on ocs install flow

### PR DESCRIPTION
**Pull request by gnehapk**

### CODE REVIEW

**Comment by obnoxxx** [comment]
@spadgett just like PR #2866, we need this backported to release-4.2 for one of the next z-streams.

**Comment by spadgett** [comment]
> @spadgett just like PR #2866, we need this backported to release-4.2 for one of the next z-streams.

Please clone the Bugzilla bug, set target release to 4.2.z, and open a PR against the release-4.2 branch. You can usually do this with `/cherrypick release-4.2` on the PR.

**Pull request merged**
