### PR TITLE
Bug 1889515: - Accessibility - The checkmark in the Node > overview page has no text description, label, or other accessible information

### PR DESCRIPTION
**Pull request by cyril-ui-developer**
/assign @jcaianirh 
cc: @spadgett

### CODE REVIEW

**Review by jcaianirh — APPROVED** [review]
looks good. thanks @cyril-ui-developer

**Review by spadgett — APPROVED** [review]
lgtm, but we might want to hold for @rhamilto's i18n PR

**Comment by spadgett** [comment]
Disregard, @rhamilto's PR doesn't hit this page since nodes are under Compute now. Thanks @cyril-ui-developer 👍 

/lgtm

**Comment by spadgett** [comment]
/lgtm cancel
Looks like the unit tests need to be updated.

**Review by cyril-ui-developer — COMMENTED** [review]
> /lgtm cancel
> Looks like the unit tests need to be updated.

@spadgett Updated it, thanks!

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
