### PR TITLE
Add user preferences to guided tour

### PR DESCRIPTION
**Pull request by rohitkrai03**
**Fixes**: https://issues.redhat.com/browse/ODC-6468

**Analysis / Root cause**: We needed to showcase user preferences as part of 

**Solution Description**: Added a new step to guided tour that shows user preferences.

**Screen shots / Gifs for design review**: @openshift/team-devconsole-ux @serenamarie125 

https://user-images.githubusercontent.com/6041994/150572830-0d6685bb-c93d-4014-9f72-f8a0a46d22af.mov

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by beaumorley** [comment]
@rohitkrai03 wow that was fast. looks great.

**Comment by invincibleJai** [comment]
Thanks @rohitkrai03 👍 

@beaumorley the texts have been updated 

- when web terminal operator is not installed
image


- when web terminal is installed

image

**Review by vikram-raj — COMMENTED** [review]
Verified the changes. 

/lgtm

**Comment by invincibleJai** [comment]
Propagate from epic:
/label docs-approved
/label px-approved

**Comment by beaumorley** [comment]
@rohitkrai03 LGTM thank you.

**Pull request merged**
