### PR TITLE
[release-4.5] Bug 1908587: fix filesystem queries

### PR DESCRIPTION
**Pull request by jhadvig**
Manual backport of https://github.com/openshift/console/pull/7278

@sjenning FYI

/assign @rhamilto

### CODE REVIEW

**Review by rhamilto — APPROVED** [review]
/lgtm

**Comment by markmc** [comment]
/hold

Feel free to remove this hold when the jobs are fixed

**Comment by markmc** [comment]
(patch manager) @jhadvig please explain why these very significant looking graphql changes were introduced in this backport, since they weren't in the 4.6 and 4.7 commit. Ideally these changes would be in their own commit (still in this PR, if appropriate)

**Comment by jhadvig** [comment]
@markmc sorry for that I've had to accidentally push additional change. Updated. PTAL

**Comment by markmc** [comment]
/unhold

Needs lgtm again

**Review by rhamilto — APPROVED** [review]
/lgtm

**Pull request merged**
