### PR TITLE
CONSOLE-3715: Move useAnnotationsModal to console-shared

### PR DESCRIPTION
**Pull request by vojtechszocs**
This should fix some potential cycles related to `AnnotationsModal` and `useAnnotationsModal` code.

- remove `ModalWrapper` and `AnnotationsModal` exports from Console internal SDK package
- move `useAnnotationsModal` code to `packages/console-shared/src/hooks` directory
- fix bug in `webpack.circular-deps.ts` due to `compilation.getStats().endTime` being `undefined`

Generated `.webpack-cycles` shows a decrease in total cycles from 378 to 366.

### CODE REVIEW

**Comment by rhamilto** [comment]
LGTM but will let @TheRealJon give the final approval since he did the initial implementation.

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Review by TheRealJon — CHANGES_REQUESTED** [review]
Actually, I just noticed, we aren't exposing this in the SDK. We need to export the `useAnnotationsModal` hook from the core API and add JSDoc.

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Comment by rhamilto** [comment]
Test failures indicate docs need to be generated an committed?

**Comment by vojtechszocs** [comment]
> Test failures indicate docs need to be generated and committed?

@rhamilto You are right, I missed the docs :man_facepalming: I will regenerate and add them to the PR.

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Comment by rhamilto** [comment]
@vojtechszocs, did you confirm usage of `useAnnotationsModal`?

**Comment by rhamilto** [comment]
> @vojtechszocs, did you confirm usage of `useAnnotationsModal`?

I did.  It works.  The caveat being that anything internal needs to use the internal import (e.g., `import { useAnnotationsModal } from '@console/shared/src/hooks/useAnnotationsModal';` and plugins can use the SDK import (e.g., `import { useAnnotationsModal } from '@openshift-console/dynamic-plugin-sdk';`).

https://github.com/openshift/console/assets/895728/b67a072d-798d-44f9-835a-c8834ecc8fe5

**Pull request merged**
