### PR TITLE
CONSOLE-2495: Check in remaining Chinese translations from Sprint 192

### PR DESCRIPTION
**Pull request by rebeccaalpert**
Received a new batch of Chinese translations today; checking them in in a separate PR.

These are all the remaining strings from Sprint 192.

Fixes https://issues.redhat.com/browse/CONSOLE-2495.

### CODE REVIEW

**Comment by rebeccaalpert** [comment]
CC @rh-tchuang.

**Comment by spadgett** [comment]
Will this conflict with #7224? We might want to simply combine them since #7224 hasn't merged and still needs to qe-approved label.

**Comment by rebeccaalpert** [comment]
Just the "Versions" key will conflict. Happy to do either approach.

**Comment by spadgett** [comment]
@rebeccaalpert I think at this point it would be better to do it as one PR.

**Comment by rebeccaalpert** [comment]
Closing in favor of updating https://github.com/openshift/console/pull/7224.

**Pull request closed without merging**
