### PR TITLE
Bug 2023060: [e2e][automation] Test for Windows VM with CDROM migration

### PR DESCRIPTION
**Pull request by lkladnit**
Cypress tests for [CNV-14292: add TC/automation for fixed bugs](https://issues.redhat.com/browse/CNV-14292) #4
[Polarion doc](https://polarion.engineering.redhat.com/polarion/#/project/CNV/wiki/Management/_UI_%20VM%20actions)
[TC](https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-7497)

### CODE REVIEW

**Comment by gouyang** [comment]
@lkladnit Let's moving this test to tier2 as it's not able to run in upstream actually.

**Comment by lkladnit** [comment]
Moved to tier2: https://gitlab.cee.redhat.com/cnv-qe/console/-/merge_requests/3

**Pull request closed without merging**
