### PR TITLE
[release-4.10] Bug 2099600: Topology toolbars are unaligned to other toolbars

### PR DESCRIPTION
**Pull request by Lucifergene**
This is a manual cherry-pick of https://github.com/openshift/console/pull/11160

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Tested locally and works fine :+1: 

/lgtm
/approve

**Comment by Lucifergene** [comment]
Tested this on a cluster bot:

https://user-images.githubusercontent.com/47265560/175144921-cd807f09-190c-4fb9-a661-ddd49431a640.mp4

**Pull request merged**
