### PR TITLE
CONSOLE-2877: Additional Operator badge for Single-Node Compatibility

### PR DESCRIPTION
**Pull request by maudem**
Changes in this PR:

-  A filterable value called sno (display name, Single Node Clusters) is available in the operators.openshift.io/infrastructure-features field for Operator authors to denote support for Single-Node OpenShift (SNO)
- CatalogSource with image `quay.io/rhamilto/example-registry:latest` and use the included `etcd` operator.

(Screen Shot 2021-07-20 at 2 13 27 PM
Screen Shot 2021-07-20 at 2 14 31 PM
)

/hold
/assign @TheRealJon 
/assign @spadgett

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
Thanks @maudem 👍 

/lgtm
/hold for approvals
/assign @yapei @ahardin-rh @sferich888 

@ahardin-rh Looks like this will need to be added to the docs here:

https://docs.openshift.com/container-platform/4.7/operators/operator_sdk/osdk-generating-csvs.html#osdk-csv-manual-annotations_osdk-generating-csvs

cc @kevinrizza @tlwu2013

**Review by TheRealJon — APPROVED** [review]
/lgtm
/approve

**Comment by rhamilto** [comment]
Ideally the two commits here would be squashed to one.  `git rebase -i upstream/master`

**Pull request merged**
