### PR TITLE
Bug 2077138: update pf-quickstart version

### PR DESCRIPTION
**Pull request by abhinandan13jan**
# Fixes
https://bugzilla.redhat.com/show_bug.cgi?id=2077138 / https://issues.redhat.com/browse/OCPBUGSM-43474?filter=-1

# Screenshot
Screenshot 2022-11-23 at 6 51 47 PM

Screenshot 2022-11-23 at 6 51 55 PM

multiline-exec-fix

## Testing
use YAMl
https://bugzilla.redhat.com/attachment.cgi?id=1873878

### CODE REVIEW

**Comment by invincibleJai** [comment]
/cc @jcaianirh , Joe PTAL at this change as we need `quickstart` bump for an issue and last we attempted with https://github.com/openshift/console/pull/12038 but it got reverted with  
https://github.com/openshift/console/pull/12063/files#diff-da6498268e99511d9ba0df3c13e439d10556a812881c9d03955b2ef7c6c1c655R145

Let us know if you see an issue with this change?

**Comment by Lucifergene** [comment]
I tested it in the 4.12 cluster. I am able to copy the code snippets mentioned in the code blocks. 

https://user-images.githubusercontent.com/47265560/204141418-565e9f43-4ad7-43b7-8012-030b2f6f9e00.mp4

**Review by Lucifergene — COMMENTED** [review]
I tested it in the 4.12 cluster. I am able to copy the code snippets mentioned in the code blocks.

https://user-images.githubusercontent.com/47265560/204141485-f12bb482-976d-43e6-bd07-45522f8ece19.mp4

**Comment by Lucifergene** [comment]
@abhinandan13jan There is still an issue. After installing the Web Terminal Operator, when I am trying to copy/execute the commands, only the first code block is getting properly copied/executed. The other one, which is in a list, is neither getting copied/executed. Video attached.

Do note that it's working well without installing the Operator as demoed in the previous video.

https://user-images.githubusercontent.com/47265560/204255158-b4ac21a9-135c-4816-9278-e391f5379cc6.mp4

**Comment by abhinandan13jan** [comment]
@Lucifergene So, initially the intent was to only have one copy/execute per step and that's how the implementation is. It reads the value stored based on a `html-id` and `executes/copies` it. So, in the example above only the first `copy/exec` snippet gets executed every-time. My use of multiple such snippets was only to demonstrate the UI/visual placements. 

The execute/copy for multiple snippets is a different issue which should be taken care of separately. cc: @invincibleJai @christianvogt 

code reference:
```
  const textToExecute = React.useMemo(() => {
    const executeTextId = element.getAttribute(MARKDOWN_EXECUTE_BUTTON_ID);
    return (docContext.querySelector(
      `${rootSelector} [${MARKDOWN_SNIPPET_ID}="${executeTextId}"]`,
    ) as HTMLElement).innerText;
  }, [element, rootSelector, docContext]);
 ```

**Comment by christianvogt** [comment]
@abhinandan13jan Looks like PF uses `groupId` when referencing the whereas console is using `groupType`
https://github.com/patternfly/patternfly-quickstarts/blob/main/packages/module/src/ConsoleShared/src/components/markdown-extensions/multiline-clipboard-extension.tsx

This could be why console is failing to find the correct corresponding elements.

**Comment by abhinandan13jan** [comment]
fixed @Lucifergene @christianvogt 
multiline-exec-fix

**Comment by Lucifergene** [comment]
Verified it in 4.12 cluster

/lgtm

**Review by Lucifergene — APPROVED** [review]

**Pull request merged**
