### PR TITLE
CONSOLE-3140: Expose ResourceIcon to dynamic-plugin-sdk

### PR DESCRIPTION
**Pull request by tvu20**
Addresses: https://issues.redhat.com/browse/CONSOLE-3140

Exposes ResourceIcon to the dynamic-plugin sdk.

### CODE REVIEW

**Comment by jcaianirh** [comment]
QE Approver:
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

Console Approver:
/assign @rhamilto

LGTM Approver:
/assign @zherman0

**Review by zherman0 — APPROVED** [review]

**Comment by yapei** [comment]
Screen Shot 2022-07-25 at 14 58 40
/label qe-approved

**Comment by rhamilto** [comment]
The story has an explicit acceptance criterion to "Add a CI test to check for the ResourceIcon component".  Not sure how/if we want to address.  @jhadvig?

/approve

**Comment by jhadvig** [comment]
@rhamilto you are right, but I think we could skip that one.
/lgtm

**Pull request merged**
