### PR TITLE
Bug 1871901: Fix restart and review quickstart scenario according to UX

### PR DESCRIPTION
**Pull request by rohitkrai03**
**Fixes**: https://issues.redhat.com/browse/ODC-4626

**Analysis / Root cause**: Restart/Resume the tour does not work if the side pane of another tour is open

**Solution Description**: Update restart/review based on latest UX.

**Screen shots / Gifs for design review**: 

@openshift/team-devconsole-ux @serenamarie125 @bmignano @beaumorley 

Peek 2020-08-24 20-20

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Tested it locally and works fine.
Code would receive a lgtm from me, but wait for a lgtm from UX.

/test e2e-gcp-console

**Comment by jerolimov** [comment]
One question for @openshift/team-devconsole-ux @serenamarie125 @bmignano @beaumorley:

When selecting a not-started quick start scenario and selecting the card and press "Start tour" on the left side (on the activated card) "nothing" happens. Is this fine for you?

**Comment by bmignano** [comment]
@jerolimov If I understand you correctly, clicking the card and the text both do the same action so if one has been done clicking the other doesn't do anything. If that is what you're referring to, I think that's okay.

**Comment by jerolimov** [comment]
Okay, I think also its ok :)

/lgtm

**Pull request merged**
