### PR TITLE
[release-4.7] Bug 1954962: removes extra annotations form spec template for ksvc

### PR DESCRIPTION
**Pull request by invincibleJai**
This is a manual cherry-pick of https://github.com/openshift/console/pull/8607

### CODE REVIEW

**Comment by sdodson** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*We've hit capacity of 50 for this week.*

* Score: *0.10*
* Reason: *maximum QE capacity for all z-stream is 50*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.10

approved

**Pull request merged**
