### PR TITLE
OCPBUGS-32222: Add warning about service binding operator will not be supported from 4.15

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
**Issue**: https://issues.redhat.com/browse/OCPBUGS-32222

**To Test**:
You can test the product name using window.SERVER_FLAGS.branding or in local using `./bin/bridge -branding 'openshift'` 

**Screenshots**:

---Topology Page---

Screenshot 2024-04-17 at 11 27 03 AM
Screenshot 2024-04-17 at 11 27 23 AM
Screenshot 2024-04-17 at 11 28 40 AM
Screenshot 2024-04-17 at 11 29 21 AM

---Service Binding list page---

Screenshot 2024-04-17 at 11 29 41 AM

---Service Binding details page---

Screenshot 2024-04-17 at 11 29 51 AM

---Catalog details side panel---

Screenshot 2024-04-17 at 11 30 16 AM

---Create Service Binding modal---
Screenshot 2024-04-17 at 11 30 39 AM

---Developer catalog page help text---
Screenshot 2024-04-17 at 12 54 01 PM

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Verified on a cluster bot and it looks nice :+1:

/lgtm
/approve

**Comment by jerolimov** [comment]
/retitle OCPBUGS-32222: Add warning about service binding operator will not be supported from 4.15

**Review by vikram-raj — COMMENTED** [review]
- Alert background color is same as modal background color in the dark theme. 

image

- Left and right padding should be added here and background color in dark theme is same here as well
image

**Comment by lokanandaprabhu** [comment]
Screenshot 2024-04-19 at 4 55 21 PM
Screenshot 2024-04-19 at 4 55 32 PM
Screenshot 2024-04-19 at 4 56 35 PM
Screenshot 2024-04-19 at 4 56 25 PM

Hi @vikram-raj / @jerolimov ,

Made the requested changes for dark mode. PTAL.

**Comment by jerolimov** [comment]
Deprecation warning ...

/label px-approved
/label docs-approved
/label qe-approved
/cc @sanketpathak

**Pull request merged**
