### PR TITLE
OCPBUGS-33801: Manually create an API token for a ServiceAccount

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @rhamilto 

@TheRealJon FYI

### CODE REVIEW

**Comment by rhamilto** [comment]
@jhadvig, something is missing.  If I try to follow the updated instructions, I get the following error:
```
❯ ./examples/run-bridge.sh                                                                                                                                   
++ oc whoami --show-server
++ oc -n openshift-config-managed get configmap monitoring-shared-config -o 'jsonpath={.data.alertmanagerPublicURL}'
++ oc -n openshift-config-managed get configmap monitoring-shared-config -o 'jsonpath={.data.thanosPublicURL}'
+ ./bin/bridge --base-address=http://localhost:9000 --ca-file=examples/ca.crt --k8s-mode=off-cluster --k8s-mode-off-cluster-endpoint=https://api.rhamilto.devcluster.openshift.com:6443 --k8s-mode-off-cluster-skip-verify-tls=true --listen=http://127.0.0.1:9000 --public-dir=./frontend/public/dist --user-auth=openshift --user-auth-oidc-client-id=console-oauth-client --user-auth-oidc-client-secret-file=examples/console-client-secret --user-auth-oidc-ca-file=examples/ca.crt --k8s-mode-off-cluster-alertmanager=https://alertmanager-main-openshift-monitoring.apps.rhamilto.devcluster.openshift.com --k8s-mode-off-cluster-thanos=https://thanos-querier-openshift-monitoring.apps.rhamilto.devcluster.openshift.com
W0708 17:17:17.084714   52685 authoptions.go:112] Flag inactivity-timeout is set to less then 300 seconds and will be ignored!
F0708 17:17:17.084743   52685 main.go:283] failed to complete authentication options: invalid flag: k8s-auth-bearer-token, error: cannot be used with --user-auth="oidc" or --user-auth="openshift"
```

**Comment by jhadvig** [comment]
> @jhadvig, something is missing. If I try to follow the updated instructions, I get the following error:
> 
> ```
> ❯ ./examples/run-bridge.sh                                                                                                                                   
> ++ oc whoami --show-server
> ++ oc -n openshift-config-managed get configmap monitoring-shared-config -o 'jsonpath={.data.alertmanagerPublicURL}'
> ++ oc -n openshift-config-managed get configmap monitoring-shared-config -o 'jsonpath={.data.thanosPublicURL}'
> + ./bin/bridge --base-address=http://localhost:9000 --ca-file=examples/ca.crt --k8s-mode=off-cluster --k8s-mode-off-cluster-endpoint=https://api.rhamilto.devcluster.openshift.com:6443 --k8s-mode-off-cluster-skip-verify-tls=true --listen=http://127.0.0.1:9000 --public-dir=./frontend/public/dist --user-auth=openshift --user-auth-oidc-client-id=console-oauth-client --user-auth-oidc-client-secret-file=examples/console-client-secret --user-auth-oidc-ca-file=examples/ca.crt --k8s-mode-off-cluster-alertmanager=https://alertmanager-main-openshift-monitoring.apps.rhamilto.devcluster.openshift.com --k8s-mode-off-cluster-thanos=https://thanos-querier-openshift-monitoring.apps.rhamilto.devcluster.openshift.com
> W0708 17:17:17.084714   52685 authoptions.go:112] Flag inactivity-timeout is set to less then 300 seconds and will be ignored!
> F0708 17:17:17.084743   52685 main.go:283] failed to complete authentication options: invalid flag: k8s-auth-bearer-token, error: cannot be used with --user-auth="oidc" or --user-auth="openshift"
> ```

@rhamilto you probably forgot to apply the change in the [run-bridge.sh](https://github.com/openshift/console/pull/14038/files#diff-31a19bdf719903ece6a6a6122d755dec0b2d580aa0347e939c8c9d7486da7054)

**Comment by rhamilto** [comment]
> @rhamilto you probably forgot to apply the change in the [run-bridge.sh](https://github.com/openshift/console/pull/14038/files#diff-31a19bdf719903ece6a6a6122d755dec0b2d580aa0347e939c8c9d7486da7054)

I've got that change as I checked out this PR.

**Comment by rhamilto** [comment]
```
console on  OCPBUGS-33801 [$] via 🐳 desktop-linux via 🐹 v1.22.4 via  v18.20.2 via 💎 v3.1.3 on ☁️  openshift-dev (us-east-1) took 5s 
❯ oc process -f examples/console-oauth-client.yaml | oc apply -f -
oc get oauthclient console-oauth-client -o jsonpath='{.secret}' > examples/console-client-secret
oauthclient.oauth.openshift.io/console-oauth-client created

console on  OCPBUGS-33801 [$] via 🐳 desktop-linux via 🐹 v1.22.4 via  v18.20.2 via 💎 v3.1.3 on ☁️  openshift-dev (us-east-1) 
❯ oc apply -f examples/sa-secrets.yaml
oc get secrets -n default --field-selector type=kubernetes.io/service-account-token -o json | \
    jq '.items[0].data."ca.crt"' -r | python -m base64 -d > examples/ca.crt
secret/builder-token created
secret/default-token created
secret/deployer-token created

console on  OCPBUGS-33801 [$] via 🐳 desktop-linux via 🐹 v1.22.4 via  v18.20.2 via 💎 v3.1.3 on ☁️  openshift-dev (us-east-1) 
❯ ./examples/run-bridge.sh
++ oc whoami --show-server
++ oc -n openshift-config-managed get configmap monitoring-shared-config -o 'jsonpath={.data.alertmanagerPublicURL}'
++ oc -n openshift-config-managed get configmap monitoring-shared-config -o 'jsonpath={.data.thanosPublicURL}'
+ ./bin/bridge --base-address=http://localhost:9000 --ca-file=examples/ca.crt --k8s-mode=off-cluster --k8s-mode-off-cluster-endpoint=https://api.lprabhu-090720241017.devcluster.openshift.com:6443 --k8s-mode-off-cluster-skip-verify-tls=true --listen=http://127.0.0.1:9000 --public-dir=./frontend/public/dist --user-auth=openshift --user-auth-oidc-client-id=console-oauth-client --user-auth-oidc-client-secret-file=examples/console-client-secret --user-auth-oidc-ca-file=examples/ca.crt --k8s-mode-off-cluster-alertmanager=https://alertmanager-main-openshift-monitoring.apps.lprabhu-090720241017.devcluster.openshift.com --k8s-mode-off-cluster-thanos=https://thanos-querier-openshift-monitoring.apps.lprabhu-090720241017.devcluster.openshift.com
W0709 08:11:32.570899   61738 authoptions.go:112] Flag inactivity-timeout is set to less then 300 seconds and will be ignored!
F0709 08:11:32.570933   61738 main.go:283] failed to complete authentication options: invalid flag: k8s-auth-bearer-token, error: cannot be used with --user-auth="oidc" or --user-auth="openshift"
```
```
#!/usr/bin/env bash

set -exuo pipefail

./bin/bridge \
    --base-address=http://localhost:9000 \
    --ca-file=examples/ca.crt \
    --k8s-mode=off-cluster \
    --k8s-mode-off-cluster-endpoint="$(oc whoami --show-server)" \
    --k8s-mode-off-cluster-skip-verify-tls=true \
    --listen=http://127.0.0.1:9000 \
    --public-dir=./frontend/public/dist \
    --user-auth=openshift \
    --user-auth-oidc-client-id=console-oauth-client \
    --user-auth-oidc-client-secret-file=examples/console-client-secret \
    --user-auth-oidc-ca-file=examples/ca.crt \
    --k8s-mode-off-cluster-alertmanager="$(oc -n openshift-config-managed get configmap monitoring-shared-config -o jsonpath='{.data.alertmanagerPublicURL}')" \
    --k8s-mode-off-cluster-thanos="$(oc -n openshift-config-managed get configmap monitoring-shared-config -o jsonpath='{.data.thanosPublicURL}')" \
    $@
```

**Pull request merged**
