### PR TITLE
Bug 1915176: Update snapshot API CRDs to v1 in web-console when creating volumesnapshot related resource

### PR DESCRIPTION
**Pull request by jhadvig**
Those resoruces are: 
- VolumeSnapshots
- VolumeSnapshotClasses
- VolumeSnapshotContents

/assign @spadgett

### CODE REVIEW

**Review by spadgett — COMMENTED** [review]
Are there any API changes from v1beta1 to v1 that we need to account for?

**Review by TheRealJon — APPROVED** [review]

**Comment by spadgett** [comment]
/override ci/prow/ceph-storage-plugin

The ceph-storage-plugin job should only have run on PRs with changes to `frontend/packages/ceph-storage-plugin`. It failed due to an unrelated CI config change. Overriding status on this PR.

**Comment by spadgett** [comment]
> Are there any API changes from v1beta1 to v1 that we need to account for?

I looked at the API, and I don't see any changes that would break our templates. @jhadvig Can you rebase?

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
