### PR TITLE
[release-4.9]Bug 2022303: Fix creation of ibm storage system at backing storage step

### PR DESCRIPTION
**Pull request by afreen23**
- an ibm storage system was getting created at backing storage step
 - this was hitting the case where user after selecting ibm storage skips to install it
 - creating ibm storage system in the end after waiting for ~2 mins for the external vendor crd

Signed-off-by: Afreen Rahman <afrahman@redhat.com>
(cherry picked from commit 142adbd8127d186b85837361b9427f93dffae017)

### CODE REVIEW

**Review by bipuladh — APPROVED** [review]
/lgtm 
/label backport-rist-assessed

**Comment by afreen23** [comment]
No ibm storage system created at backing storage step.

https://user-images.githubusercontent.com/25664409/142837675-fd5ebaa1-d01e-4fa1-b4c2-289923e86d99.mp4

**Comment by yapei** [comment]
QE has verified the changes and commented in BZ, adding proper labels
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
