### PR TITLE
Bug 1830121: Enable pod list to display node instead of owner

### PR DESCRIPTION
**Pull request by rhamilto**
and enable for daemon sets, jobs, replica sets, replication controllers, and stateful sets

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1830121

localhost_9000_k8s_ns_openshift-controller-manager_daemonsets_controller-manager_pods(5  PFXL)

### CODE REVIEW

**Comment by TheRealJon** [comment]
@rhamilto  I don't mind this solution too much, but I would prefer to use redux instead of passing the prop down through all of the intermediate components. PodTableRow is already connected to redux, so it shouldn't be too difficult to hook something up there. We just need to make sure to unset that state when we leave the pages that use it. Should be easy enough to set up a hook to do that as well. The only other thing I would say is that maybe we could name the `useAltTable` prop to something a little bit more descriptive?

In the long run, it would be nice if we came up with a way to handle this using a bit of logic. We can figure out if the current resource owns all the pods on the Pods tab using owner references and the uid of the currently viewed component. That being said, I think a solution like that might blow up the scope of this PR, so I'd be fine with a solution that uses redux as above.

**Comment by spadgett** [comment]
We should be able to use the existing `customData` prop to pass down any additional data without adding a new prop.

**Comment by rhamilto** [comment]
Take 2 using `customData`, which I now remember @spadgett mentioning before.  SHM ;-)

**Comment by rhamilto** [comment]
Note:  I intend to squash commits, but wanted to confirm we want the change for `Jobs`, `ReplicaSets`, and `StatefulSets`.

**Comment by rhamilto** [comment]
> Note: I intend to squash commits, but wanted to confirm we want the change for `Jobs`, `ReplicaSets`, and `StatefulSets`.

What about `ReplicationControllers`, too?

**Comment by spadgett** [comment]
I think it makes sense to add Replication Controllers here as well.

We want to see the owner for Deployments, Deployment Configs, and Cron Jobs. I see you've left out those resources, which is probably right.

It would be nice to hide the Namespace column, but we can make that a separate change.

**Pull request merged**
