### PR TITLE
Remove Console plugin SDK host-app package

### PR DESCRIPTION
**Pull request by vojtechszocs**
We're not planning to publish this package to npmjs so removing it for now.

### CODE REVIEW

**Review by florkbr — APPROVED** [review]
Looks good. Checked your branch out locally and don't see any additional references in the console or SDK.

**Comment by andrewballantyne** [comment]
No docs are needed, this is a correct of bad export code that isn't being consumed today.
/label docs-approved
/label px-approved

No QE effort needed as there is no export that is testable.
/label qe-approved

**Comment by andrewballantyne** [comment]
Waiting on https://github.com/openshift/console/pull/11044

**Comment by andrewballantyne** [comment]
/retest

I believe the previous test was on the old state of the repo before the fix. Hopefully this passes.

**Pull request merged**
