### PR TITLE
ODC-7655: Migrate monitoring/dashboards/index.tsx to PF5

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7655

**Solution Description**: 

Migrate file to PF5

**Screen shots / Gifs for design review**: 

Demo:

https://github.com/user-attachments/assets/10922e5b-21da-409b-9764-9b48526c74df

**Unit test coverage report**: 

unchanged

**Test setup:**

to see the observe dashboard in local development, use the mock data linked here https://github.com/openshift/monitoring-plugin/compare/main...zhuje:monitoring-plugin:mock_monitoring_dashboard_config

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

This pr is 3/4 of [ODC-7655](https://issues.redhat.com//browse/ODC-7655) story as each file is being split into a separate PR.

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
We can skip this PR changes as monitoring component will be removed from the console. 

Here is the PR for removing the Monitoring dashboard components from console https://github.com/openshift/console/pull/14192

**Comment by logonoff** [comment]
> We can skip this PR changes as monitoring component will be removed from the console.
> 
> Here is the PR for removing the Monitoring dashboard components from console #14192

cc @zhuje so that you can integrate this PRs changes into your PR

**Comment by zhuje** [comment]
@logonoff, thanks for the 'cc!  I'll incorporate these changes as a part of a seperate issue we have in our backlog: https://issues.redhat.com/browse/OU-499

**Review by vikram-raj — COMMENTED** [review]
/lgtm

**Comment by logonoff** [comment]
Tech debt that is not customer facing, so manually adding labels
/label docs-approved
/label px-approved

**Comment by logonoff** [comment]
> @logonoff I'm seeing issues with the UI when there Is small textual selection in the dropdown(in this case `All`)
> Screencast.from.2024-09-25.15-17-19.mov
> 
> FYI this is how it is in master
> 
> Screenshot from 2024-09-25 15-23-45

fixed! turns out there was some `min-width` in the patternfly component that I didn't account for :p

**Comment by sanketpathak** [comment]
Thanks for the change everything is working fine
Screenshot from 2024-09-26 16-48-05

/lgtm
/label qe-approved

**Pull request merged**
