### PR TITLE
Automation for Observe page features

### PR DESCRIPTION
**Pull request by jrichter1**
Epic: https://issues.redhat.com/browse/ODC-3698
Story: https://issues.redhat.com/browse/ODC-6384

**Checks for approving Epic scenarios Automation PR:**

- [x] Execute the @to-do tagged gherkin scripts manually
- [x] Convert the @to-do gherkin scripts to cypress automation scripts
- [x] Once scripts are automated, replace tag @to-do with @epic-number
- [x] Execute the scripts in Remote cluster

**Test Setup**
Check the TAGS in frontend/packages/topology/integration-tests/cypress.json file be: ""(@odc-3698) and not (@Manual or @to-do or @un-verified or @broken-test)"",

**Command to execute:**

Run a cluster locally and execute `./test-cypress.sh -p dev-console` simultaneously

Execute the following files:
 - changing-context-monitoring-dashboard.feature
 - dashboard-display.feature
 - topology-sidebar-actions.feature

**Browsers**
Chrome 90

**Screenshots**
m01
m02
m04

### CODE REVIEW

**Comment by sanketpathak** [comment]
/lgtm
Screenshot from 2022-01-27 15-38-59

**Comment by sanketpathak** [comment]
/cc @jerolimov 
Can you approve the pr

**Review by jerolimov — APPROVED** [review]
In general lgtm. Code changes only added some data-test attributes.

/approve

**Comment by sanketpathak** [comment]
This PR only affects our e2e tests.

/label qe-approved
/label px-approved
/label docs-approved

**Pull request merged**
