### PR TITLE
devconsole: setup sub-dir with OWNERS file

### PR DESCRIPTION
**Pull request by christianvogt**
Establishing the `extend/devconsole` space in the repository to contain all developer perspective related work according to phase 1 of the [Console Extensibility Plan](https://docs.google.com/document/d/1GtTvThPVn0PxPTbp2Hlpd7ABAjmW1Ul1uDsp77pk20E/)

Including an `OWNERS` file with team members as reviewers and approvers.

### CODE REVIEW

**Comment by joshuawilson** [comment]
You might want to add Nimisha too.

**Comment by joshuawilson** [comment]
@spadgett any idea why this keeps failing? It just adds 2 new files and the directory for them.

**Comment by spadgett** [comment]
e2e tests are failing because you don't have #1255 in master-next. An OperatorHub change broke the console-e2e tests.

I'll retarget to master

**Comment by spadgett** [comment]
We're investigating the OperatorHub flakes now

/retest

**Pull request merged**
