### PR TITLE
[release-4.16] OCPBUGS-38914: Unrelated readme opened when opening CodeReady workspaces from Quarkus using s2i quickstart

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
Manual cherrypick of https://github.com/openshift/console/pull/14140

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Tested using cluster bot. Working fine.


https://github.com/user-attachments/assets/b92b8807-fdd0-4e89-9b74-848cf1faf82e

**Review by vikram-raj — COMMENTED** [review]
/lgtm

**Pull request merged**
