### PR TITLE
fix Create route text for import forms

### PR DESCRIPTION
**Pull request by sahil143**
**Fixes**: https://issues.redhat.com/browse/ODC-5570

**Screen shots / Gifs for design review**: 

Screenshot 2021-03-02 at 2 21 53 PM
Screenshot 2021-03-02 at 2 22 03 PM

**Unit test coverage report**: 

**Test setup:**

**Browser conformance**: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by invincibleJai** [comment]
> **Fixes**: https://issues.redhat.com/browse/ODC-5570
> 
> **Screen shots / Gifs for design review**:
> 
> Screenshot 2021-03-02 at 2 21 53 PM
> 


@sahil143 code looks good. However, the checkbox and label are not aligned (though this doesn't seem associated with this PR)

**Comment by sahil143** [comment]
> > **Fixes**: https://issues.redhat.com/browse/ODC-5570
> > **Screen shots / Gifs for design review**:
> > Screenshot 2021-03-02 at 2 21 53 PM
> 
> @sahil143 code looks good. However, the checkbox and label are not aligned (though this doesn't seem associated with this PR)

I'm seeing this issue across the console. we might need another issue to fix this issue.

**Comment by spadgett** [comment]
Holding until #8289 merges to unblock CI.

/hold

**Pull request merged**
