### PR TITLE
Bug 1797382: git test updation-1

### PR DESCRIPTION
**Pull request by sanketpathak**
Added changes in git tests regarding some element correction, link updation and to rectify timeout error with navigateImportFromGit() function

### CODE REVIEW

**Comment by andrewballantyne** [comment]
@sanketpathak Unrelated to your changes, it appears these tests do not pass? Did you successfully get to the end? I'm getting an error and this is what the UI shows:

Screen Shot 2020-01-28 at 6 24 55 PM

My console printed out this:

```
3) git import flowNew application name testapp-0128-1833-4545
New app name app-0128-1833-2311

New application name testapp-0128-1833-3883
New app name app-0128-1833-8907
sendKeys failed for  applicationName  - retry nodejs-ex-git-apptext wastestapp-0128-1833-3883 testapp-0128-1833-3883
sendKeys failed for  applicationName  - second retry nodejs-ex-git-apptext wastestapp-0128-1833-3883text wastestapp-0128-1833-3883 testapp-0128-1833-3883
nodejs-ex-gittext wasapp-0128-1833-8907
sendKeys failed for  appName  - retry nodejs-ex-gittext wasapp-0128-1833-8907 app-0128-1833-8907
sendKeys failed for  appName  - second retry nodejs-ex-gittext wasapp-0128-1833-8907text wasapp-0128-1833-8907 app-0128-1833-8907
```

After digging into the code I think it has to do with this explanation:

```
  /* Note on the use of the SendKeys Protractor function: There is a widely reported
     bug in SendKeys where the function randomly drops characters. Most of the
     workarounds for this bug involve sending individual characters one-by-one,
     separated by calls to browser.sleep() or calls to Browser.executeScript
     to bypass the Protractor API. In our testing, we found neither of these approaches
     to be acceptable as we do not want to introduce sleep statements and calls to
     Browser.executeScript failed to retain values in text fields when buttons are
     subsequently pressed. We also found that the element.clear() function failed to
     clear text from text fields and that clearing text fields by sending a control/a
     sequence encountered the bug where characters are dropped by SendKeys. After
     experimentation, we found what *seems* to avoid most instances of characters being
     dropped by adding both "before" and "after" text in SendKeys calls. */
```

I'm not entirely sure I understand why Protractor would have this kind of error, this seems pretty fundamentally important for an automation testing framework... are we using a really old version or something?

I do not believe our tests are currently consumed by the console PR CI yet and this kind of error is something we do NOT need floating about. If this is intermittent, I couldn't get it to be... I ran about 5 times including debugging times and it never once passed.

@ldimaggi Do you know if these tests pass or if they have a high fail rate? I've never been able to successfully get these to pass and we intentionally ignored them when I was reviewing the first round of Pipeline work as @sanketpathak said you guys were working on it.

I understand that this PR is not the direct cause of any of this but I am doubting the validity of these tests in general if this is a common issue we have.

**Comment by ldimaggi** [comment]
It looks like there are (at least?) a couple of problems showing up here.

* The sendKeys() issue has been mentioned frequently (https://stackoverflow.com/questions/40985765/selenium-send-keys-sending-incomplete-string and elsewhere) - but I don't think that is what is failing here.

* I think that the problem that Andrew is seeing is a test bug - it looks like app name string are being concatenated over and over.

* This is odd as I was able to run the git test cleanly from Sanket's branch (sanketpathak/git-test-correction) as recently as Monday. 

* Sanket - We can look at this together at our Thursday meeting - but since that is late in the day Bangalore time - you should look at this in the morning.  One more thing - I ran the test locally again a cluster (Server Version: 4.4.0-0.ci-2020-01-24-140035) and saw a new failure.

The problem that I am seeing is here:
./frontend/packages/dev-console/integration-tests/tests/git-import-flow.scenario.ts

 ```
    56	await setBuilderImage(builderImageVersionName);
    57	expect(builderImage.isSelected());
    58	expect(buildImageVersion.getText()).toContain('8');
```
I'd recommend removing these statements. I don't think that they add much test coverage and they make the test brittle.

**Comment by sanketpathak** [comment]
I am unable to reproduce the issue @ldimaggi @andrewballantyne

**Comment by christianvogt** [comment]
@sanketpathak could you please address / respond to @ldimaggi's last comment recommendations.

**Comment by ldimaggi** [comment]
/lgtm

The git test is running cleanly for me on a 4.4 cluster (4.4.0-0.nightly-2020-01-31-165032) and this branch: sanketpathak/git-test-correction

**Pull request merged**
