### PR TITLE
Add Projects to Node Top consumers

### PR DESCRIPTION
**Pull request by rawagner**
Screenshot from 2020-04-15 11-36-50
Screenshot from 2020-04-15 11-37-00

### CODE REVIEW

**Comment by rawagner** [comment]
> Nice!
> 
> This is out of scope for this PR, but I think the items in this dropdown should be singular without the "s" instead of plural across all Breakdown popovers in all Overviews. So:
> 
> **Top consumers**
> By Project
> By Pod
> By Node
> By Storage Class
> By X
> 
> I'm not quite sure where to find that in the code, though.

:thumbsup:
fixed within this PR

**Comment by rawagner** [comment]
/hold
lets wait for https://github.com/openshift/console/pull/5050 and https://github.com/openshift/console/pull/4971 to merge first

**Comment by kyoto** [comment]
FYI @openshift/openshift-team-monitoring

**Pull request merged**
