### PR TITLE
CONSOLE-4357: Bump PatternFly to 5.4.2

### PR DESCRIPTION
**Pull request by kmcfaul**
Testing if the version bump with a slight manual adjustment of the PF entries in the lock file behaves on CI.

### CODE REVIEW

**Comment by rhamilto** [comment]
@kmcfaul, mind rebasing?

**Comment by rhamilto** [comment]
@kmcfaul, looks like there is an issue with the lock file.

/lgtm cancel

**Comment by rhamilto** [comment]
/assign @yapei

Adding approvals since this is tech debt:
/label px-approved
/label docs-approved

**Comment by rhamilto** [comment]
@yapei, can you or someone from your team please verify?  This has been waiting for a while and is blocking other bug fixes.

**Comment by yapei** [comment]
tested locally and no issues found 
/label qe-approved

**Pull request merged**
