### PR TITLE
topology i18n misses

### PR DESCRIPTION
**Pull request by debsmita1**
**This a clone of https://github.com/openshift/console/pull/8469**

### CODE REVIEW

**Comment by andrewballantyne** [comment]
/approve
/lgtm

See #8469 for all review comments

**Comment by jerolimov** [comment]
never give up

/test kubevirt-plugin
/woof

**Comment by andrewballantyne** [comment]
/hold

The kubevirt plugin is broken. See [the slack thread](https://coreos.slack.com/archives/C6A3NV5J9/p1618195395496000) for more information.

**Comment by andrewballantyne** [comment]
/retest
/unhold

Fix was provided here: https://github.com/openshift/console/pull/8609

**Comment by andrewballantyne** [comment]
@debsmita1 We had success it appears with the test passing, unfortunately you have a conflict now 😞

**Comment by jerolimov** [comment]
is this annoying :-/

/retest
/woof

**Pull request merged**
