### PR TITLE
Bug 1927898: i18n Admin Notifier

### PR DESCRIPTION
**Pull request by rebeccaalpert**
Internationalized notifier text.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1927898.

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
/lgtm

`yarn i18n` diff

**Comment by spadgett** [comment]
/lgtm cancel

`yarn i18n` diff

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by rebeccaalpert** [comment]
/test e2e-gcp-console

May need to rebase; error is related to Couchbase and I think that was fixed a while back.

**Pull request merged**
