### PR TITLE
update the text for Knative Service to Serverless Deployment

### PR DESCRIPTION
**Pull request by sahil143**
fixes: https://issues.redhat.com/browse/ODC-6074

This PR changes the text `Knative Service` in forms to `Serverless Deployments`.

Screenshot 2021-06-29 at 12 14 53 PM

### CODE REVIEW

**Review by jerolimov — COMMENTED** [review]
This is not a resource type anymore. Should we use react-i18next to make this value translatable?

**Comment by sahil143** [comment]
> This is not a resource type anymore. Should we use react-i18next to make this value translatable?

I don't think there is a need to translate this since Deployment is still a kind created by Serverless.

**Comment by jerolimov** [comment]
> > This is not a resource type anymore. Should we use react-i18next to make this value translatable?
> 
> I don't think there is a need to translate this since Deployment is still a kind created by Serverless.

@rebeccaalpert Wdyt?

**Comment by rebeccaalpert** [comment]
@jerolimov - We've been internationalizing resource kinds we have models for on the admin console side. You can see how we added a `labelKey` and `labelPluralKey` here: https://github.com/openshift/console/blob/master/frontend/public/models/index.ts#L7. If you use this approach, you have to wrap a TFunction around the `labelKey` or `labelPluralKey`. The alternative we've been doing is just also doing `t('public~Deployment details')`, etc. If you folks are able to internationalize them, it'll be more consistent with the rest of the console. (In some cases, the translators do chose to localize the resource kinds.)

**Comment by jerolimov** [comment]
@vikram-raj I would recommend to update the `ReadableResourcesNames` to a map which maps to i18n `labelKeys` instead of just labels, like:
```tsx
// Renamed to make it clear that it is required to call t() before showing it.
export const ResourcesTranslationKeys = {
  [Resources.OpenShift]: DeploymentConfigModel.labelKey,
  [Resources.Kubernetes]: DeploymentModel.labelKey,
  // t('devconsole~Serverless Deployment')
  [Resources.KnativeService]: 'devconsole~Serverless Deployment',
};
```

### The UI will show then (in Japanese)

image

And "Serverless Deployment" could be then also translated.

We still show the resource type below the "option title" untranslated.

`Deployment` and `DeploymentConfig` IS translated already on the admin side, our navigation and search as well. See:

### Current Deployment list (in Japanese)
image

### Create DeploymentConfig (in Japanese)
image

@rebeccaalpert  @openshift/team-devconsole-ux

Is this fine for you Rebecca and the UX team to change this form (only in the translated version)?

**Comment by jerolimov** [comment]
Thanks for the latest push, now also the alert message when a Pipeline combination isn't supported works fine:

Peek 2021-07-02 13-40

**Review by jerolimov — APPROVED** [review]
lgtm. I add also an hold label for feedback from @rebeccaalpert @openshift/team-devconsole-ux - if we don't get it today I think its also fine to merge this later.

/lgtm
/approve
/hold

**Review by invincibleJai — APPROVED** [review]

**Comment by rebeccaalpert** [comment]
@jerolimov - I can't speak for UX, but if the change is just internationalizing the resource kinds, I think that's great! It matches what we're doing on the admin console side.

Would you also be able to do the resource names under apps/Deployment, etc.?

**Comment by jerolimov** [comment]
As I understand we do not translate resource names? At least this is much better then before and I think we can merge this with your feedback. :)

/unhold

**Comment by rebeccaalpert** [comment]
@jerolimov - I mean in the sentence underneath the path (Deployment は..., etc.).

**Comment by jerolimov** [comment]
Got it, you mean this labels here.

* https://github.com/openshift/console/blob/9e002f6f4fb938d0093a741876ce51f8d21d0ba5/frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx#L40-L46
* https://github.com/openshift/console/blob/9e002f6f4fb938d0093a741876ce51f8d21d0ba5/frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx#L40-L46
* https://github.com/openshift/console/blob/9e002f6f4fb938d0093a741876ce51f8d21d0ba5/frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx#L40-L46
* https://github.com/openshift/console/blob/9e002f6f4fb938d0093a741876ce51f8d21d0ba5/frontend/packages/dev-console/src/components/import/section/ResourceSection.tsx#L40-L46

I don't know if we can change this right now.

**Pull request merged**
