### PR TITLE
Automation of toast notification and route label for epic ODC-6266

### PR DESCRIPTION
**Pull request by sanketpathak**
Epic: https://issues.redhat.com/browse/ODC-6266
Story: https://issues.redhat.com/browse/ODC-6411

Acceptance criteria:

- Show a toast notification when an application is imported from Git or imported Container image.
- If Route option was selected the toast notification should also show the external Route URL 
- Add a new "Additional route labels" option, with a label input field to the "Advanced Routing options"

**Checks required for approving Epic gherkin scripts PR:**

- [x] Add @epic-number to the scenarios or feature file [e.g: @odc-xxx]
- [x] Add @to-do for automation possible scenarios
- [x] Add @regression or @smoke based on the importance of the scenario
- [x] Update the test scenarios count in [Automation status confluence Report](https://docs.jboss.org/display/ODC/Automation+Status+Report)
- [x] Check for the linter issues by executing `yarn run gherkin-lint` on frontend folder [Skip epic number tags related linter issues]

**Fix**: https://issues.redhat.com/browse/ODC-6412

**Test Setup**:

Cluster should be running on local

Check the TAGS in frontend/packages/topology/integration-tests/cypress.json file be: ""(@pre-condition or @smoke or @regression) and @[odc-6266](https://issues.redhat.com/browse/odc-6266) and not (@manual or @to-do or @un-verified or @broken-test)"",

Command to execute:

Run a cluster locally and execute the command `npm run test-cypress-dev-console` simultaneously

Execute the create-from-git.feature file

**Browser**
Chrome 90

**Test Execution Screenshot:**

### CODE REVIEW

**Comment by jrichter1** [comment]
Getting an error verifying the route:
route

**Comment by jrichter1** [comment]
now it works
toasty

**Review by jerolimov — APPROVED** [review]
UI changes only add additional `dataTestID` attributes. Accepting this here because the prop already exist, otherwise I would like to move forward to `data-test` attributes.

/lgtm
/approve

**Comment by jerolimov** [comment]
This PR only affects our e2e tests.

/label qe-approved
/label px-approved
/label docs-approved

**Pull request merged**
