### PR TITLE
Remove unnecessary polyfills

### PR DESCRIPTION
**Pull request by spadgett**
We no longer support IE11. Remove core-js and url-polyfill polyfills.

### CODE REVIEW

**Comment by andrewballantyne** [comment]
@spadgett Did you want to remove `url-search-params-polyfill` as well from [app.jsx](https://github.com/openshift/console/blob/3d90303ff26b672e7d7b86888689a5d42bf140ee/frontend/public/components/app.jsx)? I believe we discussed that was also one that was no longer needed.

**Comment by spadgett** [comment]
> @spadgett Did you want to remove `url-search-params-polyfill` as well from [app.jsx](https://github.com/openshift/console/blob/3d90303ff26b672e7d7b86888689a5d42bf140ee/frontend/public/components/app.jsx)? I believe we discussed that was also one that was no longer needed.

Good catch, removed.

**Comment by andrewballantyne** [comment]
@spadgett looks like you have some conflicts

**Comment by andrewballantyne** [comment]
@spadgett Are we going to close this PR or did you want to update it?

**Comment by spadgett** [comment]
Removing `url-search-params-polyfill` causes a problem for tests that include `gitlab`. I might roll that back for now and investigate later.

**Comment by andrewballantyne** [comment]
> Removing `url-search-params-polyfill` causes a problem for tests that include `gitlab`. I might roll that back for now and investigate later.

Okay, spent all my review time trying to make this work lol. Turns out it's a limitation of the jest mocks for window. URLSearchParams needs aspects of location and that's just not mocked for free. The lost off this package means we lose that mock it seems.

Everything else looks good to me.

**Review by andrewballantyne — APPROVED** [review]
/lgtm

**Comment by andrewballantyne** [comment]
No documentation effort is needed for this change, just code cleanup.
/label docs-approved
/label qe-approved

I've done some QA effort to test around a few things. There isn't anything specific to test with this cleanup. 
/label qe-approved

**Comment by andrewballantyne** [comment]
ooops, two qe approves.

/label px-approved

**Pull request merged**
