### PR TITLE
[release-4.1] Bug 1797091: Fix bug where booleanSwitch does not default to false

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1797091

Partial back port of #3390

### CODE REVIEW

**Comment by shawn-hurley** [comment]
At this point we are only accepting critical bug fixes for 4.1. This does not seem to meet that target, do you want to close it (and the BZ) or make a case for why it is critical?

**Comment by rhamilto** [comment]
Closing per https://github.com/openshift/console/pull/4144#issuecomment-595837739 as the bug took too long to merge.

**Pull request closed without merging**
