### PR TITLE
[release-4.9] OCPBUGS-53: Non-existing link in the "Learn more about OpenShift update channels" in "Select Channel" pop-up.

### PR DESCRIPTION
**Pull request by cyril-ui-developer**

### CODE REVIEW

**Comment by yanpzhan** [comment]
@cyril-ui-developer Launched a cluster against the pr, click link in the "Learn more about OpenShift update channels" on the "Channel" pop up help info or in channel configuration pop-up, it points to a non-existing link:
https://docs.openshift.com/container-platform/4.9/html/updating_clusters/understanding-upgrade-channels-releases#understanding-upgrade-channels_understanding-upgrade-channels-releases
The valid link for 4.9 is https://docs.openshift.com/container-platform/4.9/updating/understanding-upgrade-channels-release.html#understanding-upgrade-channels_understanding-upgrade-channels-releases
Could you check the link in the code if it needs update?

**Comment by yanpzhan** [comment]
Rechecked on cluster launched against the pr, now the doc link points to https://docs.openshift.com/container-platform/4.9/updating/understanding-upgrade-channels-release.html#understanding-upgrade-channels_understanding-upgrade-channels-releases 
The fix works.
/label qe-approved

**Review by jerolimov — APPROVED** [review]
Verified by Yanping

/unhold
/approve

**Review by jcaianirh — APPROVED** [review]
/lgtm

**Pull request merged**
