### PR TITLE
ODC-7428: Update quick start name and document links for getting started section

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
**Story**: https://issues.redhat.com/browse/ODC-7428

**Demo**: 

https://github.com/openshift/console/assets/102503482/a5407292-cf1f-43a4-91bd-5e4c537d4701

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
Verified it.

/lgtm

**Comment by lokanandaprabhu** [comment]
Propage labels from the epic:

/label docs-approved
/label px-approved

**Comment by jerolimov** [comment]
Just updates some links as requested by PM. @sanketpathak please take a look. I hope you accept that I apply the qe label for now to get this merged asap. If you see any issue please let @lokanandaprabhu know.

/label qe-approved
/retest

**Comment by sanketpathak** [comment]
@lokanandaprabhu This is the UI I'm getting on cluster-bot

https://github.com/openshift/console/assets/10252230/69114ad1-c6d2-4c88-b8fd-6f9da9d07df2

**Comment by lokanandaprabhu** [comment]
Hi @sanketpathak ,

This is not related to this PR. This happened due to PatternFly 5 upgrade merged with master. To handle the styling I have created separate PR - https://github.com/openshift/console/pull/13356 for that.

**Comment by sanketpathak** [comment]
Verifies on cluster-bot with admin and non-admin users
/label qe-approved

**Pull request merged**
