### PR TITLE
Bug 1876853: Fix resource log not showing last line

### PR DESCRIPTION
**Pull request by TheRealJon**
Show last line of resource logs even when not newline-terminated.

### CODE REVIEW

**Comment by TheRealJon** [comment]
/hold

Depends on https://github.com/openshift/console/pull/6752

**Comment by spadgett** [comment]
/hold cancel

#6752 has merged

**Review by spadgett — APPROVED** [review]
LGTM, let me know when you rebase. Thanks!

**Comment by TheRealJon** [comment]
@spadgett  Rebase done

**Review by spadgett — APPROVED** [review]
/lgtm

**Review by dtaylor113 — APPROVED** [review]

**Pull request merged**
