### PR TITLE
[release-4.8] Bug 2046043: Topology performance: Do not fetch HPA for each Deployment (Pod Ring)

### PR DESCRIPTION
**Pull request by jerolimov**
This is a manual cherry-pick of #10913, which was a backport of #10894

4.10: https://bugzilla.redhat.com/show_bug.cgi?id=2042829
4.9: https://bugzilla.redhat.com/show_bug.cgi?id=2044259
4.8: https://bugzilla.redhat.com/show_bug.cgi?id=2046043

**Merge notes**
Import was reordered between 4.8 and 4.9. Just copy the complete file, so that the import now matches the newer releases.

**Test notes**
Could verify on my local cluster that release-4.8 requests the HPA list for each deployment and with this change just once.

release-4.8:
image

with this PR:
image

### CODE REVIEW

**Review by rottencandy — APPROVED** [review]
Looks good. Code changes are the same as original PR, aside from imports.
Also tested locally, HPA calls are fewer and watch is being used.
/lgtm

**Comment by sanketpathak** [comment]
Verified using cluster-bot
Screenshot from 2022-02-01 12-20-34
/label cherry-pick-approved

**Pull request merged**
