### PR TITLE
Bug 1876532:  Corrected system names for object service dashboard

### PR DESCRIPTION
**Pull request by afreen23**
Screenshots for the fix
Screenshot from 2020-09-17 09-31-00
Screenshot from 2020-09-17 09-31-13

### CODE REVIEW

**Comment by afreen23** [comment]
/hold 
tests need to be updated as well

**Comment by cloudbehl** [comment]
I see some extra space RADOS gateway & Provider than usual.
image

**Comment by afreen23** [comment]
> I see some extra space RADOS gateway & Provider than usual.

Fixed now:
Screenshot from 2020-09-17 12-20-05

**Pull request merged**
