### PR TITLE
[release-4.5.z] Bug 1879973: properly encode vpx URL

### PR DESCRIPTION
**Pull request by suomiy**

### CODE REVIEW

**Comment by suomiy** [comment]
can you please cherry-pick-approved ?
@sdodson @eparis @markmc @crawford

**Comment by sdodson** [comment]
Please see the patch manager documentation in the topic of #forum-release.
A patch manager will review according to the merge windows and there should
be no need to ping someone directly for PRs that only need
cherry-pick-approved label.

**Pull request merged**
