### PR TITLE
Update table classes for kube-virt, ceph-storage, bare-metal and network attachment

### PR DESCRIPTION
**Pull request by abhinandan13jan**
# Addresses

https://issues.redhat.com/browse/ODC-5816

# Screenshots
Ceph
ceph

Kubevirt

vm-layout
vm-nic
vm-wizard

# Tests 
None change

# Broswer conformance

Chrome

### CODE REVIEW

**Review by afreen23 — APPROVED** [review]
Approved ceph chnages. Thanks for the fix!

**Comment by glekner** [comment]
missing some kubevirt tables 
image

**Comment by abhinandan13jan** [comment]
> missing some kubevirt tables
> image

Hi @glekner , I checked the files and all are updated and most have no associated `bootstrap class` for table, so there is no need for a change. This PR targets to update Bootstrap classes used in tables.

- networking-tab.tsx  -- imports `nicTableColumnClasses` from another file
- vm-wizard-nic-row -- columnClasses is a prop, cannot find any bootstrap class 
- vm-wizard-storage -- same as abve
- affinity-modal -- borrows columnclass from `helper` file which is updated
- disk-row -- `columnClass` is a prop. no bootstrap associated
- nic-row -- same as above
- vm-snapshot -- imports columnClassfrom external file
- vm-nics -- imports columnClass from external file
- vm-snapshot-row -- column class is a prop

**Comment by nemesis09** [comment]
verified locally
works as expected
/lgtm

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Comment by andrewballantyne** [comment]
Looks like internal errors with google apis... I'm not going to retest right now because I think it's best to let the bot do it (hopefully it's wiser to the success rate of external apis and their stability)

**Pull request merged**
