### PR TITLE
Set Resources tab as default of resources overview side panel

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Fixes https://jira.coreos.com/browse/ODC-1683

### CODE REVIEW

**Comment by beanh66** [comment]
I am fine either keeping the order as is or switching to have resources appear first. Either way, I don't think we should change the name of the tabs since we reference the same "Overview" tab on the full detail pages.

**Comment by jeff-phillips-18** [comment]
Need a final answer here. Anyone... anyone... Bueller...

@sspeiche @serenamarie125 @beanh66

**Comment by serenamarie125** [comment]
My 2 cents ... Resources tab should be selected by default, and Overview first.  

As Steve mentioned, the selected will be remembered regardless so for some the 2nd tab may be the default regardless.

**Comment by sspeiche** [comment]
+1 to Resources tab should be selected by default, and Overview first.

**Comment by spadgett** [comment]
I still think it's weird, but I seem to be in the minority :) I'll defer to you guys

**Comment by jeff-phillips-18** [comment]
@spadgett willing to approve?

**Pull request merged**
