### PR TITLE
Fix to make provisioned services page name-spaced

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Also removes extranous fetching/watching of web-sockets for resources.

https://jira.coreos.com/browse/CONSOLE-1179
https://bugzilla.redhat.com/show_bug.cgi?id=1664577

### CODE REVIEW

**Comment by spadgett** [comment]
Should we use the `withRouter` HOC instead of passing `match` through?

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/withRouter.md

**Comment by jeff-phillips-18** [comment]
@spadgett The HorizontalNav component requires the `match` parameter and passes it along to each of the sub-components. Is it worth making the `match` parameter optional and making the change to use `withRouter`?

**Comment by spadgett** [comment]
Ah, OK. If that's the pattern we're using elsewhere, let's go ahead with that.

**Comment by spadgett** [comment]
```
$ eslint --ext .js,.jsx,.ts,.tsx --color .

/go/src/github.com/openshift/console/frontend/__tests__/components/operator-lifecycle-manager/install-plan.spec.tsx
  118:7   error  'match' is never reassigned. Use 'const' instead  prefer-const
  120:20  error  Missing trailing comma                            comma-dangle
  121:6   error  Missing trailing comma                            comma-dangle

✖ 3 problems (3 errors, 0 warnings)
```

**Comment by jeff-phillips-18** [comment]
Fixed those issues above.

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
