### PR TITLE
Bug 2044803: buttons styles aligned

### PR DESCRIPTION
**Pull request by upalatucci**
**Fix:**
https://bugzilla.redhat.com/show_bug.cgi?id=2044803

**Analysis / Root cause:**
Buttons with different styles applied across tabs

**Solution Description:**
Apply the same style on all top page buttons across tabs

**Before:**
Screenshot from 2022-01-26 12-06-19
Screenshot from 2022-01-26 12-04-13
Screenshot from 2022-01-26 12-04-07
Screenshot from 2022-01-26 12-04-02

**After:**
Screenshot from 2022-01-26 15-17-32
Screenshot from 2022-01-26 12-26-53
Screenshot from 2022-01-26 12-26-56
Screenshot from 2022-01-26 12-27-00

### CODE REVIEW

**Comment by yfrimanm** [comment]
Hi @bgaydosrh or @lmandavi@redhat.com, would you please review the mentioned changes?
Thank you.

**Comment by bgaydosrh** [comment]
Hi @yfrimanm - My only comment (and this might not be possible) would be to present the expander for the **Guest Login Credentials** header closer to the heading instead of to the far right of the screen.

**Comment by upalatucci** [comment]
Hi @bgaydosrh, thanks for your eagle eye. 
This is a different bug from what the PR is trying to resolve. 
I would like to discuss the resolution with the team as it involves adding some styling in a patternfly component. 
It just seems a little tricky to me. But I got the point of your observation and thanks

**Comment by yfrimanm** [comment]
> Hi @yfrimanm - My only comment (and this might not be possible) would be to present the expander for the **Guest Login Credentials** header closer to the heading instead of to the far right of the screen.
> 
> Screenshot from 2022-01-26 13-02-31

Thank you @bgaydosrh! Just making sure that the capitalization is now correct in the top page buttons across the tabs. Correct?
The Guest Login Credentials will be issued in another bug.

**Comment by bgaydosrh** [comment]
Hi @yfrimanm and @upalatucci - No problem, I understand Pattern Fly may have limitations with things like the expander. 

I see no problems with the presentations on the headers. The only question would be on "Network interfaces" --- if you want to cap both words or not. Doc follows strict sentence-style casing (which is first word only) but UI may be different. The most important thing is that you follow whatever style you are adhering to currently (so the user sees the same type of capitalization everywhere), and even that is hardly a showstopper. Make sense? If not, let me know.

Thanks,
Bob

**Comment by yfrimanm** [comment]
Thank you @Robert Gaydos ***@***.***> this makes perfect sense to
me as well.

**Pull request merged**
