### PR TITLE
[release-4.13] OCPBUGS-15228: Create helm release page doesn't show a YAML editor when schema isn't available (httpd-imagestreams chart)

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
This is an manual cherry-pick of https://github.com/openshift/console/pull/12914

Automated cherry-pick PR https://github.com/openshift/console/pull/12919 frontend test is failing, creating manual cherry-pick PR to analyse and update.

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Tested using cluster bot

/lgtm

https://github.com/openshift/console/assets/102503482/c9bb23b4-c56a-4bf5-bb06-68dd167df6d2

**Comment by vikram-raj** [comment]
/retitle [release-4.13] OCPBUGS-15228: Create helm release page doesn't show a YAML editor when schema isn't available (httpd-imagestreams chart)

**Pull request merged**
