### PR TITLE
adds spec to get knative resources utils

### PR DESCRIPTION
**Pull request by invincibleJai**
- adds spec to get knative resources utils

Tracks: https://jira.coreos.com/browse/ODC-1980

### CODE REVIEW

**Comment by invincibleJai** [comment]
@sahil143 yes we need to decide on the place maybe something shared for `mocks` as here mocks  are sahred in `dev-console` as well as in `knative-plugin` packages.

@christianvogt any inputs

**Comment by sahil143** [comment]
We can add a mocks directory in console-shared and import it from there because In PR #2849 I'm also importing mock data from topology inside console-shared utils tests.

**Comment by invincibleJai** [comment]
@sahil143 yes makes sense only doubt I have as these mocks are related to knative so should  this be moved to `console-shared`  or to `knative-plugins`

**Comment by sahil143** [comment]
@invincibleJai I would suggest moving knative mocks to console-shared because those mocks can also be used in topology to test knative deployments and graph data related to them.

**Comment by christianvogt** [comment]
We should try to keep knative separate.
Anywhere knative needs to _plugin_ to the console we need extensions to support this. Eg. Topology should be pluggable.

**Pull request merged**
