### PR TITLE
Bug 2099654: Fix endless re-render loop when associatedDeployment is not defined

### PR DESCRIPTION
**Pull request by jerolimov**
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2099654

**Analysis / Root cause**: 
The endless rerender happens because `EventSink` sets `associatedDeployment` to a empty object `= {}` when its not defined.

https://github.com/openshift/console/blob/e9ceaf5d255eee6bac40e0733d6e635151345b0d/frontend/packages/knative-plugin/src/topology/components/nodes/EventSink.tsx#L60-L75

On each rerender this object doesn't match the old instance and triggers the updateResources call in usePodsWatcher:

https://github.com/openshift/console/blob/e9ceaf5d255eee6bac40e0733d6e635151345b0d/frontend/packages/console-shared/src/hooks/usePodsWatcher.ts#L49-L51

And then we have an endless re-render loop...

**Solution Description**: 
1. Don't set `associatedDeployment` to a empty object `= {}`, just keep it undefined
2. Make the rest of the code save if the `associatedDeployment` is null or undefined.
3. Don't watch anything in `usePodsWatcher` if NO resource AND NO kind is defined.
4. Add useMemo for `const revisionIds` in `EventSink` because the revision.map creates a new array every render and breaks the `const donutStatus` `useMemo`

Highlight updates in React dev tools before:

https://user-images.githubusercontent.com/139310/175125694-9e716992-48f6-47bc-9ff6-4c352eb870b2.mp4

Highlight updates in React dev tools with this PR:

https://user-images.githubusercontent.com/139310/175125705-ef66dba3-6180-409e-8c51-1cf9d824c0bf.mp4

**Unit test coverage report**: 
Untouched

**Test setup:**
1. Install Serverless and Camel K operator
3. Create required eventing resources
4. Open the developer perspective
5. Navigate to Add > Event Sinks and search for HTTP
6. Select "HTTP Sink" and press "Create Event Sink"
7. Enter any URL and press Create
8. Navigate to the topology graph, open the react dev tools (browser extension)
9. Select the React Components tab and enable "Highlight updates when component render."

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by invincibleJai** [comment]
Thanks, Christoph, this Looks good. Need to verify it once.

**Comment by vikram-raj** [comment]
Verified it locally and do not see the re-rendering of the `EventSink` node in the topology.

**Pull request merged**
