### PR TITLE
Bug 1990018: chore(i18n): update translations

### PR DESCRIPTION
**Pull request by rebeccaalpert**
Adding latest translations from Memsource project https://cloud.memsource.com/web/project2/show/1im7WzX1P5AZB4xc2yY0nk.

Related bug (console-app misspelled a word): https://bugzilla.redhat.com/show_bug.cgi?id=1990024

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1990018.

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by rebeccaalpert** [comment]
Putting on hold until test is fixed.

**Comment by rebeccaalpert** [comment]
Rebasing since the test fix seems like it merged.

**Comment by spadgett** [comment]
> Rebasing since the test fix seems like it merged.

Note that you shouldn't need to rebase since CI will merge your PR with current master. (It doesn't cause a problem of course.)

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
