### PR TITLE
Better align masthead styles with those in origin-web-console

### PR DESCRIPTION
**Pull request by rhamilto**
So that when switching between consoles, the differences aren't as obvious.  Note:  this doesn't make it pixel-perfect, but it's not intended to.

Before:
http://recordit.co/beLTPGbiDk

After:
http://recordit.co/O059VM1vO3

### CODE REVIEW

**Comment by rhamilto** [comment]
> The font stack change is still noticeable

font stack shouldn't be changing.  font size is going up 1px in bridge/tectonic...

**Comment by rhamilto** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
Hm

```
1) Kubernetes resource CRUD operations Visiting special routes : successfully displays view for route: /k8s/cluster/clusterroles/view
   Error: Failed: omg js error: true
```

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
