### PR TITLE
[release-4.7] Bug 1962493: Hide TaskRun edit actions for rows in Pipelinerun's TaskRun tab

### PR DESCRIPTION
**Pull request by rottencandy**
This is a manual cherry pick of #8960

### CODE REVIEW

**Review by andrewballantyne — APPROVED** [review]
Types getting their own files caused the conflict.

/lgtm

**Comment by sdodson** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*We've hit capacity of 50 for this week.*

* Score: *0.20*
* Reason: *maximum QE capacity for all z-stream is 50*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by derekwaynecarr** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

approved

**Pull request merged**
