### PR TITLE
OCPBUGS-35287: Alphabetize icons, alias httpd to apache

### PR DESCRIPTION
**Pull request by logonoff**
Links to https://issues.redhat.com/browse/OCPBUGS-35287

I also alphabetized the map object 

Before:
image

After:
image

/cc @Lucifergene

### CODE REVIEW

**Review by Lucifergene — APPROVED** [review]
Thank you @logonoff for sorting the list!

The issue looks resolved on the Git Import page

/lgtm

**Review by jerolimov — APPROVED** [review]
/retest
/approve

**Pull request merged**
