### PR TITLE
move ObjectEnum from console-shared to kubevirt

### PR DESCRIPTION
**Pull request by glekner**

### CODE REVIEW

**Comment by glekner** [comment]
@spadgett @vojtechszocs @christianvogt please review

**Comment by christianvogt** [comment]
@glekner I don't think this is a valid API for the console plugin SDK to expose. It is a utility to help with enums but it doesn't help the plugin developer to build plugins.

I suggest copying the code to your repo. 

We want to expose API that are required to build plugins, help them work with k8s APIs, and build a consistent user interface.

**Comment by glekner** [comment]
@christianvogt yep, moved the code into kubevirt

**Review by spadgett — APPROVED** [review]
/lgtm
/hold for others to look as well

**Comment by christianvogt** [comment]
/hold cancel

i'm fine with the move

**Pull request merged**
