### PR TITLE
CONSOLE-2361:  Remove Bootstrap 3/PatternFly 3 dropdown styles

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by rhamilto** [comment]
/hold for approval

/assign @yapei

@yapei We just need a regression test to make sure there are no visual problems with these changes.

**Review by sg00dwin — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
This PR has no user visible changes, and we have general docs and px approval for this epic. @ahardin-rh @sferich888 FYI

/label docs-approved
/label px-approved
/hold cancel

**Comment by rhamilto** [comment]
Rebased.  Please retag, @spadgett.

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
