### PR TITLE
[release-4.9]Bug 2056826: Revert "Merge pull request #10316 from dtaylor113/e2e-tests-replace-codeready-operator"

### PR DESCRIPTION
**Pull request by bipuladh**

### CODE REVIEW

**Comment by bipuladh** [comment]
/test frontend

Unit tests are failing but are untouched.

**Review by jhadvig — APPROVED** [review]
Tagging for merge since 3scale should be available on the 4.9 cluster

/approve
/lgtm

**Comment by spadgett** [comment]
/lgtm cancel

It looks like there's a problem with the updated tests. Both failures were the same error.

[screenshot](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_console/11087/pull-ci-openshift-console-release-4.9-e2e-gcp-console/1496049125047668736/artifacts/e2e-gcp-console/test/artifacts/gui_test_screenshots/cypress/screenshots/create-namespace.spec.ts/1_Create%20namespace%20from%20install%20operators%20--%20creates%20namespace%20from%20operator%20install%20page%20(failed).png)

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by jerolimov** [comment]
4.8 branch is also broken at the moment

/cherry-pick release-4.8

**Pull request merged**
