### PR TITLE
Bug 1779932: Fix VM template-namespace label

### PR DESCRIPTION
**Pull request by pcbailey**
This PR changes the VM template-namespace annotation label from 'vm.kubevirt.io/template-namespace' to 'vm.kubevirt.io/template.namespace'.

### CODE REVIEW

**Comment by rawagner** [comment]
@pcbailey shouldn't we update https://github.com/openshift/console/blob/master/frontend/packages/kubevirt-plugin/src/models/templates/vm-template-yaml.ts#L18 too ?

**Comment by pcbailey** [comment]
@rawagner I don't know how I missed that one. I fixed it. Thanks for catching it! =)

**Pull request merged**
