### PR TITLE
Bug 2076544: Added margin-bottom for the paragraph component

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-43396

**Analysis / Root cause**: 
PatternFly removed a generic rule for the paragraph component. It was adding margin-bottom by default before now it is not.

**Solution Description**: 
Added margin-bottom styling for paragraph component. Not kept the class in global level, added class for the component levels.

**Screen shots / Gifs for design review**: 

Changed in 8 screens, attached all the screenshots below with the steps to the page

1) Administrator -> workloads -> secrets -> secret details -> Add secret to workload 

--------BEFORE----------

Add secret to workload

--------AFTER-----------
Add secret to workload

==========================================

2) Administrator -> Observe -> Alerting -> Silence -> Create silence

--------BEFORE----------

Pasted Graphic 1

--------AFTER-----------

Create silence

==========================================

3) Administrator -> Administation -> Cluster Settings -> Configuration

--------AFTER-----------

Cluster Settings

--------BEFORE----------

Cluster Settings

===========================================

4) Administrator -> Networking -> NetworkPolicies -> Create NetworkPolicy

--------BEFORE----------

Create NetworkPolicy

--------AFTER-----------

Pasted Graphic 12

===========================================

5) Developer -> Topology -> Topology Side Bar -> Actions -> Edit Pod Count

--------BEFORE----------

Pasted Graphic 5

--------AFTER-----------

Edit Pod count

===========================================

6) Developer -> Topology -> Topology Sidebar -> Add health checks

--------BEFORE----------

Pasted Graphic 6

--------AFTER-----------

Health checks for O devfile-sample-git

===========================================

7) Developer -> Topology -> Topology Side Bar -> Actions -> Edit update strategy

--------BEFORE----------

Edit update strategy

--------AFTER-----------

Edit update strategy

===========================================

8) Developer -> pipelines -> create pipelines -> click on task to open side bar 

--------BEFORE----------

Pasted Graphic 8

--------AFTER-----------

CT buildah

Workspaces

================================================================

**Unit test coverage report**: 
NA

**Test setup:**
All 8 points added in the screenshot section

**Browser conformance**: 
- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge

### CODE REVIEW

**Comment by jerolimov** [comment]
Thanks for all these screenshots! :+1:

@lokanandaprabhu Can you check if the screenshot are swapped for "Administrator -> Administation -> Cluster Settings -> Configuration"?

It looks better before, and based on the screenshot font size it looks like the before and after were swapped, or?. :smile:

**Comment by spadgett** [comment]
/hold

You want to wrap the `p` elements in a PatternFly `TextContent` component, which will add the bottom margin. cc @sg00dwin

**Comment by sg00dwin** [comment]
> You want to wrap the `p` elements in a PatternFly `TextContent` component, which will add the bottom margin. cc @sg00dwin

Yes, bottom margin for `p` `ul` and `headings` should now be set by wrapping those with the PatternFly `<TextContent>` component
https://www.patternfly.org/v4/components/text#body

We used to have generic element (p ul ...) css rules that set bottom margin. But these were removed to prevent display inconsistencies and to move closer to a "pure" PatternFly structure and styling.

**Comment by lokanandaprabhu** [comment]
> https://www.patternfly.org/v4/components/text#body

Hi @sg00dwin/ @spadgett ,

PF TextContent will not add the default margin-bottom to the text if it is the last child or the only child. If TextContent will have multiple Text components then margin-bottom will be added to all Text component apart from the last child. Similarly if there is only one child then it will not add margin-bottom.

------With a single child-----
image

-----with 2 text component----
image

image

========================================

For the <p> what we are working on, it will always be a single child.

**Comment by sg00dwin** [comment]
> For the paragraph tag what we are working on, it will always be a single child.

@lokanandaprabhu  Ah yes within forms that's likely the case, so `margin-bottom` would need to be applied separately. 

Since there are several locations and likely others to be found. It would probably make more sense to create a single generic class in `_common.scss`, with a comment that it can be re-applied as needed.

```
// Apply to single <p> elements within forms, that do not conform 
to the PatternFly `pf-c-form` structure for spacing.
.co-form--paragraph {
  margin-bottom: (--pf-c-content--MarginBottom);
}
```

**Comment by lokanandaprabhu** [comment]
> > For the paragraph tag what we are working on, it will always be a single child.
> 
> @lokanandaprabhu Ah yes within forms that's likely the case, so `margin-bottom` would need to be applied separately.
> 
> Since there are several locations and likely others to be found. It would probably make more sense to create a single generic class in `_forms.scss`, with a comment that it can be re-applied as needed.
> 
> ```
> // Apply to single <p> elements within forms, that do not conform 
> to the PatternFly `pf-c-form` structure for spacing.
> .co-form--paragraph {
>   margin-bottom: var(--pf-c-content--MarginBottom);
> }
> ```

Hi @sg00dwin ,

We thought about the generic class but team suggested to have individual class instead of generic class since we don't need this styling for all paragraph tags(some are implemented with 0 margin-bottom) and if someone changes this generic class it will affect in all the places. 

cc @jerolimov , any thoughts!!?

**Comment by sg00dwin** [comment]
> Hi @sg00dwin ,
> 
> We thought about the generic class but team suggested to have individual class instead of generic class since we don't need this styling for all paragraph tags(some are implemented with 0 margin-bottom) and if someone changes this generic class it will affect in all the places.

I'm fine with that path.

**Comment by jerolimov** [comment]
Def. agree with the feedback from Sam and Steve to use more PF components in the future, but as you explained there is no "easy" solution to do this. And I like your way that allows us to do this per component later, but for now this is a "safe" way to get our old padding back on pages that already use custom CSS.

**Review by jerolimov — APPROVED** [review]
The pages I have tested looks fine for me. Thanks for this fix :+1:

/lgtm
/approve

**Pull request merged**
