### PR TITLE
 [release-4.13] OCPBUGS-33382: Routes created by devfiles do not always use HTTPS

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
Manual cherry pick for PR - https://github.com/openshift/console/pull/13787

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Tested using cluster bot. Working fine.

/lgtm

https://github.com/openshift/console/assets/102503482/5f9804ce-62be-4b82-b08f-52d4ed5ccd60

/cc @jerolimov @vikram-raj

**Review by vikram-raj — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
