### PR TITLE
Bug 1873427: GuidedTour: remove the confirmation modal while closing out the guide…

### PR DESCRIPTION
**Pull request by sahil143**
**Fixes**: https://issues.redhat.com/browse/ODC-4505

**Analysis / Root cause**: Based on user feedback remove the confirmation modal while closing out the guided tour

**Solution Description**: removed confirmation modal

**Screen shots / Gifs for design review**: 

closemodalremove

**Unit test coverage report**: 
Screenshot 2020-08-28 at 3 27 53 PM

**Test setup:** None

**Browser conformance**: 

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by invincibleJai** [comment]
/lgtm

Works as expected

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Review by jerolimov — APPROVED** [review]
Tested it locally, works as expected.

/lgtm

**Comment by jerolimov** [comment]
@sahil143 You added a hold label? Something still to-do here from your perspective?

**Comment by sahil143** [comment]
> @sahil143 You added a hold label? Something still to-do here from your perspective?

Nothing to do here. I added the hold because the integration tests were failing which are fixed now.

**Review by invincibleJai — APPROVED** [review]

**Pull request merged**
