### PR TITLE
Bug 1925175: fix incorrect quickstart highlight

### PR DESCRIPTION
**Pull request by abhinandan13jan**
# Addresses
https://issues.redhat.com/browse/ODC-5329

# Issue
`Devperspectivenav` doesn't get removed from DOM like the `AdminNav` perspective does when nav is closed.

#Solution
remove `DevPerspectiveNav` from DOM when nav is closed.

# Test Data
Apply the following quickstart through YAML

```
apiVersion: console.openshift.io/v1
kind: ConsoleQuickStart
metadata:
  name: test-highlights
spec:
  description: Description here
  displayName: test highlights
  durationMinutes: 1
  introduction: Introduction here
  tasks:
    - description: |
        Perspective switcher: [link]{{highlight qs-perspective-switcher}}

        ### Admin perspective nav Links:
        - [Home]{{highlight qs-nav-home}}
        - [Operators]{{highlight qs-nav-operators}}
        - [Workloads]{{highlight qs-nav-workloads}}
        - [Serverless]{{highlight qs-nav-serverless}}
        - [Networking]{{highlight qs-nav-networking}}
        - [Storage]{{highlight qs-nav-storage}}
        - [Service catalog]{{highlight qs-nav-servicecatalog}}
        - [Compute]{{highlight qs-nav-compute}}
        - [User maganement]{{highlight qs-nav-usermanagement}}
        - [Administration]{{highlight qs-nav-administration}}

        ### Dev perspective nav Links:
        - [Add]{{highlight qs-nav-add}}
        - [Topology]{{highlight qs-nav-topology}}
        - [Search]{{highlight qs-nav-search}}
        - [Project]{{highlight qs-nav-project}}
        - [Helm]{{highlight qs-nav-helm}}

        ### Common nav Links:
        - [Builds]{{highlight qs-nav-builds}}
        - [Pipelines]{{highlight qs-nav-pipelines}}
        - [Monitoring]{{highlight qs-nav-monitoring}}

        ### Masthead Links:
        - [CloudShell]{{highlight qs-masthead-cloudshell}}
        - [Utility Menu]{{highlight qs-masthead-utilitymenu}}
        - [User Menu]{{highlight qs-masthead-usermenu}}
        - [Applications]{{highlight qs-masthead-applications}}
        - [Import]{{highlight qs-masthead-import}}
        - [Help]{{highlight qs-masthead-help}}
        - [Notifications]{{highlight qs-masthead-notifications}}
      title: test highlight
```

# Screenshots
qs-highlight

# Tests
No tests altered

# Browser conformance
Chrome 88

### CODE REVIEW

**Comment by rottencandy** [comment]
Works fine for the nav items, but seems to show up on perspective switcher.

https://user-images.githubusercontent.com/20013884/106915650-4774f000-672c-11eb-9a0c-533a087b9daf.mp4

**Comment by christianvogt** [comment]
Not a big deal but in the admin perspective, if i highlight a nav item while the nav is collapsed, the animation still appears on the left because the admin nav is still rendered:
image

It's odd that for the admin nav, the highlight is placed off screen but for the perspective switcher it isn't....

**Comment by abhinandan13jan** [comment]
@christianvogt @rottencandy Changedto hide(unmount) the nav which should take care of both the problems above

**Review by jerolimov — APPROVED** [review]
This fixes the issue and opening the Navigation again doesn't flicker or trigger any network requests. This is not perfect but works as expected.

I think we can still improve this in 4.8. My suggestion is that we need to detect if its a menu item and highlight the menu button when the menu is closed.

edit: I created (untriaged) bug https://issues.redhat.com/browse/ODC-5489 for this.

/lgtm

**Comment by christianvogt** [comment]
/lgtm cancel

As mentioned in the slack conversation, hiding the nav results in losing the expansion state of the nav items in admin perspective. Whether this is acceptable or not needs to have approval from UX as this changes the existing behavior that is built into patternfly

**Pull request closed without merging**
