### PR TITLE
CONSOLE-2391: Monitoring: Initial i18n for list & details pages

### PR DESCRIPTION
**Pull request by kyoto**
Covers various elements like headings, button text and navigation links.

Also changes various elements from title case to sentence case.

Future PR(s) will cover
- Metrics page
- Monitoring Dashboards page
- Create / Edit Silence page

[CONSOLE-2391](https://issues.redhat.com/browse/CONSOLE-2391)

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm
/hold for QE / docs / CEE approvals
/assign @yapei @ahardin-rh @sferich888

**Comment by dtaylor113** [comment]
Hi @kyoto, cypress monitor test failing since we changed to "sentance case", section heading is diff, think test needs to be updated.

image

**Comment by spadgett** [comment]
/lgtm cancel
Due to CI failures.

(@yapei This should still be ready for QE review.)

**Comment by yapei** [comment]
tested locally and no issues found

**Comment by kyoto** [comment]
Updated tests

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
