### PR TITLE
Topology: Adjust tooltip delays, use PF style tips

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Fixes https://jira.coreos.com/browse/ODC-1391

image

### CODE REVIEW

**Comment by vikram-raj** [comment]
Tooltip is hidden behind the overview panel 

Screenshot from 2019-08-14 00-17-42

And can we also add the same tooltip for resource badge on the node label?

**Comment by jeff-phillips-18** [comment]
The tooltips do not adjust to be visible always, they are drawn in the SVG container so will remain below the side panel. Adjustments can be made in the future if deemed necessary, but I spoke with UX about this issue (@serenamarie125) and this approach was agreed upon.

I'll let UX also decide if we want this style tooltip on the badge (standard HTML tips on badges throughout the rest of the UI). @serenamarie125 @beanh66

**Comment by serenamarie125** [comment]
This style tooltip is what's used with PF4 charts.  I think changing it for the badge is a larger effort and should be an effort outside of this PR if we decide to do it.

**Comment by beanh66** [comment]
@jeff-phillips-18 I agree we should change to this style for the badge tooltips as well!

**Comment by jeff-phillips-18** [comment]
Issue to address badges tooltips: https://jira.coreos.com/browse/CONSOLE-1688

**Comment by joshuawilson** [comment]
@spadgett I've reviewed this changed, but they extend outside of dev console. Can you please take a look or have someone review it.

**Pull request merged**
