### PR TITLE
Update resource icon colors to Patternfly palette

### PR DESCRIPTION
**Pull request by spadgett**
Colors from @jennyhaines

deployments openshift origin 2018-07-18 19-32-00

search openshift origin 2018-07-18 19-29-42

@openshift/team-ux-review @rhamilto @sg00dwin

### CODE REVIEW

**Comment by spadgett** [comment]
/hold
for feedback

**Comment by robszumski** [comment]
These look great!

**Comment by tlwu2013** [comment]
Thanks for quickly putting this together @spadgett 👍👍 

Hey @jennyhaines,
Just one nit: I feel the color between **Deployment** and **Pod** seems to be a bit close:
screen shot 2018-07-18 at 5 34 03 pm

(I thought it'll be nice if we can make the color of "Pod" a bit lighter, but then I realized if directly using *pf-cyan-300* then it wouldn't meet the color contrast... so I am not sure what to do about this.)

Do you have any suggestions if we can pick another one for pod?  Thanks!

**Comment by serenamarie125** [comment]
Hey all - I'm back from PTO.  Jenny is now on maternity.  I've included the badge palette which I received from Jenny.  The color differentiation looks much different in her palette than your screenshot. 

resource type badge colors-updated copy

I'd suggest the following:
Pods - use pf-light-blue-400 #00b9e4 (which was used for containers)
Containers/CRDs -  use pf-gold-500 #b58100 (which isn't currently being used)
take the pf-cyan-400 #007a87 and have it reserved for other k8s resources

What do you think @tlwu2013 ?

**Comment by spadgett** [comment]
Just a quick note that this is the same palette I was working from and should match the screenshot.

I can definitely try the suggestions.

**Comment by serenamarie125** [comment]
@spadgett yes, saw that your values matched her specs.  it must look different visually because it's surrounded by white rather than next to the other colors 😄 Thanks for trying out the suggestion!

**Comment by spadgett** [comment]
> Containers/CRDs - use pf-gold-500 #b58100 (which isn't currently being used)
> take the pf-cyan-400 #007a87 and have it reserved for other k8s resources

Currently there's just one bucket of "other resources." I'm not sure we can tell the difference between a custom resource and another k8s resource we just don't have a rule for.

**Comment by spadgett** [comment]
With @serenamarie125's suggested changes:

screen shot 2018-07-19 at 11 19 23 am

**Comment by spadgett** [comment]
One thing about changing the container color: I liked that Replica Set -> Pod -> Container used progressively lighter shades of blue since they're all related and matches the hierarchy.

**Comment by rhamilto** [comment]
My $0.02:  the new colors are not very appealing when presented in the dropdown, and the benefit of using different colors to differentiate resource types is lost because the colors are so similar.

**Comment by spadgett** [comment]
For comparison, here are the original, unchanged colors before this PR:

screen shot 2018-07-19 at 11 45 15 am

**Comment by serenamarie125** [comment]
@spadgett let's connect on this later today when we meet

**Comment by robszumski** [comment]
Our guiding principal for these was to make sure certain combos that are frequently used together don't share a color but ignore the larger issue because we just have too few colors and so many resources.

Example important combos:
- Deployment & Pod
- Role & Role Binding
- Pod & Container
- Ingress & Service
- Node & Pod
- Namespace & basically anything since it shows on most list pages

**Comment by serenamarie125** [comment]
@robszumski that's really helpful information!  We are trying to use the PF color palette, one of the issues there is that we only have so many colors which work with white text, and some of them are honestly a bit too dark IMO.  We'll take another stab at combinations for monday.

**Comment by tlwu2013** [comment]
@serenamarie125 @robszumski cc @jennyhaines
>Our guiding principal for these was to make sure certain combos that are frequently used together don't share a color but ignore the larger issue because we just have too few colors and so many resources.

Some context and history here:
This guidling principal is well communited to Jenny and we collaborately iterated a bit together to come up and agree on the color palette (exactly the one as Serena posted above). 
We basically agreed on generally mapping the color as Tectonic console to make sure the color palette can be well spreading across color hues for better differentiation. And one additional thing we've put into consideration is we'd like to avoid using **pf-blue-400** as badge color since that is a color of text link. It'll be a bit weird to see the badge and the text link using the same color.

I actually like Jenny's latest palette **a lot**! That's why I asked a favor from @spadgett to come up a test build so that we can really see things going live for trying out the feasibility. 
But just wondering if we can push an extra mile for improving the differentiation between **Pod** and **Deployment** badge color. If we can't, then it's fine for me too. That's why I refer it as a **nit**.

**Comment by rhamilto** [comment]
jenkins rebuild

**Pull request merged**
