### PR TITLE
Updates and fixes for pipelines-plugin cypress tests

### PR DESCRIPTION
**Pull request by jrichter1**
- update outdated tests
 - fix the broken cases
 - improve stability of some common test functions

### CODE REVIEW

**Comment by jrichter1** [comment]
@christianvogt could you slap your approval on this?

There is a tiny change in the root directory...

**Comment by christianvogt** [comment]
/approve

@jrichter1 you need a valid bugzilla or appropriate labels

**Comment by sanketpathak** [comment]
This PR only affects our e2e tests.
/label px-approved
/label docs-approved
/label qe-approved

**Pull request merged**
