### PR TITLE
fix(pipeline-bars): Cancelled tasks

### PR DESCRIPTION
**Pull request by abhinandan13jan**
Addresses https://jira.coreos.com/browse/ODC-1516
-------------------------------------------------------------------
Screenshot from 2019-08-30 18-13-57
Screenshot from 2019-08-30 18-14-16

### CODE REVIEW

**Comment by andrewballantyne** [comment]
I am not sure this covers all the cases. It appears you have removed the pending values @abhinandan13jan ...

pipeline-starting

I'll keep looking at this chunk of code to see if I can figure out a better logic path.

**Comment by abhinandan13jan** [comment]
@andrewballantyne I updated without changing the logic. I just missed the `plus` in line 251 which was required as the statement was moved down. Neway, thanks for the suggestion, can you please try again.

**Comment by andrewballantyne** [comment]
> @andrewballantyne I updated without changing the logic. I just missed the `plus` in line 251 which was required as the statement was moved down. Neway, thanks for the suggestion, this really helps. can you please try again?

Issue appears fixed. Thanks for the update.

We should definitely look at writing tests for this function; to that extent I logged https://jira.coreos.com/browse/ODC-1748 to avoid holding up your PR.

**Pull request merged**
