### PR TITLE
[release-4.6] Bug 1915013: Fix pipeline visualization issue when taskspecs is used

### PR DESCRIPTION
**Pull request by karthikjeeyar**
This a manual cherry-pick of https://github.com/openshift/console/pull/7729

Verification setup:
1. Click Import Yaml  in top-right corner
2. Paste the following this pipeline [yaml](https://github.com/karthikjeeyar/pipelines/blob/main/taskspec.yaml#L1-L32)

cc: @andrewballantyne @vikram-raj

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
verified it on 4.6 cluster and it works as expected.

/lgtm

**Review by andrewballantyne — APPROVED** [review]
/lgtm

**Comment by knobunc** [comment]
[As patch-manager] Pulling the cherry-pick-approval since the PR didn't make the merge window... sorry.  Please resolve the CI problems so it can make next week's window.

**Comment by andrewballantyne** [comment]
Understood, it was https://github.com/openshift/console/pull/8025 that caused the issue that prevented this from merging.

**Pull request merged**
