### PR TITLE
updates text description for Event sinks

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes**: 
https://issues.redhat.com/browse/ODC-6523

**Solution Description**: 

updates text description for Event sinks based on the provided text

**Screen shots / Gifs for design review**: 

- Event sink added in add flow

image

- Event sink support in Catalog

image

- Developer catalog popover on type

image

- Create flow event sink with dynamic form/YAML view

image

- Topology: Event sink side panel

image

- Event Source: creation form

image

- Topology: Event source side panel

image

Test setup:

- Install Serverless operator and create CR for `knativeServing/knativeEventing`
- Install Camel K operator
- Create a Channel
- Create Event sink from Add flow

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by sahil143** [comment]
/cc @serenamarie125 @nainaz 

Please take a look at the updated text.

**Comment by nainaz** [comment]
Can we add Event Source above Event Sink or these are alphabetized?
Other than that it looks good. 
Thank you !

**Review by serenamarie125 — CHANGES_REQUESTED** [review]
Based on request from Naina, please update the order of items in the Eventing card in the Add page:
(1) Event Source (2) Broker (3) Channel (4) Event Sink

**Comment by invincibleJai** [comment]
> Configure using the YAML and form views

Have updated this as per suggestion

image

**Comment by nainaz** [comment]
Looks good. 
Thank you !!
good catch @serenamarie125 :)

**Review by sahil143 — APPROVED** [review]
/lgtm
/label qe-approved

**Pull request merged**
