### PR TITLE
Show community operators, warn on details

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Addresses original issue in https://jira.coreos.com/browse/CONSOLE-1255

fyi @tlwu2013 @serenamarie125 @alimobrem

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
image

**Comment by jeff-phillips-18** [comment]
Added a badge for community operators, sorted the list of categories

image

@beanh66 @tlwu2013 @serenamarie125 @alimobrem

**Comment by tlwu2013** [comment]
We've iterated a couple of logo/badge for community operators with Mary, Ali, and Rob, and folks felt that simply using this kind of tag is the most straightforward approach even though it takes more space. The tag is equivalent to the badge concept we had in the early mocks, and we don't have a double badge use case in OperatorHub, so should be fine in this case. I'll let others chime in as well.

**Comment by serenamarie125** [comment]
thanks for the info @tlwu2013, glad to hear these things were taken into consideration

**Comment by beanh66** [comment]
@serenamarie125 the icon we had for community was difficult to make out at that small size. I agree, if we need additional badges in the future, we can revisit the icon idea or maybe stack the text labels in some way. @jeff-phillips-18 I assume the categorization will be handled in a separate PR?

**Comment by jeff-phillips-18** [comment]
Yeah, not sure what is to be done with the categorization. They are sorted now but the sheer number of categories is dependent on the operators. If the operators standardize their categories the list here will reflect that.

**Comment by jeff-phillips-18** [comment]
@benjaminapetersen Any chance this can be reviewed today?

**Comment by robszumski** [comment]
Categories were fixed and unfied across the board in https://github.com/operator-framework/community-operators/pull/51

Maturity levels will be fixed and unified in https://github.com/operator-framework/community-operators/pull/63

**Comment by benjaminapetersen** [comment]
filed as a bug, so exception not needed.

/lgtm

**Comment by jeff-phillips-18** [comment]
@benjaminapetersen Rebased, needs new LGTM.

**Comment by spadgett** [comment]
flake https://jira.coreos.com/browse/CONSOLE-1293

/retest

**Comment by spadgett** [comment]
performance test flake

/retest

**Comment by spadgett** [comment]
deploy image test flake

/retest

**Comment by spadgett** [comment]
olm test flake

/retest

**Comment by spadgett** [comment]
> NoSuchElementError: No element found using locator: by.buttonText("Install")

/retest

**Comment by jeff-phillips-18** [comment]
Last failure looked real. Looking into it (if I can get my cluster to spin up).

**Comment by jeff-phillips-18** [comment]
@spadgett Updated tests

**Pull request merged**
