### PR TITLE
support visualisation of internal deployment in topology view and sidepanel for event sink

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes**: 
https://issues.redhat.com/browse/ODC-6519

**Solution Description**: 

updates text description for Event sinks based on the provided text

**Screen shots / Gifs for design review**: 

eventSinkDeployment

Test setup:

- Install Serverless operator and create CR for `knativeServing/knativeEventing`
- Install Camel K operator
- Create a Channel

-  kn channel to kamelet sink

```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: log-sink-binding
spec:
  source:
    ref:
      kind: Channel
      apiVersion: messaging.knative.dev/v1
      name: channel
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
```  

- URI to kamelet sink

```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: log-sink-binding-uri
spec:
  source:
    uri: "http://abc.com"
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
```  

- KameletBinding with source and sink both as kamelet

```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: chuck-to-log-sink
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: chuck-norris-source
  sink:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1alpha1
      name: log-sink
```  

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by invincibleJai** [comment]
/label docs-approved
/label px-approved

propagating above labels based on ACKs on epic

**Comment by sahil143** [comment]
/label qe-approved

verified on cluster bot

**Pull request merged**
