### PR TITLE
[release-4.11] OCPBUGS-6492: Add RBAC check on Create a Project link in all-namespaces pages

### PR DESCRIPTION
**Pull request by vikram-raj**
Manual cherry-pick of https://github.com/openshift/console/pull/12489

/cc @jerolimov

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Tested this on a cluster bot and it work as expected :+1:

https://user-images.githubusercontent.com/139310/216770178-2dd71811-c754-458e-b8b0-7ceaf2576507.mp4

/label backport-risk-assessed
/lgtm
/approve

**Comment by vikram-raj** [comment]
manual cherry-pick PR https://github.com/openshift/console/pull/12566

**Pull request merged**
