### PR TITLE
Bug 1973572: Hardcode strings in Home->Overview page

### PR DESCRIPTION
**Pull request by kdoberst**
This addresses [Bug 1973572](https://bugzilla.redhat.com/show_bug.cgi?id=1973572)

The following add changes for the following:
- Control Plane
- Configure
- Cluster
- Not available

to ensure that they are provided the translated value when language is set to simple Chinese.

Note: These changes have all been made in 4.8. This commit to to bring those changes into 4.7.

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by kdoberst** [comment]
@spadgett Sorry Sam - I had remove some comments that caused the localization files to not be build correctly and the test failed.  I added them back in and now all the tests pass.  Can you give this another look? (See frontend/packages/console-app/src/plugin.tsx)

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
