### PR TITLE
Bug 1804049: Alertmanager - Prevent duplicate/same router label keys on Receiver forms

### PR DESCRIPTION
**Pull request by dtaylor113**
Added validation to check for duplicate routing label keys/names.

image

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
/approve

will lgtm if the tests pass.

**Comment by dtaylor113** [comment]
This is another flake around `.clear()` & `.sendKeys()`.  Here we see `clear()` not working...happening asynchronously?
image
I see `clear()` used elsewhere, not sure why it's usage in the [replaceInput()](https://github.com/openshift/console/blob/master/frontend/integration-tests/tests/alertmanager.scenario.ts#L17) is causing this issue.  At one point I removed `replaceInput` and used the straight:
```
await foobar.clear()
await foobar.sendKeys()
```
But still saw the issue.

**Pull request merged**
