### PR TITLE
Bug 1967979:  Masthead Dropdowns options are not accessible via the keyboard

### PR DESCRIPTION
**Pull request by cyril-ui-developer**
/assign @rhamilto 
cc: @spadgett 

### Before:
Screen Shot 2021-07-02 at 2 07 43 PM

### After:
Screen Shot 2021-07-02 at 2 08 49 PM

### CODE REVIEW

**Comment by rhamilto** [comment]
@cyril-ui-developer apologies for missing the review assignment.  The PR looks good, but now it needs a rebase.

**Comment by cyril-ui-developer** [comment]
> @cyril-ui-developer apologies for missing the review assignment. The PR looks good, but now it needs a rebase.

@rhamilto No worries :)
Rebased.

**Review by rhamilto — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
/bugzilla refresh

@cyril-ui-developer Needs rebase :/

**Comment by rhamilto** [comment]
Looks like you have a linter error, @cyril-ui-developer

**Comment by cyril-ui-developer** [comment]
> Looks like you have a linter error, @cyril-ui-developer

@rhamilto

**Comment by cyril-ui-developer** [comment]
> > Looks like you have a linter error, @cyril-ui-developer
> 
> @rhamilto Thanks

Lint ran successfully in local.

**Review by rhamilto — APPROVED** [review]
/lgtm

**Pull request merged**
