### PR TITLE
Bug 1952585: Enhance operator modal repo and container links

### PR DESCRIPTION
**Pull request by florkbr**
Updates the operator hub item details modal to use a link widget for the repository  and copyclipboard for container.

image

https://issues.redhat.com/projects/CONSOLE/issues/CONSOLE-2034?filter=allissues

### CODE REVIEW

**Comment by florkbr** [comment]
@TheRealJon @spadgett FYI I worked with Peter on the design team on this issue. We have decided to go forward with using the existing pattern for copying the container image (green plus on hover and click to copy). Eventually we will want to switch over to the PatternFly CopyClipboard component possibly. See Jira issue for details.

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Review by spadgett — APPROVED** [review]
/lgtm
/hold so we can create a Bugzilla. let's track this as a bug.

**Pull request merged**
