### PR TITLE
CONSOLE-3653: Adds French Localization

### PR DESCRIPTION
**Pull request by fallmo**
Adding French Localization to Console by:
Creating `fr` locale folders with JSON translation files for each package. 
Including French in `supportedLocales` map

@spadgett @jhadvig

### CODE REVIEW

**Comment by spadgett** [comment]
Fantastic, thanks for the PR!

/ok-to-test
/cc @jhadvig @jcaianirh 

@alimobrem FYI

**Comment by jhadvig** [comment]
There is an bug filed for this PR - https://issues.redhat.com/browse/OCPBUGS-16734

**Comment by fallmo** [comment]
> There is an bug filed for this PR - https://issues.redhat.com/browse/OCPBUGS-16734

Good catch, addressed it in the latest commit.

**Comment by XiyunZhao** [comment]
Hi @fallmo, there are other three issues were found for this PR, please help to take a look
[OCPBUGS-16759](https://issues.redhat.com/browse/OCPBUGS-16759), [OCPBUGS-16761](https://issues.redhat.com/browse/OCPBUGS-16761), [OCPBUGS-16763](https://issues.redhat.com/browse/OCPBUGS-16763)

**Comment by fallmo** [comment]
> Hi @fallmo, there are other three issues were found for this PR, please help to take a look [OCPBUGS-16759](https://issues.redhat.com/browse/OCPBUGS-16759), [OCPBUGS-16761](https://issues.redhat.com/browse/OCPBUGS-16761), [OCPBUGS-16763](https://issues.redhat.com/browse/OCPBUGS-16763)

Addressed in latest commits.

**Comment by XiyunZhao** [comment]
sorry for the delay, all bug has been verified on pre-merge testing, all passed, and no other new issue was found
/label qe-approved

**Comment by fallmo** [comment]
> sorry for the delay, all bug has been verified on pre-merge testing, all passed, and no other new issue was found /label qe-approved

Great news!

**Comment by ymoisan** [comment]
FR in OpenShift would be *really* nice :-)

**Comment by fallmo** [comment]
> FR in OpenShift would be _really_ nice :-)

Agreed!

**Comment by fallmo** [comment]
@jhadvig hey there, any new bugs show up? What are the next steps?

**Comment by yanpzhan** [comment]
@jhadvig this pr is still open, will it be include in 4.15?

**Comment by jhadvig** [comment]
Unfortunately we need to close this PR since there is no business requirement for this feature anymore.

**Pull request closed without merging**
