### PR TITLE
Add error boundary in edit-flows

### PR DESCRIPTION
**Pull request by divyanshiGupta**
**Fixes:** https://issues.redhat.com/browse/ODC-6005

**Screen Recording:**

https://user-images.githubusercontent.com/20724543/122060888-9bdf5900-ce0b-11eb-93e2-b90e733f1cda.mov

/kind bug

### CODE REVIEW

**Review by andrewballantyne — APPROVED** [review]
Love the simplicity of this fix.

**Comment by invincibleJai** [comment]
/lgtm

thanks , verified the changes works as expected

**Comment by jerolimov** [comment]
/retitle Bug 2002273: Add error boundary in edit-flows

**Pull request merged**
