### PR TITLE
Bug 1812418: Handle the Grafana `$__interval` var

### PR DESCRIPTION
**Pull request by spadgett**
/assign @benjaminapetersen 
/cc @kyoto

### CODE REVIEW

**Comment by spadgett** [comment]
Using `timespan / samples` creates some gaps in the graphs. We'll need adjust the interval we calculate.

**Comment by kyoto** [comment]
Thanks for looking into this @spadgett!

Generally, the approach LGTM.

I think the problem with gaps in the graph is happening because the queries use `$__interval` along with an `irate` function, so at least 2 data points must be found in the `$__interval` in order to calculate a rate.

The default `30m` timespan and `30` samples results in `__interval` = `60s`, so if we scrape about every `30s`, we may get 1, 2 or 3 data points during a `60s` interval.

Maybe the easiest solution is to set a minimum value for the interval? `2m` may be enough, but perhaps `5m` to be safer?

**Comment by spadgett** [comment]
/hold cancel

Thanks @kyoto! Updated

**Pull request merged**
