### PR TITLE
Bug 1790711: Remove nightly-4.1 channel from console

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @spadgett 

@wking fyi

### CODE REVIEW

**Comment by wking** [comment]
> expected Bugzilla bug 1790711 to depend on a bug...

This is asking for a 4.4 -> 4.3 -> 4.2 -> 4.1 bug chain.  This may be a low-enough grade issue to not be worth a 4.1 fix, but we certainly want to pull nightly entries out of the more master-ward branches, or file bugs so QE can sign off on their not being there (I haven't checked those branches).  If this is just a 4.1 issue, you can WONTFIX it or talk a patch manager into granting an exception from the usual Bugzilla flow.

**Comment by spadgett** [comment]
This is only a 4.1.z issue. The other branches look OK.

**Pull request merged**
