### PR TITLE
OCPBUGS-2455: Pods and PDBs list page just reports 'Not found' when no Pod/PDB

### PR DESCRIPTION
**Pull request by cyril-ui-developer**
### Before
Screen Shot 2022-10-17 at 12 49 51 PM
Screen Shot 2022-10-17 at 12 50 01 PM

### After
Screen Shot 2022-10-17 at 12 50 17 PM
Screen Shot 2022-10-17 at 12 50 34 PM

### CODE REVIEW

**Review by rhamilto — APPROVED** [review]
/lgtm

**Review by sg00dwin — APPROVED** [review]

**Pull request merged**
