### PR TITLE
[DO NOT MERGE] Debug secret tests

### PR DESCRIPTION
**Pull request by jhadvig**
PR for debugging purposes, related to failing secret scenario tests

@spadgett FYI

### CODE REVIEW

**Comment by spadgett** [comment]
/hold
to avoid accidental merge

**Comment by spadgett** [comment]
@jhadvig I have a feeling the secrets tests are flaking due to

https://bugzilla.redhat.com/show_bug.cgi?id=1697225

**Comment by jhadvig** [comment]
@spadgett most probably yes. Trying to come up with the best solution on how to preserve the state still.

**Comment by spadgett** [comment]
/close

This looks like it was a side effect of the API discovery problem.

**Pull request closed without merging**
