### PR TITLE
Add Unit tests for QuotaGaugeCharts and QuotaScopesList

### PR DESCRIPTION
**Pull request by xiaocwan**
Add a unit test for checking QuotaGaugeCharts and QuotaScopesList .
@spadgett Could you help to review plz? Thanks!

### CODE REVIEW

**Comment by spadgett** [comment]
These charts are changing in #1783. We should write the tests for the new charts.

/hold

**Comment by xiaocwan** [comment]
#1783 is merged. 
/hold cancel

**Comment by xiaocwan** [comment]
Hi @spadgett 
It's been rebased on latest code now, could you please have a review? Thanks!

**Comment by xiaocwan** [comment]
@jhadvig @jeff-phillips-18  Could you help to approve please? Thanks!

**Comment by spadgett** [comment]
/lgtm cancel

looks like the tests need to be updated for current master

**Pull request closed without merging**
