### PR TITLE
OCPBUGS-9405: [OSD] There is no error message shown on node label edi…

### PR DESCRIPTION
**Pull request by tvu20**
…t modal

Fixes https://issues.redhat.com/browse/OCPBUGS-9405

Error message renders as part of "Edit Labels" modal

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm

**Comment by yanpzhan** [comment]
@tvu20 Hi I launch a cluster against the pr, and edit node label, when the label is not valid, clicking save button will close the modal without error info. Checked on 4.14 cluster, the issue is also reproduced. Seems the code is not working now. Pls refer to the screenshot.
[Screencast from 07-06-2023 08:44:54 PM.webm](https://github.com/openshift/console/assets/7313189/c3ecff9b-c793-4a2a-81d3-42d67b5b27f8)

**Comment by tvu20** [comment]
@yanpzhan When the label contains invalid characters, the modal displays an invalid marker and does not add it to the list of labels. Therefore, there is no error returned from the backend when saving with an input with invalid characters. One solution would be to disable the save button when there are invalid characters present - this would change the functionality of the modal itself.

**Comment by yanpzhan** [comment]
@tvu20 since the reaction when edit node label on current 4.12 nightly cluster looks the same on the cluster launched against the pr, I'm wondering what's the code's usage from the pr? How could I test the change?

**Comment by tvu20** [comment]
@yanpzhan You can test the change by inputting a new label with a value more then 63 characters, e.g. testnew=1111111111111111112222222222222222333333333333333344444444444444444555555555555555556666666666666667777777777777777777

**Comment by yanpzhan** [comment]
@tvu20 Thanks! After tested again, there is the erorr message shown on node label edit modal.
Screenshot from 2023-07-10 13-50-53

**Pull request merged**
