### PR TITLE
Bug 1831002: Fix for pod text / icon overlap in topology

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**Fixes**: 
https://issues.redhat.com/browse/ODC-3036

**Analysis / Root cause**: 
Pod text was too large for where it was positioned within the Pod rings. Attempt was made to setup a subtitle component for the longer text but that component is not used in react-charts when positioned in the center.

**Solution Description**: 
Update the styling of the created tspan's for the pod text. Position the text in order to make longer text be in the middle of the pod ring to give more horizontal space for the text.

**Screen shots / Gifs for design review**:
Before:
image
image

After:
image

**Browser conformance**: 
- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge

cc @openshift/team-devconsole-ux @serenamarie125 @beaumorley 

/kind bug

### CODE REVIEW

**Comment by serenamarie125** [comment]
This looks great @jeff-phillips-18!  FYI I'm going to do some investigation to see what the frequency is for having > 9 (2 digits) and > 99 (3 digits) pods.  If these are high freq use cases, i'll create a separate bug to track.

**Comment by serenamarie125** [comment]
> @serenamarie125 On the overview panel scaling to 3 is small as wrt ring size. Is it fine?

Hard to see out of context - if the ring size is larger on the overview panel, which it seems to be, i'd suggest keeping the text size the same as it was previous to this PR.

**Comment by jeff-phillips-18** [comment]
Updated:

image

**Comment by nemesis09** [comment]
verified locally
build: 4.5.0-0.ci-2020-05-07-094159
/lgtm

**Pull request merged**
