### PR TITLE
ODC-7421: Show vulnerability column in the pipelinerun list page

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Fixes:
Fixes [ODC-7421](https://issues.redhat.com/browse/ODC-7421)

Adds a vulnerability column and a signed indicator column to the pipeline run list page.
Adds a `View SBOM` action on pipeline runs.
Adds a `Vulnerabilities` section to the pipeline run details page.

image

image

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
Updated signed badge location per @MariaLeonova, screen shot updated above.

**Review by karthikjeeyar — APPROVED** [review]
/lgtm

**Comment by karthikjeeyar** [comment]
cc: @vdemeester

**Review by vikram-raj — COMMENTED** [review]
verified it

/approve

**Comment by vikram-raj** [comment]
Propagate from the epic

/label docs-approved
/label px-approved

**Comment by beaumorley** [comment]
LGTM thank you

**Comment by sanketpathak** [comment]
Verified with admin and non-admin user
Screenshot 2023-11-16 at 2 51 52 PM

Screenshot 2023-11-16 at 2 54 35 PM

Tests will be added as separate pr
/label qe-approved

**Pull request merged**
