### PR TITLE
OU-231: Add jgbernalp and zhuje to OWNERS for monitoring

### PR DESCRIPTION
**Pull request by kyoto**

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by kyoto** [comment]
This is just changing the OWNERS file.

/label px-approved
/label docs-approved

**Comment by kyoto** [comment]
Adding `/qe-approved` since this is just changing the OWNERS file

FYI @juzhao 

/qe-approved

**Pull request merged**
