### PR TITLE
Bug 1779208: Capacity breakdown card queries - changed average to absolute values

### PR DESCRIPTION
**Pull request by anmolsachan**
Signed-off-by: Anmol Sachan <anmol13694@gmail.com>

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1779208

Currently, the storage usage in the Capacity breakdown card shown is the hourly average of the values. It should be an absolute value. 

Current : 
Screenshot from 2019-12-03 17-40-46

Proposed : 
Screenshot from 2019-12-03 17-40-55

### CODE REVIEW

**Comment by afreen23** [comment]
@anmolsachan please add the BZ for this.
Thanks for the PR

**Comment by anmolsachan** [comment]
> @anmolsachan please add the BZ for this.
> Thanks for the PR

@afreen23 Thanks. Also tested the sorting.
Screenshot from 2019-12-04 13-46-53

**Comment by anmolsachan** [comment]
@afreen23 @rawagner Please review

**Comment by a2batic** [comment]
/lgtm
/approve
Thanks @anmolsachan

**Pull request merged**
