### PR TITLE
Added service token to log-exploration-api request header

### PR DESCRIPTION
**Pull request by apeksha-khandelwal**
The following changes have been made for the Jira ticket: [1455](https://issues.redhat.com/browse/LOG-1455).
The code adds a service token from the cluster in the header when requesting logs from Log-exploration-API

Note: This PR was built on PR #8944 to view logs from log-exploration API on the console and thus includes that code.

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
@apeksha-khandelwal It seems like the build is failing. Can you run `./build.sh` and see if there are any errors and fix them?

**Comment by apeksha-khandelwal** [comment]
Squashed all 30 commits into one and resolved the build errors.

**Comment by divyanshiGupta** [comment]
@invincibleJai  @vikram-raj This PR adds alert logs in alert details page. It will be great to have some reviews from you guys as you have closely worked on dev-console monitoring. PR #8944 has more details on what is to be accomplished PTAL at it.

/cc: @invincibleJai 
/cc: @vikram-raj

**Pull request closed without merging**
