### PR TITLE
Kubevirt - Affinity modal

### PR DESCRIPTION
**Pull request by glekner**

### CODE REVIEW

**Comment by glekner** [comment]
Ok guys, this turned out to be big.

- Added `AffinityModal, AffinityEdit, AffinityTable`

- [Using Multiple Select for multiple values in a single `matchExpression | matchField`](https://github.com/openshift/console/pull/4884/files#diff-140a4e185171a66a07cfcce8cc90e1d1R60)

- At the end I [created helpers](https://github.com/openshift/console/pull/4884/files#diff-140a4e185171a66a07cfcce8cc90e1d1R60) instead of a class because I only needed to convert the data to rows and from rows back to data

- Updated `useNodeQualifier` to [accept a predicate](https://github.com/openshift/console/pull/4884/files#diff-2570419cb975b7b70da9ed46de129f0aR11) since we have multiple operators now ('In, Exists'...)

- Updated `useNodeQualifier` to [accept node fields](https://github.com/openshift/console/pull/4884/files#diff-2570419cb975b7b70da9ed46de129f0aR11) instead of just its labels

- Updated Vm Details and Template Details to match the latest design

Lets get this in before freeze ;)
can you review @suomiy @yaacov?

**Comment by yaacov** [comment]
/lgtm
greate !

**Pull request merged**
