### PR TITLE
CONSOLE-3081: Integrate dark theme - fix(borders): convert #ccc, #ddd, $pf-color-black-300, $color-row-filter-border to var(--pf-global--BorderColor--100)

### PR DESCRIPTION
**Pull request by mattnolting**
For: https://issues.redhat.com/browse/CONSOLE-3081
fix(borders): convert #ccc, #ddd, $pf-color-black-300, $color-row-filter-border to var(--pf-global--BorderColor--100)
This pr converts `#ddd`, `#ccc`, `$pf-color-black-300`, `$color-row-filter-border`

Color shifts are described here: https://codepen.io/bobcatTaco/pen/NWwVYzq#ccc-ddd-black-300

Screen Shot 2022-03-08 at 2 34 10 PM

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/approve
/assign @sg00dwin 
/ok-to-test

**Comment by jcaianirh** [comment]
Propagate from epic:
/label docs-approved
/label px-approved

**Review by vikram-raj — COMMENTED** [review]
Verified the changes. 

/lgtm
/label qe-approved

**Comment by yanpzhan** [comment]
@schituku Could you help to test the pr from QE side?

**Comment by mattnolting** [comment]
> @mattnolting , var(--pf-global--BorderColor—100) doesn't work here. See screenshot. cc: @sg00dwin

@rhamilto Is this still valid?

**Comment by sg00dwin** [comment]
> > @mattnolting , var(--pf-global--BorderColor—100) doesn't work here. See screenshot. cc: @sg00dwin
> 
> @rhamilto Is this still valid?

`var(--pf-global--BorderColor—100)` should be `var(--pf-global--BorderColor--100)` Incorrect in several places.

**Pull request merged**
