### PR TITLE
Integration Tests: Wait for etcd Create New button before trying to click

### PR DESCRIPTION
**Pull request by spadgett**
We're trying to click the button before it appears on the page. Hopefully this fixes it.

/cc @alecmerdler

### CODE REVIEW

**Comment by spadgett** [comment]
OK, looks like this is a problem other places, too:

```
1) Interacting with the Prometheus OCS : displays YAML editor for creating a new `Prometheus` instance
   NoSuchElementError: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, .dropdown)
```

**Comment by alecmerdler** [comment]
@spadgett Thanks for addressing this, I couldn't reproduce locally but it seems to be caused because it's taking longer for the Operator deployment's pods to become ready than it was before, so the button is disabled until they are ready.

**Comment by spadgett** [comment]
Sure. I'm still seeing this locally sometimes... We might need to give a generous timeout if we're waiting for pod readiness.

**Comment by spadgett** [comment]
> I'm still seeing this locally sometimes...

Looks like this was because we were out of capacity on the cluster, so the pods weren't starting.

**Pull request merged**
