### PR TITLE
Bug 1919406: Update OperatorHub 'Provider type' filter to 'Source'

### PR DESCRIPTION
**Pull request by TheRealJon**
As per UX feedback, the 'Provider type' filter on the OperatorHub page needed to be updated to 'Source'. Update the filter name accordingly and rename underlying functions and variables in the code to reflect association to CatalogSource.

image
image

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

👍

**Comment by spadgett** [comment]
/hold looks like we need a test update

> AssertionError: Timed out retrying after 30000ms: Expected to find element: `[data-test="source-red-hat"]`, but never found it.

**Comment by TheRealJon** [comment]
@spadgett updated the cypress test

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by TheRealJon** [comment]
/hold

Until we figure out CI failures

**Pull request merged**
