### PR TITLE
Add descriptor reference doc

### PR DESCRIPTION
**Pull request by tlwu2013**
Initial doc for descriptor reference with code snippet and example screenshots.

### CODE REVIEW

**Comment by tlwu2013** [comment]
cc @alimobrem   This is the markdown version of the descriptor reference. 
Do we need to include those work-in-progress views in the reference?

**Comment by tlwu2013** [comment]
Hey @spadgett and @alecmerdler , can you guys help review if this doc is good to merge?  
Much appreciated!

**Comment by spadgett** [comment]
/approve

docs only

**Comment by spadgett** [comment]
Thanks @tlwu2013 !

**Pull request merged**
