### PR TITLE
[WIP] Implemented cypress-plugin-retries

### PR DESCRIPTION
**Pull request by dtaylor113**
https://github.com/Bkucera/cypress-plugin-retries

### CODE REVIEW

**Comment by spadgett** [comment]
Lots of build errors with this change like

```
ERROR in /go/src/github.com/openshift/console/frontend/packages/ceph-storage-plugin/integration-tests/tests/1-install/installFlow.scenario.ts
(52,5): No overload matches this call.
  Overload 1 of 6, '(title: string, config: TestConfigOverrides, fn?: Func): Test', gave the following error.
    Type '() => Promise<void>' has no properties in common with type 'TestConfigOverrides'.
  Overload 2 of 6, '(title: string, config: TestConfigOverrides, fn?: AsyncFunc): Test', gave the following error.
    Type '() => Promise<void>' has no properties in common with type 'TestConfigOverrides'.
```

**Comment by dtaylor113** [comment]
> Lots of build errors with this change like
> 
> ```
> ERROR in /go/src/github.com/openshift/console/frontend/packages/ceph-storage-plugin/integration-tests/tests/1-install/installFlow.scenario.ts
> (52,5): No overload matches this call.
>   Overload 1 of 6, '(title: string, config: TestConfigOverrides, fn?: Func): Test', gave the following error.
>     Type '() => Promise<void>' has no properties in common with type 'TestConfigOverrides'.
> ```

Hi @spadgett, where do you see these errors?

**Pull request closed without merging**
