### PR TITLE
Enable tab into Create button

### PR DESCRIPTION
**Pull request by nicolethoen**
Fixes [CONSOLE-1156](https://jira.coreos.com/browse/CONSOLE-1156)

Apr-02-2019 11-30-41

### CODE REVIEW

**Comment by spadgett** [comment]
Operator Hub tests are currently broken in CI. Skipping.

/skip

**Comment by spadgett** [comment]
console e2e failures fixed by #1375

**Comment by jhadvig** [comment]
```
WebDriverError: chrome not reachable
  (Session info: headless chrome=67.0.3396.62)
  (Driver info: chromedriver=2.38.552522 (437e6fbedfa8762dec75e2c5b3ddb86763dc9dcb),platform=Linux 3.10.0-957.1.3.el7.x86_64 x86_64)
    at Object.checkLegacyResponse (/go/src/github.com/openshift/console/frontend/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/go/src/github.com/openshift/console/frontend/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/go/src/github.com/openshift/console/frontend/node_modules/selenium-webdriver/lib/http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

/retest

**Comment by spadgett** [comment]
This failure is related to the other test errors. Operator Hub seems to crash Chrome in CI :(

cc @jeff-phillips-18 @alecmerdler 

```
Performance test downloads new bundle for operator-hub 3.53s

go run hack/e2e.go -v -test --test_args='--ginkgo.focus=Performance\stest\sdownloads\snew\sbundle\sfor\soperator\-hub$'

WebDriverError: unknown error: session deleted because of page crash
from unknown error: cannot determine loading status
from tab crashed
```

**Pull request merged**
