### PR TITLE
[release-4.8] Bug 1990141: Console overview operators shown upgrading when still waiting on approval

### PR DESCRIPTION
**Pull request by jcaianirh**
This is a manual cherry pick of both:
https://github.com/openshift/console/pull/9264
https://github.com/openshift/console/pull/9475

from 4.9->4.8

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by mfojtik** [comment]
[patch-manager] :rocket: Approved for z-stream by score: 0.20

adding cherry-pick approved

**Pull request merged**
