### PR TITLE
OCPBUGS-32405: Create Serverless form does not create BuildConfig

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-32405

**Analysis / Root cause**: 
When pipeline operator is not installed and Pipeline resource is not created for that particular serverless function then BuildConfig is not created

**Solution Description**: 
Updated to consider build option as BUILDS when pipeline is not checked and if pipeline is checked, build option will be PIPELINES.

**Screen shots / Gifs for design review**: 

----Without pipeline operator installed----
https://github.com/openshift/console/assets/102503482/6391cd11-b582-497a-9ca0-4ed1eab8e3ef

----With pipeline operator installed and without Pipeline resource----

https://github.com/openshift/console/assets/102503482/ad81ee1a-e5ff-42ee-8616-5c661d7407d0

----With pipeline operator installed and with Pipeline resource----

https://github.com/openshift/console/assets/102503482/792e8161-dd1e-469d-999f-12c5712fac1c

----With pipeline operator installed and with Pipeline resource but unchecked add pipeline----

https://github.com/openshift/console/assets/102503482/85dcf4fa-90a4-4d30-a652-754a6b2f155f

---with Samples----
https://github.com/openshift/console/assets/102503482/b49ba0a7-638a-4d2e-b5d5-daace0329e51

**Unit test coverage report**: 
NA

**Test setup:**

    1.Install serverless operator and knative instances
    2. Don't install pipelines operator
    3. Create serverless function, then BuildConfig should be created
    4. Install Pipelines operator but don't create Pipeline resource for particular serverless function and create serverless function, then also BuildConfig should be created
    5. Create Pipeline resource using https://gist.github.com/vikram-raj/386b4eca5193036b0ca29471f6e513a5 and create serverless function, then if you select add pipelines then Pipeline/Repository will be created and if you don't add pipeline, then BuildConfig will be created

     
**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by jerolimov — COMMENTED** [review]
@lokanandaprabhu Thanks for the great bug description will all links to setup it locally!! :+1:

Your change fixes the problem and we can merge it this way.

But on the other side, I think we should align the UI with the "Import from Git" flow and show a "Build" section when the BuildConfig and Pipeline option is available:

image

Wdyt?

**Comment by lokanandaprabhu** [comment]
Hi @jerolimov ,

Sure, we can align the UI with other import flows but can we handle it in separate ticket since this issue is targeting Serverless form not creating BC and it is critical. I can create separate ticket for the same.

**Review by vikram-raj — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
