### PR TITLE
ODC-7672: Migrate TelemetryUserPreferenceDropdown to PF5

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7672

**Screen shots / Gifs for design review**: 

before:

https://github.com/user-attachments/assets/95d942a7-91d4-4563-8426-6b12cf4b92fd

after:

https://github.com/user-attachments/assets/0bbff5b9-14df-4a9b-b13f-ac23ecb09ab5

**Unit test coverage report**: 

n/a

**Test setup:**

run the bridge with `./bin/bridge --telemetry 'STATE=OPT-IN'` to enable telemetry, then remove the required flags `TELEMETRY_CLUSTER_CONFIGURATION` and `TELEMETRY_ENABLED` in [console-extensions.json](https://github.com/openshift/console/tree/master/frontend/packages/console-telemetry-plugin/console-extensions.json)

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

This pr is 2/2 of [ODC-7672](https://issues.redhat.com//browse/ODC-7672) story as each file is being split into a separate PR.

### CODE REVIEW

**Comment by vikram-raj** [comment]
Clicking anywhere in the window does not close the dropdown option. It should close the dropdown.


https://github.com/user-attachments/assets/a5df0d3d-f05d-44eb-a4c1-e128cc7b7d47

**Comment by logonoff** [comment]
> Clicking anywhere in the window does not close the dropdown option. It should close the dropdown.
> Screen.Recording.2024-08-30.at.3.51.50.PM.mov

amended, thanks for catching :)

**Review by vikram-raj — APPROVED** [review]
/lgtm

**Comment by logonoff** [comment]
Tech debt that is not customer facing, so manually adding labels
/label px-approved
/label docs-approved

**Pull request merged**
