### PR TITLE
Bug 1927797: Add "Pod" in HPA pod donut label

### PR DESCRIPTION
**Pull request by rottencandy**
**Fixes**: 
https://issues.redhat.com/browse/ODC-5396

**Analysis / Root cause**: 
The term 'Pod(s)' should added to the horizontal pod autoscaler pod donut label so it's like the other pod donut labels.

**Screen shots / Gifs for design review**: 
tmp0
tmp1
tmp2
@openshift/team-devconsole-ux 

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by lwrigh — APPROVED** [review]
This update looks good to me!

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
