### PR TITLE
Bug 1894330: update channels list

### PR DESCRIPTION
**Pull request by yapei**
Updated channels list for 4.7

### CODE REVIEW

**Comment by spadgett** [comment]
Hi, @yapei. This should no longer be necessary as we now get the list of channels from the API since #6283, although I see you're updating the fallback. It might be better to just remove the fallback so we don't have to maintain this release-to-release. The ClusterVersion API should have the valid values.

cc @rhamilto

**Comment by rhamilto** [comment]
> Hi, @yapei. This should no longer be necessary as we now get the list of channels from the API since #6283, although I see you're updating the fallback. It might be better to just remove the fallback so we don't have to maintain this release-to-release. The ClusterVersion API should have the valid values.
> 
> cc @rhamilto

Yeah.  We should remove the fallback **and**  there is also [a TODO to not link to the modal if `cv.spec.desired.channels` does not exist for a build](https://github.com/openshift/console/blob/master/frontend/public/components/cluster-settings/cluster-settings.tsx#L144) (e.g., a nightly).  If I remember correctly, @megan-hall had a design task for this.

**Comment by megan-hall** [comment]
@rhamilto yes - I do. I will circle back with you offline and get that taken care of.

**Comment by rhamilto** [comment]
IMO, we should probably close this PR since we don't want to remove the fallback without implementing the pending design changes at the same time as we'll end up with a modal containing no options in the dropdown if we do.

**Comment by rhamilto** [comment]
@megan-hall's design story is https://issues.redhat.com/browse/PD-579

**Comment by yapei** [comment]
Got it, let me close the PR

**Comment by spadgett** [comment]
Let's go ahead and update the fallback for now so it's not wrong, and we can circle back when we have a design for when there are no channels.

/reopen

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
