### PR TITLE
Bug 1875360: Update project workloads tab to use topology list view

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Updates the Project page's workloads tab to show the topology list view component. This shows grouping info for things like knative services, helm releases, and operator backed services. This make the two views of the same data from different perspectives become the same.

**Screen shots / Gifs for design review**: 

image

image

/kind bug

### CODE REVIEW

**Comment by jeff-phillips-18** [comment]
/hold

Depends on https://github.com/openshift/console/pull/6188

**Comment by jeff-phillips-18** [comment]
/hold

Working on fixing chunk size issue. Seems less is sometimes more.

**Review by spadgett — APPROVED** [review]
/lgtm

Thanks @jeff-phillips-18 👍

**Pull request merged**
