### PR TITLE
Define chromium base branch and checksum at one place

### PR DESCRIPTION
**Pull request by rhrazdil**
Currently chrome base branch and checksum values used for console CI are hardcoded in `test-prow-e2e.sh` and `frontend/test-e2e.sh`. 

As there are teams working on building CI automation for openshift/console plugins (kubevirt, ceph-storage), it would be better to define chromium binary version at one place so that other teams can use it as well.

This way, if openshift core team decides to move to a newer version, it can be done by updating single file and more importantly, without breaking other teams jobs.

I'm not sure about the file naming. @spadgett @vojtechszocs wdyt?

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
/lgtm

+1 to avoiding the duplication.

**Comment by benjaminapetersen** [comment]
The analyze fail seems unlikely given you haven't touched JavaScript:

```
Copying the Webpack Bundle Analyzer report to /tmp/artifacts...
Main vendor bundle size: 4.17 MiB
FAILURE: Main vendor bundle is larger than the 2 MiB limit.
If you haven't added a new dependency, an import might have accidentally pulled an existing dependency into the main vendor bundle.
If adding a large dependency, consider lazy loading the component with AsyncComponent.
```

**Comment by spadgett** [comment]
/hold
e2e-gcp-console is currently broken

**Comment by spadgett** [comment]
/hold cancel
/retest
#3847 has fixed the e2e tests

**Pull request merged**
