### PR TITLE
Bug 1872288: Delete the hashed session token on user logout

### PR DESCRIPTION
**Pull request by jhadvig**
Manual backport of https://github.com/openshift/console/pull/6431

/assign @spadgett

cc'ing @sttts

### CODE REVIEW

**Comment by crawford** [comment]
Does this need to wait for https://github.com/openshift/origin/pull/25415?

**Comment by yapei** [comment]
QE tested the fix with steps:
```
$ export KUBECONFIG=./cluster-bot-2020-08-27-021119.kubeconfig
$ oc get oauthaccesstoken    // before user is logged in
No resources found
$ oc get oauthaccesstoken | grep yapei   // after user yapei1 is logged in
1bRY.......   yapei1      console       2020-08-27T03:07:51Z   2020-08-28 03:07:51 +0000 UTC   https://<console_route>/auth/callback   user:full
$ oc get oauthaccesstoken | grep yapei    //after user yapei1 is logged out
No resources found
```
The oauthaccesstoken is deleted after user is logged out

**Review by yapei — APPROVED** [review]
/lgtm

**Comment by yapei** [comment]
> Does this need to wait for [openshift/origin#25415](https://github.com/openshift/origin/pull/25415)?

I have the same concern.

**Comment by jhadvig** [comment]
@yapei check the enhancement describing the change: https://github.com/openshift/enhancements/blob/master/enhancements/authentication/oauth-resource-storage.md

**Comment by jhadvig** [comment]
we need to wait for https://github.com/openshift/origin/pull/25415 to get merged

/hold

**Comment by sttts** [comment]
> we need to wait for openshift/origin#25415 to get merged

No, the other way around.

/hold cancel

**Comment by xingxingxia** [comment]
@yapei  @jhadvig @sttts I think this PR verification requires https://github.com/openshift/origin/pull/25415.
@yapei maybe we need: /msg @cluster-bot launch openshift/console#6445,openshift/origin#25415
I'm currently testing /msg @cluster-bot launch openshift/origin#25415

**Pull request merged**
