### PR TITLE
Monitoring: Improve graph tooltip style

### PR DESCRIPTION
**Pull request by kyoto**
Builds on https://github.com/openshift/console/pull/2071. Only the last commit of this PR is new.

- Move tooltip above the cursor
- Add tooltip arrow
- Allow the height to expand to fill the available space
- Decrease font size
- Also set metric dropdown overflow to `auto` (was accidentally set to `scroll`)

screenshot

FYI @cshinn

### CODE REVIEW

**Comment by spadgett** [comment]
@kyoto do you want to close #2071 and just go with this one?

**Comment by kyoto** [comment]
Rebased and also squashed the 2 tooltip commits.

**Pull request merged**
