### PR TITLE
Update OAuth error handling

### PR DESCRIPTION
**Pull request by spadgett**
/assign @rhamilto

### CODE REVIEW

**Comment by rhamilto** [comment]
@spadgett, it looks like the backend auth test is broke.  :(

```
# github.com/openshift/console/pkg/auth [github.com/openshift/console/pkg/auth.test]
pkg/auth/auth_test.go:170:21: too many arguments in call to a.redirectAuthError
```

**Comment by spadgett** [comment]
@rhamilto I fixed the backend test error

/hold cancel

**Pull request merged**
