### PR TITLE
[release-4.12] OCPBUGS-16846: Fix stop PLR option

### PR DESCRIPTION
**Pull request by vikram-raj**
Manual cherry-pick of PR https://github.com/openshift/console/pull/13031

### CODE REVIEW

**Comment by vikram-raj** [comment]
verified it on the cluster bot


https://github.com/openshift/console/assets/2561818/ed36ef53-026e-4345-8e71-0b1563b1ab3f

/retest

**Comment by lokanandaprabhu** [comment]
Tested on cluster bot. Working fine.

/lgtm


https://github.com/openshift/console/assets/102503482/1d9db9f3-527e-4136-8074-26d363ca4dfb

**Pull request merged**
