### PR TITLE
[release-4.9] OCPBUGS-2008: Show already loaded catalog items after a timeout (3sec)

### PR DESCRIPTION
**Pull request by jerolimov**
Manual backport of #12106

Just a simple fixable merge conflict in `frontend/packages/dev-console/integration-tests/features/e2e/add-flow-ci.feature`

4.12: https://issues.redhat.com/browse/OCPBUGS-270
4.11: https://issues.redhat.com/browse/OCPBUGS-1523
4.10: https://issues.redhat.com/browse/OCPBUGS-1759
4.9: https://issues.redhat.com/browse/OCPBUGS-2008

/kind bug
/cc @invincibleJai @sanketpathak

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
verified the changes by adding setTimeout to devfile catalog request.

packages/dev-console/src/components/catalog/providers/useDevfile.tsx and
packages/dev-console/src/components/catalog/providers/useDevfileSamples.tsx

/lgtm

**Comment by invincibleJai** [comment]
verified on cluster and seems fine

image
 
 cc @sanketpathak

**Pull request merged**
