### PR TITLE
ODC-7389: Replace topology graphic with new version for openshift v4.15

### PR DESCRIPTION
**Pull request by Lucifergene**
**Fixes**: 
https://issues.redhat.com/browse/ODC-7389

**Solution Description**: 
Updated the image.

**Screen shots / Gifs for design review**: 

image

**Unit test coverage report**: 
Not changed.

**Test setup:**
1. Create a new application with the label: `app.openshift.io/runtime=openshift`

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Tested locally. 

/lgtm

image

**Review by jerolimov — APPROVED** [review]
/approve

**Comment by jerolimov** [comment]
Just an icon, hope that's fine @sanketpathak 

/label qe-approved

**Comment by sanketpathak** [comment]
Verified on cluster-bot using admin and non-admin user

https://github.com/openshift/console/assets/10252230/35554462-b683-4db4-9309-172cd2e4cd28

/label qe-approved

**Pull request merged**
