### PR TITLE
Bug 1879485: fix application selector incontext for add forms

### PR DESCRIPTION
**Pull request by sahil143**
**Fixes**: https://issues.redhat.com/browse/ODC-2386

**Analysis / Root cause**: when the application is selected using the ApplicationSelector in the secondary masthead . Context for the selected application is not kept in the import forms

**Solution Description**: Keep the context of application

**Screen shots / Gifs for design review**: Coming soon

**Unit test coverage report**: None

**Test setup:**

**Browser conformance**: 

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by invincibleJai** [comment]
Looks good, Verified locally seems to work as expected

**Comment by christianvogt** [comment]
The selector is still showing `all applications` when the last application is deleted in another browser.

**Comment by invincibleJai** [comment]
@sahil143 have verified again after fix , i see as below i.e even if user deletes app name from another browser still show's that application. That's the expected behaviour right?


Sep-24-2020 14-19-35

**Comment by sahil143** [comment]
> @sahil143 have verified again after fix , i see as below i.e even if user deletes app name from another browser still show's that application. That's the expected behaviour right?

Yes, That is expected behaviour

cc @christianvogt

**Comment by jerolimov** [comment]
Unfortunately this change means also that a deep link with the `?application` parameter was not displayed correctly. But the new Deployment was created with the correct application anyway!

Screencast_24 09 2020_14:35:27 webm

**Comment by christianvogt** [comment]
@jerolimov I don't see a difference in your scenario with this change or without. It seems like it's something we can handle in a separate issue. Do you mind creating a issue for this?

**Comment by christianvogt** [comment]
This improves the issue.
UX had some further suggestions that we can consider after further review.

**Pull request merged**
