### PR TITLE
[release-4.3] Bug 1808282: fixes issue with new imageStream getting created for knative in case of internal image registry

### PR DESCRIPTION
**Pull request by invincibleJai**
This is a manual cherry-pick of https://github.com/openshift/console/pull/3931 of commit 6f04e4f4005cd95670b2363d0acde128359ac421

fixes issue with new imageStream getting created for knative in case of internal image registry

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
Tested the scenario where Imagestream is only created when the source is from External registry in case of Knative Service.
/lgtm

**Comment by sahil143** [comment]
/lgtm 
Verified locally, works as expected.

**Pull request merged**
