### PR TITLE
Bug 2018884: Adapting crw-basic.feature to changs introduced in OCP 4.9

### PR DESCRIPTION
**Pull request by rhopp**
Signed-off-by: Radim Hopp <rhopp@redhat.com>

### CODE REVIEW

**Comment by rhopp** [comment]
@makambalaji I think you can take a look. I'll create bugzilla and link it here on Monday if necessary.

**Comment by rhopp** [comment]
@makambalaji Issue in bugzilla was created: https://bugzilla.redhat.com/show_bug.cgi?id=2018884. PTAL

**Comment by makambalaji** [comment]
@rhopp - Page is getting logged out after clicking on CodeReady Workspaces in Application menu in Masthead
image

**Comment by rhopp** [comment]
Trying...

**Comment by rhopp** [comment]
@makambalaji Are you running it in the same setup as the CI is? It doesn't seem to me based on your screenshot you are running some local console instance (localhost:9000) and even the htpasswd provider is named differently. AFAIK the default htpasswd provider name in CI is `test` (https://github.com/openshift/console/blob/master/frontend/integration-tests/data/patch-htpasswd.yaml) and your is named `consoledeveloper`.
Either please use the same setings as CI is using, or please override `BRIDGE_HTPASSWD_*` env variables to fit your needs.

**Comment by rhopp** [comment]
Screencast of successfull run: https://youtu.be/XMF21A1m4C0
<details>
<summary>Stdout log</summary>

```
> Executing task: npm run test-headless <


> @dev-console/integration-tests@0.0.1 test-headless /home/rhopp/git/console/frontend/packages/dev-console/integration-tests
> node --max-old-space-size=4096 ../../../node_modules/.bin/cypress run --env openshift=true --browser ${BRIDGE_E2E_BROWSER_NAME:=chrome} --headless --spec "features/codeready-workspaces/crw-basic.feature";


====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    8.5.0                                                                              │
  │ Browser:    Chrome 95 (headless)                                                               │
  │ Specs:      1 found (codeready-workspaces/crw-basic.feature)                                   │
  │ Searched:   features/codeready-workspaces/crw-basic.feature                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  codeready-workspaces/crw-basic.feature                                          (1 of 1)


  Logging in as kubeadmin
  Basic Codeready Workspaces usage
  Logging out
  Logging in as kubeadmin
      Installing operator: "Red Hat CodeReady Workspaces"
      Operator Red Hat CodeReady Workspaces was not yet installed.
      Performing CRW post-installation steps
      User has selected namespace openshift-workspaces
      User has selected namespace openshift-workspaces
  Logging out
  Logging in as test
    ✓ CRW is shown in Applications menu in Masthead (403639ms)
  Logging out
  Logging in as kubeadmin
      Installing operator: "Red Hat CodeReady Workspaces"
      Operator Red Hat CodeReady Workspaces is already installed.
      Performing CRW post-installation steps
      User has selected namespace openshift-workspaces
      Red Hat CodeReady Workspaces already installed.
      User has selected namespace openshift-workspaces
  Logging out
  Logging in as test
    ✓ CRW Dashboard is opened when user clicks on CRW in Applications menu in Masthead (59587ms)


  2 passing (8m)

[mochawesome] Report JSON saved to /home/rhopp/git/console/frontend/gui_test_screenshots/cypress_report_devconsole_007.json


  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        2                                                                                │
  │ Passing:      2                                                                                │
  │ Failing:      0                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     7 minutes, 44 seconds                                                            │
  │ Spec Ran:     codeready-workspaces/crw-basic.feature                                           │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Video)

  -  Started processing:  Compressing to 32 CRF                                                     
    Compression progress:  52%
    Compression progress:  94%
  -  Finished processing: /home/rhopp/git/console/frontend/gui_test_screenshots/cypre   (24 seconds)
                          ss/videos/codeready-workspaces/crw-basic.feature.mp4                      


====================================================================================================

  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  codeready-workspaces/crw-basic.feat      07:44        2        2        -        -        - │
  │    ure                                                                                         │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        07:44        2        2        -        -        -  


```
</details>

**Comment by makambalaji** [comment]
> @makambalaji Are you running it in the same setup as the CI is? It doesn't seem to me based on your screenshot you are running some local console instance (localhost:9000) and even the htpasswd provider is named differently. AFAIK the default htpasswd provider name in CI is `test` (https://github.com/openshift/console/blob/master/frontend/integration-tests/data/patch-htpasswd.yaml) and your is named `consoledeveloper`. Either please use the same setings as CI is using, or please override `BRIDGE_HTPASSWD_*` env variables to fit your needs.

When we are executing scripts on localhost, username and password are not needed as per the [login](https://github.com/openshift/console/blob/master/frontend/packages/integration-tests-cypress/support/login.ts#L20) function

**Comment by makambalaji** [comment]
CRW terminal displays only with developer role, so while executing the che test cases in local, login with developer and executes

/lgtm

**Comment by jerolimov** [comment]
@rhopp should we cherrypick/backport this to 4.9?

**Pull request merged**
