### PR TITLE
fix(serverless): Adv Search for knative resources throws error

### PR DESCRIPTION
**Pull request by invincibleJai**
Adv Search for knative resources i.e services/routes/revisions throws an error

Tracks: https://jira.coreos.com/browse/ODC-1540

GIF:

ezgif com-video-to-gif

### CODE REVIEW

**Comment by joshuawilson** [comment]
I don't know how to validate this, I can't reproduce it.

**Comment by invincibleJai** [comment]
@joshuawilson ah, i updated the issue with steps. I'll try to create a gif as well.

**Pull request merged**
