### PR TITLE
ODC-7703: Quick create actions in the masthead toolbar

### PR DESCRIPTION
**Pull request by vikram-raj**
Story: https://issues.redhat.com//browse/ODC-7703

Descriptions: 
- Change Import YAML to a dropdown
- Add 3 menu actions 
    -  Import YAML
    - Import from GIT
    -  Container image

https://github.com/user-attachments/assets/d5c6dab3-82d6-46d3-aeb5-bcef3a18672e

image

Tests
image

### CODE REVIEW

**Review by lokanandaprabhu — COMMENTED** [review]
1. Quick create tooltip does not look like tooltip, since the background color is same, if I hover on `+` sign, it gives the feeling as some random string/button replaced `?` icon. 

Screenshot 2024-10-08 at 1 31 40 PM

------
2. For small screen, when I hover on any of the 3 new options, all 3 background color is getting changed, it should change color for only one option

Screenshot 2024-10-08 at 1 33 52 PM


-------
3. On click of `+` icon, dropdown opens, but the position is creating confusion, `?` is in the middle of the dropdown, it does not clearly indicate the fact that the menu is for `+` sign.

Screenshot 2024-10-08 at 1 32 35 PM

-------

**Comment by vikram-raj** [comment]
@lokanandaprabhu Fixed above issues PTAL. Thanks

**Comment by sanketpathak** [comment]
I tested the pr with the cluster bot and have two questions: 

- When logging in for the first time import from yaml will have All Projects and the other two imports will have default selected. Is this an intended behavior if yes this will force a user to use default as the namespace

https://github.com/user-attachments/assets/4e9c9d5b-5900-48bc-8d18-f876b4fe2609

- When logging in as a non-admin user there is no option available for quick create until the user creates a namespace as compared below in two images where one is from the latest nighty available. Is this also an intended behavior

Cluster on pr
Screenshot from 2024-10-10 16-22-38

Latest nightly
Screenshot from 2024-10-10 16-25-26

**Comment by vikram-raj** [comment]
@sanketpathak , Yes these are intended behaviours.

> When logging in for the first time import from yaml will have All Projects and the other two imports will have default selected. Is this an intended behavior if yes this will force a user to use default as the namespace

Other forms like Build in admin perspective have the same behavior and on form page we do not have to select the namespace but in case of YAML user can mention the namespace in yaml.

> When logging in as a non-admin user there is no option available for quick create until the user creates a namespace as compared below in two images where one is from the latest nighty available. Is this also an intended behavior

It doesn't make sense to show the options if the user has no access to any namespace or does not create any namespace.

**Comment by sanketpathak** [comment]
Screenshot from 2024-10-12 03-24-36
Verified on cluster with admin and  non admin users, tests run green as well
/label qe-approved

**Pull request merged**
