### PR TITLE
Bug 2050637: add a hardcoded blog link as fallback in guided tours

### PR DESCRIPTION
**Pull request by sahil143**
**Fixes**: https://issues.redhat.com/browse/OCPBUGSM-40325

**Analysis / Root cause**: ConsoleLinks CR is not available at times which causes the blog link to be undefined

**Solution Description**: add a fallback link for blogs

**Screen shots / Gifs for design review**: 

Kapture 2022-03-02 at 12 16 24

**Unit test coverage report**: None

**Test setup:**

**Browser conformance**: 

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by debsmita1** [comment]
@sahil143 would be great if you can add a test :)

**Comment by debsmita1** [comment]
verified the changes
/lgtm

**Comment by invincibleJai** [comment]
/approve

Verified the changes with cluster bot

**Pull request merged**
