### PR TITLE
ODC-7384: Update the PipelineRun details page to use Tekton Results API to load all the info

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
Story : https://issues.redhat.com/browse/ODC-7384

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Hi @vikram-raj / @jerolimov 

I updated the PR. PTAL. Thanks.

**Review by vikram-raj — COMMENTED** [review]
I noticed an issue. On the details page, there is continuous network call for results API.

**Review by karthikjeeyar — COMMENTED** [review]
Fetching TektonResult CR,  tekton results API service and the actual tekton-results pipelinerun API call is being called in infinitely in the pipelinerun details page. 

image

**Comment by karthikjeeyar** [comment]
In pipelinerun details page, we will be fetching all the taskruns as well. So when you delete a pipelienrun (which will inturn delete all the taskruns automatically from K8s cluster)  and then go to that deleted details page you can see the visualization with wrong task status, we need to use tekton-results for fetching the taskruns here as well.

image

**Comment by lokanandaprabhu** [comment]
Closing this PR since it is handled in PR - https://github.com/openshift/console/pull/13328

/close

**Pull request closed without merging**
