### PR TITLE
Bug 1921713: Fix migration tests

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Comment by rawagner** [comment]
/hold

I need to update the PR

**Comment by rawagner** [comment]
/hold cancel
@gouyang please take a look again. There was another problem where `waitForStatus` uses conditional waiting which is not always correct. `until.textToBePresentInElement` which was used before this change checks if the text is _included_ in the status. But we need to check if status _startsWith_ which is more precise

**Comment by spadgett** [comment]
/override ci/prow/ceph-storage-plugin

The ceph-storage-plugin job should only have run on PRs with changes to `frontend/packages/ceph-storage-plugin`. It failed due to an unrelated CI config change. Overriding status on this PR.

**Pull request merged**
