### PR TITLE
Add filter by label in topology

### PR DESCRIPTION
**Pull request by karthikjeeyar**
**Fixes**: 

https://issues.redhat.com/browse/ODC-4410

**Analysis / Root cause**: 

As a user, I want to toggle the search between Name and Label in topology.

**Solution Description**: 

1. Added label filter to topology and left  filter by `Name` as the default option.
2. Updated the search filter dropdown components to add custom placeholders and default selection.

**Screen shots / Gifs for design review**: 

image

Screenshot 2021-11-19 at 4 45 29 PM

image

https://user-images.githubusercontent.com/9964343/142613679-dff1f441-e31c-4ee8-a497-f050249c2190.mp4

**Unit test coverage report**: 

image

**Test setup:**

1. Add different type of workloads in a namespace and use filter by name and label feature in the topology page.

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

cc: @serenamarie125 @beaumorley

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
The name should be the first option in the dropdown as we have at other places.

image

**Comment by beaumorley** [comment]
Agree that the dropdown should be sorted with the default (Name) being first in the dropdown list. 

Also for Label, do we want to have "Find by label" as the help text instead of changing it to "app=frontend"? Raising this as a question because it is not consistent. I notice that in Secrets, ConfigMaps and Builds we keep the the Name/Label field help text in this format ("Search by xxx") but for Search we use an example of how you enter the search but we do it for both Label and Name. I think we should do both options in the same format but looking for input on which format is better for Topology.  @serenamarie125 do you have thoughts.

**Comment by karthikjeeyar** [comment]
@beaumorley  It makes sense to have the same format for both the field's placeholder text. I want to highlight that when a user enters a character we are auto suggesting the available labels to choose from and they get to see the format of the labels in the dropdown values as well. IMO `Find by Label...`  placeholder text would make it consistent with our existing `Find By Name....` name field placeholder.

image

**Comment by vikram-raj** [comment]
@karthikjeeyar Looks like the label filter is not working in the topology list view
Kapture 2021-11-24 at 20 37 06
.

**Comment by karthikjeeyar** [comment]
fixed list view label filter

image

**Review by vikram-raj — COMMENTED** [review]
Verified it and its works as expected.

/lgtm
/label qe-approved

**Comment by vikram-raj** [comment]
Propagate from epic:
/label docs-approved
/label px-approved

**Comment by serenamarie125** [comment]
This looks great @karthikjeeyar !

**Review by vikram-raj — COMMENTED** [review]
/lgtm

**Pull request merged**
