### PR TITLE
i18n overview dashboard health state messages

### PR DESCRIPTION
**Pull request by afreen23**
- Created `healthStateMessage` function to update the strings when language changes, since the  existing map `healthStateMapping` is used at various places for icons/priority only.
- replaced `healthStateMapping[state].message` with `healthStateMapping`

Followup for this comment https://github.com/openshift/console/pull/7368#discussion_r533136267

### CODE REVIEW

**Comment by rawagner** [comment]
looks good, but please run `yarn i18n` to update the locale files

**Comment by afreen23** [comment]
> looks good, but please run `yarn i18n` to update the locale files

Done!

**Pull request merged**
