### PR TITLE
OCPBUGS-41613: Various tests are failing due to missing content in <li.pf-v5-c-menu__list-item> element

### PR DESCRIPTION
**Pull request by Mylanos**
Working with the object yielded from the create project oc command seemed to fix the issue locally. WIP testing on CI.

### CODE REVIEW

**Comment by Mylanos** [comment]
┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        true                                                                             │
  │ Duration:     44 seconds                                                                       │
  │ Spec Ran:     operator-install-global.cy.ts                                                    │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

1) Globally installing "Data Grid" operator in openshift-operators
       "before all" hook for "Globally installs Data Grid operator in openshift-operators and creates Infinispan operand":
     AssertionError: Timed out retrying after 30000ms: Expected to find element: `[data-test="datagrid-redhat-operators-openshift-marketplace"]`, but never found it.

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `Globally installing "Data G...`

**Comment by jhadvig** [comment]
looks promising 🤞

**Review by jhadvig — APPROVED** [review]
/approve
/lgtm

**Review by jhadvig — APPROVED** [review]
/lgtm

**Comment by jhadvig** [comment]
@Mylanos the additional wait is not fixing the issue :( annotations are not failing

**Comment by Mylanos** [comment]
I thought so 🙁 maybe we should try to add the timeout before the page with the dropdown actually renders, e.g. after the CLI exec command that creates new project.

**Comment by jhadvig** [comment]
I would rather suggest refresh of the page

**Pull request merged**
