### PR TITLE
OCPBUGS-23764: bump PF dependencies to the latest patch fix

### PR DESCRIPTION
**Pull request by nicolethoen**
Fixes misalignment of buttons as captured in this screenshot.
Screenshot 2023-11-27 at 4 46 22 PM

### CODE REVIEW

**Review by lokanandaprabhu — APPROVED** [review]

**Review by jerolimov — APPROVED** [review]
/retest

**Review by jerolimov — APPROVED** [review]
I've checked the broken e2e tests manually on a cluster bot and couldn't find an issue.

* Import from git > Imported Dev file > Tested topology actions
* Created a Helm release > Tested topology actions

So I think the tests needs some updates, but we can handle this as a follow up.

/lgtm

**Pull request merged**
