### PR TITLE
Ctrl-S (or Cmd-S on macOS) should save in the Monaco editor

### PR DESCRIPTION
**Pull request by spadgett**
/assign @TheRealJon 
@beanh66 fyi

### CODE REVIEW

**Comment by spadgett** [comment]
@rebeccaalpert We should probably add this to the shortcuts from #3178, but let's do it in a follow up after both PRs merge.

**Comment by rebeccaalpert** [comment]
@spadgett Thanks for the heads up. Sounds like a plan.

**Pull request merged**
