### PR TITLE
CONSOLE-3081: Adjust pf-c-card background color, when on dark theme, so that it is discernible.

### PR DESCRIPTION
**Pull request by sg00dwin**
Upstream issue opened https://github.com/patternfly/patternfly/issues/4889

**Before and After**

Screen Shot 2022-06-09 at 3 43 54 PM
Screen Shot 2022-06-09 at 3 45 42 PM

----

Screen Shot 2022-06-09 at 3 43 11 PM

Screen Shot 2022-06-09 at 3 09 24 PM

----
os-dark-card2
Screen Shot 2022-06-09 at 2 37 22 PM

### CODE REVIEW

**Comment by sg00dwin** [comment]
/label docs-approved
/label px-approved

We have docs- and px-approval for the epic.

**Comment by sg00dwin** [comment]
QE Approver:
/assign @yanpzhan

**Review by jcaianirh — APPROVED** [review]
/lgtm

pulled it down and checked it out. looks great
Screen Shot 2022-06-10 at 11 42 59 AM

**Pull request merged**
