### PR TITLE
OU-241,OCPBUGS-19458: Remove unused Observe > Metrics page code

### PR DESCRIPTION
**Pull request by kyoto**
This page is now provided by the `monitoring-plugin` dynamic plugin and nothing in the console codebase is using these components.

### CODE REVIEW

**Comment by kyoto** [comment]
This is a refactoring change. There should be no user visible changes.

/label docs-approved
/label px-approved

**Comment by juzhao** [comment]
regression bug: https://issues.redhat.com/browse/OCPBUGS-19458

**Pull request merged**
