### PR TITLE
OCPBUGS-6994:  when ACM is installed and no previous perspective is set, default perspective to All Clusters

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by rhamilto** [comment]
/hold

I broke tests that need fixing.

**Comment by rhamilto** [comment]
/hold cancel

Test fixed.

**Comment by rhamilto** [comment]
/hold

Testathon reveals this is not a valid solution.

**Comment by rhamilto** [comment]
It is believed the issues we were seeing during the testathon were related to the GraphQL changes and not the changes in this PR.

But keeping the `hold` since https://github.com/openshift/console/pull/12480 should merge first.

**Comment by rhamilto** [comment]
@TheRealJon, PTAL.

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Pull request merged**
