### PR TITLE
Bug 2067180: Completed-7034-OCP 4.11 UI Localization- Sprint 215

### PR DESCRIPTION
**Pull request by cyril-ui-developer**
@jhadvig 
cc: @spadgett 

I downloaded translations for public, console-app, console-shared and olm. I'm not sure of the other packages to download. Please let me know if I need to download more packages.

### CODE REVIEW

**Comment by cyril-ui-developer** [comment]
@jhadvig @spadgett I have downloaded translations for all the packages.

**Comment by jhadvig** [comment]
We should be backporting to 4.10, we do that at least for the messages that came in after code freeze, although we have to be careful if existing messages were changed.

**Pull request merged**
