### PR TITLE
frontend: Fix developer catalog heights

### PR DESCRIPTION
**Pull request by rebeccaalpert**
Add class from OperatorHub tiles to developer catalog tiles and add maxTruncation prop to these tiles.

Screen Shot 2019-12-04 at 2 57 21 PM

Heads up @jcaianirh and @spadgett.

### CODE REVIEW

**Comment by spadgett** [comment]
It seems like we're truncating too early in these tiles. There is plenty of space below.

It would be better to use line-clamp instead of arbitrary character lengths so it fills the available width. We have a mixin.

https://github.com/openshift/console/blob/master/frontend/public/style/mixin/_line-clamp.scss

cc @christianvogt

**Comment by spadgett** [comment]
We've removed the fading text style from other parts of context, so there's no reason to keep it in the catalog any longer imo. line-clamp with `...` would be better.

**Comment by rebeccaalpert** [comment]
The tiles change width depending on the size of your browser window. I had set the truncation based on the narrowest width there.

I need to make a change to the extension to let us apply this class to the description and remove the fade; I'll get on that.

**Pull request merged**
