### PR TITLE
Bug 2046156: fix showing error in netpol affected pods

### PR DESCRIPTION
**Pull request by jotak**
BZ https://bugzilla.redhat.com/show_bug.cgi?id=2046156 (console)
JIRA https://issues.redhat.com/browse/NETOBSERV-172 (netobserv)

### CODE REVIEW

**Comment by jotak** [comment]
@jhadvig not sure which target I should set in BZ. This isn't a critical issue.

**Review by mariomac — APPROVED** [review]

**Review by OlivierCazade — APPROVED** [review]

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by jotak** [comment]
hey @spadgett the master branch target 4.11 now, right? So i guess we can unhold, do you confirm?

**Pull request merged**
