### PR TITLE
CONSOLE-2776: Consolidate i18n namespaces s-z

### PR DESCRIPTION
**Pull request by zherman0**
Consolidate i18n namespaces s-z

### CODE REVIEW

**Review by dtaylor113 — APPROVED** [review]
/lgtm

**Comment by dtaylor113** [comment]
built locally, no errors. `yarn i18n` ran with no errors and no addtional i18n files were generated.  :+1:

**Comment by zherman0** [comment]
/assign @yapei @ahardin-rh @sferich888
for approvals

**Comment by zherman0** [comment]
/retest

'uninstall btn not there' for olm - I assume that is a flake

**Comment by spadgett** [comment]
/label px-approved
We've received approval from Eric for this PR.

**Review by spadgett — APPROVED** [review]
/lgtm
/hold for QE review

**Pull request merged**
