### PR TITLE
Bug 1754789: Fix pending status of the importer pod

### PR DESCRIPTION
**Pull request by mareklibra**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1754789

### CODE REVIEW

**Comment by mareklibra** [comment]
/assign @bparees

Any idea why netther @suomiy nor me (@mareklibra ) can not approve that PR? We are both listed in the https://github.com/openshift/console/blob/master/frontend/packages/kubevirt-plugin/OWNERS .

It worked up to this PR. Has anything changed?

**Comment by suomiy** [comment]
@mareklibra it started working again :tada:

**Pull request merged**
