### PR TITLE
kubevirt e2e: Scroll dev console add+ tab to bottom

### PR DESCRIPTION
**Pull request by yaacov**
Fix dev console create virtual machine tests

Signed-off-by: yzamir <yzamir@localhost.localdomain>

### CODE REVIEW

**Comment by yaacov** [comment]
@gouyang @metalice @giannisalinetti @pcbailey please review

**Comment by gouyang** [comment]
/lgtm
I just add this into #8997 some time ago as well. :)

**Comment by gouyang** [comment]
it's still not working in this way, I have changed it to another way in #8997 as it pass locally.

**Pull request merged**
