### PR TITLE
View more links to monitoring page instead of prometheus

### PR DESCRIPTION
**Pull request by rawagner**
addresses https://github.com/openshift/console/issues/3036

@ncameronbritt @cshinn @kyoto remaining question is where should we link to as regular (non-admin) user. User can still query prometheus tenancy endpoint but monitoring page is hidden.

### CODE REVIEW

**Comment by sichvoge** [comment]
There will be a similar query browser view in the dev perspective you may want to link into.

**Comment by kyoto** [comment]
Thanks @rawagner!

I think you can now remove `urls` from `PopoverBodyProps` too.

**Comment by kyoto** [comment]
@rawagner The Developer perspective version of the Metrics page already exists on master, so you can link to that the same as for the Administrator perspective.

**Comment by rawagner** [comment]
@kyoto removed `urls` from `PopoverBodyProps`. Once https://github.com/openshift/console/pull/3131 is merged I can link to developer/monitoring page from Project Dashboard - it will be done is separate PR

**Pull request merged**
