### PR TITLE
Bug 2037772: Use correct caps in 'Service name' & 'System name '

### PR DESCRIPTION
**Pull request by ashishkumsingh**
https://bugzilla.redhat.com/show_bug.cgi?id=2037772

Signed-off-by: Ashish Singh <assingh@redhat.com>

### CODE REVIEW

**Comment by afreen23** [comment]
/ok-to-test
/retitle Bug 2037772: Use correct caps in 'Service name' & 'System name '

**Comment by afreen23** [comment]
/lgtm cancel

run yarn i18n , commit and push the changes.
@ashishkumsingh

**Comment by ashishkumsingh** [comment]
@afreen23 Can you review now?

**Review by afreen23 — CHANGES_REQUESTED** [review]
Hi @ashishkumsingh , make sure you do the following:
1. run `yarn i18n`
2. commit your changes . After running yarn 1i8n , there will be some changes in the i18n files.
3. squash your changes
4. Then push your PR

**Pull request merged**
