### PR TITLE
[release-4.14] OCPBUGS-31394: PipelineRuns in Console show wrong status or load indefinitely

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
This is manual cherry-pick of PR - https://github.com/openshift/console/pull/13672

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Tested using cluster bot. Working fine.


https://github.com/openshift/console/assets/102503482/f0400ed3-9eed-40f2-8932-3084f3dc4307

**Comment by lokanandaprabhu** [comment]
@vikram-raj , can you please review this PR.

**Review by Lucifergene — COMMENTED** [review]
/lgtm

**Review by vikram-raj — COMMENTED** [review]
/approve

**Comment by lokanandaprabhu** [comment]
@sanketpathak / @The-Anton ,

Can you please review this PR? 

/cc @sanketpathak @The-Anton

**Comment by vikram-raj** [comment]
/retitle [release-4.14] OCPBUGS-31394: PipelineRuns in Console show wrong status or load indefinitely

**Pull request merged**
