### PR TITLE
ODC-7610: Add light theme CodeEditor

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 
https://issues.redhat.com/browse/ODC-7610

**Solution Description**: 

Add a light mode to Monaco for light mode users, so that when they are editing they are also in light mode

**Screen shots / Gifs for design review**: 

dark theme is unaffected.

before:
before

after: 
after

demo:

https://github.com/user-attachments/assets/04b1653f-1266-46b8-9e41-f29e335e31a0

I have double checked that the custom light theme color choices pass WCAG 2.0 level AA contrast requirements 

**Unit test coverage report**: 

n/a

**Test setup:**

n/a

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

### CODE REVIEW

**Review by Lucifergene — COMMENTED** [review]
**Couple of questions:**

1. How will the user change the theme from the UI?
2. How does it react to the Light & Dark modes of the console? Will the theme change accordingly?
3. Why is the BuildConfig EditorField only updated alongside the shared Code-Editor? Are there any other packages where EditorField used? We need to ensure same experience console-wide.

**Comment by logonoff** [comment]
> **Couple of questions:**
> 
>     1. How will the user change the theme from the UI?

Through the existing theme changer in the user dropdown in the masthead > User preferences > Theme

>     2. How does it react to the Light & Dark modes of the console? Will the theme change accordingly?

Yes, I use the global `ThemeProvider` to determine light/dark values, it reacts to system theme changes and changes to theme within the settings

>     3. Why is the BuildConfig EditorField only updated alongside the shared Code-Editor? Are there any other packages where EditorField used? We need to ensure same experience console-wide.

I did a global search for the string `MonacoEditor` and updated files accordingly, since the `MonacoEditor` component is what actually renders the editor and consumes the `theme` prop that is being supplied

**Comment by logonoff** [comment]
Following feedback, here is a version of this story where the CodeEditor theme control is decoupled from the rest of the console:

https://github.com/user-attachments/assets/74c68002-28e3-4b05-868c-54ab04517fb9

What are your thoughts? @Lucifergene @vikram-raj

**Review by vikram-raj — APPROVED** [review]
Verified it.

/lgtm

**Comment by sanketpathak** [comment]
Verified on a cluster with admin and non-admin users
Screenshot 2024-09-11 at 9 39 53 PM

/label qe-approved

**Pull request merged**
