### PR TITLE
TypeScript 3.0

### PR DESCRIPTION
**Pull request by alecmerdler**
### Description

Upgrade to `typescript@3.0.1` and made the necessary fixes.

Addresses our need to be on the cutting edge

### CODE REVIEW

**Comment by spadgett** [comment]
Nothing too scary here: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes

I say we go ahead if tests are passing. We have a few sprints to roll back if we find something.

**Comment by alecmerdler** [comment]
`yarn run test` works fine locally, not sure why it is failing in Jenkins...

**Comment by alecmerdler** [comment]
@spadgett This isn't ready to merge, need to work out some bugs first.

**Comment by spadgett** [comment]
Understood, just trying to understand why the prow tests aren't running

**Comment by alecmerdler** [comment]
Closing until I can figure out the circular dependency issues.

**Pull request closed without merging**
