### PR TITLE
Moved the remaining popover to top under utilization card

### PR DESCRIPTION
**Pull request by bipuladh**
- Moved CPU popover to top.
Screenshot from 2019-11-25 02-02-22

### CODE REVIEW

**Comment by bipuladh** [comment]
/assign @rawagner @andybraren 
The other two had been moved in the previous PR.

**Comment by rawagner** [comment]
can you do the same for the Project dashboard ?

**Comment by bipuladh** [comment]
@rawagner made changes for Project Dashboard too.

**Comment by cloudbehl** [comment]
@bipuladh Does this work properly with a smaller screen width?

**Comment by bipuladh** [comment]
@cloudbehl just tested, yes!

**Pull request merged**
