### PR TITLE
Improve display of Operators columns

### PR DESCRIPTION
**Pull request by rhamilto**
localhost_9000_k8s_all-namespaces_operators coreos com_v1alpha1_InstallPlan_orderBy=desc sortBy=Name
localhost_9000_k8s_all-namespaces_operators coreos com_v1alpha1_InstallPlan_orderBy=desc sortBy=Name (1)
localhost_9000_k8s_all-namespaces_operators coreos com_v1alpha1_InstallPlan_orderBy=desc sortBy=Name (2)
localhost_9000_k8s_all-namespaces_operators coreos com_v1alpha1_InstallPlan_orderBy=desc sortBy=Name (3)
localhost_9000_k8s_all-namespaces_operators coreos com_v1alpha1_InstallPlan_orderBy=desc sortBy=Name (4)
localhost_9000_k8s_ns_openshift-operators_operators coreos com_v1alpha1_InstallPlan_install-gkhn9_components
localhost_9000_k8s_ns_openshift-operators_operators coreos com_v1alpha1_InstallPlan_install-gkhn9_components(PFSM)
localhost_9000_k8s_ns_openshift-operators_operators coreos com_v1alpha1_InstallPlan_install-gkhn9_components(PFMD)
localhost_9000_k8s_ns_openshift-operators_operators coreos com_v1alpha1_InstallPlan_install-gkhn9_components(PFLG)
localhost_9000_k8s_ns_openshift-operators_operators coreos com_v1alpha1_InstallPlan_install-gkhn9_components(PFXL)
localhost_9000_k8s_ns_tony_operators coreos com_v1alpha1_ClusterServiceVersion_couchbase-operator v1 2 1_couchbase com_v1_CouchbaseCluster_orderBy=desc sortBy=Name(PFXS)
localhost_9000_k8s_ns_tony_operators coreos com_v1alpha1_ClusterServiceVersion_couchbase-operator v1 2 1_couchbase com_v1_CouchbaseCluster_orderBy=desc sortBy=Name(PFSM)
localhost_9000_k8s_ns_tony_operators coreos com_v1alpha1_ClusterServiceVersion_couchbase-operator v1 2 1_couchbase com_v1_CouchbaseCluster_orderBy=desc sortBy=Name(PFMD)
localhost_9000_k8s_ns_tony_operators coreos com_v1alpha1_ClusterServiceVersion_couchbase-operator v1 2 1_couchbase com_v1_CouchbaseCluster_orderBy=desc sortBy=Name(PFLG)
localhost_9000_k8s_ns_tony_operators coreos com_v1alpha1_ClusterServiceVersion_couchbase-operator v1 2 1_couchbase com_v1_CouchbaseCluster_orderBy=desc sortBy=Name(PFXL)
localhost_9000_k8s_ns_tony_operators coreos com_v1alpha1_ClusterServiceVersion_couchbase-operator v1 2 1_couchbase com_v1_CouchbaseCluster_orderBy=desc sortBy=Name(PF2XL)
localhost_9000_k8s_ns_tony_operators coreos com_v1alpha1_ClusterServiceVersion_orderBy=asc sortBy=Name
localhost_9000_k8s_ns_tony_operators coreos com_v1alpha1_ClusterServiceVersion_orderBy=asc sortBy=Name (1)
localhost_9000_k8s_ns_tony_operators coreos com_v1alpha1_ClusterServiceVersion_orderBy=asc sortBy=Name (2)
localhost_9000_k8s_ns_tony_operators coreos com_v1alpha1_ClusterServiceVersion_orderBy=asc sortBy=Name (3)
localhost_9000_k8s_ns_tony_operators coreos com_v1alpha1_ClusterServiceVersion_orderBy=asc sortBy=Name (4)

### CODE REVIEW

**Comment by bmignano** [comment]
Overall, looks good to me! Curious where the status icon for Created came from – do we use that anywhere else?

**Comment by rhamilto** [comment]
/hold

> Overall, looks good to me! Curious where the status icon for Created came from – do we use that anywhere else?

Good catch.  No, we do not.  Lemme fix.

**Comment by rhamilto** [comment]
Updated Install Plan Status Completed icon to green checkmark so we're consistent with other Completed statuses. 

localhost_9000_k8s_ns_openshift-operators_operators coreos com_v1alpha1_InstallPlan_install-gkhn9_components(4  PFLG)

@spadgett, please re-tag.

**Pull request merged**
