### PR TITLE
update event source icons

### PR DESCRIPTION
**Pull request by nemesis09**
Tracked by:
https://issues.redhat.com/browse/ODC-4354

Solution Description:
Update icons for Event Sources as per new UXD

Screens:

Screenshot from 2020-07-30 20-47-33

Screenshot from 2020-07-30 20-09-47

Screenshot from 2020-07-30 21-07-37

Test Coverage:
No new/updated tests

Browser Conformation:
- [x] Firefox
- [ ] Chrome
- [ ] Safari
- [ ] Edge

Additional Info:
[UXD](https://docs.google.com/document/d/1x9UHIVz9ubFYWg-H_Rgxq9YDghC9hHTdPek1-cxVsxQ/edit)

### CODE REVIEW

**Comment by nemesis09** [comment]
cc @openshift/team-devconsole-ux

**Comment by invincibleJai** [comment]
looks good to me !! @beaumorley needed your approval

**Comment by beaumorley** [comment]
This looks great.

One question @invincibleJai. Is Ping Source being removed? We did not create a new icon for Ping Source because we thought is was going away. If we are unsure when, I can create something temporary so it is not the same icon as Cron Job Source. LMK.

Thank you.

cc
@markito @serenamarie125

**Comment by invincibleJai** [comment]
> This looks great.
> 
> One question @invincibleJai. Is Ping Source being removed? We did not create a new icon for Ping Source because we thought is was going away. If we are unsure when, I can create something temporary so it is not the same icon as Cron Job Source. LMK.
> 
> Thank you.
> 
> cc
> @markito @serenamarie125

Actually CronJob is deprecated but it's still there in Serverless operator so we show it, PingSource will be there

**Comment by serenamarie125** [comment]
Great improvements here, great job everyone!!

**Pull request merged**
