### PR TITLE
Bug 1882653:  Convey automatic subscriptions in same namespace as a m…

### PR DESCRIPTION
**Pull request by rhamilto**
…anual will function as manual

Screen Shot 2020-10-30 at 10 14 22 AM
Screen Shot 2020-10-30 at 10 14 50 AM
Screen Shot 2020-10-30 at 10 16 45 AM
Screen Shot 2020-10-30 at 10 18 08 AM
Screen Shot 2020-10-30 at 10 18 17 AM
Screen Shot 2020-10-30 at 10 18 39 AM
Screen Shot 2020-10-30 at 10 18 46 AM

### CODE REVIEW

**Comment by rhamilto** [comment]
@TheRealJon, this will conflict with your i18n story, but I did go ahead and i18n the new bits I'm adding.

**Comment by itsptk** [comment]
I love this thing. Looks great Robb, thanks.
cc @tlwu2013

**Review by spadgett — APPROVED** [review]
/lgtm

👍

**Pull request merged**
