### PR TITLE
[release-4.13] OCPBUGS-15410: Add Git Repository (PAC) doesn't setup GitLab and Bitbucket configuration correct

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
Manual cherry-pick PR for https://github.com/openshift/console/pull/12593

**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-15410

**Analysis / Root cause:**
Git provider URL was added for all git providers except github. Removed for Bitbucket and Gitlab providers.

**Solution Description:**
1) Removed git provider URL for Bitbucket and Gitlab providers
2) Added Bitbucket username input field if the provider is Bitbucket and it is mandatory
3) Removed Webhook secret for Bitbucket 
4) Made Git Access token or Git access token secret as mandatory. Either of the one should be present.

**Screen shots / Gifs for design review:**

-------GitLab-----
Screenshot 2023-02-22 at 8 43 57 PM

-------GitHub----
Screenshot 2023-02-22 at 8 34 27 PM

-----Bitbucket----
Screenshot 2023-02-22 at 8 45 43 PM

-----PipelineRuns-----
Screenshot 2023-02-22 at 8 54 01 PM

****Unit test coverage report:****
NA

**Test setup:**

1. Install OpenShift Pipelines operator
2. Navigate to Developer perspective > Pipelines
3. Select Create > Repository
4. Enter a GitLab based git repository with Git access token and Webhook secret
5. Enter a Bitbucket based git repository with Git access token (webhook secret isn't supported)

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by jerolimov** [comment]
/retitle [release-4.13] OCPBUGS-15410: Add Git Repository (PAC) doesn't setup GitLab and Bitbucket configuration correct

**Review by jerolimov — APPROVED** [review]
/label backport-risk-assessed
/approve

**Review by vikram-raj — COMMENTED** [review]
Verified it on the cluster bot and it works as expected.

image


/lgtm

**Pull request merged**
