### PR TITLE
Monitoring: Clean up imports and types

### PR DESCRIPTION
**Pull request by kyoto**
This PR has a few refactoring changes that are both for the sake of general clean up and also begin moving the code to run more like a dynamic plugin.

- Add type definitions for table pagination 
- Rename `paginationOptions` to `perPageOptions` to match the name used by PatternFly
- Tighten up `PrometheusAPIError` type definition (the fields of `APIError` are not all found in `PrometheusAPIError`)
- Import components and types from `dynamic-plugin-sdk` whenever possible. This is preferable because it brings us closer to having the monitoring pages run as a plugin.
- Limit comment line length to 100 characters
- Change classNames import syntax to avoid TypeScript error

### CODE REVIEW

**Comment by kyoto** [comment]
This is a refactoring change. There should be no user visible changes.

/label px-approved
/label docs-approved

**Review by spadgett — APPROVED** [review]
LGTM, but it looks like you have some linter errors.

**Comment by spadgett** [comment]
Hey, @kyoto sorry for missing the update. It looks like there is a unit test failure where `AlertSeverity` is undefined here...

https://github.com/openshift/console/blob/master/frontend/public/components/notification-drawer.tsx#L81

**Comment by kyoto** [comment]
@spadgett Fixed the failing tests. Could you please take another look?

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by Tai-RedHat** [comment]
Use cluster-bot test the PR, no regression issues
/label qe-approved

**Pull request merged**
