### PR TITLE
Bug 1951169: Change "Explore" to "API Explorer"

### PR DESCRIPTION
**Pull request by rhamilto**
Screen Shot 2021-04-16 at 11 26 17 AM

### CODE REVIEW

**Comment by rhamilto** [comment]
@alimobrem is going to create a bug for tracking.

**Comment by rhamilto** [comment]
@spadgett, PTAL.  See https://coreos.slack.com/archives/C6A3NV5J9/p1619191324274700

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
