### PR TITLE
OCPBUGS-18401: fix filtering issues on Events

### PR DESCRIPTION
**Pull request by rhamilto**
In addition to the text filter not working, this PR also addresses:

- [x] open websockets do not get closed when changing project or resource filter
- [x] the type filter does not work
- [x] pausing the stream does not work

After:

https://github.com/openshift/console/assets/895728/b0ec0cc1-0439-4640-b886-d4e894449ad8

### CODE REVIEW

**Comment by sg00dwin** [comment]
Local testing found the text filter, type filter, and resources filter are functioning properly.

One behavior I did find is regarding when the Event stream is paused. If a resource is either added or removed, it triggers the event stream to become un paused.

**Review by TheRealJon — APPROVED** [review]
If this fixes the bug, we should go ahead and commit it, but this component still has some problematic patterns we need to address at some point.

/lgtm

**Comment by rhamilto** [comment]
> Also could we create a follow-on story or another PR attached to this bug that adds at least a basic e2e test for the events page?

Agreed.  We do have [a very basic test](https://github.com/openshift/console/blob/master/frontend/packages/integration-tests-cypress/tests/events/events.cy.ts). But I punted on adding to it since it will require figuring out how to generate additional events in order to test the filters and figured it was more important to get the fix in and backported first.

**Comment by rhamilto** [comment]
> > Also could we create a follow-on story or another PR attached to this bug that adds at least a basic e2e test for the events page?
> 
> Agreed. We do have [a very basic test](https://github.com/openshift/console/blob/master/frontend/packages/integration-tests-cypress/tests/events/events.cy.ts). But I punted on adding to it since it will require figuring out how to generate additional events in order to test the filters and figured it was more important to get the fix in and backported first.

Determined I think we can safely update the existing Events test to also cover the type and text filters. Still thinking about how to test the resource filter and pause.  https://github.com/openshift/console/pull/13407

**Pull request merged**
