### PR TITLE
Bug 2096392: [Dark Theme]: Add white background to node icons in Topology in dark mode

### PR DESCRIPTION
**Pull request by vikram-raj**
**Fixes:** https://bugzilla.redhat.com/show_bug.cgi?id=2096392

**Screenshots:**
### **Before**
image (5)

### **After**
image (6)

### CODE REVIEW

**Review by jerolimov — COMMENTED** [review]
@vikram-raj Isn't it possible to fill the forms completely? Wouldn't this look better? :thinking:

**Comment by vikram-raj** [comment]
> @vikram-raj Isn't it possible to fill the forms completely? Wouldn't this look better? 🤔

@jerolimov  Do you want to make the Node background color white completely?

**Comment by jerolimov** [comment]
> > @vikram-raj Isn't it possible to fill the forms completely? Wouldn't this look better? thinking
> 
> @jerolimov Do you want to make the Node background color white completely?

Yes, this is your BaseNode rectangle version:

updated

I would recommend to fill the PodState circle (and keep a small transparent border) like this

image77

IMHO we should also fill the other shapes (connections etc.) IF they render a logo. If we can invert an icon, we should just apply a (invert) filter.

/cc @serenamarie125 @beaumorley
wdyt?

**Comment by vikram-raj** [comment]
@jerolimov Updated the PR as per your suggestion.
image

**Review by jerolimov — APPROVED** [review]
Looks good too me :+1: 

/lgtm
/approve

**Review by jerolimov — COMMENTED** [review]
/lgtm

**Pull request merged**
