### PR TITLE
Bug 1821846: Hide `OpenShift Cluster Manager` when branding is `azure`

### PR DESCRIPTION
**Pull request by nilsanderselde**
Fixes https://github.com/Azure/ARO-RP/issues/298.

Needs to be backported to `release-4.3`.

### CODE REVIEW

**Comment by jim-minter** [comment]
@spadgett bump, please could you take a look at this?  Please could you help us get this backported to release-4.3?  Please advise @nilsanderselde what he needs to do.

**Comment by nilsanderselde** [comment]
4.5: https://bugzilla.redhat.com/show_bug.cgi?id=1821846
4.4: https://bugzilla.redhat.com/show_bug.cgi?id=1821849
4.3.0: https://bugzilla.redhat.com/show_bug.cgi?id=1821850
4.3.z: https://bugzilla.redhat.com/show_bug.cgi?id=1821852

**Pull request merged**
