### PR TITLE
Bug 1948556: Add check if model is defined to prevent RTE

### PR DESCRIPTION
**Pull request by zherman0**
Unknown model types cause a run time error when getReferenceForModel is called.  I removed the call for getReferenceForModel since it was deprecated and used the properties to get the information needed.  This prevents the model from being undefined.

Before:
tackle-blows-up

After:
tackle-fixed

### CODE REVIEW

**Review by TheRealJon — COMMENTED** [review]
It looks like we would end up returning `core~undefined~undefined` if `model` is undefined. Is this what we would want?

**Comment by rhamilto** [comment]
I poked at this a little bit yesterday and agree with Jon the fix proposed here is not the right one.  Without a valid model, [a valid watch cannot be opened and the access review cannot occur](https://github.com/openshift/console/blob/abf86548e15219d033c27df85219fa4032301637/frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx#L886-L899).  `modelFor` should not be used [here](https://github.com/openshift/console/blob/abf86548e15219d033c27df85219fa4032301637/frontend/packages/operator-lifecycle-manager/src/components/clusterserviceversion.tsx#L883) per https://github.com/openshift/console/blob/abf86548e15219d033c27df85219fa4032301637/frontend/public/module/k8s/k8s-models.ts#L57-L60?

**Comment by zherman0** [comment]
@rhamilto @TheRealJon - I completely changed the logic of this to not  call getReferenceForModel which was failing because the model was undefined.  I now use the property value from the Custom Resource and no longer need to look at the model.  Please take another look.

**Comment by rhamilto** [comment]
LGTM, but will let @TheRealJon give the final approval.

**Review by TheRealJon — COMMENTED** [review]
**Accidentally submitted before I was done. Review in progress.**

**Review by TheRealJon — COMMENTED** [review]
A couple of things. I think the `kind` property passed into `useK8sWatchResource` needs to be a full `group~version~kind` string and we still need to move away from using `modelFor`, especially when dealing with APIs that an operator installed. Would something like this work?:

```ts
  const initializationResourceKind = initializaationResource.kind;
  const initializationResourceReference = referenceFor(initializationResource);
  const [model] = useK8sModel(initializationResourceReference);

  // Check if the CR is already present - only watches for the model in namespace
  const [customResource, customResourceLoaded] = useK8sWatchResource<K8sResourceCommon[]>({
    kind: initializationResourceReference,
    namespaced: true,
    isList: true,
  });

  const canCreateCustomResource = useAccessReviewAllowed(model ? {
    group: model?.apiGroup,
    resource: model?.plural,
    namespace: model?.namespaced
      ? initializationResource?.metadata.namespace || csv.metadata.namespace
      : null,
    verb: 'create',
  });

```

**Comment by zherman0** [comment]
@TheRealJon - Your suggestions look good and testing looks good, so I have made the changes and updated the PR. PTAL. Thanks.

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Pull request merged**
