### PR TITLE
Modified 'yarn run dev' in package.json to poll for changed files

### PR DESCRIPTION
**Pull request by SamiSousa**
Added the '--watch-poll' flag to poll for changed files for interactive frontend development.

### CODE REVIEW

**Comment by coreos-ui** [comment]
Can one of the admins verify this patch?

**Comment by coreos-ui** [comment]
Can one of the admins verify this patch?

**Comment by SamiSousa** [comment]
I'm running on Fedora 28. Without the `--watch-poll` flag, `yarn run dev` just compiles the files once, and doesn't respond to changes to files.

**Comment by SamiSousa** [comment]
@spadgett That works for me. :)

**Comment by spadgett** [comment]
We should add something to the README under https://github.com/openshift/console#interactive-development

**Pull request closed without merging**
