### PR TITLE
ODC-7680: Migrate `ResultsList` to PF5

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7680

**Solution Description**: 

Migrate ResultsList to PF5

**Screen shots / Gifs for design review**: 

https://github.com/user-attachments/assets/f1b937d7-9cd6-4e7e-96f9-a39ce82cd4a1

**Unit test coverage report**: 

unchanged

**Test setup:**

n/a

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

This pr is 2/? of [ODC-7680](https://issues.redhat.com//browse/ODC-7680) story as each file is being split into a separate PR.

### CODE REVIEW

**Review by lokanandaprabhu — APPROVED** [review]
Tested locally. Working fine.


https://github.com/user-attachments/assets/ec2badc2-95ff-47bb-b6e2-07477736f549

/lgtm

**Comment by logonoff** [comment]
adding labels because this is debt

/label px-approved
/label docs-approved

**Comment by sanketpathak** [comment]
Verified the UI and the tests.
Screenshot from 2024-10-16 17-09-36
/label qe-approved

**Pull request merged**
