### PR TITLE
Temporarily disable broken secret scenario tests

### PR DESCRIPTION
**Pull request by spadgett**
Disable secret scenario which is failing almost every run.

### CODE REVIEW

**Comment by spadgett** [comment]
/assign @jhadvig 

We should debug the secret test. I was hoping #1385 would fix it, but no luck.

I'm upgrading Chrome to try and avoid the OperatorHub crash in #1383

**Comment by jhadvig** [comment]
@spadgett yeah, will take a closer look on what could be the possible cause of the issue. Lets skip these test.
Also I see that the performance tests are failing pretty often.

**Comment by spadgett** [comment]
/hold

We've updated Chrome to the latest version in CI. Previously we were using an older beta version (at the time it was required for `--headless`). Let's see if it fixes OperatorHub tests.

**Comment by jhadvig** [comment]
ok... if anything we can disable all the secret tests temporarily, already looking into it.

**Comment by spadgett** [comment]
/hold

e2e-aws-console passed in #1383. Just want to double-check that this is still needed after that merges.

**Comment by spadgett** [comment]
/hold cancel

Secret tests are still failing (just not every run)

**Pull request merged**
