### PR TITLE
Bug 1909207: Fix accessibility issues on monitoring page

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**Fixes**: 
https://issues.redhat.com/browse/ODC-5206

**Analysis / Root cause**: 
Dropdowns do not have aria-labels or labels set for them

**Solution Description**: 
Add aria-label to ResourceDropdown, add htmlFor to labels for options dropdowns.

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

/kind bug

### CODE REVIEW

**Review by dtaylor113 — APPROVED** [review]
/lgtm

**Review by dtaylor113 — APPROVED** [review]
/lgtm

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
