### PR TITLE
ODC-7279: Correcting CI failures of ODC Packages

### PR DESCRIPTION
**Pull request by hemantsaini-7**
Epic: [ODC-7279](https://issues.redhat.com/browse/ODC-7279)

Knative: 

- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/12704/pull-ci-openshift-console-master-e2e-gcp-console/1643253453482364928
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/12683/pull-ci-openshift-console-master-e2e-gcp-console/1640729080988962816
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/12697/pull-ci-openshift-console-master-e2e-gcp-console/1642023676993867776

Pipelines:

- Entire pipeline flow from Builder page Add secret to pipeline with authentication type as Basic Authentication
- Entire pipeline flow from Builder page Delete the Pipeline Run

Dev-Console:

- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/12678/pull-ci-openshift-console-master-e2e-gcp-console/1643263038301671424

### CODE REVIEW

**Comment by hemantsaini-7** [comment]
bugzilla/valid-bug

**Comment by jerolimov** [comment]
/retitle ODC-7279: Correcting CI failures of ODC Packages

**Pull request merged**
