### PR TITLE
Add form to configure HTPasswd IDP

### PR DESCRIPTION
**Pull request by spadgett**
https://jira.coreos.com/browse/CONSOLE-1276

screen shot 2019-02-28 at 4 10 57 pm

screen shot 2019-03-01 at 8 31 40 am

cc @enj @openshift/team-ux-review

### CODE REVIEW

**Comment by beanh66** [comment]
LGTM @spadgett. Can we add a link out to the IDP documentation at the end of the grey instruction text?

**Comment by bmignano** [comment]
This looks good to me too! Minor nit, wondering if we should have the page title and primary action button match, so making them both either "Add" or "Create".

**Comment by spadgett** [comment]
> LGTM @spadgett. Can we add a link out to the IDP documentation at the end of the grey instruction text?

Yes, when it's available. I don't think there's a topic yet. (I put a TODO in the code for that.)

**Comment by spadgett** [comment]
> This looks good to me too! Minor nit, wondering if we should have the page title and primary action button match, so making them both either "Add" or "Create".

Thanks, I changed the button to "Add"

**Comment by rhamilto** [comment]
Did you intend to be adding 34 commits?

**Comment by spadgett** [comment]
> Did you intend to be adding 34 commits?

Oops, forgot to switch the branch back to master. Should be fixed now :)

**Pull request merged**
