### PR TITLE
Update Kubernetes Models for OLM 

### PR DESCRIPTION
**Pull request by alecmerdler**
### Description

Updates API group to `operators.coreos.com` and removes `-v1` suffix on CRDs in favor of official versioning. See [corresponding OLM pull request](https://github.com/operator-framework/operator-lifecycle-manager/pull/398).

Fixes https://jira.coreos.com/browse/ALM-673

### CODE REVIEW

**Comment by alecmerdler** [comment]
jenkins push

**Comment by coreos-ui** [comment]
The PR image has been pushed to Quay with tag `pr_359_build_409`

**Comment by alecmerdler** [comment]
@spadgett `GUI-Tests-OLM` pass locally.

**Comment by spadgett** [comment]
Great, we're working on switching to the OpenShift cluster in our CI now

**Pull request merged**
