### PR TITLE
Fixed issue: Not able to select access modes for snapshot and clone

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Bugzilla Id: https://bugzilla.redhat.com/show_bug.cgi?id=1882057

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@localhost.localdomain>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
x-special/nautilus-clipboard
copy
file:///home/gshanmug/Pictures/pvc_clone.png



x-special/nautilus-clipboard
copy
file:///home/gshanmug/Pictures/restore_snapshot.png

**Comment by GowthamShanmugam** [comment]
pvc_clone_page
restore_snapshot

**Comment by GowthamShanmugam** [comment]
@cloudbehl @afreen23 @bipuladh  Changes are done, please review

**Comment by cloudbehl** [comment]
@rawagner can you please review it once.

**Pull request merged**
