### PR TITLE
[release-4.8] Bug 1972788: Convert probe data values from string to number type

### PR DESCRIPTION
**Pull request by debsmita1**
Manual cherry-pick of https://github.com/openshift/console/pull/9237

Peek 2021-06-23 13-37

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Tested this PR also and it works as expected.

With the exception of the imports, this PR is also completely identical to the original PR.

/lgtm
/approve

**Comment by jerolimov** [comment]
Tested the latest bugfix and now it is possible to check/uncheck the HTTPS checkbox again. Thanks for the additional tests. :+1: 

* master works thanks to #9300
* release-4.8, release-4.7 and release-4.6 branches are broken
* with this PR it works again

As https://issues.redhat.com/browse/ODC-6015 is marked as high we maybe should backport this as well.

/lgtm
/retest

**Comment by sdodson** [comment]
Re-validating bugzilla status after prow config updates.
/bugzilla refresh

**Pull request merged**
