### PR TITLE
Bug 2028885: Add a message to all console errors which just logs an error object

### PR DESCRIPTION
**Pull request by jerolimov**
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2028885

**Analysis / Root cause**: 
Errors which just logs an error are sometimes hard to understand.

For example, error

> Forbidden

Which component? Which API call?

**Solution Description**: 
Add a fix message (first parameter of console.warn and console.error) to all code areas I could find with `console.[a-z]+\(e` (as regex)

**Screen shots / Gifs for design review**: 
UI is not affected. If everything works fine nothing should be changed. If something breaks this should just show more info in the browser console.

**Unit test coverage report**: 
Not changed

**Test setup:**
Double-check the code changes.

**Browser conformance**: 
Not relevant

### CODE REVIEW

**Comment by jerolimov** [comment]
/test e2e-gcp
test e2e-gcp-console

**Comment by jerolimov** [comment]
/cc @rottencandy 
/hold
wait for triage meeting

**Comment by andrewballantyne** [comment]
cc @kdoberst @spadgett

**Review by rottencandy — APPROVED** [review]
Thanks! Changes look good to me.

**Comment by jerolimov** [comment]
> cc @kdoberst @spadgett

Any objections against "an individual log message" if we log errors?

**Comment by kdoberst** [comment]
> > cc @kdoberst @spadgett
> 
> Any objections against "an individual log message" if we log errors?

Looks good to me.

**Review by rottencandy — APPROVED** [review]
/lgtm

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Pull request merged**
