### PR TITLE
contribute actions , sidepanel for channel, subscription, broker and trigger

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes**: 
https://issues.redhat.com/browse/ODC-6345

**Solution Description**: 

- contribute actions for channel, subscription, broker and trigger
- contribute side panel for channel, subscription, broker and trigger

**Screen shots / Gifs for design review**: 

No visual changes

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by sahil143 — COMMENTED** [review]
@invincibleJai EditApplicationGrouping is missing from sidepanel actions

**Comment by sahil143** [comment]
getting these i18n error on console

image

**Comment by invincibleJai** [comment]
> @invincibleJai EditApplicationGrouping is missing from sidepanel actions

updated.

**Review by sahil143 — APPROVED** [review]
/lgtm
/label qe-approved

verified locally and works as expected

**Comment by invincibleJai** [comment]
Propagate from epic:
/label docs-approved
/label px-approved

**Pull request merged**
