### PR TITLE
Bug 2069760: Added divider to developer console navigation

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2069760

**Analysis / Root cause**: 
It is due to changes in patternfly. We are using NavGroup component from patternfly. In the latest update, the title field they made it mandatory. 

--before-----
```
<h2 className={css(styles.navSectionTitle)} id={id}>
      {title}
 </h2>
```

---Now-----
```
{title && (
        <h2 className={css(styles.navSectionTitle)} id={id}>
          {title}
        </h2>
      )} 
```

We are passing null to title. Before if title is null also we used to get the divider but now since title is null, h2 was not getting rendered.

**Solution Description**: 
Modified below style for section class

```
.pf-c-nav__section.no-title {
    border-bottom: 1px solid var(--pf-global--BackgroundColor--dark-200);
    padding-bottom: var(--pf-global--spacer--sm);
    --pf-c-nav__section--MarginTop: 0;
    .pf-c-nav__section-title {
      --pf-c-nav__section-title--PaddingBottom: 0;
    }
    &:last-child {
      border: none;
    }
  }
```
File Name: frontend/public/components/nav/_perspective-nav.scss

**Screen shots / Gifs for design review**: 
----Before change-----
image

---After changes-----
image

**Unit test coverage report**: 
NA

**Test setup:**
-Login to ODC
-Navigate to Developer menu

**Browser conformance**: 
- [ x ] Chrome
- [ x ] Firefox
- [ x ] Safari

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
In 4.10, the Pinned navigation item doesn't have border at the end. 
image

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
