### PR TITLE
CNV-35417, OCPBUGS-28702: Remove empty annotation from nad

### PR DESCRIPTION
**Pull request by metalice**
In case of empty/lacking annotation - dont add it to nad

### CODE REVIEW

**Review by avivtur — APPROVED** [review]

**Comment by jhadvig** [comment]
@metalice do we need to backport to 4.15 ?

**Comment by gouyang** [comment]
@jhadvig it's better if we can backport this to 4.15.

**Comment by gouyang** [comment]
@jhadvig @metalice  is there any chance for us to merge this to 4.16?

**Comment by logonoff** [comment]
/retitle CNV-35417, OCPBUGS-28702: Remove empty annotation from nad

**Pull request merged**
