### PR TITLE
[release-4.8] Bug 2020162: PVC is deleted along with VM even with "Delete Disks" unchecked

### PR DESCRIPTION
**Pull request by avivtur**
Manual backport to: 
https://github.com/openshift/console/pull/10391

Fixing:
https://bugzilla.redhat.com/show_bug.cgi?id=2020162

/assign @yaacov 

Signed-off-by: Aviv Turgeman <aturgema@redhat.com>

### CODE REVIEW

**Comment by yaacov** [comment]
/lgtm
/label backport-risk-assesse
/retitle [release-4.8] Bug 2020162: PVC is deleted along with VM even with "Delete Disks" unchecked

**Comment by avivtur** [comment]
/retitle [release-4.8] Bug 2020162: PVC is deleted along with VM even with "Delete Disks" unchecked

**Comment by yaacov** [comment]
@yapei @gouyang for cherry-pick review

**Pull request merged**
