### PR TITLE
Bug 1967667: Update translations for Sprint 202 (first half)

### PR DESCRIPTION
**Pull request by rebeccaalpert**
Adding latest translations from Memsource project https://cloud.memsource.com/web/project2/show/tWkkpXPi0IMQeaE2kBluY4.

I didn't see any new issues, so yay!

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1967667.

### CODE REVIEW

**Comment by rebeccaalpert** [comment]
This is blocked by the other translation PR.

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
@rebeccaalpert Looks like you need to rebase now that #9104 merged... Does #9223 supersede this?

**Comment by rebeccaalpert** [comment]
Rebased.

**Comment by rebeccaalpert** [comment]
We are no longer blocked since the other translation PR merged.

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
