### PR TITLE
Fix displayed token max age on OAuth details page

### PR DESCRIPTION
**Pull request by spadgett**
The value was not calculated correctly. Also remove property
authorizeTokenMaxAgeSeconds, which is no longer in the config.

/cc @rhamilto @TheRealJon 
@enj

### CODE REVIEW

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by enj** [comment]
LGTM, at some point you will want to add support for the inactivity timeout field as well.

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
