### PR TITLE
Bug 2080260: Update OLM pages to use details and list page extensions for operands when they exist

### PR DESCRIPTION
**Pull request by TheRealJon**
- Update the CSV details page to load and render list and details page extensions for the operands it manages
- Remove container security route extensions that collide with olm create-operand routes

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
Nicely done @TheRealJon 👍 

/lgtm
/approve

**Comment by jhadvig** [comment]
```
Failed Specs:

1) CRD extensions ConsoleExternalLogLink CRD : creates a new test pod to display the ConsoleExternalLogLink instance
   Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       at listOnTimeout internal/timers.js:554:17
       at processTimers internal/timers.js:497:7
   
   Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       at listOnTimeout internal/timers.js:554:17
       at processTimers internal/timers.js:497:7
   
   Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
       at listOnTimeout internal/timers.js:554:17
       at processTimers internal/timers.js:497:7
```

/retest

**Comment by TheRealJon** [comment]
/retest

Cluster install failed

**Comment by TheRealJon** [comment]
/hold cancel

Tests were failing due to a change outside this PR. See https://github.com/openshift/console/pull/11894

**Comment by TheRealJon** [comment]
/hold

This is a legit CI failure. There's a RTE encountered during the global operator installation test.

**Comment by TheRealJon** [comment]
/hold cancel

Found the issue and fixed it and also refactored my solution to simplify it a bit.

**Comment by jhadvig** [comment]
@TheRealJon the tests are failing with

frontend:
```
OperandDetailsPage › renders a `DetailsPage` with the correct subpages
    Method “props” is meant to be run on 1 node. 0 found instead.
      
      at ReactWrapper.single (node_modules/enzyme/src/ReactWrapper.js:1166:13)
      at ReactWrapper.props (node_modules/enzyme/src/ReactWrapper.js:710:17)
      at Object.<anonymous> (packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx:391:24)
          at new Promise (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
  ● OperandDetailsPage › renders a `DetailsPage` which also watches the parent CSV
    Method “props” is meant to be run on 1 node. 0 found instead.
      
      at ReactWrapper.single (node_modules/enzyme/src/ReactWrapper.js:1166:13)
      at ReactWrapper.props (node_modules/enzyme/src/ReactWrapper.js:710:17)
      at ReactWrapper.prop (node_modules/enzyme/src/ReactWrapper.js:827:17)
      at Object.<anonymous> (packages/operator-lifecycle-manager/src/components/operand/index.spec.tsx:400:38)
          at new Promise (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
....
```


console:
```
2 failing
  1) Globally installing "Service Binding Operator" operator in openshift-operators
       Globally installs Service Binding Operator operator in openshift-operators and creates ServiceBinding operand:
     AssertionError: Timed out retrying after 30000ms: Expected to find element: `[data-test="msg-box-title"]`, but never found it.
      at Object.createOperand (https://console-openshift-console.apps.ci-op-q2hl16kt-75d12.xxxxxxxxxxxxxxxxxxxxxx/__cypress/tests?p=tests/operator-install-global.spec.ts:14235:38)
      at Context.eval (https://console-openshift-console.apps.ci-op-q2hl16kt-75d12.xxxxxxxxxxxxxxxxxxxxxx/__cypress/tests?p=tests/operator-install-global.spec.ts:14112:71)
  2) Globally installing "Service Binding Operator" operator in openshift-operators
       "after all" hook for "Globally installs Service Binding Operator operator in openshift-operators and creates ServiceBinding operand":
     CypressError: You attempted to make a chai-jQuery assertion on an object that is neither a DOM object or a jQuery object.
...
```

**Review by jhadvig — APPROVED** [review]
/lgtm

**Pull request merged**
