### PR TITLE
Bug 2035321: chore(i18n): update translations

### PR DESCRIPTION
**Pull request by rebeccaalpert**
Adding latest translations from Memsource project https://cloud.memsource.com/web/project2/show/TI2cYf0HQHTknWSX2UeFn6

Related bugs:
* https://bugzilla.redhat.com/show_bug.cgi?id=2035323 (AppliedClusterResourceQuota translations looked off sometimes)
* https://bugzilla.redhat.com/show_bug.cgi?id=2035348 (Kubevirt grammar)

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2035321.

### CODE REVIEW

**Review by sg00dwin — APPROVED** [review]
/lgtm

**Review by spadgett — APPROVED** [review]
/approve

**Pull request merged**
