### PR TITLE
Bug 1942641: Fix build related i18n misses

### PR DESCRIPTION
**Pull request by TheRealJon**
Below is the summary of the research I did on the screenshots in the original bug. A few of them were actual missed externalized strings or resource kinds that weren't in PascalCase, but for the most part, we are just missing translations for these, or the translations are in English.
___

### **BuildConfig list page**
- **FIX**: Update "Build Configs" heading to "BuildConfigs" which should have a translation defined.
- Missing translations for interpolated empty state: "No {{label}} found" **(not fixed by this PR)**
- Missing translations for interpolated create action: "Create {{objLabel}}" **(not fixed by this PR)**

Screenshot from 2021-03-24 21-32-46

___

### **Create BuildConfig Page Heading**
- Missing all translations for interpolated create action: "Create {{objLabel}}" **(not fixed by this PR)**
Screenshot from 2021-03-24 21-33-01

___

### **BuildConfig Details Page**
- **FIX**: Update "Build Config details" to "BuildConfig details"
- **FIX**: Externalize strings in Webhooks section
- Missing translations for interpolated string "{{kindLabel}} details" **(not fixed by this PR)**
- Chinese translation for "Context dir" is in English (not a bug)

Screenshot from 2021-03-24 21-34-12

___

### **BuildConfig details > Builds list page**
- **Fix**: Externalize "Status" filter category
Screenshot from 2021-03-24 21-35-07

___

### **Builds list page**
- Missing translations for interpolated empty state: "No {{label}} found" **(not fixed by this PR)**
Screenshot from 2021-03-24 21-35-52
___

### **Build details page**
- Missing translations for interpolated string "{{kindLabel}} details" **(not fixed by this PR)**
- Chinese translation for "Git commit" and "Context dir" are in English (not a bug)
Screenshot from 2021-03-24 21-38-32

___

### **ImageStreams list page**
- Missing translations for interpolated empty state: "No {{label}} found" **(not fixed by this PR)**
- Missing translations for interpolated create action: "Create {{objLabel}}" **(not fixed by this PR)**
Screenshot from 2021-03-24 21-38-55
___

### **ImageStreams creation page**
- Missing translations for interpolated create action: "Create {{objLabel}}" **(not fixed by this PR)**
Screenshot from 2021-03-24 21-39-07

___

### **ImageStream details page**
- Missing translations for interpolated string "{{kindLabel}} details" **(not fixed by this PR)**
Screenshot from 2021-03-24 21-40-01

cc @rebeccaalpert

### CODE REVIEW

**Comment by rebeccaalpert** [comment]
Thanks, the missing translations aren't something you should be fixing. We'll get those in the next round. :) 

Did you take a look at the BuildConfig Details Page Webhooks section? It looks like Krishna highlighted something there.

**Review by rebeccaalpert — APPROVED** [review]
Changes look good to me. Thank you for making these (and going through all the screenshots).

**Comment by spadgett** [comment]
This might conflict with #8469

@debsmita1 FYI

**Review by spadgett — APPROVED** [review]
/lgtm

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
