### PR TITLE
[release-4.9] OCPBUGS-2576, OCPBUGS-2719: Fix backend test (devfile registry change), fix console e2e test (3scale operator name change)

### PR DESCRIPTION
**Pull request by jerolimov**
Manual backport of #12194 and rebased on top of #12188 because both PR are in a deadlock. This fixes a backend test issue, the other one a console e2e issue.

Just a small merge conflict in sample.go, the test merges automatically.

4.12: https://issues.redhat.com/browse/OCPBUGS-1678 / #12088
4.11: https://issues.redhat.com/browse/OCPBUGS-2014 / #12137
4.10: https://issues.redhat.com/browse/OCPBUGS-2622 / #12194
4.9: https://issues.redhat.com/browse/OCPBUGS-2719 / this PR

/kind bug
/cc @jhadvig @sanketpathak

### CODE REVIEW

**Comment by jerolimov** [comment]
/retitle [release-4.9] OCPBUGS-2576, OCPBUGS-2719: Fix backend test (devfile registry change), fix console e2e test (3scale operator name change)

**Review by jhadvig — APPROVED** [review]
/approve

**Comment by yapei** [comment]
```
    ✓ Installs Red Hat Integration - 3scale - Managed Application Services operator in test-zspop and creates 3scale Backend Schema operand instance (149366ms)
```

```
=== RUN   TestGetRegistrySamples
=== RUN   TestGetRegistrySamples/Fetch_samples_from_mock_registry_server
=== RUN   TestGetRegistrySamples/Invalid_registry
--- PASS: TestGetRegistrySamples (0.00s)
    --- PASS: TestGetRegistrySamples/Fetch_samples_from_mock_registry_server (0.00s)
    --- PASS: TestGetRegistrySamples/Invalid_registry (0.00s)
PASS
coverage: 85.7% of statements
ok  	github.com/openshift/console/pkg/devfile	0.012s	coverage: 85.7% of statements
?   	github.com/openshift/console/pkg/graphql/resolver	[no test files]
```
both backend test and e2e test pass in CI
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
