### PR TITLE
Bug 2117642: Backport CI test fix to relase 4.10

### PR DESCRIPTION
**Pull request by zherman0**
Fix CI bug in the creates namespace test suite.  This is a partial backport of https://github.com/openshift/console/pull/11809.

@spadgett

### CODE REVIEW

**Comment by invincibleJai** [comment]
@zherman0 e2e looks good but I see link issue 

https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/11966/pull-ci-openshift-console-release-4.10-frontend/1560332294625955840

```
{  yarn run v1.22.15
$ NODE_OPTIONS=--max-old-space-size=4096 yarn eslint .
$ eslint --ext .js,.jsx,.ts,.tsx,.json,.gql,.graphql --color .
�[0m�[0m
�[0m�[4m/go/src/github.com/openshift/console/frontend/packages/operator-lifecycle-manager/integration-tests-cypress/tests/create-namespace.spec.ts�[24m�[0m
�[0m  �[2m39:1�[22m  �[31merror�[39m  Delete `····`  �[2mprettier/prettier�[22m�[0m
�[0m�[0m
�[0m�[31m�[1m✖ 1 problem (1 error, 0 warnings)�[22m�[39m�[0m
�[0m�[31m�[1m�[22m�[39m�[31m�[1m  1 error and 0 warnings potentially fixable with the `--fix` option.�[22m�[39m�[0m
�[0m�[31m�[1m�[22m�[39m�[0m
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2022-08-18T19:17:30Z"}
}
```

**Review by spadgett — APPROVED** [review]
/lgtm
/label backport-risk-assessed

**Comment by yapei** [comment]
```
Running:  create-namespace.spec.ts                                                        (2 of 8)


  Create namespace from install operators
  Logging in as kubeadmin
      create project
      test namespace creation from dropdown
      delete project
      delete project
  Logging out
    ✓ creates namespace from operator install page (52019ms)


  1 passing (1m)
```
/label qe-approved
/label cherry-pick-approved

**Comment by zherman0** [comment]
@spadgett - Do we need to make this work for 4.8 as well?

**Comment by spadgett** [comment]
> @spadgett - Do we need to make this work for 4.8 as well?

Yeah, the 4.8 queue is broken as well :/

**Pull request merged**
