### PR TITLE
enhance(pipeline): Expand the Pipeline Run columns

### PR DESCRIPTION
**Pull request by abhinandan13jan**
Addresses: https://jira.coreos.com/browse/ODC-1511
--------------------------------------------------------------------------
Post-Fix
-------------------------------------------------
Pipeline-List
Screenshot from 2019-08-05 14-08-35

-------------------------------------------------
Pipeline-Run-List
Screenshot from 2019-08-01 17-17-55
-------------------------------------------------

### CODE REVIEW

**Comment by christianvogt** [comment]
@abhinandan13jan your column sizes should add up to `12` for each breakpoint

**Comment by abhinandan13jan** [comment]
> @abhinandan13jan your column sizes should add up to `12` for each breakpoint

updated

**Comment by joshuawilson** [comment]
@abhinandan13jan please add the bug this fixes to the main description. Also please squash the commits.

**Comment by serenamarie125** [comment]
@abhinandan13jan for pipeline, can you make the Name and the Last Run colums the same width?  I also created a bug around left aligning the Task Status widget in the column ... 

Also, the column header should be Task Status in both the PL and PLR listings.  Not sure if you can sneak those fixes in with this PR ? :)

**Comment by serenamarie125** [comment]
@abhinandan13jan also, i think there's a way to add the kebab without it having to be it's own column.  Pinging @jeff-phillips-18 for reference info

**Comment by jeff-phillips-18** [comment]
By using the table component, the kebab must be in its own column. However, it would be better to lose a lot of the padding around the kebab, seems like there is far too much.

**Comment by abhinandan13jan** [comment]
> @abhinandan13jan for pipeline, can you make the Name and the Last Run colums the same width? I also created a bug around left aligning the Task Status widget in the column ...
> 
> Also, the column header should be Task Status in both the PL and PLR listings. Not sure if you can sneak those fixes in with this PR ? :)

`Name` and `Last Run` column are same width now. Made changes to `Task Progress` -> `Task Status`
in https://github.com/openshift/console/pull/2261 . Can you please pass on the Link for left-aligning the `TaskStatus` component in the UI channel/me over slack.

**Pull request merged**
