### PR TITLE
add secondary masthead with disabled dropdowns to add flows

### PR DESCRIPTION
**Pull request by christianvogt**
Fixes: https://jira.coreos.com/browse/ODC-1722

This fix adds the secondary masthead with disabled dropdowns to the add flows. The user cannot change the project while in the form. They also cannot change the application if one has already been selected prior to entering the form. If no application has been selected, the user can select an existing application or create a new one.

Project with no application (app selector is part of form):
_Note: The dropdown is still part of the form. Removing it will require further refactoring and is best to do in a separate PR_
image

Project with applications but none selected (app selector is part of form):
image
image

Project with applications and application is selected (app selector is omitted from form):
image

@openshift/team-devconsole-docs 
@openshift/team-devconsole-ux

### CODE REVIEW

**Comment by serenamarie125** [comment]
Great seeing this PR coming in to match the design!

Note that these designs are intended to simplify the design and improve efficiency.

**Comment by christianvogt** [comment]
@vikram-raj from the UX doc:
Application selector is All Applications and 1+ applications exist
- Application dropdown is part of the form (create App is one of the available options).  If only one application exists, default to that.  If there are more than one application, default to the first in the list.

It's not crystal clear whether the selector remains as `all applications` or not in the selector. I interpreted the above as only the dropdown in the form is affected.

@serenamarie125 please confirm.

**Comment by serenamarie125** [comment]
@christianvogt PR behavior is correct.  Application selection in the secondary masthead should not change from All Apps to the selected app in the form. Once we return to the Topology view, we still want to view All Apps.

**Comment by christianvogt** [comment]
Thanks @serenamarie125.

This is ready for approval again.

**Comment by andrewballantyne** [comment]
@christianvogt Squash?

**Comment by christianvogt** [comment]
@andrewballantyne I separated out the commits on purpose as they touch different parts of the code and for different reasons

**Pull request merged**
