### PR TITLE
Bug 1839460: fix VMImport cancelation options

### PR DESCRIPTION
**Pull request by suomiy**
rename Delete VM to Cancel VM Import

### CODE REVIEW

**Comment by suomiy** [comment]
### VMImport before the VM gets created

We can say the name so the user is sure what VM will be canceled




### VMImport in progress after VM gets created

no need to say the name?




### after VMImport




@matthewcarleton @pkliczewski Can you take a look?

**Comment by matthewcarleton** [comment]
> ### VMImport before the VM gets created
> We can say the name so the user is sure what VM will be canceled
> 
> 

> 
> 
> ### VMImport in progress after VM gets created
> no need to say the name?
> 
> 

This feels like a better option to me - We should be more concerned with showing them the VM That they will interact with.

> 
> 

Maybe instead say: 
Cancel Import
Are you sure you want to cancel importing VM-name-from-provider-here? It will also delete the newly created VM-name-from-cnv-here in the default namespace.

That's if we even need to really talk about the VM that has been creating in the console and what namespace it's in. Do they care about that detail if they are canceling the import?

> ### after VMImport
> 
What exactly is the import resource? Would the user know this or be confused by it? 
Is it a source that you can create other VMs from once it's been imported b/c that's what it sounds like to me.
> 
> @matthewcarleton @pkliczewski Can you take a look?

**Comment by suomiy** [comment]
> This feels like a better option to me - We should be more concerned with showing them the VM That they will interact with.

These were not meant as options, but states which the UI has to go through:
1. VMImport before the VM gets created
2. VMImport in progress after VM gets created
3. after VMImport

> 
> Maybe instead say:
> Cancel Import
> Are you sure you want to cancel importing VM-name-from-provider-here? It will also delete the newly created VM-name-from-cnv-here in the default namespace.

Changed it, although they are cancel importing of vm cirros, not  vm-import-cirros-nw7cl. But I guess it can make sense both ways.

bb
cc



> 
> That's if we even need to really talk about the VM that has been creating in the console and what namespace it's in. Do they care about that detail if they are canceling the import?
>

**Comment by matthewcarleton** [comment]
> > This feels like a better option to me - We should be more concerned with showing them the VM That they will interact with.
> 
> These were not meant as options, but states which the UI has to go through:
> 
> 1. VMImport before the VM gets created
> 2. VMImport in progress after VM gets created
> 3. after VMImport

Ah I see: So my opinion is still the same: Do we have to show that level of detail? Or is it that we don't have a VM to show yet so we can only show the process of the import?
I don't see much value in focusing on the import outside of the status but maybe I'm missing something. 
> 
> > Maybe instead say:
> > Cancel Import
> > Are you sure you want to cancel importing VM-name-from-provider-here? It will also delete the newly created VM-name-from-cnv-here in the default namespace.
> 
> Changed it, although they are cancel importing of vm cirros, not vm-import-cirros-nw7cl. But I guess it can make sense both ways.

Ok what I'm trying to do (and not very clearly :) ) is to simplify this and not show more than we the user needs to see. It feels like we are surfacing here the underlying method of import and not focuses on the thing the user will ultimately care about : His new CNV VM. 


> 
> bb
> cc
> 
> > That's if we even need to really talk about the VM that has been creating in the console and what namespace it's in. Do they care about that detail if they are canceling the import?

**Comment by suomiy** [comment]
> Ah I see: So my opinion is still the same: Do we have to show that level of detail? Or is it that we don't have a VM to show yet so we can only show the process of the import?
> I don't see much value in focusing on the import outside of the status but maybe I'm missing something.

Yep we don't have  a VM yet and in case of an error we will never will. The biggest value of showing it is when error happens (for diving into the problem).

> 
> Ok what I'm trying to do (and not very clearly :) ) is to simplify this and not show more than we the user needs to see. It feels like we are surfacing here the underlying method of import and not focuses on the thing the user will ultimately care about : His new CNV VM.
> 

I guess yeah, but it would be confusing to say we are deleting the VM, when it does not exist yet and only VMImport object gets deleted. The second option is to describe it just as cancel, but we would be hiding the fact what is happening

**Comment by suomiy** [comment]
> So I'd say for the badge it would be an improvement to not have VMimport in there b/c it's breaking the text up. I know we can't use VMI but could we maybe use I for import? It's not very informative - but I think they'll more likely be interested in the status which more clearly states what is happening anyway.

Just Import is not a very good IMO and it will come back to hunt us later. There are may be many import kinds (for example CDI ones are more common and it could lead to confussion). Also the` I` abbreviation is already used by `Ingress`

> I also don't think for the cancel action we'd state the name. This is not a pattern in OCP AFAIK so it should just be Cancel import.

This was made to coincide with the menu action (please take a look). This might not be the best way, but the VM name should be surfaced somehow.

> Can we also be consistent with VM vs Virtual Machine? I don't think we use VM anywhere outside of badges right?
> 

I can replace it, I just worry the label would be too long.

> 
> I guess generally what I'm saying is - regardless of at what stage they are cancelling - they are taking the action to cancel so it should always be a similar experience. We confirm they want to cancel it and then remove anything associated with the VM that was created. I'm not sure why a user would be concerned with how we are doing an import especially if they are not interested in proceeding with the import anyway. WDYT?

The main difference is that they see different objects in the UI (VM vs VMImport) and they can visit their details page (where they can delete these objects). So I think both of these experiences should be similar and make sense from both perspectives.

**Comment by matthewcarleton** [comment]
> > So I'd say for the badge it would be an improvement to not have VMimport in there b/c it's breaking the text up. I know we can't use VMI but could we maybe use I for import? It's not very informative - but I think they'll more likely be interested in the status which more clearly states what is happening anyway.

> 
> Just Import is not a very good IMO and it will come back to hunt us later. There are may be many import kinds (for example CDI ones are more common and it could lead to confussion). Also the` I` abbreviation is already used by `Ingress`

Ya that's the problem with those badges - I can see if we repeat these badges. I really don't think they are meant to be THAT informative. I think the status is what we should rely on. I would say we can't put VMimport because it's too long and looks really strange.
We shouldn't be relying on a badge to define the type of import anyway that's what the status shows.
> 
> > I also don't think for the cancel action we'd state the name. This is not a pattern in OCP AFAIK so it should just be Cancel import.
> 
> This was made to coincide with the menu action (please take a look). This might not be the best way, but the VM name should be surfaced somehow.

I'm confused why we can't just say "cancel import"?
> 
> > Can we also be consistent with VM vs Virtual Machine? I don't think we use VM anywhere outside of badges right?
> 
> I can replace it, I just worry the label would be too long.
I'm referring more to the popups - Using VM in the label is the only place it's ok
> 
> > I guess generally what I'm saying is - regardless of at what stage they are cancelling - they are taking the action to cancel so it should always be a similar experience. We confirm they want to cancel it and then remove anything associated with the VM that was created. I'm not sure why a user would be concerned with how we are doing an import especially if they are not interested in proceeding with the import anyway. WDYT?
> 
> The main difference is that they see different objects in the UI (VM vs VMImport) and they can visit their details page (where they can delete these objects). So I think both of these experiences should be similar and make sense from both perspectives.

Right - it is tricky, but hiding some of this doesn't seem that bad to me. Does a user care about the underlaying method in which the import happens or only that it is happening and everything is ok OR something is wrong? I like the idea of cancelling the import that makes more sense than deleting and helps them think of it like a process not a creation of something.

**Comment by suomiy** [comment]
> > > So I'd say for the badge it would be an improvement to not have VMimport in there b/c it's breaking the text up. I know we can't use VMI but could we maybe use I for import? It's not very informative - but I think they'll more likely be interested in the status which more clearly states what is happening anyway.
> 
> > Just Import is not a very good IMO and it will come back to hunt us later. There are may be many import kinds (for example CDI ones are more common and it could lead to confussion). Also the` I` abbreviation is already used by `Ingress`
> 
> Ya that's the problem with those badges - I can see if we repeat these badges. I really don't think they are meant to be THAT informative. I think the status is what we should rely on. I would say we can't put VMimport because it's too long and looks really strange.
> We shouldn't be relying on a badge to define the type of import anyway that's what the status shows.
> 
> > > I also don't think for the cancel action we'd state the name. This is not a pattern in OCP AFAIK so it should just be Cancel import.
> > 
> > 
> > This was made to coincide with the menu action (please take a look). This might not be the best way, but the VM name should be surfaced somehow.
> 
> I'm confused why we can't just say "cancel import"?

We can, I just used it to show the VM name in the list. If we can show the VM name in some other way, then we can remove it from the cancel action.

> 
> > > Can we also be consistent with VM vs Virtual Machine? I don't think we use VM anywhere outside of badges right?
> > 
> > 
> > I can replace it, I just worry the label would be too long.
> > I'm referring more to the popups - Using VM in the label is the only place it's ok
> > > I guess generally what I'm saying is - regardless of at what stage they are cancelling - they are taking the action to cancel so it should always be a similar experience. We confirm they want to cancel it and then remove anything associated with the VM that was created. I'm not sure why a user would be concerned with how we are doing an import especially if they are not interested in proceeding with the import anyway. WDYT?
> > 
> > 
> > The main difference is that they see different objects in the UI (VM vs VMImport) and they can visit their details page (where they can delete these objects). So I think both of these experiences should be similar and make sense from both perspectives.
> 
> Right - it is tricky, but hiding some of this doesn't seem that bad to me. Does a user care about the underlaying method in which the import happens or only that it is happening and everything is ok OR something is wrong? I like the idea of cancelling the import that makes more sense than deleting and helps them think of it like a process not a creation of something.

Sure, we can keep the idea of canceling. But it is still useful to see the VMImport object when something goes wrong. But I guess they don't care that much when it is going alright.

**Comment by matthewcarleton** [comment]
Also I've been chatting with other OpenShift designers and there are already duplicates of letters for these badges. We could use VMI and then use a different color from what we are already using from the VMI Badge.
I wonder if we can make better use of the status popup to help the user understand what is happening. 
We have more room there to add a more descriptive message. WDYT?

**Comment by suomiy** [comment]
> **EDIT: We could just use `VIM` for the badge letters. It makes sense for it to be the same color as the VM badge too since it's very closely related.**

done

Screenshot from 2020-06-15 14-50-05

> 
> Also I've been chatting with other OpenShift designers and there are already duplicates of letters for these badges. We could use VMI and then use a different color from what we are already using from the VMI Badge.

Not sure, if it is a good idea to distinguish the entities only by color. I personally don't remember colors of entities, and just look at the abbreviation/name. Plus there are many people who don't see all colors. `VIM` seems good enough option to me so far. 

> I wonder if we can make better use of the status popup to help the user understand what is happening.
> We have more room there to add a more descriptive message. WDYT?

The status is quite descriptive already, but not sure if we can fit in the VM name somewhere? Thoughts? 

aa

**Comment by matthewcarleton** [comment]
> > **EDIT: We could just use `VIM` for the badge letters. It makes sense for it to be the same color as the VM badge too since it's very closely related.**
> 
> done
> 
> Screenshot from 2020-06-15 14-50-05
> 
> > Also I've been chatting with other OpenShift designers and there are already duplicates of letters for these badges. We could use VMI and then use a different color from what we are already using from the VMI Badge.
> 
> Not sure, if it is a good idea to distinguish the entities only by color. I personally don't remember colors of entities, and just look at the abbreviation/name. Plus there are many people who don't see all colors. `VIM` seems good enough option to me so far.
+1 I think this is a good solution and doesn't need a separate colour.
> 
> > I wonder if we can make better use of the status popup to help the user understand what is happening.
> > We have more room there to add a more descriptive message. WDYT?
> 
> The status is quite descriptive already, but not sure if we can fit in the VM name somewhere? Thoughts?
> 
> aa

Instead of saying "importing virtual machine..." could we just use the name instead? They know it's a VM being imported already.

**Comment by suomiy** [comment]
done 
aa

**Pull request merged**
