### PR TITLE
Topology: Add Helm Release selection and details side panel

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Addresses story https://issues.redhat.com/browse/ODC-2794

image

/cc @openshift/team-devconsole-ux 

TODO:
- [ ] Add resources tab once it is available

### CODE REVIEW

**Comment by christianvogt** [comment]
Errored out when opening the sidebar.
I used helm v3 and didn't get the labels so I manually added labels to the deployment and while the topology showed the helm grouping. Side bar resulted in this:
image

**Comment by jeff-phillips-18** [comment]
Added a check and display an error if unable to find the resource.

**Comment by christianvogt** [comment]
/hold

waiting for https://github.com/openshift/console/pull/4065

**Comment by jeff-phillips-18** [comment]
@christianvogt Rebased, needs lgtm again

**Comment by andrewballantyne** [comment]
/lgtm
/hold

This likely to follow the same issues as the rest of our PRs. https://coreos.slack.com/archives/CEKNRGF25/p1579962369129100

**Comment by andrewballantyne** [comment]
/hold cancel
/retest

Looks like it's good to go again.

**Comment by andrewballantyne** [comment]
Bundle flake... but only so tiny amount... this test is quite annoying lol...

>Main vendor bundle size: 2.48 MiB
FAILURE: Main vendor bundle is larger than the 2 MiB limit.

/retest

**Pull request merged**
