### PR TITLE
Bug 1797379: pipeline test edit1

### PR DESCRIPTION
**Pull request by sanketpathak**
Minor addition in pipeline tests to run existing tests flawlessly

### CODE REVIEW

**Comment by abhinandan13jan** [comment]
@sanketpathak Is there a description or a link around what this PR is trying to do?

**Comment by sanketpathak** [comment]
Added the description, it's just a slight change in the tests to run the test without any errors

**Comment by ldimaggi** [comment]
/lgtm

Thanks for making the final changes!

**Pull request merged**
