### PR TITLE
ODC-7539: Update devfile library to v2.2.2

### PR DESCRIPTION
**Pull request by maysunfaisal**
### Description

This PR updates to a newer version of devfile/library. The devfile/library go mod version that has been selected includes the updated devfile validation, whereby the ports defined in the devfile sample can now be more uniform and consistent. For example, take a peak at the Quakus devfile sample for this port change https://github.com/devfile-samples/devfile-sample-code-with-quarkus/pull/23

For a list of the feature updates on devfile/library, see the [release v2.2.1](https://github.com/devfile/library/releases/tag/v2.2.1)

### Issue
Fixes https://github.com/devfile/api/issues/1136

### Testing
Build an image from branch, push to quay and update the console container with the quay image.

### Notes
We should also be back porting this to a few releases.

### CODE REVIEW

**Comment by maysunfaisal** [comment]
@jerolimov are you still monitoring the code base from devfile POV? If you are, I would be grateful if you could also please take a look!

**Comment by maysunfaisal** [comment]
@thepetk could you please use this branch and test it with the new registry index with multiple versions? It is now pulling the latest devfile/library

**Review by thepetk — APPROVED** [review]
/lgtm

I've tested the updated console with the existing `registry index`:

* Was able to fetch all devfile samples.
* Was able to build an application for each one of the samples.

Another thing I've tried to test the latest changes, was to try to import from git a `temp` branch I've created for the `go-basic` sample which has two components using the same port `8080`. The updated console was able to validate & build the devfile, which is not allowed atm for console as it uses an older version of devfile library. The example code is here: https://github.com/thepetk/devfile-sample-go-basic/tree/temp_branch

**Review by jerolimov — APPROVED** [review]
This change works really fine. I've tested this on a cluster bot and verified that all 6 included samples works fine:

image

image

I will continue testing some old devfiles repo...

/lgtm
/approve

**Comment by jerolimov** [comment]
/retitle ODC-7539: Update devfile library to v2.2.2

**Comment by jerolimov** [comment]
It's a go library update and I spend a lot of time to test different use case...

/label px-approved
/label docs-approved
/jira refresh

**Comment by sanketpathak** [comment]
Verified with admin and non-admin users
Screenshot 2024-03-12 at 7 00 23 PM
/label qe-approved

**Pull request merged**
