### PR TITLE
Change dropdown units for consistency on PVC form

### LINKED ISSUE #1209: Inconsistent unit labels in the PVC creation form
When creating a Persistent Volume Claim, the unit dropdown next to the size field starts as `GiB`. Interacting with the dropdown changes the unit label from the expected `MiB/GiB/TiB` to the abbreviated `Mi/Gi/Ti` instead. Since abbreviated units are used elsewhere in the console, it seems like the elongated labels should be replaced.

pvc-unit-change

### PR DESCRIPTION
**Pull request by zherman0**
Change dropdown units for consistency on PVC form to shortened form

Fixes #1209

NEW:
dropdown-units
OLD:
dropdown-old-units

### CODE REVIEW

**Comment by spadgett** [comment]
@zherman0 will need #1226 to pass CI :/

**Comment by AyushAmbastha** [comment]
@zherman0 @spadgett This seems to be a workaround in solving the drop down issue as the keys are being picked up instead of the intended values from the dropdownUnits dictionary defined in 'console/frontend/public/components/storage/create-pvc.tsx'.
I've made changes to the 'console/frontend/public/components/utils/request-size-input.tsx' file which solves the problem and displays units in the shortened form.

The changes I've made are-
OLD ->    this.props.onChange({ value: this.state.value, unit });
NEW ->   this.props.onChange({ value: this.state.value, unit: this.state.value });
 Please take a look.

image

**Comment by zherman0** [comment]
@AyushAmbastha - I am confused by your fix there.  
  Quoting: The changes I've made are-
  OLD -> this.props.onChange({ value: this.state.value, unit });
  NEW -> this.props.onChange({ value: this.state.value, unit: this.state.value });
You have set the `unit` state variable that is the drop down value equal to `this.state.value` which is the value from the numeric input field.  I do not understand how this would work.

**Comment by spadgett** [comment]
olm test flake

/retest

**Comment by spadgett** [comment]
olm flake

/retest

**Comment by AyushAmbastha** [comment]
> You have set the `unit` state variable that is the drop down value equal to `this.state.value` which is the value from the numeric input field. I do not understand how this would work.

@zherman0 Oh! I think I got confused with what 'value' is. It worked so I didn't look at it again. I'll try coming up with another fix. I feel the dictionary keys shouldn't be displayed so I don't understand why we need to define the dictionary as Mi: "Mi"  and so on. It should work when the units are defined as an array as well,right?

**Comment by jhadvig** [comment]
operator-hub TC failed

/retest

**Comment by spadgett** [comment]
> NoSuchElementError: No element found using locator: by.cssContainingText(".co-resource-list__item", "etcd")

/retest

**Comment by jhadvig** [comment]
```
StaleElementReferenceError: stale element reference: element is not attached to the page document
```

/retest

**Pull request merged**
