### PR TITLE
Bump helm version  to 3.10.1

### PR DESCRIPTION
**Pull request by Kartikey-star**
This PR bumps the helm version to 3.10.1.
Signed-off-by: Kartikey Mamgain <mamgainkartikey@gmail.com>

### CODE REVIEW

**Comment by Kartikey-star** [comment]
Requesting review from @dperaza4dustbit too.

**Review by dperaza4dustbit — APPROVED** [review]
/lgtm

**Review by jhadvig — APPROVED** [review]
/approve

**Comment by jhadvig** [comment]
Adding `qe-approved` label manually since this PR is just bumping the dependecies.

**Pull request merged**
