### PR TITLE
odc-5571-fixed page details related smoke test case

### PR DESCRIPTION
**Pull request by makambalaji**
**Problem**: page details related smoke test cases are failed
**Solution**: updated the locator for add page and moved the pipelines test case to pipelines folder

**Jira Id**: https://issues.redhat.com/browse/ODC-5571

image

### CODE REVIEW

**Comment by sanketpathak** [comment]
Tests are passing 
Screenshot from 2021-03-03 19-22-56
/lgtm

**Comment by spadgett** [comment]
Holding until #8289 merges to unblock CI.

/hold

**Comment by makambalaji** [comment]
@sanketpathak - Can you please add lgtm again. Due to rebase lgtm got removed

**Pull request merged**
