### PR TITLE
GITOPS-3433: get ready for cypress upgrade

### PR DESCRIPTION
**Pull request by ciiay**
This is for the cypress upgrade. This can't be merged in until rebase master after #13070 PR goes in.

### CODE REVIEW

**Comment by rhamilto** [comment]
@ciiay, please rebase to resolve conflicts.  Any word from QE about the re-enablement of the Cucumber tests?

**Comment by ciiay** [comment]
@rhamilto Conflicts resolved. Our QE team is still working on it. Will update here asap.

**Comment by rhamilto** [comment]
Work is tech debt and has no customer-facing impact.

/label docs-approved
/label px-approved
/label qe-approved

**Pull request merged**
