### PR TITLE
Improve git section performance in git import flow

### PR DESCRIPTION
**Pull request by rottencandy**
**Story**: 
https://issues.redhat.com/browse/ODC-5998

**Analysis / Root cause**: 
Memoized some data inside the `GitSection` component, and moved onchange handler statements to inside the debounced callback.
profile
The profiler reports that a lot of time is being spent in rendering components outside of the input field, such as the git advanced options section and the resource type section. I've tried memoizing some of the data, but I'm unsure if we can do much here since these places make use of shared components.

**Screen shots / Gifs for design review**: 
Before:

https://user-images.githubusercontent.com/20013884/129927295-818db084-e9ec-4203-9acb-06822bd49be4.mp4

After:

https://user-images.githubusercontent.com/20013884/129927318-50777594-a1cd-4bb5-8269-3cbed0a786a7.mp4

**Unit test coverage report**: 
<unchanged>

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by rohitkrai03 — CHANGES_REQUESTED** [review]
Overall changes looks good.  Found a issue though while running it locally. Some times the create button doesn't get enabled when switching from an invalid url to valid one.

https://user-images.githubusercontent.com/6041994/130120839-830f38b4-2b58-4b07-a836-53a72ab241d9.mov

**Comment by rottencandy** [comment]
> Overall changes looks good. Found a issue though while running it locally. Some times the create button doesn't get enabled when switching from an invalid url to valid one.

Was happening because fields were not reset on invalid URL, fixed.

**Comment by rohitkrai03** [comment]
@rottencandy Earlier issue is solved now but found another issue. The recommendation gets reset when you submit the form. 

https://user-images.githubusercontent.com/6041994/130218910-e8069ef6-3271-4341-8b8b-cf74d247c52f.mov

**Comment by rottencandy** [comment]
> @rottencandy Earlier issue is solved now but found another issue. The recommendation gets reset when you submit the form.

Fixed. Added isSubmitting check before running url change handler in effect.

**Review by rohitkrai03 — APPROVED** [review]
/lgtm
/approve

Verified locally. Works as expected. Definitely see an improvement in the performance while typing in the git url input field.

**Comment by rottencandy** [comment]
/label px-approved
/label docs-approved

Added label on behalf of doc, px since epic https://issues.redhat.com/browse/ODC-5009 has ack from docs and px and AC hasn't changed

**Comment by rohitkrai03** [comment]
/label qe-approved

Verified on a cluster created using cluster bot. Everything work as expected.

**Pull request merged**
