### PR TITLE
OCPBUGS-36967: RWOP access mode is not integrated in the UI [cephfs.csi.ceph.com & rbd.csi.ceph.com]

### PR DESCRIPTION
**Pull request by cyril-ui-developer**

### CODE REVIEW

**Review by SanjalKatiyar — APPROVED** [review]
LGTM, thanks @cyril-ui-developer.

**Comment by cyril-ui-developer** [comment]
> LGTM, thanks @cyril-ui-developer.

Thank you, too! :)

**Review by rhamilto — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
