### PR TITLE
Bug 1932277: Create new pool with arbiter - wrong replica (4.7 release)

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
@spadgett Please approve this PR

**Comment by spadgett** [comment]
/approve
/hold

analyze is failing due to https://github.com/openshift/release/pull/13715. I will open a PR to fix.

**Comment by spadgett** [comment]
The analyze job should be fixed by https://github.com/openshift/release/pull/16955. Feel free to remove the hold when that merges.

**Pull request merged**
