### PR TITLE
ODC-7680: Remove `SeriesButton`, `QueryTable`

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7680

**Solution Description**: 

`SeriesButton` and `QueryTable` do not appear to be used anywhere within the [openshift/console](https://github.com/openshift/console/) and [openshift/monitoring-plugin](https://github.com/openshift/monitoring-plugin/) repos, and `QueryTable` is using deprecated PatternFly Table components

**Screen shots / Gifs for design review**: 

n/a

**Unit test coverage report**: 

unchanged

**Test setup:**

n/a

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

This pr is 3/4 of [ODC-7680](https://issues.redhat.com//browse/ODC-7680) story as each file is being split into a separate PR.

### CODE REVIEW

**Comment by kyoto** [comment]
CC @jgbernalp, @zhuje, @PeterYurkovich 

Is it OK to remove these now?

**Comment by zhuje** [comment]
okay to remove

**Comment by logonoff** [comment]
adding labels because this is debt

/label px-approved
/label docs-approved

**Review by vikram-raj — APPROVED** [review]
/approve

**Comment by sanketpathak** [comment]
Verified on cluster with admin and non-admin user
Screenshot from 2024-10-17 20-22-55
/label qe-approved

**Pull request merged**
