### PR TITLE
Bug 1907307: Propagate provider and support annotations

### PR DESCRIPTION
**Pull request by rawagner**
Screenshot from 2020-12-11 10-36-50
Screenshot from 2020-12-11 10-22-26
Screenshot from 2020-12-11 10-22-07

@matthewcarleton can you take a look ?

### CODE REVIEW

**Comment by rawagner** [comment]
@matthewcarleton 
labels updated with tooltip

Screenshot from 2020-12-14 14-55-29

Screenshot from 2020-12-14 14-54-59

**Comment by matthewcarleton** [comment]
nice! can you add some spacing (8px maybe) between the labels? 
Also - we'd only see "Kubevirt" as the supporter upstream?

**Comment by rawagner** [comment]
> nice! can you add some spacing (8px maybe) between the labels?

added
Screenshot from 2020-12-15 09-00-49



> Also - we'd only see "Kubevirt" as the supporter upstream?
actually we wont see `Kubevirt` supporter anywhere, upstream wont have any support, downstream will have Red Hat. I just changed the code for the purpose of screenshotting

**Comment by matthewcarleton** [comment]
LGTM!

**Comment by yaacov** [comment]
/close
CI fails, will continue in #7641

**Pull request closed without merging**
