### PR TITLE
[release-4.6] Bug 1924069: fix pipeline rerun when pipelineSpec is embedded

### PR DESCRIPTION
**Pull request by nemesis09**
This is a 4.6 cherry pick for https://github.com/openshift/console/pull/7923

Fixes:
https://issues.redhat.com/browse/ODC-5395

### CODE REVIEW

**Comment by spadgett** [comment]
You will need #8025 for the backend tests to pass.

**Comment by nemesis09** [comment]
> You will need #8025 for the backend tests to pass.

Thank you @spadgett 
I'll retest it once the dependent PR is merged

**Comment by nemesis09** [comment]
putting it on hold until https://github.com/openshift/console/pull/8025 merges, since that is required for tests to pass.

**Review by andrewballantyne — APPROVED** [review]
Added more tests than was in your mirror, but that's never a bad thing 😄

**Comment by jerolimov** [comment]
#8025 is now merged. Remove the hold again.
/unhold

**Review by andrewballantyne — APPROVED** [review]
/lgtm

**Pull request merged**
