### PR TITLE
[release-4.14] OCPBUGS-42757: Switch to use annotations as labels from PipelineRuns created through Pipelines as Code is deprecated

### PR DESCRIPTION
**Pull request by vikram-raj**
Manual cherry-pick of https://github.com/openshift/console/pull/14358

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
Verified

https://github.com/user-attachments/assets/7f52c6d5-a456-469d-a85c-8a4b1145c8d6

**Review by lokanandaprabhu — APPROVED** [review]

**Pull request merged**
