### PR TITLE
Bug 1952495:  “Create” button on the Templates page is confuse

### PR DESCRIPTION
**Pull request by avivtur**
In this example, I change text from 'Create' to 'Create VM' on each template row.
before:
bz_1952495_before

after:
bz_1952495_after

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=1952495
Signed-off-by: Aviv Turgeman <aturgema@redhat.com>

### CODE REVIEW

**Comment by avivtur** [comment]
@matthewcarleton @yaacov please review

**Comment by yaacov** [comment]
kubevirt-plugin tests are failing, fix is available in https://github.com/openshift/console/pull/8768

**Pull request merged**
