### PR TITLE
Bug 1877842: Replace quick start route icon with rocket icon

### PR DESCRIPTION
**Pull request by rottencandy**
**Fixes**: 
https://issues.redhat.com/browse/ODC-4696

**Analysis / Root cause**: 
Quick start icon needs to be updated to the rocket icon.

**Solution Description**: 
Replace quick start route icon with rocket icon.

**Screen shots / Gifs for design review**: 
tmp0
tmp1

@openshift/team-devconsole-ux

**Unit test coverage report**: 
Unchanged.

**Browser conformance**: 

- [ ] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by sahil143 — APPROVED** [review]
/lgtm

verified changes locally

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
