### PR TITLE
Kubernetes Marketplace - disable nav button

### PR DESCRIPTION
**Pull request by galletti94**
## Description

This comments out the marketplace nav item and routes until we have clickable tiles and more user interaction is possible.

### CODE REVIEW

**Comment by spadgett** [comment]
I'm OK leaving the route if it makes testing easier.

**Comment by galletti94** [comment]
Ok - I wasn't sure whether we wanted to make this completely inaccessible or just hidden. It's definitely more convenient for us if it's just hidden and we can still access the UI through that route. Will change this now

**Pull request merged**
