### PR TITLE
Remove unnecessary padding in alerts title, fix icon/text position

### PR DESCRIPTION
**Pull request by rawagner**
before:
alerts_padding

after:
alerts_padding1

### CODE REVIEW

**Comment by spadgett** [comment]
The icons don't look like they're properly aligned with the text (both before and after)

**Comment by rawagner** [comment]
> The icons don't look like they're properly aligned with the text (both before and after)

fixed

alerts

**Comment by spadgett** [comment]
This is also not new, but the cluster health icon and the alert icons are slightly different sizes, even though the text is the same size. It looks like a mistake. Either the icons should be the same size, or the difference should be greater (and we'd probably want to make the cluster health text larger as well). @lizsurette @andybraren opinion?

We can tackle this as a follow on.

**Pull request merged**
