### PR TITLE
Bug 2009420: Use live regions for alerts in modals

### PR DESCRIPTION
**Pull request by jcaianirh**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2009420

This came up as a screen reader user typed in an upper case char during project creation displaying an error alert in the create project modal.
The alert does not get announced by the screen reader. Creating a liveRegion is a way to announce errors for screen readers. 

This is a pr to test with the jaws screen reader.

cc: @jessiehuff 

Before:

https://user-images.githubusercontent.com/35978579/135485341-0c32508b-d6c6-4715-8eeb-4056d77d2843.mov

After:

https://user-images.githubusercontent.com/35978579/135485565-1afa76d3-8b3a-4424-8dc3-f78f21ab23aa.mov

### CODE REVIEW

**Review by dtaylor113 — APPROVED** [review]
/lgtm

**Review by zherman0 — APPROVED** [review]

**Comment by jcaianirh** [comment]
/hold
for discussions and testing with jessie

**Comment by jessiehuff** [comment]
Hey @jcaianirh, we updated our alert and alert groups to make this easier on products, and I think all you should need to do is wrap it in an AlertGroup with the same properties that you have in this PR ([example](https://www.patternfly.org/v4/components/alert#dynamic-live-region-alert)). I also created a11y documentation to try to spell this out easily [here](https://www.patternfly.org/v4/components/alert/accessibility).

**Comment by jcaianirh** [comment]
> Hey @jcaianirh, we updated our alert and alert groups to make this easier on products, and I think all you should need to do is wrap it in an AlertGroup with the same properties that you have in this PR ([example](https://www.patternfly.org/v4/components/alert#dynamic-live-region-alert)). I also created a11y documentation to try to spell this out easily [here](https://www.patternfly.org/v4/components/alert/accessibility).

This is great news @jessiehuff. Can you tell me which version of patternfly-react we would need to pick up this change? We currently are on 2021-10.

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
