### PR TITLE
Bug 1999422: Guard display of supported vendors

### PR DESCRIPTION
**Pull request by afreen23**
- external vendors must be flagged based on the annotation `vendors.odf.openshift.io/kind`
- this will control the disablement of vendor's UI in ODF UI (in case the vendor could not finish up in a proposed release)

Followup Pr for UI for https://github.com/red-hat-storage/odf-operator/pull/74

Signed-off-by: Afreen Rahman <afrahman@redhat.com>

### CODE REVIEW

**Comment by SanjalKatiyar** [comment]
/lgtm
If annotation is not present, external vendor option will not be shown in `Connect an external storage platform > Storage platform dropdown`

**Comment by afreen23** [comment]
> /lgtm
> If annotation is not present, external vendor option will not be shown in `Connect an external storage platform > Storage platform dropdown`

Yes, thats expected.

**Pull request merged**
