### PR TITLE
[WIP] Bug 1980531: additionalHelpActions 'HelpMenu' ConsoleLinks not translated

### PR DESCRIPTION
**Pull request by kdoberst**
Addresses [Bug 1980531](https://bugzilla.redhat.com/show_bug.cgi?id=1980531)

In the help menu, the "Learning Portal" and "OpenShift Blog" links are brought into the console code so they can be translated.  

Note: This PR should be merged after https://github.com/openshift/console-operator/pull/565 to prevent the help links from being duplicated.

### CODE REVIEW

**Comment by spadgett** [comment]
Thanks @kdoberst 

> The "Learning Portal" and "OpenShift Blog" links will always show and cannot be deleted. There needs to be some investigation if it is possible for users to remove these links in the current system.

It's not currently possible for admins to remove these links. The operator will recreate them if an admin deletes them.

We should be able to add the `release.openshift.io/delete: "true"` annotation in the manifests in the console-operator repo to remove the existing ConsoleLink resources.

**Comment by kdoberst** [comment]
> We should be able to add the `release.openshift.io/delete: "true"` annotation in the manifests in the console-operator repo to remove the existing ConsoleLink resources.

This has been verified and there is PR to put those changes into the console-operator.

**Review by dtaylor113 — CHANGES_REQUESTED** [review]
lgtm, one issue to include new translated sections in e2e tests :-) 

If the additional links are now translated we should remove the `.first()` [here](https://github.com/openshift/console/pull/9385/files#diff-2dee3deaca1bd14a234e5d813f3bd2fb14fa0e42beb1371f60994805c16bc5d4R26) in `frontend/packages/integration-tests-cypress/tests/i18n/pseudolocalization.spec.ts` in order to test pseudolocalization of all help menu sections.

**Comment by kdoberst** [comment]
There was an error rebasing.  Closing this PR and opening https://github.com/openshift/console/pull/9811

**Pull request closed without merging**
