### PR TITLE
Add generic "OpenShift" branding option and make it default

### PR DESCRIPTION
**Pull request by rhamilto**
IMPORTANT:  this PR overrides the default branding option `okd` with `openshift`.  We'll undo this at a future date.

cc: @jwforres, @smarterclayton 

screen shot 2018-12-05 at 5 05 32 pm
screen shot 2018-12-05 at 5 05 36 pm

### CODE REVIEW

**Comment by spadgett** [comment]
@rhamilto You'd need to change the flag handling here:

https://github.com/openshift/console/blob/master/cmd/bridge/main.go#L86

and here:

https://github.com/openshift/console/blob/master/cmd/bridge/main.go#L140-L151

We should check if the operator is setting anything in the config file that would override the default.

**Comment by spadgett** [comment]
Looks like the operator sets it, too.

https://github.com/spadgett/console-operator/blob/5082c444bad82ca884941ca479141169ee13d0c9/pkg/console/subresource/configmap/configmap.go#L93

For now, I think it would be simplest to ignore the flag and just always use openshift. Then we can roll that change back.

**Comment by rhamilto** [comment]
@spadgett ready for final review.

**Pull request merged**
