### PR TITLE
Only Watch Kubernetes Resources that Support Watching

### PR DESCRIPTION
**Pull request by alecmerdler**
### Description

Some k8s resources (like OLM's `PackageManifest` aggregated apiserver) do not implement the `watch` verb, and will throw `HTTP 405` when trying to establish a watch. Now we check that `watch` is included in the `verbs` before attempting a WebSocket connection.

Addresses https://jira.coreos.com/browse/ALM-786

### CODE REVIEW

**Comment by spadgett** [comment]
Do we correctly fill in the verbs for static models? (I can't remember if we fixed that.)

**Comment by spadgett** [comment]
> Do we correctly fill in the verbs for static models? (I can't remember if we fixed that.)

I guess it doesn't matter since the PR defaults to watch if `verbs` is missing.

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by alecmerdler** [comment]
@spadgett Yes we do (for CRDs and aggregated apiservers):

screenshot_20190115_160916

**Comment by alecmerdler** [comment]
Whoops, this isn't working. Need to revisit where to add the `if` statement.

**Pull request merged**
