### PR TITLE
Upgrade Yaml Language Server from 0.5.4 to 0.9.0 #6084

### PR DESCRIPTION
**Pull request by apupier**
I called `yarn upgrade yaml-language-server --latest` to do the modification

### CODE REVIEW

**Comment by spadgett** [comment]
Hi @apupier were you able to test the change? We had issues trying to bump this dependency. I'm not sure if 0.9.0 is compatible with our current Monaco version.

**Comment by apupier** [comment]
> Hi @apupier were you able to test the change? We had issues trying to bump this dependency. I'm not sure if 0.9.0 is compatible with our current Monaco version.

no, not able to test yet. First time I'm touching this codebase. I was hoping some tests would show it on CI while searching how to test it locally.

**Comment by apupier** [comment]
tried a bunch of test and it is nto working:
- upgrading yaml-language-server vscode-languageserver-types, compile btu doesn't work at runtime
-  upgrading yaml-language-server vscode-languageserver-types monaco-language-client react-monaco-editor, doesn't compile with ```
Error: Cannot find module 'monaco-editor/esm/vs/editor/contrib/goToDefinition/goToDefinitionCommands'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.resolve (/home/apupier/git/console/frontend/node_modules/v8-compile-cache/v8-compile-cache.js:166:23)
    at resolveMonacoPath (/home/apupier/git/console/frontend/node_modules/monaco-editor-webpack-plugin/index.js:21:18)
    at use.options.pre.featurePaths.map (/home/apupier/git/console/frontend/node_modules/monaco-editor-webpack-plugin/index.js:134:51)
    at Array.map (<anonymous>)
    at createLoaderRules (/home/apupier/git/console/frontend/node_modules/monaco-editor-webpack-plugin/index.js:134:31)
    at MonacoWebpackPlugin.apply (/home/apupier/git/console/frontend/node_modules/monaco-editor-webpack-plugin/index.js:71:19)
```
- upgrading to yaml-language-server to 0.7.2, it doesn't load at runtime
- upgrading to yaml-language-server to 0.6.1, it doesn't load at runtime
- upgrading to yaml-language-server to 0.5.8, it doesn't load at runtime
- upgrading to yaml-language-server to 0.5.6, it is working

when failing at runtime it doesn't load, there are some errors mentioning 503 for prometheus or rules (don't understand how it can be related) or some other path but found no information related to yaml or monaco

**Comment by spadgett** [comment]
Thank you for the PR. We have this working in #6099 with `umd-compat-loader`, so I'm going to close in favor of #6099.

**Pull request closed without merging**
