### PR TITLE
CONSOLE-2361: tidy base styles

### PR DESCRIPTION
**Pull request by rhamilto**
Formatting fixes, cleanup to meet code conventions.

### CODE REVIEW

**Comment by rhamilto** [comment]
/hold for approval

/assign @yapei 
for QE approval

This PR has no user visible changes, and we have general docs and px approval for this epic. @ahardin-rh @sferich888 FYI

/label docs-approved
/label px-approved

**Review by spadgett — APPROVED** [review]
/lgtm

**Review by sg00dwin — APPROVED** [review]

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Pull request merged**
