### PR TITLE
Bug 1998388: User preference screen shows "Create Namespace" instead of "Create Project"

### PR DESCRIPTION
**Pull request by yozaam**
**Fixes**: 

https://issues.redhat.com/browse/ODC-6284

**Analysis / Root cause**: 

I looked at the values of the 3 booleans used at [list-dropdown.jsx#L207](https://github.com/openshift/console/blob/bc0f4129c60240f43fddd532de94e5e23f5995ae/frontend/public/components/utils/list-dropdown.jsx#L207)

( oc -> 4.9.0-0.nightly-2021-08-25-231643 )

```
canCreateNamespace true
canCreateProject true
openshiftFlag true
```

This is why we see "create namespace" since the condition was 
`const model = canCreateNamespace || !openshiftFlag ? NamespaceModel : ProjectModel;`

Changing this to look at only openshiftFlag solves the bug ( way it is implemented in multiple places of the codebase )
https://github.com/openshift/console/blob/852743d807b0c5f8a551cb4bc18345b8c3b22029/frontend/packages/kubevirt-plugin/src/components/form/project-dropdown.tsx#L22-L23

**Solution Description**: 

Only look at the openshift flag when deciding the model 
https://github.com/openshift/console/pull/9890/files#diff-30e14373ba5138b3b0753194670c0fa14ecbcb207856ce302b4728e268c9e9deL222-R222

**Screen shots / Gifs for design review**: 

We see "Create Project" instead of seeing "Create Namespace"
Screenshot from 2021-08-26 14-32-20

**Unit test coverage report**: 

**Test setup:**

Open user preferences from username dropdown
Open the project dropdown
Check option to create a new namespace / project

**Browser conformance**: 

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by jerolimov** [comment]
/uncc jerolimov

Btw: the tests are broken. We should check if they are wrong or if we could
Life for the moment by creating a hook just for this component. We want replace them soon with the shared namespace Dropdown which was recently updated.

**Comment by yozaam** [comment]
The failing test was only looking for a "Create_Namespace" button I edited to match anything that starts with "Create_" inside our because dropdown we can have either one , Namespace or Project 

Tests have passed now

**Comment by yozaam** [comment]
/assign @spadgett 
requesting approval

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
