### PR TITLE
update and add image vulnerability toggle group in IMV details page

### PR DESCRIPTION
**Pull request by vikram-raj**
**Fix:** https://issues.redhat.com/browse/ODC-5392

**Descriptions:**
- Add Source and Type column to Vulnerabilities table
- Add Image Vulnerability toggle group in `IMV` details page

**Screenshots:**
image

image

image

Peek 2022-03-23 18-12

**Tests coverage:**
image

**Test setup:**
1. Install `Quay Container Security` provided by Red Hat
1. Create a deployment through Import from yaml flow using this image `quay.io/redhat-appstudio-qe/quarkus:7dd062e2e8cb4ba599185e48d628b65a`
2. Navigate to Project > Vulnerabilities tab
3. Open the Vulnerability details page

### CODE REVIEW

**Comment by vikram-raj** [comment]
/cc @invincibleJai 

cc: @serenamarie125

**Comment by itsptk** [comment]
Looks good, my only comment would be that we churned quite a bit on what icon should be used to represent severity, and ultimately landed on the triangle (vs the shield that's been implemented here) since the triangle is what's used in Quay's UI, and also the shield icon is supposedly reserved for specific 'security advisory' usage: https://mojo.redhat.com/docs/DOC-1157657 

Designs:
https://docs.google.com/document/d/1fAsA2GIpMpC-0lUDX4HL0qN6kuokP5e_ZvS_bb_G5kA/edit#
https://github.com/openshift/openshift-origin-design/pull/508

**Comment by vikram-raj** [comment]
@itsptk Updated the Severity icon to `ExclamationTriangleIcon`. PTAL. Thanks

image

**Comment by invincibleJai** [comment]
> https://docs.google.com/document/d/1fAsA2GIpMpC-0lUDX4HL0qN6kuokP5e_ZvS_bb_G5kA/edit#

@itsptk I see missing at two places, so even these need to be updated looks like

- Project overview

image

- Cluster overview

image

cc @vikram-raj

**Comment by vikram-raj** [comment]
> > https://docs.google.com/document/d/1fAsA2GIpMpC-0lUDX4HL0qN6kuokP5e_ZvS_bb_G5kA/edit#
> 
> @itsptk I see missing at two places, so even these need to be updated looks like
> 

@invincibleJai Icon for image Vuln on overview is not based on the severity of the vuln.  The icon of the item on the status card is based on the health state of the item. As per the discussion with @itsptk we decided that we can go with it what we have currently.

**Review by karthikjeeyar — COMMENTED** [review]
Verified the PR, Toggle Group and Filter in the Table works as expected.

However I noticed the Popover in the Developer -> Project Overview has style issue. The content overflows and clicking on the links makes the popover jump to different position and closes it.

image

**Comment by vikram-raj** [comment]
Thanks @karthikjeeyar for the review and testing of the PR. The issue you mentioned is not related to the changes in this PR. IMO we can address it as part of another ticket. wdyt?

**Comment by karthikjeeyar** [comment]
@vikram-raj Yes, Its appears that it is a shared component and the Issue is noticeable in the Admin overview as well. I have created a ticket to fix this issue https://bugzilla.redhat.com/show_bug.cgi?id=2070457

**Comment by vikram-raj** [comment]
Propagate from epic:
/label docs-approved
/label px-approved

**Pull request merged**
