### PR TITLE
Bug 1772346: Fix InstallPlan link on Subscription page

### PR DESCRIPTION
**Pull request by spadgett**
/assign @rhamilto 
/kind bug

### CODE REVIEW

**Comment by spadgett** [comment]
etcdoperator v0 9 4 · Details · OKD 2019-11-18 13-43-25

**Comment by spadgett** [comment]
> find bug, get @spadgett to fix.

One character bug fixes are great for padding my GitHub stats :)

**Comment by rhamilto** [comment]
/hold
 
I don't think this is right as the new link uses the generic details page view (e.g., `k8s/ns/robb/operators.coreos.com~v1alpha1~InstallPlan/install-btvc4`) instead of `<InstallPlanDetails>` (e.g., `/k8s/ns/robb/installplans/install-btvc4`), which currently renders as a blank page.

**Comment by spadgett** [comment]
We should prefer the `operators.coreos.com~v1alpha1~InstallPlan` page, but we need to fix the white page for old links.

**Comment by spadgett** [comment]
It looks like the other problem is fixed by #3316

/hold cancel

**Pull request merged**
