### PR TITLE
CONSOLE-3814: Conditionally render "Users" and "Groups" nav items

### PR DESCRIPTION
**Pull request by TheRealJon**
- Add a new flag for the User and Group APIs
- Add the new flags to the Users and Groups nav items

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by TheRealJon** [comment]
/retest

Cluster install failed

**Comment by TheRealJon** [comment]
QE Approver
/assign @yanpzhan

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

**Comment by yanpzhan** [comment]
@TheRealJon I tried to deploy an external oidc(using keycloak) on the cluster launched against the pr, but when I choose this oidc, I could not login successfully. Do you have any doc to deploy a usable external oidc? I recorded my steps in test case: https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-68749

**Comment by TheRealJon** [comment]
Hi @yanpzhan! Thanks for taking a look at this! This PR is actually part of the BYO OIDC effort. @stlaz Is helping our team with that effort and might be more helpful in setting up an end-to-end environment, though we might not be at a stage where that's possible.

As far as testing the changes in this PR, I've created a [test branch](https://github.com/TheRealJon/console/tree/CONSOLE-3814-test) to mock the condition where User and Group APIs don't exist on the cluster. It filters out these APIs from the redux state.

There are similar use cases for other OpenShift APIs like DeploymentConfigs. As long as the APIs are removed from the cluster when they should be, I don't predict any issues on the front end.

**Comment by yanpzhan** [comment]
@TheRealJon Thanks. I bridged the console using your test branch, and could see that "Users" and "Groups" sub-menus are removed. I see the jira issue CONSOLE-3814 has been closed. I will check related progress from auth team. 
/label qe-approved

**Pull request merged**
