### PR TITLE
Topology: Fix to use full height at low resolutions in safari and on iOS

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Fixes https://jira.coreos.com/browse/ODC-2305

### CODE REVIEW

**Comment by christianvogt** [comment]
holding if we can get the fix in PF instead: https://github.com/patternfly/patternfly-react/issues/3312

**Comment by jeff-phillips-18** [comment]
With a bump to patternfly as well, let's hold off on upgrading PF versions.

/hold cancel

**Pull request merged**
