### PR TITLE
Bug 1913331: Remove master as default branch and use only when ref is given

### PR DESCRIPTION
**Pull request by rohitkrai03**
**Fixes**: https://issues.redhat.com/browse/ODC-5285

**Analysis / Root cause**: Github changed its default branch from `master` to `main`. Our default branch for detection was set as `master`.

**Solution Description**: After updating to `getContents` API, we do not need to send ref explicitly. It automatically checks the default branch. So ref is sent as param only if user enters git ref.

**Screen shots / Gifs for design review**: 

https://user-images.githubusercontent.com/6041994/103779726-269c7a80-505a-11eb-91b4-5e627fd18cc3.mov

**Unit test coverage report**: 

Screenshot 2021-01-06 at 8 03 18 PM

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [x] Safari
- [x] Edge

### CODE REVIEW

**Review by jerolimov — CHANGES_REQUESTED** [review]
@rohitkrai03 With this PR the Builder image detection doesn't work anymore.

You can test this with `https://github.com/eggheadio/egghead-next` (which use the main branch)
and my work `https://github.com/jerolimov/egghead-next` (which has also a master branch)

/hold

**Comment by rohitkrai03** [comment]
> https://github.com/eggheadio/egghead-next

@jerolimov I just tested with both of your repositories and builder image detection worked correctly for both of them.


https://user-images.githubusercontent.com/6041994/103874654-75e4b880-50f7-11eb-8277-625fcab053a3.mov

**Comment by jerolimov** [comment]
> I just tested with both of your repositories and builder image detection worked correctly for both of them.

Okay sorry, today they work here as well. I will test this later a little bit more, but drop my hold now already if someone else wants review it earlier.

/unhold

**Comment by rottencandy** [comment]
@rohitkrai03 seems like there's a merge conflict.

**Comment by divyanshiGupta** [comment]
@rohitkrai03 I have verified this locally and it works fine for me.
Will add lgtm once you resolve these merge conflicts.

**Comment by rohitkrai03** [comment]
/hold

Putting it on hold as need to rework on the logic a bit.

**Comment by rohitkrai03** [comment]
/unhold

Updated the PR with new logic.

**Pull request merged**
