### PR TITLE
Bug 1866337: Changes placeholder to 'Search by node name' in install page

### PR DESCRIPTION
**Pull request by vbnrh**
Signed-off-by: Vineet Badrinath <vbadrina@redhat.com>

### CODE REVIEW

**Comment by cloudbehl** [comment]
@vbnrh you are changing the generic component to fix the problem for OCS. You need to pass the placeholder from the OCS filter component.

**Review by bipuladh — COMMENTED** [review]
@andybraren can we replace `Search by name...` with `Search by "resource" name...`

**Comment by andybraren** [comment]
Reading through the [Bugzilla discussion](https://bugzilla.redhat.com/show_bug.cgi?id=1866337), I think Shiri's latest suggestion of `Search by node name` sounds good.

Ankush is correct that `Search` is the word we use elsewhere in the Console at the moment (with a few outliers), and if we ever decide to switch to `Filter` (which other products and [PatternFly's examples](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters) use) we can switch all of our fields at the same time.

I do wonder if the incorrect position of the filter contributed to (multiple?) users being confused during the study, but `Search by [resource] name` seems like a harmless adjustment to make it even clearer for now.

FYI @yuvalgalanti @shirimordechay

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
