### PR TITLE
Bug 1817394: Windows CDs use VirtIO instead of sata

### PR DESCRIPTION
**Pull request by glekner**

### CODE REVIEW

**Comment by yaacov** [comment]
Fixes:
https://bugzilla.redhat.com/show_bug.cgi?id=1817394
https://bugzilla.redhat.com/show_bug.cgi?id=1818714

**Comment by yaacov** [comment]
cherry-pick of: https://github.com/openshift/console/pull/5334

**Comment by yaacov** [comment]
@sdodson PTAL

**Comment by sdodson** [comment]
@sdodson there's no need to ping patch manager as long as the PR is only waiting on cherry-pick-approved.

**Pull request merged**
