### PR TITLE
[release-4.3] Bug 1800615: Serverless apiVersion from v1beta1 to v1

### PR DESCRIPTION
**Pull request by invincibleJai**
This is a cherry-pick of https://github.com/openshift/console/pull/4075

Serverless apiVersion from `v1beta1` to `v1`

### CODE REVIEW

**Comment by karthikjeeyar** [comment]
Verifed locally, works as expected. Now its fetching from `v1` instead of `v1beta1` api version.
/lgtm

**Comment by bparees** [comment]
skipping this one for approval this week due to bug severity and the number of other changes already accepted.

**Comment by invincibleJai** [comment]
@bparees will it be considered for this week ?

**Comment by bparees** [comment]
> @bparees will it be considered for this week ?

it is still on the list so it should be reviewed by this week's patch manager.  whether it will make the cut or not i can't say (i'm not patch manager this week) but i'd expect so.

**Pull request merged**
