### PR TITLE
ODC-7620: Use PatternFly Button progress indicator for all Create buttons that shows a loading indicator

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7620

**Solution Description**: 

When the submit button is not hidden, use the `isLoading` PF button prop instead of the `inProgress` prop in our `ButtonBar` component

**Screen shots / Gifs for design review**: 

https://github.com/openshift/console/assets/18614559/30096fc7-d865-4b0b-840d-9e391d3b4eb7

**Unit test coverage report**: 

Unchanged

**Test setup:**

n/a

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
Looks good 👍 

It covers all the forms we have in the ODC, the only form left it `instantiate-template.tsx`  

Can you please add isLoading here as well https://github.com/openshift/console/blob/master/frontend/public/components/instantiate-template.tsx#L322

**Review by vikram-raj — COMMENTED** [review]
/lgtm
/approve

**Comment by vikram-raj** [comment]
propagate from the epic
/label docs-approved
/label px-approved

**Comment by sanketpathak** [comment]
Verified on a cluster with admin and non-admin users

https://github.com/openshift/console/assets/10252230/08168573-3828-48c7-bd3e-e482731ee310

/label qe-approved

**Pull request merged**
