### PR TITLE
[release-4.12] OCPBUGS-1753: Fix OLM descriptor components deletes operand e2e test failing

### PR DESCRIPTION
**Pull request by jhadvig**
Manual backport of https://github.com/openshift/console/pull/12453

/assign @rhamilto

### CODE REVIEW

**Comment by yapei** [comment]
@jhadvig it looks like your branch `OCPBUGS-1753` needs to be rebased to `release-4.12` because there are ONLY two scenarios has been executed in the `e2e-gcp-console` tests
```
  Running:  descriptors.spec.ts                                                             (3 of 8)


  Using OLM descriptor components
  Logging in as kubeadmin
      create project
    ✓ displays list and detail views of an operand (44517ms)
      delete project
  Logging out
    ✓ creates an operand using the form (10961ms)


  2 passing (1m)
```

**Review by rhamilto — APPROVED** [review]
/lgtm

**Comment by jerolimov** [comment]
/retitle [release-4.12] OCPBUGS-1753: Fix OLM descriptor components deletes operand e2e test failing
/retest

**Pull request merged**
