### PR TITLE
Bug 1915200: [OCP 4.7+ OCS 4.6]Arbiter related Note should not show u…

### PR DESCRIPTION
**Pull request by TimothyAsirJeyasing**
Signed-off-by: Timothy Asir Jeyasingh <tjeyasin@redhat.com>

### CODE REVIEW

**Comment by TimothyAsirJeyasing** [comment]
@cloudbehl , @bipuladh , @afreen23 Please review

**Comment by cloudbehl** [comment]
@TimothyAsirJeyasing Thanks for PR. The code looks good.

Can you fix the commit message and be concise and don't overflow the description to the summary.

**Comment by cloudbehl** [comment]
frontend tests are failing: 
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/7903/pull-ci-openshift-console-master-frontend/1353593257040285696#1:build-log.txt%3A55

**Comment by cloudbehl** [comment]
@TimothyAsirJeyasing you have made two commits can you squash it with the same description. Please fix.

https://github.com/openshift/console/pull/7903/commits

**Comment by afreen23** [comment]
Please make one textual change here as well:
` 2 zones per node)` to ` 2 nodes per zone)`  
https://github.com/openshift/console/blob/79c6d1118674cb1a2c8dcfcfd1797f25492e699b/frontend/packages/ceph-storage-plugin/src/constants/ocs-install.ts#L25

Thanks!

**Comment by cloudbehl** [comment]
@TimothyAsirJeyasing you need to runt `yarn i18n` for the translations to work.

**Pull request merged**
