### PR TITLE
migrate context menu actions of WorkloadNode and application group to use new action extn mechanism

### PR DESCRIPTION
**Pull request by debsmita1**
**Sub-task:**
https://issues.redhat.com/browse/ODC-6370

**Solution description:**
- migrated context menu actions For WorkloadNode , Bindable Node , Connectors, application group
- removed unused files in helm plugin package

### CODE REVIEW

**Review by rottencandy — COMMENTED** [review]
- Looks like i18n files need updating.
- Page crashes when I right-click on empty topology page.


EDIT: Page seems to crash regardless of whether there are nodes in topology.

**Comment by debsmita1** [comment]
> * Looks like i18n files need updating.
> * Page crashes when I right-click on empty topology page.
>   
> 
> EDIT: Page seems to crash regardless of whether there are nodes in topology.

Replaced the `graphContextMenu` with `contextMenuActions` by mistake. Fixed it ! PTAL

**Comment by abhinandan13jan** [comment]
I see the `Edit application grouping` for vmnode on cluster 4.10.0-0.nightly-2021-11-28-164900
Screenshot 2021-11-29 at 3 36 59 PM

**Comment by debsmita1** [comment]
> I see the `Edit application grouping` for vmnode on cluster 4.10.0-0.nightly-2021-11-28-164900 Screenshot 2021-11-29 at 3 36 59 PM Screenshot 2021-11-29 at 3 30 31 PM

@abhinandan13jan  this is fixed here https://github.com/openshift/console/pull/10179

**Comment by rottencandy** [comment]
Apart from the Edit Application option, there seem to be a few other differences, like the "restart virtual machine", "migrate virtual machine" and the extra "copy ssh command" options.
Before:
after
After:
before

**Comment by debsmita1** [comment]
> Apart from the Edit Application option, there seem to be a few other differences, like the "restart virtual machine", "migrate virtual machine" and the extra "copy ssh command" options. Before: after After: before

migration of VM actions will be covered in this PR https://github.com/openshift/console/pull/10179 @yozaam

**Comment by yozaam** [comment]
> migration of VM actions will be covered in this PR #10179 @yozaam

https://github.com/openshift/console/pull/10305 has changed the actions that are shown
 e.g. it removed copy SSH

**Comment by abhinandan13jan** [comment]
sort imports

**Comment by abhinandan13jan** [comment]
tested using cluster bot
/label qe-approved
/label docs-approved
/label px-approved

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Pull request merged**
