### PR TITLE
Bug 1800867: don't repeat "Uninstall Operator" text in modal

### PR DESCRIPTION
**Pull request by spadgett**
https://bugzilla.redhat.com/show_bug.cgi?id=1800867

@itsptk Opinion? We could also leave the title "Uninstall Operator" and put the name in the message. I notice some other inconsistencies too (like using the question mark in one place and not the other).

/assign @itsptk 

Before:

Screen Shot 2020-02-08 at 9 15 22 AM

After:

Screen Shot 2020-02-08 at 9 16 48 AM

For reference, here is the delete project modal:

Screen Shot 2020-02-08 at 9 15 10 AM

### CODE REVIEW

**Comment by spadgett** [comment]
OK, I've noticed this is an issue for the normal delete modal, too. I've attempted to make these more consistent.

Before:

Screen Shot 2020-02-08 at 10 23 50 AM

Screen Shot 2020-02-08 at 10 24 00 AM

Screen Shot 2020-02-08 at 10 24 14 AM


After:

Screen Shot 2020-02-08 at 10 20 44 AM

Screen Shot 2020-02-08 at 10 12 20 AM

Screen Shot 2020-02-08 at 10 12 07 AM

**Comment by itsptk** [comment]
@spadgett I think this is all on the right track, thanks for making this consistent across the other dialogs as well.

A guideline exists for PF4 "Confirm a destructive action" with a modal: https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/modal
image
Any chance the icon could move to the top line to be in line with that? Let's keep the question mark on the title. 

Also, any chance of making the buttons left aligned or including the close "X" with this?

**Comment by spadgett** [comment]
I'll look at moving the icon.

I'd rather track the button alignment separately since that impacts every modal. @sg00dwin @rhamilto fyi

**Comment by itsptk** [comment]
@spadgett Ok after asking some designers they mentioned the button placement (left/right) has been an ongoing thing, so I agree probably not worth addressing here.

Would the close "X" button be doable here or more of a sweeping change?

**Comment by spadgett** [comment]
I'd say we track the `x` separately as well since it's an issue with all dialogs if you agree.

**Comment by itsptk** [comment]
Sounds good to me, thanks Sam.

**Comment by spadgett** [comment]
/assign @rhamilto 

I've found some others I've updated. Here are the screenshots:

Screen Shot 2020-02-10 at 12 47 03 PM
Screen Shot 2020-02-10 at 12 46 54 PM
Screen Shot 2020-02-10 at 12 39 20 PM
Screen Shot 2020-02-10 at 12 38 33 PM
Screen Shot 2020-02-10 at 12 38 17 PM

**Comment by itsptk** [comment]
LGTM!

**Comment by spadgett** [comment]
/hold
forgot to remove the orphaned style

**Comment by spadgett** [comment]
/hold cancel

Removed orphaned styles and fixed the catalog source dialog

**Comment by spadgett** [comment]
/hold
needs test updates

**Pull request merged**
