### PR TITLE
[release-4.12] OCPBUGS-12477: Users don't know what type of resource is being created by Import from Git or Deploy Image flows

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-7395

**Analysis / Root cause:**
NA

**Solution Description:**
Moved Resource type selection out of Advanced section

**Screen shots / Gifs for design review:**

https://user-images.githubusercontent.com/102503482/233934744-c2d5657a-4fbb-475e-9488-a79324ff9e1f.mov

****Unit test coverage report:****
NA

**Test setup:**

NA

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by jerolimov** [comment]
/retitle [release-4.12] OCPBUGS-12477: Users don't know what type of resource is being created by Import from Git or Deploy Image flows

**Comment by lokanandaprabhu** [comment]
Tested using cluster bot

/lgtm

https://user-images.githubusercontent.com/102503482/234235565-f0d75d05-531f-4652-888b-7f6553bc6c3d.mov

**Review by jerolimov — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Pull request merged**
