### PR TITLE
ODC-5507-Topology cypress cucumber setup

### PR DESCRIPTION
**Pull request by makambalaji**
**Problem**: Topology cypress cucumber setup
**solution**: Moved all the files to topology folder and added cypress configuration related files

### CODE REVIEW

**Comment by makambalaji** [comment]
This [PR: 8539](https://github.com/openshift/console/pull/8539 ) needs to merge, until then marking it as hold
/hold

**Comment by makambalaji** [comment]
PR: 8539 got merged
/hold cancel

**Review by gajanan-more — APPROVED** [review]
/lgtm

**Review by gajanan-more — APPROVED** [review]
/lgtm

**Review by gajanan-more — APPROVED** [review]
/lgtm

**Pull request merged**
