### PR TITLE
Remove PF3 alerts and convert remaining instances to PF4 alerts

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://jira.coreos.com/browse/CONSOLE-1594

Screen Shot 2019-07-03 at 1 44 24 PM

Note:  I was unable to test the vm-disk instance, but believe it should be fine based on the JSX changes alone.

### CODE REVIEW

**Comment by spadgett** [comment]
FYI prettier is enabled under packages, which is the cause of the lint failure

```
 /go/src/github.com/openshift/console/frontend/packages/kubevirt-plugin/src/components/vm-disks/vm-disks.tsx
   6:1   error  Delete `⏎`                                                                                                                                                                                                                                                                                                                            prettier/prettier
  76:25  error  Replace `<Alert·variant="danger"·action={<AlertActionCloseButton·onClose={()·=>·setCreateError(null)}·/>}·title={createError}·/>` with `(⏎··········<Alert⏎············variant="danger"⏎············action={<AlertActionCloseButton·onClose={()·=>·setCreateError(null)}·/>}⏎············title={createError}⏎··········/>⏎········)`  prettier/prettier 
```

**Comment by rhamilto** [comment]
Thanks, @spadgett.  Linter errors fixed.

**Comment by rhamilto** [comment]
Fixed broken unit test (or so I think).  @spadgett please tag again.

**Pull request merged**
