### PR TITLE
Rename `masthead.scss` to `_masthead.scss` to match existing convention

### PR DESCRIPTION
**Pull request by TheRealJon**
Just something that's been bugging me for a while.

### CODE REVIEW

**Comment by spadgett** [comment]
It's more than just a convention. This makes it a partial. But I think that's what we want here anyway.

/cc @rhamilto 
just to confirm before we merge

**Comment by rhamilto** [comment]
I'm good with that.

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
