### PR TITLE
Bug 1625776 - Default logging to auth=ERROR

### PR DESCRIPTION
**Pull request by spadgett**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1625776

/assign @jhadvig

### CODE REVIEW

**Comment by spadgett** [comment]
The drawback to this approach is that it is difficult to disable logging entirely, although I'm not sure we ever want that for any real cluster. `auth` package error logging really should be enabled by default, though.

**Comment by spadgett** [comment]
The one in the console repo: https://github.com/openshift/console/blob/master/auth/auth.go

**Comment by jhadvig** [comment]
Was a bit surprised to see "package=loglevel" to define the log level but now I see its as desired:
https://github.com/coreos/capnslog/blob/b3cd39bbbf4adf5efdb145ab1bcedaf76cc0a012/logmap.go#L173

**Comment by spadgett** [comment]
Yeah, it's part of the reason I didn't want to expose this in the config file yet. We should look how we want to expose this as an API.

**Comment by spadgett** [comment]
OK, looks like this isn't necessary. It wasn't just a log level setting. We weren't correctly handling the error on OAuth discovery failures.

**Comment by spadgett** [comment]
Closing... The real issue is fixed in #506

**Pull request closed without merging**
