### PR TITLE
Use plural instead of path

### PR DESCRIPTION
**Pull request by yaacov**
**Use plural instead of path**

Sorry, #1691 was closed automatically when I rebased :-(

This PR continues from https://github.com/openshift/console/pull/1691#issuecomment-502228245

> We can switch to plural, but we should remove path from all the models if it's not being used imo. I don't see a reason to keep both if they're always the same value.

And replace `path` with `plural`

### CODE REVIEW

**Comment by yaacov** [comment]
@alecmerdler @spadgett @mareklibra @vojtechszocs please review.

This PR, removed the  `path` from `k8sKind` and use `plural` in it's place.

**Comment by spadgett** [comment]
Looks like some usages were missed:

```
frontend/public/components/monitoring.tsx
72:const alertURL = (alert, ruleID) => `${AlertResource.path}/${ruleID}?${labelsToParams(alert.labels)}`;
73:const ruleURL = rule => `${AlertRuleResource.path}/${_.get(rule, 'id')}`;
94:  href: `${SilenceResource.path}/~new?${labelsToParams(alert.labels)}`,
104:  href: `${SilenceResource.path}/${silence.id}/edit`,
638:    history.replace(`${url.pathname}?${params.toString()}${url.hash}`);
753:        <Link className="co-resource-item__resource-name" data-test-id="silence-resource-link" title={obj.id} to={`${SilenceResource.path}/${obj.id}`}>{obj.name}</Link>
779:          <Link className="co-resource-item__resource-name" data-test-id="silence-resource-link" title={obj.id} to={`${SilenceResource.path}/${obj.id}`}>{obj.name}</Link>
924:        history.push(`${SilenceResource.path}/${encodeURIComponent(_.get(data, 'silenceId'))}`);
996:          <Link to={data.id ? `${SilenceResource.path}/${data.id}` : SilenceResource.path} className="btn btn-default">Cancel</Link>
```

**Comment by yaacov** [comment]
@spadgett updated the monitoring file, please review.

**Pull request merged**
