### PR TITLE
Bug 1979562:  Cluster operators: don't show messages when neither progressing, degraded or unavailable

### PR DESCRIPTION
**Pull request by cyril-ui-developer**
/assign @spadgett 

### Before:

Screen Shot 2021-08-11 at 12 58 39 PM

### After:
Screen Shot 2021-09-20 at 2 59 48 PM

### CODE REVIEW

**Review by spadgett — CHANGES_REQUESTED** [review]
We still want to show the messages in the other states. We only hide them if

Degraded: false
Progressing: false
Available: true

**Comment by cyril-ui-developer** [comment]
> We still want to show the messages in the other states. We only hide them if
> 
> Degraded: false
> Progressing: false
> Available: true

@spadgett I couldn't find conditions for `Degraded: false` and `Progressing: false` for displaying messages. I have removed the condition for `Available: true`.  So `Available` would be hidden and default to `-`. Please take a look and let me know if you have any concerns. Thanks.

**Comment by cyril-ui-developer** [comment]
> We still want to show the messages in the other states. We only hide them if
> 
> Degraded: false
> Progressing: false
> Available: true


> We still want to show the messages in the other states. We only hide them if
> 
> Degraded: false
> Progressing: false
> Available: true

@spadgett I couldn’t find conditions for `Degraded: false` and `Progressing: false` for displaying messages.Were you referring to these conditions? 
https://github.com/openshift/console/blob/master/frontend/public/module/k8s/cluster-operator.ts#L19
https://github.com/openshift/console/blob/master/frontend/public/module/k8s/cluster-operator.ts#L24


 I removed the message property for `Available: true` . So the  `Available` message would be hidden and default to `-`. Please take a look and let me know if you have any concerns. Thanks.

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
