### PR TITLE
Bug 2020001: Update demo dynamic plugin dockerfile to reflect dir structure change

### PR DESCRIPTION
**Pull request by jcaianirh**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2020001

cc: @spadgett

### CODE REVIEW

**Comment by yapei** [comment]
I can see error when trying to build 
```
Removing intermediate container 33776478970d
 ---> e31d8d865314
Step 6/15 : WORKDIR /src/console/dynamic-demo-plugin
 ---> Running in d35c770f2f35
Removing intermediate container d35c770f2f35
 ---> d69b53315c7d
Step 7/15 : RUN yarn install &&     yarn build
 ---> Running in b6f35100c1f6
yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > react-i18next@11.12.0" has unmet peer dependency "i18next@>= 19.0.0".
warning "@openshift-console/dynamic-plugin-sdk-webpack > webpack > terser-webpack-plugin@2.3.8" has incorrect peer dependency "webpack@^4.0.0 || ^5.0.0".
warning " > copy-webpack-plugin@6.4.1" has unmet peer dependency "webpack@^4.37.0 || ^5.0.0".
warning " > file-loader@1.1.11" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > react-dom@17.0.2" has incorrect peer dependency "react@17.0.2".
warning " > webpack-cli@4.5.0" has unmet peer dependency "webpack@4.x.x || 5.x.x".
warning "webpack-cli > @webpack-cli/configtest@1.0.1" has unmet peer dependency "webpack@4.x.x || 5.x.x".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 174.10s.
yarn run v1.22.10
$ yarn clean && NODE_ENV=production yarn ts-node node_modules/.bin/webpack
$ rm -rf dist
$ ts-node -O '{"module":"commonjs"}' -I '/node_modules/(?!(@openshift-console)/)/' node_modules/.bin/webpack
Hash: 4dd9a8b6ae46575fdd39
Version: webpack 5.0.0-beta.16
Time: 47979 ms
Built at: 2021-11-04 01:33:23
38 assets
Entrypoint console-demo-plugin = plugin-entry.js (plugin-entry.js.map)
container entry 42 bytes [built]
./utils/example-navs.tsx + 1 modules 2.12 KiB [built]
./utils/bar.ts 138 bytes [built]
./utils/perspective.ts + 1 modules 1.03 KiB [built]
./utils/telemetry.ts 4.23 KiB [built]
./components/ExtensionConsumer.tsx 1.88 KiB [built]
./components/UtilityConsumer.tsx 1.26 KiB [built]
./components/Nav.tsx 684 bytes [built]
./components/ListPage.tsx 2.77 KiB [built]
overridable react -> react 42 bytes [built]
overridable react-i18next -> react-i18next 42 bytes [built]
overridable @patternfly/react-core -> @patternfly/react-core 42 bytes [built]
overridable react -> react 42 bytes [built]
overridable react-i18next -> react-i18next 42 bytes [built]
overridable @openshift-console/dynamic-plugin-sdk -> @openshift-console/dynamic-plugin-sdk 42 bytes [built]
    + 408 hidden modules

ERROR in container entry K8sAPIConsumer[6]
Module not found: Error: Can't resolve './components/K8sConsumer/K8sAPIConsumer.tsx' in '/src/console/dynamic-demo-plugin/src'

(node:82) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.modules was changed from Array to Set (using Array method 'reduce' is deprecated)
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:82) [DEP_WEBPACK_MODULE_ERRORS] DeprecationWarning: Module.errors was removed (use getErrors instead)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn install &&     yarn build' returned a non-zero code: 1
```

**Comment by jhadvig** [comment]
@yapei the error you are hitting is a separate issue. Check https://bugzilla.redhat.com/show_bug.cgi?id=2019986

**Review by jhadvig — CHANGES_REQUESTED** [review]
@jcaianirh thanks for the fix. We also need to update the ` Dockerfile.plugins.demo2` file

**Comment by jcaianirh** [comment]
@yapei I've added all necessary script updates to this pr so it can all be tested at the same time. You should no longer see the error you pointed out above with the latest commits. 

@jhadvig I added the changes to demo2 as requested.

Thanks all for the comments.

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
/hold

We have two PRs with some of the same changes. See also #10395

**Comment by vojtechszocs** [comment]
@jcaianirh Hi, #10395 already takes care of all the changes needed to build the Console demo plugin - except the Dockerfiles :smiley:

**Comment by jcaianirh** [comment]
@spadgett @vojtechszocs reverted yarn.lock and package.json files

**Pull request merged**
