### PR TITLE
CONSOLE-2390: i18n build page and image stream page

### PR DESCRIPTION
**Pull request by wansc2016**
This PR covers i18n support for

Build list page
Build details page
Cancel build modal
Image stream list page
Image stream detail page

See [CONSOLE-2390](https://issues.redhat.com/browse/CONSOLE-2390) (Do not have access, is it the correct issue number?)

It depends on https://github.com/openshift/console/pull/6913

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
/lgtm cancel

Build error:

```
ERROR in /go/src/github.com/openshift/console/frontend/public/components/build.tsx
ERROR in /go/src/github.com/openshift/console/frontend/public/components/build.tsx(171,13):
TS17001: JSX elements cannot have multiple attributes with the same name.

ERROR in /go/src/github.com/openshift/console/frontend/public/components/build.tsx
ERROR in /go/src/github.com/openshift/console/frontend/public/components/build.tsx(189,13):
TS17001: JSX elements cannot have multiple attributes with the same name.
```

**Comment by wansc2016** [comment]
Added image stream part and fixed build error

**Comment by spadgett** [comment]
@wansc2016 Will need rebase.

/assign @ahardin-rh @sferich888 
for approvals

**Review by spadgett — APPROVED** [review]
/lgtm

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
