### PR TITLE
Bug 1945637: odc 5666 fixing pipelines scripts issues

### PR DESCRIPTION
**Pull request by makambalaji**
**problem**: pipelines scripts are failed
**solution**:  Fixed the pipelines scripts and did minor changes to existing scripts

**Browser version**: Chrome 89

Note: One bug is raised as part of the failure : https://issues.redhat.com/browse/ODC-5691

**Execution process**:  
Execute `yarn run test-cypress-pipelines-headless`

image

### CODE REVIEW

**Comment by sanketpathak** [comment]
Balaji getting these error while  locally running  the tests

Screenshot from 2021-03-21 01-11-05
Screenshot from 2021-03-21 02-29-44
Screenshot from 2021-03-21 01-56-18

**Comment by makambalaji** [comment]
@sanketpathak - second screenshot says, code is not updated on your local. because on cluster, `Pipeline Run details` but in above screenshot it is displaying as `Pipeline run details`
image

**Comment by VeereshAradhya** [comment]
Ran tests and no failures were seen.
/lgtm

**Pull request merged**
