### PR TITLE
OCPBUGS-43780: GCP environment parament cannot shown on Operator subscription page

### PR DESCRIPTION
**Pull request by cyril-ui-developer**

### CODE REVIEW

**Comment by cyril-ui-developer** [comment]
/assign @jhadvig 

@XiyunZhao Could you please verify this fix?

**Comment by XiyunZhao** [comment]
PR has been tested on pr-merge testing, now the 4 additional fields (Project_Number,POOL_ID,PROVIDER_ID,SERVICE_ACCOUNT_EMAIL) can be shown on the operator subscription now
/label qe-approved

**Pull request merged**
