### PR TITLE
Monitoring: Use the label "Alerting Rule" instead of "Alert Rule"

### PR DESCRIPTION
**Pull request by kyoto**

### CODE REVIEW

**Comment by cshinn** [comment]
@kyoto Good catch!

**Comment by kyoto** [comment]
FYI @cshinn, @christianvogt

**Comment by spadgett** [comment]
Looks like I broke the OLM tests splitting them out. Investigating.

> WebDriverError: unknown error: unhandled inspector error: {"code":-32000,"message":"Cannot navigate to invalid URL"}

Skipping for now since this PR has no impact to OLM

**Comment by spadgett** [comment]
Hm, e2e-aws-console-olm failed because of

```
++ oc get route console -n openshift-console -o 'jsonpath={.spec.host}'
Error from server (NotFound): the server could not find the requested resource (get routes.route.openshift.io console)
```

Maybe a one-off error? The route should be there if the install completed. Console operator log say the route is there:

```
time="2019-03-14T15:53:25Z" level=info msg="running sync loop 4.0.0"
time="2019-03-14T15:53:25Z" level=info msg="validating console route..."
time="2019-03-14T15:53:25Z" level=info msg="route exists and is in the correct state"
```

**Pull request merged**
