### PR TITLE
OU-110: Observe > Dashboards : Code Consolidation Fixes

### PR DESCRIPTION
**Pull request by zhuje**
**Related:** 
[OU-110 Original PR](https://github.com/openshift/console/pull/12422)

**Summary**
A separate PR was created to address [additional comments in the original PR](https://github.com/openshift/console/pull/12422#pullrequestreview-1302754796). 

**Testing**
Testing will be the same as the [description in the original PR](https://github.com/openshift/console/pull/12422#issue-1526460887).

**Product and Documentation** 
This PR does not change any initial functionality found in [original PR](https://github.com/openshift/console/pull/12422) and does not need re-evaluation by px or docs. 
See original approvals : 
- px: https://github.com/openshift/console/pull/12422#issuecomment-1431862035
- docs: https://github.com/openshift/console/pull/12422#pullrequestreview-1301306103

### CODE REVIEW

**Comment by kyoto** [comment]
This is a refactoring change. There should be no user visible changes.

/label px-approved
/label docs-approved

**Comment by zhuje** [comment]
/assign @yapei
for approval

**Comment by yanpzhan** [comment]
Tested on cluster launched against the pr, prepare data following testing instructions in https://github.com/openshift/console/pull/12422 description, then check on Observe -> Dashboards page, switch JZ-TEST dashboard, check the request url, metrics queries fetch from custom-defined Prometheus via proxy configured by plugin /api/proxy/plugin/dashboards-console-plugin/backend/proxy/.
Screenshot from 2023-02-28 19-16-01
/label qe-approved

**Pull request merged**
