### PR TITLE
[release-4.12] OCPBUGS-34564: Routes created by devfiles do not always use HTTPS

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
Manual chrrypick for PR - https://github.com/openshift/console/pull/13827

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Tested using cluster bot. Working fine.

/lgtm

Uploading Screen Recording 2024-05-29 at 2.08.15 PM.mov…

**Comment by lokanandaprabhu** [comment]
Hi @vikram-raj / @Lucifergene ,

Can you please review this PR?

**Review by vikram-raj — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
