### PR TITLE
Bug 2102681: Fix zh locale (greater than pod)

### PR DESCRIPTION
**Pull request by raspbeep**
https://bugzilla.redhat.com/show_bug.cgi?id=2102681

Signed-off-by: Pavel Kratochvil <pakratoc@redhat.com>

### CODE REVIEW

**Comment by raspbeep** [comment]
@kyoto @rhamilto Could you review this one please?

**Review by rhamilto — APPROVED** [review]
/lgtm

**Comment by rhamilto** [comment]
This bug also exists in `ja` and `ko`.  https://github.com/openshift/console/blob/master/frontend/public/components/modals/configure-update-strategy-modal.tsx#L76 is the source of the bug.  For some reason, the keys aren't generating properly.

**Comment by rhamilto** [comment]
> For some reason, the keys aren't generating properly.

@cyril-ui-developer, do you know how `*_plural` keys work in the non-en files?

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
