### PR TITLE
[release-4.15] OCPBUGS-29842: Switch to service from external result route endpoint

### PR DESCRIPTION
**Pull request by vikram-raj**
Manual cherry-pick PR https://github.com/openshift/console/pull/13624

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
Verified.
https://github.com/openshift/console/assets/2561818/c7470b46-fa97-407a-852a-90b30dd7e893

**Review by lokanandaprabhu — APPROVED** [review]

**Pull request merged**
