### PR TITLE
Correcting Pipelines Package Failures

### PR DESCRIPTION
**Pull request by hemantsaini-7**
opening a PR for checking nightly failures of Pipelines package, and correcting them.

**Jira Id:**
- Story: [ODC-7223](https://issues.redhat.com/browse/ODC-7223)

### CODE REVIEW

**Comment by hemantsaini-7** [comment]
retest

**Comment by sanketpathak** [comment]
CI is green
/lgtm

**Comment by hemantsaini-7** [comment]
Changes only affect E2E tests
/label qe-approved
/label docs-approved
/label px-approved

**Pull request merged**
