### PR TITLE
Bug 1779116: vm template should create url import dataVolumes on its creation

### PR DESCRIPTION
**Pull request by suomiy**
- show URL provision source for templates
- provision source changed to Disk (Attach Cloned Disk) for vms created
from such templates
- add warning to the template disk modal

@mareklibra @matthewcarleton Can you take a look?

As you can see bellow, I changed a provision source of VM to `Disk`  to truthfully reflect the situation.

I added a warning to disk-modal in template creation to show the difference between template url and vm url.

Is this enough? Should I show this also in the general tab so the user knows what is going on? Or in the review?

### CODE REVIEW

**Comment by matthewcarleton** [comment]
@suomiy just so I know I understand this correctly:
1. User creates a template and the source is via a URL
2. Datavolume is created with what was provided via the URL
3. VM is created with that Datavolume and not via the URL from the template

**Comment by suomiy** [comment]
> @suomiy just so I know I understand this correctly:
> 3. VM is created with that Datavolume and not via the URL from the template

yup, although VM clones the PVC and does not use the original Datavolume or original PVC ever again

I guess we should modify that disk modal message a bit?

**Comment by matthewcarleton** [comment]
@suomiy ya I'm wondering why we are alerting them of this. Is it something that should concern them? Is it just because this will take storage space so we want to let them know?

**Comment by suomiy** [comment]
Because the behaviour is different for VM and VM template and for other VM template datavolumes

**Comment by matthewcarleton** [comment]
Do you think we should be talking about DataVolumes here if we don't show them anywhere in the UI?

**Comment by suomiy** [comment]
Not sure. Maybe PVC should be enough? - but that takes a while before it is ready (datavolume implies that)

**Comment by matthewcarleton** [comment]
I'd vote for PVC for now. At least it's somewhat more understandable. Although we still may confuse them with it b/c VMs deal in disk terminology. 
I wonder if we could do something like this:
Screen Shot 2019-12-06 at 1 27 44 PM

**Comment by suomiy** [comment]
That is just a consequence and doesn't say what is going on currently. They might not even expect that some pvc gets allocated with the creation of template.

I think PVC should be ok, as that is a pretty common term in k8s. Datavolumes not so much - unless you are familiar with CDI,

**Comment by matthewcarleton** [comment]
ok. It would be nice eventually if we could surface the idea of a PVC in the creation flow.

**Comment by suomiy** [comment]
updated

aa

**Comment by mareklibra** [comment]
/lgtm

I do not think we need to expose this back-end stuff to the user so explicitly.
IMO, (s)he do not care. A note in the documentation might be good enough.

But as this is already agreed, I am not against it.

**Comment by matthewcarleton** [comment]
@mareklibra I am relying on the developer perspective here to better understand the use case for this. I do think that exposing PVCs here don't really help a CNV user since they don't necessarily know what a PVC is and won't get a better understanding of that by creating a VM from this template. I don't feel strongly about showing/hiding this in general though.

**Pull request merged**
