### PR TITLE
OCPBUGS-5360: re-enable operator-install-single-namespace.spec.ts test

### PR DESCRIPTION
**Pull request by rhamilto**
Re-enable operator-install-single-namespace.spec.ts test as the 3scale operator is now installing fine despite no activity on https://issues.redhat.com/browse/THREESCALE-9015

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by rhamilto** [comment]
@jhadvig, mind re-tagging?  It appears the operator name changed again.

**Pull request merged**
