### PR TITLE
Bug 1982751: i18n misses in move subscription modal

### PR DESCRIPTION
**Pull request by debsmita1**
**Fixes:**
https://issues.redhat.com/browse/OCPBUGSM-32105

**Solution description:**
passing label key, if present, to the title

**Screenshots:**

**Trigger:**
Before:
t-before2
t-before

After:
t-after2
t-after

**Subscription:**
Before:
S-before-2
S-before

After:
s-after-2
s-after

### CODE REVIEW

**Review by rottencandy — COMMENTED** [review]
Build is failing, looks like the locale files need to be updated.

**Comment by invincibleJai** [comment]
/approve

verified works as expected

**Review by rottencandy — APPROVED** [review]
/lgtm

**Pull request merged**
