### PR TITLE
Bug 1803192: use monitoring config from openshift-config-managed namespace

### PR DESCRIPTION
**Pull request by simonpasquier**
This is the counter part of https://github.com/openshift/cluster-monitoring-operator/pull/654

### CODE REVIEW

**Comment by spadgett** [comment]
We should switch to the custom endpoint we added to the console backend in #3912, which will read config maps from openshift-config-managed. Not all users will be able to read the config map directly.

This is tracked by https://bugzilla.redhat.com/show_bug.cgi?id=1795398

**Comment by spadgett** [comment]
Disregard, I see now this is for the URLs, not the grafana config.

**Comment by spadgett** [comment]
Do we still have the same RBAC problem as before? Not all users can read config maps in the openshift-config-managed namespace.

**Comment by simonpasquier** [comment]
@spadgett let me research this.

**Comment by benjaminapetersen** [comment]
I believe we still have the RBAC issue.
Now that the configmap is in openshift-config-managed, the operator can read it & pass the information along.

**Comment by s-urbaniak** [comment]
Indeed, now I recall I mentioned this elsewhere, that these configuration should be funneled through the console-backend, where the console-backend (be it the underlying operator or the backend proxy) has the RBAC to read out the configmaps.

**Comment by spadgett** [comment]
/bugzilla refresh
/hold

I think this needs console-operator changes to wire through the URLs as console config.

**Comment by simonpasquier** [comment]
Closing this PR as it requires more work that is going to be handled by the console team.

**Pull request closed without merging**
