### PR TITLE
CONSOLE-2975: Migrate from Node Sass to Dart Sass

### PR DESCRIPTION
**Pull request by spadgett**
Node Sass is deprecated. Now that #10080 has merged, migrate to the newest version of Dart Sass. See the note in the Node Sass README:

https://github.com/sass/node-sass

Remove deprecated use of `/` for division in Sass.

https://sass-lang.com/documentation/breaking-changes/slash-div

/cc @kdoberst @rhamilto @sg00dwin

### CODE REVIEW

**Comment by kdoberst** [comment]
I'm getting errors when trying to run the dev server. I'll try again tomorrow.

**Comment by kdoberst** [comment]
Able to download this and take a look.  Looks good.  Did notice that FontAwesome does still use the slash for dividing even in the most current version ([Example](https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_variables.scss#L12))- so there isn't much we can do there.  

Wondering if we need to give other teams a "heads-up" for example there appears to be a slash for division in the [operator-lifestyle-manager package](https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/style.scss#L263)

**Comment by spadgett** [comment]
> Able to download this and take a look. Looks good. Did notice that FontAwesome does still use the slash for dividing even in the most current version ([Example](https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_variables.scss#L12))- so there isn't much we can do there.

Yeah, there's an issue tracking: https://github.com/FortAwesome/Font-Awesome/issues/17946

I wonder if we still need FontAwesome. Maybe for the template icons? @rhamilto do you know?

> Wondering if we need to give other teams a "heads-up" for example there appears to be a slash for division in the [operator-lifestyle-manager package](https://github.com/openshift/console/blob/master/frontend/packages/operator-lifecycle-manager/src/style.scss#L263)

Hm, I must have missed some. There is a utility that automates the fixes. Strange I didn't get the deprecation warning (or maybe I just missed it).

**Comment by spadgett** [comment]
/assign @yapei 
for QE review

We simply need a basic regression test to make sure the console styles look OK.

/label px-approved
/label docs-approved

No user-visible changes.

**Comment by rhamilto** [comment]
> I wonder if we still need FontAwesome. Maybe for the template icons? @rhamilto do you know?

We still need it.  In addition to the template icons, we have numerous references to `fa-` classes in the code.

**Comment by rhamilto** [comment]
I should add many of the latter instances could be migrated to [PatternFly](https://github.com/patternfly/patternfly-react/blob/main/packages/react-icons/README.md) since it includes FontAwesome, but the templates still rely on the `fa-` classes, so I'm not sure it's worth it?

**Comment by spadgett** [comment]
@kdoberst I fixed up a few more uses of `/` in our styles and removed the now unnecessary `SKIP_SASS_BINARY_DOWNLOAD_FOR_CI` from our Dockerfile.

@sosiouxme FYI, we're no longer using Dart Sass after this change (in master anyway, it's still there in older release branches).

**Comment by spadgett** [comment]
@sosiouxme We might be able to get rid of python3 and the node headers from the Dockerfile as well, but I'm not sure.

**Comment by spadgett** [comment]
Rebased

**Comment by spadgett** [comment]
@sosiouxme Thanks, I made the change to the Dockerfile in a separate commit in this PR. If there are problems, we can roll that back.

/hold

**Comment by spadgett** [comment]
/hold cancel

This should be ready... @kdoberst Another look?

**Comment by kdoberst** [comment]
@spadgett I downloaded the code and noticed a couple of things.  

The first is that when you make a change, you get warnings like the following `WARNING in Conflict: Multiple assets emit different content to the same filename app-bundle.7ead3c69f31c01ee59e6.css.map`. I know there is (or will be a fix) in master, I'm assuming this isn't an issue.

I did notice another weird thing.  The first time you click on the context switcher (Administrator / Developer drop-down) the entire screen flashes.  Drop down works properly.  This effect isn't in the 4.10.0-0.nightly-2021-10-16-173656 nightly.

**Comment by spadgett** [comment]
I've rebased the PR. @kdoberst I'm going to investigate the issues you're seeing. The conflict warning has since been fixed.

**Comment by spadgett** [comment]
@kdoberst I can't reproduce the flicker

**Comment by kdoberst** [comment]
> @kdoberst I can't reproduce the flicker

@spadgett 
It is really weird because I don't see anything in the PR that would cause it.  I'm including a video of what I'm seeing. 
With that said, it builds, the CSS looks fine  - I'm OK /lgtm'ing this especially if I'm the only one seeing the issue.


https://user-images.githubusercontent.com/82059948/142291608-19440cd3-ba78-42ff-800d-8961e7215ba4.mov

**Comment by spadgett** [comment]
@kdoberst I don't doubt that you're seeing it... I just can't reproduce. How did you build?

Maybe we can have someone else on the team try or try with cluster-bot? @sg00dwin Any chance you can help test?

https://user-images.githubusercontent.com/1167259/142637864-b2df650d-219d-4144-a6d7-e3e347587a34.mov

**Comment by kdoberst** [comment]
> @kdoberst I don't doubt that you're seeing it... I just can't reproduce. How did you build?
> 
> Maybe we can have someone else on the team try or try with cluster-bot? @sg00dwin Any chance you can help test?
> 

@spadgett Just checking out the commit locally, running yarn install (just to be sure), building the back end (again just to be sure), and then running yarn dev.  As you can see above, it is a pretty minor flash, and only on the first time you change the context - everything else I checked looked good.  🤷‍♀️

**Comment by florkbr** [comment]
Pulled down Sam's changes against a nightly 4.10 cluster (4.10.0-0.nightly-2021-12-02-140313) to see if I could reproduce @kdoberst's screen flicker issue. I am unable to reproduce the issue in Firefox 78.15.0esr and Chrome 96.0.4664.55 (Official Build) (x86_64).

Dec-03-2021 11-31-17

**Pull request merged**
