### PR TITLE
Bug 2023865: Pull in css to support react-virtualized-extension, remove overrides and scope class to prevent conflicts with dynamic plug-in screens

### PR DESCRIPTION
**Pull request by sg00dwin**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2023865
https://issues.redhat.com/browse/CONSOLE-2998

### CODE REVIEW

**Comment by sg00dwin** [comment]
@spadgett would you mind adding the lgtm on this PR. It finally passed. \0/ 
You originally reviewed these opened here https://github.com/openshift/console/pull/10483 but I inadvertently closed it and couldn't reopen it.

**Comment by rhamilto** [comment]
@sg00dwin, it looks like you mistakenly push the wrong commit?

**Pull request closed without merging**
