### PR TITLE
Automation: Add flows should allow user to pick from a list of pipelines

### PR DESCRIPTION
**Pull request by sanketpathak**
**Fix**: https://issues.redhat.com/browse/ODC-6410

**Problem**: As a user, I need the ability to select the from list of pipeline in Add form

**Solution**: This script will automate the add page to select the from list of pipeline

**Test Setup**:

Cluster should be running on local

Check the TAGS in frontend/packages/pipelines-plugin/integration-tests/cypress.json file be: ""("TAGS": "@pipelines and @[odc-6372](https://issues.redhat.com/browse/odc-6372) and not (@manual or @to-do or @un-verified or @broken-test)"",

Command to execute:

```
export NO_HEADLESS=true && export CHROME_VERSION=$(/usr/bin/google-chrome-stable --version)
BRIDGE_KUBEADMIN_PASSWORD=xry7n-UVpxC-6hXFf-sgjEi
BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.jakumar-2021-09-01-193941.devcluster.openshift.com
export BRIDGE_KUBEADMIN_PASSWORD
export BRIDGE_BASE_ADDRESS
export BRIDGE_API
oc login -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD https://api.jakumar-2021-09-01-193941.devcluster.openshift.com:6443/ --insecure-skip-tls-verify
oc apply -f ./frontend/integration-tests/data/htpasswd-secret.yaml
oc patch oauths cluster --patch "$(cat ./frontend/integration-tests/data/patch-htpasswd.yaml)" --type=merge
./test-cypress.sh -p dev-console
```
Or 
Run a cluster locally and execute the command `npm run test-cypress-pipelines` simultaneously

Execute the create-from-add-options feature file and check for the P-01-TC11 test case

**Checks for approving Epic scenarios Automation PR:**

- [x] Execute the @to-do tagged gherkin scripts manually
- [x] Convert the @to-do gherkin scripts to cypress automation scripts
- [x] Once scripts are automated, replace tag @to-do with @epic-number
- [x] Execute the scripts in the Local/Remote cluster
- [x] Update [Automation Report](https://docs.jboss.org/display/ODC/Automation+Status+Report)

**Browser**
Chrome 90

**Test Execution Screenshot:**

### CODE REVIEW

**Comment by makambalaji** [comment]
working as expected wtih "TAGS": "@pipelines and @odc-6372 and not (@manual or @to-do or @un-verified)"
/lgtm
image

**Comment by makambalaji** [comment]
For merging purpose, adding below labels
/label qe-approved
/label px-approved
/label docs-approved

**Comment by jrichter1** [comment]
Runs green with the selected tag.

**Pull request merged**
