### PR TITLE
add data-test-id for console dashboard components

### PR DESCRIPTION
**Pull request by dantrainor**

### CODE REVIEW

**Comment by spadgett** [comment]
Please add the attributes in the same PR as the tests so we can see how they will be used.

**Comment by honza** [comment]
> Please add the attributes in the same PR as the tests so we can see how they will be used.

They are in this PR. Only the metal3 ones are elsewhere to ease the review burden.

**Comment by dantrainor** [comment]
Also added data-test-id attributes for the counts of such Items

**Comment by spadgett** [comment]
> They are in this PR. Only the metal3 ones are elsewhere to ease the review burden.

I'm confused... These are added for specific integration tests, correct? There aren't any tests in this PR. It's difficult to evaluate if the changes make sense without seeing how they're used.

**Comment by dantrainor** [comment]
> > They are in this PR. Only the metal3 ones are elsewhere to ease the review burden.
> 
> I'm confused... These are added for specific integration tests, correct? There aren't any tests in this PR. It's difficult to evaluate if the changes make sense without seeing how they're used.

They are to facilitate the integration tests as part of #1886, which were originally written using brittle xpaths.  These changes and the ones in #2288 are used for more precise identification of the elements needed to test against.  This PR was split from #2288 to try and get the changes reviewed and accepted quicker, with the idea of having a different set of reviewers able to review #2288 quicker.

**Comment by spadgett** [comment]
Right, understood. But it's impossible to review this change in isolation, and it should only be merged when the tests are merged. IMO, breaking it out actually makes reviews harder.

**Comment by dantrainor** [comment]
> Right, understood. But it's impossible to review this change in isolation, and it should only be merged when the tests are merged. IMO, breaking it out actually makes reviews harder.

Understood, thanks for the feedback.

Can you provide some guidance on how to proceed with these PRs as they relate to each other?  Should #2287 and #2288 become part of #1886?

**Comment by spadgett** [comment]
Yes, I would roll both changes into #1886

**Comment by dantrainor** [comment]
> Yes, I would roll both changes into #1886

I appreciate the help thank you.

**Comment by dantrainor** [comment]
This is going to become part of #1886

**Pull request closed without merging**
