### PR TITLE
PF5.3 package updates

### PR DESCRIPTION
**Pull request by jcaianirh**

### CODE REVIEW

**Comment by jcaianirh** [comment]
Error: 
```
could not run steps: step console-plugin-demo failed: error occurred handling build console-plugin-demo-amd64: the build console-plugin-demo-amd64 failed after 5m4s with reason DockerBuildFailed: Dockerfile build strategy has failed. 
[36mINFO[0m[2024-05-14T15:37:26Z] Reporting job state 'failed' with reason 'executing_graph:step_failed:building_project_image' 
```

**Comment by jcaianirh** [comment]
QE Approver:
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

**Comment by yapei** [comment]
@XiyunZhao is working on PR verification

**Comment by XiyunZhao** [comment]
No issue(layout, action of button, basic function etc.) was found on the regression and manual test
/label qe-approved

**Comment by jcaianirh** [comment]
` │ ✖  crud/namespace-crud.cy.ts                02:09        3        2        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  crud/other-routes.cy.ts                  04:54       23       16        7        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  crud/quotas.cy.ts                        00:50        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  crud/resource-crud.cy.ts        `

**Pull request closed without merging**
