### PR TITLE
Update advanced form to only show the route port when serverless is checked

### PR DESCRIPTION
**Pull request by joshuawilson**
This is for the task: https://jira.coreos.com/browse/ODC-1357

It does NOT deal with the route checkbox, nor does it deal with any variable name changes. 
Serverless-routing

### CODE REVIEW

**Comment by rohitkrai03** [comment]
@joshuawilson Target port for serverless can be any port and not only the open ports for the builder image?

**Comment by joshuawilson** [comment]
as far as I know it can be any port, early today PM and knative team said that is should NOT be a dropdown since it can be anything.

**Pull request merged**
