### PR TITLE
OCPBUGS-29528: List of default Camel K event sources disappears when adding a custom event source

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-29528

**Analysis / Root cause**: 
If there is any Kamelet resource created for particular namespace, then only that resource is considered by ignoring  kamelets resource available in global namespace and camel k operator namespace

**Solution Description**: 
With this change, kamelets resource from particular namespace, global namespace and camel k operator namespace are considered with unique check for `metadata.uid` to avoid duplicated

**Screen shots / Gifs for design review**: 

--- Before---

https://github.com/openshift/console/assets/102503482/c045effc-3388-43d9-a431-139072353f66

---After---

https://github.com/openshift/console/assets/102503482/9a1d818c-243f-4444-9d04-e90617219109

**Unit test coverage report**: 
NA

**Test setup:**

    1. install global Camel K operator in operator namespace (e.g. openshift-operators)
    2. list all available event sources in "default" user namespace and see all Kamelets listed as event sources/sinks
    3. add a custom Kamelet custom resource to the default namespace
    4. see the list of available event sources only listing the custom Kamelet and the default Kamelets are gone from that list

     For example of a custom Kamelet event source: Refer comments in https://issues.redhat.com/browse/OCPBUGS-29528

    

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
Can you also checks non-admin user scenario here. As a non-admin user I am not able to see the event sources catalog even after giving create access for kamelets to the user.

**Comment by lokanandaprabhu** [comment]
If I update the permission for the user, I am able to see the default and newly created event sources. I gave admin access to developer user.

https://github.com/openshift/console/assets/102503482/72dfeef7-de70-4ee4-b567-2d63edcfe386

**Comment by lokanandaprabhu** [comment]
Hi @vikram-raj ,

I have updated the PR. Issue was camel-k-operator namespace was not there and watch resource was throwing load error, and loaded was set to false for that. While consider whether data was loaded or not, we were checking whether all 3 loaded. So the loaded state set to false, now I modified the condition and added some instead of every because if we get data in any of namespace we need to show it.

PTAL.

**Comment by lokanandaprabhu** [comment]
Hi @vikram-raj ,

I have updated the PR. PTAL.

**Review by vikram-raj — COMMENTED** [review]
/lgtm

**Pull request merged**
