### PR TITLE
[WIP] Migrate usek8sWatchResource(s)

### PR DESCRIPTION
**Pull request by invincibleJai**
**Fixes:**

https://issues.redhat.com/browse/HAC-198

**Addresses:**

- [x] migrate `useK8sWatchResource` to SDK
- [x] migrate `useK8sWatchResources` to SDK
- [x] moved all utils, hooks needed for above in SDK
- [x] split and moved actions/reducers from `k8s` to SDK and exposed these reducers via SDK to the app (console)
- [x] refactor code of k8s reducers/actions in the console app
- [x] migrate webScocets factory to SDK, which already transformed to TS in the previous PR   https://github.com/openshift/console/pull/10528
- [x] fix/update existing tests
- [ ]  code clean up
- [ ]  create dedicated selectors for the reducer moved to SDK
- [ ] feedback / any other input for this migration

**Verify:**

Verify overall app is working as expected esp areas that needs to watch for resources

### CODE REVIEW

**Comment by florkbr** [comment]
```> Unauthorized``` error we have been seeing. See thread in Slack https://coreos.slack.com/archives/C6A3NV5J9/p1637758896387300

**Comment by florkbr** [comment]
Same failure as before unrelated to these changes:
```

  Localization
  Logging in as kubeadmin
    1) "before all" hook for "pseudolocalizes masthead"
  Logging out
    2) "after all" hook for "pseudolocalizes masthead"


  0 passing (2s)
  2 failing

  1) Localization
       "before all" hook for "pseudolocalizes masthead":
     a: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Unauthorized
```

**Comment by florkbr** [comment]
I have these changes checked out locally running against the nightly OCP clusters and everything seems to be working as expected in the admin/developer experience.

**Comment by andrewballantyne** [comment]
@florkbr Can we close this PR since we have your other one now?

**Comment by florkbr** [comment]
@invincibleJai closing this in favor of https://github.com/openshift/console/pull/10595. Let me know if you have any concerns. Thanks!

**Pull request closed without merging**
