### PR TITLE
[release-4.14] OCPBUGS-25997: change Alertmanager form to create using matchers inst…

### PR DESCRIPTION
**Pull request by rhamilto**
…ead of match and match_re

### CODE REVIEW

**Comment by rhamilto** [comment]
@jhadvig, mind taking a look?  Note I migrated the existing Protractor tests to Cypress rather than update the exiting Protractor tests.

**Review by jhadvig — APPROVED** [review]
/lgtm

**Comment by yanpzhan** [comment]
Tested on cluster launched against the pr. Went to Administration->configuration>Alertmanager page, created new receiver, checked in alertmanager YAML, the new created receiver was using matcher by default. Add receiver in alertmanager YAML with match_re/match in route, then edited this receiver and saved, check in alertmanager YAML again,  both match and match_red were reverted to matchers.
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
