### PR TITLE
Improve display of Operator > PackageManifests table

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://jira.coreos.com/browse/CONSOLE-1220

After:
localhost_9000_k8s_ns_openshift-operator-lifecycle-manager_clusterserviceversions_packageserver v0 8 0_packages apps redhat com_v1alpha1_packagemanifest iphone 5_se
localhost_9000_k8s_ns_openshift-operator-lifecycle-manager_clusterserviceversions_packageserver v0 8 0_packages apps redhat com_v1alpha1_packagemanifest ipad
localhost_9000_k8s_ns_openshift-operator-lifecycle-manager_clusterserviceversions_packageserver v0 8 0_packages apps redhat com_v1alpha1_packagemanifest 1
localhost_9000_k8s_ns_openshift-operator-lifecycle-manager_clusterserviceversions_packageserver v0 8 0_packages apps redhat com_v1alpha1_packagemanifest

### CODE REVIEW

**Comment by alecmerdler** [comment]
jenkins rebuild

**Comment by rhamilto** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
Last failure was flake https://jira.coreos.com/browse/CONSOLE-1224

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by rhamilto** [comment]
Rebased to pick up OLM test fixes.

**Pull request merged**
