### PR TITLE
Bug 1880008: general step text enhancements

### PR DESCRIPTION
**Pull request by glekner**

### CODE REVIEW

**Comment by matthewcarleton** [comment]
Can we also cover this from the bz in this PR?
```
Update text when no image is available

Default operating system image not available. Define a boot source manually below or request your administrator to define one for this operating system via the PVC upload form.

When user is told to go to storage step to edit disk we tell them the name of the disk rather than say "mounted disk" 

example:

Enter URL below or edit the rootdisk in the storage step
```

**Comment by glekner** [comment]
added texts @matthewcarleton

**Comment by matthewcarleton** [comment]
Lgtm!

**Comment by jelkosz** [comment]
good, 
/hold cancel

**Comment by jelkosz** [comment]
come on Kobi, why are you always faster than me?!

**Pull request merged**
