### PR TITLE
Bug 1842482: Bug fixes for storage plugin

### PR DESCRIPTION
**Pull request by cloudbehl**
- RGW provisioner name fix
- Storage status fix on PV dashboard

Signed-off-by: Ankush Behl <cloudbehl@gmail.com>

### CODE REVIEW

**Comment by cloudbehl** [comment]
@spadgett if 4.6 is open now why is bugzilla invalid?

**Comment by spadgett** [comment]
> @spadgett if 4.6 is open now why is bugzilla invalid?

It should be valid. It looks like the bot hasn't been updated.

**Pull request merged**
