### PR TITLE
[release-4.12] OCPBUGS-34933: Helm Plugin's Catalog incorrectly renders a single index entry into multiple tiles

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
Manual cherrypick of PR - https://github.com/openshift/console/pull/13872

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Tested using cluster bot. Working fine.

https://github.com/openshift/console/assets/102503482/6ea39739-c3cc-407a-8bc3-ed1ad1ff2f7a

**Review by vikram-raj — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
