### PR TITLE
Bug 2013996: Project detail page: Action "Delete Project" does nothing for the default project

### PR DESCRIPTION
**Pull request by yozaam**
**Fixes**: 

https://bugzilla.redhat.com/show_bug.cgi?id=2013996
https://issues.redhat.com/browse/OCPBUGSM-36171

**Analysis / Root cause**: 

An action either has a callback or else a redirect
But when these are not present, the action will do 'nothing'
https://github.com/openshift/console/blob/7044928d3a9f3ae3704659ce2c9dedf2e250cac9/frontend/public/components/utils/dropdown.jsx#L637-L649

**Solution Description**: 

Disable any action which does 'nothing'

**Screen shots / Gifs for design review**: 

# default project ( disabled )
Screenshot from 2021-12-01 10-43-56
# normal project ( enabled )
Screenshot from 2021-12-01 10-45-01

**Unit test coverage report**: 

in `frontend` we can use the new file `yarn test ./public/components/utils/__tests__/kebab.spec.tsx`
image

**Test setup:**

1. Switch to developer perspective
2. Navigate to 'Project' and select 'Project default' from the project list or the project dropdown
3. Click Actions => 'Delete Project'

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Looks good :+1:

Did you know why the callback is undefined for the default project?
Can you add a test?

These questions should not block merging this PR. I would like to add LGTM as well at the end of today. :)

/approve

**Comment by yozaam** [comment]
have added unit tests 
image

**Comment by jerolimov** [comment]
Really nice! Thanks for adding these tests also for the cases you don't have changed :+1: 

/lgtm

**Comment by jerolimov** [comment]
The code contains a TypeScript error which breaks all tests. Please take a look next week. :)

/lgtm cancel
/hold

**Comment by jerolimov** [comment]
Just fixed the TS build errors.

/approve
/lgtm
/cancel hold

**Pull request merged**
