### PR TITLE
Bug 2055702: enable Serverless e2e tests

### PR DESCRIPTION
**Pull request by jrichter1**
- contains a workaround for operator installation issue

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Would be cool to solve this broken-tests later, but looks like a good step into the right direction to have knative tests again on board.

/lgtm
/cc @christianvogt

**Comment by jrichter1** [comment]
Just to clarify, the broken-tests are not part of the e2e suite, but rather the nightly one. I was too lazy to create separate PRs :)

**Pull request merged**
