### PR TITLE
Bug 2071617: remove Kubevirt extensions in favour of dynamic plugin

### PR DESCRIPTION
**Pull request by glekner**

### CODE REVIEW

**Comment by yaacov** [comment]
/retitle Bug 2071617: remove Kubevirt extensions in favour of dynamic plugin

**Comment by yaacov** [comment]
@glekner hi,

Can you change the PR to use a flag to disable the replaced extensions instead of hard code removing them, like @vojtechszocs suggested ?

**Comment by glekner** [comment]
@spadgett I think we need an override here

**Comment by yaacov** [comment]
/hold
@glekner looking at the test screenshots it looks like "virtualization" menu item is missing

? it may be the script the is installing kubevirt (e.g. kubevirt is not getting installed)
or it may be our UI not identifying a kubevirt that is installed ?

cc:// @orenc1 @gouyang

**Comment by glekner** [comment]
/hold
wait for https://github.com/openshift/console/pull/11344

**Pull request merged**
