### PR TITLE
frontend: graph cpu usage intead of shares

### LINKED ISSUE #342: Pod metrics should report cores or millicores, not shares
Shares is not a thing.  We should either report cores (unit-less) or millicores (most people think in terms of fractions of a core though, so 0.01 cores reads better than 10m in most cases).

### PR DESCRIPTION
**Pull request by sjenning**
Closes #342

### CODE REVIEW

**Comment by coreos-ui** [comment]
Can one of the admins verify this patch?

**Comment by coreos-ui** [comment]
Can one of the admins verify this patch?

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
thanks @sjenning 👍

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
The last failure was test flake CONSOLE-1183

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
@sjenning There's one more reference. Do you mind updating build.tsx?

https://github.com/openshift/console/blob/master/frontend/public/components/build.tsx#L96

Looks like the query is right, but the label is wrong, like the pods page.

**Comment by spadgett** [comment]
This has passed CI. We can make the change to build.tsx in a follow on.

/hold cancel

**Pull request merged**
