### PR TITLE
[release-4.13] OCPBUGS-15720,OCPBUGS-15721,OCPBUGS-15722: Helm Chart installation form hangs on create if JSON-schema is using 2019-09 or 2020-20 standard revisions

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
This is the manual cherry-pick for PR - https://github.com/openshift/console/pull/12929

Fixes:
https://issues.redhat.com/browse/OCPBUGS-15720
https://issues.redhat.com/browse/OCPBUGS-15721
https://issues.redhat.com/browse/OCPBUGS-15722

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Tested using cluster bot. Working fine

https://github.com/openshift/console/assets/102503482/25f782f3-d2b2-460c-bc24-c6120974be1c

**Review by vikram-raj — APPROVED** [review]
/lgtm
/approve

**Review by jerolimov — APPROVED** [review]

**Review by jerolimov — APPROVED** [review]
/approved

**Pull request merged**
