### PR TITLE
Rename NamespaceSelector to NamespaceBar and fix styling issues

### PR DESCRIPTION
**Pull request by rhamilto**
Replaces https://github.com/openshift/console/pull/639

### CODE REVIEW

**Comment by spadgett** [comment]
```
/go/src/github.com/openshift/console/frontend/public/components/namespace.jsx
  295:2  error  Missing semicolon  semi
```

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by sg00dwin** [comment]
In order to alleviate popping of of the project bar, I  propose we set a `background color: #292E34` and height on the parent div that will contain the namespace selector.

It would be one less part of the ui that causes jumping while waiting to load.

Without
without-height



With 
with-height-color

**Comment by rhamilto** [comment]
> In order to alleviate popping of of the project bar, I propose we set a background color: #292E34 and height on the parent div that will contain the namespace selector.

Agreed.  I'm further refactoring the structure in my follow on.

**Pull request merged**
