### PR TITLE
CONSOLE-3948: rename 'supported but not recommended' to 'known issues…

### PR DESCRIPTION
**Pull request by rhamilto**
…' for update edges

Screenshot 2024-02-21 at 10 35 29 AM

https://github.com/openshift/console/assets/895728/fe25d7a1-3bad-427d-923e-e06cde1daa8a

### CODE REVIEW

**Comment by rhamilto** [comment]
SME Approver:
@LalatenduMohanty
Code Approver:
/assign @cyril-ui-developer 
QE Approver:
/assign @yapei
Docs Approver:
/assign @opayne1
PX Approver:
/assign @RickJWagner

**Comment by RickJWagner** [comment]
Thank you for including the screenshot above for reviewers.  Very useful.

**Comment by yanpzhan** [comment]
Tested against the pr, the texts "supported but not recommended" are updated to "known issues". Need check translates for other local languages after they are in.
/label qe-approved

**Pull request merged**
