### PR TITLE
CONSOLE-4124: replace deprecated components in ResourceLog

### PR DESCRIPTION
**Pull request by rhamilto**
**Note:**  [CONSOLE-4124](https://issues.redhat.com//browse/CONSOLE-4124) will be addressed by 4 PRs, of which this is 1.

After

https://github.com/user-attachments/assets/a3707de3-951a-4838-9379-89a6cc290686

https://github.com/user-attachments/assets/55c2e30d-9fc8-49cf-9cd8-955604aed40e

### CODE REVIEW

**Comment by rhamilto** [comment]
Tech debt so manually adding labels:
/label px-approved
/label docs-approved

/assign @yapei
/assign @sg00dwin

**Comment by yanpzhan** [comment]
Regression test on pod logs page passed.
/label qe-approved

**Comment by yapei** [comment]
do some regression about Pod Logs, container and Current/Previous log switching works well
/label qe-approved

**Review by sg00dwin — APPROVED** [review]
/lgtm

**Pull request merged**
