### PR TITLE
OCPBUGS-23299: Replace checkbox with PF checkbox component to correct alignment

### PR DESCRIPTION
**Pull request by sg00dwin**
https://issues.redhat.com/browse/OCPBUGS-23299

**After**
Screenshot 2023-12-01 at 4 41 37 PM

### CODE REVIEW

**Review by rhamilto — COMMENTED** [review]
This results in some SCSS being orphaned.  See https://github.com/openshift/console/blob/670181dea8092e4705c77872f38cf9f64de139bb/frontend/packages/console-app/src/components/network-policies/_create-network-policy.scss#L7C20-L7C20

**Comment by sg00dwin** [comment]
Removed orphaned css

**Pull request merged**
