### PR TITLE
eslint: sort imports into groups

### PR DESCRIPTION
**Pull request by suomiy**
Sort imports into groups separated by newlines. It allows newlines inside groups so it is quite permissive.

uses this rule with default groups value ([order#options](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md#options)):
```
 "import/order": ["error", { "groups": ["builtin", "external", "parent", "sibling", "index"], "newlines-between": "always-and-inside-groups" }],
```

Applied to plugins only.

What is your opinion on this issue and these exact settings? Or do you have some alternative in mind?

### CODE REVIEW

**Comment by christianvogt** [comment]
The eslint rule should be moved to `packages/eslint-plugin-console/lib/config/rules/airbnb-base-overrides.js` instead of an override in the packages eslintrc.

Airbnb (which is our base) defines this:
`'import/order': ['error', { groups: [['builtin', 'external', 'internal']] }],`

I'm fine with the stricter grouping. Your set is however is missing `internal`. Update to:
`['builtin', 'external', 'internal', 'parent', 'sibling', 'index']`

My preference is to not to include new lines between groups.

**Comment by spadgett** [comment]
Nice, I didn't realize eslint supported this 👍 

cc @alecmerdler

**Comment by suomiy** [comment]
changed the groups to `['builtin', 'external', 'internal', 'parent', 'sibling', 'index']` with no spaces between them

**Comment by suomiy** [comment]
rebased

**Pull request merged**
