### PR TITLE
OCPBUGS-42778: Add kuadrant-console-plugin to known plugins for telemetry

### PR DESCRIPTION
**Pull request by spadgett**
https://github.com/Kuadrant/kuadrant-console-plugin

/cc @jasonmadigan @alimobrem

### CODE REVIEW

**Review by jhadvig — COMMENTED** [review]
@spadgett could you also add [networking-console-plugin](https://github.com/openshift/networking-console-plugin), [distributed-tracing-console-plugin](https://github.com/openshift/distributed-tracing-console-plugin) and [console-dashboards-plugin](https://github.com/openshift/console-dashboards-plugin), since we are missing them as well

**Comment by spadgett** [comment]
> @spadgett could you also add [networking-console-plugin](https://github.com/openshift/networking-console-plugin), [distributed-tracing-console-plugin](https://github.com/openshift/distributed-tracing-console-plugin) and [console-dashboards-plugin](https://github.com/openshift/console-dashboards-plugin), since we are missing them as well

networking-console-plugin is being added in #14382 by @jerolimov. Maybe we can pull these together into one PR.

@jerolimov FYI

**Comment by jerolimov** [comment]
I chatted with Sam and updated PR #14382. It includes now all four plugins.

/close

**Comment by spadgett** [comment]
Closing in favor of #14382

**Pull request closed without merging**
