### PR TITLE
Bug 2007328: Updated patternfly to v4.125.3 and pf.quickstarts to v1.2.3.

### PR DESCRIPTION
**Pull request by dtaylor113**
Pretty standard update.  One tweak in User Preferences, and another in QuickStarts.

The former sparked a discussion in PF asking when we (OpenShift) was going to update our 2 year old `@types/react` to the latest release:  
```
zack
@Nicole @Evan Wilkinson You may want to schedule a time with Sam to talk about their 2 year old 
@types/react@16.8.13 which causes their types to break whenever we change whether 
a component forwards its ref.

This is the 3rd release we've seen the translate type error occur when bumping PatternFly
```
cc'ing @zherman0 who I thought did some recent React version updates in our codebase.

### CODE REVIEW

**Comment by spadgett** [comment]
> The former sparked a discussion in PF asking when we (OpenShift) was going to update our 2 year old `@types/react` to the latest release:

Unfortunately, we're in a tough spot given the size of our code base. Updating the types creates thousands of type errors, which is why we haven't done it. We need to come up with a strategy for getting them bumped. I was hoping when we pull out dynamic plugins into separate repos it will make this more manageable.

cc @kdoberst @christianvogt

**Review by jcaianirh — APPROVED** [review]

**Pull request merged**
