### PR TITLE
Automation enhance export app ux experience odc 6296

### PR DESCRIPTION
**Pull request by sanketpathak**
Epic: https://issues.redhat.com/browse/ODC-6296
Story: https://issues.redhat.com/browse/ODC-6424

Acceptance criteria:

- When an export is in progress, provide a quick link to view the logs when it's initially kicked off (via the toast)
- When an export is in progress, provide access to view logs if that toast has disappeared (via the Export modal)

**Checks required for approving Epic gherkin scripts PR:**

- [x] Add @epic-number to the scenarios or feature file [e.g: @odc-xxx]
- [x] Add @to-do for automation possible scenarios
- [x] Add @regression or @smoke based on the importance of the scenario
- [x] Update the test scenarios count in [Automation status confluence Report](https://docs.jboss.org/display/ODC/Automation+Status+Report)
- [x] Check for the linter issues by executing `yarn run gherkin-lint` on frontend folder [Skip epic number tags related linter issues]

**Fix**: https://issues.redhat.com/browse/ODC-6435
            https://issues.redhat.com/browse/ODC-6425

**Test Setup**:

Cluster should be running on local with **gitops-primer installed** due to issue with the installation

Check the TAGS in frontend/packages/topology/integration-tests/cypress.json file be: ""(@pre-condition or @smoke or @regression) and not (@manual or @to-do or @un-verified or @broken-test)"",

Command to execute:

Run a cluster locally and execute the command `npm run test-cypress-topology` simultaneously

Execute the export-of-application.feature file

**Browser**
Chrome 90

**Test Execution Screenshot:**
Screenshot from 2021-11-22 14-53-03

### CODE REVIEW

**Comment by jrichter1** [comment]
The tests are quite flaky. There are times when the run is completely green, but often some of the export jobs either gets stuck, or just takes too long. And the rest of the tests then fail because the job is still running
export
.

**Comment by jrichter1** [comment]
/lgtm
on the condition that ODC-6453 gets done ASAP

**Comment by sanketpathak** [comment]
This PR only affects our e2e tests.

/label qe-approved
/label px-approved
/label docs-approved

**Pull request merged**
