### PR TITLE
[release-4.9] OCPBUGS-2718: Update dependencies to the registry library and devfile parser

### PR DESCRIPTION
**Pull request by kim-tsao**
Backport changes from 4.12 PR: https://github.com/openshift/console/pull/12043

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Tested this as described here https://github.com/openshift/console/pull/12043#pullrequestreview-1129518578 on my local machine and the timeout works fine.

/label backport-risk-assessed
/lgtm
/approve

**Comment by jerolimov** [comment]
/retitle [release-4.11] OCPBUGS-2718: Update dependencies to the registry library and devfile parser

**Comment by jerolimov** [comment]
/retitle [release-4.9] OCPBUGS-2718: Update dependencies to the registry library and devfile parser

**Comment by jhadvig** [comment]
@kim-tsao `TestGetRegistrySamples` TC is failing in the `backend.sh`

**Comment by jerolimov** [comment]
@jhadvig this is a general 4.9 issue and is fixed with #12201

**Comment by jerolimov** [comment]
@kim-tsao the backend job fails because a formatting issue:

```
Checking gofmt...
gofmt checking failed:
pkg/devfile/sample.go
```

**Comment by jerolimov** [comment]
Re-tested as described here https://github.com/openshift/console/pull/12043#pullrequestreview-1129518578 

1. With a network call that takes 10 seconds, the samples are shown after 3 seconds (not part of this PR) and the `/api/devfile` API call fails after 5 seconds. :heavy_check_mark:

https://user-images.githubusercontent.com/139310/200835805-ae3d0b37-5bc7-4418-b923-a34331e6f81b.mp4

2. Working example without timeout URL :heavy_check_mark:

https://user-images.githubusercontent.com/139310/200835788-69c99341-b153-4251-a810-0ee170ff6914.mp4

/lgtm
@jhadvig, can you please add approval for this.
@sanketpathak, can you test this on a cluster and add cherry-pick-approved as well.

**Comment by sanketpathak** [comment]
Verified on a disconnected cluster with proxy
[Screencast from 11-09-2022 022928AM.webm](https://user-images.githubusercontent.com/10252230/203354053-687ce2fc-a43b-430d-8cc0-d503e914221d.webm)
/label cherry-pick-approved

**Comment by invincibleJai** [comment]
/retitle OCPBUGS-2718: Update dependencies to the registry library and devfile parser

**Comment by invincibleJai** [comment]
/retitle [release-4.9] OCPBUGS-2718: Update dependencies to the registry library and devfile parser

**Pull request merged**
