### PR TITLE
Bug 1875371: Fix to show topology list view filtered items correctly

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**Fixes**
https://issues.redhat.com/browse/ODC-4736

**Description**
Fix to dim non-matching items and highlight matching items immediately on text entry to the 'Find by name' field in the topology list view.

**Browser conformance**: 
- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge

/kind bug

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Tested it locally, works fine :+1: 

/lgtm

**Comment by jeff-phillips-18** [comment]
@jerolimov Fixed tests.

**Pull request merged**
