### PR TITLE
CONSOLE-3682: Convert components in cluster-settings folder from clas…

### PR DESCRIPTION
**Pull request by tvu20**
…s component to functional component

Files in frontend/public/components/cluster-settings have been converted from a class component to a functional component in order to use react-router v6 hooks.

Frontend tests in frontend/_tests_/components/cluster-settings have been commented out because they are incompatible with functional components. A story has been created to update these tests: https://issues.redhat.com/browse/CONSOLE-3711

### CODE REVIEW

**Comment by jhadvig** [comment]
> Frontend tests in frontend/tests/components/cluster-settings have been commented out because they are incompatible with functional components. A story has been created to update these tests: https://issues.redhat.com/browse/CONSOLE-3711

/hold
I would suggest to hold this PR until we have re-written tests and have passing tests.

**Comment by jhadvig** [comment]
QE Approver: 
/assign @yanpzhan
Docs Approver:
 /assign @opayne1 
PX Approver:
/assign @RickJWagner

**Review by jhadvig — APPROVED** [review]
Found couple of small nits, but lets try to merge it, so we dont need to retest the whole suite.
/lgtm
/approve

**Comment by tvu20** [comment]
This is technical debt cleanup and has no user-facing impact, so I am manually assigning docs approval.

/assign @yanpzhan for QE approval.
/label docs-approved

**Comment by yanpzhan** [comment]
Did a regression test on console pages, especially on clustersettings page(including idp configuration pages). There is no regression issue found.
/label qe-approved

**Pull request merged**
