### PR TITLE
odc-5518-cypress dev file[add flow] automation

### PR DESCRIPTION
**Pull request by makambalaji**
Description:
This PR is related to add flow - dev file automation
Jira Id: https://issues.redhat.com/browse/ODC-5518

Please Note: This scripts are not integrated with CI

Execute the below command "yarn run test-cypress-devconsole" on fronted folder

Test Results:
No. of smoke test cases in this pr : 1 [Execution Time: - 34 sec]
No. of regression test cases in this pr: 2 [Execution Time: - sec]
No. of test cases in this pr: 3 [Execution Time: - 89 sec]

### CODE REVIEW

**Comment by makambalaji** [comment]
/assign @josephca 
Assigning it to you, please review the scenarios as well as scripts and let me know if it works

**Comment by josephca** [comment]
@makambalaji I tried to bring in the changes of this PR and run locally. When I tried to run 'create-from-devfile.feature', I got the following error. Running the default test, 'project-creation.feature' ran fine with no issue as we can see 'e2e-gcp-console-test' passed with this PR.  

image

**Comment by makambalaji** [comment]
> @makambalaji I tried to bring in the changes of this PR and run locally. When I tried to run 'create-from-devfile.feature', I got the following error. Running the default test, 'project-creation.feature' ran fine with no issue as we can see 'e2e-gcp-console-test' passed with this PR.
> 
> image

Scripts executed based on the cypress configuration. 
In this pr, Only smoke tagged test scripts are added for execution. which you can see on 
[cypress.json](https://github.com/openshift/console/blob/master/frontend/packages/dev-console/integration-tests/cypress.json#L26) file.

If you want to execute regression scripts also then you need to update the line as `"TAGS": "@regression or @smoke and not @manual"`

**Comment by josephca** [comment]
@makambalaji The screenshot that I attached was from my local cypress runner (not related to the Ci tests) and the test with 'create-from-devfile.feature' was triggered to run the included regression/smoke tests - failed. 
image

I will approve the change for now and will try to run tests with another PR by modifying the cypress config.

**Comment by josephca** [comment]
@makambalaji Thanks, I was able to bypass the issue by modifying cypress config as you said. 
However, 3 tests are failed with the following errors on my local test. 

1.         Scenario: Deploy git workload with devfile from topology page
image

2. Scenario: Create the workload with git private repo from dev file
image

3. Scenario: Create the sample workload from dev file

image

**Comment by makambalaji** [comment]
> @makambalaji Thanks, I was able to bypass the issue by modifying cypress config as you said.
> However, 3 tests are failed with the following errors on my local test.
> 
> 1. ```
>        Scenario: Deploy git workload with devfile from topology page
>    ```
> 
> image
> 
> 1. Scenario: Create the workload with git private repo from dev file
>    image
> 2. Scenario: Create the sample workload from dev file
> 
> image

This issue is occurring due to git repo url validation. Its an intermittent issue [https://issues.redhat.com/browse/ODC-5534] - defect raised
I am able to execute the scripts, below is the screenshot for the same.
image

**Comment by josephca** [comment]
@makambalaji It seems to be working fine on my machine as well. I guess it would be an intermittent issue. Thanks!

**Comment by sanketpathak** [comment]
Screenshot from 2021-02-18 02-12-28
/lgtm

**Comment by sanketpathak** [comment]
Screenshot from 2021-02-19 16-55-10
/lgtm

**Pull request merged**
