### PR TITLE
Bug 2027288: Devfile samples can't be loaded after fixing it on Safari (redirect caching issue)

### PR DESCRIPTION
**Pull request by gruselhaus**
This PR is a continuation to #10464

**Fixes**: 
https://bugzilla.redhat.com/show_bug.cgi?id=2027288
https://issues.redhat.com/browse/OCPBUGSM-37613

**Analysis / Root cause**: 
After fixing that the Devfile samples could not be loaded on Safari (only), it looks like they couldn't be loaded at all / or on other browsers.

The reason was that the browsers caches an redirect from /api/devfile/samples (frontend code) to /api/devfile/samples/ (backend code). The PR https://github.com/openshift/console/pull/10464 to fix https://bugzilla.redhat.com/show_bug.cgi?id=2023356 changed all code to /api/devfile/samples but the browsers keep their redirect. So that the fix works when the user clears their cache or uses another cluster (URL) but has issues after updating locally. We could also expect that the users will have issues after updating from 4.9 to 4.10 with this solution.
**Solution Description**: 

How reproducible:
Only if the user uses an older version first (before https://github.com/openshift/console/pull/10464 was merged) and then switches to the latest version.

Steps to Reproduce:
1. Test with an old version first (before 22th Nov 2021)
2. Open developer perspective and open Add > Samples
3. Switch your console to the latest master
4. Open developer perspective and open Add > Samples again

Actual results:
The Devfile samples could not be loaded. After cleaning the browser cache it works fine.

Expected results:
The Devfile samples could be loaded also when the browser has a redirect in its cache.

Additional info:
You can open the browser network inspector to check if the API calls contain any redirect.

**Fix**: 
I changed all routes back to `...samples/...`. In addition to that I made a change in `devfileHooks.ts` to use the new logic which was overlooked at #10464.

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [x] Safari
- [ ] Edge

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Tested this locally and it looks good to me.

/lgtm
/approve
/cc jhadvig

**Comment by florkbr** [comment]
Tested on a 4.10 nightly cluster and looks good in Chrome, Firefox, and Safari:

## Before
Screen Shot 2021-12-06 at 9 34 24 AM

## After
Screen Shot 2021-12-06 at 10 51 21 AM

The redirect has been removed.

**Pull request merged**
