### PR TITLE
Fix resource icon memoization

### LINKED ISSUE #135: Swapped position of actionMenu and resource-icon
Often after creating a first instance of a specific resource(Service, Secret, Stateful Set, ... ) the position of the actionMenu and resource-icon is swapped. Even after the navigating to some other page and back to the resource List page the order is still swapped. Only after refreshing the page the order goes back to normal.
Swapped position:

Normal position:

Also the size of the resource-icon is incorrect since it's bigger the the intended size.

### PR DESCRIPTION
**Pull request by spadgett**
Include className in the memo key.

@tlwu2013 I believe this fixes the icon weirdness we've seen.

Fixes #135
/assign @jhadvig

### CODE REVIEW

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by jhadvig** [comment]
@spadgett really nice usage of memoization :+1: 
/lgtm

**Pull request merged**
