### PR TITLE
[release-4.11] Bug 2102335: Implement dynamic plugin dependency resolution

### PR DESCRIPTION
**Pull request by vojtechszocs**
This is a backport of #11626 for the `release-4.11` branch.

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]

**Comment by yapei** [comment]
Hi @vojtechszocs it looks like we still need backport https://github.com/openshift/console-operator/pull/659 to `release-4.11` to implement dynamic plugin dependency resolution, could you help confirm?

**Comment by jhadvig** [comment]
@vojtechszocs @yapei I've backported https://github.com/openshift/console-operator/pull/679

**Comment by yapei** [comment]
```
Error while loading plugin console-demo-plugin from /api/plugins/console-demo-plugin/ u: Unmet dependency on Console plugin API:
@console/pluginAPI: required ~4.9.0, current 4.11.0-0.ci.test-2022-08-31-054831-ci-ln-skyzr9t-latest
```
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
