### PR TITLE
pf-2023-1 package updates

### PR DESCRIPTION
**Pull request by jcaianirh**

### CODE REVIEW

**Comment by jcaianirh** [comment]
QE Approver:
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

Console Approver:
/assign @rhamilto

**Comment by XiyunZhao** [comment]
@jcaianirh Could you help to check the issue below for this PR update
**Reproduce Step:**
1. Navigate to Operators -> OperatorHub page
2. Input some word on the "Filter by keyword"
**Result:**
The input word is shown as [Object] which is incorrect
image

**Comment by jcaianirh** [comment]
✖  e2e/add-flow-ci.feature                  09:55       16       14        2        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  1 of 1 failed (100%)                     09:55       16       14        2        -        -

**Comment by jcaianirh** [comment]
│ ✖  operator-uninstall.spec.ts               00:32        5        -        1        -        4 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  4 of 8 failed (50%)                      05:02       20        8        4        1

**Comment by jcaianirh** [comment]
@XiyunZhao I'm not seeing this behavior. Is there any other steps that you went through to reproduce this?

**Comment by jcaianirh** [comment]
Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  catalog-source-details.spec.ts           01:20        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  create-namespace.spec.ts                 00:51        1        -        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  descriptors.spec.ts                      01:28        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  edit-default-sources.spec.ts             00:23        1        1        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  operator-hub.spec.ts                     00:50        6        2        1        -        3 │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  operator-install-global.spec.ts          00:24        1        -        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  operator-install-single-namespace.s      171ms        1        -        -        1        - │
  │    pec.ts                                                                                      │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  operator-uninstall.spec.ts               00:58        5        -        1        -        4 │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  4 of 8 failed (50%)                      06:17       20        8        4        1        7

**Comment by XiyunZhao** [comment]
@jcaianirh I've tried to reproduce this issue via cluster-bot again, but this issue is still there
**Here is the reproduce step:** launch the cluster( make sure the PR is included in the build), navigate to the Operators -> Operators Hub page directly, and input some word on the"Filter by keyword", you will see the issue
**Btw,** Chrome is the browser that I use, and the version is 109.0.5414.74
Ping me if you need any other information

**Comment by jcaianirh** [comment]
> @jcaianirh Could you help to check the issue below for this PR update **Reproduce Step:**
> 
> 1. Navigate to Operators -> OperatorHub page
> 2. Input some word on the "Filter by keyword"
>    **Result:**
>    The input word is shown as [Object] which is incorrect
>    image

fixed this in my last commit thanks @XiyunZhao

**Comment by XiyunZhao** [comment]
This PR has been verified via cluster-bot, and now no issue found for the basic function on the console, the package install is smooth on the backend for the console (like 'yarn install'), and no issue found either
/label qe-approved

**Pull request merged**
