### PR TITLE
ODC-7655: Migrate IntervalDropdown to PF5

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7655

**Solution Description**: 

Migrate file to PF5

**Screen shots / Gifs for design review**: 

Demo:

https://github.com/user-attachments/assets/114c340c-850f-44c0-8e6c-9bee34be9823

**Unit test coverage report**: 

unchanged

**Test setup:**

to see the observe dashboard in local development, use the mock data linked here https://github.com/openshift/monitoring-plugin/compare/main...zhuje:monitoring-plugin:mock_monitoring_dashboard_config

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

This pr is 1/4 of [ODC-7655](https://issues.redhat.com//browse/ODC-7655) story as each file is being split into a separate PR.

### CODE REVIEW

**Comment by logonoff** [comment]
Tech debt that is not customer facing, so manually adding labels
/label px-approved
/label docs-approved

**Review by vikram-raj — APPROVED** [review]
/lgtm

**Comment by logonoff** [comment]
> This change should be added on the monitoring plugin side as well as we will re use the admin components. cc @zhuje

Sorry! I wasn't aware that this file was duplicated -- I've opened another PR on the monitoring plugin repo as well: https://github.com/openshift/monitoring-plugin/pull/183

**Comment by sanketpathak** [comment]
Verified on a cluster with admin and non-admin users
Screenshot 2024-09-12 at 5 06 21 PM
/label qe-approved

**Pull request merged**
