### PR TITLE
Added PVC volume type info for volume information on workloads

### PR DESCRIPTION
**Pull request by anmolsachan**
Required change :

Added volume type information(PVC) for volumes attached to workloads.

Before: 
Screenshot from 2019-07-19 22-20-23

After:
Screenshot from 2019-07-19 22-26-57

Dependency PR : https://github.com/openshift/console/pull/1891

### CODE REVIEW

**Comment by anmolsachan** [comment]
@spadgett Please Review

**Comment by spadgett** [comment]
/hold

This is a bug fix if nothing is showing up in the table, but imo it's not the right approach. We should have a link to the PVC/Secret/ConfigMap with the badge icon. See discussion in #1433

**Comment by spadgett** [comment]
@anmolsachan I opened #2107 with the changes I had in mind

**Comment by anmolsachan** [comment]
> @anmolsachan I opened #2107 with the changes I had in mind

@spadgett Works for me. Closing this. Your PR looks good.

**Pull request closed without merging**
