### PR TITLE
Bug 1828993: Add divider line befor field selectors

### PR DESCRIPTION
**Pull request by yaacov**
Add divider line befor field selectors

Requested in https://bugzilla.redhat.com/show_bug.cgi?id=1828993#c5

Screenshot
screenshot-localhost_9000-2020 05 19-08_44_45

### CODE REVIEW

**Comment by yaacov** [comment]
@glekner please review

**Comment by yaacov** [comment]
@rhrazdil please reaview

**Comment by rhrazdil** [comment]
NIce, I appreciate the description. 
/lgtm

**Pull request merged**
