### PR TITLE
Bug 1906745: Upgrade Helm to 3.4.2

### PR DESCRIPTION
**Pull request by maysunfaisal**
This is for issue https://issues.redhat.com/browse/HELM-47

- upgrades Helm go module to 3.4.2
- go mod tidy & go mod vendor
- updates all the test index files for Helm 3.4.2

P.S.
If you're coming back to look at this PR for googleapis vendor changes, the module path changed from `vendor/github.com/googleapis/gnostic/OpenAPIv2` to `vendor/github.com/googleapis/gnostic/openapiv2`

You may set the git config to take this into account
```
 git config core.ignorecase false
```

### CODE REVIEW

**Comment by pedjak** [comment]
/title Bug: 1906745: Upgrade Helm to 3.4.1

**Comment by pedjak** [comment]
/retitle Bug 1906745: Upgrade Helm to 3.4.1

**Comment by pedjak** [comment]
@maysunfaisal the latest version is 3.4.2, so since we perform update now, let's upgrade to that instead?

**Comment by pedjak** [comment]
/retitle Bug 1906745: Upgrade Helm to 3.4.2

**Review by spadgett — APPROVED** [review]
/approve

**Review by akashshinde — APPROVED** [review]

**Pull request merged**
