### PR TITLE
Fix odc-progressive-list__button text vertical alignment

### PR DESCRIPTION
**Pull request by rhamilto**
Before:
Screen Shot 2019-08-21 at 3 23 57 PM

After:
Screen Shot 2019-08-22 at 9 04 47 AM

### CODE REVIEW

**Comment by rhamilto** [comment]
Updated per @christianvogt suggestion.  Note:  doing so increased the font weight on the buttons.

**Comment by christianvogt** [comment]
Thanks @rhamilto 
/approve

**Pull request merged**
