### PR TITLE
Move DevConsole integration tests to the appropriate package

### PR DESCRIPTION
**Pull request by vojtechszocs**
With #2051 merged, Console plugins can now declare new (or extend existing) test suites.

Files related to `devconsole` suite were moved to `packages/dev-console/integration-tests`.

cc @spadgett @christianvogt

### CODE REVIEW

**Comment by christianvogt** [comment]
@vojtechszocs thanks for doing this

**Comment by vojtechszocs** [comment]
Looks like I've missed some ESLint errors :smiley: will update.

**Comment by vojtechszocs** [comment]
@christianvogt PR updated & added `packages/dev-console/integration-tests/.eslintrc.js` file.

**Pull request merged**
