### PR TITLE
[release-4.13] OCPBUGS-13285: add multipath device type to LocalVolumeSet

### PR DESCRIPTION
**Pull request by RomanBednar**
This is a cherry-pick of https://github.com/openshift/console/pull/12723 and https://github.com/openshift/console/pull/13022

### CODE REVIEW

**Review by jhadvig — COMMENTED** [review]
@RomanBednar you need to open the PR agains the release-4.13 branch

**Comment by Phaow** [comment]
Pre verify passed with the prebuild cluster by clusterbot
```console
$ oc version
Client Version: 4.12.0-ec.3
Kustomize Version: v4.5.4
Server Version: 4.13.0-0.test-2023-09-04-041247-ci-ln-pvzt91k-latest
Kubernetes Version: v1.26.7+0ef5eae

1. Install OCP cluster and local storage operator;
2. Configure multipath on 1 worker node;
3. Create localvolumediscovery CR and check the localvolumediscoveryResults contains the mpath type volumes;
$ oc get localvolumediscoveryResults -oyaml|grep -i 'mpath'
      type: mpath
4. Create localvolumeset with mpath type and check the provisioned pvs contains the mpath volumes.(Check both with CLI and Web console)
$ oc get pv/local-pv-2bd661c4 -oyaml|yq .metdadta.annotations
null
$ oc get pv/local-pv-2bd661c4 -oyaml|yq .metadata.annotations
pv.kubernetes.io/provisioned-by: local-volume-provisioner-ci-ln-pvzt91k-72292-6545l-worker-c-psrhh
storage.openshift.com/device-id: wwn-0xGoogle_PersistentDisk_persistent-disk-1
storage.openshift.com/device-name: dm-0
```

**Comment by RomanBednar** [comment]
@jhadvig Looking at the above, it seems like we might need someone from your team for adding the remaining labels? Also please review (or assign).

**Comment by Phaow** [comment]
@yanpzhan @XiyunZhao Could you please take a look and add the `cherry-pick-approved` when you get a chance? I pre-merge test looks good from storage side. Thanks!

**Pull request merged**
