### PR TITLE
Rename vert-nav to horizontal-nav

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://jira.coreos.com/browse/CONSOLE-775

Is just a simple rename of files, component, and classes.

### CODE REVIEW

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by rhamilto** [comment]
jenkins rebuild

**Comment by rhamilto** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
