### PR TITLE
Update visual grouping of layout buttons in topology control bar

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Resolves https://jira.coreos.com/browse/ODC-2338

image

cc @serenamarie125 @mceledonia @Veethika

### CODE REVIEW

**Comment by christianvogt** [comment]
The hover state of the right button:
image

The hover state of the left button:
image

The shadows aren't consistent as the shadow overlaps in one case but not the other.

@serenamarie125 @mceledonia 
Is this the correct look you want for the depressed state? IMO it doesn't stand out very well.

**Comment by Veethika** [comment]
> The hover state of the right button:
> image
> 
> The hover state of the left button:
> image
> 
> The shadows aren't consistent as the shadow overlaps in one case but not the other.
> 
> @serenamarie125 @mceledonia
> Is this the correct look you want for the depressed state? IMO it doesn't stand out very well.

@serenamarie125 @christianvogt @jeff-phillips-18 A few changes for the toggle visual:
• The shadow should apply to the whole toggle button and not parts of it
• To differentiate better between the hover and selected state for the toggle button, #004080 should be used for the hover state of the icon
(While not hovering over, the depressed state visual seems acceptable)

**Comment by jeff-phillips-18** [comment]
Updated to suggestions from @Veethika 

X4m2F92Ebc

**Comment by andrewballantyne** [comment]
> X4m2F92Ebc

Hmmm, that looks odd to me. A drop shadow overlapping the other button feels weird in a "button group".

**Comment by jeff-phillips-18** [comment]
@andrewballantyne Agreed, looking for UX feedback.

**Comment by christianvogt** [comment]
We should provide a proper button group in PF that can be used here.

**Comment by jeff-phillips-18** [comment]
@christianvogt Agreed and the PF team is aware:
https://github.com/patternfly/patternfly-next/issues/2478

**Comment by jeff-phillips-18** [comment]
Updated visuals per discussions w/ @serenamarie125 :

FdtdKO7pDN

**Comment by serenamarie125** [comment]
@sspeiche and I think this looks much better, @christianvogt @andrewballantyne do you agree?  Unfortunately we didn't have any PF visuals folks available to review.

**Comment by andrewballantyne** [comment]
The dark gray background is for just these two buttons (based on selection) or is it for all of them?

@jeff-phillips-18 @serenamarie125

**Comment by jeff-phillips-18** [comment]
@andrewballantyne The dark grey background is only to represent the currently selected layout option.

**Comment by andrewballantyne** [comment]
image

@jeff-phillips-18 Are we okay with this overlap?

cc @serenamarie125

**Comment by jeff-phillips-18** [comment]
That overlap occurs when a layout button has focus and another is hovered over. Due to there being no space between the buttons.

**Comment by andrewballantyne** [comment]
I'm good with the code / how it works as long as UX is okay with the overlap @jeff-phillips-18

**Comment by jeff-phillips-18** [comment]
WvHmSxav3y

@openshift/team-devconsole-ux Please review

**Comment by christianvogt** [comment]
/lgtm

What's interesting is that I believe kiali is also doing their own customizations like this. We need to get into PF.

**Pull request merged**
