### PR TITLE
Bug 1921541: skip guide page if it presents

### PR DESCRIPTION
**Pull request by gouyang**
verified in https://cnv-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/test-kubevirt-[console-4](https://issues.redhat.com/browse/console-4).7-cnv-2.6-dev-gouyang/7/console

### CODE REVIEW

**Comment by spadgett** [comment]
/override ci/prow/ceph-storage-plugin

The ceph-storage-plugin job should only have run on PRs with changes to `frontend/packages/ceph-storage-plugin`. It failed due to an unrelated CI config change. Overriding status on this PR.

**Comment by gouyang** [comment]
Verified in d/s job: https://cnv-qe-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/test-kubevirt-console-4.7-cnv-2.6/22/console

**Pull request merged**
