### PR TITLE
Bug 2033407: Fix secure route pre-filled issue in edit flow

### PR DESCRIPTION
**Pull request by vikram-raj**
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=2033407

**Analysis / Root cause:**
Route data is not pre-filled in the edit form. We are reading the `tls` data from the `Route` `spec` instead of `spec.tls`. And we are using the wrong key I:e `privateKey` which should be `key`.

**Solution Description:**
Read the `Route` `tls` data from `spec.tls` and changed `privateKey` to 'key`.

GIF: 
Kapture 2021-12-17 at 18 56 18

### CODE REVIEW

**Comment by vikram-raj** [comment]
cc @jerolimov

**Review by jerolimov — CHANGES_REQUESTED** [review]
When disable the Secure setting the Route tls options are not removed, so that when I open the edit page again it is enabled again. Please let us fix this as part of this PR as well., :)

**Comment by vikram-raj** [comment]
> When disable the Secure setting the Route tls options are not removed, so that when I open the edit page again it is enabled again. Please let us fix this as part of this PR as well., :)

Fixed this scenario as well.

**Review by jerolimov — APPROVED** [review]
Works great. Good catch to find this really old issue. Let us backport this as soon as this is merged. :+1:

/lgtm
/approve

**Pull request merged**
