### PR TITLE
OCPBUGS-4418: Re-enable shipwright e2e tests

### PR DESCRIPTION
**Pull request by jerolimov**
**Fixes:** https://issues.redhat.com/browse/OCPBUGS-4418

Let see if this passes with master and how long it takes!

We can rerun this also after #12910 and #12960 are merged.

### CODE REVIEW

**Comment by jerolimov** [comment]
Don't reenable this before we release 4.14

/hold

**Comment by jerolimov** [comment]
Fyi Avik

/cc @Lucifergene

**Comment by vikram-raj** [comment]
closing it as Shipwright tests are not in good state.

/close

**Pull request closed without merging**
