### PR TITLE
[WIP] Integrate PatternFly 4 nav and font-family

### PR DESCRIPTION
**Pull request by rhamilto**
Replaces #674 

TODOs:

- [x] Remove `nav-item-iconic` added in https://github.com/openshift/console/pull/839
- [ ] Finalize About modal content
- [ ] Help menu gets a caret?

KNOWN ISSUES:
- Dropdowns in navbar (PF4 dropdowns) behave differently than dropdowns in content
  * The first menu item in the dropdown is selected on opening the dropdown, so instead of a second enter press closing the dropdown, it selects the selected menu item
  * The only way to close the dropdown is using the Esc key, which is problematic for mobile (i.e., there is no way to close the dropdown)
  * Cannot tab out of the dropdown menu to the next keyboard focusable item
- Cluster Update Available and Help icons 
  * are not vertically aligned (upstream bug @matthewcarleton is investigating)
  * have differing default and hover colors (gray and white vs. white and gray) (upstream bug @matthewcarleton is investigating)
- Long usernames do not truncate (@matthewcarleton is investigating)

### CODE REVIEW

**Comment by rhamilto** [comment]
jenkins rebuild

**Comment by TheRealJon** [comment]
Look at all those green check marks!! 🎉

**Comment by rhamilto** [comment]
jenkins rebuild

**Comment by rhamilto** [comment]
jenkins push

**Comment by spadgett** [comment]
jenkins push

**Comment by rhamilto** [comment]
jenkins push

**Comment by coreos-ui** [comment]
The PR image failed.

**Comment by rhamilto** [comment]
jenkins rebuild

**Comment by rhamilto** [comment]
jenkins rebuild

**Comment by rhamilto** [comment]
Accidentally closed.

**Pull request closed without merging**
