### PR TITLE
Bug 1827291: Fix bad websocket url error due to fetching of resourcea when not required

### PR DESCRIPTION
**Pull request by rohitkrai03**
Fixes - https://issues.redhat.com/browse/ODC-3503

Peek 2020-04-23 19-25

### CODE REVIEW

**Comment by rohitkrai03** [comment]
> /lgtm
> 
> I find it odd that (unrelated to your work here) we allow an `/import/all-namespaces` route to exist.
> 
> cc @christianvogt not sure if we want to look to remove this or if it was added for a specific reason.

Well, it was added at the time of 4.2 when we had a project selector dropdown in the form itself. So opening import form with all-namespaces would let you choose the project directly in the form. But then we changed all that and it's not required now. So maybe we can look at removing it.

**Comment by andrewballantyne** [comment]
> Well, it was added at the time of 4.2 when we had a project selector dropdown in the form itself. So opening import form with all-namespaces would let you choose the project directly in the form. But then we changed all that and it's not required now. So maybe we can look at removing it.

@rohitkrai03 can you log a refactor task?

**Comment by rohitkrai03** [comment]
> > Well, it was added at the time of 4.2 when we had a project selector dropdown in the form itself. So opening import form with all-namespaces would let you choose the project directly in the form. But then we changed all that and it's not required now. So maybe we can look at removing it.
> 
> @rohitkrai03 can you log a refactor task?

@andrewballantyne Added a bug in Jira - https://issues.redhat.com/browse/ODC-3672

**Pull request merged**
