### PR TITLE
[release-4.12] OCPBUGS-11601: Move operator install status to it's own …

### PR DESCRIPTION
**Pull request by TheRealJon**
…route/page

Manual cherry-pick of #12704

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm

**Comment by XiyunZhao** [comment]
This PR has been verified by using cluster-bot. Now user will stay on the install page after Service Binding Operator installation is complete, the message "Installed operator: ready for user" will show on the page
/label qe-approved

**Pull request merged**
