### PR TITLE
pipeline builder cleanup

### PR DESCRIPTION
**Pull request by debsmita1**
**Fixes:**
https://issues.redhat.com/browse/ODC-5937

**Root analysis:**

**Solution description:**
- The icon for the popover next to workspaces has been updated to i info icon
- `When Expression` title in the Task sidebar has been updated to "When expressions". The help text has been updated to "No when expressions are associated with this task.". 
- The "Display Name" in the Task sidebar has been updated to "Display name"

**Screenshot:**
pb

**Browser conformance:**
- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by andrewballantyne — APPROVED** [review]
/lgtm
/hold
/retest

**Comment by andrewballantyne** [comment]
/unhold

Brigid can log another bug if she sees something else. This PR covers the items in the ticket.

**Comment by bgliwa01** [comment]
Everything looks good! I just noticed we need to capitalize use in the help text "Use this format when referencing..." under when expressions. I will create a new bug!

**Pull request merged**
