### PR TITLE
Bug 2015496: Storage - PersistentVolumes  Claim column value 'No Claim' in English

### PR DESCRIPTION
**Pull request by cyril-ui-developer**
/assign @spadgett 

### Before:
Screen Shot 2021-10-25 at 8 29 05 AM

### After:
Screen Shot 2021-10-25 at 8 28 34 AM

### CODE REVIEW

**Comment by cyril-ui-developer** [comment]
> /lgtm cancel
> 
> Looks like you need to run `yarn i18n`:
> 
> > i18n files are not up to date. Commit them to fix.

@spadgett I actually ran `yarn i18n` and the "No claim" string was added to public.json. I will run it again. 
Thanks

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
