### PR TITLE
chore(i18n): update translations :  Completed-7034-OCP 4.11/Release Branch UI Localization- Sprint 220

### PR DESCRIPTION
**Pull request by cyril-ui-developer**
Adding latest translations from Memsource project https://cloud.memsource.com/web/project2/show/yb8SPE83cqGt8N1w73vkQ6

No ready for merge.
Need to double check these changes with Localization teem

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by jhadvig** [comment]
Adding the label manually since this is not a bug, rather then a maintenance.

**Comment by jerolimov** [comment]
@cyril-ui-developer @jhadvig Do you still want merge this PR? :smile:

**Comment by jhadvig** [comment]
kubevirt:
```
error An unexpected error occurred: "https://registry.yarnpkg.com/@patternfly/react-core/-/react-core-4.135.15.tgz: unexpected end of file".
```

storage:
```
* Container test is not ready with reason PodInitializing
Found 2 events for Pod ceph-storage-plugin-ipi-install-monitoringpvc:
* 0001-01-01T00:00:00Z 0x : Successfully assigned ci-op-r4wsy6hl/ceph-storage-plugin-ipi-install-monitoringpvc to ip-10-0-155-51.ec2.internal
* 2023-10-11T11:49:[48](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_console/11875/pull-ci-openshift-console-release-4.11-ceph-storage-plugin/1712060378164236288#1:build-log.txt%3A48)Z 7x kubelet: Failed to create pod sandbox: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

/retest

**Pull request closed without merging**
