### PR TITLE
[release-4.10] Bug 2094211: Change Ping source spec.jsonData (deprecated) field to spec.data

### PR DESCRIPTION
**Pull request by vikram-raj**
This is a manual cherry-pick of https://github.com/openshift/console/pull/11548

### CODE REVIEW

**Comment by invincibleJai** [comment]
@vikram-raj look at ci failures

**Comment by invincibleJai** [comment]
/lgtm
/label backport-risk-assessed

Verified on cluster bot and works as expected

image


image

image

**Comment by jerolimov** [comment]
> /label  cherry-pick-approved

@sanketpathak can you please re-apply this label. The bot doesn't added it. Thx.

**Pull request merged**
