### PR TITLE
[release-4.13] OCPBUGS-17181: Creation of GH webhook and attaching it to repo while importing from git using PAC

### PR DESCRIPTION
**Pull request by Lucifergene**
Manual Cherry-pick of PR https://github.com/openshift/console/pull/12905 and PR https://github.com/openshift/console/pull/13021
---
1. This introduces the ability to auto-attach webhooks to the Git repository upon Pipeline Repository creation.

2. It also fixes 2 bugs: 
- https://issues.redhat.com/browse/OCPBUGS-9409
- https://issues.redhat.com/browse/OCPBUGS-16270

/assign @Lucifergene

### CODE REVIEW

**Review by Lucifergene — COMMENTED** [review]
Verified. Working as expected.

1. Webhook:

https://github.com/openshift/console/assets/47265560/cd02b116-d2e3-486e-bc97-1764f0fa5c89

2. `gitProvider` bug:

https://github.com/openshift/console/assets/47265560/bbead1b9-209e-4d7a-bc86-fcc09bfa2583

3. Local Bitbucket:
 
https://github.com/openshift/console/assets/47265560/d4c56718-5b0b-4177-83b4-ee379ccf0850

**Comment by lokanandaprabhu** [comment]
Tested using cluster bot. Working fine.

/lgtm


https://github.com/openshift/console/assets/102503482/897ec51d-f9d5-4738-adeb-9a9eee115b62



https://github.com/openshift/console/assets/102503482/975a1340-04a2-42f3-add3-34a511712afc

**Review by vikram-raj — COMMENTED** [review]
verified it and it works as expected

/lgtm
/approve

**Review by jerolimov — APPROVED** [review]
Great work. Manually tested this on a cluster bot instance and works fine. :+1:

/approve

**Pull request merged**
