### PR TITLE
Bug 1978225: add alert when new IDP is added

### PR DESCRIPTION
**Pull request by rhamilto**
https://user-images.githubusercontent.com/895728/124975280-de0b4d00-dffb-11eb-9fc8-a8e6fe5ee577.mov

### CODE REVIEW

**Comment by rhamilto** [comment]
I didn't receive any feedback on this in Slack, so figured I'd throw it up here to facilitate that process.

**Comment by spadgett** [comment]
I think it would be good to show the `authentication` cluster operator status here so users know when the changes roll out.

**Comment by itsptk** [comment]
> I think it would be good to show the `authentication` cluster operator status here so users know when the changes roll out.

Does this mean that we have insight into when this reconfiguration would be complete? Is that when the alert would disappear in the current PR implementation?

Also, does the addition of any one IDP initiate a reconfiguration for all IDPs? This wouldn't be a rollout per IDP then?

**Comment by rhamilto** [comment]
> Does this mean that we have insight into when this reconfiguration would be complete? Is that when the alert would disappear in the current PR implementation?

The current PR is dumb about the reconfiguration.  We'd need to figure out how to determine the authentication cluster operator has rolled out the change.

> Also, does the addition of any one IDP initiate a reconfiguration for all IDPs? This wouldn't be a rollout per IDP then?

The rollout will occur any time the oauth config changes.  So each IDP config would trigger a rollout.

**Comment by spadgett** [comment]
You'd see the `authentication` operator status go from `Available` -> `Progressing` -> `Available`. (These are actually separate conditions in the resource, but console summarizes them as one status.) There might be some delay before the operator goes to `Progressing`, so we can't simply hide the alert if the operator if `Progressing: false`.

Simplest might be just to show the `authentication` operator status in the alert.

**Comment by spadgett** [comment]
It'd also be helpful if there's a problem with the IDP you added because you'd see the operator status go to `Degraded`.

**Comment by rhamilto** [comment]
Updated the alert body to include a link to the authentication cluster operator so the user can watch the reconfiguration (see video above).  Note I cut the video off before the reconfiguration actually started...

@megan-hall, @itsptk

**Review by itsptk — APPROVED** [review]
LGTM

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
