### PR TITLE
ODC-7424: Add e2e tests for vulnerabilities column in pipelinerun list and details page

### PR DESCRIPTION
**Pull request by karthikjeeyar**
Fixes:
https://issues.redhat.com/browse/ODC-7424 

1. Added test to vulnerabilities column in list and details page.
2. Added test to conditionally show `View SBOM` link in the kebab action.

Screenshot 2023-11-16 at 6 04 16 PM

### CODE REVIEW

**Comment by sanketpathak** [comment]
@karthikjeeyar I think the feature file changes are missing in pr

**Comment by karthikjeeyar** [comment]
Pushed the feature file 😅

**Comment by sanketpathak** [comment]
Tests run green
Screenshot 2023-11-18 at 2 19 21 AM

/lgtm

**Comment by sanketpathak** [comment]
PR only affects e2e tests
/label qe-approved
/label docs-approved
/label px-approved

**Pull request merged**
