### PR TITLE
OCPBUGS-41620: Fix access mode selection menu issue

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
The clone and restore modal shows two different options as selected on toggle, and dropdown options. For more: https://bugzilla.redhat.com/show_bug.cgi?id=2310369

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
For the PVC which has access mode RWX
Before fix:
Screenshot 2024-09-09 at 4 10 39 PM


After fix:
Screenshot 2024-09-09 at 4 11 21 PM

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve
/cherry-pick release-4.17

**Pull request merged**
