### PR TITLE
 kubevirt: add Advanced Cloud-init Tab to CreateVMWizard

### PR DESCRIPTION
**Pull request by suomiy**
- cloud init data is persisted inside the volume
- fix disks editing
- create InlineBooleanRadio component

depends on:
- [ ] #2896

### CODE REVIEW

**Comment by suomiy** [comment]
screenshots

ci


cia

**Comment by mareklibra** [comment]
/lgtm

Considering size of this PR, it was reviewed f2f off-line. 
Additional comments which (can) arise can be addressed in follow-ups.

**Pull request merged**
