### PR TITLE
OCPBUGS-3069: add Release not accepted to Update status on Cluster Se…

### PR DESCRIPTION
**Pull request by rhamilto**
…ttings

Screenshot 2022-11-07 at 3 19 33 PM

Note the popover contents are incorrect, but are included here to show the popover is being added.
Screenshot 2022-11-07 at 3 19 40 PM

### CODE REVIEW

**Comment by megan-hall** [comment]
lgtm

**Comment by rhamilto** [comment]
/hold cancel

After discussing this with @wking and @megan-hall, this is the approach we want to take.

@TheRealJon, please review.

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Comment by rhamilto** [comment]
@TheRealJon, mind re-tagging?  I had to rebase.

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Pull request merged**
