### PR TITLE
Bug 2092496: [release-4.10] Added vault_tenants_sa to the list of supported providers

### PR DESCRIPTION
**Pull request by RishabhKodes**
Signed-off-by: Rishabh Bhandari <rishabhbhandari6@gmail.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
/retitle Bug 2079685: [release-4.10] Bug 2079685: Added vault_tenants_sa to the list of supported providers

**Review by GowthamShanmugam — APPROVED** [review]

**Comment by jerolimov** [comment]
> /cherry-pick-approved

@SanjalKatiyar hey, it must be `/label cherry-pick-approved`

And I can not apply it myself 🤷‍♂️

**Comment by nehaberry** [comment]
Adding the details of testing done by @amr1ta 

Its working for dev setup 4.10 as well.

OCP version: 4.10.0-0.ci.test-2022-06-15-141110-ci-ln-iyfx9pb-latest
ODF version: 4.10.3-7

image

**Pull request merged**
