### PR TITLE
Bug 1959715: No relevant error when pg limit is reached in block pools page [4.7 Backport]

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
image

**Comment by GowthamShanmugam** [comment]
@afreen23 Please review

**Comment by afreen23** [comment]
/hold
Pending parent BZ verification

**Comment by afreen23** [comment]
/lgtm
code looks good

**Comment by GowthamShanmugam** [comment]
BZ is closed for this due to less priority: https://bugzilla.redhat.com/show_bug.cgi?id=1959715, Wont fix

**Pull request closed without merging**
