### PR TITLE
[release-4.14] OCPBUGS-38972: Redirects to new PipelineRun logs URL from old PipelineRun logs URL

### PR DESCRIPTION
**Pull request by vikram-raj**
This is a manual cherry-pick of https://github.com/openshift/console/pull/14083

### CODE REVIEW

**Review by vikram-raj — COMMENTED** [review]
Verified it on the cluster bot.


https://github.com/user-attachments/assets/328c7046-d3a2-4b9b-85ba-495a9b66f787

**Review by lokanandaprabhu — APPROVED** [review]

**Comment by vikram-raj** [comment]
manual cherry-pick PR https://github.com/openshift/console/pull/14263

**Pull request merged**
