### PR TITLE
CONSOLE-4120: remove orphaned GettingStartedGrid

### PR DESCRIPTION
**Pull request by rhamilto**
as it contains deprecated components

### CODE REVIEW

**Comment by rhamilto** [comment]
Tech debt so manually adding labels:
/label px-approved
/label docs-approved

/assign @yapei
/assign @sg00dwin

**Comment by XiyunZhao** [comment]
No layout issue was found on the Home -> Overview Getting Start Grid, both for administrator and normal users.
/label qe-approved

**Review by sg00dwin — APPROVED** [review]
/lgtm

**Pull request merged**
