### PR TITLE
Update base images

### PR DESCRIPTION
**Pull request by spadgett**
CONSOLE-462

/cc @jwforres @ggreer

### CODE REVIEW

**Comment by ggreer** [comment]
jenkins push

**Comment by coreos-ui** [comment]
The PR image failed.

**Comment by spadgett** [comment]
jenkins push

**Comment by ggreer** [comment]
I think a better solution would be to change the base to be scratch for the default build, then add two other dockerfiles that base off centos & rhel. That would keep build times low, improve container download/startup time, and still give us build artifacts for openshift releases.

**Comment by ggreer** [comment]
It looks like Clayton's OK with using scratch for dev builds & CI, and having another dockerfile for openshift releases.

**Comment by spadgett** [comment]
jenkins push

**Comment by coreos-ui** [comment]
The PR image failed.

**Comment by coreos-ui** [comment]
The PR image has been pushed to Quay with tag `pr_12_build_279`

**Comment by spadgett** [comment]
@ggreer updated, ptal

**Comment by ggreer** [comment]
jenkins push

**Comment by coreos-ui** [comment]
The PR image has been pushed to Quay with tag `pr_12_build_280`

**Comment by spadgett** [comment]
I'd like to reopen the discussion on this.

> increases the container size by an order of magnitude

It's bigger, but the image is still only ~90MB. Other components on the cluster use the same base image, so it should rarely need to be pulled.

> introduces multiple security issues

This seems to be because console CI pulled an old version from DockerHub. That's not how we build our release images.

> I think a better solution would be to change the base to be scratch for the default build, then add two other dockerfiles that base off centos & rhel. That would keep build times low, improve container download/startup time, and still give us build artifacts for openshift releases.

Problems using scratch:

* We'll need to maintain different Dockerfiles and potentially a different build script to build a static binary
* We're no longer developing and testing the image we're shipping (which sort of defeats the purpose of containers)
* It's no longer possible to rsh into the container to debug
* For local development, we typically just run the binary and `yarn run dev`. We're generally not rebuilding an image to test changes locally.

Maintaining the scratch image is some work for what seems like little gain and a few clear drawbacks.

How much time is this really saving in CI?

**Comment by spadgett** [comment]
/hold

scratch image is not working

**Comment by kans** [comment]
@spadgett Scratch would work but is a bit user hostile. `gcr.io/distroless/base` should be a drop-in replacement if you change the CMD to 

```
CMD ["/opt/bridge/bin/bridge", "--public-dir=/opt/bridge/static"]
```

**Comment by spadgett** [comment]
@kans Best I can tell this is not a drop-in replacement. Here is an example for go:

https://github.com/GoogleContainerTools/distroless#examples-with-docker

I really question whether we want different images for development and production.

@ggreer Can you give concrete numbers on how much the CentOS base adds to CI? It took me less than 3 minutes to build and push locally, although I had most of the layers already pulled. Do we take the hit every time or only the first build/push?

**Comment by spadgett** [comment]
Closing since this will need rework regardless of our approach.

**Pull request closed without merging**
