### PR TITLE
CONSOLE-4234,CONSOLE-4297: Remove deprecated PF Table from frontend/p…

### PR DESCRIPTION
**Pull request by TheRealJon**
…ublic/components/custom-resource-definition.tsx

### CODE REVIEW

**Comment by TheRealJon** [comment]
QE Approver
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @reestr

**Comment by yanpzhan** [comment]
Regression test about CRD related page passed against the pr code.
/label qe-approved

**Review by jhadvig — APPROVED** [review]
/lgtm

**Comment by TheRealJon** [comment]
@opayne1 Anything I can do to expedite? This is ready to merge once you approve.

**Pull request merged**
