### PR TITLE
CONSOLE-3907: add actions extension point to Events

### PR DESCRIPTION
**Pull request by rhamilto**
Update Events to render actions provided via [console.action/resource-provider](https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md#consoleactionresource-provider).  See example below.

If there is 1 action, render it as a button:
localhost_9000_k8s_all-namespaces_events (1)

If there is more than 1 action, render an actions dropdown:
localhost_9000_k8s_all-namespaces_events (2)

### To test:

Add the following to https://github.com/openshift/console/blob/6935c3fce1cf3d0a185e20ed8ca29547c9f0930f/frontend/packages/console-app/console-extensions.json#L1835
```json
  {
    "type": "console.action/resource-provider",
    "properties": {
      "model": {
        "version": "v1",
        "kind": "Event"
      },
      "provider": {
        "$codeRef": "eventActions.useEventActions"
      }
    }
```

Add the following to https://github.com/openshift/console/blob/6935c3fce1cf3d0a185e20ed8ca29547c9f0930f/frontend/packages/console-app/package.json#L52

```json
      "eventActions": "src/components/events/menu-actions.tsx"
```

Add the following as https://github.com/openshift/console/tree/master/frontend/packages/console-app/src/components/events/menu-actions.tsx

```tsx
import * as React from 'react';
import { Action } from '@console/dynamic-plugin-sdk';
import { EventKind, ExtensionHook } from '@console/internal/module/k8s';

export const useEventActions: ExtensionHook<Action[], EventKind> = (event) => {
  const eventActions = React.useMemo<Action[]>(() => {
    const actions: Action[] = [
      {
        id: 'test',
        label: 'Explain', // but use i18n in your code
        // eslint-disable-next-line no-console
        cta: () => console.log('Will open a modal for', event),
      },
      // {
      //   id: 'test2',
      //   label: 'A second action', // but use i18n in your code
      //   // eslint-disable-next-line no-console
      //   cta: () => console.log('Will open a modal for', event),
      // },
    ];
    return actions;
  }, [event]);

  return [eventActions, true, undefined];
};
```

### CODE REVIEW

**Comment by rhamilto** [comment]
Code Approver:
/assign @jhadvig 
QE Approver:
/assign @yapei
Docs Approver:
/assign @opayne1
PX Approver:
/assign @RickJWagner

**Comment by rhamilto** [comment]
cc: @bparees

**Comment by bparees** [comment]
cc @kyoto

**Comment by bparees** [comment]
thanks @rhamilto !

**Comment by RickJWagner** [comment]
Thank you for including the screen shots in the description of this issue, @rhamilto .  This greatly facilitates stakeholder review.

**Review by jhadvig — COMMENTED** [review]
QE assigne
/assign @XiyunZhao 

The change itself looks good. From the UX perspective I think that the btn would look better in the right bottom corner, rather then below the timestamp.

**Comment by tobiastal** [comment]
Hey guys,
from UX perspective, I would recommend adjusting the spacing, so everything is separated(4 different columns) and well-distinguished, while placing the button at the top right corner.
UX

**Comment by rhamilto** [comment]
> Hey guys, from UX perspective, I would recommend adjusting the spacing, so everything is separated(4 different columns) and well-distinguished, while placing the button at the top right corner. UX

What about mobile sizes where there isn't so much vertical space?
localhost_9000_k8s_all-namespaces_events(iPhone 14 Pro Max)

**Comment by tobiastal** [comment]
> > Hey guys, from UX perspective, I would recommend adjusting the spacing, so everything is separated(4 different columns) and well-distinguished, while placing the button at the top right corner. UX
> 
> What about mobile sizes where there isn't so much horizontal space? localhost_9000_k8s_all-namespaces_events(iPhone 14 Pro Max)

I would suggest to keep the CTA Button at the top right corner, and keep rest of the columns one below the other
Group 7

**Comment by jhadvig** [comment]
@tobiastal thanks for input. We had a broather discussion and we will probably need to revisit the whole Events page and make UX changes there.
Tagging the PR
/lgtm

**Comment by rhamilto** [comment]
@yapei, can you see this gets approved by QE?  Thanks!

**Comment by yapei** [comment]
@rhamilto @yanpzhan is working on the verification and will give feedback soon

**Comment by yanpzhan** [comment]
@rhamilto I have tested against the pr according to example codes, the action button/dropdowns are shown on events page. Drafted a test case for the US, could you help to review if the checkpoints are correct? Thanks! case link: https://polarion.engineering.redhat.com/polarion/redirect/project/OSE/workitem?id=OCP-71919.

**Comment by yanpzhan** [comment]
@rhamilto From current test result, there is no issue about the pr, approve it. pls feel free to give suggestion to my test case, thanks!
/label qe-approved

**Pull request merged**
