### PR TITLE
Bug 1989143: [e2e][automation] Add hostpath-provisioner-setup.yml used in release-4.8 tests

### PR DESCRIPTION
**Pull request by yaacov**
fix test error:
`error: unable to read URL "https://raw.githubusercontent.com/openshift/console/master/frontend/packages/kubevirt-plugin/integration-tests/ci-scripts/hostpath-provisioner-setup.yml", server reported 404 Not Found, status code=404`

On e2e tests for release-4.8 we need this file

Signed-off-by: yaacov <kobi.zamir@gmail.com>

### CODE REVIEW

**Comment by spadgett** [comment]
@yaacov Why are the 4.8 tests pulling the file from the master branch? Shouldn't they use the file in the 4.8 branch?

It's unclear to me why we're making an HTTP request to get the file since it should be available locally in the filesystem.

**Comment by yaacov** [comment]
> @yaacov Why are the 4.8 tests pulling the file from the master branch? Shouldn't they use the file in the 4.8 branch?
> 
> It's unclear to me why we're making an HTTP request to get the file since it should be available locally in the filesystem.

yes, they should not, I also made this one:
https://github.com/openshift/console/pull/9700

but I also make this to unblock PRs waiting for tests until we can do the fix in release-4.8

after that I plan to remove this files again

**Comment by yaacov** [comment]
@spadgett ^^

**Pull request merged**
