### PR TITLE
Bug 2074100: fix CRD name filter

### PR DESCRIPTION
**Pull request by rhamilto**
After:

https://user-images.githubusercontent.com/895728/163433611-414066f0-b6f2-422b-8518-7c2f4a115eb9.mov

### CODE REVIEW

**Comment by spadgett** [comment]
/lgtm cancel

The ConsoleCLIDownload integration tests are failing

**Comment by rhamilto** [comment]
> /lgtm cancel
> 
> The ConsoleCLIDownload integration tests are failing

D'oh!  Thanks, @spadgett.  Fixed.

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
