### PR TITLE
Remove namespace dependency and fix top consumer

### PR DESCRIPTION
**Pull request by cloudbehl**
- Remove namespace dependency from pv, pvc and storageclass
- Fix width for top consumer graph

Signed-off-by: Ankush Behl <cloudbehl@gmail.com>

### CODE REVIEW

**Comment by afreen23** [comment]
can you add a screenshot for width fix. Thanx!

**Comment by cloudbehl** [comment]
Screenshot from 2019-09-05 14-11-43
Screenshot from 2019-09-05 14-11-35
Screenshot from 2019-09-05 14-11-17

**Comment by afreen23** [comment]
Why the width fix is required though ?

**Comment by cloudbehl** [comment]
if number increasing 100's then it's getting hidden.

**Comment by afreen23** [comment]
> if number increasing 100's then it's getting hidden.

Don't you think legends are out of sync due to this, they should be in alignment with y axis

**Comment by cloudbehl** [comment]
> > if number increasing 100's then it's getting hidden.
> 
> Don't you think legends are out of sync due to this, they should be in alignment with y axis

I think this should be fine.

**Comment by afreen23** [comment]
> > > if number increasing 100's then it's getting hidden.
> > 
> > 
> > Don't you think legends are out of sync due to this, they should be in alignment with y axis
> 
> I think this should be fine.

If we are following PF4 in console then I wont expect this firstly,
https://patternfly-react.surge.sh/patternfly-4/charts/chartline/
Other than that its just a minor thing we can enhance it.
doing something like ` legendPosition="bottom-left"` can fix it

**Pull request merged**
