### PR TITLE
Add charts for metrics on route details

### PR DESCRIPTION
**Pull request by zherman0**
Add charts to the route overview that show some basic metrics from prometheus data.

route-charts1
route-charts2

### CODE REVIEW

**Comment by zherman0** [comment]
@smarterclayton @spadgett - The first iteration of adding charts to the routes overview

**Comment by spadgett** [comment]
@smarterclayton we're going to look at stacked charts in a follow up so that we can get basic router metrics done for 4.3

**Comment by spadgett** [comment]
Let's go ahead with the change. If there is an issue with the query, we can address as a bug.

/hold cancel

**Comment by smarterclayton** [comment]
Looks fine to me

**Pull request merged**
