### PR TITLE
[release-4.8] Bug 2017469: key not a valid prop name causing display issue in env editor

### PR DESCRIPTION
**Pull request by jcaianirh**
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2017469
Screen Shot 2021-11-09 at 1 17 24 PM

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
Nice catch Joe 👍 

/lgtm

**Comment by jhadvig** [comment]
@yapei could you please take a look and add the cherry-pick-approved label is its ok?
Thanks!
/assign @yapei

**Review by zherman0 — APPROVED** [review]
/lgtm

**Comment by yapei** [comment]
verified that the key value field is properly updated
Screen Shot 2021-11-12 at 11 16 48 AM
/label qe-approved
/lgtm

**Pull request merged**
