### PR TITLE
ODC-7620: Modal submit button: show loading state

### PR DESCRIPTION
**Pull request by logonoff**
**Fixes**: 

https://issues.redhat.com/browse/ODC-7620

**Solution Description**: 

I noticed that modals are not affected by the previous PR #13959, this PR applies the same change to modals

**Screen shots / Gifs for design review**: 

https://github.com/openshift/console/assets/18614559/39695775-a692-42e4-9d41-c27b2fecad51

**Unit test coverage report**: 

Unchanged

**Test setup:**

n/a

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari

### CODE REVIEW

**Comment by vikram-raj** [comment]
It will affect the Admin perspective as well. So, better to get +1 from @jhadvig. 

Context:  In dev console, we updated the all forms submit button with [pf progress indicator](https://www.patternfly.org/components/button#progress-indicators) in the button itself instead of the inline indicator below the button. 

This PR adding the progress indicator to the modal submit button will affect the admin perspective as we are using the same modal component in both perspectives. 

@jhadvig are you fine with this change?

**Comment by jhadvig** [comment]
@vikram-raj the change looks good to me 👍 
Glad we are able to use the PF components for this.

**Review by vikram-raj — APPROVED** [review]
Thanks @logonoff for adding this to the modal submit action as well.

/lgtm

**Comment by vikram-raj** [comment]
propagated from the epic
/label docs-approved
/label px-approved

**Pull request merged**
