### PR TITLE
Fix for catalog tile text overflow, tree shaking pf react extensions

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Update versions of patternfly-react and patternfly-react-extensions to:

- Add text fade out on overflow of catalog tiles
- Allow tree shaking to dis-include patternfly-react components that are not used

@sosiouxme fyi

/hold

### CODE REVIEW

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
We probably want to wait for #692 so we don't have parallel PRs updating offline dependencies

**Comment by spadgett** [comment]
@jeff-phillips-18 You'll want to rebase now that #692 merged. Thanks!

**Comment by jeff-phillips-18** [comment]
Rebased.

**Comment by sosiouxme** [comment]
@jeff-phillips-18 please include the following change to the sources file:

```
--- a/sources
+++ b/sources
@@ -1,2 +1,2 @@
 401aa1438604b8e32306fa2bd4f8e211  node-v8.9.4-headers.tar.gz
-a49c88ab70f7c240d443b51770db791d  yarn-offline.tar
+5a31a2c68718575bd3b1d239e9b2c103  yarn-offline.tar
```

**Comment by jeff-phillips-18** [comment]
Updated `sources`

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
Looks spurious:

```
1) Kubernetes resource CRUD operations Namespace : deletes the namespace
   StaleElementReferenceError: stale element reference: element is not attached to the page document
```

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
