### PR TITLE
[release-4.10] Bug 2089315: fix rolebinding in DevConsole dropping all subjects when updating

### PR DESCRIPTION
**Pull request by debsmita1**
manual cherry-pick of https://github.com/openshift/console/pull/11292

**GIF:**
4 10-pz

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Didn't tested it yet, but code change is similar to the 4.11 version and we want fix this in 4.10.

/approve
/label backport-risk-assessed

**Comment by jerolimov** [comment]
My tests was successfully :+1:
/lgtm

**Comment by hemantsaini-7** [comment]
/label cherry-pick-approved

image

**Pull request merged**
