### PR TITLE
OCPBUGS-11971: When removing the project owner from the project in GUI, instead of that user, the group (the default group added as project admin through the project template) will be removed.

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGS-11971

**Analysis / Root cause**: 
While removing the subjects were not properly considered

**Solution Description**: 
Proper subject to remove is considered

**Screen shots / Gifs for design review**: 

https://github.com/openshift/console/assets/102503482/6c293666-70bc-4324-b64c-738492fbd818

**Unit test coverage report**: 
NA

**Test setup:**

Follow steps to reproduce in https://issues.redhat.com/browse/OCPBUGS-11971 

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Review by Lucifergene — COMMENTED** [review]
The fix is working as expected.

https://github.com/openshift/console/assets/47265560/17b60bcc-34e9-4a9e-aa9d-d265aa8e9131

**Comment by lokanandaprabhu** [comment]
> I noticed an edge-case issue. I am not able to remove a group from the Project access page. The same group has been defined in 2 different Rolebinding of a namespace. When I remove it it does not make any network call.

Updated the PR to handle this.

**Pull request merged**
