### PR TITLE
eslint: no-multiple-empty-lines

### PR DESCRIPTION
**Pull request by mareklibra**
Enforce no extra empty line at the end of a file.

Motivation for this PR is nit-pick in https://github.com/openshift/console/pull/1997#discussion_r303996926 .

### CODE REVIEW

**Comment by vojtechszocs** [comment]
cc @christianvogt

**Comment by christianvogt** [comment]
Looks fine to me as this matches what's done in the main eslint config.

**Comment by spadgett** [comment]
One more file to fix before this can merge:

``` 
/go/src/github.com/openshift/console/frontend/public/components/volumes-table.tsx
  Too many blank lines at the end of file. Max of 0 allowed
```

/hold
to avoid retest. Feel free to remove the hold when updated.

**Comment by mareklibra** [comment]
re-executed `yarn run lint --fix`, removing `on hold`

**Pull request merged**
