### PR TITLE
Bug 2023077: [e2e][automation] Home Overview Virtualization status

### PR DESCRIPTION
**Pull request by lkladnit**
Cypress tests for [CNV-14292: add TC/automation for fixed bugs](https://issues.redhat.com/browse/CNV-14292) #1
[Polarion doc](https://polarion.engineering.redhat.com/polarion/#/project/CNV/wiki/Management/_UI_%20VM%20actions)
[TC](https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-7507)

### CODE REVIEW

**Comment by gouyang** [comment]
@yaacov Please review.

**Comment by yaacov** [comment]
/lgtm

Nit pics about the pull request description:
Should have been:
```
Description: Test Virtualization status on Overview page

Test that status card is displayed, and Virtualization has green icon with 'Healthy' tooltip

Polarion: https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-7507
Jira: https://issues.redhat.com/browse/CNV-14292
```

**Comment by lkladnit** [comment]
> /lgtm
> 
> Nit pics about the pull request description: Should have been:
> 
> ```
> Description: Test Virtualization status on Overview page
> 
> Test that status card is displayed, and Virtualization has green icon with 'Healthy' tooltip
> 
> Polarion: https://polarion.engineering.redhat.com/polarion/#/project/CNV/workitem?id=CNV-7507
> Jira: https://issues.redhat.com/browse/CNV-14292

Thanks, I'll follow this guidelineis

**Pull request merged**
