### PR TITLE
OCPBUGS-5435: Add managed cluster api server config validation back t…

### PR DESCRIPTION
**Pull request by TheRealJon**
…o bridge

### CODE REVIEW

**Review by spadgett — COMMENTED** [review]
Will this be a problem if there is a firewall between the hub and spoke where we can't use the public API server URL?

We might be able to use the OAuth service on the spoke cluster directly through the service proxy instead of the public endpoint, which would presumably eliminate the need to discover the endpoints altogether.

**Comment by spadgett** [comment]
There's an `oauth-openshift` service in the `openshift-authentication` namespace that I believe has the token endpoints.

**Comment by TheRealJon** [comment]
This is now covered by https://github.com/openshift/console/pull/12545

**Pull request closed without merging**
