### PR TITLE
ODC-7482: Add flags checks to hide Pipeline static plugin List and details pages

### PR DESCRIPTION
**Pull request by vikram-raj**
story: https://issues.redhat.com/browse/ODC-7482

### CODE REVIEW

**Comment by vikram-raj** [comment]
Propagate from the epic
/label docs-approved
/label px-approved

**Comment by lokanandaprabhu** [comment]
Tested locally. Working fine.

/lgtm

**Comment by sanketpathak** [comment]
Verified on cluster, pipelines functionality is working as expected
/label qe-approved

**Pull request merged**
