### PR TITLE
Bug 1840992: Refactor release_name query param to name

### PR DESCRIPTION
**Pull request by akashshinde**
Please refer for more info: https://issues.redhat.com/browse/APPSVC-508

### CODE REVIEW

**Comment by akashshinde** [comment]
@rohitkrai03 If you could manage to make query param changes in devconsole UI for v4.5, we can merge this accordingly.

**Comment by sbose78** [comment]
Does this need changes on the UI side as well? If the change is simple, could we add those changes to this PR itself ?

**Comment by akashshinde** [comment]
> Does this need changes on the UI side as well? If the change is simple, could we add those changes to this PR itself ?

Good idea, we can have those changes here as well

**Comment by rohitkrai03** [comment]
@akashshinde The UI uses this endpoint in one place at the moment so you can include the UI change in this PR easily. But I do have a cleanup and refactor PR that changes a lot of Helm code in UI - https://github.com/openshift/console/pull/4912. This PR can create conflicts for you but they should still be very small.

**Comment by akashshinde** [comment]
cc @benjaminapetersen

**Comment by rohitkrai03** [comment]
@akashshinde I don't see the UI changes included in this PR.

**Comment by akashshinde** [comment]
> @akashshinde I don't see the UI changes included in this PR.

It seems UI isn't making use of this API as of now, so raised another API https://github.com/openshift/console/pull/5113, cc: @rohitkrai03

**Comment by rohitkrai03** [comment]
@akashshinde The UI does uses the API to fetch release details in upgrade form - https://github.com/openshift/console/blob/master/frontend/packages/dev-console/src/components/helm/helm-utils.ts#L115. Once the backend changes gets merged, UI will break because of it. Also, the changes in #5113 are not an urgent requirement right now since the API currently being used works fine for both the cases.

**Comment by akashshinde** [comment]
@pedjak Done, @rohitkrai03 can you take a look at it again ?

**Comment by akashshinde** [comment]
@benjaminapetersen please review this PR

**Comment by benjaminapetersen** [comment]
/approve

but you will need a bugzilla to merge code.

**Pull request merged**
