### PR TITLE
CONSOLE-3793: add uptime to Node pages

### PR DESCRIPTION
**Pull request by rhamilto**
https://github.com/openshift/console/assets/895728/249cc17d-ccdd-4c1b-a1dd-7721bd319194

### CODE REVIEW

**Comment by rhamilto** [comment]
Design Approver:
/assign @yuvalgalanti
Code Approver:
/assign @jhadvig 
QE Approver: 
/assign @yanpzhan
Docs Approver: 
/assign @opayne1
PX Approver:
/assign @RickJWagner

**Comment by rhamilto** [comment]
/retest

"Error: This socket has been ended by the other party"

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Comment by yanpzhan** [comment]
The feature from pr works.
/label qe-approved

**Pull request merged**
