### PR TITLE
odc-6017-updated helm scripts with new page objects

### PR DESCRIPTION
**Pull request by makambalaji**
**Description:**
Fixing helm scripts and adding them to CI
Couple of tests are broken due to the bug: https://issues.redhat.com/browse/ODC-6107. So creating another pr: https://github.com/openshift/console/pull/9709

**Jira Id:**
 Jira Id : https://issues.redhat.com/browse/ODC-6017

**Refactoring criteria for approving Automation PR:**

- [x] update the test cases count in [Automation status confluence Report](https://docs.jboss.org/display/ODC/Automation+Status+Report)
- [x] Execute the scripts in Remote cluster

**Execution Commands:**
Example:
```
    export NO_HEADLESS=true && export CHROME_VERSION=$(/usr/bin/google-chrome-stable --version)
    BRIDGE_KUBEADMIN_PASSWORD=YH3jN-PRFT2-Q429c-5KQDr
    BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.dev-svc-4.8-042801.devcluster.openshift.com
    export BRIDGE_KUBEADMIN_PASSWORD
    export BRIDGE_BASE_ADDRESS
    oc login -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD
    oc apply -f ./frontend/integration-tests/data/htpasswd-secret.yaml
    oc patch oauths cluster --patch "$(cat ./frontend/integration-tests/data/patch-htpasswd.yaml)" --type=merge
    ./test-cypress.sh -p helm -h true
```

**Screen shots**:
image

**Browser conformance**:

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by makambalaji** [comment]
/hold
Bug: https://issues.redhat.com/browse/ODC-6200 needs to be fixed before this pr merge

**Comment by makambalaji** [comment]
/unhold
Bug: https://issues.redhat.com/browse/ODC-6200 got fixed and pr is merged

**Comment by makambalaji** [comment]
@gajanan-more - Please review this pr using nightly build : 4.9.0-0.nightly-2021-07-26-220837

**Comment by makambalaji** [comment]
Re-executed again on remote cluster and below are the results 
image

**Comment by sanketpathak** [comment]
Tests are running fine on the remote cluster
Screenshot from 2021-07-29 21-08-36

/lgtm

**Comment by christianvogt** [comment]
PR addresses integration tests only.

/label px-approved
/label docs-approved
/label qe-approved
/approve

**Comment by makambalaji** [comment]
/hold
The issue is fixed in https://github.com/openshift/console/pull/9579

**Comment by makambalaji** [comment]
Due to one Bugzilla bug, UI got changed. so the scripts are broken. Need to update the script before merging this pr
/hold

**Comment by makambalaji** [comment]
Created separate pr: https://github.com/openshift/console/pull/9709 to address the bug: https://issues.redhat.com/browse/ODC-6107

**Comment by rohitkrai03** [comment]
@makambalaji Is this PR dependent on https://github.com/openshift/console/pull/9709? Why not add both changes in one PR?

**Comment by makambalaji** [comment]
> @makambalaji Is this PR dependent on #9709? Why not add both changes in one PR?

Couple of changes needs to be done i.e, approximately 8 files. So I think better to merge this first

**Review by rohitkrai03 — APPROVED** [review]
/lgtm

**Pull request merged**
