### PR TITLE
Fixes: Topology Error on selection of group with more then two nodes

### PR DESCRIPTION
**Pull request by sahil143**
**Fixes**: https://issues.redhat.com/browse/ODC-3605

**Analysis / Root cause**: Node id's are being added twice in the groups

**Solution Description**: cleanup code that is responsible for duplicate id's.

**Screen shots / Gifs for design review**: 

**BEFORE**
Screenshot from 2020-04-17 17-15-50

**AFTER**
Screenshot from 2020-04-17 17-14-31

**Unit test coverage report**: 

TODO

**Test setup:**

**Browser conformance**: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by invincibleJai** [comment]
/approve

verified locally works as expected

**Comment by spadgett** [comment]
/hold
for #5100

**Comment by spadgett** [comment]
/hold cancel
/lgtm cancel

frontend tests are failing

**Pull request merged**
