### PR TITLE
Fix disable delete and drag button on empty name value pair editor

### PR DESCRIPTION
**Pull request by gijohn**
Fixes: https://jira.coreos.com/browse/ODC-1481
delete-button

### CODE REVIEW

**Comment by joshuawilson** [comment]
@gijohn this is outside of dev console, only Christian can approve it or someone on the admin/core team can.

**Comment by joshuawilson** [comment]
@spadgett This appears to work correctly for where we need it but I don't know where core is using it and if there could be any negative impacts. Can you please have someone from your side review.

**Comment by spadgett** [comment]
Stepping back, I think there's a bit of a divide on handling forms, buttons, and validation between admin console and dev console.

* admin console: leave buttons enabled always, use native browser support for required fields, rely on server for validation
* dev console: disable buttons until form is valid, validate client-side as much as possible before submitting form

I worry that we've lost some consistency in the user experience across console. It becomes more apparent in shared components like this. The existing behavior is more in line with admin console forms and working as intended. The new behavior is more in line with dev console forms. The admin console behavior is largely a holdover from Tectonic console, which took this philosophy. I didn't like the admin console form behavior at first, but having used it for a while, I've come around. It works well!

In 3.x, we performed extensive client-side validation. We ran into a number of bugs around this, either because

1. We had incorrect assumptions / validation logic in the client implementation, or 
2. The API changed sometime after the initial console feature was implemented, which caused bugs in later releases.

(2) is hard to avoid no matter how careful you are with the initial implementation. Some of these bugs blocked users from making changes they should be able to make. There was at least one case where we lost data in the route editor because of an API change to routes.

I was happy when we started to let the server do validation, since it avoided having to reimplement complicated server validation logic on the client and seemed more sustainable in the face of future API changes.

I realize this is a small change and a long comment. But I guess my point is the current behavior is more in line with the existing admin console forms. I feel like we should step back and decide what experience we want for forms. Maybe it's OK to have different approaches in different perspectives, but all else being equal, I'd think we'd want consistency.

I'm hesitant to go back to too much client-side field validation. Regular expressions like #2373 scare me :) I'd really prefer to use server dry-run for validation when possible. An easy win might be to align on when we disable buttons, though, for required fields and simple checks.

cc @openshift/team-ux-review

**Comment by spadgett** [comment]
Can we target 4.3? This is a minor bug, and the current behavior doesn't have any bad effects.

We definitely want to fix #2243 in 4.2, though.

**Comment by spadgett** [comment]
If we make this change here, we should update list-input.tsx minimally which has the same remove button behavior. There are probably some other similar places.

**Comment by gijohn** [comment]
@christianvogt, I have made the requested changed.

**Pull request merged**
