### PR TITLE
Bug 2033013: Fix user preferences project dropdown

### PR DESCRIPTION
**Pull request by rottencandy**
**Fixes**: 
https://issues.redhat.com/browse/OCPBUGSM-38512

**Analysis / Root cause**: 
Regression caused by #10466 

**Solution Description**: 
Restrict height of `MenuContent`.

**Screen shots / Gifs for design review**: 

**Unit test coverage report**: 
(Unchanged)

**Test setup:**
- Navigate to user preferences page (dropdown from top-right)
- Open project selection dropdown

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

/kind bug

### CODE REVIEW

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Comment by karthikjeeyar** [comment]
Verified locally, works fine
/lgtm

**Pull request merged**
