### PR TITLE
OCPBUGS-38803: CONSOLE-4108 [4.16 backport] Show deprecated operators in OperatorHub

### PR DESCRIPTION
**Pull request by cyril-ui-developer**
Manually backported the following PR/commits to release-4.16 branch: 
- [CONSOLE-4098](https://issues.redhat.com//browse/CONSOLE-4098): Show deprecated operators in OperatorHub (Post-installation screens): https://github.com/openshift/console/pull/14048
- [CONSOLE-4098](https://issues.redhat.com//browse/CONSOLE-4098): Show deprecated operators in OperatorHub (Post-installation screens): https://github.com/openshift/console/pull/14048

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by cyril-ui-developer** [comment]
Docs Approver:
/assign @yapei

**Comment by yapei** [comment]
Deprecated icon is not shown in `Channel` and `Version` 
416-channel-version

this is how OCP 4.17 looks like
417-channel-version

**Comment by cyril-ui-developer** [comment]
> Deprecated icon is not shown in `Channel` and `Version` 416-channel-version
> 
> this is how OCP 4.17 looks like 417-channel-version

Weird! I am on PTO until Tuesday next week. I will take a look at it when I return.

**Comment by cyril-ui-developer** [comment]
@yapei I have reproduced the issue. It is happening only in Firefox version 4.16. I think we can address this as a bug. I will open a bug report for it and keep you posted on the issue.
cc: @jhadvig

**Comment by yapei** [comment]
thanks @cyril-ui-developer 
/label qe-approved

**Pull request merged**
