### PR TITLE
Fix: console error while installing pipeline operator

### PR DESCRIPTION
**Pull request by gijohn**
Fixes https://jira.coreos.com/browse/ODC-1694

### CODE REVIEW

**Comment by spadgett** [comment]
/hold

We shouldn't need a static model for this. We should have the model from API discovery.

**Comment by spadgett** [comment]
To expand on this: it's fine to have the model if we're using it in the code or to override a value like the label or abbreviation. But I don't think it should be needed to avoid the bug we're seeing. We should investigate and understand what's going on since it could be a problem for any operator.

**Comment by christianvogt** [comment]
I agree with what @spadgett said.
@andrewballantyne ran into some issues regarding model lookup via kind vs reference in his PR: https://github.com/openshift/console/pull/2917

Probably got something similar going on.

**Comment by spadgett** [comment]
I think there's a race when installing an operator. We detect changes the new API and rerun discovery, but it's not always fast enough.

**Comment by christianvogt** [comment]
Thanks for the insight.

**Comment by gijohn** [comment]
@spadgett can you provide more insight on how the discovery is happening? possibly the code base for the logic. I can investigate on this.

**Pull request closed without merging**
