### PR TITLE
Bug 1891376: Remove title passed to the PrometheusGraph component in the AreaChart

### PR DESCRIPTION
**Pull request by jhadvig**
Was introduced in https://github.com/openshift/console/pull/6878/files

/assign @spadgett 
cc'ing @dtaylor113

### CODE REVIEW

**Comment by spadgett** [comment]
@jhadvig Does this still pass the accessibility check?

**Comment by spadgett** [comment]
@jhadvig You'll need to revert the unit test change as well.

@dtaylor113 It looks like this is passing the e2e tests... Was your original change to fix a problem found during the e2e tests, or was it an accessibility issue found with other testing?

**Comment by jhadvig** [comment]
Closing the PR per discussion with @dtaylor113

**Pull request closed without merging**
