### PR TITLE
Bug 2017879: Omission of translation

### PR DESCRIPTION
**Pull request by orangeji11**
translate "alternate" in locale zh.

### CODE REVIEW

**Comment by spadgett** [comment]
/remove-lifecycle stale
/assign @rebeccaalpert 

Thank you for the PR. Most likely this was left in English intentionally by the translator, but we can raise it with the globalization team.

**Comment by XiyunZhao** [comment]
@rebeccaalpert there is one extra space on the translation text "添加 备用服务"

**Pull request merged**
