### PR TITLE
NO-JIRA: Update OWNERS files

### PR DESCRIPTION
**Pull request by jhadvig**
/assign @TheRealJon

### CODE REVIEW

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Comment by rhamilto** [comment]
When you rebase, I think it would be good to also remove the following individuals from various files:

* @dtaylor113
* @jcaianirh 
* @kdoberst

**Comment by rhamilto** [comment]
And there are additional instances of the following that can be removed:

* @bparees 
* @dtaylor113 
* @zherman0

**Pull request merged**
