### PR TITLE
CONSOLE-2452: i18n for replicationControllers

### PR DESCRIPTION
**Pull request by zherman0**
[CONSOLE-2452](https://issues.redhat.com/browse/CONSOLE-2452): i18n for replicationControllers

### CODE REVIEW

**Comment by zherman0** [comment]
@spadgett - I fixed your request. This one should be ready for final review.

**Review by spadgett — APPROVED** [review]
/lgtm
/hold for approvals
/assign @yapei @ahardin-rh @sferich888

**Pull request merged**
