### PR TITLE
ODC-5803-epic automation for workspaces

### PR DESCRIPTION
**Pull request by makambalaji**
**Description**: 
Automating the gherkin scripts related to EPIC [ODC-3991](https://issues.redhat.com/browse/ODC-3991)
Gherkin scripts designed for this epic are present in PR: [#8361](https://github.com/openshift/console/pull/8361) 

**Jira Id**; https://issues.redhat.com/browse/ODC-5803

**Browser & its version** : Chrome 89

**Execution Commands**:

1. Update the "TAGS" as **"@pipelines and @[odc-3991](https://issues.redhat.com/browse/odc-3991) and not @manual and not @to-do**",
 [pipelines-plugin/integtaion-tests/cypress.json](https://github.com/openshift/console/blob/master/frontend/packages/pipelines-plugin/integration-tests/cypress.json) file 

2. In below commands, please update url and password based on the cluster

```
export NO_HEADLESS=true && export CHROME_VERSION=$(/usr/bin/google-chrome-stable --version)
BRIDGE_KUBEADMIN_PASSWORD=YH3jN-PRFT2-Q429c-5KQDr
BRIDGE_BASE_ADDRESS=https://console-openshift-console.apps.dev-svc-4.8-042801.devcluster.openshift.com
export BRIDGE_KUBEADMIN_PASSWORD
export BRIDGE_BASE_ADDRESS
oc login -u kubeadmin -p $BRIDGE_KUBEADMIN_PASSWORD

#Execute below commands under console folder
oc apply -f ./frontend/integration-tests/data/htpasswd-secret.yaml
oc patch oauths cluster --patch "$(cat ./frontend/integration-tests/data/patch-htpasswd.yaml)" --type=merge

./test-cypress.sh -p pipelines
```
Select the 
1. create-from-builder-page.feature
2. pipelines-runs.feature
3. pipelines-workspaces.feature
4.  pipelines/pipelines-actions.feature
5. pipelines/pipelines-triggers.feature

**Results**:
image

image

image

image

image

### CODE REVIEW

**Review by karthikjeeyar — COMMENTED** [review]
Right after the pipeline operator installation, the first test checks for the `[] Add pipeline` checkbox in the git form and fails to find as the operator installation will takes its time to install all sub components.

image

image

**Comment by karthikjeeyar** [comment]
Most of the tests in any feature files are skipped and has the following error.
image

In the automation test for workspaces, I see only one test passing (tried multiple times), but the screenshot in PR description has multiple tests passing. Am I missing something here :thinking:  ?

image

**Comment by makambalaji** [comment]
> Most of the tests in above feature files are skipped and has the following error.
> image
> 
> In the automation test for workspaces, I see only one test passing (tried multiple times), but the screenshot in PR description has multiple tests passing. Am I missing something here  ?
> 
> image

cypress.config file needs to be changed as mentioned in the description

**Comment by makambalaji** [comment]
> Right after the pipeline operator installation, the first test checks for the `[] Add pipeline` checkbox in the git form and fails to find as the operator installation will takes its time to install all sub components.
> 
> image
> 
> image

This is known issue. Defect https://issues.redhat.com/browse/ODC-5817 already raised for the same

**Comment by karthikjeeyar** [comment]
Thanks @makambalaji for the clarification.
/lgtm

**Comment by gajanan-more** [comment]
Working as expected. 

/lgtm

**Pull request merged**
