### PR TITLE
Add ability to filter topology by resource types

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**Fixes**
https://issues.redhat.com/browse/ODC-4319

**Description**
As a user, I want to show/hide specific resource types in the topology view

When a resource is selected, that resource and its children are shown.

**Screenshots**

image

**Browser conformance**: 
- [x] Chrome
- [x] Firefox
- [x] Safari
- [ ] Edge

/kind feature

cc @openshift/team-devconsole-ux @serenamarie125 @beaumorley @bgliwa01

### CODE REVIEW

**Comment by andrewballantyne** [comment]
Odd... Knative selected, but I don't see Knative - I see the Revision. This would be confusing, no?

Screen Shot 2020-07-30 at 4 08 32 PM
Screen Shot 2020-07-30 at 4 08 37 PM

**Comment by andrewballantyne** [comment]
There appears to be a rendering issue with groups too... It seems I can toggle off my group of Deployments, then re-enable them... and the grouping doesn't come back immediately. I wanna say it comes back after "some time" (feels like a webhook kick) or some sorta mouse-over triggering it. I don't think it's a "svg rendering issue" because the alignment is off:

Screen Shot 2020-07-30 at 4 26 28 PM
Screen Shot 2020-07-30 at 4 26 37 PM

**Comment by jeff-phillips-18** [comment]
> Odd... Knative selected, but I don't see Knative - I see the Revision. This would be confusing, no?

Fixed.

**Comment by invincibleJai** [comment]
Thanks @jeff-phillips-18 , works as expected and i could do the filter as mentioned (some cases i see slight delay in filter but they depends on nodes we have). Another observation is In design there is equal gap between `Display Options`, `Filter by Resource`

image

**Comment by jeff-phillips-18** [comment]
> Another observation is In design there is equal gap between `Display Options`, `Filter by Resource`

Fixed.

**Comment by andrewballantyne** [comment]
/retitle Add ability to filter topology by resource types
/hold

Putting on hold so it doesn't look like this is incomplete, just waiting on dependant PR to merge.

**Comment by andrewballantyne** [comment]
Only pending issue I can see is this one: https://issues.redhat.com/browse/ODC-4417

**Pull request merged**
