### PR TITLE
Do not render pod labels because they are too expensive and mostly po…

### PR DESCRIPTION
**Pull request by kans**
…intless.

### CODE REVIEW

**Comment by spadgett** [comment]
Is the thought to eventually remove labels from all resource lists?

**Comment by kans** [comment]
@spadgett 

Most rows are currently too expensive to scroll smoothly with virtual rendering.  Labels are the hardest component to deal with all around:

1. They are the most expensive component to render and to paint
2. They are arbitrarily long which forces rows to be a dynamic height (really bad for performance and the virtual rendering UI on big lists)
3. Their contents is elided on non-huge screens.
4. Alot of labels are meaningless k8s abstraction leaks.

However, the search page probably doesn't make much sense as is without labels *somewhere*...

The options aren't great and we have punted on this for a while - I don't think there is much more significant performance that can be squeezed out of the other small components:

You could resurrect the Redux -> JSON performance improvement branch which would be a 20% speed up on big lists.  The gist is that `<Firehose/>` shouldn't be JSON serializing the entire working set out of Immutable (it doesn't even know which parts will be rendered).  It would be a significant effort because the interface for lists would need to change *everywhere*, although you could do the transition piecemeal.  The speedup comes from being able to do a shallow equals (PureComponent) on Immutable objects and obviously not JSONing the whole list (that is how Immutable should be used - the current system dates back to the pre-react transition).  

We have also tinkered with memoizing the subset of information we care about directly in Redux and throwing away the rest (eg, the pod status/readiness).  This is tricky since Redux data is potentially consumed from multiple sources, but it could be a small speedup.  

Its possible that React 17 will make this better (or at least bearable), but perhaps only with some effort.  Otherwise, Lists could just show less data - eg, setting a minimum height of 75 px (ie, show fewer of them), or even set some fixed height.  Maybe some combination of these changes would be enough.

@robszumski may have some other thoughts here too

**Comment by spadgett** [comment]
I'm wondering if owner references aren't more useful than labels anyway without the performance penalty.

CLI doesn't show labels even with `kubectl get pods -o wide`. We have limited space in the tables, so we should be picky about what we show anyway. With more columns, the content starts to wrap awkwardly and you get fewer rows on the screen. Labels can also make the rows different heights.

**Comment by robszumski** [comment]
> I'm wondering if owner references aren't more useful than labels anyway without the performance penalty.

That's an interesting idea!

> With more columns, the content starts to wrap awkwardly and you get fewer rows on the screen.

This is why I wanted to find a way around listing the namespace on every table, but I think we have to, which eats up space.

Wasn't there an idea to stop rendering labels on scroll and then show them? Does that get us anywhere?

**Comment by alecmerdler** [comment]
We can revisit this again when needed.

**Pull request closed without merging**
