### PR TITLE
[release-4.9] Bug 2069258: Decode secrets before authorizing repository

### PR DESCRIPTION
**Pull request by rottencandy**
Manual cherry-pick of https://github.com/openshift/console/pull/11094

Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=2069258

### CODE REVIEW

**Comment by rottencandy** [comment]
Tested on cluster, works as expected.

https://user-images.githubusercontent.com/20013884/161704569-27b31821-dba9-43c0-9891-1e0b4a46c1f7.mp4

/cc @sanketpathak

**Review by vikram-raj — APPROVED** [review]
Verified it on cluster bot. works as expected.

Kapture 2022-04-18 at 14 26 17
 
 /lgtm

**Pull request merged**
