### PR TITLE
Bug 1833087: Update placement of inline editing icons

### PR DESCRIPTION
**Pull request by rebeccaalpert**
Updated placement of inline editing icons from content to header across many resource detail pages.

Projects:
Screen Shot 2020-06-01 at 1 34 16 PM

Namespaces:
Screen Shot 2020-06-01 at 1 34 41 PM

Installed Operators:
Screen Shot 2020-06-01 at 1 35 10 PM

Example Workloads page:
Screen Shot 2020-06-01 at 1 31 30 PM

Example Workloads page with tolerations:
Screen Shot 2020-06-01 at 1 40 18 PM

Example Nodes page:
Screen Shot 2020-06-01 at 1 32 21 PM

Machine Sets:
Screen Shot 2020-06-01 at 1 32 59 PM

Cluster Settings:
Screen Shot 2020-06-01 at 1 33 21 PM

Custom Resource Definitions: 
Screen Shot 2020-06-01 at 1 33 44 PM

Example from Pipelines:
Screen Shot 2020-06-01 at 1 36 16 PM

Example from Serverless: 
Screen Shot 2020-06-01 at 1 35 47 PM

Example from User Management section:
Screen Shot 2020-06-01 at 1 38 20 PM

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1833087.

Heads up @openshift/team-ux-review.

### CODE REVIEW

**Comment by gdoyle1** [comment]
@rebeccaalpert I can't add myself as reviewer here, but these changes look great! Wondering if a bug was also created for adding the pencil to the rest of the fields that we listed in that design doc? One of them included the "Label" category

**Comment by rebeccaalpert** [comment]
@gdoyle1 I left the pencil out for Labels because we don't have that functionality baked into the details view right now (you have to use the actions menu). I figured maybe it was from an older version. Do you guys want the user to be able to modify the labels from there?

**Comment by gdoyle1** [comment]
> @gdoyle1 I left the pencil out for Labels because we don't have that functionality baked into the details view right now (you have to use the actions menu). I figured maybe it was from an older version. Do you guys want the user to be able to modify the labels from there?

Yes, we would like it to be there too! So you can access editing labels from both the actions menu and by clicking the pencil. I realized that it was written in the bug description, but not specifically in the design doc. I'll update the doc but here's the description from the bug:

"For all resource detail pages, move the pencil edit icon to the right of the field label rather than the field value. For example, the pencil would be moved to the right of "Annotations" and the number of Annotations underneath would remain. In addition, for Labels, the pencil should be added since users can edit those in context.

Currently we are inconsistent. For VM detail pages, we are doing this correctly today. (See screenshot attached) Everywhere else, we are including the pencil next to the field value. "

**Comment by rebeccaalpert** [comment]
Thanks, I'll add that on.

**Comment by rebeccaalpert** [comment]
@gdoyle1 - I added the functionality we discussed and updated the screenshots; let me know if you have feedback!

**Comment by gdoyle1** [comment]
@rebeccaalpert It looks good!! Do you mind adding a screenshot of hover + click just to confirm that the flow works as designed? Then it'll be all set!

**Comment by beanh66** [comment]
Looks great @rebeccaalpert! Thanks for all the screenshots, this one really spanned across a number of pages!

**Comment by rebeccaalpert** [comment]
@gdoyle1 - Here you go (top one in each case):

Hover:
Screen Shot 2020-06-02 at 10 07 55 AM

Click: 
Screen Shot 2020-06-02 at 10 08 06 AM

**Comment by gdoyle1** [comment]
@rebeccaalpert Perfect!!! This is good to go! Thanks so much!

**Comment by serenamarie125** [comment]
@rebeccaalpert what does clicking on the pencil next to the Default Pull Secret do?  The reason I'm asking is because we have an epic around creating an efficient and discoverable way to add a secret, and would like to see how this may help!  Thanks

Screen Shot 2020-06-02 at 10 56 06 AM

**Comment by rebeccaalpert** [comment]
@serenamarie125 - It triggers this modal:

Screen Shot 2020-06-02 at 11 04 37 AM

(Scrolled all the way down so you can see the remaining fields):
Screen Shot 2020-06-02 at 11 04 49 AM

**Comment by serenamarie125** [comment]
thanks for the details @rebeccaalpert!

btw, this design/implementation looks great!

**Comment by matthewcarleton** [comment]
This looks great Rebecca! I'm guessing for virtualization we'd need to update these on our side?
Also: A question about accessibility, I see the aria label which is awesome b/c right now screen readers just announce this as "button". I do wonder though if the labels should be more specific beyond "update". Has there been any discussion around this?

**Comment by rebeccaalpert** [comment]
@matthewcarleton - I didn't see any other instances in the console code; I'm not sure where the virtualization codebase lives. I'm assuming that needs to be updated separately. There hasn't been discussion of the aria-labels. @openshift/team-ux-review, do you have thoughts?

**Comment by itsptk** [comment]
@rebeccaalpert I also wanted to ask if this change would apply to OLM descriptors that appear on operators' custom resources' Details tabs as well, or if that would be a separate change? If separate I can open a different bug for it. Thank you!

**Comment by matthewcarleton** [comment]
> @matthewcarleton - I didn't see any other instances in the console code; I'm not sure where the virtualization codebase lives. I'm assuming that needs to be updated separately. 

Thanks, ya I guess that makes sense. I wasn't sure if this was a standard thing that got pulled in or just custom code for each use.

**Comment by rebeccaalpert** [comment]
Putting this under a WIP tag until I can fix @itsptk's page.

**Comment by matthewcarleton** [comment]
@rebeccaalpert I've been talking to @jelkosz about this a bit more. It would be great if this PR could cover the virtualization details page as well so we are in line with your changes. I believe it would require the operator to get access to the codebase. Is it possible for you to cover that here?
If you need any help figuring it out I'm sure we can help :)
I've been thinking a bit more about the aria-labels too - what if we add the label text after update? So for annotations the aria-label would be "update annotations"? We could change `update` to `edit` too - that might align a bit better with the action. WDYT?

**Comment by rebeccaalpert** [comment]
Screen Shot 2020-06-08 at 12 05 10 PM
Screen Shot 2020-06-08 at 12 05 15 PM

@matthewcarleton - Virtualization should be all set (icons were previously generated through CSS, so weren't coming up in search); working through updating all aria-labels.

**Comment by matthewcarleton** [comment]
awesome thanks @rebeccaalpert !

**Comment by rebeccaalpert** [comment]
Updated aria labels to reflect "Edit ${thing}" pattern and refactored code to use the kubevirt package's EditButton component so that no one has to go through and modify all those buttons individually in the future.

**Comment by rhamilto** [comment]
I find this change confusing.  The pencil beside the label suggests clicking the pencil is how you edit the label, not the value.  In other words, it obfuscates how to go about editing the value.  With the existing functionality, the blue hyperlink clearly indicates the item is clickable, and paired with the pencil icon suggests the behavior is different than a standard hyperlink.

**Comment by matthewcarleton** [comment]
> I find this change confusing. The pencil beside the label suggests clicking the pencil is how you edit the label, not the value. In other words, it obfuscates how to go about editing the value. With the existing functionality, the blue hyperlink clearly indicates the item is clickable, and paired with the pencil icon suggests the behavior is different than a standard hyperlink.

hey Robb - you make some good points. We had a lot of back and fourth in the design decision with this one. We landed here because it was the most flexible for areas that have more than one value under the label that can have an edit icon. 
For example boot order for a VM:
Screen Shot 2020-06-09 at 1 40 23 PM
Having the icon with just the first item feels odd b/c you aren't editing just that item you're editing them all at the same time in a single modal.
Alternatively if we put the icon near all the children of the list then it feels really strange b/c they all do the same thing. 

Screen Shot 2020-06-09 at 1 40 13 PM

I do agree that it could confuse users but wouldn't say it would confuse all users. It is also a learned pattern in the console. Once they click it once they understand what it does. We also don't allow labels to be edited (AFAIK) so there isn't any overlap with functionality there. 
Screen Shot 2020-06-09 at 1 43 03 PM

This also helps fix the issue where things like labels can't be edited in the details view but only through the actions dropdown.

This definitely qualifies as a candidate for user feedback so we aren't operating upon assumptions.
 
Hopefully I've helped and not confused this further :)

**Comment by rebeccaalpert** [comment]
Created a new Jira issue to track new concept addressing concerns about approach: https://issues.redhat.com/browse/CONSOLE-2298

Closing PR as Jon will be pursuing shared component as part of the new story as part of current work.

**Pull request closed without merging**
