### PR TITLE
Bug 1952209: Consistent formatting of dates and times

### PR DESCRIPTION
**Pull request by spadgett**
Manual 4.7.z backport of #8490. This PR does not include removing moment.js, only the time format changes.

Consistently format dates with Intl.DateTimeFormat. This will ensure that we honor the browser's locale setting even for languages we don't yet support. Always show the year for dates. Ultimately, we want to make the date and time format a user preference.

/assign @rhamilto 
/cc @kyoto

### CODE REVIEW

**Review by rhamilto — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
@rhamilto I needed to run `yarn i18n`. Do you mind tagging again?

**Review by rhamilto — APPROVED** [review]
/lgtm

**Comment by spadgett** [comment]
/hold
I'd like address regression #8815 before merging

**Comment by spadgett** [comment]
/hold cancel
Updated, @rhamilto PTAL

**Review by rhamilto — APPROVED** [review]
/lgtm

**Pull request merged**
