### PR TITLE
Remove dead code for in context binding and fix wrong import

### PR DESCRIPTION
**Pull request by rohitkrai03**
**Fixes**: 
- https://issues.redhat.com/browse/ODC-5529
- https://issues.redhat.com/browse/ODC-5530

**Analysis / Root cause**: Dead code for in context binding in import forms and wrong import in topology service binding file.

**Solution Description**: Remove dead code and fix import.

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Looks unused :+1: 

/lgtm

**Comment by invincibleJai** [comment]
/lgtm

Verified works as expected

**Pull request merged**
