### PR TITLE
CONSOLE-2774: Consolidate i18n namespaces k-m

### PR DESCRIPTION
**Pull request by zherman0**
Consolidate i18n namespaces k-m

### CODE REVIEW

**Comment by zherman0** [comment]
/assign @yapei @ahardin-rh @sferich888
for approvals

**Comment by zherman0** [comment]
/retest
failed to acquire lease

**Review by spadgett — APPROVED** [review]
/lgtm
/hold for approvals

**Comment by zherman0** [comment]
@yapei @ahardin-rh @sferich888 - Can you please approve?

**Comment by spadgett** [comment]
/label px-approved
We've received approval from Eric for this PR.

**Review by spadgett — APPROVED** [review]
/lgtm

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
