### PR TITLE
Fix for topology sub context menus, make topology side panel resizable

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**Fixes**: 
https://issues.redhat.com/browse/ODC-5649

**Addresses**
https://issues.redhat.com/browse/ODC-1881

**Analysis / Root cause**: 
Issue in PF React Core caused the sub-context menu to not show up correctly.
Updating PF React Core updates styling which breaks the topology side panel.

**Solution Description**: 
Update PF React Core to fix the sub-context menu issue
Update PF React Topology to update the topology side panel to be compatible with the styles
Update Topology to use the new Topology Drawer components which are resizable.
Track user resizing of the side panel to open at the last size the user chose.

**Screen shots / Gifs for design review**: 
TopologySidePanelResize

**Browser conformance**: 
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge

/kind bug
/kind feature

/cc @openshift/team-ux-review

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
Verified locally, works fine.
/lgtm

**Review by jerolimov — APPROVED** [review]
Works like a charm.

/approve

**Review by rohitkrai03 — APPROVED** [review]
/approve

**Comment by debsmita1** [comment]
@jeff-phillips-18 this needs rebase

**Pull request closed without merging**
