### PR TITLE
[release-4.8] Bug 2045051: Add subject name selector field to SinkBinding form

### PR DESCRIPTION
**Pull request by rottencandy**
Manual cherry pick of #10568 
Conflicts occurred due to changed import order.

### CODE REVIEW

**Review by jerolimov — APPROVED** [review]
Same code as in 4.9 and 4.10. Tested it on a local cluster and it works fine.

/approve
/lgtm
/label backport-risk-assessed

**Comment by jrichter1** [comment]
tested and verified
/label cherry-pick-approved

**Pull request merged**
