### PR TITLE
Change the behaviour of card help from click to hover

### PR DESCRIPTION
**Pull request by bipuladh**
This fix  changes the trigger of the help-card from click to hover(With click functionality still retained for touch screens; this issue still persists on touch screens). To avoid the issue seen in the picture below. On scroll the tool tip sticks to the viewport rather than scrolling with the parent component. This should suffice until patternfly fixes this issue.

bugpic

### CODE REVIEW

**Comment by bipuladh** [comment]
@rawagner @cloudbehl @afreen23

**Comment by spadgett** [comment]
I'd rather not change the click/hover behavior unless we think it's better. It seems like the problem is Patternfly appends the popover to body instead of to the trigger element? This only happens when you scroll the page with the popover open, correct?

If this is an upstream bug, we should work with Patternfly to fix it there.

**Comment by bipuladh** [comment]
@spadgett Yes it only happens when you scroll the page. And yes its an Patternfly issue. I thought this could work as an workaround until it gets fixed in the Patternfly repo.

**Comment by spadgett** [comment]
Our other popovers are click to trigger. IMO introducing an inconsistency here is a worse bug than the one we're fixing. This is a pretty minor problem. I'd rather see if we can get this fixed upstream and not change the click/hover behavior.

/hold

**Comment by cloudbehl** [comment]
@bipuladh The issue seems valid to me, can you open a patternfly issue and reference the Issue in this PR.

**Pull request closed without merging**
