### PR TITLE
Bug 1840585: Add loading box when helm readme is being fetched

### PR DESCRIPTION
**Pull request by rohitkrai03**
**Fixes**: https://issues.redhat.com/browse/ODC-3790

**Analysis / Root cause**: Sometimes it takes time to load readme content of helm charts in sidebar which gives user the impression that nothing is happening.

**Solution Description**: Adds a loading box in the sidebar while readme is being fetched for helm chart.

**Screen shots / Gifs for design review**: 
cc: @openshift/team-devconsole-ux @parvathyvr @beaumorley 

Peek 2020-05-27 14-52

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by andrewballantyne** [comment]
This is a small (but I think nice) win... however you will need Christian's approval @rohitkrai03 

/assign @christianvogt

**Comment by christianvogt** [comment]
I like the idea. I'm sure UX will have some suggestion on the text being used instead of `Loading Markdown`.

In your gif, the last item shows the loading indicator and then nothing shows up. I think this could be confusing. Although that's definitely an edge case because chances are if the chart had a README file present, it most likely will have content.

@beaumorley got any suggestion?
cc @openshift/team-devconsole-ux @serenamarie125

**Comment by christianvogt** [comment]
Thanks @andrewballantyne for pointing out that @parvathyvr already gave a lgtm.

In that case:
/approve

**Pull request merged**
