### PR TITLE
StorageClass name displayed as a list in pool list page popover and its keep expanding

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Issue: https://issues.redhat.com/browse/RHSTOR-2063

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Comment by GowthamShanmugam** [comment]
image

**Comment by GowthamShanmugam** [comment]
image

**Comment by bipuladh** [comment]
For some reasons the close button and the scroll bar looks a bit weird.

**Comment by bipuladh** [comment]
@yuvalgalanti wdyt?

**Comment by GowthamShanmugam** [comment]
Actually, we need a better design here popup is not the correct element to display storage class here. Really worried it will keep expanding.

**Pull request closed without merging**
