### PR TITLE
[release-4.10] Bug 2117351: fix helm readme bug

### PR DESCRIPTION
**Pull request by debsmita1**
Manual cherry pick of https://github.com/openshift/console/pull/11881

### CODE REVIEW

**Comment by invincibleJai** [comment]
@debsmita1 can you pls put gif of the scenario tested on bot?

**Comment by debsmita1** [comment]
Screenshot 2022-08-19 at 10 35 18 AM
Screenshot 2022-08-19 at 10 35 41 AM

**Pull request merged**
