### PR TITLE
Bump patternfly-react-extensions@2.5.1

### PR DESCRIPTION
**Pull request by spadgett**
/cc @jeff-phillips-18 @dtaylor113

### CODE REVIEW

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by jeff-phillips-18** [comment]
This does not provide the PatternFly styling for the tooltip that is used across many applications. The overlay trigger and popup was used to gain this styling.  The `title` tooltip does truncate after a number of characters where as the `popup` gets large and may end up off the screen for very large descriptions depending on the tile's location. The `title` tooltip will also auto dismiss before you get a chance to finish reading the description if it is very long.

**Comment by spadgett** [comment]
> A delay is being added to the tile's default tooltip, see patternfly/patternfly-react#640

This only address one of the issues. Other things:

* Are we worried about performance with many items due to all the tooltip event listeners? (I suspect marketplace will have a lot.)
* The user experience is poor on touch devices. You have to tap the tile twice to activate it since the hover will take the first tap. (Verified this on my phone.)
* The positioning of the tooltip is often offscreen if the tile is at the top of the page.
* The tooltip popover seems too narrow for a large description.
* Long text like URLs in the tooltip gets cut off.

Even if we solve all the problems, I still personally think the tooltip gets in the way more than it helps.

**Comment by serenamarie125** [comment]
Hey @spadgett can you add a screenshot of what your fix looks like?  I'd like to see how you're handling the issues you mention above

We definitely want the experience to be the same in the embedded marketplace and the catalog.  I'd rather see the desired behavior in PF React if possible.  

Re: performance, do we know what the hit is?

**Comment by spadgett** [comment]
@serenamarie125 Right now my PR just disabled the tooltip

**Comment by serenamarie125** [comment]
@spadgett I didn't see your previous comment re: removing the tooltip altogether.  I'm fine with that for now, given that you can see the info in the  sidebar without changing context.  We can test this behavior as well, to see if people feel this is an issue.

cc @tlwu2013

**Comment by spadgett** [comment]
> Re: performance, do we know what the hit is?

No, I haven't profiled it or confirmed it's really a problem. But I think it's worth doing.

It's no issues with a few dozen items. Adding event listeners to thousands of tiles on a page could have an impact, though. But again I haven't tested it.

**Comment by jeff-phillips-18** [comment]
I agree that the tooltip isn't all that helpful here. I'll update https://github.com/patternfly/patternfly-react/pull/640 to not show a tooltip by default.

**Comment by spadgett** [comment]
I'll change my PR to bump patternfly react

**Comment by spadgett** [comment]
OK I removed the custom truncate function and just bumped to the latest patternfly-react-extensions

@dtaylor113 @jeff-phillips-18 PTAL

/hold cancel

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
