### PR TITLE
[release-4.8] Bug 1985193: Add create resource extension

### PR DESCRIPTION
**Pull request by rawagner**
cherry-pick of https://github.com/openshift/console/pull/9395

### CODE REVIEW

**Comment by spadgett** [comment]
/hold

We are investigating a possible regression in the create operand form.

**Comment by ecordell** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped*

* Score: *0.00*
* Reason: *skipping because "do-not-merge/hold" label found*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by ecordell** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped*

* Score: *0.00*
* Reason: *skipping because "do-not-merge/hold" label found*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by ecordell** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped*

* Score: *0.00*
* Reason: *skipping because "do-not-merge/hold" label found*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by ecordell** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped*

* Score: *0.00*
* Reason: *skipping because "do-not-merge/hold" label found*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by ecordell** [comment]
[patch-manager] :hourglass: This pull request was not picked by the patch manager for the current z-stream window and have to wait for the next window.

*skipped*

* Score: *0.00*
* Reason: *skipping because "do-not-merge/hold" label found*

**NOTE**: This message was automatically generated, if you have questions please ask on #forum-release

**Comment by yanpzhan** [comment]
Tested against the pr, component from dynamic plugin could be rendered instead of the static plugin. Fix for bug 1985193 works.

**Comment by christianvogt** [comment]
@spadgett could you provide an update regarding your hold.

**Comment by rawagner** [comment]
The bug is fixed in master https://github.com/openshift/console/pull/9711
once this PR is merged, I will backport 9711 or I can include the commit into this PR

**Comment by spadgett** [comment]
/hold cancel

We can backport that separately. Thanks @rawagner

**Pull request merged**
