### PR TITLE
Bug 1820192: ask before deleting referenced VM resources

### PR DESCRIPTION
**Pull request by suomiy**
```
- split delete device modal into delete disk and nic modal
- ask if referenced volume resource should be deleted
  - on disk removal
  - remove owner reference if delete checkbox is off
- move logic from delete disk modal into a hook
- add DeleteVMLikeEntityModal
- allow freeing up volume resources on VM/Template delete
- add option for cleaning up vm import
- add hooks for vmlike entity and vmimport
```

### CODE REVIEW

**Comment by suomiy** [comment]
This looks at resources which are referenced through volumes (most notably DataVolume and PVC, but also Secret, Config Map etc.). And investigates if the VM owns the resource, and gives user an option of preserving that resources and separating it from VM lifecycle.

#### Option of keeping that resource when VM owns the  resource (when checkbox deselected)

DV:

a3

Secret

a1


#### No option when VM doesn't own the resource

a2


#### Same behaviour when deleting the VM, but has only possibility of selecting the resources in bulk.

#### when VM owns 2 disks (one DV and one Secret)

a5

#### No option when VM doesn't own any resource

a6

**Comment by suomiy** [comment]
Please review @yaacov @pcbailey @glekner @irosenzw

@jelkosz @matthewcarleton 

The main problem is that we do not offer such option for cdroms and also for environment tab (less priority). 
So the user can't choose that it wants to preserve cdrom resources (for example downloaded URL DV and PVC) when deleting it.

How could we present that with our cdrom UI?

Would it make sense to align it with the disk flow as it allows more features (also bus editing)?

We could use disk filtering which @yaacov added in https://github.com/openshift/console/pull/5453 and send them to disks tab filtered for CDs only, when the user clicks on CDs editing button in VM details tab

**Comment by matthewcarleton** [comment]
Hey @suomiy this is awesome! I really think these type of effort is exactly what we need to ensure the user is more informed on their actions, nice work! I have some questions/ comments :)

> This looks at resources which are referenced through volumes (most notably DataVolume and PVC, but also Secret, Config Map etc.). And investigates if the VM owns the resource, and gives user an option of preserving that resources and separating it from VM lifecycle.
> 
> #### Option of keeping that resource when VM owns the resource (when checkbox deselected)
> DV:
> 
> a3

Can we show just the disk name here and not the name of the vm (makes it easier to read and we can assume they already know that it's for this VM b/c they took the action) I think we need to come up with an overall strategy on how we are presenting data volumes and PVCs to the user. When they create a disk they aren't informed of the backing DV/PVC so it could confuse them here. I like adding DV/PVC exposure but I don't think we should do it at the end like this but rather the beginning when they create the Disk.
> 
> Secret
> 
> a1

What about adding some clarity  : This will also delete the example-secret connected to this VM.
> 
> #### No option when VM doesn't own the resource
> a2

Can we add some assurance here for the user where we state that it won't be deleted entirely but just from the VM?
> 
> #### Same behaviour when deleting the VM, but has only possibility of selecting the resources in bulk.
> #### when VM owns 2 disks (one DV and one Secret)
> a5
I think we could add a bit more clarity here too : Are you sure you want to delete this VM and the following resources:
Disk-1
Disk-2
[] delete vm and listed resources

> 
> #### No option when VM doesn't own any resource
> a6
Clarity here could be nice too where the user is aware that the VM is not deleting the resources and they will still be intact.

**Comment by suomiy** [comment]
> > #### Option of keeping that resource when VM owns the resource (when checkbox deselected)
> Can we show just the disk name here and not the name of the vm (makes it easier to read and we can assume they already know that it's for this VM b/c they took the action) I think we need to come up with an overall strategy on how we are presenting data volumes and PVCs to the user. When they create a disk they aren't informed of the backing DV/PVC so it could confuse them here. I like adding DV/PVC exposure but I don't think we should do it at the end like this but rather the beginning when they create the Disk.

Nice, added. I like the idea of making this clear to the user at the beginning, but I still think it has a value of emphasizing this when deleting too.

d2


> > Secret
> What about adding some clarity : This will also delete the example-secret connected to this VM.

I think this might indicate a wrong action if the checkbox is deselected.

> > #### No option when VM doesn't own the resource
> Can we add some assurance here for the user where we state that it won't be deleted entirely but just from the VM?

> Clarity here could be nice too where the user is aware that the VM is not deleting the resources and they will still be intact.

It is not that straightforward, because we would have to mention that some disks reference different resource, but some might not. So the VM might reference something, or in case of container image nothing. 

> > #### when VM owns 2 disks (one DV and one Secret)
>  I think we could add a bit more clarity here too : Are you sure you want to delete this VM and the following resources:
>  Disk-1
>  Disk-2
>  [] delete vm and listed resources

The VM will be always deleted and is not dependent on the checkbox. We would like to add a list of disks and possibility to pick them in the future.

Currently there is also stale VirtualMachineImport resource marked for deletion. So we have actually 2 checkboxes (forgot to show it).

i1

**Comment by matthewcarleton** [comment]
I might be thinking of these checkboxes wrong. 
Is the idea that we want to ensure the user knows what they are doing so we require a checkbox so they don't do something accidentally OR are we providing additional options WHEN they delete the VM. Maybe it's a mix of both?

**Comment by suomiy** [comment]
we are providing additional options (what to delete/preserve) when they delete the VM/disk

**Comment by yaacov** [comment]
@matthewcarleton @suomiy hi,

This looks like a feature, we may want to consider this after 4.5, added notes about this bug in the BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1820192#c8

Un-targeting the BZ from 4.5 (see comment in BZ).
/bugzilla refresh

**Comment by yaacov** [comment]
@mattf @suomiy we may want to add a hint educating users what are data-volumes, why we do not delete them by default, and what are the risks when deleting them with the vm.

**Comment by yaacov** [comment]
Re-targeting the BZ to 4.5 (see comment in BZ).
/bugzilla refresh

**Comment by matthewcarleton** [comment]
@suomiy ah I think what's confusing me here is the pattern that we see in other places in OCP where the user is required to check the checkbox to ensure they are aware of the destructive action they are about to take.
I think we could help clarify that but having addition text that precedes the checkboxes like: 

```The following checked items will also be removed (uncheck if you'd prefer to keep them)```

We could also have something like 
``` The following items can not be deleted and will persist after this virtual machine is deleted```
and then list out what will stay.
WDYT?

**Comment by suomiy** [comment]
done,

remove 3 owned resources



remove 1 owned resource



remove 0 owned resources

**Comment by matthewcarleton** [comment]
> done,
> 
> remove 3 owned resources
> 
> 
> 
> remove 1 owned resource
> 
> 
> 
> remove 0 owned resources
> 
> 

So when they uncheck items do we change the text above? and if they uncheck them all we remove the text? Or is this just in cases where the modal is shown and only some (or none) of the check boxes are checked? 
It would be nice if we just had a singe string of text for the checkboxes regardless of them being checked or not:
```Select the resources you'd like to delete with the virtual machine.```
Then the options are not checked by default. WDYT? We could then remove "delete" from the checkbox label.

**Comment by suomiy** [comment]
> So when they uncheck items do we change the text above? and if they uncheck them all we remove the text? Or is this just in cases where the modal is shown and only some (or none) of the check boxes are checked?

it is checked by default and we change the text if they get unchecked

> t would be nice if we just had a singe string of text for the checkboxes regardless of them being checked or not:
Select the resources you'd like to delete with the virtual machine.
Then the options are not checked by default. WDYT? We could then remove "delete" from the checkbox label.

I think it is preferable to have them checked by default (especially VMImport resource - as they probably will not know what it is for)

For example, oVirt has the same behaviour - has deletion of disks checked by default.

**Comment by matthewcarleton** [comment]
> > So when they uncheck items do we change the text above? and if they uncheck them all we remove the text? Or is this just in cases where the modal is shown and only some (or none) of the check boxes are checked?
> 
> it is checked by default and we change the text if they get unchecked
> 
> > t would be nice if we just had a singe string of text for the checkboxes regardless of them being checked or not:
> > Select the resources you'd like to delete with the virtual machine.
> > Then the options are not checked by default. WDYT? We could then remove "delete" from the checkbox label.
> 
> I think it is preferable to have them checked by default (especially VMImport resource - as they probably will not know what it is for)

Yes I agree, checked by default is the best. I Would say we don't need to change the text string though it could be a bit weird to see it shifting around. I think this string could work:

```The following resources will be deleted along with this virtual machine. Unchecked items will not be deleted.```

WDYT?
> 
> For example, oVirt has the same behaviour - has deletion of disks checked by default.

**Comment by suomiy** [comment]
ok, done

aa

**Pull request merged**
