### PR TITLE
feat(dev-catalog): Create Config to launch in Form

### PR DESCRIPTION
**Pull request by abhinandan13jan**
Addresses https://jira.coreos.com/browse/ODC-2456

dev-cat

### CODE REVIEW

**Comment by spadgett** [comment]
/hold

I'm not sure we're ready to switch yet since you can't edit all fields in the form. cc @alimobrem

**Comment by spadgett** [comment]
cc @tlwu2013

Adding Ali and Tony for input

**Comment by benjaminapetersen** [comment]
+1 thanks, I missed that.

**Comment by andrewballantyne** [comment]
This has been agreed by @sspeiche that it has been bumped out of 4.4.

/approve cancel

**Comment by abhinandan13jan** [comment]
closing the PR... can be used as a reference for later implementation if needed.

**Pull request closed without merging**
