### PR TITLE
[release-4.12] OCPBUGS-13357: add multipath device type to LocalVolumeSet

### PR DESCRIPTION
**Pull request by RomanBednar**
This is a cherry-pick of https://github.com/openshift/console/pull/12723 and https://github.com/openshift/console/pull/13022

### CODE REVIEW

**Comment by Phaow** [comment]
Pre verify passed with the prebuild cluster by clusterbot

```console
$ oc version
Client Version: 4.12.0-ec.3
Kustomize Version: v5.0.1
Server Version: 4.12.0-0.test-2023-11-07-073945-ci-ln-4sbi2b2-latest
Kubernetes Version: v1.25.14+bcb9a60
1. Install OCP cluster and local storage operator;
2. Configure multipath on 1 worker node;
3. Create localvolumediscovery CR and check the localvolumediscoveryResults contains the mpath type volumes;
$ oc get localvolumediscoveryResults -oyaml|grep -i 'mpath'
    - deviceID: /dev/disk/by-id/dm-name-mpatha
      type: mpath
4. Create localvolumeset with mpath type and check the provisioned pvs contains the mpath volumes.(Check both with CLI and Web console)
$ oc get pv/local-pv-2bbeeadc -oyaml|yq .metadata.annotations
pv.kubernetes.io/provisioned-by: local-volume-provisioner-ci-ln-4sbi2b2-72292-dncnt-worker-c-rtlht
storage.openshift.com/device-id: dm-name-mpatha
storage.openshift.com/device-name: dm-0
```

**Comment by Phaow** [comment]
@yanpzhan @XiyunZhao Could you please take a look and add the cherry-pick-approved when you get a chance? I pre-merge test looks good from storage side. Thanks!

**Comment by RomanBednar** [comment]
/unhold

https://github.com/openshift/local-storage-operator/pull/408 is now merged

**Review by jhadvig — APPROVED** [review]
/approve
/label backport-risk-assessed

**Comment by RomanBednar** [comment]
> @yanpzhan @XiyunZhao Could you please take a look and add the cherry-pick-approved when you get a chance? I pre-merge test looks good from storage side. Thanks!

@yanpzhan @XiyunZhao ^^^

**Comment by Phaow** [comment]
@RomanBednar Let me ping them in slack, maybe they missed the e-mails notifications.

**Pull request merged**
