### PR TITLE
Bump patternfly* to latest versions to pick up bug fixes

### PR DESCRIPTION
**Pull request by rhamilto**
Note:  because PatternFly is unstable, I'm locking the version numbers down in this PR.

Fixes https://jira.coreos.com/browse/CONSOLE-1236

And adds now-available separator between `Config Maps`  and `Cron Jobs` in the `Workloads` nav section.

localhost_9000_catalog_ns_openshift-monitoring
localhost_9000_catalog_ns_openshift-monitoring 1

### CODE REVIEW

**Comment by priley86** [comment]
thanks for starting this branch @rhamilto ! I will try to start digging on some of the issues referenced in the PR and ones listed above. Please continue adding here or in the doc and we will try to resolve a.s.a.p.

**Comment by priley86** [comment]
We tested a fix for the nav expand today:
https://github.com/patternfly/patternfly-react/pull/1479#issuecomment-468808219

We should be able to release and update you on Monday.

As far as the modal goes, I recommend just overriding the background-image CSS for now:
```
@media only screen and (min-width: 576px){
  .pf-c-about-modal-box__hero {
    background-image: url('../imgs/pfbg_992.jpg') !important;
  }
}
```
We would normally override `--pf-c-about-modal-box__hero--sm--BackgroundImage`, but that doesn't seem to be playing nice with Webpack file-loader here. I will continue investigating for the long term, but I think this is a reasonable option for now.

Will continue investigating other issues as we have time next week @rhamilto .

**Comment by boaz0** [comment]
//cc @rhamilto pr https://github.com/patternfly/patternfly-react/pull/1489 fixes the inputgroup typescript problem.

thanks.

**Comment by priley86** [comment]
updated [1490](https://github.com/patternfly/patternfly-react/pull/1490) just now. It should fix the nav issues you were experiencing. The edge case we were seeing was due to the `NavSection` state now being in sync w/ PF's `NavExpandable` state. To resolve this, I've added a hook back so you can manage this state the same way you did before (an optional callback). PF will then respect the props coming down. "Lifting state" is typically good from a React standpoint. You'll need to add these changes after we release the fix (ignoring the console.log's):
https://github.com/priley86/web-ui/commit/4816b4de384c7d18eeea89a45a6a311d4af764aa

This should resolve it.

**Comment by rhamilto** [comment]
> This should resolve it.

It does with one exception:  if the active nav section is collapsed by the user and the next navigation is within the same section, the active nav section is not re-expanded.  What is the intended behavior @openshift/team-ux-review?   

c5gtvtwrni

**Comment by priley86** [comment]
@rhamilto - yes, this is a facet of onToggle and onExpand currently. In order to support that additional usecase, we'd have to implement onToggle from the `Nav` side too (in Console). This can be done, but is optional by the consumer. This seems to be quite the edge case but good to note it...

**Comment by cshinn** [comment]
@rhamilto I talked it over with Matt C and we think that in this case the group should stay collapsed so that we don't override the users decision to collapse it. In other cases, the relevant category should still expand when navigating to a new section

**Comment by rhamilto** [comment]
tsconfig.json changes removed, integration tests fixed.  @spadgett PTAL.

**Pull request merged**
