### PR TITLE
OCPBUGS-2525: migrate CRD extensions tests to Cypress to mitigate flakes

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by rhamilto** [comment]
> Changes look good but, could we add ConsoleQuickstart, ConsoleYAMLSample and ConsolePlugin CRDs as well? so we them all

We certainly can, but perhaps that should be a tech debt story since the bug is specific to the tests in https://github.com/openshift/console/pull/12331/files#diff-a322b9d3357bd7a990ecfb84dccfed026411d94bc92ef90e727b87fc2c59564f?

**Comment by rhamilto** [comment]
> > Changes look good but, could we add ConsoleQuickstart, ConsoleYAMLSample and ConsolePlugin CRDs as well? so we them all
> 
> We certainly can, but perhaps that should be a tech debt story since the bug is specific to the tests in https://github.com/openshift/console/pull/12331/files#diff-a322b9d3357bd7a990ecfb84dccfed026411d94bc92ef90e727b87fc2c59564f?

I am not seeing that we have existing integration tests for ConsoleQuickstart, ConsoleYAMLSample and ConsolePlugin CRDs...  Am I missing something?

**Comment by jhadvig** [comment]
Makes sense @rhamilto will create a techdebt story for the remaining ones 👍

**Pull request merged**
