### PR TITLE
[release-4.10] OCPBUGS-18014: When removing the project owner from the project in GUI, instead of that user, the group (the default group added as project admin through the project template) will be removed.

### PR DESCRIPTION
**Pull request by lokanandaprabhu**
This is manual cherry-pick for PR - https://github.com/openshift/console/pull/13071

### CODE REVIEW

**Comment by lokanandaprabhu** [comment]
Tested using cluster bot. Working fine.


https://github.com/openshift/console/assets/102503482/1a00bcf0-02b5-4dff-a824-273a713c4c75

**Comment by Lucifergene** [comment]
Verified 
/lgtm

**Review by jerolimov — APPROVED** [review]
Testes this backport on a cluster bot instance and it works as expected:

https://github.com/openshift/console/assets/139310/845ac96b-6815-4324-9f26-34c366c4d690

/lgtm
/approve

**Pull request merged**
