### PR TITLE
Increased height of activity card in overview dashboard

### PR DESCRIPTION
**Pull request by afreen23**
**Before:**
Screenshot from 2020-01-06 20-01-40

**After:**
Screenshot from 2020-01-06 18-55-59
Screenshot from 2020-01-06 18-56-08

### CODE REVIEW

**Comment by afreen23** [comment]
The VM and events card are  using default activity card length.
Would be better if we set the height on them and change the default for activity card here
https://github.com/openshift/console/blob/6d1dcffe07b1108006bd086e5c86190984936fe4/frontend/public/components/dashboard/project-dashboard/activity-card.scss#L1-L3

Thoughts ??

**Comment by rawagner** [comment]
I think the best would be to have Activity card as long as the middle section of Dashboards but I couldnt find a way to do so - any idea @andybraren  @matthewcarleton  ?

**Comment by matthewcarleton** [comment]
> I think the best would be to have Activity card as long as the middle section of Dashboards but I couldnt find a way to do so - any idea @andybraren @matthewcarleton ?

let me take a look and see. I feel like this is doable :)

**Comment by matthewcarleton** [comment]
@rawagner so far I can only see a way to make the card itself the same height, but the content needs a fixed height in order to scroll.

**Comment by andybraren** [comment]
I think increasing the height manually like this is okay for now, but I agree, it would be nice if we could rearchitect the HTML/CSS so that the height of the Activity card just automatically lines up with the bottom-most part of the left or center columns. Hopefully that can be a future PR.

**Comment by rawagner** [comment]
/hold
e2e tests are failing

**Pull request merged**
