### PR TITLE
Fix to warn user when creating an application grouping that exists

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**Fixes**: 
https://issues.redhat.com/browse/ODC-1310
https://issues.redhat.com/browse/ODC-3206

**Solution Description**: 
On text change, determine if the application grouping already exists. If it exists update the input field to show a warning message but allow the user to continue.

**Screen shots / Gifs for design review**: 
image

image

**Browser conformance**: 
- [x] Chrome
- [x] Firefox
- [x] Safari
- [x] Edge

### CODE REVIEW

**Comment by jerolimov** [comment]
@jeff-phillips-18 Some i18n keys are missed in the `devconsole.json`

Could verify the warning and UI locally, works and looks like expected. :+1:

**Review by jerolimov — CHANGES_REQUESTED** [review]
@jeff-phillips-18 Some i18n keys are missed in the `devconsole.json`

Could verify the warning and UI locally, works and looks like expected. :+1:

**Comment by jeff-phillips-18** [comment]
@jerolimov Don't think I missed any keys for things I modified. However, I did not update the config files to actually use the devconsole.json file that I added here. I can add those if need be (otherwise they will get used once one of the other PRs get in)

**Comment by jeff-phillips-18** [comment]
@jerolimov I've added the config file changes

**Comment by jeff-phillips-18** [comment]
@jerolimov I've added the missing keys

**Review by jerolimov — APPROVED** [review]
:+1: 
/lgtm

**Comment by rohitkrai03** [comment]
@jeff-phillips-18 You have conflicts in the PR.

**Comment by jeff-phillips-18** [comment]
@rohitkrai03 Rebased.

**Pull request merged**
