### PR TITLE
Update pf packages to pf-2022-10

### PR DESCRIPTION
**Pull request by jcaianirh**

### CODE REVIEW

**Comment by jcaianirh** [comment]
QE Approver:
/assign @yapei

Docs Approver:
/assign @opayne1

PX Approver:
/assign @RickJWagner

Console Approver:
/assign @rhamilto 

LGTM Approver:
/assign @sg00dwin

**Review by rhamilto — APPROVED** [review]
/lgtm

**Comment by l1xiangyi** [comment]
/label qe-approved
1. Checked console page, no UI anamoly is spotted. Also checked dev tools for pf components and found no issue. 
2. Dynamic plugin page could load successfully as well.

**Pull request merged**
