### PR TITLE
Fix ClusterServiceClasses not showing up in Developer Catalog

### PR DESCRIPTION
**Pull request by spadgett**
/cc @alecmerdler @dtaylor113 @rhamilto 

@dtaylor113 Can you investigate how CI was passing with this bug? We should update our service catalog e2e tests as needed to catch this.

### CODE REVIEW

**Comment by spadgett** [comment]
@dtaylor113 Thanks, appreciate it.

Looks like we only provision services through Catalog -> Broker Management. We should add a provision test through Catalog -> Developer Catalog, which is the more common way. (Probably the tests were written before we finished Developer Catalog.)

**Comment by spadgett** [comment]
It looks like that test only checks that source-to-image items are filtered out. It doesn't check for the presence of service classes.

**Comment by dtaylor113** [comment]
Hmm...looks like we're not running the dev catalog (frontend/integration-tests/tests/catalog.scenario.ts) or the Operator Hub (frontend/integration-tests/tests/operator-hub/operator-hub.scenario.ts) e2e tests during Jenkins CI. https://github.com/openshift/console/blob/master/jenkins.sh#L103
@spadgett , @jeff-phillips-18

**Comment by spadgett** [comment]
We should look at adding Operator Hub tests now that we're moving to prow.

I think missing catalog.scenario.ts was just an oversight. It's confusing that we have two catalog.scenario.ts files, which might have been why :( Can we rename that to developer-catalog.scenario.ts?

cc @jcaianirh

**Comment by dtaylor113** [comment]
> Can we rename that to developer-catalog.scenario.ts?

Sure, will do.  Also updating the dev-catalog.scenario to test for a specific service-class to catch when no service classes are loaded.

**Comment by spadgett** [comment]
Thanks, sounds good.

**Pull request merged**
