### PR TITLE
add close [x] button in the pipeline task sidebar

### PR DESCRIPTION
**Pull request by debsmita1**
**Fixes:**
https://issues.redhat.com/browse/ODC-5519

**Solution Description:**
- added `x` button on the task sidebar

**GIF:**
x button

**Browser conformance:**
- [x] Chrome
- [x] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by andrewballantyne** [comment]
@bgliwa01 FYI.

**Comment by jerolimov** [comment]
> @bgliwa01 FYI.

Brigid means your :+1: lgtm or that you will take a look? :)

**Review by bgliwa01 — APPROVED** [review]
lgtm!

**Review by andrewballantyne — APPROVED** [review]

**Comment by karthikjeeyar** [comment]
Verified, works fine. Thanks @debsmita1 
/lgtm

**Pull request merged**
