### PR TITLE
[WIP] Change search to handle multiple resources

### PR DESCRIPTION
**Pull request by zherman0**
Change search page to allow for multiple resources to be selected at one time and searched using query.
Functionality this is complete, but visually we might want to make more tweaks.
Version 2: (Using PF4 Select with multi and typeahead)
There are still several visual issues and there is a difference between PF 3.112 (consle version) and PF 3.124 (current).
Images with 3.112
multiselect-12
multiselect-11
multiselect-10
Filter Removed:
multselect-no-filter

Images with PF 3.124
multiselect-1
multiselect-2
multiselect-3

Version1: (non PF dropdown)
I tried several ways to unselect resources but decided on a checkbox for UX.  I don't love the appearance so I am open to comments.  I did try simply highlighting the selected row in the dropdown but was not sure that it would be obvious to users they needed to click on it again to unselect the item.  I also added a close button on each resource but the title area of the dropdown is controlled by the generic Dropdown component and the close button was not clickable since it invoked the dropdown.  I should have taken more pics along the way but I did not.
Here are the current images:
multisearch-1
multisearch-2

### CODE REVIEW

**Comment by zherman0** [comment]
@spadgett - first version.  Please review when you have some time.

**Comment by spadgett** [comment]
I wonder if we should just use Patternfly `Select` with `SelectVariant.typeaheadMulti`.

https://www.patternfly.org/v4/documentation/react/components/select#multiple

If we use our own, I would just show a count for the number selected like the Patternfly widget.

PatternFly 4 2019-12-09 14-02-09

**Comment by spadgett** [comment]
We might skip preselecting Service when we make this change since it's extra clicks to manually deselect it when you want something else.

**Comment by spadgett** [comment]
We should try to have one text filter for all types instead of repeating it.

**Comment by sg00dwin** [comment]
Screen Shot 2019-12-16 at 14 54 28
Screen Shot 2019-12-16 at 15 00 54
 ---

- Tab closes the dropdown
- Arrow rotates though select options but highlighting doesn't work
- Left side Resource name is cut off 

Search-keyboard-navigation1

**Comment by benjaminapetersen** [comment]
/hold
As we look at the issues to address.  @zherman0 was going to open a second PR with his initial simplified impl as a fallback.

**Comment by zherman0** [comment]
https://github.com/patternfly/patternfly-react/pull/3457 has been created to tweak how this PF component works which should make this more usable. @spadgett @benjaminapetersen

**Comment by zherman0** [comment]
Closing in favor of solution https://github.com/openshift/console/pull/3875

**Pull request closed without merging**
