### PR TITLE
OCPBUGS-44657: Add IBM Block Storage CSI driver support for RWX

### PR DESCRIPTION
**Pull request by kasserater**
the upcoming IBM Block Storage CSI driver support release will add support for RWX
adding now so that we can start Beta testing with customers

### CODE REVIEW

**Comment by kasserater** [comment]
@kyoto can you be so kind and review this change? we have multiple customers wanting to Beta test our new IBM Block Storage CSI driver with RWX support, specifically with regards to VM virtualization and live-migration. This will have a big impact on RH and IBM sales.

**Review by csiblock — APPROVED** [review]

**Comment by csiblock** [comment]
@gnufied @jhadvig can you please assist with the review of this PR?

**Comment by csiblock** [comment]
/assign @vojtechszocs 

all - please note that we have passed our Beta phase and we are planning on releasing the upcoming IBM CSI 1.12.0 release in the next several weeks. We would really appreciate the review and approval here, so that upcoming OpenShift releases will allow customers set RWX access modes

**Comment by logonoff** [comment]
> /assign @vojtechszocs
> 
> all - please note that we have passed our Beta phase and we are planning on releasing the upcoming IBM CSI 1.12.0 release in the next several weeks. We would really appreciate the review and approval here, so that upcoming OpenShift releases will allow customers set RWX access modes

Could you open a [CONSOLE jira ticket](https://issues.redhat.com/browse/CONSOLE), since PRs can't be merged without `jira/valid-reference`

**Comment by kasserater** [comment]
@logonoff I lack sufficient permissions to create a CONSOLE Jira ticket (i can find the project in the projects directory, but cannot select it for ticket creation).
@csiblock cannot even find the CONSOLE Jira project in the projects directory
how can we gain access to the project as well as permissions to create tickets?
i would like to add those permissions to the rest of my development team as well
* @eranrotker
* @shlomitn
* @uriziv1
* @shirlyfa
* @chengoldi
* @eyalbeIL
* @ilanoxen
* @kariyb
* @lechapitre

**Comment by logonoff** [comment]
/retitle CONSOLE-4356: Add IBM Block Storage CSI driver support for RWX

**Comment by kasserater** [comment]
thank you @logonoff for opening the Jira ticket for me and linking it to this PR
our upcoming CSI release will support OCP 4.14 through 4.17, so that should be set as the target fix version in Jira (if you Jira project scheme allows for multiple fix versions)

**Comment by logonoff** [comment]
/retitle OCPBUGS-44657: Add IBM Block Storage CSI driver support for RWX

**Comment by logonoff** [comment]
> thank you @logonoff for opening the Jira ticket for me and linking it to this PR our upcoming CSI release will support OCP 4.14 through 4.17, so that should be set as the target fix version in Jira (if you Jira project scheme allows for multiple fix versions)
> 
> what are the next required steps to complete this PR?

Someone from the console team will look at the PR and may provide comments. Until then no further action is required

**Comment by yapei** [comment]
- Create a demo storageclass whose provisioner is `provisioner: block.csi.ibm.com`
- Goes to PVC creation page, check `Access mode` list, we can see RWO(ReadWriteOnce) and RWX(ReadWriteMany)
Screenshot 2024-11-19 at 2 07 34 PM

**Comment by kasserater** [comment]
@cyril-ui-developer @logonoff  as this was merged into the **master** branch, i.e. for OCP 4.18, how can we make sure it is also merged into the branches for OCP 4.14 through 4.17?

**Comment by kasserater** [comment]
@cyril-ui-developer can you please continue with the cherry picks to 4.16, 4.15 and 4.14?

**Pull request merged**
