### PR TITLE
[release-4.15]OCPBUGS-31105: Update to pf5.2 to fix quick starts

### PR DESCRIPTION
**Pull request by jcaianirh**
Manual back port of: https://github.com/openshift/console/pull/13653

### CODE REVIEW

**Review by jhadvig — COMMENTED** [review]
/approve
/label backport-risk-assessed

**Comment by rhamilto** [comment]
/hold

There is a bug impacting `yarn dev` that needs to be resolved.

**Comment by rhamilto** [comment]
@jcaianirh, please run `npx yarn-deduplicate --scopes @patternfly` against this PR and commit the resulting changes to `frontend/yarn.lock`.

**Review by jerolimov — APPROVED** [review]
Verified this PR on a cluster-bot instance.

https://github.com/openshift/console/assets/139310/1d61dc91-fed2-467d-ba8c-c30019dcb486

/cc @sanketpathak

**Pull request merged**
