### PR TITLE
Bug 1973565: Evaluate dynamic route pages before static ones

### PR DESCRIPTION
**Pull request by rawagner**

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/approve
/lgtm

**Comment by spadgett** [comment]
/hold

Can we hold this for now and discuss next week? We should be careful about letting dynamic plugin replace core console behavior

**Comment by rawagner** [comment]
Sure, i added it to agenta for next week

**Comment by spadgett** [comment]
Closing in favor of #9395

**Pull request closed without merging**
