### PR TITLE
update helm catalog description

### PR DESCRIPTION
**Pull request by debsmita1**
**JIRA story:**
https://issues.redhat.com/browse/ODC-6518

**Solution description:**
- removed the link to the Quick start for adding helm chart repo in a namespace
- added a link that will now take the user to the form for adding helm chart repo in the namespace
- the link will be shown to users having the privilege to create project helm chart repo CR

**GIF:**
Logged in as a kubeadmin 
helmcatalog-decs
 
 Logged in as a regular user with no access to create PHCR CR
Screenshot from 2022-05-27 00-12-13

### CODE REVIEW

**Comment by serenamarie125** [comment]
This looks great @debsmita1 - what happens in the case of a regular developer role?  Is there a different comment which doesn't include the final sentence?

**Comment by debsmita1** [comment]
> This looks great @debsmita1 - what happens in the case of a regular developer role? Is there a different comment which doesn't include the final sentence?

@serenamarie125 A regular developer will not have access to create a project helm chart repository CR in a namespace until the kubeadmin provides the user with that privilege. The steps are mentioned here https://docs.google.com/presentation/d/1kTKRNa1WDnFyWxrkrDXtOx5FwzeCS9nuI9PWLH3NsgU/edit#slide=id.g5a662668d9_0_352

**Comment by serenamarie125** [comment]
@debsmita1 for now could we just remove that last sentence if the user doesn't have the ability to perform the action?  Currently we don't have a convention to educate users on how to request access.  I think it would be best to punt on that, until we have customer requests.  Thanks!

**Review by serenamarie125 — APPROVED** [review]
LGTM

Looks great, thanks @debsmita1 !

**Comment by debsmita1** [comment]
Propagating docs and px acks from the Epic
/label docs-approved
/label px-approved

**Pull request merged**
