### PR TITLE
OCPBUGS-2145: maxUnavailable and minAvailable on PDB creation page - i18n misses

### PR DESCRIPTION
**Pull request by cyril-ui-developer**
### Before:
Screenshot 2022-12-15 at 9 05 58 AM

### After:
Screenshot 2022-12-15 at 9 06 50 AM

### CODE REVIEW

**Review by jhadvig — COMMENTED** [review]
one small nit

**Comment by cyril-ui-developer** [comment]
@jhadvig Updated.

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
