### PR TITLE
clean up files for components which have been migrated to dynamic extensions

### PR DESCRIPTION
**Pull request by debsmita1**
**Task:**
https://issues.redhat.com/browse/ODC-6400

### CODE REVIEW

**Comment by debsmita1** [comment]
> @debsmita1 E2E tests are failing for dev console tests. Need to update the tests to use new sidebars I guess.

these tests are not related to my PR . I have checked the devconsole & helm e2e tests, they are passing in my local

**Review by rottencandy — APPROVED** [review]
Tested changes on a cluster. Looks good.

cc @invincibleJai

**Pull request merged**
