### PR TITLE
Update modal inputs to PF4 style

### PR DESCRIPTION
**Pull request by rhamilto**
cc: @sg00dwin 

Partially addresses https://jira.coreos.com/browse/CONSOLE-1564

### CODE REVIEW

**Comment by spadgett** [comment]
@rhamilto it looks like there are some other modals. will the change in _modals.scss break those?

**Comment by spadgett** [comment]
A few others:

```
public/components/operator-hub/operator-hub-community-provider-modal.tsx
public/components/operator-lifecycle-manager/descriptors/spec/resource-requirements.tsx
packages/kubevirt-plugin/src/components/modals/delete-device-modal/delete-device-modal.tsx
packages/dev-console/src/components/import/git/CreateSourceSecretModal.tsx
```

**Comment by spadgett** [comment]
@alecmerdler fyi this will conflict with #1990

**Comment by rhamilto** [comment]
> @rhamilto it looks like there are some other modals. 

Updated the other relevant modals that are not in the modals folder.  

> will the change in _modals.scss break those?

If I did miss something, the worse that happens is the background of the inputs will mask the modal shadow **if the modal scrolls so the input overlays the shadow** (a minor concern).

**Pull request merged**
