### PR TITLE
Bug 1806284: disable deploy-image integration tests

### PR DESCRIPTION
**Pull request by sahil143**
**Analysis / Root cause**: 

Tests fixed in the PR https://github.com/openshift/console/pull/4474 doesn't seem to be fixed on PR Builds. But After that fix, this failing test
```
should deploy the image and display it in the topology (3 failures)
```
 is not reproducible locally.

**Solution Description**: 

Disable test until we identify a fix because this fix is blocking PRs from getting merged.

**Screen shots / Gifs for design review**: 

**Unit test coverage report**: 

**Test setup:**

**Browser conformance**: 

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by andrewballantyne** [comment]
/kind cleanup

@sahil143 Do we want to clean this up as a whole file or just the one test that fails? I think the other test cases work fine - it's just the last one that has issues on a flake-nature.

@spadgett @christianvogt thoughts?

**Comment by christianvogt** [comment]
@sahil143 if we can just disable the one test, that would be better than everything as I don't recall flakes in the other tests.

**Comment by sahil143** [comment]
> @sahil143 if we can just disable the one test, that would be better than everything as I don't recall flakes in the other tests.

@christianvogt @andrewballantyne Test is failing at the "creation of resource" step, Scenario was testing the whole flow by creating a resource and checking its availability in topology. I wasn't sure whether to disable one or all of them because it's not successful at the last step which we are actually testing for.

I will disable only the failing test.

**Comment by andrewballantyne** [comment]
🤞 Going to wait on the tests before adding label.

**Comment by andrewballantyne** [comment]
/test analyze

Not the issue we are fixing here...

**Pull request merged**
