### PR TITLE
Add Open Liberty icon option

### PR DESCRIPTION
**Pull request by rhamilto**
I mocked a template that uses the new `icon-openliberty` iconClass for the purposes of the screenshots below:

Screen Shot 2019-09-09 at 9 38 16 AM
Screen Shot 2019-09-09 at 9 38 22 AM
Screen Shot 2019-09-09 at 9 38 33 AM

### CODE REVIEW

**Comment by rhamilto** [comment]
/hold

Going to swap the logo for an SVG.

**Comment by rhamilto** [comment]
/hold cancel

Updated logo to SVG.  @spadgett, please re-tag.

**Comment by spadgett** [comment]
I opened #2645 to address the test flake above

**Pull request merged**
