### PR TITLE
Apply correct pf4 button classes to dropdowns

### PR DESCRIPTION
**Pull request by sg00dwin**
https://jira.coreos.com/browse/CONSOLE-1590
 [Revised]
Screen Shot 2019-07-05 at 1 56 45 PM
Screen Shot 2019-07-05 at 1 56 53 PM
Screen Shot 2019-07-05 at 1 57 47 PM

### CODE REVIEW

**Comment by spadgett** [comment]
I think we'll want to try to update all buttons for to PF4 styles in 4.2.

**Comment by christianvogt** [comment]
The vertical alignment of the text looks too high.
There is also a shadowed border around the button that needs to be removed to align with PF4.

**Comment by rhamilto** [comment]
> The vertical alignment of the text looks too high.
There is also a shadowed border around the button that needs to be removed to align with PF4.

This is because PF4 dropdown styles and button styles are pretty different.  The [PF4 dropdowns demo page](https://patternfly-react.surge.sh/patternfly-4/components/dropdown/) does not include examples of mixing button styles with dropdowns, so perhaps this usage is not intended?  @openshift/team-devconsole-ux?

**Comment by rhamilto** [comment]
^ @openshift/team-ux-review please seehttps://github.com/openshift/console/pull/1905#issuecomment-508211183.  I mistagged the wrong team on my initial comment (autocomplete fail).

**Comment by spadgett** [comment]
@sg00dwin I'd suggest using the default white dropdown button for now and opening an upstream patternfly issue for using primary button styles with the dropdown. Unfortunately the create button styles will be different page to page, but it'd be good to fix the immediate bug.

/lgtm cancel

**Comment by bmignano** [comment]
@sg00dwin @spadgett I believe you're correct that PF4 does not account for this use case. In the [gap analysis](https://docs.google.com/document/d/18jIivmC7AwP3SbWxkSnFyLy26E2-jiaYDTl1qRaJxgc/edit#heading=h.ld20sb2ud1zi) we did regarding buttons we noted that these button dropdowns might end up being custom since PF4 doesn't support them as of right now. Agree with Sam's approach to open an issue and use the other styling for now 👍

**Comment by sg00dwin** [comment]
Related issue for option to apply primary styling to dropdown buttons
https://github.com/patternfly/patternfly-next/issues/1872

**Pull request merged**
