### PR TITLE
Use action group extensions for group/submenus and create new action menu components using PF menu

### PR DESCRIPTION
**Pull request by rohitkrai03**
**Fixes**: 
- https://issues.redhat.com/browse/ODC-5749
- https://issues.redhat.com/browse/ODC-5748

**Analysis / Root cause**: 
- The `ActionGroup` extension was not used to create groups and submenus in kebab.
- PF components were not being used in `KebabMenu`.

**Solution Description**: 
- Added new logic in `ActionLoader` that uses `ActionGroup` extensions to create menu options with groups and submenus.
- Created new `ActionMenu` components that uses PF menu components. Had to use custom menu and submenu rendering logic due to PF bug with submenus.
- Added logic to sort all the actions based on `insertBefore` and `insertAfter` properties.
- `ActionMenu` component now supports both kebab as well as dropdown variant that can be used for different action menu scenarios.
- Migrated actions menu on the helm details page to use new extension based actions and `ActionsLoader`.

**Screen shots / Gifs for design review**: 

https://user-images.githubusercontent.com/6041994/123707324-25207200-d887-11eb-81c1-673ed13646ef.mov

**Unit test coverage report**: 

Screenshot 2021-06-29 at 9 10 15 PM

https://user-images.githubusercontent.com/6041994/123834722-5d768d80-d925-11eb-8148-e94c7d5f315b.mov

**Test setup:**

- Added a [dummy commit](https://github.com/openshift/console/pull/9365/commits/beaf6499408e110c86c548a165d298c01757c42a) that updates the helm actions to use dummy groups and submenus. This commit is just for testing and will be deleted before merging.

**Browser conformance**: 

- [x] Chrome
- [x] Firefox
- [ ] Safari
- [x] Edge

### CODE REVIEW

**Review by sahil143 — APPROVED** [review]
Looks Good to me.

Tested Locally and works as expected.

I only see one issue with the component is that clicking on subgroup closes the dropdown and action is not performed.

**Comment by rohitkrai03** [comment]
@sahil143 Deleted the dummy commit. The issue with sub menu clicks is because of popper rendering popper as submenus. Since there are no actual use cases for submenus right now, we'll wait for this PF fix - https://github.com/patternfly/patternfly-react/pull/5789. Once the PF fix is in we can update our code to use PF `Menu` component directly. I think we can get this PR merged if there're no other comments because https://github.com/openshift/console/pull/9306 also depends on this PR.

**Pull request merged**
