### PR TITLE
Bug 2094240: Update workload-pause.tsx to fix inconsistency between buttons in the notification and kebab action dropdown. 

### PR DESCRIPTION
**Pull request by l1xiangyi**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2094240
The Resume rollout in the [MachineConfigPools] > MachineConfigPool details page is inconsistent with the Resume updates button appeared in the kebab action dropdown menu.

### CODE REVIEW

**Comment by l1xiangyi** [comment]
@jhadvig

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
