### PR TITLE
Correctly handle batch calls to setState when creating secrets

### PR DESCRIPTION
**Pull request by spadgett**
See https://reactjs.org/docs/react-component.html#setstate

### CODE REVIEW

**Comment by jhadvig** [comment]
```
Interacting with the create secret forms.Registry credentials image secrets check for edited registry credentials image secret value 0.32s

Error: Failed expectation
    at Object.<anonymous> (/go/src/github.com/openshift/console/frontend/integration-tests/views/secrets.view.ts:67:29)
    at step (/go/src/github.com/openshift/console/frontend/integration-tests/views/secrets.view.ts:32:23)
    at Object.next (/go/src/github.com/openshift/console/frontend/integration-tests/views/secrets.view.ts:13:53)
    at fulfilled (/go/src/github.com/openshift/console/frontend/integration-tests/views/secrets.view.ts:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

/retest

**Comment by spadgett** [comment]
> Although Im not really sure why the Registry credentials image secrets check for edited registry credentials image secret value step is failing.

Yeah, that is failing on almost every PR :(

**Comment by spadgett** [comment]
Adding `lgtm` label based on approved reviews from Jakub and Dave.

**Pull request merged**
