### PR TITLE
Reduce min-length module cycles & enforce max threshold

### PR DESCRIPTION
**Pull request by vojtechszocs**
```diff
-171 total cycles, 31 min-length cycles (A -> B -> A)
+165 total cycles, 17 min-length cycles (A -> B -> A)
```

cc @spadgett @benjaminapetersen @christianvogt

### CODE REVIEW

**Comment by spadgett** [comment]
👍 thank you

**Comment by vojtechszocs** [comment]
Rebased on latest master, there was a conflicting file.

**Pull request merged**
