### PR TITLE
Bug 1821577: No info "badge" on alert details page for Alert Watchdog after alert name at the top

### PR DESCRIPTION
**Pull request by dtaylor113**
### Added badges

image

image

### CODE REVIEW

**Comment by spadgett** [comment]
I'm not sure this is better. We might consider closing this as not a bug @cshinn opinion?

/cc @cshinn @kyoto 
/assign

**Comment by kyoto** [comment]
Sorry @dtaylor113, I didn't see this Bugzilla ticket.

Not showing the severity badge for `None` was intentional.

I think it's confusing to have a `None` badge because it's not obvious what "None" means in this context. The other severities on the other hand are pretty self explanatory (`Critical`, `Warning` and `Info`).

Also, you could say that `severity=none` means there is no severity, so a severity badge should not be shown.

I've closed the Bugzilla ticket, but please reopen if you think more discussion is required.

CC @cshinn

**Pull request closed without merging**
