### PR TITLE
[release-4.9] Bug 2010677: Update PatternFly/react-console

### PR DESCRIPTION
**Pull request by pcbailey**
A fix for the VNC console in the kubevirt-plugin is in the latest version of PatternFly. This PR updates the kubevirt-plugin's version of patternfly/react-console to the latest version to include this fix.

### CODE REVIEW

**Review by spadgett — APPROVED** [review]
/approve

**Comment by yapei** [comment]
@gouyang  Did you verify the fix? If everything works well could you help add the required labels so that I can add `cherry-pick-approved` label? 
The comments you need to add
```
/lgtm
/label qe-approved
```

**Pull request merged**
