### PR TITLE
OCPBUGS-22749: Adjust NAD name by using unique-names-generator

### PR DESCRIPTION
**Pull request by hstastna**
**Fixes:**
https://issues.redhat.com/browse/OCPBUGS-22749

**Analysis / Root cause**:
By using the "Create Network Attachment Definition" dialog, an administrator may create two NADs in two different namespaces that would be connected to a single L2 network. There is nothing in the UI that indicates that namespace isolation is breached.

**Solution Description**:
Adjust the NetworkAttachmentDefinition name after its creation to make sure the name will be unique, to prevent creating a network shared between isolated namespaces. Use `unique-names-generator` package to generate the unique names that are appended to the name filled in the form for creating NADs.

**Screen shots / Gifs for design review**:
_Before:_
NADs with same names, shared NADs between the different namespaces can be created:
nad_before

_After:_
Unique NADs names:
nad_after

### CODE REVIEW

**Comment by hstastna** [comment]
@avivtur @metalice @pcbailey @upalatucci @vojtechszocs please review

**Comment by metalice** [comment]
i can see it already installed by another package, you can just import it without installing it with yarn add. 
image

**Comment by hstastna** [comment]
> i can see it already installed by another package, you can just import it without installing it with yarn add. image

Well, it didn't work when I tried to just import it. It acted like the package didn't exist.

**Comment by metalice** [comment]
this is strange as i can see it imported here:
image

**Comment by metalice** [comment]
hmm tried to import.. didn't get any errors, 
image

**Comment by metalice** [comment]
you are adding to fornend/package.json and its has 
image

**Comment by hstastna** [comment]
@metalice I've played with the code and it started to work even without adding the package anywhere. Weird that it didn't work previously.

**Comment by hstastna** [comment]
@avivtur @metalice @pcbailey @upalatucci @vojtechszocs please review

**Pull request merged**
