### PR TITLE
(WIP) Level-up Jest & Enzyme

### PR DESCRIPTION
**Pull request by vojtechszocs**
### Dependency changes
- upgrades:
  - `jest`, `jest-cli`, `ts-jest` from `21.x` to `24.x` (latest)
  - `enzyme-adapter-react-16` from `1.12.1` to `1.13.2` (latest)
- additions:
  - `@types/jest`
  - `enzyme-to-json`

### TS config changes
- add `compilerOptions.types` referencing Jest and Jasmine typings

### Jest config changes
- extract config to `jest.config.js`
- use [`jsWithTs` preset](https://kulshekhar.github.io/ts-jest/user/config/#jest-preset) which reflects the [`allowJs:true` setting](https://www.typescriptlang.org/docs/handbook/compiler-options.html) in `tsconfig.json`
- run `before-tests.js` via `setupFilesAfterEnv` following [Enzyme setup](https://github.com/airbnb/enzyme/blob/master/docs/guides/jest.md) recommendation
- run `ts-jest` with [`isolatedModules:true`](https://kulshekhar.github.io/ts-jest/user/config/isolatedModules) (otherwise, the updated Jest runner gets stuck)
- use `snapshotResolver.js` that allows test vs. snapshot co-location

### Test vs. Snapshot co-location

```tsx
// packages/console-demo-plugin/src/foo.tsx

import * as React from 'react';

const Bar: React.SFC<any> = (props) => {
  return <div className="bar">
    Hello {props.text}!
  </div>
};

export const Foo: React.SFC = () => {
  return <div className="foo">
    <Bar text="Bar" />
  </div>
};
```

```tsx
// packages/console-demo-plugin/src/__tests__/foo.spec.tsx

import * as React from 'react';
import { shallow } from 'enzyme';
import toJson from 'enzyme-to-json';

import { Foo } from '../foo';

it('renders correctly', () => {
  const wrapper = shallow(<Foo />);
  expect(toJson(wrapper)).toMatchSnapshot();
});
```

```tsx
// packages/console-demo-plugin/src/__tests__/foo.snap.tsx

// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`renders correctly 1`] = `
<div
  className="foo"
>
  <Bar
    text="Bar"
  />
</div>
`;
```

Jest snapshot files have the same extension as their test counterparts.

```
foo.tsx
__tests__/foo.spec.tsx
__tests__/foo.snap.tsx
```

---

/cc @christianvogt @spadgett

### CODE REVIEW

**Comment by vojtechszocs** [comment]
@spadgett There are currently some post-upgrade Enzyme related errors, I need to look into those.

/cc @alecmerdler

**Comment by vojtechszocs** [comment]
@mareklibra @rawagner FYI, this PR customizes Jest snapshot file resolution, putting snapshot files next to test files.

**Comment by christianvogt** [comment]
@vojtechszocs please setup the `snapshotSerializers` for `enzyme-to-json`  to simplify tests.

**Comment by vojtechszocs** [comment]
Note to self: add [`typescript-snapshots-plugin`](https://github.com/asvetliakov/typescript-snapshots-plugin) to this PR.

**Comment by christianvogt** [comment]
@vojtechszocs are you going to complete this soon? The dev console needs snapshots. Otherwise we'll need to do some updates so our plugin functions in the interim

**Comment by alecmerdler** [comment]
What is the value of snapshot tests versus normal unit tests? It seems to unnecessarily couple the DOM output to the implementation, doesn't test the component logic, and makes it harder to follow TDD.

**Comment by christianvogt** [comment]
Snapshots are useful for testing data transformations. ie input -> json output

I also find snapshots to be useful for components which are rendering html elements which have CSS that couples the rules to the structure. eg. using `>` and other nested selectors.

But simply snapshotting all react components does not make sense.

**Comment by vojtechszocs** [comment]
> @vojtechszocs are you going to complete this soon? The dev console needs snapshots. Otherwise we'll need to do some updates so our plugin functions in the interim

@christianvogt I'm currently finalizing my work on testing actual plugins, i.e. validating their extensions, as part of the Console build (like we discussed before). I'll get back to this PR right after that.

This PR is still WIP since I've encountered some weird Enzyme-related errors once I bumped Jest & related deps from `21.x` to `24.x` so I'll look into that.

> What is the value of snapshot tests versus normal unit tests?

Snapshot tests ensure that serialization of the given object yields the same results every time you run those tests.

The object being serialized can be anything, but developers often associate snapshot tests with React components. Based on the premise that a React component is essentially a function taking inputs (props, state, context) and producing rendered markup (JSX), snapshot tests guard against regressions that might occur in component's rendered JSX.

So, for React components, it's a way to ensure rendered UI doesn't change unexpectedly. If it does, and the change was intentional/expected, you can update the snapshot to make the test pass again.

> It seems to unnecessarily couple the DOM output to the implementation, doesn't test the component logic, and makes it harder to follow TDD.

React components should be snapshot-tested in _isolation_, i.e. rendered in `jsdom` that emulates "real" DOM env. Snapshots of React components should _not_ include rendered markup of their children, for example:

```tsx
const Bar: React.SFC<any> = (props) => {
  return <div className="bar">
    Hello {props.text}!
  </div>
};

export const Foo: React.SFC = () => {
  return <div className="foo">
    <Bar text="Bar" />
  </div>
};
```

`Foo` component snapshot should look like this:

```
<div className="foo">
  <Bar text="Bar" />
</div>
```

Component logic can be tested by simulating interaction with component's DOM elements, i.e. using Enzyme wrapper. You are testing a React component as a unit, instead of testing its individual methods.

As for TDD, I think it's best to complement it with different techniques.

> But simply snapshotting all react components does not make sense.

Fully agreed. Just like 100% test coverage just for the sake of having it doesn't make sense.

**Pull request closed without merging**
