### PR TITLE
Bug 1881934:  Fix for clearing topology kind filters whenever filters change

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
**Fixes**
https://issues.redhat.com/browse/ODC-4909

**Description**
Fix for topology to allow filtering by kinds.

**Browser conformance**: 
- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

/kind bug

### CODE REVIEW

**Comment by invincibleJai** [comment]
/approve

Verified changes , works as expected

**Review by sahil143 — APPROVED** [review]
/lgtm

verified changes locally

**Pull request merged**
