### PR TITLE
Consume New Marketplace APIs

### PR DESCRIPTION
**Pull request by alecmerdler**
### Description

Converts `PackageManifest`, `OperatorGroup`, `OperatorSource`, and `CatalogSourceConfig` to be under `operators.coreos.com/v1`. 

Introduces some (hacky) helper functions in order to use the model defined in Redux (old APIs) if the static models (new APIs) do not exist in the cluster. In the future, this is not how APIs should be upgraded. The standard migration model for software always puts the burden of supporting older APIs on the provider, not the clients. The correct way to do this would be:
1. Operator adds new APIs and supports old versions ([Kubernetes provides mechanism for this](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/))
2. Console updates static models to use the new APIs
3. Operator removes old APIs now that all clients have been given a chance to migrate

This was not possible for the Marketplace Operator due to limitations with the Operator SDK.

Associated with https://github.com/operator-framework/operator-lifecycle-manager/pull/774
Associated with https://github.com/operator-framework/operator-marketplace/pull/139
Addresses https://jira.coreos.com/browse/OLM-978

### CODE REVIEW

**Comment by spadgett** [comment]
Is the plan to remove these helpers after operator-framework/operator-lifecycle-manager#774 merges?

**Comment by alecmerdler** [comment]
@spadgett Yes, this is an intermediate PR, but I put more effort into reducing the hackiness in case our CI breaks and the backend PRs aren't able to merge.

**Comment by aravindhp** [comment]
@alecmerdler operator-framework/operator-marketplace#139 is ready to go once this PR and operator-framework/operator-registry#40 have merged. It will pass e2e only after operator-framework/operator-registry#40 has merged.

**Comment by alecmerdler** [comment]
New c[luster-wide channel for etcd Operator](https://github.com/openshift/console/pull/1327) is breaking the end-to-end tests

**Comment by alecmerdler** [comment]
@SamiSousa Tests are passing, do you mind giving an `/lgtm`?

**Pull request merged**
