### PR TITLE
[WIP] Bug 1811886: Disable `downlevelIteration` in tsconfig.json

### PR DESCRIPTION
**Pull request by spadgett**
I believe this is a TypeScript bug.

We've been seeing occasional `RangeError` runtime errors when using the
spread operator on a `Set`. Here is an example from CI:

https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_console/4683/pull-ci-openshift-console-release-4.4-e2e-gcp-console/746

And this bug:

https://bugzilla.redhat.com/show_bug.cgi?id=1811886

I was able to reproduce in 4.3.0-0.nightly-2020-03-09-200240 and set a
breakpoint on runtime errors. The error in this release happens here:

https://github.com/openshift/console/blob/57355dcf1ccf267dbca508589b640947a90ecc40/frontend/public/module/k8s/get-resources.ts#L104

Screen Shot 2020-03-10 at 10 57 17 AM

`[...resourceSet]` fails, even though the `Set` has the expected data,
and you should be able to use the spread operator on a `Set` when
`downlevelIteration` is enabled in tsconfig.json. In the generated JS
`__spreadArray` function, the code attempts to read the `length`
property on the `Set` to calculate the size of the new array. `Set` does
not have a `length`, however, so this result in `NaN`. Creating a new
array with `NaN` length causes the `RangeError`.

I'm not sure under what circumstances this occurs, but this commit
switches to the alternative `Array.from`, which works with `Set`, and
disables `downlevelIteration` to avoid errors in the future.

### CODE REVIEW

**Comment by spadgett** [comment]
@benjaminapetersen If you disable `downlevelIteration`, using spread operator on a set is a compiler error

**Comment by benjaminapetersen** [comment]
Excellent. Then we are good to go.

**Comment by spadgett** [comment]
Closing for now since this change seems to have introduced another problem. We need to figure out why we don't have repeatable builds.

/close

**Pull request closed without merging**
