### PR TITLE
[release-4.13] OCPBUGS-18538: OCP console mandate secret for repository creation

### PR DESCRIPTION
**Pull request by Lucifergene**
Manual cherry-pick PR for #13084 & #12690

/assign @Lucifergene

### CODE REVIEW

**Review by Lucifergene — COMMENTED** [review]
Verified on 4.13.0-0.nightly-2023-09-04-204240


https://github.com/openshift/console/assets/47265560/639d50b8-c155-4595-82c1-be6322e638e7

**Review by jerolimov — APPROVED** [review]
/label backport-risk-assessed
/lgtm
/approve

**Pull request merged**
