### PR TITLE
Add id in application-launcher div for tests

### PR DESCRIPTION
**Pull request by sanketpathak**

### CODE REVIEW

**Comment by spadgett** [comment]
Typically this would be added in the same PR that introduces the test. Code change looks good, however.

**Comment by christianvogt** [comment]
@sanketpathak I agree with @spadgett, why is this a separate PR?

**Comment by ppitonak** [comment]
@christianvogt @spadgett I told Sanket to separate it because I didn't know how team uses IDs in tests. Feel free to close it and Sanket would put this change to #1802.

**Comment by sanketpathak** [comment]
Should I update the PR #1802  with the changes from this PR.

**Comment by spadgett** [comment]
> @christianvogt @spadgett I told Sanket to separate it because I didn't know how team uses IDs in tests. Feel free to close it and Sanket would put this change to #1802.

Yeah, we're moving to `data-test-` attributes, which we've found makes tests easier to write and more reliable. The changes here look good. I'd add this to #1802. Thanks!

**Pull request closed without merging**
