### PR TITLE
CONSOLE-3686: Convert SecretFormWrapper component in create-secret.ts…

### PR DESCRIPTION
**Pull request by tvu20**
…x from class component to functional component

SecretFormWrapper component in create-secret.tsx converted from a class component to a functional component in order to use react-router v6 hooks.

### CODE REVIEW

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by tvu20** [comment]
This is technical debt cleanup and has no user-facing impact, so I am manually assigning docs and px approvals.

/label docs-approved
/label px-approved

**Comment by yanpzhan** [comment]
@XiyunZhao will help to test it.

**Comment by XiyunZhao** [comment]
This PR has been tested, no issue was found
/label qe-approved

**Pull request merged**
