### PR TITLE
Bug 1741473: Apply correct pf4 button styling and fix disabled functionality.

### PR DESCRIPTION
**Pull request by sg00dwin**
Issue https://jira.coreos.com/browse/CONSOLE-1698

**Fixed**
Screen Shot 2019-08-21 at 3 14 24 PM
Screen Shot 2019-08-21 at 3 56 37 PM

### CODE REVIEW

**Comment by sg00dwin** [comment]
@jtomasek would you be able to test this on your end?

**Comment by spadgett** [comment]
@sg00dwin this failed the linter. the plugins require prettier formatting

**Comment by sg00dwin** [comment]
updated pr
/retest

**Comment by jtomasek** [comment]
This fixes https://bugzilla.redhat.com/show_bug.cgi?id=1741473 please add the reference to the PR title: Bug 1741473

**Pull request merged**
