### PR TITLE
Bug 1847141: Add 4.5 channels to Cluster Settings page

### PR DESCRIPTION
**Pull request by spadgett**
/assign @rhamilto @sdodson

### CODE REVIEW

**Comment by spadgett** [comment]
yarn install is failing due to network errors

```
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info If you think this is a bug, please open a bug report with the information provided in "/go/src/github.com/openshift/console/frontend/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error An unexpected error occurred: "https://registry.yarnpkg.com/@patternfly/react-tokens/-/react-tokens-2.8.4.tgz: ESOCKETTIMEDOUT".
```

/retest

**Comment by sdodson** [comment]
I've set cherry-pick-approved because this is time sensitive, it needs to make it in ideally this week, absolute worst case next week so that 4.4.10 or 4.4.11 presents 4.5 channels.

**Pull request merged**
