### PR TITLE
Block pool management page capitalization

### PR DESCRIPTION
**Pull request by GowthamShanmugam**
Issue: [RHSTOR-1872](https://issues.redhat.com/browse/RHSTOR-1872)

Signed-off-by: Gowtham Shanmugasundaram <gshanmug@redhat.com>

### CODE REVIEW

**Review by afreen23 — CHANGES_REQUESTED** [review]
Change in the plugin.ts file as well:
```
  {
    type: 'ClusterServiceVersion/Action',
    properties: {
      id: 'delete',
      kind: models.CephBlockPoolModel.kind,
      label: '%ceph-storage-plugin~Delete Block Pool%',
 ```
 This causing tests to fail

**Comment by afreen23** [comment]
@GowthamShanmugam this needs rebase
Looks good to me

**Comment by GowthamShanmugam** [comment]
@afreen23 Fixed conflicts

**Review by afreen23 — APPROVED** [review]
/lgtm

**Comment by GowthamShanmugam** [comment]
Resolved conflicts from #9017

**Pull request merged**
