### PR TITLE
Change Operator Hub to OperatorHub

### PR DESCRIPTION
**Pull request by TheRealJon**
Fixes https://jira.coreos.com/browse/CONSOLE-1280
Change all instances of "Operator Hub' in the UI to "OperatorHub"

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Same error as the other PRs, think the authentication-operator PR 73 will also unclog this one.

**Comment by benjaminapetersen** [comment]
/retest

[operator PR 143](https://github.com/openshift/console-operator/pull/143) merged, lets see if the TLS issue with the authentication operator goes away.

**Comment by benjaminapetersen** [comment]
/retest

artifacts are gone, need to generate some new fail data.

**Comment by spadgett** [comment]
@TheRealJon merge conflict :/

**Comment by spadgett** [comment]
/hold cancel
but will need rebase

**Comment by TheRealJon** [comment]
Rebased, needs lgtm again

**Comment by spadgett** [comment]
flake https://jira.coreos.com/browse/CONSOLE-1294

/retest

**Comment by TheRealJon** [comment]
/retest

Test flake: https://jira.coreos.com/browse/CONSOLE-1297

**Comment by spadgett** [comment]
performance test flake

/retest

**Comment by spadgett** [comment]
performance test flake

/retest

**Comment by spadgett** [comment]
> level=error msg="\t* aws_instance.master.2: Error launching source instance: timeout while waiting for state to become 'success' (timeout: 30s)"

/retest

**Comment by spadgett** [comment]
```
level=error msg="\t* module.vpc.aws_route.to_nat_gw[4]: 1 error occurred:"
level=error msg="\t* aws_route.to_nat_gw.4: Error creating route: timeout while waiting for state to become 'success' (timeout: 2m0s)"
```

/retest

**Comment by TheRealJon** [comment]
@spadgett Rebased and fixed performance test

**Pull request merged**
