### PR TITLE
Bug 1836298: add runtime for redhat spring boot

### PR DESCRIPTION
**Pull request by sahil143**
**Fixes**: https://issues.redhat.com/browse/ODC-3051

**Analysis / Root cause**: missing Redhat spring boot icon

**Solution Description**: added icon

**Screen shots / Gifs for design review**: 

Screenshot from 2020-05-15 20-47-24

**Unit test coverage report**: 

**Test setup:**

**Browser conformance**: 

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### CODE REVIEW

**Comment by sahil143** [comment]
>Does this PR only provide the snowdrop logo?

Yes, this Pr only provides the snowdrop logo. We already have a logo for spring.
Screenshot 2020-05-15 at 9 54 18 PM

If another runtime is needed for spring-boot. Can you please provide the SVG for that. On the issue I see a `springboot.png` but not svg.

**Comment by serenamarie125** [comment]
@sahil143 let me see if I can locate it!

**Comment by invincibleJai** [comment]
Looks good to me , will add lgtm once we have approval from UXD

**Comment by serenamarie125** [comment]
@sahil143 @invincibleJai we also need to add spring-boot : https://github.com/eclipse/che-devfile-registry/blob/master/images/springboot.svg

**Comment by sahil143** [comment]
@serenamarie125  @invincibleJai added spring-boot icon as well
Screenshot from 2020-05-19 14-46-19

**Comment by invincibleJai** [comment]
/lgtm

looks good , below is screenshot for `rh-spring-boot` and `spring-boot`

Screenshot 2020-05-19 at 3 31 40 PM

**Pull request merged**
