### PR TITLE
Fix text overflow on Catalog tiles w/ long names

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Fix is in patternfly-react-extensions version 2.9.6

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1640054

### CODE REVIEW

**Comment by spadgett** [comment]
@sosiouxme fyi

/hold

**Comment by spadgett** [comment]
@jeff-phillips-18 I know @SamiSousa wanted to update patternfly-react as well. We might try to pull this together into one PR to make it easier on @sosiouxme. Are there any other fixes in patternfly-react we might need?

We need to figure out how to automate this since we update dependencies so frequently. I'm going to open a task.

**Comment by jeff-phillips-18** [comment]
There are a few PRs that need patternfly-react 2.18+
#655 and #666

**Comment by jeff-phillips-18** [comment]
patternfly-react 2.21.3 also has a fix we would want (side modal overlay animation on firefox)

**Comment by jeff-phillips-18** [comment]
@sosiouxme Updated package.json to patternfly-react-extensions 2.9.8 to pickup some other necessary fixes.

**Comment by jeff-phillips-18** [comment]
Updated `sources`

**Comment by spadgett** [comment]
Service catalog tests will be broken until #670 merges

**Comment by spadgett** [comment]
jenkins rebuild

**Pull request merged**
