### PR TITLE
Refactor Ceph Plugin Dashboard Directory Structure

### PR DESCRIPTION
**Pull request by bipuladh**
Depends on https://github.com/openshift/console/pull/5978/
Diff: 
```
3,12c3,24
< │   ├── attached-devices-mode
< │   │   └── lso-disk-inventory
< │   │       ├── disk-replacement-modal.tsx
< │   │       ├── ocs-disks-list.tsx
< │   │       ├── ocs-kebab-options.tsx
< │   │       ├── ocs-status-column.scss
< │   │       ├── ocs-status-column.tsx
< │   │       └── state-reducer.ts
< │   ├── dashboard-page
< │   │   └── storage-dashboard
---
> │   ├── dashboards
> │   │   ├── common
> │   │   │   ├── breakdown-card
> │   │   │   │   ├── breakdown-body.tsx
> │   │   │   │   ├── breakdown-capacity.tsx
> │   │   │   │   ├── breakdown-card.scss
> │   │   │   │   ├── breakdown-chart.tsx
> │   │   │   │   ├── breakdown-dropdown.tsx
> │   │   │   │   ├── breakdown-loading.tsx
> │   │   │   │   ├── consts.ts
> │   │   │   │   └── utils.tsx
> │   │   │   ├── data-resiliency
> │   │   │   │   └── data-resiliency-activity.tsx
> │   │   │   └── storage-efficiency
> │   │   │       ├── storage-efficiency-card-item.tsx
> │   │   │       └── storage-efficiency-card.scss
> │   │   ├── persistent-external
> │   │   │   ├── breakdown-card.tsx
> │   │   │   ├── details-card.tsx
> │   │   │   ├── status-card.tsx
> │   │   │   └── utilization-card.tsx
> │   │   └── persistent-internal
17d28
< │   │       │   ├── data-resiliency-activity.tsx
19,27d29
< │   │       ├── breakdown-card
< │   │       │   ├── breakdown-body.tsx
< │   │       │   ├── breakdown-capacity.tsx
< │   │       │   ├── breakdown-card.scss
< │   │       │   ├── breakdown-chart.tsx
< │   │       │   ├── breakdown-dropdown.tsx
< │   │       │   ├── breakdown-loading.tsx
< │   │       │   ├── consts.ts
< │   │       │   └── utils.tsx
40,41d41
< │   │       │   ├── storage-efficiency-card-item.tsx
< │   │       │   ├── storage-efficiency-card.scss
49,60d48
< │   ├── independent-dashboard-page
< │   │   ├── breakdown-card.tsx
< │   │   ├── details-card.tsx
< │   │   ├── status-card.tsx
< │   │   └── utilization-card.tsx
< │   ├── independent-mode
< │   │   ├── fileUpload.scss
< │   │   ├── fileUpload.tsx
< │   │   ├── install.scss
< │   │   ├── install.tsx
< │   │   ├── utils.spec.ts
< │   │   └── utils.ts
64a53,58
> │   ├── lso-disk-inventory
> │   │   ├── ocs-disks-list.tsx
> │   │   ├── ocs-kebab-options.tsx
> │   │   ├── ocs-status-column.scss
> │   │   ├── ocs-status-column.tsx
> │   │   └── state-reducer.ts
71a66
> │   │   ├── disk-replacement-modal.tsx
78c73
< │   │   ├── attached-devices
---
> │   │   ├── attached-devices-mode
93a89,95
> │   │   ├── external-mode
> │   │   │   ├── fileUpload.scss
> │   │   │   ├── fileUpload.tsx
> │   │   │   ├── install.scss
> │   │   │   ├── install.tsx
> │   │   │   ├── utils.spec.ts
> │   │   │   └── utils.ts
163c165
< 35 directories, 125 files
---
> 37 directories, 125 files
```
BEFORE
```
./packages/ceph-storage-plugin/src/
├── components
│   ├── attached-devices-mode
│   │   └── lso-disk-inventory
│   │       ├── disk-replacement-modal.tsx
│   │       ├── ocs-disks-list.tsx
│   │       ├── ocs-kebab-options.tsx
│   │       ├── ocs-status-column.scss
│   │       ├── ocs-status-column.tsx
│   │       └── state-reducer.ts
│   ├── dashboard-page
│   │   └── storage-dashboard
│   │       ├── activity-card
│   │       │   ├── activity-card.scss
│   │       │   ├── activity-card.tsx
│   │       │   ├── cluster-expand-activity.tsx
│   │       │   ├── data-resiliency-activity.tsx
│   │       │   └── ocs-upgrade-activity.tsx
│   │       ├── breakdown-card
│   │       │   ├── breakdown-body.tsx
│   │       │   ├── breakdown-capacity.tsx
│   │       │   ├── breakdown-card.scss
│   │       │   ├── breakdown-chart.tsx
│   │       │   ├── breakdown-dropdown.tsx
│   │       │   ├── breakdown-loading.tsx
│   │       │   ├── consts.ts
│   │       │   └── utils.tsx
│   │       ├── capacity-breakdown
│   │       │   ├── capacity-breakdown-card.scss
│   │       │   └── capacity-breakdown-card.tsx
│   │       ├── details-card.tsx
│   │       ├── inventory-card.tsx
│   │       ├── raw-capacity-card
│   │       │   ├── raw-capacity-card.scss
│   │       │   └── raw-capacity-card.tsx
│   │       ├── status-card
│   │       │   ├── status-card.tsx
│   │       │   └── utils.ts
│   │       ├── storage-efficiency-card
│   │       │   ├── storage-efficiency-card-item.tsx
│   │       │   ├── storage-efficiency-card.scss
│   │       │   └── storage-efficiency-card.tsx
│   │       ├── top-consumers-card
│   │       │   ├── top-consumers-card-body.tsx
│   │       │   └── utils.ts
│   │       └── utilization-card
│   │           ├── utilization-card.tsx
│   │           └── utils.tsx
│   ├── independent-dashboard-page
│   │   ├── breakdown-card.tsx
│   │   ├── details-card.tsx
│   │   ├── status-card.tsx
│   │   └── utilization-card.tsx
│   ├── independent-mode
│   │   ├── fileUpload.scss
│   │   ├── fileUpload.tsx
│   │   ├── install.scss
│   │   ├── install.tsx
│   │   ├── utils.spec.ts
│   │   └── utils.ts
│   ├── kms-config
│   │   ├── kms-config.scss
│   │   ├── kms-config.tsx
│   │   └── utils.tsx
│   ├── modals
│   │   ├── add-capacity-modal
│   │   │   ├── _add-capacity-modal.scss
│   │   │   └── add-capacity-modal.tsx
│   │   ├── advanced-kms-modal
│   │   │   ├── advanced-kms-modal.scss
│   │   │   └── advanced-kms-modal.tsx
│   │   ├── storage-class-dropdown.scss
│   │   ├── storage-class-dropdown.tsx
│   │   └── storage-pool-modal
│   │       ├── storage-pool-modal.scss
│   │       └── storage-pool-modal.tsx
│   ├── ocs-install
│   │   ├── attached-devices
│   │   │   ├── attached-devices.scss
│   │   │   ├── create-sc
│   │   │   │   ├── create-sc.tsx
│   │   │   │   ├── state.ts
│   │   │   │   └── wizard-pages
│   │   │   │       ├── auto-detect-volume.tsx
│   │   │   │       ├── configure-step.tsx
│   │   │   │       ├── create-local-volume-set.tsx
│   │   │   │       ├── disk-list.tsx
│   │   │   │       ├── donut-chart.tsx
│   │   │   │       ├── review-and-create-step.tsx
│   │   │   │       └── storage-and-nodes-step.tsx
│   │   │   ├── install.tsx
│   │   │   └── sc-node-list.tsx
│   │   ├── existing-cluster-modal.tsx
│   │   ├── install-page.scss
│   │   ├── install-page.tsx
│   │   ├── install-wizard
│   │   │   ├── capacity-and-nodes.tsx
│   │   │   ├── _configure.scss
│   │   │   ├── configure.tsx
│   │   │   ├── install-wizard.scss
│   │   │   └── review-and-create.tsx
│   │   ├── internal-mode
│   │   │   ├── install-wizard-steps
│   │   │   │   ├── configure.tsx
│   │   │   │   ├── index.ts
│   │   │   │   ├── review-and-create.tsx
│   │   │   │   └── select-capacity-and-nodes-step.tsx
│   │   │   ├── install-wizard.tsx
│   │   │   └── reducer.ts
│   │   ├── node-list.tsx
│   │   ├── ocs-install.scss
│   │   ├── ocs-request-data.ts
│   │   ├── pvs-available-capacity.scss
│   │   ├── pvs-available-capacity.tsx
│   │   ├── subscription-icon.scss
│   │   ├── subscription-icon.tsx
│   │   └── types.ts
│   └── ocs-storage-class-form
│       ├── ocs-storage-class-form.scss
│       └── ocs-storage-class-form.tsx
├── constants
│   ├── common.ts
│   ├── disks.ts
│   ├── index.ts
│   ├── kms.ts
│   ├── network.ts
│   ├── ocs-install.ts
│   ├── pool.ts
│   ├── queries.ts
│   ├── resources.ts
│   ├── storage-pool-const.ts
│   └── tooltips.ts
├── extensions
│   └── dashboards.ts
├── features.ts
├── index.ts
├── __mocks__
│   ├── breakdown-data.ts
│   └── independent-mode-dashboard-data.ts
├── models.ts
├── plugin.ts
├── selectors
│   └── index.ts
├── __tests__
│   ├── breakdown-body.spec.tsx
│   ├── breakdown-chart.spec.tsx
│   ├── independent-dashboard-breakdown-card.spec.tsx
│   ├── independent-dashboard-details-card.spec.tsx
│   └── __snapshots__
├── types.ts
└── utils
    ├── add-capacity.ts
    ├── alert-action-path.tsx
    ├── common-ocs-install-el.tsx
    ├── dashboard.ts
    ├── events.ts
    ├── index.ts
    ├── install.ts
    ├── ocs-storage-class-params.tsx
    ├── osd-size-dropdown.tsx
    └── storage-pool.tsx
```
AFTER
```
./packages/ceph-storage-plugin/src/
├── components
│   ├── dashboards
│   │   ├── common
│   │   │   ├── capacity-breakdown
│   │   │   │   ├── breakdown-body.tsx
│   │   │   │   ├── breakdown-capacity.tsx
│   │   │   │   ├── breakdown-card.scss
│   │   │   │   ├── breakdown-chart.tsx
│   │   │   │   ├── breakdown-dropdown.tsx
│   │   │   │   ├── breakdown-loading.tsx
│   │   │   │   ├── consts.ts
│   │   │   │   └── utils.tsx
│   │   │   ├── data-resiliency
│   │   │   │   └── data-resiliency-activity.tsx
│   │   │   └── storage-efficiency
│   │   │       ├── storage-efficiency-card-item.tsx
│   │   │       └── storage-efficiency-card.scss
│   │   ├── persistent-external
│   │   │   ├── breakdown-card.tsx
│   │   │   ├── details-card.tsx
│   │   │   ├── status-card.tsx
│   │   │   └── utilization-card.tsx
│   │   └── persistent-internal
│   │       ├── activity-card
│   │       │   ├── activity-card.scss
│   │       │   ├── activity-card.tsx
│   │       │   ├── cluster-expand-activity.tsx
│   │       │   └── ocs-upgrade-activity.tsx
│   │       ├── capacity-breakdown-card
│   │       │   ├── capacity-breakdown-card.scss
│   │       │   └── capacity-breakdown-card.tsx
│   │       ├── details-card.tsx
│   │       ├── inventory-card.tsx
│   │       ├── raw-capacity-card
│   │       │   ├── raw-capacity-card.scss
│   │       │   └── raw-capacity-card.tsx
│   │       ├── status-card
│   │       │   ├── status-card.tsx
│   │       │   └── utils.ts
│   │       ├── storage-efficiency-card
│   │       │   └── storage-efficiency-card.tsx
│   │       ├── top-consumers-card
│   │       │   ├── top-consumers-card-body.tsx
│   │       │   └── utils.ts
│   │       └── utilization-card
│   │           ├── utilization-card.tsx
│   │           └── utils.tsx
│   ├── disk-inventory
│   │   ├── ocs-disks-list.tsx
│   │   ├── ocs-kebab-options.tsx
│   │   ├── ocs-status-column.scss
│   │   ├── ocs-status-column.tsx
│   │   └── state-reducer.ts
│   ├── kms-config
│   │   ├── kms-config.scss
│   │   ├── kms-config.tsx
│   │   └── utils.tsx
│   ├── modals
│   │   ├── add-capacity-modal
│   │   │   ├── add-capacity-modal.scss
│   │   │   └── add-capacity-modal.tsx
│   │   ├── advanced-kms-modal
│   │   │   ├── advanced-kms-modal.scss
│   │   │   └── advanced-kms-modal.tsx
│   │   ├── disk-replacement-modal.tsx
│   │   ├── storage-class-dropdown.scss
│   │   ├── storage-class-dropdown.tsx
│   │   └── storage-pool-modal
│   │       ├── storage-pool-modal.scss
│   │       └── storage-pool-modal.tsx
│   ├── ocs-install
│   │   ├── attached-devices-mode
│   │   │   ├── attached-devices.scss
│   │   │   ├── create-sc
│   │   │   │   ├── create-sc.tsx
│   │   │   │   ├── state.ts
│   │   │   │   └── wizard-pages
│   │   │   │       ├── auto-detect-volume.tsx
│   │   │   │       ├── configure-step.tsx
│   │   │   │       ├── create-local-volume-set.tsx
│   │   │   │       ├── disk-list.tsx
│   │   │   │       ├── donut-chart.tsx
│   │   │   │       ├── review-and-create-step.tsx
│   │   │   │       └── storage-and-nodes-step.tsx
│   │   │   ├── install.tsx
│   │   │   └── sc-node-list.tsx
│   │   ├── existing-cluster-modal.tsx
│   │   ├── external-mode
│   │   │   ├── fileUpload.scss
│   │   │   ├── fileUpload.tsx
│   │   │   ├── install.scss
│   │   │   ├── install.tsx
│   │   │   ├── utils.spec.ts
│   │   │   └── utils.ts
│   │   ├── install-page.scss
│   │   ├── install-page.tsx
│   │   ├── install-wizard
│   │   │   ├── capacity-and-nodes.tsx
│   │   │   ├── _configure.scss
│   │   │   ├── configure.tsx
│   │   │   ├── install-wizard.scss
│   │   │   └── review-and-create.tsx
│   │   ├── internal-mode
│   │   │   ├── install-wizard-steps
│   │   │   │   ├── configure.tsx
│   │   │   │   ├── index.ts
│   │   │   │   ├── review-and-create.tsx
│   │   │   │   └── select-capacity-and-nodes-step.tsx
│   │   │   ├── install-wizard.tsx
│   │   │   └── reducer.ts
│   │   ├── node-list.tsx
│   │   ├── ocs-install.scss
│   │   ├── ocs-request-data.ts
│   │   ├── pvs-available-capacity.scss
│   │   ├── pvs-available-capacity.tsx
│   │   ├── subscription-icon.scss
│   │   ├── subscription-icon.tsx
│   │   └── types.ts
│   └── ocs-storage-class-form
│       ├── ocs-storage-class-form.scss
│       └── ocs-storage-class-form.tsx
├── constants
│   ├── common.ts
│   ├── disks.ts
│   ├── index.ts
│   ├── kms.ts
│   ├── network.ts
│   ├── ocs-install.ts
│   ├── pool.ts
│   ├── queries.ts
│   ├── resources.ts
│   ├── storage-pool-const.ts
│   └── tooltips.ts
├── extensions
│   └── dashboards.ts
├── features.ts
├── index.ts
├── __mocks__
│   ├── breakdown-data.ts
│   └── independent-mode-dashboard-data.ts
├── models.ts
├── plugin.ts
├── selectors
│   └── index.ts
├── __tests__
│   ├── breakdown-body.spec.tsx
│   ├── breakdown-chart.spec.tsx
│   ├── independent-dashboard-breakdown-card.spec.tsx
│   ├── independent-dashboard-details-card.spec.tsx
│   └── __snapshots__
├── types.ts
└── utils
    ├── add-capacity.ts
    ├── alert-action-path.tsx
    ├── common-ocs-install-el.tsx
    ├── common.ts
    ├── dashboard.ts
    ├── events.ts
    ├── index.ts
    ├── install.ts
    ├── ocs-storage-class-params.tsx
    ├── osd-size-dropdown.tsx
    └── storage-pool.tsx
```

### CODE REVIEW

**Comment by afreen23** [comment]
1. The `storage efficiency` card can also be part of common similar to `breakdown`.
   The component `storage-efficiency-card-item.tsx` is a generic one and utilized by both `noobaa` and `ceph`. 
 
2. I think we can move `lso-disk-inventory` out from `attached-devices-mode` just like other components

      │   ├── ~~attached-devices-mode~~
      │   │   └── lso-disk-inventory
      │   │       ├── disk-replacement-modal.tsx
      │   │       ├── ocs-disks-list.tsx
      │   │       ├── ocs-kebab-options.tsx
      │   │       ├── ocs-status-column.scss
      │   │       ├── ocs-status-column.tsx
      │   │       └── state-reducer.ts

3. `disk-replacement-modal.tsx` can come under `modals` dir

4. `attached-devices` to `attached-devices-mode` to be consistent with other installation mode names

**Review by afreen23 — COMMENTED** [review]
1. The `storage efficiency` card can also be part of common similar to `breakdown`.
   The component `storage-efficiency-card-item.tsx` is a generic one and utilized by both `noobaa` and `ceph`. 
 
2. I think we can move `lso-disk-inventory` out from `attached-devices-mode` just like other components

      │   ├── ~~attached-devices-mode~~
      │   │   └── lso-disk-inventory
      │   │       ├── disk-replacement-modal.tsx
      │   │       ├── ocs-disks-list.tsx
      │   │       ├── ocs-kebab-options.tsx
      │   │       ├── ocs-status-column.scss
      │   │       ├── ocs-status-column.tsx
      │   │       └── state-reducer.ts

3. `disk-replacement-modal.tsx` can come under `modals` dir

4. `attached-devices` to `attached-devices-mode` to be consistent with other installation mode names

**Comment by afreen23** [comment]
1. We can take out dropdown from modals:

    │   ├── modals
    │   │   ├── add-capacity-modal
    │   │   │   ├── _add-capacity-modal.scss
    │   │   │   └── add-capacity-modal.tsx
    │   │   ├── advanced-kms-modal
    │   │   │   ├── advanced-kms-modal.scss
    │   │   │   └── advanced-kms-modal.tsx
    │   │   ├── disk-replacement-modal.tsx
    │   │   ├── ~~storage-class-dropdown.scss~~
    │   │   ├── ~~storage-class-dropdown.tsx~~

2.  We need to be consistent with names here:

│   │   ├── common
│   │   │   ├── ~~breakdown-card~~  => capacity-breakdown-card
│   │   │   ├── ~~data-resiliency~~ => activity-card
│   │   │   │   └── ...
│   │   │   └── ~~storage-efficiency~~  => storage-efficiency-card
│   │   │       ├── ...

3. Odd one out. This scss file name is not consistent with others: `_add-capacity-modal.scss` to `add-capacity-modal.scss`
│   ├── modals
│   │   ├── add-capacity-modal
│   │   │   ├── _add-capacity-modal.scss

4.This is ocs disk inventory, bad naming (my bad) and lso disk inventory is already in lso package.
We can just say `disk-inventory`.

│   ├── ~~lso-~~ disk-inventory
│   │   ├── ocs-disks-list.tsx
│   │   ├── ocs-kebab-options.tsx
│   │   ├── ocs-status-column.scss
│   │   ├── ocs-status-column.tsx
│   │   └── state-reducer.ts

**Comment by bipuladh** [comment]
@afreen23 Thanks for the review.
Regarding (1) Not making changes to `storage-class-dropdown` right now. IMO we should just remove it. 
Regarding (2) Agree but I am leaning towards not having the card part(Cards are technically completed when we have the dashboard header and other card related stuffs). `data-resiliency` exports a data resiliency activity hence I want to keep it that way. Either way I agree that the naming convention should be consistent and will make changes to make that happen.

**Pull request merged**
