### PR TITLE
Bug 1941798:  i18n kind on LimitRange and ResourceQuota list pages

### PR DESCRIPTION
**Pull request by rhamilto**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1941798

After:
Screen Shot 2021-04-26 at 2 34 18 PM
Screen Shot 2021-04-26 at 2 34 12 PM

### CODE REVIEW

**Review by rebeccaalpert — CHANGES_REQUESTED** [review]
The ResourceQuota create button text on line 447 also needs to be done. 
```
createButtonText={t('resource-quota~Create {{resource}}', {
          resource: ResourceQuotaModel.label,
        })}```

**Comment by rhamilto** [comment]
> The ResourceQuota create button text on line 447 also needs to be done.
> 
> ```
> createButtonText={t('resource-quota~Create {{resource}}', {
>           resource: ResourceQuotaModel.label,
>         })}```
> ```

Fixed.  Thanks, @rebeccaalpert

**Review by rebeccaalpert — APPROVED** [review]
Perfect! Thanks Robb.

**Review by spadgett — APPROVED** [review]
/lgtm

**Comment by rhamilto** [comment]
Drat. I forgot to run `yarn i18n` after my last fix.  Please retag, @spadgett.

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
