### PR TITLE
Bug 1803756: Vm Wizard always uses sata for CD ROM devices

### PR DESCRIPTION
**Pull request by glekner**

### CODE REVIEW

**Comment by glekner** [comment]
@rhrazdil can you review?
This is the windows tools cdrom, which is auto attached if the os is a Windows one.
regarding adding a new cd manually through the wizard, SATA was not the default choice for me, can you approve?

**Comment by glekner** [comment]
@jelkosz are we sure we want VirtIO for windows VMs? AFAIK we said SATA.

**Comment by jelkosz** [comment]
> @jelkosz are we sure we want VirtIO for windows VMs? AFAIK we said SATA.

you are right, it should be SATA - this CD only contains the drivers for VirtIO so using VirtIO would not work here.

> Also, should this be Targeted to 4.4 or 4.3?

If we want to fix it, than 4.4. But I don't  think we do :)

**Comment by glekner** [comment]
We are keeping SATA recommended for Windows and should remove the warning
Closing this, should be fixed through `common-templates`

**Pull request closed without merging**
