### PR TITLE
OCPBUGS-5164: add support for version v1beta1 for knativeServing and knativeEventing

### PR DESCRIPTION
**Pull request by vikram-raj**
Descriptions: Add support for API version `v1beta1` for `knativeServing` and `knativeEventing`

### CODE REVIEW

**Comment by cardil** [comment]
> Still, the UI is missing Knative Serving related UI. The Eventing UI is present.


I think those errors were just a fluke. After reinstalling Serverless with images from the development branch, I see the full UI.

Screenshot from 2022-12-22 19-13-05
Screenshot from 2022-12-22 19-12-52

**Comment by cardil** [comment]
Serverless UI tests are passing after this change. Thanks, @vikram-raj.

This should be backported to 4.8+ before Serverless 1.27 GA - 01/18

**Review by jerolimov — APPROVED** [review]
/retest
/lgtm

**Pull request merged**
