### PR TITLE
OCPBUGS-43084: While accessing the node terminal from UI observed 'Warning alert:Admission Webhook Warning`

### PR DESCRIPTION
**Pull request by cyril-ui-developer**

### CODE REVIEW

**Review by rhamilto — APPROVED** [review]
/lgtm

**Comment by rhamilto** [comment]
@cyril-ui-developer, I just noticed we have this same bug for debug pods.  Mind also fixing it [there](https://github.com/openshift/console/blob/bdb211350a66fe96ab215a655d41c45864dc3cef/frontend/public/components/debug-terminal.tsx#L114)?

**Comment by cyril-ui-developer** [comment]
> @cyril-ui-developer, I just noticed we have this same bug for debug pods. Mind also fixing it [there](https://github.com/openshift/console/blob/bdb211350a66fe96ab215a655d41c45864dc3cef/frontend/public/components/debug-terminal.tsx#L114)?

@rhamilto Is there a Jira ticket for this?

**Comment by rhamilto** [comment]
> > @cyril-ui-developer, I just noticed we have this same bug for debug pods. Mind also fixing it [there](https://github.com/openshift/console/blob/bdb211350a66fe96ab215a655d41c45864dc3cef/frontend/public/components/debug-terminal.tsx#L114)?
> 
> @rhamilto Is there a Jira ticket for this?

Not yet.

**Comment by cyril-ui-developer** [comment]
> > > @cyril-ui-developer, I just noticed we have this same bug for debug pods. Mind also fixing it [there](https://github.com/openshift/console/blob/bdb211350a66fe96ab215a655d41c45864dc3cef/frontend/public/components/debug-terminal.tsx#L114)?
> > 
> > 
> > @rhamilto Is there a Jira ticket for this?
> 
> Not yet.

Ok, I will create a ticket for it.

**Pull request merged**
