### PR TITLE
Bug 1908180: Add source for template is stucking in preparing pvc

### PR DESCRIPTION
**Pull request by glekner**
- Fixed suggested Volume, Access modes not updating upon SC change
- Showing alerts with documentation
- If modes are known, non-default modes will have the label `Not recommended`

Screen Shot 2020-12-29 at 12 56 08

--------------------

Screen Shot 2020-12-29 at 12 56 00

### CODE REVIEW

**Comment by glekner** [comment]
- changed not recommended text to include storage class name 
`Not recommended for ${storageClassName} storage class`

**Comment by yaacov** [comment]
/hold
for translations

**Pull request merged**
