### PR TITLE
CNV-36170: Multi NetworkPolicies

### PR DESCRIPTION
**Pull request by upalatucci**
- List page with NetworkPolicy and MultiNetworkPolicy tab
- creation form for NetworkPolicy and MultiNetworkPolicy

The list page component can be called also in the Developer view search page (last screenshot) IN that case do not show the tabs but only the list component.

Screenshot from 2024-04-26 15-28-28

Screenshot from 2024-04-18 09-25-02
Screenshot from 2024-04-18 09-24-57
Screenshot from 2024-04-18 09-24-50
Screenshot from 2024-04-18 09-24-40

image

### CODE REVIEW

**Comment by rhamilto** [comment]
In reading [the design document](https://docs.google.com/document/d/1cow5Aj3hfo9QCvvJc9DdK6boJ18LMp2AlyKASgYtPqY/edit#heading=h.bjyb6rg0pgjc), I understand the goal in using tabs atop the page is to reduce the number of items in the navigation.  However, this is not advisable for a couple of reasons:
* This pattern does not exist elsewhere in console.
* This pattern breaks the Search page (see video below).

https://github.com/openshift/console/assets/895728/69291d13-f04b-4cd5-9db1-ab2fd485685f

cc: @jhadvig, @spadgett

**Comment by upalatucci** [comment]
@rhamilto i can fix the search but for the first point i have to talk to the designer :-) THanks for the review

**Comment by yfrimanm** [comment]
Hi [@https://github.com/rhamilto], re your comment 
> This pattern does not exist elsewhere in console.

We found this as a solution that can reduce the number of pages under "Networking" and simplify the navigation. Adding too many pages would clutter the UI. 

Please note that only when Multus is installed will the two tabs be displayed together.

**Comment by jhadvig** [comment]
Hey @upalatucci, thank you for the PR!
From the design perspective I agree with @rhamilto that we should stick to pattern which is used across the console, by adding resources to their main navbar categories, iow. under the `Networking` section. 
Re:
> We found this as a solution that can reduce the number of pages under "Networking" and simplify the navigation. Adding too many pages would clutter the UI.

Here I would argue that:
- the Workloads section contains twelve resource and so far we havent got issue with usability. Same for `Compute` section
- if anything having the resources listed directly under the main section makes the UI more clear since its more visible to the users.
- we dont have any example of this type of tabbing in the console and I would rather not add it, since it would be a precedence

My suggestion would be to have the `NetworkPolicies` and `MultiNetworkPolicies`, both listed under the `Networking` section but separated by the divider (eg. as we have in `Compute` section)
Screenshot 2024-04-24 at 12 37 20

**Comment by upalatucci** [comment]
MultiNetworkPolicies is a resource that needs to be enabled by the cluster admin.
Is there a way to show the navbar item only when this feature is enabled? @jhadvig

**Comment by jhadvig** [comment]
>  I would go with just adding the NetworkPolicies and MultiNetworkPolicies, both listed under the Networking section one after the other.

ok, lets to that 👍 

Sorry for the the inconvenience, but we need to be strict about the design and user experience in the console repository, since its sets patterns for plugins creators.
That said if the network plugin would be a dynamic plugin then the design and behaviour would be solely up to you.

**Comment by rhamilto** [comment]
> Is there a way to show the navbar item only when this feature is enabled? @jhadvig

Yes.  You can make it optional based on a feature flag.  See https://github.com/openshift/console/blob/badb0c68d24e5516b65a465a3db8a5654f0c162e/frontend/packages/helm-plugin/console-extensions.json#L261-L263.

Use https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md#consoleflag, https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md#consoleflaghookprovider, or https://github.com/openshift/console/blob/master/frontend/packages/console-dynamic-plugin-sdk/docs/console-extensions.md#consoleflaghookprovider to set the flag depending on your use case.

**Comment by rhamilto** [comment]
QA Approver:
/assign @yapei
Docs Approver:
/assign @opayne1
PX Approver:
/assign @RickJWagner

**Comment by yapei** [comment]
@gouyang will verify the changes

**Pull request merged**
