### PR TITLE
Bug 1669300 - Fixing provider name of operators

### PR DESCRIPTION
**Pull request by galletti94**
Bug 1669300

Fixes [Bug 1669300](https://bugzilla.redhat.com/show_bug.cgi?id=1669300)

/cc @jeff-phillips-18 @alecmerdler @spadgett

### CODE REVIEW

**Comment by galletti94** [comment]
Realized provider was in status of packagemanifest not in metadata. Could I get an lgtm again @alecmerdler @jeff-phillips-18 @spadgett ?

Side Note: why is the provider label in metadata different from the provider name in status @alecmerdler ?

**Comment by alecmerdler** [comment]
@galletti94 The `status.provider` is mapped from the CSV `spec.provider` ([code](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/package-server/apis/packagemanifest/v1alpha1/packagemanifest.go#L11)). The `metadata.labels` are simply copied from the `CatalogSource` ([code](https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/package-server/provider/registry.go#L292)).

**Comment by jhadvig** [comment]
Test failuer:
`NoSuchElementError: No element found using locator: by.cssContainingText(".co-resource-list__item", "etcd")
`
/test console-e2e

**Comment by spadgett** [comment]
```
NoSuchElementError: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, .catalog-tile-pf)
```

/retest

**Comment by spadgett** [comment]
```
level=error msg="1 error occurred:"
level=error msg="\t* module.vpc.aws_route.to_nat_gw[5]: 1 error occurred:"
level=error msg="\t* aws_route.to_nat_gw.5: Error creating route: timeout while waiting for state to become 'success' (timeout: 2m0s)"
```

/retest

**Comment by spadgett** [comment]
```
NoSuchElementError: Index out of bound. Trying to access element at index: 0, but there are only 0 elements that match locator By(css selector, .catalog-tile-pf)
```

/retest

**Comment by jhadvig** [comment]
install error
/retest

**Comment by spadgett** [comment]
@galletti94 can you confirm that the OLM tests pass locally for you?

**Comment by galletti94** [comment]
@spadgett all tests pass for me locally

**Comment by galletti94** [comment]
Waiting on #1255 to merge

**Pull request merged**
