### PR TITLE
PF Update to 2021-6

### PR DESCRIPTION
**Pull request by jcaianirh**
Update pf packages to the latest release: 2021-6.

### CODE REVIEW

**Comment by christianvogt** [comment]
This update will fix https://issues.redhat.com/browse/ODC-5797
cc @abhinandan13jan

**Comment by jcaianirh** [comment]
> /hold for pf fix for [patternfly/patternfly-react#5788](https://github.com/patternfly/patternfly-react/issues/5788)

verified fixed with updated packages

**Comment by jcaianirh** [comment]
> This update will fix https://issues.redhat.com/browse/ODC-5797
> cc @abhinandan13jan

verified this is fixed with the update:

Screen Shot 2021-05-17 at 11 33 03 AM

**Review by dtaylor113 — APPROVED** [review]
/lgtm

**Comment by jcaianirh** [comment]
/hold cancel
issues fixed

**Review by sg00dwin — APPROVED** [review]

**Review by spadgett — APPROVED** [review]
/approve

**Review by zherman0 — APPROVED** [review]

**Review by spadgett — APPROVED** [review]
/lgtm

**Pull request merged**
