### PR TITLE
[release-4.10] OCPBUGS-6754: Fix for initial showing of topology contents

### PR DESCRIPTION
**Pull request by jerolimov**
This is a manual cherry-pick of @jeff-phillips-18 PR #12311

/cc @jeff-phillips-18 @vikram-raj 
/kind bug

### CODE REVIEW

**Review by vikram-raj — APPROVED** [review]
Verified it on the cluster bot.
/lgtm
Peek 2023-02-03 15-47

**Review by jeff-phillips-18 — APPROVED** [review]

**Pull request merged**
