### PR TITLE
OU-229: Remove Observe > Targets page code

### PR DESCRIPTION
**Pull request by kyoto**
This page is now provided by the `monitoring-plugin` dynamic plugin and nothing in the console codebase is using these components.

### CODE REVIEW

**Comment by kyoto** [comment]
This is a refactoring change. There should be no user visible changes.

/label docs-approved
/label px-approved

**Review by zhuje — APPROVED** [review]

**Comment by zhuje** [comment]
Do you think we need to add `"Targets" : "Targets"` back into `frontend/public/locales/en/public.json`?

The `ci/prow/e2e-gcp-console` error mentioned "Failed: Missing i18n key "Targets" in namespace "public" and language "en." exception Error: Failed: Missing i18n key "Targets" in namespace "public" and language "en." "

**Comment by kyoto** [comment]
@zhuje Thanks! I had missed that error message.
I think this is the necessary fix: https://github.com/openshift/monitoring-plugin/pull/73

**Review by zhuje — APPROVED** [review]

**Comment by Tai-RedHat** [comment]
test PR with cluster bot, failed to see Ovserve page as admin

https://github.com/openshift/console/assets/99250368/c627ea67-bdf5-477b-be85-9fdf9756b861

**Comment by juzhao** [comment]
@Tai-RedHat from the screen recording, you used 4.15 payload to test this PR, the master branch is 4.16 now. cc: @kyoto

**Comment by Tai-RedHat** [comment]
> @Tai-RedHat from the screen recording, you used 4.15 payload to test this PR, the master branch is 4.16 now, I am afraid this is the reason that the test did not pass. cc: @kyoto

yes, it's a payload issue.

**Comment by Tai-RedHat** [comment]
test with cluster-bot 4.16 build, Observe pages worked well.
/label qe-approved

**Comment by kyoto** [comment]
This PR is still causing an error with "Targets" not being available in the i18n files. To fix we probably want something like https://github.com/openshift/monitoring-plugin/pull/73, but that caused CI failures so we will need to figure out the issue there.

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Pull request closed without merging**
