### PR TITLE
HELM-532: Sort on basis of Chart Version

### PR DESCRIPTION
**Pull request by Kartikey-star**
Default sorting is by logical semver, with latest being the bottom of the list (default selected) and top of the list being the oldest chart.

### CODE REVIEW

**Review by lokanandaprabhu — APPROVED** [review]

**Comment by lokanandaprabhu** [comment]
Tested using cluster bot. Working fine.


https://github.com/openshift/console/assets/102503482/365f21c1-961e-48bd-952e-46efdceeb75c

**Comment by sanketpathak** [comment]
Verified with admin and non-admin users
Screenshot 2024-05-14 at 6 56 42 PM
/label qe-approved

**Review by dperaza4dustbit — APPROVED** [review]
/lgtm

**Pull request merged**
