### PR TITLE
Add console version to about modal

### PR DESCRIPTION
**Pull request by honza**
This would help with testing the console code.

### CODE REVIEW

**Comment by spadgett** [comment]
/hold

The version string will not be the right value. Is there a reason you can't use the console ClusterOperator to tell the version?

**Comment by spadgett** [comment]
Is it the commit you need to see?

**Comment by honza** [comment]
Here is the actual, real-life scenario that prompted this PR. Console development moves a lot faster than the cluster parts. As such, testers need to run the console locally in order to see latest changes and to verify them. The console UI should display its own version. This will make it explicit that you're accessing the right instance (local vs in-cluster). It's also helpful for bug reports.

**Comment by spadgett** [comment]
> Here is the actual, real-life scenario that prompted this PR. Console development moves a lot faster than the cluster parts. As such, testers need to run the console locally in order to see latest changes and to verify them. The console UI should display its own version. This will make it explicit that you're accessing the right instance (local vs in-cluster). It's also helpful for bug reports.

QE should not be testing a local console. We have frequent developer releases (several each day), so there isn't really a reason that we can't test an in-cluster console.

This is going to be extremely confusing for real users since it will show a completely different version that what's reported by the operator and the cluster version.

/close

**Comment by spadgett** [comment]
If you use the Report Bug link in console, it will prefill the correct version in the bug report, and we should only be testing the in-cluster console.

**Pull request closed without merging**
