### PR TITLE
OCPBUGS-10562: fix operator uninstall test

### PR DESCRIPTION
**Pull request by rhamilto**
I was finally able to debug and fix this as a result of [the Cypress upgrade work](https://github.com/openshift/console/pull/13070).  I am choosing to remove the problematic test while cleaning up a few other issues I noticed in the process.

### CODE REVIEW

**Comment by rhamilto** [comment]
/hold

For https://github.com/openshift/console/pull/13070 to merge first.

**Comment by rhamilto** [comment]
@TheRealJon, mind reviewing?

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Pull request merged**
